### ISSUE TITLE
Need runtime option to emit errors via stderr instead of as pop-ups

### ISSUE THREAD

**Issue by jflorian** [TigerVNC/tigervnc#1]
Controlling vncviewer via another application is problematic due to certain pop up messages that can occur. One example I'm aware of is _read: Connection reset by peer (104)_, though there may be others. When vncviewer is wrapped with another app, the whole experience would be improved if the wrapper app could capture the error message if emitted via stderr. Furthermore, it's troublesome that vncviewer blocks for user acknowledgement when this occurs. **In kiosk-like environs, the user may not have any way of dismissing the pop-up.**
##

**Comment by CendioOssman** [comment]
We have a setting for this for the fatal ones, so I'll go ahead and close this for now. Any other popups would need a more specific scenario.

**Comment by jflorian** [comment]
> We have a setting for this for the fatal ones

Great.  What's the name of that setting?

**Comment by CendioOssman** [comment]
It is called `alertOnFatalError`.
