### ISSUE TITLE
Sudo password window not showing

### ISSUE THREAD

**Issue by dsardelic** [TigerVNC/tigervnc#1001]
Host and client have the same configuration:
 - OS: Linux Mint 19.3 x64 Cinnamon edition
 - VNC client: TigerVNC
 - VNC client version: 1.10.1
 - Files extracted and manually installed from the official tar.gz binary

Hi guys! TigerVNC is amazing, but I'm experiencing a rather irritating issue (basically two issues, but the second one wouldn't bother me were it not for the first one). The steps to reproduce the issue are as follows:

1) Log in on the host, thus creating a "primary" desktop environment session on the host.
2) Start the vncserver on the host (vncserver :1 -PasswordFile <password file path>)
3) Start the vncviewer on the client (xtigervncviewer HOST:1 -PasswordFile <password file path>)
4) On the remote host in the VNC session window open the "Start menu" and select an application that requires entering the sudo password before it can be run (e.g. Synaptics package manager).

After step 4 the computer would normally show me a dedicated window where I would need to input the sudo password to proceed. And this is exactly what happens when I use x0vncserver. However, when using vncserver no window appears and the session just goes on seemingly normally, as if nothing happened. The password window is there somewhere, it is displayed in the "primary" session on the host's monitor even as the VNC session goes further on, but it's like it is somehow out of vncserver's sight.

Is this expected behavior? You can imagine how this prevents one from efficiently managing the remote host. I therefore use the x0vncserver and it works very well, except that clipboard sharing does not work in either direction. Somewhat irritating but tolerable. I haven't yet tested that scenario, but what would happen when at startup the host would initiate a CLI session only, so no DE sessions would be initialized until the first VNC session? Would the password window behavior be the same?

I use what I've googled to be a basic xstartup file script:
#! /bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec dbus-launch cinnamon-session

I am the only computer user and hence a sudoer. Both the host and the client are in the same private network.

**Comment by CendioOssman** [comment]
That should normally work find, but unfortunately it is something that is mostly outside of our control. Please try the latest nightly build as it has a new way of starting sessions that should hopefully be more compatible with things. If that still doesn't work then I'm afraid I'll have to direct you to report a bug with Linux Mint.
