### ISSUE TITLE
TigerVNC for Win7 embedded

### ISSUE THREAD

**Issue by bira19** [TigerVNC/tigervnc#1002]
**Is your feature request related to a problem? Please describe.**
A I am facing issue when trying to use TigerVNC on Windows 7 embedded. Have been noticing some strange issues. Like, after configuring the Server, I ran viewer on the Server itself (using localhost to connect). But, it says no password was found. Checked the Registry, but there was not entry. I did the same steps on Windows 10 and it worked fine.

**Describe the solution you'd like**
A If there is any older version that I could use for Win 7 embedded, please direct me there. If not, then it's added support could really be useful.

**Describe alternatives you've considered**
A I have only found the Certificate based Authentication (that I required) only with TigerVNC. So, no alternatives as of now.

**Comment by CendioOssman** [comment]
Sorry, I'm afraid embedded is not something we have access to for development. It wouldn't surprise me if it lacks some functionality that we require. Unfortunately there isn't much we can do unless a developer steps up with access to such a system. Sorry. :/
