### ISSUE TITLE
Strange cursor pointer shapes on Win10 viewer

### ISSUE THREAD

**Issue by trantham** [TigerVNC/tigervnc#1004]
My TigerVNC Viewer for Windows 10 has some bizarre cursor shapes (see the triangle [wedge] and the T in the attached photos).  

![IMG_20200423_210116](https://user-images.githubusercontent.com/13106079/80168837-8e349780-85a9-11ea-84b5-c776df0b38d6.jpg)
![IMG_20200423_210242](https://user-images.githubusercontent.com/13106079/80168845-94c30f00-85a9-11ea-9bf4-9b7d8f0560db.jpg)

The issue is not present on older TigerVNC builds prior to 1.8 (1.7.1 cursor appears normal), but everything through 1.10.80 is showing the issue.  I tried deleting the FLTK.org and vnc appdata folders.  

Any suggestions on how to debug or fix this (other than going back to 1.7.1)?

**Comment by CendioOssman** [comment]
That's when we implemented support for RealVNC's alpha cursors. So there seems to be something off there. Does it work with a TigerVNC server?

**Comment by trantham** [comment]
Connecting to a TigerVNC server does not work.  It authenticates without error, but there is no response following authentication.  I ran it from a command line with logging enabled and captured the following log file:

Fri Apr 24 08:51:14 2020
 DecodeManager: Detected 8 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to 10.2.28.41 [10.2.28.41] port 5900
 CConn:       Connected to host 10.2.28.41 port 5900
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Server offers security type VncAuth(2)
 CConnection: Choosing security type VeNCrypt(19)
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CVeNCrypt:   Server offers security type TLSVnc (258)
 CConnection: processing security message
 CVeNCrypt:   Server offers security type VncAuth (2)
 CVeNCrypt:   Choosing security type TLSVnc (258)

Fri Apr 24 08:51:15 2020
 CConnection: processing security message
 TLS:         Anonymous session has been set
 CConnection: processing security message
 CConnection: processing security message
 TLS:         TLS handshake completed with
              (TLS1.2)-(ANON-ECDH)-(AES-256-CBC)-(SHA1)

Fri Apr 24 08:51:17 2020
 CConnection: processing security result message
 CConnection: processing security result message
 CConn:       End of stream

**Comment by trantham** [comment]
I tried installing alpha cursors on my machine, but that did not help.

**Comment by CendioOssman** [comment]
That's odd. Can you check the server log? And how was the server setup and started?

**Comment by CendioOssman** [comment]
And so we can try reproducing it here, what server are you running when seeing this issue? We need to know the exact version and how it was setup so we can try to do the same here.

**Comment by trantham** [comment]
The server had x11vnc  V0.9.14 (which was old).  I tried updating all the Arch packages (pacman -Syu) on the server and refreshing its font cache (sudo fc-cache -f-v, sudo fc-cache -rs), but the system did not respond after a sudo restart now.  I won't be able to see what's happening with it until this weekend - unless I can get a maintenance technician to look at it.

**Comment by CendioOssman** [comment]
Alright. Let us know if the issue still remains once the machine is updated and back up and running. Hopefully it's a bug that's already been resolved in a newer x11vnc.

**Comment by trantham** [comment]
Updating fonts and refreshing font cache corrected the issue.  Viewer works fine with x11vnc.  Thanks for your help!
