### ISSUE TITLE
not working to connect to raspbian buster

### ISSUE THREAD

**Issue by boistordu** [TigerVNC/tigervnc#1005]
**Describe the bug**
RealVnc is the default vncviewer in raspbian buster
Apparently your viewer isn't recognizing the security options so we got a message of `no matching security types`

there is nothing in the logs that would suggest a problem on the server.
Thanks to the RealVnc viewer I've seen there was a generation of keys at each conneciton maybe it's that? 

**Client (please complete the following information):**
 - OS: [e.g. Windows 8.1] windows 10
 - VNC client: [e.g. TigerVNC, or UltraVNC] tigervnc
 - VNC client version: [e.g. 1.8.0] 1.0.1
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1] raspbian buster on rasp 4
 - VNC server: [e.g. TigerVNC, or UltraVNC] realvnc
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver`] default fresh configuration and also with vncserver -Encryption PreferOff -Authentication VncAuth

**Additional context**

**Comment by CendioOssman** [comment]
Could you share what the log from the client says?

**Comment by boistordu** [comment]
where would that be on the windows client version?

**Comment by CendioOssman** [comment]
Please see the wiki for how to get the log on Windows:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs

**Comment by CendioOssman** [comment]
No response. Closing.
