### ISSUE TITLE
CTRL and ALT keys not working consistently on MacBook.

### ISSUE THREAD

**Issue by countofsanfrancisco** [TigerVNC/tigervnc#1007]
**Describe the bug**
I am on a Macbook. I am using TigerVNC viewer to VNC to a xVNC server which is running on RHEL 7.6. The  VNC server and xVNC server is what comes with RHEL 7.6. My Tiger VNC is 1.10.1 64-bit.

My MacOS is the Catalina 10.15.4.

When I press combinations like ALT+TAB, or ALT+CTRL+up-arrow or ALT+CTRL+down-arrow or ALT+CTRL+SHIFT+(up or down arrow), they don't work all the time. In fact, they seldom work but they do work at times, if I am lucky.

I have xVNC only accept TLSVnc connection as the Security Type.

On a Macbook, the ALT is the Option key.

Any help to root cause the problem would be greatly appreciated.

**To Reproduce**
See details above.

**Expected behavior**
I expect the key combination to work all the time.

**Screenshots**
None

**Client (please complete the following information):**
See details above.

**Server (please complete the following information):**
 See details above.

**Additional context**

**Comment by CendioOssman** [comment]
Could you try using the Command key instead and see if that works? We shuffle those keys around a bit on macOS as Alt/Option doesn't behave quite like it does on other systems and it tends to confuse servers. Details here:

https://github.com/TigerVNC/tigervnc/wiki/Keyboard-shortcuts

**Comment by countofsanfrancisco** [comment]
I see. I didn't realize that. Thanks for the info.

This works when I go into full screen mode but doesn't when it is a normal window. This is because the CMD key is not sent to the windowed view because MacOS traps that.

Can we have the ability to make the OPTION key behave like the CMD key in windowed (i.e. not full screen)? I like that the CMD + Tab key combo can still switch between my other MacOS apps so allowing me to use OPTION as the CMD allows me to switch between apps on the Xvnc server (i.e. Linux apps in my case).

**Comment by CendioOssman** [comment]
I'm afraid we don't have that feature right now. Please see #2 and #835. Also see the server `-RemapKeys` setting.
