### ISSUE TITLE
After updating tigerVNC from v1.10.0 to v1.10.1 NoVNC is unable to connect

### ISSUE THREAD

**Issue by tokariu** [TigerVNC/tigervnc#1010]
I have the following setup:
Win10 1909 x64, noVNC v1.1.0 - hosted by a localhost apache webserver and node-websockify. apache is reverse proxying vnc traffic via websockets to TigerVNC v1.10.x x64 - running as a local windows service.

The Setup worked perfectly without issues prior to TigerVNC v1.10.1, before I applied the security update.
After updating TigerVNC from 1.10.0 ---> 1.10.1 noVNC suddenly fails to make a connection.
After reverting the update, uninstalling TigerVNC 1.10.1 and installing 1.10.0 again, noVNC is immediately able to make the connection.
The TigerVNC config didn't change while installing/uninstalling, all settings were the same.

Something has changed in TigerVNC v1.10.1 that prevents noVNC making connections.

**To Reproduce**
1. create above setup with noVNC, TigerVNC, apache/websockify reverseproxy.
2. switch between TigerVNC version v1.10.0 and v1.10.1
3. see that noVNC is unable to make new connections with v.1.10.1
4. uninstall v1.10.1, install v1.10.0
5. see noVNC will work again without doing anything else.

**Expected behavior**
TigerVNC v1.10.1 should work with noVNC exactly like v1.10.0 and lower.
We should be able to install the security update without losing functionality.

**Screenshots**

browser console log of NoVNC connecting to TigerVNC 1.10.**0**, working:

![TigerVNC 1 10 0](https://user-images.githubusercontent.com/7195846/80839674-fe6f9880-8bfb-11ea-80f4-8cbc8562e22c.png)

browser console log of NoVNC connecting to TigerVNC 1.10.**1**, failed:

![2020-05-01_22-30-32](https://user-images.githubusercontent.com/7195846/80839820-41317080-8bfc-11ea-9401-29d804eacef9.png)

TigerVNC security settings (unchanged in both versions)
![Zwischenablagebild (11)](https://user-images.githubusercontent.com/7195846/80839921-7473ff80-8bfc-11ea-84dc-5539873c56fb.png)

**Comment by tokariu** [comment]
came to the tigerVNC google discussion group by accident and found the info that there is a nightly which probably fixes the issue:

http://tigervnc.bphinz.com/nightly/ -> tigervnc64-1.10.80.exe

this version fixes the issue for me.

maybe this nightly should already be released, what could be worse than a not functioning tigervnc 1.10.1 ?

**Comment by CendioOssman** [comment]
TigerVNC has more components than WinVNC which also need to be considered. Unfortunately WinVNC is currently more of a bonus rather than a core component as it lacks a maintainer.

Closing this issue as this has been fixed and is just waiting for a release.
