### ISSUE TITLE
Difference between tigervnc & vnc4server

### ISSUE THREAD

**Issue by athenawisdoms** [TigerVNC/tigervnc#1017]
Hi, I hope this is the right place to ask this question!

Looking at the docs for [`vnc4server`](https://manpages.debian.org/testing/vnc4server/vnc4server.1) and for [`tigervnc-standalone-server`](https://tigervnc.org/doc/vncserver.html), they both appear to be very similar and have common authors such as *Tristan Richardson, RealVNC Ltd*.

What is the difference between installing `vnc4server` and `tigervnc-standalone-server` on an Ubuntu system? Are both TigerVNC servers?

**Comment by CendioOssman** [comment]
TigerVNC is based on RealVNC 4, so there are a lot of similarities. However TigerVNC has had  14 years of development on top of RealVNC, so it has a lot more features and fixes.

Hope this answers your question.
