### ISSUE TITLE
vncviewer - allow wm window class or title being set

### ISSUE THREAD

**Issue by cherusk** [TigerVNC/tigervnc#1018]
**Is your feature request related to a problem? Please describe.**

For integrating well with sway processing, which relies on window names/classes/ids, would be great to have a parameter to influence one of those for the vncviewer client viewer window being spawned for each connection.

**Describe the solution you'd like**
Parameter allowing for setting either or window names/classes/id , ideally all for separate vnc connections done with vncviewer client.

**Describe alternatives you've considered**
Using other vnc clients.

**Comment by CendioOssman** [comment]
The class is unfortunately used by desktop environments to identify applications, so we cannot modify that. Window title might be feasible though.

Part of the window title comes from the session though. Have you looked at setting it that way?

And I'm not familiar with sway processing. Do you think you could elaborate on your scenario so we can get a better understanding of what you are trying to achieve?

**Comment by cherusk** [comment]
> The class is unfortunately used by desktop environments to identify applications, so we cannot modify that. Window title might be feasible though. 

That's fairly what I want to achieve, identify the window, with sway, a wm [1].

E.g.:


Nigh, think we can close here, as reminna does set enough specifics. Will go with that client.

[1] https://github.com/swaywm/sway
