### ISSUE TITLE
Is there any way to connect to PCs over internet and not local?

### ISSUE THREAD

**Issue by tungstenboy** [TigerVNC/tigervnc#1019]
I'm trying to connect to a friend's PC using TigerVNC. Is there anyway to do this?

**Comment by CendioOssman** [comment]
Probably. Is this a Windows machine? If so then he needs to install and configure our Windows server (it's in the Windows installation program). Then he needs to make sure it's reachable by you, i.e. configure any firewalls in the way.

If it's just for a quick remote assistance then TigerVNC is probably overly complex for that and I would suggest chrome or team viewer or something like that.

Also note that we unfortunately have an issue with the Windows server in the latest release, so please use a nightly build.
