### ISSUE TITLE
tigervnc-server on Raspbian 'buster'

### ISSUE THREAD

**Issue by jejo86** [TigerVNC/tigervnc#1022]
I have the following `/home/pi/.vnc/xstartup` file (on my RaspberryPi with raspbian as an OS), which is the default content having replaced `exec startx` with `exec /usr/bin/startlxde`:

```
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec /usr/bin/startlxde
```

I try to start the tigervnc-standalone-server (1.9.0+dfsg-3+deb10u1) via the command `vncserver :1 -fg -localhost no -rfbauth ~/.vnc/passwd`.

```
vncserver :1 -fg -localhost no -rfbauth ~/.vnc/passwd

New 'raspberrypi:1 (pi)' desktop at :1 on machine raspberrypi

Starting applications specified in /home/pi/.vnc/xstartup
Log file is /home/pi/.vnc/raspberrypi:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/pi/.vnc/passwd raspberrypi:1 to connect to the VNC server.
```

When I connect on Linux Mint 19.3 with tigervnc-viewer (1.7.0+dfsg-8ubuntu2) via the command 
```
xtigervncviewer -SecurityTypes VncAuth,TLSVnc raspberrypi:1

TigerVNC-Betrachter (64-bit) Version 1.7.0
Erstellt auf: 2017-12-05 09:25
Copyright (C) 1999-2016 TigerVNC Team und viele andere (siehe README.txt)
Copyright (C) 2005 Klaus Franken, StrukturPunkt
Siehe http://www.tigervnc.org für Informationen über TigerVNC.

Tue May 19 22:21:44 2020
 DecodeManager: Detected 2 CPU core(s)
 DecodeManager: Creating 2 decoder thread(s)
 CConn:       verbunden mit Rechner raspberrypi, Port 5901
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VeNCrypt(19)
 CVeNCrypt:   Choosing security type VncAuth (2)
``` 
I am prompted for the password. Entering the password, the client crashes immediately with the output:
```
Tue May 19 22:21:57 2020
 CConn:       End of stream
```
and the server on the raspberrypi with the output:
```
vncserver: Failed command '/home/pi/.vnc/xstartup': 256!

=================== tail -15 /home/pi/.vnc/raspberrypi:1.log ===================
Tue May 19 22:21:44 2020
 Connections: accepted: [fd00::b65f:bef8:1186:aacc]::56882
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type VncAuth (2)
terminate called after throwing an instance of 'rdr::Exception'
terminate called recursively
(EE) 
(EE) Backtrace:
(EE) 
(EE) 
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE) 
Killing Xtigervnc process ID 32077... which seems to be deadlocked. Using SIGKILL!

================================================================================

Starting applications specified in /home/pi/.vnc/xstartup has failed.
Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
```

The entire logs are attached:
[/home/pi/.vnc/raspberrypi:1.log](https://github.com/TigerVNC/tigervnc/files/4653044/raspberrypi.1.log)
[/home/pi/.cache/lxsession/LXDE/run.log](https://github.com/TigerVNC/tigervnc/files/4653045/run.log)

Is it a problem with LXDE or tigervnc?

**Comment by CendioOssman** [comment]
I'm afraid this is a Debian bug that we cannot do much about. Please see #800 and #895. There are links there to the Debian bug reports where you can continue getting help.

**Comment by jejo86** [comment]
Thanks, you pointed me into the right direction! Setting the view-only password serves as a workaround for the [apparent problem in libunwind8](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923962#15).

# Workaround

If anyone reads this: Run `vncpasswd` and confirm with `y` when asked to create a view-only password!:
```
pi@raspberrypi:~ $ vncpasswd
Password:
Verify:
Would you like to enter a view-only password (y/n)? y
Password:
Verify:
```
## Additional Hint

Additionally use `startlxde-pi`, to get the same desktop as in the 'real' session. The full `/home/pi/.vnc/xstartup` should therefore look like this:
```
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec /usr/bin/startlxde-pi
```
