### ISSUE TITLE
VncAuthPasswdParameter contains private inheritance

### ISSUE THREAD

**Issue by chraac** [TigerVNC/tigervnc#1024]
https://github.com/TigerVNC/tigervnc/blob/3aab38257ec93a17a1380efb5b71e50d94b6a4cd/common/rfb/SSecurityVncAuth.h#L44

As we can see above, there is no access specifier before BinaryParameter, so the compiler assume that is private.

> In the absence of an access-specifier for a base class, public is assumed when the derived class is defined with the class-key struct and private is assumed when the class is defined with the class-key class.
> class B { /* ... */ };
> class D1 : private B { /* ... */ };
> class D2 : public B { /* ... */ };
> class D3 : B { /* ... */ };             // B private by default
> struct D4 : public B { /* ... */ };
> struct D5 : private B { /* ... */ };
> struct D6 : B { /* ... */ };            // B public by default
> class D7 : protected B { /* ... */ };
> struct D8 : protected B { /* ... */ };

Reference:
[Accessibility of base classes and base class members](http://eel.is/c++draft/class.access.base)

**Comment by CendioOssman** [comment]
Doesn't seem to be an issue though. Are you seeing some practical problem from this?

**Comment by chraac** [comment]
> Doesn't seem to be an issue though. Are you seeing some practical problem from this?

Thanks for replying, and it' ll prevent user to call some member function inheritance from BinaryParameter like  setParam, etc.

And if that's and intentional omission, then I'll close the issue.

**Comment by CendioOssman** [comment]
I'd say probably. The class is supposed to be used via `getVncAuthPasswd()`.
