### ISSUE TITLE
Could not connect to session bus : Failed to connect to socket /tmp/dbus- ....

### ISSUE THREAD

**Issue by AKDali** [TigerVNC/tigervnc#1025]
Hello, 
I did install TigerVNC on a Linux server (centos rhel). 

I installed on a remote computer TigerVNC client, all is working well through SSH Tunnel 

When I stop server and restart it (server gets new IP), client can no more connect to server and message on client after passwd authentification is "Could not connect to session bus : Failed to connect to socket /tmp/dbus- ....:Connection refused.

VNC Server is running, I could not troubleshoot and correct. Any idea on how to re-initialize client connection ?

Thank you

**Comment by CendioOssman** [comment]
That generally means the session isn't started correctly. Could you try a nightly build? We've redesigned the session startup there to better support current systems.

**Comment by AKDali** [comment]
Thanks, I could gather additional info from server log file (<ip address>:1.log in .vc/ folder) after restarting server :
"
Wed May 20 11:15:07 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
mate-session[4260]: WARNING: Could not make bus activated clients aware of XDG_CURRENT_DESKTOP=MATE environment variable: Could not connect: Connection refused
mate-session[4260]: WARNING: Could not make bus activated clients aware of DISPLAY=:1 environment variable: Could not connect: Connection refused
mate-session[4260]: WARNING: Could not make bus activated clients aware of MATE_DESKTOP_SESSION_ID=this-is-deprecated environment variable: Could not connect: Connection refused
mate-session[4260]: dconf-WARNING: failed to commit changes to dconf: Could not connect: Connection refused
mate-session[4260]: WARNING: Could not make bus activated clients aware of SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/4260,unix/unix:/tmp/.ICE-unix/4260 environment variable: Could not connect: Connection refused
Gtk-Message: 11:15:11.901: GtkDialog mapped without a transient parent. This is discouraged.
"

**Comment by CendioOssman** [comment]
Is that log output from a nightly build or from the CentOS version?

**Comment by CendioOssman** [comment]
No response. Closing.
