### ISSUE TITLE
Connection refused 111

### ISSUE THREAD

**Issue by joezhou099** [TigerVNC/tigervnc#1027]
Hi, i used vncserver -localhost＝no to create a session. When i used vncviewer to connect it, it reported the connection refused 111. Also, i noticed that the port number did not change when i created a new session. Normally, when i executed vncserver, it is supposed to open new ports every time. Pls help!

**Comment by CendioOssman** [comment]
Have you checked the log file for the server? Perhaps it failed to start correctly.

**Comment by CendioOssman** [comment]
No response. Closing.
