### ISSUE TITLE
Closing VNC Client Window crashes server

### ISSUE THREAD

**Issue by jejo86** [TigerVNC/tigervnc#1030]
With [1022](https://github.com/TigerVNC/tigervnc/issues/1022) being solved, a new issue arised.

# Problem Description

I am now startig the `vncserver` without the `-fg` in order to be able to reconnect at a later time.

```
vncserver :1 -localhost no -rfbauth ~/.vnc/passwd -useold
``` 
Connecting to the server via `xtigervncviewer -SecurityTypes VncAuth,TLSVnc raspberrypi:1` works as expected. When closing the viewer, I cannot reconnect to the previous session calling the same command.

The server has become stale:

```
pi@raspberrypi:~/.vnc $ vncserver -list

TigerVNC server sessions:

X DISPLAY #	RFB PORT #	PROCESS ID
:1		5901		13499 (stale)
```

## Error Details in Log

The log file [/home/pi/.vnc/raspberrypi:1.log](https://github.com/TigerVNC/tigervnc/files/4669099/raspberrypi.1.log) shows an error:

```
Fri May 22 17:30:50 2020
 VNCSConnST:  FramebufferUpdateRequest 1900x1200 at 0,0 exceeds framebuffer
              1280x710
terminate called after throwing an instance of 'rdr::EndOfStream'
terminate called recursively
(EE) 
(EE) Backtrace:
(EE) 
(EE) 
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE) 
syswrite() on closed filehandle WH at /usr/bin/vncserver line 912.
```

## Commands do work in Principle

This problem does not occur on Linux Mint 19.3 with version `1.7.0+dfsg-8ubuntu2` of `tigervnc-standalone-server`.

## Possible Similarity

I found the bug [185](https://github.com/TigerVNC/tigervnc/issues/185), which seems to be similar but was supposed to be fixed in 9f03a09.

**Comment by CendioOssman** [comment]
I'm afraid this is a Debian bug that we cannot do much about. Please see #800 and tell Debian they need to get this issue resolved.
