### ISSUE TITLE
Mouse dragging does not work on Centos 6/7 tigervnc server 1.10+ vncviewer Windows10 

### ISSUE THREAD

**Issue by robertosussex** [TigerVNC/tigervnc#1033]
**Describe the bug**
Using vncviewer and attempting to use the mouse to move windows does not work
alt+space  does not work. Tabs around programs like xterm, matlab do no appear so very difficult to close them

**To Reproduce**
1. Use either Centos 6/7
2. Download tigervnc 1.10 x86_64 vncserver
3. Download any of the vnc viewer for windows

**Expected behavior**
I thought I could use the mouse to move windows around and/or close  the programs inside

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. Windows 10]
 - VNC client: [e.g. TigerVNC, or RealVNC  on Windows 10]
 - VNC client version: [e.g. 1.10.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Centos 6/7]
 - VNC server: [e.g. TigerVNC binary download ]
 - VNC server version: [e.g. 1.10.0]
 - Server was started using: [e.g. `vncserver`]

**Additional context**

**Comment by CendioOssman** [comment]
It sounds like your session has not started properly. Do you think you could attach a screenshot of what it looks like?

**Comment by robertosussex** [comment]
[cid:f8037296-4965-4bc6-86de-292e4aed0a47]


Hi there,

As you can see the xterm does not have tabs above its windows, If I try to touch it with the mouse I can neither resize nor move it. Same behaviour for most of the programs like matlab, mathematica (although gedit for instance does work better!) As a result it is also very difficult to terminate them and I can only do that with ctrl-Q.

Any advice ?

Roberto
________________________________

**Comment by robertosussex** [comment]
my xstartup is very simple and reads
#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xterm -geometry 80x24+10+10 -ls -title "VNCDESKTOP Desktop" &

I suspect there is something wrong with the xserver settings of the server machine although if I run xstartup directly on apollo2.hpc.susx.ac.uk the xterm appears fine ...

Best

Roberto
________________________________

**Comment by CendioOssman** [comment]
I'm afraid you cannot mail in images to Github. You'll need to use the web interface to add that screenshot.

**Comment by robertosussex** [comment]
![centos_vncviewer_screenshot](https://user-images.githubusercontent.com/37402138/82814706-8cebd880-9e8f-11ea-8ec3-4d57ba23b127.png)

**Comment by robertosussex** [comment]
Can you see it now ?
The xterm does not have tabs above its windows, If I try to touch it with the mouse I can neither resize nor move it. Same behaviour for most of the programs like matlab, mathematica (although gedit for instance does work better!) As a result it is also very difficult to terminate them and I can only do that with ctrl-Q.

Any advice ?

Roberto

**Comment by robertosussex** [comment]
I am not sure whether it has to do with the X11 settings on the server machine. Any tests I need to run ?

**Comment by samhed** [comment]
You don't have a window manager, that's the problem. Run your application together with something like openbox, compiz or metacity, and you should get what you're asking for.

**Comment by robertosussex** [comment]
Can you elaborate ? Where do I need to install the program? On the server I presume ?

**Comment by samhed** [comment]
Yes.

I'm not sure how you start the application you want to use, but I normally do something like this:

`DISPLAY=:50 metacity & DISPLAY=:50 xterm`

(in this case display 50 would be my VNC display)

**Comment by robertosussex** [comment]
So I can put openbox in my xstartup ?
R.

________________________________

**Comment by samhed** [comment]
Sounds good

**Comment by robertosussex** [comment]
Openbox-Message: A window manager is already running on screen 0
Do I have to stop other Xwindows manager first ?

**Comment by robertosussex** [comment]
rpm -qa |grep xorg-x11*
xorg-x11-xinit-1.3.4-2.el7.x86_64
xorg-x11-proto-devel-2018.4-1.el7.noarch
xorg-x11-server-utils-7.7-20.el7.x86_64
xorg-x11-fonts-Type1-7.5-9.el7.noarch
xorg-x11-xauth-1.0.9-1.el7.x86_64
xorg-x11-font-utils-7.5-20.el7.x86_64
xorg-x11-xkb-utils-7.7-14.el7.x86_64

**Comment by robertosussex** [comment]
Actually it works !!! with openbox in xstartup brilliant many thanks!
