### ISSUE TITLE
MaxDisconnectionTime option not working on ubuntu 20.04 (over xrdp)?

### ISSUE THREAD

**Issue by monkey-jsun** [TigerVNC/tigervnc#1042]
**Describe the bug**
This option has been working nicely with ubuntu 18.04.  I recently port it over ubuntu 20.04, and it stopped working.

tigervnc-standalone-server version is 1.10.1+dfsg-3.  xrdp version is 0.9.12-1. 

Xvnc -version
Xvnc TigerVNC 1.10.0 - built Apr  9 2020 06:49:31

**To Reproduce**
1. Launch an ubuntu 20.04 image from AWS
2. "sudo apt update; sudo apt install -y lxde xrdp tigervnc-standalone-server"
3. Modify /etc/xrdp/sesman.ini file and add following to [Xvnc] section
param=-MaxDisconnectionTime
param=120 
4. Launch an xrdp session, log in with Xvnc, and then close the client window (not logging out)
5. Exam the existence of Xvnc process by "pstree"
6. 2 minutes later (120sec), exam the existence of Xvnc process with "pstree"

**Expected behavior**
The Xvnc process should be killed 2 minutes later.  One can confirm by running "journalctl -fe" and see messages about terminating Xvnc.

**Client (please complete the following information):**
- end-user client is windows remote desktop
- local client is xrdp 

**Server (please complete the following information):**
- Ubuntu 20.04 on AWS

**Additional context**
1. While I reproduced this bug on AWS, I think it should be reproducible on any Ubuntu 20.04. 

2. Here is output from ps command:

ubuntu@ip-10-1-3-240:~$ ps -wwfaux | grep Xvnc
ubuntu     20770  0.0  0.0   8160   736 pts/1    S+   01:44   0:00              \_ grep --color=auto Xvnc
jsun       20066  0.0  3.6 452264 72308 ?        Sl   01:39   0:00      \_ Xvnc :10 -auth .Xauthority -geometry 1680x1050 -depth 24 -rfbauth /home/jsun/.vnc/sesman_passwd-jsun@ip-10-1-3-240:10 -bs -nolisten tcp -localhost -dpi 96 -MaxDisconnectionTime 120

3. for ubuntu 18.04 where this option works, here is the version output

Xvnc TigerVNC 1.7.0 - built Dec  5 2017 09:25:01

**Comment by monkey-jsun** [comment]
Just FYI.  The same procedure works fine on ubuntu 18.04 on AWS.

**Comment by CendioOssman** [comment]
From Xvnc's point of view it's xrdp that is the client, so the issue might simply be that it doesn't disconnect.

Could you share the log file for Xvnc?

**Comment by CendioOssman** [comment]
I'm afraid that did not include the log output from Xvnc. I'm not familiar enough with xrdp to know where it puts that unfortunately, so you'll have to figure that out yourself.

**Comment by monkey-jsun** [comment]
I can't seem to find the Xvnc logging output anywhere.  Strange.

Is there a way to direct the log output to a file?  I tried the following command with no avail.  Note I cannot use pipe to redirect the output since command is invoked from inside xrdp.  I can control the parameters xrdp uses.

Xvnc :10 -auth .Xauthority -geometry 1680x1050 -depth 24 -rfbauth /home/jsun/.vnc/sesman_passwd-jsun@ip-10-1-3-239:10 -bs -nolisten tcp -localhost -dpi 96 -MaxDisconnectionTime 120 -Log *:/tmp/js.log:100

**Comment by CendioOssman** [comment]
I'm afraid Xvnc doesn't support logging to file directly. xrdp seems to have its own logging file though. Have you checked that?

You could also try telling Xvnc to log to syslog by doing `-Log *:syslog:100`.

**Comment by monkey-jsun** [comment]
Thanks, Pierre.  Using syslog is a brilliant idea.  I think I will leave it there for production too.  

I'm able to capture the log from Xvnc.  See below. It looks like disconnect is detected, but 2 minutes later there is no timer event detected.

[xvnc.log](https://github.com/TigerVNC/tigervnc/files/4784469/xvnc.log)

**Comment by CendioOssman** [comment]
Thanks. It seems we broke this in 8e09912f9d66e5bef8146040b366286c661e3b53. Should be fixed again in 38726ce083db1a9227325bf87989513499bfa698.

Unfortunately I did not see any workaround. So please try the next nightly build, or wait for the upcoming release.
