### ISSUE TITLE
When I use gnuradio in remote access with tigervnc, the terminal outputs error: the X11 connection broke.

### ISSUE THREAD

**Issue by tinyxuyan** [TigerVNC/tigervnc#1044]
When I use gnuradio in remote access with tigervnc, the terminal outputs some error, and gnuradio can not run normally.

The detailed error is listed as below:
```
The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 22 (Invalid argument) on X server ":1.0"
      after 447 requests (443 known processed) with 0 events remaining.
```
I have posted the issue in gnuradio Github issue. And the gnuradio developer believes that the error is caused by remote access with X sever.

**server** 
 - OS:  Ubuntu 18.04 LTS
 - VNC client: TigerVNC

**client**
 - OS: Windows 10
 - VNC Viewer: 6.20.113

**Comment by CendioOssman** [comment]
That error means the application tried to send a X11 request that was larger than the server supports. So it usually means an application bug.

But let's first see if there is something odd with the request sizes on your system. Please run the following inside the VNC session: `xdpyinfo | grep -i request` and post the output here.

**Comment by tinyxuyan** [comment]
@CendioOssman I have switched to local access. Thank you for your reply.
