### ISSUE TITLE
F8 not working

### ISSUE THREAD

**Issue by MrErr** [TigerVNC/tigervnc#1046]
This probably isn't a bug, but I don't know now to fix the issue.

I am using tigervnc viewer version 64-bit v1.10.1 on windows and connecting to a centos server. For the past two days the hitting the F8 key has not brought up the menu.

Do any of you know what could be wrong?

**Comment by CendioOssman** [comment]
Could be many things, so let's start narrowing things down.

 * Do other F keys work inside the session?

 * Does your machine have an F lock that is set to the wrong mode?

 * Have you double checked the TigerVNC configuration which key is configured for the menu?

**Comment by MrErr** [comment]
Thank you!! It was the F lock key. Until today, I have never noticed the F Lock key.
