### ISSUE TITLE
Not taking keyboard input

### ISSUE THREAD

**Issue by akandGA** [TigerVNC/tigervnc#1050]
After opening vnc client I see my linux desktop to give userid and password for log-in as expected. However, it does not allow to give keyboard inputs and hence I can not get into the desktop.

**Comment by CendioOssman** [comment]
Please fill out the bug form so we can understand the context of your issue.

**Comment by akandGA** [comment]
Thanks for reply. I do not find any bug form to fill out. The attachment shows xstartup and config files (vnc1.zip). We have RHEL7.5. The process Xvnc shows:
webery    40212      1  0 11:14 pts/0    00:00:02 /usr/bin/Xvnc :1 -auth /home/webery/.Xauthority -desktop gpu01.cluster.com:1 (webery) -fp catalogue:/etc/X11/fontpath.d -geometry 1024x768 -pn -rfbauth /home/webery/.vnc/passwd -rfbport 5901 -rfbwait 30000

[vnc1.zip](https://github.com/TigerVNC/tigervnc/files/4838085/vnc1.zip)

**Comment by samhed** [comment]
When you create a new issue, you get a pre-formatted form that you're supposed to fill out. It includes essential information like what version of TigerVNC you are using.

**Comment by akandGA** [comment]
The tiger vnc version shows 1.8.0. Can I retrieve the bug fill out form? Need to mention, the machine I am intending to vnc is a gpu node and all drivers (nvidia, etc.) and gl libs are updated.

**Comment by samhed** [comment]
You will find the form here:
https://github.com/TigerVNC/tigervnc/issues/new?template=bug_report.md

**Comment by akandGA** [comment]
Thanks. It looks like after filling out it has opened a new case (#1051). Anyway, I have given the same title "Not taking keyboard input".
