### ISSUE TITLE
Multithreaded Xvnc

### ISSUE THREAD

**Issue by AAAPops** [TigerVNC/tigervnc#1052]
Currently, most users use a lot of multimedia in their daily work.
It makes Xvnc work more and more hardly. I need to have CPU about 3.0-3.5GHz to playback FullHD video. In that case Xvnc takes about 90-100% of one CPU core.

On the other side the typical mid-range server have quite a lot CPU cores but CPU frequency is less then 3.0GHz (I would say about 2.5GHz)
It means that users  feel very vell that they use remote desktop. 

What about to divide Xvnc on two thread:
first thread - X server
second thread - vnc (more precisely Tight Encoder Engine)

It will allow to spread CPU load more balanced.

**Comment by CendioOssman** [comment]
Generally not desirable to split it that way as both the X11 portion and the VNC portion wants to work with the framebuffer. So the two threads would end up waiting for each other.

What could probably be done is using several threads to encode a large update in parallel. I did a prototype of that but I had problems getting it to work properly. A simple implementation didn't do enough work on each thread to get the scheduler to ramp up the CPU frequency.

If someone would like to work on this then it would be very welcome. But I'd like to avoid having an issue open about it unless we have something more substantial than the fact that sometimes we run out of CPU power.
