### ISSUE TITLE
How can I start vncserver/client properly? There are many problems regarding display/login/authority/polkit etc.

### ISSUE THREAD

**Issue by sgon00** [TigerVNC/tigervnc#1053]
# Environment

OS: debian 10 (both client and server)
Client: tigervnc-viewer 1.9.0+dfsg-3+deb10u1
Server: tigervnc-standalone-server 1.9.0+dfsg-3+deb10u1
tigervnc-common 1.9.0+dfsg-3+deb10u1

# How do I run the server and client

## Server

simply execute `vncserver`, it will then create `~/.vnc` directory for me and related passwd file.

## Client

create ssh tunnel (port forwarding) to localhost 5901
and then `vncviewer localhost:5901`.
Because the server is running xfce enironment by defaut, so xfce desktop will be launched.
(Btw, it has lightdm too, but with the default configuration, xfce will be started automatically without lightdm)

## Problems

There are many problems when I use the vnc client. I think all should be fixable by changing some config files. OR maybe I should start vncserver differently. But I don't find any solutions yet online. The following are just some of them:

(1) I can not mount/automout USB devices. In thunar file manager, when I try to mount the USB filesystem manually, it will report the following error message in UI: `Failed to mount xxxx. Not authorized to perform operation (polkit authority not available and caller is not uid 0`

(2) I failed to execute `sudo gparted`, it will report error message in console: ` Gtk-WARNING **: 15:39:22.122: cannot open display: :1.0`.

(3) This is a small problem. When I launch terminal and filemanager thunar, the default path is `/`. But what I expect is `/home/$USER`. 

(4) login keyring can not be unlocked by default. When I start some apps which require keyring such as google-chrome, I have to enter the pasword. 

All the above problems do not happen if I don't use vnc client and use physical monitor/keyboard and login via lightdm.

I just tried tigervnc server and client for a few minutes. (googled solutons for more than 8 hours without any luck). The above is what I found during the few minutes trial (+ 8 hours googling). 

Thank you very much for your help.

**Comment by CendioOssman** [comment]
Debian has their own script for starting the VNC server, so I'm afraid it's not something we can support.

We've also done a lot of changes with regard to starting sessions in the upcoming version. Do you think you could try a nightly build? You'll find a link on our homepage.

**Comment by sgon00** [comment]
@CendioOssman Thank you very much for the quick reply. I didn't expect the response is this fast. 
I checked the homepage, it only provides nigthly binary builds for ubuntu, but not for debian.I don't want to compile anything from source at these days. So if I have to compile the nightly build, I don't feel I will do it. 
If this is debian related and not officially support, you can close this issue. 
Thanks a lot again.

**Comment by CendioOssman** [comment]
Right, I'm afraid we don't have any builds specific for Debian. What you can try is uninstalling the TigerVNC you've currently got, and unpacking the universal tar ball from our nightly builds.

**Comment by sgon00** [comment]
@CendioOssman Thanks a lot. I think I will simply close this issue.
