### ISSUE TITLE
TightDecoder: rectange too big

### ISSUE THREAD

**Issue by colemickens** [TigerVNC/tigervnc#1054]
**Describe the bug**
Is there a maximum size of display supported by tightvnc?

I can adjust the output I'm connecting to and it doesn't seem to like being over (approximately) 2000x1000 pixels. My monitor is 3440x1440, and would ideally like to use the entire display.

When I go past this size, I get an error:

`TightDecoder: Too large rectangle `

**Client (please complete the following information):**
 - OS: TigerVNC
 - VNC client: TigerVNC's vncviewer64.exe
 - VNC client version: [e.g. 1.8.0] latest nightly as of today
 - Client downloaded from: [e.g. my Linux distribution] tigervnc's recommended mirror/site

**Server (please complete the following information):**
 - OS: Linux
 - VNC server: wayvnc
 - VNC server version: current git head
 - Server downloaded from: built from source
 - Server was started using: `wayvnc -o HEADLESS-1 0.0.0.0`

**Comment by colemickens** [comment]
It looks like I can force another encoding type and it proceeds... How do I choose between these options?

**Comment by CendioOssman** [comment]
I'm afraid this is a server bug, so it isn't something we can do anything about. You'll need to report this to wayvnc/neatvnc. Please point them to this section in the specification:

> Tight encoding provides efficient compression for pixel data. To reduce implementation complexity, the width of any Tight-encoded rectangle cannot exceed 2048 pixels. If a wider rectangle is desired, it must be split into several rectangles and each one should be encoded separately.

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#tight-encoding
