### ISSUE TITLE
How to start mate-session correctly by using /home/janusz/.vnc/xstartup

### ISSUE THREAD

**Issue by JanuszChmiel** [TigerVNC/tigervnc#1055]
Dear specialists,
I have tried to simply add mate-session to The 
/home/janusz/.vnc/xstartup
but mate-session did not start at all. Tigervnc did not crashed, but mate-session have not been loaded to RAM.
So I must still start it by typing
mate-session
Wich trick must be done so The script
/home/janusz/.vnc/xstartup
Will really load mate-session to memory and mate desktop environment will run?
I Am very very nicely surpriced because of The quality of Tigervnc. Even without shared memory its speed is amazing and stability is outstanding. Very very well done.
Tigervnc is Fully compatible with ANdroid Termux, Proot and some running Linux distribution. XKB protocol is fully compatible ith Orca screen reader which can be perfectly used.
I have previously used Xorg, xinit and x11vnc. But I think, that Tigervnc is really reliable and fast solution. I would like to thank all C programmers, who are spending so much time while making Tigervnc project live.
Very well done.
Because you hve allowed users to use default shared memory or disable shared memory, yours app can be used in strictly userspace chrooted distros. OUstanding work and thank you very much for yours time and for yours complex programmers work on Tigervnc.

**Comment by CendioOssman** [comment]
The `xstartup` way of starting session isn't very reliable on modern systems unfortunately. So we are switching to a new model in the upcoming release where the server is started as a service. Do you think you could test a nightly build and see if that works better for you? You can find a link on our home page.

**Comment by JanuszChmiel** [comment]
Sure I will give it a try. My biggest problem is, if service can be started
on chrooted ArchLinux on A top of Android. And if you will respect
-extension MIT-SHM
command line option also in The newest version.
Unfortunately, sysctl do not work on Chrooted Arch Linux it is pardigm of
Arch Linux developers and routine to detect if The system have been started
as A chrooted system is buind inside various distribution binary modules.
Thank you very much for yours time and for yours help.

**Comment by JanuszChmiel** [comment]
Please, could you tell Me, if
HdyColumn
GTK3 object name is correct or if this GTK3 object name is A tipo: If is it
A tipo, please could you write Me its correct name?
I AM fighting with one C opensourc e app and its refuses to run because of
The fact, that
HdyColumn
do not exist in GTK3.

**Comment by CendioOssman** [comment]
> Sure I will give it a try. My biggest problem is, if service can be started on chrooted ArchLinux on A top of Android. 

Maybe. The environment would have to be able to run services and start uses sessions. It's really something you'll have to discuss with the people handling that chroot environment.

> And if you will respect -extension MIT-SHM command line option also in The newest version.

It is really up to the version of Xorg used with TigerVNC, but it looks like that option is still there even in the latest versions.

> HdyColumn GTK3 object name is correct or if this GTK3 object name is A tipo: If is it A tipo, please could you write Me its correct name?

No idea. This is not something related to TigerVNC so I'm afraid we cannot help you out with this.

**Comment by JanuszChmiel** [comment]
Dear Mr Ossman,
	Thank you very much for yours kind and friendly behaviour to Me.
Really, Tigervnc is making Me very big joy. To be hones, without inventors
of VNC protocol, I would never been able to use Linux X11 based apps on A
top of non rooted Android device. It is also good that XORG programmers have
done many many positive thinks for us.
I must give up real shared memory support for Android. I will wait till some
CPU ARM manufacturer will not introduce hardware virtualisation support to
ARM CPUs for tablet or phones. Then I will be able to run virtualisation
solution.
Thank you again and I wish you many nice experience not only while
developing Tigervnc.
