### ISSUE TITLE
TigerVNCViewer can't connect to macOS Catalina's native VNC server

### ISSUE THREAD

**Issue by daihard** [TigerVNC/tigervnc#1058]
xtigervncviewer running on Kubuntu 18.04 LTS cannot connect to the Screen Sharing (i.e. native VNC server) running on macOS Catalina (10.15.5).

**Repro steps**
Execute xtigervncviewer from the terminal on Kubuntu as follows. (10.0.0.92 is the IP address of the macOS machine.)

╼[dtoyama@leo]─[~]
└╼[$]─> xtigervncviewer 10.0.0.92

TigerVNC Viewer 64-bit v1.10.80
Built on: 2020-06-15 22:27
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Sat Jul  4 16:14:52 2020
 DecodeManager: Detected 8 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       Connected to host 10.0.0.92 port 5900

Sat Jul  4 16:14:53 2020
 CConnection: Server supports RFB protocol version 3.889
 CConnection: Using RFB protocol version 3.8
 CConnection: No matching security types
 CConn:       No matching security types

**Expected behavior**
I expect xtigervncviewer to be able to connect with macOS Catalina's Screen Sharing. I do not expect to have to install TigerVNCServer on macOS.

**Client:**
 - OS: Kubuntu 18.04 LTS
 - VNC client: TigerVNC Viewer
 - VNC client version: 1.10.80
 - Client downloaded from: TigerVNC website

**Server:**
 - OS: macOS Catalina (1015.5)
 - VNC server: Native "Screen Sharing" feature
 - VNC server version: N/A
 - Server downloaded from: N/A
 - Server was started using: N/A

**Comment by bphinz** [comment]
Unfortunately, Apple's native screen sharing feature is a proprietary application that uses the RFB protocol but does not conform to the specification.  So while it has worked to a certain extent in the past, there is simply no way for us to ensure any degree of compatibility.  That being said, I can connect to Apple Screen Sharing on Catalina just fine.  The error message suggests to me that perhaps you have not set a VNC password.  Make sure that you go to System Preferences -> Sharing -> Screen Sharing -> Computer Settings and set a password

**Comment by CendioOssman** [comment]
I agree with @bphinz diagnosis here. This is expected behaviour in a default setup of macOS screen sharing as their authentication methods are secret. Please follow @bphinz instructions and you should be able to connect.

**Comment by daihard** [comment]
Thanks for the reply and suggestions. You’re correct. I don’t have a VNC password set. All my computers at home are behind a hardware firewall. Is it a requirement by macOS that its Screen Sharing only works if you set a password?

Thanks again,
Dai

**Comment by CendioOssman** [comment]
Yes, if you want to use something other than Apple's own client.
