### ISSUE TITLE
Tiger VNC Window captures keyboard and mouse on macOS 10.15.5

### ISSUE THREAD

**Issue by le-jawa** [TigerVNC/tigervnc#1059]
**Describe the bug**
Tiger VNC client 1.10.1 captures the keyboard and mouse on macOS 10.15.5.

- Window must be launched full-screen
- Keyboard stays entirely captured in VNC window, it can't be used at all elsewhere on the Mac
- Mouse capture seems to vary.  Sometimes left- and right-click work in macOS, with nothing else working (such as gestures on the Magic Mouse).  Other times, the mouse stays completely captured by VNC.  When this happens, nothing works except the VNC window.  
- While the VNC session is running, its menu is the only one that will show, even if you select a different application.  (Only visible if you have multiple monitors).
- Exiting the session returns keyboard and mouse control to the Mac.

**To Reproduce**
1. Launch a full-screen VNC session on a Mac running OS 10.15.5
2. Try to use keyboard shortcuts or mouse gestures to move to a different desktop in macOS, or a different program.
3. The keyboard and mouse will not work outside of the VNC window, except (possibly) left- and right-clicking. 
4. Exit your VNC session to return control to the local OS.

**Expected behavior**
Mouse and keyboard control should move fluidly between the VNC session and the OS.

**Screenshots**
I'd love to provide screenshots, but my mouse and keyboard are captured.  ;-)

**Client (please complete the following information):**
 - OS: macOS 10.15.5
 - VNC client: TigerVNC
 - VNC client version: 1.10.1
 - Client downloaded from: Tiger VNC GitHub site

**Server (please complete the following information):**
 - OS: CentOS 7.8
 - VNC server: TigerVNC
 - VNC server version: 1.10.1
 - Server downloaded from: TigerVNC GitHub site
 - Server was started using: xvnc

**Additional context**
- Occurs with single- and multi-monitor setups
- It looks like this occurs on Microsoft Windows 10 too, but I don't have multiple monitors setup on my Windows desktop to be certain.
- I didn't notice this when I was running macOS 10.15.2 (or maybe .3).  This seems to have happened after a recent patch.  The Linux system was also patched (no change to TVNC client or server), so I suppose there's a chance that played into the problem.
- There is a work-around:  launch the TVNC session as a window, then go full-screen using the green traffic light.
- Other (potentially) useful client config info:
    - Security is enabled, with only "TLS with X509 certificates" selected.  Authentication is set to "None".  A CA cert is provided to the client.
    - "Resize remote session to the local window"  is enabled.
    - "Show dot when no cursor" is enabled.
    - All other options not called out here are left at defaults.
- Other (potentially) useful hardware info:
    - MacBook Air 13" Early 2014 
    - Intel HD Graphics 5000 1536 MB
    - 4GB RAM
    - 1440x900 built-in monitor resolution
    - 1920x1080 external monitor resolution

**Comment by CendioOssman** [comment]
I'm afraid this is the designed behaviour so that people can control their remote sessions fully. If you do not wish to have this behaviour then please disable the setting "Pass system keys directly to server".
