### ISSUE TITLE
"Load X.509 Certificate" and "Load X.509 Certificate Key" don't do anything

### ISSUE THREAD

**Issue by YmrDtnJu** [TigerVNC/tigervnc#106]
Clicking on any of those buttons doesn't do anything. I am using version 1.4.80 and Windows 7.
##

**Comment by CendioOssman** [comment]
Huh. Apparently noone finished that work on the Windows side.

**Comment by krjukOFF** [comment]
Hi, "Load X.509 Certificate" and "Load X.509 Certificate Key"  issue is closed on Windows or not? 
Version 1.4.3  is used on Windows 8.1 64bit

**Comment by CendioOssman** [comment]
No, the buttons are still there without doing anything. Note though that this bug is about the server, not the client.

**Comment by krjukOFF** [comment]
HI, what the path and file format for encryption x.509 certificates in tigervnc server configuration:
"Load X.509 Certificate"  and "Load X.509 Certificate Key"

Best regards Konstantins.

**Comment by TheFlyinGeek** [comment]
Would like to see this feature working too. Any progress on this?

**Comment by CendioOssman** [comment]
No, I'm afraid there isn't anyone working on WinVNC.

**Comment by bphinz** [comment]
@CendioOssman can you please review 1028810?  It works but I'm sure there's quite a bit of room for improvement...

**Comment by CendioOssman** [comment]
Sure, but it'll probably be next week. Can you make a PR? Easier to review that way.
