### ISSUE TITLE
Issue in start of vncserver through cronjob

### ISSUE THREAD

**Issue by oyearunpal** [TigerVNC/tigervnc#1061]
Following script I use to start vnc,

`cd $HOME; vncserver -kill :12`
`cd $HOME; vncserver :12 -geometry 1280x1024 -name myvnc --alwaysshared`

It works when I run from terminal, but It gives error when run from cronjob

Screenshot of vnc when start from cron
![hwjTg](https://user-images.githubusercontent.com/8914459/86875718-c9525b80-c100-11ea-905b-573e59b9e713.png)

Machine configuration
```
Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
Kernel: Linux 3.10.0-957.el7.x86_64
Architecture: x86-64
```

Machine was up for last 141 days, after reboot of machine the above issue gets resolved. Can any one tell me how to figure out what cause this issue to arise?

Update: Still, issues arise within every 3-4 days after reboot.

`Version Xvnc TigerVNC 1.8.0 - built Aug 31 2018 12:04:07`
[Also added on Stackoverflow](https://stackoverflow.com/questions/62047668/issue-in-start-of-vncserver-through-cronjob)

**Comment by CendioOssman** [comment]
I'm afraid the vncserver script isn't reliable on modern systems. Please test a nightly build where we've moved to a service based approach instead. Or wait until the next release, which should hopefully not be far off.
