### ISSUE TITLE
"The native viewer should follow the system scale factor", but it doesn't?

### ISSUE THREAD

**Issue by imperative** [TigerVNC/tigervnc#1062]
On Linux Cinnamon, with scaling factor, the main window looks tiny. I am referring to the interface controls, labels etc. (Not even the remote view of the screen.)
Is this supposed to work already? Does it work in some other environments?
(Changing env FLTK_SCALING_FACTOR does not do anything either.)

**Comment by CendioOssman** [comment]
Please don't open duplicate issues. This is already discussed on #369.
