### ISSUE TITLE
vncviewer: The dialog for opening a configuration file could have a better default directory

### ISSUE THREAD

**Issue by erkkiruohtula** [TigerVNC/tigervnc#1065]
Currently using the dialog to open a configuration file in vncviewer always sets the starting point at the root of the file system. This means the user may have to navigate several levels to find where the user prefers to keep the files.

The issue does not matter so much if the user always uses the same server, because Tigervnc remembers the latest server,  but someone like me who frequently connects to different servers finds this inconvenient.

It would be more usable if the starting point were either the user's home directory, or the latest directory used to load a configuration file. I think starting at home would be a trivial change to implement, from what I can see from the code.

(I'm now using Linux, but I recall Windows also started the file dialog at C:\).

**Comment by samhed** [comment]
Agreed.

**Comment by CendioOssman** [comment]
Fixed via #1331.
