### ISSUE TITLE
"Invalid PixelBuffer height" error

### ISSUE THREAD

**Issue by MageSlayer** [TigerVNC/tigervnc#1067]
**Describe the bug**
Strange bug on connect using TigerVNC.

**To Reproduce**
Start vnc server at dual-head 4k display.
$ x11vnc -display :0 -scale 1/2 -ncache 10 -forever --passwd "123123"

Try to connect:
$ vncviewer localhost:5901
TigerVNC Viewer 64-bit v1.10.1
Built on: 2020-07-26 09:21
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Sun Jul 26 12:25:26 2020
 DecodeManager: Detected 12 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       Connected to host localhost port 5901
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VncAuth(2)

Sun Jul 26 12:25:35 2020
 CConn:       Invalid PixelBuffer height of 23040 pixels requested

**Expected behavior**
Normal connect expected.

**Client (please complete the following information):**
TigerVNC-1.10.1 under Gentoo 64bit

**Server (please complete the following information):**
Same PC.

**Comment by CendioOssman** [comment]
We've restricted the maximum size of sessions to something reasonable to avoid overflow issue that can cause security problems. x11vnc's ncache feature unfortunately creates a massive session size. So I suggest turning that off and you should be fine.
