### ISSUE TITLE
(win viewer) No such include file and building path error on Win10 and Cygwin environment

### ISSUE THREAD

**Issue by joshlin5900** [TigerVNC/tigervnc#1068]
No such include files and wrong building path configure of "rfb_win32/*", "rfb/*", and others.

![image](https://user-images.githubusercontent.com/68728513/88510898-82c49280-d016-11ea-91a5-e9fe15ad438e.png)

**Comment by CendioOssman** [comment]
It looks like you ran `cmake` in the `win` directory. I'm afraid the build only works if you build from the top.

So please start over and run `cmake` and `make` all the way at the top tigervnc directory.
