### ISSUE TITLE
VNC-Server does not work in Windows 7

### ISSUE THREAD

**Issue by YmrDtnJu** [TigerVNC/tigervnc#107]
The TCP connection is reset immediately. Server was startet as system service and as logged in user.

**Comment by CendioOssman** [comment]
Could you add the argument `-Log *:EventLog:100` to winvnc.exe and see if any log entries show up in Windows' event log when you connect?

**Comment by YmrDtnJu** [comment]
ok... suddenly, it seems to work. i don't get the tcp reset error again. sorry for the bug report. i am using version 1.4.1 again. so maybe the problem was with version 1.4.80 only.
