### ISSUE TITLE
Shortcut (like F8) to minimize the vnc

### ISSUE THREAD

**Issue by Naff86** [TigerVNC/tigervnc#1070]
I currently use tigervnc for work using full screen mode over multiple monitors. To minimize the screen you press F8 and then clicking on minimize. 20% of the time I click on the toggle full screen button that is right next to the minimize on the F8 menu. This jumbles all the vnc window locations and is a pain to reconfigure. 

I suggest adding a shortcut to minimize ghe tiger vnc screen. Or alternatively to move the toggle full screen button somewhere lower on the menu. 

Thanks!

**Comment by samhed** [comment]
You should be able to use the shortcut characters in the menu. When you open the F8 menu, look for the underlined characters.

For example, minimizing should probably be something like F8->m

**Comment by Naff86** [comment]
Works! Thanks! 
F8->z
