### ISSUE TITLE
Server listening on a Unix Domain Socket doesn't work

### ISSUE THREAD

**Issue by Jousboxx** [TigerVNC/tigervnc#1071]
**Describe the bug**
I cannot start a VNC server listening on a domain socket.

**To Reproduce**
`vncserver -rfbunixpath /tmp/mysocket`

**Expected behavior**
Server starts and then backgrounds itself, same as it does when running on a network port.

**Server**
 - OS: Ubuntu 20.04
 - VNC server: TigerVNC
 - VNC server version: 1.10.0
 - Server downloaded from: Ubuntu 20.04 repositories, using apt
 - Server was started using: `vncserver`

(Client info N/A)

**Additional context**
After running the `vncserver` command, the terminal hangs for about 40 seconds as if it's waiting for something. After it presumably times out, the following message is shown:

```
vncserver: /usr/bin/Xtigervnc did not start up, please look into '/home/iv/.vnc/vbox:1.log' to determine the reason! -1
Killing Xtigervnc process ID 2685... success!
```

Here are the contents of the log file:
```
Xvnc TigerVNC 1.10.0 - built Apr  9 2020 06:49:31
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12008000, The X.Org Foundation


Sat Aug  1 15:53:51 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on /tmp/mysocket (mode 0600)
 vncext:      created VNC server for screen 0

Sat Aug  1 15:54:31 2020
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
```
There doesn't seem to be a specific error message, which is strange.

This is essentially a fresh install of Ubuntu, so nothing weird going on distro-wise. This example was done in Virtualbox, but I have had the same problem in a Singularity container and running normally on the host.

**Comment by CendioOssman** [comment]
I'm afraid Debian and Ubuntu includes their own `vncserver` script, so it's not something we can support. That specific error is only in their version of `vncserver`.

I'll have to direct you to file a bug with Ubuntu about this.

**Comment by CendioOssman** [comment]
Yes. I'm afraid that's just a different name for the same script.
