### ISSUE TITLE
-localhost option for x0vncserver throws error

### ISSUE THREAD

**Issue by jaredpooole** [TigerVNC/tigervnc#1074]
**Describe the bug**
I am trying to configure x0vncserver to only allow connections from ssh an tunnel so I would like to restrict x0vncserver to localhost only. The documentation for x0vncserver states that this can be accomplished by including -localhost anywhere in the command line arguments.

What I really don't understand is that I had a look at the codebase and it seems like this was implemented a while back at the request of a different user. I can't figure out why it isn't working now.

**To Reproduce**
1. Try to start x0vncserver with the -localhost option like "/usr/bin/x0vncserver -localhost -passwordfile /home/user/.vnc/passwd -display :0" for example and an error will be produced. The equivalent command without -localhost works as expected

**Expected behavior**
The -localhost flag should stop x0vncserver from opening any ports on the computer and should only accept connections from localhost

**Client (please complete the following information):**
 - OS: [Windows 10
 - VNC client: TigerVNC
 - VNC client version: 1.10.1
 - Client downloaded from: Website

**Server (please complete the following information):**
 - OS: Debian 4.9.228-1
 - x0vncserver variant included in TigerVNC
 - VNC server version: 1.7.0
 - Server downloaded from: apt
 - Server was started using: /usr/bin/x0vncserver -localhost -passwordfile /home/user/.vnc/passwd -display :0

**Comment by CendioOssman** [comment]
I'm afraid your server is too old. That option was added in TigerVNC 1.10.0. So please upgrade and it should work fine.
