### ISSUE TITLE
about the vnc xstartup config of kde

### ISSUE THREAD

**Issue by unihon** [TigerVNC/tigervnc#1075]
How config vnc xstartup script. I has try some conifgs, but not work well.

```bash
#!/bin/bash                                                                                                                       
startkde &
plasmashell --replace
```

It only can run one plasmashell instance.

```bash
#!/bin/bash                                                                                                                       
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec dbus-launch plasmashell
```

This config, windows have some problems, eg no windows border, and mouse icon lose on some windows.

Who have better conifg to share to me.

**Comment by CendioOssman** [comment]
I don't think you're supposed to start `plasmashell` manually. So I suggest having just `startkde`, and no `&`.

The `xstartup` method is also being deprecated for being too unreliable. Please test one of our nightly builds from our homepage which has a new method of starting desktops. You can also wait for the upcoming 1.12.0 release.
