### ISSUE TITLE
Leak struct addrinfo in network::createTcpListeners

### ISSUE THREAD

**Issue by chraac** [TigerVNC/tigervnc#1076]
https://github.com/TigerVNC/tigervnc/blob/6d5915d3ca9e37fd602d5a7eb1653440ed536c68/common/network/TcpSocket.cxx#L453

As we can see, in the function ```network::createTcpListeners(std::list<SocketListener*> *, const char *, int)``` we call ```getaddrinfo``` to obtain a ```struct addrinfo``` from ```addr``` and ```port```.
And then call the overload function ```void network::createTcpListeners(std::list<SocketListener*> *, const struct addrinfo *)``` to create a new ```TcpListener```.
The returned  ```struct addrinfo``` from ```getaddrinfo``` must explicit call ```freeaddrinfo``` to free. But neither one of ```network::createTcpListeners``` was call ```freeaddrinfo``` when there is no exception occur.

**Comment by CendioOssman** [comment]
Nice catch. Thanks. Fixed in cbe0ddc28cab60712890c756bc6129ada7c52215.
