### ISSUE TITLE
IPv6 breaks TCP filter (HostsFile)

### ISSUE THREAD

**Issue by austinbutler** [TigerVNC/tigervnc#108]
This is how I am starting x0vncserver:
```
/usr/bin/x0vncserver -display=:0 -hostsfile=/home/austin/.vnc/hosts -passwordfile=/home/austin/.vnc/passwd
```

This is the contents of the hosts file:
```
+192.168.1.2
```

When I try to connect from that IP, this is the result:
```
Thu Jan 22 16:16:16 2015
 Geometry:    Desktop geometry is set to 1920x1080+0+0
 Main:        XTest extension present - version 2.2
 Main:        Listening on port 5900

Thu Jan 22 16:16:20 2015
 Main:        Client connection rejected
```

Why is that? My real aim is to have localhost and that IP allowed, so either from my desktop on the internal network or, if outside, through an SSH tunnel.

But I tried this, and it didn't work so I tried the very simple rule above:
```
+192.168.1.2
+127.0.0.1
-
```

Everything works fine without the hostsfile parameter. This is on Arch with TigerVNC built from Github.

**Comment by CendioOssman** [comment]
I can't see anything obviously wrong with your file. Could you run `x0vncserver` with `-Log *:stderr:100` and see if it tells us anything more?

**Comment by austinbutler** [comment]
It reads out the parameters, but otherwise the error is the same unfortunately.

```
Sat Jan 24 10:42:33 2015
 Config:      set display(String) to :0
 Config:      set HostsFile(String) to /home/austin/.vnc/hosts
 Config:      set PasswordFile(String) to /home/austin/.vnc/passwd
 Geometry:    Desktop geometry is set to 1920x1080+0+0
 Main:        XTest extension present - version 2.2
 VNCServerST: creating single-threaded server x0vncserver
 Main:        Listening on port 5900

Sat Jan 24 10:42:44 2015
 Main:        Client connection rejected
```

**Comment by CendioOssman** [comment]
Ah. Found it. It's the new IPv6 support that is causing problems. The filter code only supports IPv4. 

@twaugh I guess this needs some attention as well. :)

**Comment by twaugh** [comment]
Thanks, I'll take a look.

**Comment by CendioOssman** [comment]
Closing this now as we've merged the proper fix.
