### ISSUE TITLE
Server does not respond with EndOfContinuousUpdates message after requesting ContinuousUpdates pseudo encoding

### ISSUE THREAD

**Issue by MarcusWichelmann** [TigerVNC/tigervnc#1086]
According to https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#continuousupdates-pseudo-encoding the server should respond with a `EndOfContinuousUpdates` message after the client has sent an initial SetEncodings message and advertised its support for the `ContinuousUpdates` psuedo encoding. But it doesn't.

**Protocol Flow**
Here is a minimal example of a protocol flow where the error occurs:
![image](https://user-images.githubusercontent.com/5501487/91663428-0b888f80-eae9-11ea-81f9-b7e9c9fe52c3.png)
Following the `SetEncodings` and `FramebufferUpdateRequest` messages, there is only a single `FramebufferUpdate` message containing a few RAW-encoded rectangles and nothing more.

**Expected behavior**
After my client sent the `SetEncodings` message and advertised the pseudo encoding -313, I would expect a `EndOfContinuousUpdates` message back.

**Client:**
- Self-developed: https://github.com/MarcusWichelmann/MarcusW.VncClient

**Server:**
 - OS: Fedora 32 Workstation
 - VNC server: TigerVNC
 - VNC server version: Latest (tigervnc-1.11.80-20200824gitac76a87.x86_64) from http://tigervnc.bphinz.com/nightly/
 - Server was started using: `vncserver -log *:stderr:100 -pixelformat RGB888`

**Server log**
![image](https://user-images.githubusercontent.com/5501487/91663980-68397980-eaec-11ea-82a1-0fa433ac814b.png)

**Comment by MarcusWichelmann** [comment]
Aah, looks like it's suppressed if the client does not also support fences:
https://github.com/TigerVNC/tigervnc/blob/baae6518ef988b466373e366a7945f61df43c65d/common/rfb/VNCSConnectionST.cxx#L767

That makes sense, of course. But printing a warning to the log output would be very helpful in this case. :smile:

**Comment by samhed** [comment]
I guess it could be a debug line, in that case, feel free to make a PR for that if you feel it's important enough 😉
