### ISSUE TITLE
windows server 2012 R2 connect error

### ISSUE THREAD

**Issue by vitoAllin** [TigerVNC/tigervnc#1090]
**Describe the bug**
**windows server 2012 R2** connect error
readTLS：Error in the pull function. (-54)

**Screenshots**
![image](https://user-images.githubusercontent.com/24727128/92432440-b75a6b00-f1cc-11ea-9845-19ddd7335df3.png)

**Comment by CendioOssman** [comment]
Please fill out the bug report form so we can see the details about your setup.

**Comment by vitoAllin** [comment]
> Please fill out the bug report form so we can see the details about your setup.

Thanks Can you tell me where is the bug report form or error log dir on windows  I can't find where is it

**Comment by vitoAllin** [comment]
Thanks for your reply .
Sorry can you tell me where is the tigervnc server log  ,I can't find it on win 10 or win 2012 server R2

**Comment by CendioOssman** [comment]
I don't think it logs by default unfortunately. Please see this wiki page for how to enable it:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs

**Comment by vitoAllin** [comment]
> I don't think it logs by default unfortunately. Please see this wiki page for how to enable it:
> 
> https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs

Many thanks，I can see the log now . 
If I get error again, I will comment it here.

**Comment by vitoAllin** [comment]
I find the cause of the problem is just 【the Fast User Switching】

**Comment by vitoAllin** [comment]
![image](https://user-images.githubusercontent.com/24727128/92486766-0f21c200-f21f-11ea-93fb-6c1144c215e8.png)
