### ISSUE TITLE
/usr/bin/vncserver command is not generated on release 31

### ISSUE THREAD

**Issue by hslyu** [TigerVNC/tigervnc#1091]
**Describe the bug**

**To Reproduce**
1. From the official [bintray link](https://bintray.com/tigervnc/beta/tigervnc/1.11beta#files/ubuntu-18.04LTS%2Famd64) of the release 31(version 1.11 beta), download tigervncserver_1.10.90-1ubuntu1_amd64.deb
2. Install the deb file using dpkg
3. /usr/bin/vncserver command is not generated.
4. I tested /usr/bin/vncserver successfully generated by installing tigervnc with the following command
"""
sudo apt install tigervnc-standalone-server tigervnc-xorg-extension
"""

**Client (please complete the following information):**
This is not client issue

**Server (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - VNC server: Tigervnc
 - VNC server version: 1.11.0
 - Server downloaded from: official bintray
 **- Server was started using: This part is problem**

**Additional context**

**Comment by CendioOssman** [comment]
This is on purpose. The old method is gone and you must now start things via a system service for things to work correctly. Please see the vncsession man page for more details. You can also get help via our users mailing list (see our home page).
