### ISSUE TITLE
Does it support multiple Viewers to connect to the same WindwOS machine through different ports

### ISSUE THREAD

**Issue by vitoAllin** [TigerVNC/tigervnc#1092]
**Is your feature request related to a problem? Please describe.**
Does it support multiple Viewers to connect to the same WindwOS machine through different ports ？
just like linux.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/24727128/92568835-54db9a80-f2b2-11ea-8051-a7b9a71943f2.png)

**Comment by CendioOssman** [comment]
No, I'm afraid not. WinVNC only really handles what is visible on the local monitor of the machine.

**Comment by vitoAllin** [comment]
> No, I'm afraid not. WinVNC only really handles what is visible on the local monitor of the machine.

See it ，many thanks ！
