### ISSUE TITLE
How to set password and port by cmd on launching winvnc4 ？

### ISSUE THREAD

**Issue by vitoAllin** [TigerVNC/tigervnc#1093]
**Is your feature request related to a problem? Please describe.**
How to set password and port by cmd on launching winvnc4 or vncconfig.exe ？
Or can you tell me the place saved winvnc4 server password and port ？
In a file or  in the windows Registry ？ 
If in the registry can you tell me the dir ？
I want to change the   password and port without vncconfig.exe window.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/24727128/92715895-abb7a180-f390-11ea-853d-85326721f07f.png)

**Comment by CendioOssman** [comment]
Settings for WinVNC are stored in the registry under HKLM\Software\TigerVNC\WinVNC4 (or HKCU if run in user mode). So you can simply copy those registry keys you'd like to preconfigure to your machines.
