### ISSUE TITLE
why latest stable tigervnc can not be run without Xorg package or xinit?

### ISSUE THREAD

**Issue by JanuszChmiel** [TigerVNC/tigervnc#1094]
I have updated Tigervnc on AArch64 platform by using ArchLinux. I have found out, that it is no more possible to run standalone Tigervnc without installing and running Xorg or Xinit or startx module.
I Am getting error message unsupported Xserver session or similar result.
DOes somebody of us have xorg.conf configuration file, which can be used on Android devices which run userspace variant of ArchLinux so Tigervnc could be normally used with Xinit if is it new requirement and The revolutionar reforme of yours Tiervnc project?

I love Tigervnc, since it reliably support keyboard hot keys by using VNC protocol even on ANdroid devices without UDEV active.
But yours revolutionar new approach to yours project is making Tigervnc very probably only usable with normal computers which uses Xorg with appropriate video drivers.
Is it possible to run tigervnc with
xorg-server-xvfb
Or it is also impossible?
I Am very sad. Because I will not be able to run Orca, mate-session on Android devices with yours perfect solution which support SHIFT+TAB with Orca screen reader so perfectly.
Sure. I could use last stable version which work according to my needs.
Thank you very much for yours advices.

Now, I must use X11vnc with Xinit and I must use vieo dummy driver and special xorg.conf configuration file. FOrtunately, because I do not see at all, I AM visually impaired, it work. But SHIFT+TAB combination do not work with Orca when using X11vnc. So any advices are very welcomed.
Tigervnc is also much more faster.

**Comment by CendioOssman** [comment]
There must have been some misunderstanding, at least partially. TigerVNC does not require Xorg as it ships its own replacement in the form of Xvnc. It does however require large parts of Xorg's infrastructure as it tries to start a similar session. It also requires systemd as sessions must be run as services.

I have no idea what the environment on Android looks like so I'm afraid I don't know if it has what's required. Our target is standard Linux distributions and I'm afraid we don't have the resources to deal with exotic stuff.

Please see the tigervnc-users mailing list for more help on the new model. There are already some tips there from people.

**Comment by JanuszChmiel** [comment]
And please could you send Me Github link to get previous version, not from
yesterday, which I could build since it have worked for Me?

**Comment by JanuszChmiel** [comment]
I Am getting The following error:
vncserver: Couldn't find suitable Xsession
Previous versions have worked perfectly on Android devices on ArchlInux
AArch64 which uses Proot.

**Comment by JanuszChmiel** [comment]
Xvnc TigerVNC 1.11.0 - built Sep 10 2020 07:46:56

**Comment by CendioOssman** [comment]
All old releases are still available from the release page here:

https://github.com/TigerVNC/tigervnc/releases

**Comment by JanuszChmiel** [comment]
I will try to run Xvnc directly without using vncserver script.

**Comment by JanuszChmiel** [comment]
I have excellent news for zou.
Even newest Tigervnc can be normally used from ANdroid. I have stop to use
vncserver ArchLinux script. And I run tigervnc directly by typing The
following command and it work like A charm.

**Comment by JanuszChmiel** [comment]
Fortunately, Tigervnc latest stable version can be perfectly run even on
Android by using Termux and Proot.
I had to stop to use vncserver Bash shell script. And I run Tigervnc by
using The following command.

**Comment by JanuszChmiel** [comment]
It is possible To use Tigervnc even on Android with Termux and Proot.
I have simply stopped to use vncserver script.
And I Am using This command instead.
 
Xvnc -localhost -geometry 1024x768 -depth 24 -SecurityTypes=None &

**Comment by pfactum** [comment]
https://bbs.archlinux.org/viewtopic.php?pid=1925707#p1925707
