### ISSUE TITLE
vnc server for windows after 1.11.0 release

### ISSUE THREAD

**Issue by sunlin7** [TigerVNC/tigervnc#1095]
Hi All,

As the 1.11.0 release note write,
> WARNING: winvnc is currently unmaintainted and and may not function correctly.

What vnc server should be used on windows? Thanks.

**Comment by CendioOssman** [comment]
Any one you like. We don't have any recommendations from our end. I know that TightVNC and UltraVNC are commonly used, so they are probably a safe bet.

**Comment by sunlin7** [comment]
@CendioOssman Okay, I'll give a try. 
Thank you.
