### ISSUE TITLE
UseIPv6=0 in config file

### ISSUE THREAD

**Issue by emmanuelux** [TigerVNC/tigervnc#1098]
UseIPv6=0 in .vnc/config doesn't work.

It works only with the command line "Xvnc -UseIPv6=0", the problem is that with last update of tigervnc in archlinux it used vncsession and no parameters is possible without .vnc/config or global configs in /etc/tigervnc/... that doesn't work too.

**Comment by CendioOssman** [comment]
Ah. I see the issue. It seems we have a bug where we cannot have "0" as the value for options. I'll get a fix sorted out.

Until then you should be able to use "UseIPV6=no" instead.

**Comment by emmanuelux** [comment]
UseIPV6=no makes vncsession stops
UseIPV6=no makes vncsession starts but without cut IPv6

**Comment by CendioOssman** [comment]
Crap. This turned out to be trickier than I thought. I should be fixed as of 38c6848b30cb1908171f2b4628e345fbf6727b39.

Unfortunately I see no workaround for existing code though. So you'll have to rebuild things yourself, or poke your distribution in to adding that patch.

**Comment by emmanuelux** [comment]
I try your patch today, but XVnc still does not start with UseIPv6=no or UseIPv6=off  in .vnc/config file
with UseIPv6=0, it starts but I have always IPV6 opened
