### ISSUE TITLE
"session" requirements in vncserver 1.11

### ISSUE THREAD

**Issue by noahfriedman** [TigerVNC/tigervnc#1099]
1. Why is any "session" required at all?  What happened to the old support for a plain xinitrc file?

2. Why do session files have to be located in /usr/share/xsession?  Why can't I create my own local one?

3. What is all this vncsession nonsense anyway?  I just want to start multiple virtual framebuffers when I'm doing testing or remote work.  I don't care about multiuser environments or "desktops".  How do I get back the old behavior?

4. This is hugely disruptive, non-backward compatible change in workflow that warranted a major version bump at least, not 1.10 => 1.11.

**Comment by noahfriedman** [comment]
I mean, how many people even share physical or virtual hosts and need user session management anymore?  Isn't this a 1990s problem?

**Comment by pfrenssen** [comment]
I'm also affected by this: the latest version 1.11 throws an error for me on any of my headless servers:

```
$ vncserver
vncserver: Couldn't find suitable Xsession.
```

This is a breaking change. I read from the PR and the related bug report in arch linux that this now requires a desktop manager to be installed, but it doesn't make sense to install a desktop environment on a server.

I think it would be a good idea to fall back to the previous behavior when no desktop manager is present on the system.

**Comment by keke-cute** [comment]
vncserver: Couldn't find suitable Xsession.
yes,my system no desktop manager too

**Comment by CendioOssman** [comment]
> 1. Why is any "session" required at all?  What happened to the old support for a plain xinitrc file?
> 

Because desktop environments require this method or they won't work correctly. We've gotten lots and lots of bug reports and so we had to start fulfilling the requirements more properly.

> 2. Why do session files have to be located in /usr/share/xsession?  Why can't I create my own local one?
> 

We followed the established behaviour of the display managers. But I suppose we could also look for them in `$XDG_DATA_HOME` as well. Please add a feature request issue and we can have a look.

> 3. What is all this vncsession nonsense anyway?  I just want to start multiple virtual framebuffers when I'm doing testing or remote work.  I don't care about multiuser environments or "desktops".  How do I get back the old behavior?
> 

I'm afraid you don't. The target for `vncserver` is a user session and not arbitrary custom stuff, I'm afraid. `Xvnc` is still included and supported by us. So feel free to write your own scripts to start what you need.

> 4. This is hugely disruptive, non-backward compatible change in workflow that warranted a major version bump at least, not 1.10 => 1.11.

Possibly. But `vncserver` is just one small part of our project so we opted to continue the current numbering.

**Comment by noahfriedman** [comment]
"I'm afraid you don't. The target for vncserver is a user session and not arbitrary custom stuff, I'm afraid. Xvnc is still included and supported by us. So feel free to write your own scripts to start what you need."

"Possibly. But vncserver is just one small part of our project so we opted to continue the current numbering."

Next time, please be more concise and just write "fuck you" when that's what you mean.

**Comment by noahfriedman** [comment]
You could have trivially left the "vncserver" command alone, since you replaced it with a different command (vncsession) anyway.  You broke legacy behavior **FOR NO NECESSARY REASON**

**Comment by bphinz** [comment]
I don't think that's what was meant at all, and it's not like your tone was
all that friendly from the get go...  Could the old vncserver co-exist with
the new one?  Sure, but the rest of the world is moving to systemd and
there's plenty of reasons for us to do the same.  Keeping both means
maintaining both and there's only a handful of developers on this
project, we have to allocate our time where we think it's most beneficial.
If you need the legacy behavior then why not simply stay at 1.10?

**Comment by noahfriedman** [comment]
I would love to, but no distribution is going to stay at that release.  Eventually, even pinning 1.10 is going to stop working and then I have the luxury of either moving with the tide or swimming upstream.

Free software means you have the freedom to swim upstream against a tsunami, but good luck with that.

The only practical way to keep from drowning is for the work upstream to care about supporting more than just one workflow.  Declaring "this is what this is for (as of now)" and ignoring several decades of existing practice is exactly as contemptuous, if not outright hostile, as you accuse me of being.

**Comment by bphinz** [comment]
On Mon, Sep 21, 2020 at 2:23 PM Noah Friedman <notifications@github.com>
wrote:

> I would love to, but no distribution is going to stay at that release.
> Eventually, even pinning 1.10 is going to stop working and then I have the
> luxury of either moving with the tide or swimming upstream.
>
Which distribution are you concerned about? The only LTS distribution that
I know of that is even shipping 1.10 is Ubuntu 20.04 which has an EoL date
of April 2025.  RHEL/CentOS 7, 8, ubuntu 18.04, are all at 1.9 or lower.
