### ISSUE TITLE
Downloading source code

### ISSUE THREAD

**Issue by bdubbs** [TigerVNC/tigervnc#110]
When trying to specify a link for downloading the source TigerVNC tarball, the link is specified as  v1.4.2.tar.gz.  Please create a named tarball, e,g, tigervnc-1.4.2.tar.gz, as well.  This is needed to facilitate documenting the build in BLFS.  Thanks.

  -- Bruce Dubbs
      linuxfromscratch.org

**Comment by CendioOssman** [comment]
I'm afraid this is not under our control as those tar balls are automatically generated by github. I've pointed out this problem to them though, but unfortunately they couldn't give me any information if it would be fixed. Feel free to nag them as well though. :)
