### ISSUE TITLE
Unable to type in international languages and change keyboard

### ISSUE THREAD

**Issue by coda-nsit** [TigerVNC/tigervnc#1102]
**Describe the bug**
I have 
* TigerVNC client installed in my local MAC
* I have Ubuntu and Amazon Linux 2 servers with xfce4 desktop environment.
The servers have the required fonts installed and the terminals support the fonts. I can confirm this because I am able to "view" those fonts when I do a `cat`. I want to type in international fonts like I can do in my local MAC. But when I try to change the keyboard as shown in screenshot 2, I am not allowed to. As a result I can only type in English font.

**To Reproduce**
1. Install TigerVNC client in MAC
2. Install TigerVNC server in Ubuntu or Amazon Linux AMI 2
3. Install xfce4 desktop environment in the servers.
4. Start a TigerVNC session and try to change the keyboard.

**Expected behavior**
I should be able to change the keyboard and type in international fonts.

**Screenshots**
MAC shows all keyboards: https://i.imgur.com/gdcoo1sm.png
TigerVNC disables the keyboards: https://imgur.com/s2LkqMW

**Client (please complete the following information):**
 - OS: MAC OS Catalina 10.15.6
 - VNC client: TigerVNC
 - VNC client version: [e.g. 1.10.1
 - Client downloaded from: https://formulae.brew.sh/cask/tigervnc-viewer

**Server (please complete the following information):**
 - OS: Ubuntu 18.04 and Amazon Linux release 2 (Karoo)
 - VNC server: TigerVNC
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: apt, yum package manager
 - Server was started using: `vncserver :1`

**Comment by coda-nsit** [comment]
Closing this issue as it was related to ibus input method and not TigerVNC.

**Comment by asukhonosov** [comment]
I faced exactly the same issue. 
Is there a solution or a workaround?
