### ISSUE TITLE
VNC server closing session randomly

### ISSUE THREAD

**Issue by sunnytater** [TigerVNC/tigervnc#1103]
Hello, I am pretty new, so bare with me please.

**Describe the bug**
We are pretty sure our VNC server is losing/closing the connection on our clients. Network has been tested*

**To Reproduce**
not able to reproduce/ is random some times once a day others multiple times a day.

**Expected behavior**
To remote in from one client to another without disconnecting randomly.

**Screenshots**

**Client (please complete the following information):**
 - Device Type :ThinLinux (Dell 3040)
 - OS Version: Thin Linux 2.x (BaseThinLinux2.x-S02) 2.2.1.03_3040_16GB_merlin
 - Image Version: 2.2.1.03
 - VNC client: TigerVNC - vnc-viewer
 - VNC client version: [e.g.1.0.0-09]
 - Client downloaded from: pre loaded on the merlin image

**Server (please complete the following information):**
 - Device Type :ThinLinux (Dell 3040)
 - OS Version: Thin Linux 2.x (BaseThinLinux2.x-S02) 2.2.1.03_3040_16GB_merlin
 - Image Version: 2.2.1.03
 - VNC server: TigerVNC
 - VNC server version: [e.g. 1.0.0-10]
 - Server downloaded from: [e.g. preloaded on image]
 - Server was started using: [e.g. using Wyse Management Suite to manage settings on wyse to auto start server on client]

**Additional context**
We are using one Thin client to remote in to another Thin Client that is using RDP in to a Virtual machine. This process works very well except the VNC server on our thin clients is resetting/closing the connection randomly but we are able to re-connect  immediately after it looses the connection. We do have a ticket open with dell and their engineers have given us a few solutions that have not resolved the problem yet. I think a cheap solution would be to have the VNC viewer auto reconnect after 10 seconds after a disconnect event. We are using it to display info in a complex system we have. Also, If I use TightVNC to remote to a wyse device, after a while I will get an error stating the connection has been gracefully closed.

**Comment by samhed** [comment]
Are you able to see any logs? Both the client side and the server side could be interesting.

**Comment by sunnytater** [comment]
I have logs from the Dell Wyse(3040) and are confidential but no VNC server specific logs. maybe i am not finding them.

**Comment by samhed** [comment]
Are you able to start vncviewer or the server from the command line? That should result in some log output in the terminal

**Comment by sunnytater** [comment]
I am able to start the viewer 
![image](https://user-images.githubusercontent.com/71405515/93534302-ad85e580-f8f9-11ea-98dc-b6418ab515fe.png)

**Comment by samhed** [comment]
So, could you try to reproduce this disconnection issue and see if the VNC Viewer prints some sort of hint?

**Comment by sunnytater** [comment]
so the dell tech and my self came up with a temp solution to address my issue. we set up a custom connection and set parameters using the INI file and password file to make it fully automated. every time the connection drops. the vnc viewer will auto reconnect in 15 seconds. view the below solution.

CONNECT=custom \
Description="TESTEST" \
AutoConnect=yes \
Reconnect=yes \
ReconnectSeconds=15 \
Command="vncviewer -passwd ~/.vnc/passwd xxx.xxx.xxx.xxx -fullscreen=1"

note that our VNC viewer is still closing randomly on our wyse devices-no logs.

**Comment by samhed** [comment]
I'll close this issue for now then. Feel free to reopen it if you want to continue troubleshooting.
