### ISSUE TITLE
vncserver: support for multiple -geometry arguments

### ISSUE THREAD

**Issue by bolind** [TigerVNC/tigervnc#1104]
**Is your feature request related to a problem? Please describe.**
The standard list of resolutions for vncserver has fallen a bit behind modern monitor specifications. One can give one (1) -geometry option when starting the vncserver, but that's, at times, not enough, when multiple user setups have to be supported with a unified startup script.

**Describe the solution you'd like**
Multiple -geometry arguments should be supported, and all these resolutions should be added to the list.

**Describe alternatives you've considered**
Alternatively, some common high-resolution modes could be added to the stock list.

**Comment by CendioOssman** [comment]
It sounds like #328, so we'll probably merge this issue with that.

I'm curious as to what problems you are seeing right now though? If the client resizes to something that isn't in the list than it should be automatically added.
