### ISSUE TITLE
'vncserver -kill' not available in version 1.11.0?

### ISSUE THREAD

**Issue by accetto** [TigerVNC/tigervnc#1107]
It seems that the new `vncserver` script (version 1.11.0) does not provide an option to stop the VNC server. At least not as previously through `vncserver -kill :*`.

What is the correct way to stop the VNC server now?

**Comment by CendioOssman** [comment]
That is correct. You now start and stop your VNC sessions via systemctl. E.g. `systemctl stop vncserver@:2.service`.

**Comment by accetto** [comment]
I would like to add some more information to this.

The way described above would not work with my containers (see [accetto DockerHub repository](https://hub.docker.com/u/accetto/)), because they do not use `systemd` as init system.

The error message would be

```bash
System has not been booted with systemd as init system (PID 1). Can't operate.
```

Instead they use [tini](https://github.com/krallin/tini) as init system.

In that case the process tree looks like this (`pstree -p`)

```txt
tini(1)─┬─Thunar(96)
        ├─bash(6)───vnc_startup.sh(13)─┬─sleep(24)
        │                              └─xinit(23)─┬─Xvnc(28)
        │                                          └─sh(31)─┬─ssh-agent(72)
        │                                                   └─xfce4-session(83)───{xfce4-session}(84)
```

So I suppose that I have to kill the `xinit` process like `kill 23` or the `vnc_startup.sh` process like `kill 13`.

Is that the correct way to stop the VNC server in my containers and which one from the two options would you recommend?

**Comment by CendioOssman** [comment]
Yeas, that seem appropriate. `xinit` should propagate that signal on to your session process (`sh` in this case).
