### ISSUE TITLE
vncsession-start via systemd should set current directory to $HOME

### ISSUE THREAD

**Issue by timkgh** [TigerVNC/tigervnc#1108]
**Describe the bug**
On Arch Linux I upgraded from 1.10 to 1.11. I use session=LXDE and now LXTerminal starts in / (root dir) rather than $HOME which used to be the case with 1.10.
I think something is not set right when the session is started via systemd, either the unit file or vncsession-start or vncsession should first "cd $HOME" for the user before it starts the session.

**To Reproduce**
Use Arch Linux, follow install instructions in Arch wiki, use LXDE as the session. LXTerminal starts in "/" (root dir) rather than $HOME.
https://wiki.archlinux.org/index.php/TigerVNC#Running_vncserver_for_virtual_(headless)_sessions

**Expected behavior**
Current directory for the session should be set to $HOME

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1] Arch Linux
 - VNC server: [e.g. TigerVNC, or UltraVNC] tigervnc-1.11.0-5-x86_64
 - VNC server version: [e.g. 1.8.0] tigervnc-1.11.0-5-x86_64
 - Server downloaded from: [e.g. my Linux distribution] Arch Linux official pkg
 - Server was started using: [e.g. `vncserver`] systemd vncserver@:1.service 

**Additional context**
Corresponding issue on Arch, not sure if this is a packaging or core TigerVNC issue.
https://bugs.archlinux.org/task/67940

**Comment by CendioOssman** [comment]
Likely an issue in our end or the system. Should not be an issue with the packaging. Will need to dig around a bit and see where the switch to the home directory should take place.

**Comment by mrkwjc** [comment]
Hi!

I can confirm this issue on Manjaro, with the additional, possibly related, troubles. Namely, the user environment variables are also not set properly for X session. For example if the user sets up $PATH in ~/.bashrc, then this is not taken into account in login console. In KDE running `konsole -e 'some command from custom path'` ends with a non existent command error.

**Comment by mrkwjc** [comment]
FYI, modifying `vncsession-start` by replacing:
```
exec "/usr/bin/vncsession" "${USER}" "${DISPLAY}"
```
with:
```
cd "/home/$USER"
source .bashrc
/usr/bin/vncsession "${USER}" "${DISPLAY}"
```
does not change anything.

**Comment by CendioOssman** [comment]
I've had a look at where GDM sets up the working directory and made sure we do the same thing in d43c1b3cc15df9031f7f27dbcd7bb1ab8ad6cc58.

Thanks for reporting!
