### ISSUE TITLE
Server version 1.11.0 not executing '~/.vnc/xstartup'

### ISSUE THREAD

**Issue by accetto** [TigerVNC/tigervnc#1109]
**Describe the bug**
The previous version 1.10.* has executed `~/.vnc/xstartup` and even generated the default one.
The new version 1.11.0 does not do that. It's a breaking change for quite a few scripts, I suppose.

**To Reproduce**
1. Create a file `~/.vnc/xstartup` containing for example

```bash
#!/bin/bash
echo "Executing xstartup..." > ~/.vnc/xstartup.log
```

2. Start VNC server like for example `vncserver :1`

3. Check if the file `~/.vnc/xstartup.log` exists

**Expected behavior**
The file `~/.vnc/xstartup.log` should exist

**Actual behavior**
The file `~/.vnc/xstartup.log` does not exist because the file `~/.vnc/xstartup` was not executed.
Remark: The  version 1.10.1 does execute the file.

**Client:**
 - OS: Windows 10 Pro, build 2004; WSL2; Docker Desktop 2.3.0.4
 - VNC client: TigerVNC Viewer 1.11.0
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server:**
 - OS: Docker container with Ubuntu 18.04 LTS and Xfce4 (e.g. modified [accetto/xubuntu-vnc](https://hub.docker.com/r/accetto/xubuntu-vnc)) and TigerVNC Server 1.11.0
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: TigerVNC distribution
 - Server was started using: `vncserver`

**Additional context**
It's TigerVNC Server in a Docker container (see above).

**Comment by CendioOssman** [comment]
I'm afraid that is on purpose. We no longer support that kind of startup. Instead sessions are started the same way as when you log on locally to your machine. This was necessary to fulfil all the requirements that desktop environments have so we could have something reliable.

We still support starting `Xvnc` in other ways though, but it will be up to you to put together a script that starts everything you need.

**Comment by kinghrothgar** [comment]
Can you point me in the right direction on how to emulate this previous behavior? How do I get a script executed at startup?

**Comment by accetto** [comment]
@kinghrothgar: Your question is probably not about my containers, but if it would be, then the script `/dockerstartup/vnc_startup.sh` would be one option to try.

**Comment by gwhizoftv** [comment]
Hi All, so the tigervnc docs still say that it will run xstartup !
