### ISSUE TITLE
xinit: XFree86_VT property unexpectedly has 0 items instead of 1

### ISSUE THREAD

**Issue by accetto** [TigerVNC/tigervnc#1110]
**Describe the bug**

After switching to TigerVNC Server **1.11.0** in my Docker containers I'm not able to find the reason for the following line in the log:

```log
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
```

The whole log after starting the TigerVNC Server using `vncserver` looks like this:

```log
Using desktop session xfce
xauth:  file /home/headless/.Xauthority does not exist

New 'f50257795684:1 ()' desktop is f50257795684:1

Starting desktop session xfce
xinit /etc/X11/Xsession startxfce4 -- /usr/bin/Xvnc :1 -allowoverride desktop,AcceptPointerEvents,SendCutText,AcceptCutText,SendPrimary,SetPrimary,BlacklistTimeout,BlacklistThreshold -blacklistthreshold 20 -blacklisttimeout 1 -depth 24 -geometry 1360x768 -auth /home/headless/.Xauthority -desktop f50257795684:1 () -fp /usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1 -pn -rfbauth /home/headless/.vnc/passwd -rfbport 5901 -rfbwait 30000
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc TigerVNC 1.11.0 - built Sep  8 2020 12:27:03
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12001000, The X.Org Foundation


Wed Sep 23 16:16:46 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
```

Originally I've suspected that the following warning has something to do with that

```log
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
```

but unfortunatelly nothing changes even if I run the container as `root` user.

**The Questions**

1. Is that a problem or can I safely ignore it?
2. Can you tell what causes that?

**To Reproduce**

I'll describe it in the next comment because I want to publish a special branch on GitHub and a Docker image on Docker Hub for you to make it easier to test.

**Comment by accetto** [comment]
**To Reproduce**

1. Pull the Docker image tagged **dev** from the Docker Hub repository [accetto/xubuntu-vnc](https://hub.docker.com/repository/docker/accetto/xubuntu-vnc) using

```bash
docker pull accetto/xubuntu-vnc:dev
```

2. Create a container using

```bash
docker run -dP --rm accetto/xubuntu-vnc:dev
```

The container will map its TCP port `5901` to the first free port on your host, for example `32768`. You can check it using `docker ps`.

3. Contect to the container using TigerVNC Viewer. The VNC password is **headless**.

4. Check the log file `/dockerstartup/vnc_startup.log`. It will have the content described in the previous comment.

**Additional Information**

The source  code for the container is in the branch [tigervnc11](https://github.com/accetto/xubuntu-vnc/tree/tigervnc11) of the GitHub repository [accetto/xubuntu-vnc](https://github.com/accetto/xubuntu-vnc). Please not that only the base image in the folder `/xubuntu-vnc/docker/xubuntu-vnc` is modified for the test.

The VNC Server is started by the [vnc_startup.sh](https://github.com/accetto/xubuntu-vnc/blob/master/docker/xubuntu-vnc/src/startup/vnc_startup.sh) script. It also creates the configuration file `.vnc/config`.

In the [Dockerfile](https://github.com/accetto/xubuntu-vnc/blob/master/docker/xubuntu-vnc/Dockerfile) you can see that I also add `print @cmd` just before `exec(@cmd` in the `vncserver` script, so you can see the whole command line in the log. Thanks @CendioOssman for the tip. :)

The Docker image is based on `Ubuntu 18.04 LTS` with `Xfce4`. The VNC Server is the version **1.11.0**. In the Dockerfile you can see how it is installed.

You can run the container also interactivelly skipping the VNC start using

```bash
docker run -itP --rm accetto/xubuntu-vnc:dev --skip bash
```

and then start the VNC Server manually from inside the container using

```bash
/dockerstartup/vnc_startup.sh
```

It will allow you to check or modify anything before starting the VNC server.

For the case you need to use `sudo`, the password is **headless**.

**Comment by CendioOssman** [comment]
>     1. Is that a problem or can I safely ignore it?
> 

It's likely harmless. I would assume it is some optional stuff in xinit that doesn't work on a headless X server such as Xvnc.

>     2. Can you tell what causes that?

No idea. You'd have to investigate xinit to see what it is up to. It's not something I've really noticed before.
