### ISSUE TITLE
High DPI is all kinds of broken on Windows...

### ISSUE THREAD

**Issue by jeffatrad** [TigerVNC/tigervnc#1111]
Just have a high dpi Windows monitor client on a high dpi Windows server.  The client scales the window, the server double scales the mouse, probably other nonsense too. Both sides should tell Windows that you want no scaling - at least you'd get native scaling that way. Once that is working, think about client side scaling (but that's not important). Right now, nothing really works if either side is high dpi, but when both are, it's really nuts.

Here's what we do:

typedef HRESULT WINAPI setdpitype(S32 v);

void AllowHighDPIwithNoScaling(void)
{
  HMODULE h=LoadLibrary("Shcore.dll");
  if (h)
  {
    setdpitype * sd = (setdpitype*)GetProcAddress(h,"SetProcessDpiAwareness");
    if (sd )
      sd(1);
  }
}

**Comment by CendioOssman** [comment]
Unfortunately there has been very little work so far on high dpi handling. Please see #369 and #494.
