### ISSUE TITLE
Use the server-side mouse pointers sent via XFIXES, if available (x11vnc)

### ISSUE THREAD

**Issue by apocalyptech** [TigerVNC/tigervnc#1112]
**Describe the bug**

When connecting to an x11vnc server, I'd like to see the "proper" mouse pointers as sent by the VNC server via the XFIXES protocols.  When I start up x11vnc, for instance, I see:

    24/09/2020 20:17:01 XFIXES available on display, resetting cursor mode
    24/09/2020 20:17:01   to: '-cursor most'.
    24/09/2020 20:17:01   to disable this behavior use: '-cursor arrow'
    24/09/2020 20:17:01   or '-noxfixes'.
    24/09/2020 20:17:01 using XFIXES for cursor drawing.
    24/09/2020 20:17:01 GrabServer control via XTEST.

And when I connect, among the output from x11vnc is:

    24/09/2020 20:17:07 Enabling X-style cursor updates for client <ip address>

I can connect to this server with at least a few other VNC clients (tested with gvncviewer, and vinagre) and they pick up the XFIXES cursors (after a few seconds of connecting; it always seems to take awhile).

Weirder still is that I could've *sworn* that this was working in the past, but I can't pinpoint when.  There hasn't been a new x11vnc version since early 2019 (v0.9.16, which is what I'm using), and I've gone through and compiled past versions of TigerVNC's vncviewer all the way back to 1.7.1, and none of them are doing it, either.  (I'd started with the most recent, 1.11.0.)  It could be that some update to Xorg is the culprit here; some change to how XFIXES works, or something - I dunno.  I haven't found anything that I can bisect to try and narrow down a point where it was working in the past.

Let me know if I can provide any more detail!

**To Reproduce**
1. Launch x11vnc (0.9.16) on a remote host
1a. Ensure that x11vnc reports that it's making use of XFIXES for cursor notifications
2. Connect to server using vncviewer

**Expected behavior**
Should see the mouse cursor change as-appropriate while moving around (text-select over text, window-resize on the edge of windows, etc) -- a few seconds after the connection (that always seems to take awhile to initialize)

**Client (please complete the following information):**
- OS: Arch Linux
- VNC Client: TigerVNC
- VNC Client version: 1.11.0-5 (Arch package, though also tested with manual compilations from git, versions 1.11.0, 1.10.1, 1.9.0, 1.8.0, and 1.7.1)
- Client downloaded from: Arch package, initially, but also checked out git and compiled from source

**Server (please complete the following information):**
- OS: Arch Linux
- VNC Server: x11vnc
- VNC Server version: 0.9.16-3
- Server downloaded from: Arch package
- Server was started using: `x11vnc -display :0 -xkb -skip_keycodes 187,188 -repeat`

**Comment by CendioOssman** [comment]
This should work just fine, so please use the issue bug template instead so we can start figuring out what might be wrong.

A first guess though is that you are using Arch Linux which currently has broken this specific feature in their build.

**Comment by apocalyptech** [comment]
Oh!  I am indeed using Arch; that's a bizarre decision for 'em.  I'd taken a look at their packaging file for it and hadn't noticed anything unusual, but clearly I wasn't looking hard enough.  If it's something Arch is doing specifically, I'll just take it up with them instead.  Thanks for the reply!

**Comment by CendioOssman** [comment]
The bug is in Arch's FLTK, not TigerVNC itself. So it's FLTK that needs to be rebuilt properly if you want to work around this.

**Comment by apocalyptech** [comment]
Oh, okay, thanks for the pointer!  I'll look into that, then. Thanks a bunch!

**Comment by apocalyptech** [comment]
Just for the sake of anyone else who might stumble across this while googling the same problem, the issue on the Arch side is that the fltk package doesn't explicitly require libxcursor, so when the Arch build system creates the package, it's made without libxcursor support (which is what breaks this functionality for TigerVNC).  If you grab the latest package definition files and build the fltk package *yourself*, on a system which has libxcursor installed, you'll end up with an fltk which TigerVNC is happy with, in terms of cursor support.  So that's a workaround for now, at least.  Some relevant bugs on the Arch side:

https://bugs.archlinux.org/task/67295?project=5&string=fltk
https://bugs.archlinux.org/task/67916?project=5&string=fltk

Thanks again for the info!
