### ISSUE TITLE
vncserver: Couldn't find suitable Xsession.

### ISSUE THREAD

**Issue by SKTT1Ryze** [TigerVNC/tigervnc#1113]
When I run `vncserver` command on my system,error occurs:  
```
vncserver: Couldn't find suitable Xsession.
```
My system is `Manjaro 20.1`, Kernel: x86_64 Linux 5.8.6-1-MANJARO  
And I install `tigervnc` by:  
```
sudo pacman -S tigervnc
```
I don't know why this error occurs and how to fix it, so I create this issure to ask for help.  

Thanks for your suggestions.

**Comment by CendioOssman** [comment]
You should not be running the `vncserver` command directly anymore as all sessions should be started as a service. I would recommend you file a bug with Manjaro that they shouldn't put that command in `$PATH`.

That said, your particular issue will likely remain even when starting things as a service.

We now start sessions the same way as when you log on locally on a machine. That means you need to have everything installed that powers that machinery. On many systems this is included when xinit is installed, but unfortunately I don't know about Manjaro. Please file a bug with them that there is some dependency missing in their packaging of TigerVNC. Hopefully they can quickly help you out.

**Comment by SKTT1Ryze** [comment]
Thanks
