### ISSUE TITLE
authentication error using x509

### ISSUE THREAD

**Issue by SunMoondeveloper** [TigerVNC/tigervnc#1117]
hi,
   I am newly setup the tigervnc.
   I refer the below link
     https://wiki.archlinux.org/index.php/TigerVNC

   Then I used security type x509vnc
   I create a key using openssl
      https://wiki.archlinux.org/index.php/OpenSSL

  but it is now working.
  any one can resolve the issue or guide me to resolve the issue

**Comment by CendioOssman** [comment]
Please use the bug issue form so we get a better picture of what you are trying to do.

**Comment by CendioOssman** [comment]
No response. Closing.
