### ISSUE TITLE
Latin1 text encoding in ServerCutText messages is invalid

### ISSUE THREAD

**Issue by MarcusWichelmann** [TigerVNC/tigervnc#1119]
**Describe the bug**
When a client receives a `ServerCutText` messages from the TigerVNC server, the sent text bytes are neither valid Latin1 (ISO-8859-1) nor UTF-8 or anything else. This results in the received text not being equal to the text that has been copied on the server side.

For example, if I select and copy a german umlaut like `ä` in the remote session, the client then receives a `ServerCutMessage` with a `length` of 2 and two bytes for the text: `0xE4 0x3F`.
When decoding this using ISO-8859-1, you get `ä?` and with UTF-8 `�?` (but thats expected).

This doesn't happen with the TigerVNC Java client, I suppose it's using the extended clipboard protocol and therefore isn't effected.

**To Reproduce**
1. Use a VNC Viewer like Remmina to connect to a TigerVNC server.
2. Go to some web page and copy a `ä`
3. On your local system, go to some text editor and paste what's in your clipboard
4. You get `ä?`

**Expected behavior**
What get's pasted should be eqaul to what has been copied.

**Server:**
 - OS: Fedora 32 Workstation
 - VNC server: TigerVNC
 - VNC server version: tigervnc-1.11.80-20200824gitac76a87.x86_64 from http://tigervnc.bphinz.com/nightly/
 - Server was started using: `vncserver -log *:stderr:100 -pixelformat RGB888`

**Comment by CendioOssman** [comment]
I can reproduce that here as well. Let me have a look.

**Comment by CendioOssman** [comment]
Seems to be various issues here. Not sure how we managed to miss this in testing. But it's late here so I'll have to look at this next week.

**Comment by MarcusWichelmann** [comment]
Is there no library you could use for this whole charset conversion thing? Implementing this on your own looks far too error-prone to me.
Or what's the reason you chose to do it this way?

**Comment by CendioOssman** [comment]
Nothing convenient unfortunately, and adding new dependencies always creates a hassle for our users. This was supposed to be some easy transforms so it was sloppy to let these bugs go unnoticed. :/
