### ISSUE TITLE
Feature request: Support for relative mouse movements

### ISSUE THREAD

**Issue by badda71** [TigerVNC/tigervnc#1121]
Sometimes applications require relative mouse movements rather than an absolute mouse position.
Especially 3D-games are not playable with absolute mouse movements, only relative ones (almost all 3D games).
I tested this with RealVNC (RealVNC supports relative mouse movements) and there, the games are playable. However, RealVNC uses a proprietary protocol extension for this.
TigerVNC could be easily extended using the General Input Interface extension (gii pseudo-encoding) to support relative mouse movements.
This would have the additional benefit of adding Joystick/Gamepad support to UltraVNC.

**Comment by CendioOssman** [comment]
Would be nice. Please see #619 where we already track this feature.
