### ISSUE TITLE
Something wrong with the nigthly build from 2020-10-05?

### ISSUE THREAD

**Issue by accetto** [TigerVNC/tigervnc#1122]
Is there something wrong with the nightly built from 2020-10-05?

I'm getting the following error by building my Docker container:

```log
Step 12/34 : RUN wget -qO- https://tigervnc.bphinz.com/nightly/xc/x86_64/tigervnc-1.11.80-20201005git2ca7d26.x86_64.tar.gz | tar xz --strip 1 -C /
 ---> Running in 93c216c3dab0

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/bash -c wget -qO- https://tigervnc.bphinz.com/nightly/xc/x86_64/tigervnc-1.11.80-20201005git2ca7d26.x86_64.tar.gz | tar xz --strip 1 -C /' returned a non-zero code: 2
```

Has something changed or am I doing something wrong?

**Comment by CendioOssman** [comment]
It works fine without TLS. I'm not sure it has even had TLS enabled. @bphinz?

**Comment by bphinz** [comment]
Correct, it's just an amazon S3 container and I have never bothered to SSL
enable it (nor do I see any reason to...)

**Comment by CendioOssman** [comment]
So I guess you somehow got `http` swapped for `https` at some point @accetto ?

Nothing we can really fix here, so I'll go ahead and close this.

**Comment by accetto** [comment]
Sorry, it was really my fault. I've missed that copy-and-paste error. I apologize for bothering you. :(
I can confirm, that the nightly build from 2020-10-05 installs correctly.
Thanks for the answers.
