### ISSUE TITLE
Discuss generating dynamic library

### ISSUE THREAD

**Issue by KangLin** [TigerVNC/tigervnc#1123]
Generate dynamic library development library to facilitate other projects. I have generated a static development library, see: #1114

The current common is divided into four sub-libraries: os, network, rdr, and rfd.

Advantage:
The classification of the library is clear.

Disadvantages:
1. Large number of libraries
2. The library name is easy to conflict with other projects
3. When this project is implemented, there are cross dependencies, so it cannot generate dynamic libraries.

Solution:
1. The source code directory maintains the existing structure, but only one library tiger is generated
2. Keep the current library structure. Increase the utility library, remove cross-dependence. Move Exception, loger, util, etc. to the utility

**Comment by CendioOssman** [comment]
I'm afraid I don't understand what issue you are trying to solve. We have no intention of being a general VNC library, so statically linking the common code makes things a lot easier for our own use.

Exactly what scenario are you trying to get working?

**Comment by KangLin** [comment]
I want to use vnc in my project. My project only cares about interface display and keyboard and mouse operations. The specific RFB agreement is completed by this project. Therefore, this project needs to be provided in the form of a library (dynamic library and static library).
In other words, my project implements the vncviewer, winvnc, vncpasswd, vncconfig of this project, but does not implement the rfb protocol.
My project is similar to Remmina.
If this project provides a development library, then other projects that use vnc may use it.

**Comment by CendioOssman** [comment]
I'm afraid that is outside the goals of this project. Maintaining a stable library is a lot of work. Doing so for C++ is much much worse. So it's unfortunately not something we can take on at this time.

I suggest having a look at libvncclient. That project is designed for use as a library.

**Comment by KangLin** [comment]
libvncclient is C . But I need C++.  maintaining a stable library is eary.
