### ISSUE TITLE
Xvncviewer in Jumperserver suddenly appeard connection error

### ISSUE THREAD

**Issue by leon-fans** [TigerVNC/tigervnc#1124]
**Describe the bug**
Xvncviewer in Jumperserver suddenly appeard connection error

**To Reproduce**
1.Using the VNCviewer in Jumperserver connect the Centos7.6 Gnome desktop
2.a few minutes later, appeared connection error

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. Centos ]
 - VNC client: [e.g. TigerVNC, ]
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g.Centos  7.6]
 - VNC server: [TigerVNC]
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver`]

**Additional context**
Add any other context about the problem
![vnc client connection error](https://user-images.githubusercontent.com/8859297/96072868-d50ba600-0ed7-11eb-9637-b10429bf11e9.png)

**Comment by CendioOssman** [comment]
I'm afraid that dialog is not from TigerVNC so it isn't something we can help out with.
