### ISSUE TITLE
Gnome and TigerVNC 1.11.0 display a black screen

### ISSUE THREAD

**Issue by Inglebard** [TigerVNC/tigervnc#1126]
**Describe the bug**
Launch vncserver with gnome session display a black screen.

**To Reproduce**
-Add a user mapping to /etc/tigervnc/vncserver.users
-Edit $HOME/.vnc/config and add session=gnome
-Start  `sudo systemctl start vncserver@:2`

**Expected behavior**
Display the desktop environment in vnc viewer.

**Client:**
 - OS: Archlinux
 - VNC client: remmina
 - VNC client version: 1.4.8
 - Note : same issue with TigerVNC viewer 1.11.0

**Server:**
 - OS: Archlinux
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: my Linux distribution
 - Server was started using: vncserver

**Additional context**
Before version 1.11.0, I needed to update the Xstartup file. Since it is no used anymore in 1.11.0, how to deal with it ?
Use Xvnc create the same issue.
Use lxqt as session seems to work.

**Comment by CendioOssman** [comment]
Alright, so let's try to figure out what has gone wrong. What does the log in `~/.vnc` say? And can you see if there is something about your session in `journalctl`?

Are you also logged on locally on this machine as the same user?

**Comment by Inglebard** [comment]
Hi @CendioOssman ,
Here is the vnc log : 

```
Using desktop session gnome

New 'davidPC:2 (david)' desktop is davidPC:2

Starting desktop session gnome


Xvnc TigerVNC 1.11.0 - built Sep 19 2020 16:42:42
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12008000, The X.Org Foundation


Tue Oct 20 10:24:03 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5902
 vncext:      created VNC server for screen 0
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/etc/gdm/Xsession: Beginning session setup...
localuser:david being added to access control list
/etc/gdm/Xsession: Setup done, will execute: /usr/bin/gnome-session

Tue Oct 20 10:24:10 2020
 Connections: accepted: [::1]::40268
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type TLSVnc (258)

Tue Oct 20 10:24:12 2020
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888
```

Here is the journalctl log after I start vnc : https://gist.github.com/Inglebard/49229e7ec5a58670917f7678fbd75e29 

Yes, I use the same user locally and remotely. When I try to connect remotely, I am already connected locally.

**Comment by CendioOssman** [comment]
> Yes, I use the same user locally and remotely. When I try to connect remotely, I am already connected locally.

Unfortunately that isn't supported by the distributions these days. Could you test if things work if you start the VNC session without anyone logged on locally?

**Comment by Inglebard** [comment]
Yes, it works.
If it's not possible to be solve, we can close the issue, I think.

**Comment by CendioOssman** [comment]
Not from our end unfortunately. But feel free to file a bug with GNOME or your distribution that this is a use case you want.
