### ISSUE TITLE
Tigervnc on ubuntu 18 server without descktop

### ISSUE THREAD

**Issue by Venom1p** [TigerVNC/tigervnc#1129]
is it possible to use tigervnc on ubuntu 18 server, so without screen, but with virtual screens like brouser like "google chrome"?

**have this log**
usr/bin/startxfce4: X server already running on display :6
gpg-agent[28733]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:28719): xfce4-session-WARNING **: 11:39:28.992: gpg-agent returned no PID in the variables

(xfce4-session:28719): xfce4-session-WARNING **: 11:39:28.993: xfsm_manager_load_session: Something wrong with /home/venomtv/.cache/sessions/xfce4-session-ns3022246:6, Does it exist? Permissions issue?

(xfwm4:28736): xfwm4-WARNING **: 11:39:29.053: Error opening /dev/dri/card0: Permission denied
(uint32 1,)

(nm-applet:28767): nm-applet-WARNING **: 11:39:29.143: NetworkManager is not running

** (xfdesktop:28744): WARNING **: 11:39:29.239: Failed to set the background '/usr/share/backgrounds/xfce/xfce-teal.jpg': GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.DisplayManager.AccountsService'
Error executing command as another user: Not authorized

This incident has been reported.
Gtk-Message: 11:39:32.108: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by CendioOssman** [comment]
That should work fine. Could you please fill out the bug report template so we can get an idea of your setup?

**Comment by Venom1p** [comment]
what do you mean by "bug report templat" I installed everything on ubuntu server so without desktop

and use this guide: 
https://linuxize.com/post/how-to-install-and-configure-vnc-on-ubuntu-18-04/

**Comment by CendioOssman** [comment]
When you opened this issue you got a choice to file a bug report, which gives you a template in markdown to fill out. Use that template to add a new comment here.
