### ISSUE TITLE
Restream remote desktop

### ISSUE THREAD

**Issue by Venom1p** [TigerVNC/tigervnc#1133]
**is it possible to restream the remote desktop?**

**Comment by CendioOssman** [comment]
I'm afraid I don't quite understand what you mean when you say restream. Could you describe in more detail what you want to do?

**Comment by Venom1p** [comment]
thanks for answear this have solved 

ffmpeg command `-f x11grab -i :2 `
where: 2 is the remote desktop I have from tigerVNC
