### ISSUE TITLE
there is no audio?

### ISSUE THREAD

**Issue by Venom1p** [TigerVNC/tigervnc#1134]
there is no audio? in remote desktop i don't have audio!

**Comment by bphinz** [comment]
That's because there is no universal standard for audio in the RFB protocol.  Custom/proprietary implemntations exist, and I believe it's possible to proxy pulseaudio over SSH, but TigerVNC does not natively  provide support for audio.

**Comment by Venom1p** [comment]
ok it's clear, but can you have an example of how it works?
