### ISSUE TITLE
tigervnc screen capture

### ISSUE THREAD

**Issue by Venom1p** [TigerVNC/tigervnc#1138]
I'm trying to capture audio / video to make it "stream"
this wasn't too hard using "ffmpeg".

the problem now occurs to me if I want to do it with 2 remote desktops that have two different audio / video, the problem that mixes all the audio of ": 1" and ": 2"

i'm using ffmpeg whit this command:
`ffmpeg -f pulse -i default -ac 2 -f x11grab -framerate 30 -video_size 1280x720 \
	-i :1.0 -c:v libx264 -preset veryfast -b:v 1984k -maxrate 1984k -bufsize 3968k \
	-vf "format=yuv420p" -g 60 -c:a aac -b:a 128k -ar 44100 \
	-hls_segment_filename /home/streams/desktop1_%03d.ts -hls_flags delete_segments /home/streams/desktop1.m3u8 &`

has anyone experience how to take audio of: 1 and audio of: 2 avoiding mix of audio like I have them right now?

**Comment by bphinz** [comment]
I'm sorry, but this is an ffmpeg question, not tigervnc and it's really outside our scope of support.  That being said, have a look at the '-map' option of ffmpeg ;)
