### ISSUE TITLE
Qt apps come up as an empty white box on Linux

### ISSUE THREAD

**Issue by dstromberg** [TigerVNC/tigervnc#1139]
**Describe the bug**
Qt apps come up as an empty white box (keepassxc, hello world) on Linux, or segfault (konsole).

**To Reproduce**
1. Start tiger vnc server on a Linux system
2. Connect to that tiger vnc server using tiger vnc viewer
3. Run a Qt app like a "hello world" or keepassxc
4. Observe the broken app

**Expected behavior**
I expect widgits in the windows instead of an empty white rectangle

**Code**
This minimal Qt hello world program exhibits the bug:
#include <QtWidgets/QApplication>
#include <QtWidgets/QPushButton>

int main( int argc, char **argv ) {
  QApplication a( argc, argv );

  QPushButton hello( "Hello world!", 0 );
  hello.resize( 100, 30 );

  hello.show();
  return a.exec();
}

I'm compiling it and linking it with the following Makefile:
CPPFLAGS=-I/usr/include/x86_64-linux-gnu/qt5 -fPIC
LDFLAGS=-lQt5Core -lQt5Widgets

go: qt-hello-world
	./qt-hello-world

qt-hello-world: qt-hello-world.o
	g++ -o qt-hello-world qt-hello-world.o ${LDFLAGS} 

**Client (please complete the following information):**
 - OS: Debian 10.6
 - VNC client: TigerVNC
 - VNC client version: 1.9.0+dfsg-3+deb10u2
 - Client downloaded from: my Linux distribution

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - VNC server: TigerVNC
 - VNC server version: 1.7.0+dfsg-8ubuntu2
 - Server downloaded from: my Linux distribution
 - Server was started using: vncserver -geometry 1920x1003

**Additional context**
The same 'hello world' and keepassxc binaries both work correctly over ssh X11 tunneling between the same two computers.

Thanks for the cool tools!

**Comment by CendioOssman** [comment]
That's a very old TigerVNC. Could you test with the current 1.11.0 release?

**Comment by dstromberg** [comment]
Is there any signifcance to the 0x0mm?

$ xdpyinfo | grep dimen
below cmd output started 2020 Tue Oct 27 06:40:56 PM PDT
dimensions: 1920x1042 pixels (0x0 millimeters)

**Comment by CendioOssman** [comment]
That means it didn't get any physical dimensions for the fake monitor. Current versions should fake something there.

I'll close this for now. If you still see issues with a current version of TigerVNC then let us know.
