### ISSUE TITLE
Don't connect

### ISSUE THREAD

**Issue by TheFJS14** [TigerVNC/tigervnc#1140]
**Describe the bug**
When I turn on both computers, first I turn on the server (Linux Mint 20) and then I connect from Windows. The next morning, the computer decides not to connect and I try restarting both computers. I always run the same command to connect, I check the IP but nothing changes, only that it doesn't want to connect.

**To Reproduce**
1.- Start both computers
2.- Works properly
3.- I go to bed
4.- Next morning I don't have any connection

**Expected behavior**
I hope that it connects each other

**Screenshots**
![image](https://user-images.githubusercontent.com/25939369/97406666-deded180-18f9-11eb-8cba-d840f3028f36.png)
![image](https://user-images.githubusercontent.com/25939369/97407186-9c69c480-18fa-11eb-92df-81f7018dd9ac.png)

**Client (please complete the following information):**
 - OS: Windows 10 
 - VNC client: VNC Viewer
 - VNC client version: 6.20.529 - Client downloaded from: [here](https://www.realvnc.com/es/connect/download/viewer)

**Server (please complete the following information):**
 - OS: Linux Mint 20 (where TygerVNC is installed)
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: [here](https://bintray.com/tigervnc/stable/download_file?file_path=tigervnc-1.11.0.x86_64.tar.gz)
 - Server was started using: dont know

**Additional context**
I think that any mysterious force change anything on Linux Mint

**Comment by TheFJS14** [comment]
When I start my Linux laptop, I write this on terminal:

```
x0vncserver -display :0 -rfbport 5900 -passwordfile ~/.vnc/passwd -Log *:stderr:100 -BlacklistThreshold 10 -BlacklistTimeout 5 -MaxProcessorUsage 70
```
And next, I only put the address on VNC Viewer, and it should connect with password.

**Comment by CendioOssman** [comment]
And what does the log output from `x0vncserver` look like?

**Comment by TheFJS14** [comment]
![image](https://user-images.githubusercontent.com/25939369/97423103-0b511880-190f-11eb-95d2-e33b674e13d8.png)

Just this

**Comment by TheFJS14** [comment]
The problem I think is client side. Server doesn't report any error

**Comment by CendioOssman** [comment]
Your client is RealVNC, so unfortunately it is not something we can help you out with. I'm afraid you'll have to report any issues to them.

Have you tried our client instead?

**Comment by TheFJS14** [comment]
I am using VNCViewer, just got it on download page 
![image](https://user-images.githubusercontent.com/25939369/97425732-c6c77c00-1912-11eb-8c8f-800333b06755.png)

I didn't know that you got a client. (I am so noob on this, I am learning right now haha)
Where could I download it?

**Comment by CendioOssman** [comment]
That is our client, so you've found the right link. But your screen shot showed RealVNC and not TigerVNC. So please see what happens if you use that vncviewer 1.11.0.

**Comment by TheFJS14** [comment]
I noticed that I enabled firewall and didn't enabled 5900 port.

SO to @EduFdezSoy
