### ISSUE TITLE
"Attempted to configure an invalid screen layout" when connecting to a UltraVNC server

### ISSUE THREAD

**Issue by zhou13** [TigerVNC/tigervnc#1143]
**Describe the bug**
I get an error message `Attempted to configure an invalid screen layout` when coonect to a ultravnc server. Other clients such as gvncviewer works OK.

```
TigerVNC Viewer 64-bit v1.11.0
Built on: 2020-09-19 16:42
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Sat Oct 31 16:38:02 2020
 DecodeManager: Detected 8 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       Connected to host p150sma.local port 5900
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VncAuth(2)

Sat Oct 31 16:38:06 2020
 DesktopWindow: Adjusting window size to avoid accidental full screen request
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Attempted to configure an invalid screen layout
```

**To Reproduce**
Same as the summary.

**Client (please complete the following information):**
 - OS: Archlinux
 - VNC client: TigerVNC
 - VNC client version: v1.11.0
 - Client downloaded from: Linux distribution]

**Server (please complete the following information):**
 - OS: Windows 10
 - VNC server: UltraVNC
 - VNC server version: 1.3.0 alpha
 - Server downloaded from: official website
 - Server was started using: windows service

**Additional context**
I will add more information if necessary.

**Comment by zhou13** [comment]
It seems that UltraVNC 1.2.4 works fine.

**Comment by CendioOssman** [comment]
Hmm... Odd. Could you run with `-Log *:stderr:100` on the client? The extra logging should hopefully tell us what it layout it's trying to configure.

**Comment by sjuxax** [comment]
I'm getting this too. The log output from TigerVNC doesn't report anything more than the error message displayed, but TurboVNC provides:

```
PlatformPixelBuffer: Native pixel format is depth 24 (32bpp) little-endian rgb888
PlatformPixelBuffer: Native pixel format is depth 24 (32bpp) little-endian rgb888
CConn: Using pixel format depth 24 (32bpp) little-endian rgb888
CConn: Requesting Tight encoding
CConn: Screen 0 work area: 0, 0 1920 x 1044
CConn: Spanned work area: 0, 0 1920 x 1044
Viewport: Set geometry to 0, 0 1920 x 1044
CMsgReaderV3: Server supports GII version 1
CConn: Enabling GII
ScreenSet: LAYOUT RECEIVED:
ScreenSet:     1 (0x1): 0x0+0+0 (flags 0x0)
CMsgHandler: Server sent us an invalid screen layout
ScreenSet: LAYOUT SENT:
ScreenSet:     1 (0x1): 1920x996+0+0 (flags 0x0)
Viewport: Successfully created device 1 (Wacom HID 5215 Pen stylus)
Viewport: Successfully created device 1 (Wacom HID 5215 Finger touch)
Viewport: Successfully created device 1 (Wacom HID 5215 Pen eraser)
CMsgReader: Rect too big: 1920x34 at 0,0 exceeds 0x0
Rect too big
```

This is definitely a bug in WinVNC 1.3 alpha considering it affects both viewers and seems to be sending a 0x0 screen geometry.

**Comment by CendioOssman** [comment]
Indeed. So I'm afraid you'll have to file a bug with UltraVNC. Feel free to reference it here for others to find.

**Comment by acoul** [comment]
Greetings,

same issue on a Void/Linux_64 (musl library) (daily synced) with tigervnc-1.10.1_3

using [vinagre-3.22.0_3](https://en.wikipedia.org/wiki/Vinagre) works fine

**Comment by Neustradamus** [comment]
@RudiDeVos: Please look here.

**Comment by acoul** [comment]
@Neustradamus is here [here](https://github.com/ultravnc/UltraVNC/issues/8) perhaps ?

**Comment by Neustradamus** [comment]
@acoul: It is not the same bug no?

**Comment by bernd-wechner** [comment]
Dang, just got this myself as well, after upgrading my client to a 4K monitor. Worked fine before that. So now my tigervnc client is connecting from a system on a 4K monitor and refusing to. Grrr.
