### ISSUE TITLE
how to change display number

### ISSUE THREAD

**Issue by tempman5** [TigerVNC/tigervnc#1144]
Hi,

I've cloned a linux virtual machine. New machine has different IP and new hostname. It has installed tigervnc.

I'm seeing that display number in new virtual machine uses :2 and not :1 as original machine in the display number. So vnc is using 5902 and not 5901 as I want. How can I change that?

This is not a bug, I'm sorry, but asking for if someone can help me.

Thanks beforehand.

Cheers...

**Comment by bphinz** [comment]
It's hard to say without knowing how you started Xvnc, which distribution you are running, etc.  But it's probably just a matter of the original VM having lock files for desktop :1 in /tmp so vncserver or systemd incremented by one.  Try killing all running instances of Xvnc, removing any lock files from /tmp and /tmp/.X11-unix and then start a new vnc server session.

**Comment by tempman5** [comment]
Thanks!

It is CentOS 7.7, followed this guide - https://wiki.centos.org/es/HowTos/VNC-Server.

Funny now, I've deleted /tmp/.X0-lock and /tmp/.X11-unix dir and now it is using :3 display number. Should I try it again and next it will be :1? :-) Thanks beforehand.

**Comment by bphinz** [comment]
Sorry, I should have been more specific in my instructions.  You don't want
to delete X0 since that's the console, and I only meant for you to remove
the sockets in /tmp/.X11-unix.  I would reboot the machine to
re-create that dir with the proper permissions.  If you followed that guide
and are using the systemd service, then you should always get the same
display number for each user configured in /etc/sysconfig/vncservers.  On
the other hand, if you are just starting "on-demand" servers with the
vncserver script, then it will look to see which displays are already taken
and increment until it finds one.

**Comment by tempman5** [comment]
I've deleted dir that you said me but now it runs in port 5903 always (even doing same procedure or deleting and rebooting).
Not sure as it is starting, it was done by another colleague (he is not working now with me). If I look vncservers file, it shows:
# THIS FILE HAS BEEN REPLACED BY /lib/systemd/system/vncserver@.service
If I edit that file, it shows a howto:
# The vncserver service unit file
#
# Quick HowTo:
# 1. Copy this file to /etc/systemd/system/vncserver@.service
# 2. Replace <USER> with the actual user name and edit vncserver
#    parameters appropriately
#    (ExecStart=/usr/sbin/runuser -l <USER> -c "/usr/bin/vncserver %i"
#     PIDFile=/home/<USER>/.vnc/%H%i.pid)
# 3. Run `systemctl daemon-reload`
# 4. Run `systemctl enable vncserver@:<display>.service`

I've edited /etc file and it is modified with the user who runs the Xvnc process (it isn't root).
Both virtual machines has /etc/systemd/system/vncserver@:3.service file, but original is using 5901 port and new cloned continue now using 5903 port.
Should I fix this filename and putting :1 :-?
Thanks beforehand.

**Comment by tempman5** [comment]
Thank you very much for helping me. I've renamed vncserver@:3.service to vncserver@:1.service, stop vnc, deleted /tmp/.X11-unix dir and started vnc and it is using now 5901 port (it matches with display number). Thanks and I'm sorry for not seeing it before!

**Comment by CendioOssman** [comment]
Glad you got it running. Note though that this service is something Red Hat specific. Starting in TigerVNC 1.11.0 we have our own systemd service which is slightly different.
