### ISSUE TITLE
Keep one '.log.old' behind

### ISSUE THREAD

**Issue by jcpunk** [TigerVNC/tigervnc#1145]
**Is your feature request related to a problem? Please describe.**
When VNC crashes a number of my users instantly restart the server which seems to clear out my `~/.vnc/hostname:DISPLAY.log`.  Can the VNC server be adjusted to try and save the last log of so I can review it even if users restart the server?

**Describe the solution you'd like**
Can `~/.vnc/hostname:DISPLAY.log` be automatically moved over to `~/.vnc/hostname:DISPLAY.log.old`

**Describe alternatives you've considered**
I've tried asking the users to archive it themselves with limited success.

**Additional context**
Any chance server crashes could also go to syslog?

**Comment by CendioOssman** [comment]
I'm afraid no such functionality currently exists. We should probably look at logging to the journal, which is what modern local logins do.
