### ISSUE TITLE
rendering on macos bigsur shows empty windows

### ISSUE THREAD

**Issue by jrwren** [TigerVNC/tigervnc#1147]
All Windows are blank in macos bigsir 11.0.1

**To Reproduce**
1. launch tigerVNC
2. the connection details window is blank
3. press enter to accept your previous host
4. the authentication window is blank
5. press enter
6. the next window is blank.

**Expected behavior**
windows to not be blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/106443/99195399-5febf480-2753-11eb-8236-576319068c78.png)

**Client (please complete the following information):**
 - OS: macos big sir 11.0.1
 - VNC client: tigervnc
 - VNC client version: 1.10.1
 - Client downloaded from: github releases

**Server (please complete the following information):**
 - OS: linux
 - VNC server: tigervnc 
 - VNC server version: 1.7.0
 - Server downloaded from: github releases
 - Server was started using:  usr/bin/vncserver -autokill

**Comment by SinghArshdeep** [comment]
Reinstalling the software fixed it for me.

**Comment by jrwren** [comment]
Reinstall (deleting from Applications and dragging from DMG into Applications) worked. Very weird.

Thank you.
