### ISSUE TITLE
-localhost binds all interfaces port 6000+displaynumber

### ISSUE THREAD

**Issue by dkt5** [TigerVNC/tigervnc#115]
More detail https://bugs.gentoo.org/show_bug.cgi?id=538018
Seems to try listening on all interfaces to determine if a display number is available. No functioning connections are possible, but the port is open.

**Comment by CendioOssman** [comment]
Re. the upstream report, the `TcpListener` created in `displayNumFree()` will automatically be destroyed once that function exits.

What you are seeing is most likely the X11 port. `-localhost` only controls the VNC ports. If you don't want an X11 TCP port then use `-nolisten tcp`, which is an Xorg argument.
