### ISSUE TITLE
Update README for 1.11

### ISSUE THREAD

**Issue by mantkiew** [TigerVNC/tigervnc#1151]
**Describe the bug**
The README states

"You should normally use the vncserver script to start Xvnc."

However, these script is not available with version 1.11.

**To Reproduce**
1. Install vncserver 1.11 on Ubuntu 16 or 18.
2. Type `vnc<tab><tab>`
```
$ vnc<tab><tab>
vncconfig   vncpasswd   vncsession  vncviewer
```
Also
```
$ tigervnc
tigervncconfig   tigervncpasswd   tigervncsession
```

3. Type `vncserver` and see
```
$ vncserver

Command 'vncserver' not found
```
I was able to locate `vncserver` in 
```
$ ll /usr/lib/x86_64-linux-gnu/vncserver 
lrwxrwxrwx 1 root root 27 Nov 17 22:15 /usr/lib/x86_64-linux-gnu/vncserver -> /etc/alternatives/vncserver*
```

****
**Expected behavior**
A clear and concise description of how to install and configure TigerVNC server 1.11. 
Is an additional set alternatives step needed during installation?

**Server (please complete the following information):**
 - OS: Ubuntu 16 and 18
 - VNC server: TigerVNC
 - VNC server version: 1.11
 - Server downloaded from: https://bintray.com/tigervnc/stable/tigervnc/1.11.0
 - Server was started using: [e.g. `vncserver`]

Also, there's no good guide about how to setup a service for TigerVNC server 1.11. A few available third-party guides are outdated for 1.11.

**Comment by mantkiew** [comment]
After digging deeper on ubuntu alternatives setup. It seems the problem is there:
```
$ ll /etc/alternatives/ | grep vnc
vncconfig -> /usr/bin/tigervncconfig*
vncconfig.1.gz -> /usr/share/man/man1/tigervncconfig.1.gz
vncpasswd -> /usr/bin/tigervncpasswd*
vncpasswd.1.gz -> /usr/share/man/man1/tigervncpasswd.1.gz
vncserver -> /usr/lib/x86_64-linux-gnu/tigervncserver*
vncserver.8.gz -> /usr/share/man/man8/tigervncserver.8.gz
vncsession -> /usr/sbin/tigervncsession*
vncsession.8.gz -> /usr/share/man/man8/tigervncsession.8.gz
vncviewer -> /usr/bin/xtigervncviewer*
vncviewer.1.gz -> /usr/share/man/man1/xtigervncviewer.1.gz
x0vncserver -> /usr/bin/x0tigervncserver*
x0vncserver.1.gz -> /usr/share/man/man1/x0tigervncserver.1.gz
Xvnc -> /usr/bin/Xtigervnc*
Xvnc.1.gz -> /usr/share/man/man1/Xtigervnc.1.gz
xvncviewer -> /usr/bin/xtigervncviewer*
xvncviewer.1.gz -> /usr/share/man/man1/xtigervncviewer.1.gz
```
and I this works
```
$ update-alternatives --display vncviewer 
vncviewer - auto mode
  link best version is /usr/bin/xtigervncviewer
  link currently points to /usr/bin/xtigervncviewer
  link vncviewer is /usr/bin/vncviewer
  slave vncviewer.1.gz is /usr/share/man/man1/vncviewer.1.gz
  slave xvncviewer is /usr/bin/xvncviewer
  slave xvncviewer.1.gz is /usr/share/man/man1/xvncviewer.1.gz
/usr/bin/xtigervncviewer - priority 74
  slave vncviewer.1.gz: /usr/share/man/man1/xtigervncviewer.1.gz
  slave xvncviewer: /usr/bin/xtigervncviewer
  slave xvncviewer.1.gz: /usr/share/man/man1/xtigervncviewer.1.gz
```
However, the group `vncserver` does not exist and no info can be displayed:
```
$ update-alternatives --display vncserver
update-alternatives: error: no alternatives for vncserver
```
Is that intentional? Or setup of this group is missing?

**Comment by bphinz** [comment]
The README needs to be updated, and we need to provide better documentation
on using the new systemd service

**Comment by CendioOssman** [comment]
The README was updated in 32222b3bf61974f1e26ef857cd44fe710a229f86, but apparently I missed some references. Should be fixed in 76443e0899f6057f443d6604fb1e6635626fce6c.

More documentation is always nice though. Fedora has written a HOWTO they include in their packaging. Perhaps that is something that can be submitted upstream, @grulja?

**Comment by grulja** [comment]
> More documentation is always nice though. Fedora has written a HOWTO they include in their packaging. Perhaps that is something that can be submitted upstream, @grulja?

Same HOWTO is included even in RHEL 8. I will try to polish it and submit as PR.

**Comment by CendioOssman** [comment]
@grulja, any luck with that PR? :)

**Comment by grulja** [comment]
> @grulja, any luck with that PR? :)

No, sorry, I totally forgot. I will do it soon.
