### ISSUE TITLE
Make vncviewer compatible with broken VNC KVM servers (invalid pixel format)

### ISSUE THREAD

**Issue by rorait** [TigerVNC/tigervnc#1156]
I've seen some VNC servers (used as remote KVM in datacenters) to fail with vncviewer while working fine with vinagre.
The reason is shown in vinagre logs:
```
(vinagre:1076276): gtk-vnc-DEBUG: 18:18:04.143: ../src/vncconnection.c Pixel format BPP: 8,  Depth: 8, Byte order: 1234, True color: 1
             Mask  red:   7, green:   7, blue:   3
             Shift red:   5, green:   2, blue:  32
```
where the blue channel is shifted by 32 bits (!!??), which makes vncviewer very unhappy,
see `common/rfb/PixelFormat.cxx` `bool PixelFormat::isSane(void)`.

I've verified that this simple patch makes the connection successful.
```
bool PixelFormat::isSane(void)
{
  int totalBits;

  fprintf(stderr,"isSane %d %d %d %d %d %d\n",redMax, greenMax, blueMax, redShift, greenShift, blueShift);
  if(blueShift==32){
    blueShift=0;
    fprintf(stderr,"isSane %d %d %d %d %d %d -- corrected\n",redMax, greenMax, blueMax, redShift, greenShift, blueShift);
  }
```
How can this be handled? Can it be managed as a special known compatibility quirk? (checking the entire pixel configuration, instead of just testing the blueShift)

**Comment by CendioOssman** [comment]
Usually there isn't anything good in the protocol to identify servers for quirks like this. And I'm very hesitant to blindly assume that an invalid 32 always means 0.

What KVMs are these?

It would also be interested to figure out exactly how vinagre deals with these.

**Comment by rorait** [comment]
I'm getting this shift=32 value from KVM consoles that a certain cloud provider gives you to control "virtual server instances" (i.e. virtual machines).

A quick grep in the vinagre code (gtk-vnc/src/) shows things like:
`(blue << priv->fmt.blue_shift));`
`((blue & priv->fmt.blue_max) << priv->fmt.blue_shift));`
`| (pixel[2] << priv->fmt.blue_shift);`
`((priv->fmt.blue_max << priv->fmt.blue_shift) < (1 << 24)));`
without any check or validation about what comes from the server.
Apparently this just works by luck, because <<32 is undefined in C language and implemented as <<0 by Intel CPUs.
See for example: https://stackoverflow.com/questions/7401888/why-doesnt-left-bit-shift-for-32-bit-integers-work-as-expected-when-used

**Comment by CendioOssman** [comment]
Ah. That's not particularly reliable then.

If this is just virtual stuff and not hardware, then that improves the odds of fixing it in the server (i.e. the proper place). Have you talked to this cloud provider about the bug?

**Comment by samhed** [comment]
No response, closing.

**Comment by rorait** [comment]
I still think that a compatibility patch would be the best option, given that other VNC viewers, by lacking strict validation, work fine. This makes tigervnc the "broken" one, in the eyes of the users.
If the upstream patch is not possible, I'm ok with running a patched version myself.
