### ISSUE TITLE
VNC Server not Listening

### ISSUE THREAD

**Issue by dark-kornax** [TigerVNC/tigervnc#1157]
**Describe the bug**
I have followed multiple configuration examples all the same as this oracle document: https://docs.oracle.com/en/operating-systems/oracle-linux/8/obe-vnc-install/index.html#before-you-begin however VNC is not listening on the expected ports

**To Reproduce**
After following the docs, again multiple, checking netstat or any other options does not show the service listening and I cannot connect.  I have it set to be port 5902

**Expected behavior**
was hoping to connect!  i may be missing something in the configs.

**Screenshots**

**Client (please complete the following information):**
I have tried multiple clients

**Server (please complete the following information):**
 - OS: Oracle Linux 8
 - VNC server: TigerVNC
 - VNC server version: 1.10.1-7
 - Server downloaded from: ULN
 - Server was started using: systemctl (systemd)

**Additional context**
I would appreciate any help in trying to figure this out.  I have been over the configs dozens of times and I have it all done as expected.  The daemon starts, however nothing seems to be listening on 5902 as expected... or any other related VNC port either.

**Comment by CendioOssman** [comment]
I would guess something goes wrong and it terminates right away. What does the log for the service say? And the log in `~/.vnc`?

**Comment by CendioOssman** [comment]
No response. Closing.
