### ISSUE TITLE
does not work any longer in Centos8

### ISSUE THREAD

**Issue by arnjan** [TigerVNC/tigervnc#1158]
Hi there is a bug in Centos8. It had worked 10th of years but with the update yesterday it is gone. However the readme.md file is not understandable how to fix this. There is no way to find the new procedure. Maybe write a new Installation manual instead of commenting only the differences to the former installation path? Could this help?

**Comment by CendioOssman** [comment]
I'm afraid your description is a bit too vague for us to be able to help you. I would guess that CentOS has upgraded to the new service based vncserver model though. Please have a look in the `vncserver@.service` unit file for some basic steps to get going.
