### ISSUE TITLE
TigerVNC systemd failing to start

### ISSUE THREAD

**Issue by nifteen20** [TigerVNC/tigervnc#1159]
I recently updated my TigerVNC version on a CentOS 8 install and I can no longer start one off VNC sessions. Could someone please look over my config for the unit file, and why it refuses to start. I have been through about 5-8 tutorials with varying unit config files, I have set a vncpasswd as well as defined the user to session pairing as necessitated by the configuration. Is there any way I can just use the wrapper because I can't find any information on how to fall-back to that option. This is on a B-series Azure instance that is only infrequently used so I have no intention of starting in graphical or wanting this to be running in the background as a unit so if I could revert back that would be great.

--------------------------------------------------------
[root@InternalBox ~]# cat /etc/systemd/system/vncserver@:1.service
[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=simple

(#) Clean any existing files in /tmp/.X11-unix environment
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
ExecStart=/usr/sbin/runuser -l azureuser -c "/usr/bin/vncserver %i"
PIDFile=/home/azueruser/.vnc/%H%i.pid
ExecStop=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'

[Install]
WantedBy=multi-user.target

---------------------------------------------
● vncserver@:1.service - Remote desktop service (VNC)
   Loaded: loaded (/etc/systemd/system/vncserver@:1.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

Dec 09 18:30:22 InternalBox systemd[1]: vncserver@:1.service: Succeeded.
Dec 09 18:30:23 InternalBox systemd[1]: Starting Remote desktop service (VNC)...

----------------------------------------------
(#)TigerVNC User assignment
(#)
(#)This file assigns users to specific VNC display numbers.
(#) The syntax is <display>=<username>. E.g.:
(#)
(#):2=andrew
(#):3=lisa
:1=azureuser 
:2=azureuser

**Comment by CendioOssman** [comment]
Your users file looks correct, but the unit file is not the expected one. Which version of TigerVNC are you using? And could you check if the unit file has been modified in some way? `rpm --query --verify` should tell you that.

**Comment by CendioOssman** [comment]
And to clarify, the old `vncserver` script is no longer support by us. Red Hat might still support it though, but I'm afraid it's not something we can help out with.

**Comment by aizhihuxiao** [comment]
Same issues for me on centos 8.3, I try to fix the whole day but not working. Even can't see any port listening on my server.

**Comment by nifteen20** [comment]
Name         : tigervnc
Version      : 1.10.1
Release      : 7.el8
Architecture : x86_64
Size         : 290 k
Source       : tigervnc-1.10.1-7.el8.src.rpm

@aizhihuxiao  - I'm seeing the same thing that I am not listening on the expected port, and I run 'lsof | grep -i vnc' I see nothing running either

**Comment by CendioOssman** [comment]
Ah. That's an older version of TigerVNC (the current is 1.11.0 which has a much changed service for starting sessions).

I'm afraid the unit file you have is something from Red Hat and unfortunately it is not something we can help out with. We are looking at getting some RHEL 8 packages building ourselves so you can easily get the latest version, but I'm afraid that is not available yet. So for now you'll unfortunately have to ask Red Hat for help with this issue.

I would suggest looking in the log file in `~/.vnc` though for any obvious problems.

**Comment by nifteen20** [comment]
@CendioOssman - I understand you aren't necessarily paid support, but a little more info or suggestions beyond a non-existent log file would be greatly appreciated. I do use VNC in a production environment so logs were my first go-to because they solve 99% of these issues, and if this is ultimately the future of TigerVNC that you can't create one off instances I need to learn now before they creep into my production environment.

**Comment by CendioOssman** [comment]
Unfortunately we aren't familiar with that service as it is something Red Hat specific. Trying to help out with the stuff we ourselves include is taking up most of our time, so we simply don't have the resources to also understand and debug others' additions. As much as we'd like to help out with more things, we have to face realities and draw the line somewhere.

**Comment by CendioOssman** [comment]
Apparently Red Hat has backported stuff from TigerVNC 1.11.0 in to their 1.10.1. So you should have access to the new stuff. However your unit file you quoted is still from the old version. So I would suggest removing that file so things revert back to what's included in the RPM.
