### ISSUE TITLE
Cannot controle on 4K resolution

### ISSUE THREAD

**Issue by oblivion7676** [TigerVNC/tigervnc#1160]
1.Server: windows 10 pro. resolution: 4K tigervnc 32bit version 1.11.0
2. viewer: windows 10 pro. resolution: 1920*1080 

I tried with both 32bit and 64bit server and viewer as well. The mouser cursor location is not displayed correctly.
On the viewer side, for example,  it looks like the cursor is on the title bar of a program. But when I drag the bar, the window would not move because actually, the mouse cursor is somewhere else than the title bar of the program.

**Comment by CendioOssman** [comment]
What scale factor is configured in the server? We don't have any handling for anything except 100% in WinVNC, so that would be my first guess as to why things are messed up.

**Comment by oblivion7676** [comment]
> What scale factor is configured in the server? We don't have any handling for anything except 100% in WinVNC, so that would be my first guess as to why things are messed up.

OH.... Man,,, thank you for your guessing. The scale is 150% in the server.  That must be the reason. Would there be any solutions for that? I recently found this program. I used to use tightVNC which was too slow. And I was so surprised and satisfied at the speed of tigerVNC.

**Comment by CendioOssman** [comment]
Unfortunately no one has looked at the scaling stuff yet, so we have not suggestions besides turning off scaling.

Please see #494 for future support for scaling in the Windows server.
