### ISSUE TITLE
No Clipboard function in CentOS8.3 / Oracle Linux 8.3

### ISSUE THREAD

**Issue by GustelDE** [TigerVNC/tigervnc#1163]
Hi,

we have implemented the follwoing instructions under "13.1.4. VNC setup based on xinetd with XDMCP for GDM":
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-tigervnc

Clipboard (copy text from windows to linux) worked w/o problems till version 8.2.
With version 8.3 it stopped in boths distros CentOS and Oracle.

Please help us to solve this!!

Regards

**Comment by CendioOssman** [comment]
That's surprising and not an issue we've heard of before. So we need to do some digging.

What version of TigerVNC is installed now? And do you think you can find which version it was before the upgrade?

Did you have to go through the steps to set up XDMCP again after the upgrade, or was everything untouched from before?

**Comment by GustelDE** [comment]
Hi,

the problem occurs on new installed 8.3 servers and on updated 8.2 to 8.3 servers.

BUT, I did a further research, the problem occurs only with the UltraVNC viewer! With the UltraVNC viewer 1.2.2.4, the problem occurs as described above. With the new UltraVNC viewer 1.3.2 the connectiosn terminates itself after a few seconds!

But with my Android-VNC-App everything works and with the TightVNC viewer everything works as well.

It seems with the RHEL 8.3 update something was changed which creates problems with UltraVNC.

RHEL/Oracle 8.3 version of TigerVNC:
Installed packages:
![rhel_83](https://user-images.githubusercontent.com/26502186/102069060-8b6b0900-3dfd-11eb-8eb5-404434e44976.jpg)

RHEL/CentOS 8.2 version of TigerVNC:
Installed packages:
![rhel_82](https://user-images.githubusercontent.com/26502186/102069183-b2c1d600-3dfd-11eb-87fa-ec2547b202d8.jpg)

**Comment by GustelDE** [comment]
Further investigation: I can confirm it has to do with version 1.10.1.-7
I downgraded my RHEL/Oracle 8.3 to 1.9.0-15 and the clipboard function works again.

**Comment by CendioOssman** [comment]
Ah. That explains it. We've added support for more advanced clipboard in later versions, and there must be some compatibility issue with UltraVNC in that case.

Is it broken in both directions, or just one way?

**Comment by CendioOssman** [comment]
Is it possible to get a log from the crashing UltraVNC and see what it is upset about?

**Comment by GustelDE** [comment]
Yes, both directions dont work (server to client and client to server).

UltraVNC 1.2.2.4 does not crash, it simply does not copy/paste.
UltraVNC 1.3.2 terminates a few seconds after login.

Dot know if (and if yes), where the UltraVNC viewer strores its logs?

But its easy to recrate.
Setup a new RHEL/CentOS/Oracle Linux 8.3 system and install, and do the following:

sudo systemctl stop firewalld
systemctl disable firewalld

sudo dnf install gdm tigervnc tigervnc-server xinetd -y
sudo systemctl enable xinetd.service

sudo vi /etc/gdm/custom.conf
- - - - -
i

[xdmcp]
Enable=true

ESC -> :wq
- - - - -

sudo vi /etc/xinetd.d/xvncserver
- - - - -
i

service xvncserver
{
disable = no
protocol = tcp
socket_type = stream
wait = no
user = nobody
server = /usr/bin/Xvnc
server_args = -inetd -query localhost -once securitytypes=none
}

ESC -> :wq
- - - - -

sudo vi /etc/services
- - - - -
i

xvncserver      5900/tcp                        # VNC xinetd GDM base

ESC -> :wq
- - - - -

sudo reboot

This will install version 1.10.1-7.

If you access the server via UltraVNC viewer 1.2.2.4 clipboard does not work.
If you acces the server via UltraVNC viewer  1.3.2 the connection drops a few seconds after login.

**Comment by CendioOssman** [comment]
I've installed 1.3.2 here and done some testing. Unfortunately there seems to be some bugs in UltraVNC when it talks to TigerVNC. I can see it spamming `FramebufferUpdateRequest` messages constantly, some graphical glitches, and the invalid data it complains about is not seen in the protocol dump.

So unfortunately these do look like UltraVNC bugs from our point of view. That means there isn't much we can do about them, so I'll have to direct you to file a bug with them. Feel free to cross reference things here.

**Comment by RudiDeVos** [comment]
Looks, like rfbEncodingExtDesktopSize is different implemented. UltraVNC keeps getting this message.
Do you have a flow of the exchanged messages.

**Comment by CendioOssman** [comment]
I have this traffic dump with the associated log messages from UltraVNC: [uvnc.zip](https://github.com/TigerVNC/tigervnc/files/5734076/uvnc.zip)

What I can see in it is that UltraVNC keeps sending `FramebufferUpdateRequest`. Some of them have `incremental` set to `0` which makes the server send a new `ExtendedDesktopSize` frame. So there might be some bad behaviour in UltraVNC there that gets things in to a loop.

The crash seems to indeed be related to clipboard messages, as there are some near the end of the dump. But I see nothing wrong with them so the UltraVNC devs will have to take over here.

**Comment by CendioOssman** [comment]
Also note that one `FramebufferUpdateRequest` towards the end has incorrect dimensions for unknown reasons.

**Comment by CendioOssman** [comment]
Sorry, didn't realise you were *the* UltraVNC dev. :)

Let me know if there is anything we can do to help you debug this.

**Comment by RudiDeVos** [comment]
Testing Ubuntu 20.04.1
TigerVNC 1.10.0
sudo tigervnc -xstartup /user/bin/xterm -localhost no works.
Yes, i get multiple ExtendedDesktopSize messages, but this doesn't seems to hang anything, the viewer is showing
the xterm.

Made a viewer change to avoid full update request when we don't have a UltraVNC server and extDesktop is used,
In UltraVNC we use it to force fullscreen updates, therefore the server only consider the first 0 as an ExtendedDesktopSize messages.

Next test, with a desktop instead of an xterm...
Is 1.10.1.-7 needed to trigger it.

**Comment by RudiDeVos** [comment]
gmd desktop is also working, can't repeat it
![ubuntu](https://user-images.githubusercontent.com/71467484/103035789-5f235b00-4568-11eb-9094-bda59c9f5293.png)

**Comment by RudiDeVos** [comment]
Connecting tigervnc viewer to ultravnc server fail.
Reason:  
The inform ExtDesktopSize message: This is pseudo - rectangle to inform the client that setDesktopSize is supported.

 Send ExtDesktopSize
 This message is used:
 * to tell the client to change its framebuffer size
 * at the start of the session to inform the client we support size changes through setDesktopSize
 * in response to setDesktopSize commands to indicate success or failure

TigerVNC use the content of the inform ExtDesktopSize message  to set de viewer framebuffer, what is 0 in out case.

Changed UltraVNC to send the current framebuffer with the first message to make it work.

**Comment by CendioOssman** [comment]
I would assume TigerVNC 1.10.0 would be enough, as that's where the clipboard code was changed.

I could reproduce issues with just `Xvnc` and not a single application in the session. Are you not seeing any crash when using the UltraVNC viewer with a TigerVNC server? Does clipboard work for you?

**Comment by RudiDeVos** [comment]
Added a testbuild with changed ExtDesktop,
TigerViewer->UltraServer) working.
*change server size on connection OK
*Windows size changes working, NOK, only fix set of resolutions is supported by the video/monitor driver.
*Virtual desktops, not supported, doesn't exist in TigerVNC
UltraViewer->TigerServer
*change server size on connection OK
*Windows size changes working, doesn't exist in UltraVNC
*Virtual desktops, not supported, doesn't exist in TigerVNC

https://github.com/ultravnc/UltraVNC/issues/8

 I didn't got the clipboard working, it doesn't transfer anything... but also no crash.
Checking installation params..

**Comment by CendioOssman** [comment]
I'm also not getting any crashes with that build, so whatever that was seems to have gone away. 

I'm seeing some other things though, no local mouse cursor (which extensions does UltraVNC support?). And I'm getting this graphics bug:

![ubuntu2004_1 (cendio)  2021-01-04 10_18_10](https://user-images.githubusercontent.com/6640916/103519925-a1a53b80-4e76-11eb-9624-78b5076221e7.png)

Seen with both a build of `master`, and the TigerVNC 1.10.0 included in Ubuntu 20.04.
