### ISSUE TITLE
CentOS 8.3.2011 update breaks functional TigerVNC installation

### ISSUE THREAD

**Issue by kelbstf** [TigerVNC/tigervnc#1164]
**Describe the bug**
After updating yesterday to CentOS Linux release 8.3.2011 and post-update reboot, i could not launch the tigervnc service any more.

**To Reproduce**
1. Use CentOS Linux release 8.3.2011
2. Install tigervnc-server.x86_64 1.10.1-7.el8, tigervnc-server-minimal.x86_64 1.10.1-7.el8, tigervnc-server-module.x86_64 1.10.1-7.el8
3. Follow "/usr/share/doc/tigervnc/HOWTO.md" verbatim to configre service
4. Make sure not to have "/etc/sysconfig/vncservers"
5. For GNOME desktop, add "session=gnome.desktop" to "$HOME/.vnc/config"
6. Have a usermapping in "/etc/tigervnc/vncserver.users" as ":1=root"
7. Leave "/etc/tigervnc/vncserver-config-defaults" untouched
8. Leave "/etc/tigervnc/vncserver-config-mandatory" untouched
9. Make sure "$HOME/.vnc/" has proper SE-label: "unconfined_u:object_r:xdm_home_t:s0" as generated by "vncpasswd"
10. log out and back in again
11. Start vnc server: "systemctl start vncserver@:1"

**Expected behavior**
The service should be reported as:
>"systemctl status vncserver@:1 -l: Active: active (running)"

But this only lasts for a few seconds and then turns into:

>"systemctl status vncserver@:1 -l: Active: inactive (dead)"

From the logfiles one can see that the session is immediately removed after being established, and this is reported as a success, just like there would something be configured to take care of stale sessions, and mistake the valid session with a stale session?

Here are the logs:

> journalctl -xe
>--
>-- Unit UNIT has finished starting up.
--
-- The start-up result is done.
Dez 14 20:03:22 myhost at-spi-bus-launcher[21673]: dbus-daemon[21678]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=0 pid=21640 comm="/usr/libexec/gnome-session-check-accelerated " label="unconfined_u:unconfined_r:unco>
Dez 14 20:03:22 myhost at-spi-bus-launcher[21673]: dbus-daemon[21678]: Successfully activated service 'org.a11y.atspi.Registry'
Dez 14 20:03:22 myhost at-spi-bus-launcher[21673]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Dez 14 20:03:22 myhost gnome-session[21601]: gnome-session-check-accelerated: GL Helper exited with code 512
Dez 14 20:03:22 myhost gnome-session[21601]: gnome-session-check-accelerated: GLES Helper exited with code 512
Dez 14 20:03:22 myhost gnome-session[21601]: gnome-session-binary[21601]: WARNING: Unable to find required component 'com.redhat.Kiosk.WindowManager'
Dez 14 20:03:22 myhost gnome-session-binary[21601]: WARNING: Unable to find required component 'com.redhat.Kiosk.WindowManager'
Dez 14 20:03:22 myhost gnome-session-binary[21601]: WARNING: Unable to find required component 'com.redhat.Kiosk.Script'
Dez 14 20:03:22 myhost gnome-session[21601]: gnome-session-binary[21601]: WARNING: Unable to find required component 'com.redhat.Kiosk.Script'
Dez 14 20:03:22 myhost gnome-session-binary[21601]: Entering running state
Dez 14 20:03:22 myhost gnome-session[21601]: Unable to init server: Could not connect: Connection refused
Dez 14 20:03:22 myhost gnome-session-f[21752]: Cannot open display:
Dez 14 20:03:23 myhost at-spi2-registr[21681]: Failed to send session response The connection is closed
Dez 14 20:03:23 myhost systemd[20740]: Stopping D-Bus User Message Bus...
-- Subject: Unit UNIT has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit UNIT has begun shutting down.
Dez 14 20:03:23 myhost systemd[20740]: dbus.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit UNIT has successfully entered the 'dead' state.
Dez 14 20:03:23 myhost systemd[20740]: Stopped D-Bus User Message Bus.
-- Subject: Unit UNIT has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit UNIT has finished shutting down.
Dez 14 20:03:23 myhost systemd[20740]: Started D-Bus User Message Bus.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is done.
Dez 14 20:03:23 myhost systemd[20740]: at-spi-dbus-bus.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit UNIT has successfully entered the 'dead' state.
Dez 14 20:03:24 myhost vncsession[21557]: pam_unix(tigervnc:session): session closed for user root
Dez 14 20:03:24 myhost systemd[1]: vncserver@:1.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit vncserver@:1.service has successfully entered the 'dead' state.
Dez 14 20:03:24 myhost systemd-logind[1613]: Session 50 logged out. Waiting for processes to exit.
Dez 14 20:03:31 myhost systemd[1]: session-50.scope: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit session-50.scope has successfully entered the 'dead' state.
Dez 14 20:03:31 myhost systemd-logind[1613]: Removed session 50.
-- Subject: Session 50 has been terminated
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A session with the ID 50 has been terminated.

And:

 >tail /var/log/messages
 Dec 14 20:03:23 myhost journal[21681]: Failed to send session response The connection is closed
 Dec 14 20:03:23 myhost systemd[20740]: Stopping D-Bus User Message Bus...
 Dec 14 20:03:23 myhost systemd[20740]: dbus.service: Succeeded.
 Dec 14 20:03:23 myhost systemd[20740]: Stopped D-Bus User Message Bus.
 Dec 14 20:03:23 myhost systemd[20740]: Started D-Bus User Message Bus.
 Dec 14 20:03:23 myhost systemd[20740]: at-spi-dbus-bus.service: Succeeded.
 Dec 14 20:03:24 myhost systemd[1]: vncserver@:1.service: Succeeded.
 Dec 14 20:03:24 myhost systemd-logind[1613]: Session 50 logged out. Waiting for processes to exit.
 Dec 14 20:03:31 myhost systemd[1]: session-50.scope: Succeeded.
 Dec 14 20:03:31 myhost systemd-logind[1613]: Removed session 50.

**Client**
 - OS: MacOS
 - VNC client: VNC Viewer.App (6.20.817 (r42879)).

**Server:**
 - CentOS Linux release 8.3.2011
 - tigervnc-server.x86_64 1.10.1-7.el8, tigervnc-server-minimal.x86_64 1.10.1-7.el8, tigervnc-server-module.x86_64 1.10.1-7.el8
 - Server downloaded from:  @AppStream
 - Server was started using: "systemctl start vncserver@:1"

**Additional context**
The same TigerVNC installation and configuration worked perfectly fine until after update of CentOS to  8.3.2011.

Does anyone of you have similar experiences and can give me a hint where to dig deeper?
Any help would be highly appreciated, as i depend on this remote access to a management server :-/

**Comment by wtywtykk** [comment]
Are you starting VNC when logged in? It seems that you have to start it by another user.

**Comment by kelbstf** [comment]
Hello wtywtykk,
exactly. That was my mode of utilisation so far: 
-ssh into the machine 
-start VNC, 
-then connect via VNC Viewer
-stop all of that when done.
I also always used it for the root, as this is just for maintenance work...
Do i understand your question right, that it is now meant to be configured for a dedicated (non administrative) user, and root has to launch the service?

**Comment by jrTb9Vu8Dgk** [comment]
Hello, 
i think have the same problem, until yesterday. I had updated CentOS to 8.3.2011 and my TigerVNC which before the Update runs perfect, would not start now.  

I had changed the real hostname to hostname and the real username to username


**journalctl -xe**
```

-- Unit UNIT has finished starting up.

-- The start-up result is done.
Dez 15 12:47:40 hostname at-spi-bus-launcher[15209]: dbus-daemon[15214]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=15192 comm="/usr/libexec/gnome-session-check-accelerated ")
Dez 15 12:47:40 hostname at-spi-bus-launcher[15209]: dbus-daemon[15214]: Successfully activated service 'org.a11y.atspi.Registry'
Dez 15 12:47:40 hostname at-spi-bus-launcher[15209]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Dez 15 12:47:40 hostname gnome-session[15133]: gnome-session-check-accelerated: GL Helper exited with code 512
Dez 15 12:47:40 hostname gnome-session[15133]: gnome-session-check-accelerated: GLES Helper exited with code 512
Dez 15 12:47:40 hostname gnome-session[15133]: gnome-session-binary[15133]: WARNING: Unable to find required component 'com.redhat.Kiosk.WindowManager'
Dez 15 12:47:40 hostname gnome-session-binary[15133]: WARNING: Unable to find required component 'com.redhat.Kiosk.WindowManager'
Dez 15 12:47:40 hostname gnome-session[15133]: gnome-session-binary[15133]: WARNING: Unable to find required component 'com.redhat.Kiosk.Script'
Dez 15 12:47:40 hostname gnome-session-binary[15133]: WARNING: Unable to find required component 'com.redhat.Kiosk.Script'
Dez 15 12:47:40 hostname gnome-session-binary[15133]: Entering running state
Dez 15 12:47:40 hostname gnome-session[15133]: Unable to init server: Could not connect: Connection refused
Dez 15 12:47:40 hostname gnome-session-f[15255]: Cannot open display:
Dez 15 12:47:40 hostname systemd[11423]: Stopping D-Bus User Message Bus...
-- Subject: Unit UNIT has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit UNIT has begun shutting down.
Dez 15 12:47:40 hostname gnome-session[15133]: gnome-session-binary[15133]: GLib-GIO-WARNING: Error releasing name org.gnome.SessionManager: Verbindung ist geschlossen
Dez 15 12:47:40 hostname gnome-session-binary[15133]: GLib-GIO-WARNING: Error releasing name org.gnome.SessionManager: Verbindung ist geschlossen
Dez 15 12:47:40 hostname systemd[11423]: dbus.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit UNIT has successfully entered the 'dead' state.
Dez 15 12:47:40 hostname systemd[11423]: Stopped D-Bus User Message Bus.
-- Subject: Unit UNIT has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit UNIT has finished shutting down.
Dez 15 12:47:40 hostname systemd[11423]: Started D-Bus User Message Bus.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is done.
Dez 15 12:47:40 hostname systemd[11423]: at-spi-dbus-bus.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit UNIT has successfully entered the 'dead' state.
Dez 15 12:47:41 hostname vncsession[15106]: pam_unix(tigervnc:session): session closed for user username
Dez 15 12:47:41 hostname systemd[1]: vncserver@:12.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit vncserver@:12.service has successfully entered the 'dead' state.
Dez 15 12:47:41 hostname systemd-logind[1132]: Session 11 logged out. Waiting for processes to exit.

```

**/var/log/messages**
```

Dec 15 12:47:40 hostname systemd[1]: Starting Remote desktop service (VNC)...
Dec 15 12:47:40 hostname systemd-logind[1132]: New session 11 of user username.
Dec 15 12:47:40 hostname systemd[1]: Started Session 11 of user username.
Dec 15 12:47:40 hostname systemd[1]: Started Remote desktop service (VNC).
Dec 15 12:47:40 hostname dbus-daemon[12586]: [session uid=1000 pid=12586] Activating via systemd: service name='org.a11y.Bus' unit='at-spi-dbus-bus.service' requested by ':1.4' (uid=1000 pid=15192 comm="/usr/libexec/gnome-session-check-accelerated ")
Dec 15 12:47:40 hostname systemd[11423]: Starting Accessibility services bus...
Dec 15 12:47:40 hostname dbus-daemon[12586]: [session uid=1000 pid=12586] Successfully activated service 'org.a11y.Bus'
Dec 15 12:47:40 hostname systemd[11423]: Started Accessibility services bus.
Dec 15 12:47:40 hostname at-spi-bus-launcher[15209]: dbus-daemon[15214]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=15192 comm="/usr/libexec/gnome-session-check-accelerated ")
Dec 15 12:47:40 hostname at-spi-bus-launcher[15209]: dbus-daemon[15214]: Successfully activated service 'org.a11y.atspi.Registry'
Dec 15 12:47:40 hostname at-spi-bus-launcher[15209]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Dec 15 12:47:40 hostname gnome-session[15133]: gnome-session-check-accelerated: GL Helper exited with code 512
Dec 15 12:47:40 hostname gnome-session[15133]: gnome-session-check-accelerated: GLES Helper exited with code 512
Dec 15 12:47:40 hostname gnome-session[15133]: gnome-session-binary[15133]: WARNING: Unable to find required component 'com.redhat.Kiosk.WindowManager'
Dec 15 12:47:40 hostname gnome-session-binary[15133]: WARNING: Unable to find required component 'com.redhat.Kiosk.WindowManager'
Dec 15 12:47:40 hostname gnome-session[15133]: gnome-session-binary[15133]: WARNING: Unable to find required component 'com.redhat.Kiosk.Script'
Dec 15 12:47:40 hostname gnome-session-binary[15133]: WARNING: Unable to find required component 'com.redhat.Kiosk.Script'
Dec 15 12:47:40 hostname gnome-session-binary[15133]: Entering running state
Dec 15 12:47:40 hostname gnome-session[15133]: Unable to init server: Could not connect: Connection refused
Dec 15 12:47:40 hostname journal[15255]: Cannot open display:
Dec 15 12:47:40 hostname systemd[11423]: Stopping D-Bus User Message Bus...
Dec 15 12:47:40 hostname gnome-session[15133]: gnome-session-binary[15133]: GLib-GIO-WARNING: Error releasing name org.gnome.SessionManager: Verbindung ist geschlossen
Dec 15 12:47:40 hostname gnome-session-binary[15133]: GLib-GIO-WARNING: Error releasing name org.gnome.SessionManager: Verbindung ist geschlossen
Dec 15 12:47:40 hostname systemd[11423]: dbus.service: Succeeded.
Dec 15 12:47:40 hostname systemd[11423]: Stopped D-Bus User Message Bus.
Dec 15 12:47:40 hostname systemd[11423]: Started D-Bus User Message Bus.
Dec 15 12:47:40 hostname systemd[11423]: at-spi-dbus-bus.service: Succeeded.
Dec 15 12:47:41 hostname systemd[1]: vncserver@:12.service: Succeeded.
Dec 15 12:47:41 hostname systemd-logind[1132]: Session 11 logged out. Waiting for processes to exit.
Dec 15 12:47:50 hostname systemd[1]: session-11.scope: Succeeded.
Dec 15 12:47:50 hostname systemd-logind[1132]: Removed session 11.


```

 **files in /home/username/.vnc/**
```
 passwd
 config
```
**entry in /home/username/.vnc/config**
`localhost`

 
**/etc/tigervnc/vncserver.users**

```
# TigerVNC User assignment
#
# This file assigns users to specific VNC display numbers.
# The syntax is <display>=<username>. E.g.:
#
# :2=andrew
# :3=lisa
:12=username
```

**Comment by CendioOssman** [comment]
Multiple *graphical* sessions tend to break, but you should be fine if you just SSH in to start the VNC session. So in this case I don't think that is the problem.

Unfortunately the log files don't give us much help either. GNOME is upset about something, but it's not clear quite what. I would suspect that it is a GNOME upgrade in 8.3 that caused this, rather than an upgrade of TigerVNC.

Just to make things extra confusing it seems like Red Hat has back ported stuff from TigerVNC 1.11.0 in to their 1.10.1. Unfortunately that's not a combination we've tested so I'm not sure if something might be missing. @grulja, are you seeing any of these issues that people are reporting? They seem to be common.

**Comment by CendioOssman** [comment]
It's extremely odd that there is no log file `~/.vnc`. That suggests that the correct startup scripts are not being executed.

On another issue old unit files from earlier versions were still around. Could you double check that it is indeed `/usr/lib/systemd/system/vncserver@.service` being used and not some other file?

**Comment by jrTb9Vu8Dgk** [comment]
> 
> 
> It's extremely odd that there is no log file `~/.vnc`. That suggests that the correct startup scripts are not being executed.
> 
> On another issue old unit files from earlier versions were still around. Could you double check that it is indeed `/usr/lib/systemd/system/vncserver@.service` being used and not some other file?

Sorry my fault, is my first entry at GitHub, there is a log file, i had update the post

**Comment by jrTb9Vu8Dgk** [comment]
> /usr/lib/systemd/system/vncserver@.service

Here is the /usr/lib/systemd/system/vncserver@.service without some Commented lines, because it is to long and not necessary i think:

```
# The vncserver service unit file
#
# Quick HowTo:
# 1. Add a user mapping to /etc/tigervnc/vncserver.users.
# 2. Adjust the global or user configuration. See the
#    vncsession(8) manpage for details. (OPTIONAL)
# 3. Run `systemctl enable vncserver@:<display>.service`
# 4. Run `systemctl start vncserver@:<display>.service`
#


[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
ExecStart=/usr/libexec/vncsession-start %i
PIDFile=/var/run/vncsession-%i.pid
SELinuxContext=system_u:system_r:vnc_session_t:s0

[Install]
WantedBy=multi-user.target


```
and i have no file for vnc in /etc/systemd/system/

**Comment by CendioOssman** [comment]
Great. That makes a bit more sense.

We can see that you are trying to start something called "com.redhat.Kiosk". This is not something I'm familiar with, and might have issues in a remote session. Was this the session you explicitly wanted, or have you simply not configured anything?

I would try adding `session=gnome` to your TigerVNC configuration and see if that works better.

**Comment by grulja** [comment]
Using `session=gnome` is mandatory on RHEL 8/CentOS, otherwise it defaults to first session in `/usr/share/xsessions/`, which in this case is "com.redhat.Kiosk" and that doesn't work.

**Comment by kelbstf** [comment]
Thank you all for your input!
Actually i had followed "/usr/share/doc/tigervnc/HOWTO.md" verbatim, and tested these options:
<pre><code>ls -al /usr/share/xsessions
total 40
drwxr-xr-x.   2 root root  149 13. Dez 15:08 .
drwxr-xr-x. 206 root root 8192 13. Dez 15:12 ..
-rw-r--r--.   1 root root  132 21. Jul 20:57 com.redhat.Kiosk.desktop
-rw-r--r--.   1 root root 8471 21. Jul 20:57 gnome-custom-session.desktop
-rw-r--r--.   1 root root 1303 21. Jul 20:57 gnome.desktop
-rw-r--r--.   1 root root 1303 21. Jul 20:57 gnome-xorg.desktop
-rw-r--r--.   1 root root  130 14. Mai 2019  xinit-compat.desktop
</code></pre>
I sticked with "session=gnome.desktop" ever since, just to make sure.

<pre><code>
~/.vnc/config 
session=gnome.desktop
#session=gnome-xorg.desktop

# Test:
#localhost

</code></pre>

That's why i felt save to ignore the
> WARNING: Unable to find required component 'com.redhat.Kiosk.WindowManager'

My guts feeling tells me that it actually fails earlier to involving GNOME?
At no point i reached the step to actually attempt to connect remotely.
Instead:
The next one holds vor about 2 seconds:
<pre><code>
 systemctl status vncserver@:1
● vncserver@:1.service - Remote desktop service (VNC)
   Loaded: loaded (/usr/lib/systemd/system/vncserver@.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-12-15 13:37:52 CET; 2s ago
  Process: 24042 ExecStart=/usr/libexec/vncsession-start :1 (code=exited, status=0/SUCCESS)
 Main PID: 24048 (vncsession)
    Tasks: 1 (limit: 203829)
   Memory: 2.4M
   CGroup: /system.slice/system-vncserver.slice/vncserver@:1.service
           ‣ 24048 /usr/sbin/vncsession root :1

Dez 15 13:37:51 myhost systemd[1]: Starting Remote desktop service (VNC)...
Dez 15 13:37:52 myhost systemd[1]: Started Remote desktop service (VNC).
</code></pre>
And then falls back to:

<pre><code>
 systemctl status vncserver@:1
● vncserver@:1.service - Remote desktop service (VNC)
   Loaded: loaded (/usr/lib/systemd/system/vncserver@.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

Dez 14 20:03:24 myhost systemd[1]: vncserver@:1.service: Succeeded.
Dez 15 13:22:53 myhost systemd[1]: Starting Remote desktop service (VNC)...
Dez 15 13:22:54 myhost systemd[1]: Started Remote desktop service (VNC).
Dez 15 13:22:56 myhost systemd[1]: vncserver@:1.service: Succeeded.
Dez 15 13:30:12 myhost systemd[1]: Starting Remote desktop service (VNC)...
Dez 15 13:30:12 myhost systemd[1]: Started Remote desktop service (VNC).
Dez 15 13:30:15 myhost systemd[1]: vncserver@:1.service: Succeeded.
Dez 15 13:37:51 myhost systemd[1]: Starting Remote desktop service (VNC)...
Dez 15 13:37:52 myhost systemd[1]: Started Remote desktop service (VNC).
Dez 15 13:37:54 myhost systemd[1]: vncserver@:1.service: Succeeded.
</code></pre>

In particular the message "connection refused" seems to be the core of the problem:
<pre><code>
journalctl -xe
-- Support: https://access.redhat.com/support
-- 
-- Unit UNIT has begun starting up.
Dez 15 13:37:52 myhost dbus-daemon[24099]: [session uid=0 pid=24099] Successfully activated service 'org.a11y.Bus'
Dez 15 13:37:52 myhost systemd[23986]: Started Accessibility services bus.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
Dez 15 13:37:52 myhost at-spi-bus-launcher[24167]: dbus-daemon[24172]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid>
Dez 15 13:37:52 myhost at-spi-bus-launcher[24167]: dbus-daemon[24172]: Successfully activated service 'org.a11y.atspi.Registry'
Dez 15 13:37:52 myhost at-spi-bus-launcher[24167]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Dez 15 13:37:53 myhost gnome-session[24092]: gnome-session-check-accelerated: GL Helper exited with code 512
Dez 15 13:37:53 myhost gnome-session[24092]: gnome-session-check-accelerated: GLES Helper exited with code 512
Dez 15 13:37:53 myhost gnome-session[24092]: gnome-session-binary[24092]: WARNING: Unable to find required component 'com.redhat.Kiosk.WindowMana>
Dez 15 13:37:53 myhost gnome-session-binary[24092]: WARNING: Unable to find required component 'com.redhat.Kiosk.WindowManager'
Dez 15 13:37:53 myhost gnome-session-binary[24092]: WARNING: Unable to find required component 'com.redhat.Kiosk.Script'
Dez 15 13:37:53 myhost gnome-session[24092]: gnome-session-binary[24092]: WARNING: Unable to find required component 'com.redhat.Kiosk.Script'
Dez 15 13:37:53 myhost gnome-session-binary[24092]: Entering running state
Dez 15 13:37:53 myhost gnome-session[24092]: Unable to init server: Could not connect: Connection refused
Dez 15 13:37:53 myhost gnome-session-f[24246]: Cannot open display: 
Dez 15 13:37:53 myhost gnome-session[24092]: gnome-session-binary[24092]: GLib-GIO-WARNING: Error releasing name org.gnome.SessionManager: The co>
Dez 15 13:37:53 myhost gnome-session-binary[24092]: GLib-GIO-WARNING: Error releasing name org.gnome.SessionManager: The connection is closed
Dez 15 13:37:53 myhost systemd[23986]: Stopping D-Bus User Message Bus...
-- Subject: Unit UNIT has begun shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit UNIT has begun shutting down.
Dez 15 13:37:53 myhost systemd[23986]: at-spi-dbus-bus.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit UNIT has successfully entered the 'dead' state.
Dez 15 13:37:53 myhost systemd[23986]: dbus.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit UNIT has successfully entered the 'dead' state.
Dez 15 13:37:53 myhost systemd[23986]: Stopped D-Bus User Message Bus.
-- Subject: Unit UNIT has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit UNIT has finished shutting down.
Dez 15 13:37:53 myhost systemd[23986]: Started D-Bus User Message Bus.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit UNIT has finished starting up.
-- 
-- The start-up result is done.
Dez 15 13:37:54 myhost vncsession[24048]: pam_unix(tigervnc:session): session closed for user root
Dez 15 13:37:54 myhost systemd[1]: vncserver@:1.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit vncserver@:1.service has successfully entered the 'dead' state.
Dez 15 13:37:54 myhost systemd-logind[1613]: Session 61 logged out. Waiting for processes to exit.
Dez 15 13:38:02 myhost systemd[1]: session-61.scope: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit session-61.scope has successfully entered the 'dead' state.
Dez 15 13:38:02 myhost systemd-logind[1613]: Removed session 61.
-- Subject: Session 61 has been terminated
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID 61 has been terminated.
</code></pre>

Also i find suprising to find the SE-Label specified as:
<pre><code>
cat /usr/lib/systemd/system/vncserver@.service
# The vncserver service unit file
[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
ExecStart=/usr/libexec/vncsession-start %i
PIDFile=/var/run/vncsession-%i.pid
SELinuxContext=system_u:system_r:vnc_session_t:s0

[Install]
WantedBy=multi-user.target

</code></pre>
I never find the *.pid file in "/var/run/". 
Is this "PIDFile" s.th. the server takes care of on it's own, or should one create it manually and assign the proper label to it?

**Comment by jrTb9Vu8Dgk** [comment]
> 
> 
> Great. That makes a bit more sense.
> 
> We can see that you are trying to start something called "com.redhat.Kiosk". This is not something I'm familiar with, and might have issues in a remote session. Was this the session you explicitly wanted, or have you simply not configured anything?
> 
> I would try adding `session=gnome` to your TigerVNC configuration and see if that works better.

Thank you so much my problem is fixed, because this was what i need it missing:
**session=gnome**
in the vncvonfig file
I had searching severall hours and only found only this entry for config file:
**session=gnome.desktop** 
But this dosn´t work for me.

**Comment by kelbstf** [comment]
I am deeply sorry.
It's the syntax, stupid...
When posting my last reply, i stumbled upon this:
<pre><code>
cat ~/.vnc/config 
session=gnome
#session=gnome.desktop
#session=gnome-xorg.desktop
#localhost
</pre></code>
I.o.w.: do not use the extension as listed in:
<pre><code>
/usr/share/xsessions
total 40
drwxr-xr-x.   2 root root  149 13. Dez 15:08 .
drwxr-xr-x. 206 root root 8192 13. Dez 15:12 ..
-rw-r--r--.   1 root root  132 21. Jul 20:57 com.redhat.Kiosk.desktop
-rw-r--r--.   1 root root 8471 21. Jul 20:57 gnome-custom-session.desktop
-rw-r--r--.   1 root root 1303 21. Jul 20:57 gnome.desktop
-rw-r--r--.   1 root root 1303 21. Jul 20:57 gnome-xorg.desktop
-rw-r--r--.   1 root root  130 14. Mai 2019  xinit-compat.desktop
</pre></code>
Omitting the extension brings back the know behaviour, with exactly the same utilisation procedure as practised until the update.
Thank you all a lot for your greate help, and sorry.

**Comment by kelbstf** [comment]
Hello jrTb9Vu8Dgk,
exactly my same problem. Great, that works for me!

**Comment by CendioOssman** [comment]
Great. Glad things got resolved.

@grulja, what is this Kiosk thing? And should perhaps you guys ship with a different `vncserver-config-defaults` to get around it?

**Comment by grulja** [comment]
> Great. Glad things got resolved.
> 
> @grulja, what is this Kiosk thing? And should perhaps you guys ship with a different `vncserver-config-defaults` to get around it?

I'm not sure, I think it's a kiosk mode for GNOME session, like a session where users are not allowed to do anything besides accessing set of applications allowed by the admin.

And yes, I think I will ship a different `vnc-config-defaults`.
