### ISSUE TITLE
copied region update

### ISSUE THREAD

**Issue by wanglong121** [TigerVNC/tigervnc#1165]
How does the copied region in compareUpdater change and what is the implementation mechanism about it?

**Comment by CendioOssman** [comment]
It doesn't change the copied region at all. It's only the changed region it goes through.

Are you trying to fix some issue? Or adding a new feature?

**Comment by wanglong121** [comment]
I'm just learning about the implementation of framebuffer update and can't trigger this scenario about copied region. Thank you!
