### ISSUE TITLE
windows winvnc mouse  Wrong offset position ，Wrong desktop Size

### ISSUE THREAD

**Issue by onvejon** [TigerVNC/tigervnc#1166]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. Windows 10]
 - VNC client: [e.g. TigerVNC, or UltraVNC]  All
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Windows 10]
 - VNC server: [e.g. TigerVNC]
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver`]

**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid we cannot help you if you don't fill out the form properly. I would guess it is #494 though, so closing as duplicate.
