### ISSUE TITLE
systemd can't start on ubuntu 20.04 with error: No user configured for display 1

### ISSUE THREAD

**Issue by hmvs** [TigerVNC/tigervnc#1168]
When I am trying to start  service via: `sudo systemctl start vncserver@1.service` it fails with "vncsession-start[2562]: No user configured for display 1"

If I start it just with: `sudo /usr/lib/x86_64-linux-gnu/vncsession-start :1` it actually starts and I can see the following processes: 

```
 ps -aux | grep -i xvnc
hmvs        4275  0.0  0.0   4136  2480 ?        S    13:24   0:00 xinit /etc/X11/Xsession env GNOME_SHELL_SESSION_MODE=ubuntu /usr/bin/gnome-session --systemd --session=ubuntu -- /usr/bin/Xvnc :1 -alwaysshared -geometry 1920x1080 -localhost -auth /home/hmvs/.Xauthority -desktop StratospheraUbuntu:1 (hmvs) -fp /usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1 -pn -rfbauth /home/hmvs/.vnc/passwd -rfbport 5901 -rfbwait 30000
hmvs        4298  0.6  0.3 1914820 59500 ?       Sl   13:24   0:00 /usr/bin/Xvnc :1 -alwaysshared -geometry 1920x1080 -localhost -auth /home/hmvs/.Xauthority -desktop StratospheraUbuntu:1 (hmvs) -fp /usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1 -pn -rfbauth /home/hmvs/.vnc/passwd -rfbport 5901 -rfbwait 30000
hmvs        5199  0.0  0.0  11856  3020 pts/0    S+   13:25   0:00 grep --color=auto -i xvnc

```
Even though,  `-localhost` parameter was specified, I wasn't able to connect to 5901. I've managed to connect with ssh tunnel, though. Moreover, the desktop looked differently and had some LD_PATH issues. 

**Server:**
 - OS: Ubuntu 20.04.1
 - VNC server: TigerVNC
 - VNC server version: 1.11.80
 - Server downloaded from: tigervncserver_1.11.80+20201228git2a0eabec-1ubuntu1_amd64.deb
 - Server was started using: sudo systemctl start vncserver@1.service

**Additional context**

```
> cat /etc/tigervnc/vncserver.users
# TigerVNC User assignment
#
# This file assigns users to specific VNC display numbers.
# The syntax is <display>=<username>. E.g.:
#
# :2=andrew
# :3=lisa
:1=hmvs
```
```
> cat /lib/systemd/system/vncserver@.service
//...... commented

[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
ExecStart=/usr/lib/x86_64-linux-gnu/vncsession-start %i
PIDFile=/run/vncsession-%i.pid
SELinuxContext=system_u:system_r:vnc_session_t:s0

[Install]
WantedBy=multi-user.target
```

```
> cat /home/hmvs/.vnc/config
session=ubuntu
geometry=1920x1080
localhost
alwaysshared
```

```
> la /home/hmvs/.vnc/passwd
-rw------- 1 hmvs hmvs 8 гру 29 13:20 /home/hmvs/.vnc/passwd
```
```
la /usr/share/xsessions/
total 28K
drwxr-xr-x   2 root root 4,0K гру 27 23:53 ./
drwxr-xr-x 355 root root  16K гру 28 13:45 ../
-rw-r--r--   1 root root  303 бер 26  2020 ubuntu.desktop
-rw-r--r--   1 root root  242 бер 26  2020 unity.desktop
```
I've tried to comment `-session   required     pam_selinux.so close` and `-session   required     pam_selinux.so open`, with `SELinuxContext=system_u:system_r:vnc_session_t:s0` from `/lib/systemd/system/vncserver@.service`, though, no luck. 
```
cat /etc/pam.d/tigervnc
#%PAM-1.0
# pam_selinux.so close should be the first session rule
-session   required     pam_selinux.so close
session    required     pam_loginuid.so
-session   required     pam_selinux.so open
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    required     pam_limits.so
-session   optional     pam_systemd.so
session    required     pam_unix.so
-session   optional     pam_reauthorize.so prepare
```

**Comment by CendioOssman** [comment]
> When I am trying to start service via: `sudo systemctl start vncserver@1.service` it fails with "vncsession-start[2562]: No user configured for display 1"

Unfortunately the instance needs to include `:`, so it should be `vncserver@:1.service`. After that it should work right.

SELinux should not be an issue on Ubuntu as it's not enabled there.

**Comment by hmvs** [comment]
Thank you @CendioOssman.

The remaining issues are: 
1. 
While starting gnome-terminal I've got an error `ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored` 

I can see following line in logs: 
`audit[177208]: AVC apparmor="DENIED" operation="file_mmap" profile="/snap/snapd/10492/usr/lib/snapd/snap-confine" name="/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0" pid=177208 comm="snap-confine" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
`

2. Gnome session doesn't load users' settings, it loads defaults. 
For instance, how dock should look 
![image](https://user-images.githubusercontent.com/2255040/103416828-f869f700-4b90-11eb-836e-4446767002a0.png)
And how it is right now: 
![image](https://user-images.githubusercontent.com/2255040/103416852-0c155d80-4b91-11eb-8d1f-5ab7f534e8d4.png)

Any ideas about how it can be fixed?

**Comment by CendioOssman** [comment]
No, sorry. That's likely something you'll have to report to Ubuntu. I am concerned about how snap got involved though. What does the VNC log look like? Perhaps you are starting some kiosk version of the desktop.
