### ISSUE TITLE
unable to connect to socket: Connection refused(10061)

### ISSUE THREAD

**Issue by Roharry** [TigerVNC/tigervnc#117]
While opening TigerVNC,  unable to connect to socket: Connection refused(10061) is showing up. Please help

**Comment by CendioOssman** [comment]
Your server is not running on that port, or is blocking access. Check your settings and make sure you don't have a firewall that is blocking things.

**Comment by Roharry** [comment]
How can I check the settings?

**Comment by CendioOssman** [comment]
Check how you started the VNC server and make sure you use the same display number/port number for the client.

**Comment by Roharry** [comment]
Port number is still the same. I have made no modifications.

**Comment by CendioOssman** [comment]
Then there is some firewall blocking your access, either on one of your machines or in the network. I'm afraid I have no general method for finding it or disabling it. It all depends on what you are running.

**Comment by colinpretorius** [comment]
This page appears high in search results so despite being an old issue, it's worth mentioning that it could be another reason: at least on Ubuntu Zesty, TigerVNC appears to default to ``-localhost yes``, meaning it binds to port 5901 (or 2 etc) on 127.0.0.1. Easily identified by ``sudo netstat -tpln``.

Assuming you don't want to use ssh tunnelling, then running ``vncserver -localhost no`` may solve the problem.

**Comment by kumarabhilash** [comment]
you can use "vncserver -geometry 1600x900 -alwaysshared" after SSh your machine.

**Comment by subodh-malgonde** [comment]
> Assuming you don't want to use ssh tunnelling, then running vncserver -localhost no may solve the problem.

@colinpretorius 's comment fixed it for me. Pulled my hair out for over 2 hours before stumbling on to this.

**Comment by eisajanyan** [comment]
Mine was a firewall issue on the host machine. Had to ssh and run `sudo ufw disable` A better option would be to properly configure my firewall.

**WARNING:** This will disable your firewall and you'll need to run `sudo ufw enable` to enable it again.

**Comment by olb1ue** [comment]
> This page appears high in search results so despite being an old issue, it's worth mentioning that it could be another reason: at least on Ubuntu Zesty, TigerVNC appears to default to `-localhost yes`, meaning it binds to port 5901 (or 2 etc) on 127.0.0.1. Easily identified by `sudo netstat -tpln`.
> 
> Assuming you don't want to use ssh tunnelling, then running `vncserver -localhost no` may solve the problem.

Spent hours debugging this. Thanks for solving this (years ago now). Just wanted to add that this might be very confusing for people coming from TightVNC since it defaults to `-localhost no`. The [docs](https://tigervnc.org/doc/Xvnc.html) for TigerVNC do not specify that there is a default value for `-localhost` which lead me even further astray.

**Comment by gpamadi** [comment]
> > This page appears high in search results so despite being an old issue, it's worth mentioning that it could be another reason: at least on Ubuntu Zesty, TigerVNC appears to default to `-localhost yes`, meaning it binds to port 5901 (or 2 etc) on 127.0.0.1. Easily identified by `sudo netstat -tpln`.
> > Assuming you don't want to use ssh tunnelling, then running `vncserver -localhost no` may solve the problem.
> 
> Spent hours debugging this. Thanks for solving this (years ago now). Just wanted to add that this might be very confusing for people coming from TightVNC since it defaults to `-localhost no`. The [docs](https://tigervnc.org/doc/Xvnc.html) for TigerVNC do not specify that there is a default value for `-localhost` which lead me even further astray.


Thanks for your input as well.  What is the actual solution to this issue?
I've turned off the firewall on my Linux server
Still get the error connecting with TigerVNC viewr from Windows10

Really appreciate -step by step info
Regards

**Comment by olb1ue** [comment]
@gpamadi For me I had to add `-localhost no` to my `vncserver` command. More specifically I updated my systemd unit file for TigerVNC to include `-localhost no`. Not sure you're having the same problem I was, or if you're using systemd to launch TigerVNC.

**Comment by scpkyy** [comment]
> This page appears high in search results so despite being an old issue, it's worth mentioning that it could be another reason: at least on Ubuntu Zesty, TigerVNC appears to default to `-localhost yes`, meaning it binds to port 5901 (or 2 etc) on 127.0.0.1. Easily identified by `sudo netstat -tpln`.
> 
> Assuming you don't want to use ssh tunnelling, then running `vncserver -localhost no` may solve the problem.

Thanks @colinpretorius About four years later.  This was driving me nuts.   In the recent version of Tigervnc just editing /etc/tigervnc/vncserver-config-defaults with localhost=no fixes the problem.

**Comment by ak7991** [comment]
vncserver -localhost no changes error from:
```
Error connecting to the KeX server.
Please try "kex start" to start the service.
If the server fails to start, please try "kex kill" or restart your WSL2 session and try again.
```

to message:

```
Win-KeX server sessions:

X DISPLAY #     RFB PORT #      PROCESS ID
:2              5902            10381

You can use the Win-KeX client to connect to any of these displays.
```
but I still run into 
```
unable to connect to sokcet: Connection refused (10061)
```

**Comment by AymanMukh** [comment]
wsl --set-version kali-linux 2

**Comment by neurocker** [comment]
I've tried every solution I've found on the internet so far, but nothing has worked. Then I looked at the status via `kex status` (I'm on Kali Linux):
/usr/bin/kex: line 266: tasklist.exe: command not found
Solution was founded here:
https://docs.microsoft.com/ru-ru/windows/wsl/troubleshooting#running-windows-commands-fails-inside-a-distribution
I've added `/mnt/c/Windows/system32` to $PATH and restarted computer and it worked.

**Comment by barry-vt** [comment]
I too, have tried everything I can find to get tigervnc to work.  I quit on Remmina because it wouldn't work, but....
I'm on Ubuntu trying to vnc (or rdp) itno another Ubuntu.  won't even connect localhost when set to yes.

**Comment by moneroexamples** [comment]
In my case it was incorrect ssh tunnel. Instead of

```
ssh -L 5901:127.0.0.1:5901 -N  <user>@<removte host> -vv
```
it should be (i should use **-R**, NOT `-L`)
````
ssh -R 5901:127.0.0.1:5901 -N  <user>@<removte host> -vv
```

**Comment by moneroexamples** [comment]
I took me one day to figure out, but in may case the issue was that I was create the ssh tunnel with ` -o StrictHostKeyChecking=no`:

```
ssh  -o StrictHostKeyChecking=no -i ~/.ssh/privatekey.pem  -l <remote-username> -L 5903:127.0.0.1:5901 -N  <remote-ip>  -vv
```

The ` -o StrictHostKeyChecking=no`  which was causing the tunnel to fail. This is some [ssh issue](https://github.com/microsoft/vscode-remote-release/issues/6239).

Once I removed the option,  the tunnel worked as expected:

```
ssh  -i ~/.ssh/privatekey.pem  -l <remote-username> -L 5903:127.0.0.1:5901 -N  <remote-ip>  -vv
```
