### ISSUE TITLE
sendcuttext=0 not taking effect

### ISSUE THREAD

**Issue by markkieronwilliams** [TigerVNC/tigervnc#1170]
**Describe the bug**

On version 0.11, despite setting `sendcuttext=0` or `-sendcuttext=0` in `/etc/tigervnc/vncserver-config-mandatory` the vncserver still allows text inside the VNC session to be copied to the clipboard of the client.

This functionality has been confirmed working prior to latest update.

**To Reproduce**

Steps to reproduce the behaviour:
1. Have a running CentOS server/virtual machine (we’ve tested on a Google Cloud instance).
2. Install vncserver and configure a user per README
```
dnf install epel-release -y
dnf update -y
dnf config-manager --set-enabled powertools
dnf install tigervnc-server '@kde-desktop' -y
useradd testuser
echo ":1=testuser" >> /etc/tigervnc/vncserver.users
su - testuser -c "vncpasswd"
echo "sendcuttext=0" >> /etc/tigervnc/vncserver-config-mandatory
systemctl start vncserver@:1
```
3. Connect to VNC session (e.g. using vncviewer, we have also tested Apache Guacamole)
4. Try copying to client clipboard to confirm working

**Expected behavior**

No text to be copied to the client clipboard with these settings, on the latest version. 

**Client (please complete the following information):**

 - OS: Windows
 - VNC client: TigerVNC
 - VNC client version: 1.11
 - Client downloaded from: https://bintray.com/tigervnc/stable/tigervnc/1.11.0 vncviewer64-1.11.0.exe

**Server (please complete the following information):**

 - OS: CentOS 8
 - VNC server: TigerVNC
 - VNC server version: 1.11
 - Server downloaded from: my Linux distribution
 - Server was started using: systemctl

**Comment by CendioOssman** [comment]
This has been fixed in 331a27addf46d39635fb4d195ae2f94058689832 when handling #1072 and will be included in the next release. Please try a nightly build or ask your distribution to back-port the fix if it is necessary to get the fix urgently.

**Comment by CendioOssman** [comment]
Hmm... This fix was actually back-ported to 1.11.0 before release. So it should be already included.

Could you check exactly what package of TigerVNC you are running?

**Comment by markkieronwilliams** [comment]
Ah yeah it's 1.10.1 that's been recently updated in CentOS not 1.11. I'll try using an updated version, rather than the one in the dist repo.
Thanks for the help!

**Comment by danielkho** [comment]
Hi, I am facing similar problem. I downloaded the 1.11 tar.gz and replaced all the relevant vnc* files (except under /usr/share - not necessary?). I now get the following:

/usr/bin/Xvnc :xx -depth 24 -geometry 1920x1080 -localhost -maxcuttext 500 -noclipboard -sendcuttext -auth /homes/daniel-kho/.Xauthority -desktop rnd.logik.haus:21 (daniel-kho) -fp catalogue:/etc/X11/fontpath.d -pn -rfbauth /homes/daniel-kho/.vnc/passwd -rfbport 5921 -rfbwait 30000

Notice that "-sendcuttext" does not have an argument, however I have set it correctly in /etc/tigervnc/vncserver-config-mandatory
session=gnome
localhost
noclipboard
SendCutText=0
MaxCutText=500

In the latest Centos 8 repo version, I could see "-sendcuttext 0"  at the process display, however, I could still copy text from within the VNC session to the host computer.

I really need to get this fixed, as this is a big security hole for me.

Thanks a lot for the help!

**Comment by markkieronwilliams** [comment]
@danielkho we set `-sendcuttext=0` in our /etc/tigervnc/vncserver-config-mandatory (so with a dash in front) and it seems to work better

**Comment by danielkho** [comment]
@markkieronwilliams Thanks! I will try this. Do I need to add the dashes for all the other options?

**Comment by danielkho** [comment]
It works! Thanks a lot! :) 👍
