### ISSUE TITLE
Full Screen does not work over all monitors on raspi 4 with latest tigervnc version

### ISSUE THREAD

**Issue by runcipi** [TigerVNC/tigervnc#1171]
I have a pristine fresh install of Raspbian GNU/Linux 10 (buster) with (TigerVNC 1.9.0+dfsg-3+deb10u2) and a dual monitor setup per Raspi 4's two hdmi ports.

VNC connection from Raspberry to server works fine via tigervnc, however the 'enable full screen mode over all monitors' option does not.

On my former Ubuntu system (Ubuntu 18.04.5 LTS / TigerVNC Viewer 64-bit v1.7.0) the dual monitor setup works just fine and I am familiar with the setup 'options'.

I am afraid I do not have exact infos related to the Linux server, but issue does not appear to be server related.

Any help would be greatly appreciated as I would really prefer to switch to using the Raspberry Pi instead of the full-blown desktop system.

Do I need to supply any further details?

Thanks a lot in advance for any (related) suggestions!

**Comment by CendioOssman** [comment]
This is usually an issue with the local window manager that doesn't support full screen over multiple monitors.

Which desktop environment are you running on the Raspberry Pi?

**Comment by runcipi** [comment]
Thanks for getting back to me, CendioOssman. That does seem to be a very promising approach!
wmctrl delivers the following:

pi:~$ wmctrl -a
Name: Openbox
Class:
PID: N/A
Window manager's "showing the desktop" mode: OFF

**Comment by runcipi** [comment]
I will first of all follow instructions on https://raspberrytips.com/pimp-my-raspberry-pi/ -> "Install a new desktop environment" very optimistically and report back.

Thanks again!

**Comment by runcipi** [comment]
> This is usually an issue with the local window manager that doesn't support full screen over multiple monitors.
> 
> Which desktop environment are you running on the Raspberry Pi?

Thanks again, Cendio. It works a treat with Mate desktop environment!
