### ISSUE TITLE
some applications show in display :0 (physical screen) instead of display :1 created by vncserver

### ISSUE THREAD

**Issue by seudut** [TigerVNC/tigervnc#1173]
**Describe the bug**
I have Debian 10 Linux with vncserver installed.  The debian startup with graph interface (default gdm).  
After started, I then start vncserver with `vncserver` command.

On my mac, I connected the debian with real VNCView, such as `192.168.0.1:1`,  and it can show the xfce4 desktop.  However when a double click the `File System` or the `Home` icon,  nothing show in my vncview, instead, the windows shows on my Linux physic screen.  While if i open some others gui application in VNCView, such as (emacs, vim), the windows can show in my vncview.

my vnc startup

```bash
#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec startxfce4
```

**Comment by seudut** [comment]
I found a solution to this. changing display manager from the default `gdm3` to `lightdm` by `dpkg-reconfigure` can fix this issue. But I don't know why

**Comment by CendioOssman** [comment]
That sounds very odd, but glad you found a workaround.

In general though, this is unfortunately not something we can do much about. Many applications these days only want a single instance (even if there are multiple windows). E.g. browser have behaved like this for a long time.

So unfortunately you'll have to report this to the applications giving you problems and see if they can improve things.
