### ISSUE TITLE
How to run vncserver inside the docker container? The vncserver is removed in the newest release.

### ISSUE THREAD

**Issue by cainmagi** [TigerVNC/tigervnc#1174]
**Is your feature request related to a problem? Please describe.**
In the newest tigervnc release (>=1.11), the vncserver is removed from the package. I noticed that the newest method is mentioned here:
https://wiki.archlinux.org/index.php/TigerVNC#Running_vncserver_for_virtual_(headless)_sessions
However, it seems that `systemctl` is not supported in my docker container. When I run `systemctl` like this, I meet the following problem:
```
> systemctl daemon-reload
System has not been booted with systemd as init system (PID 1). Can't operate.
```

**Describe the solution you'd like**
I request instructions for:
* How to fix the `systemctl` problem inside the container?

It will be very good for me if the instructions could be added to the wiki.

**Describe alternatives you've considered**
If `systemctl` is actually not working with contaier, I think we may need to find:
* How to run vncservice without using `systemctl`?

Thank you!
Best regards,
cainmagi

**Comment by CendioOssman** [comment]
The service is designed for "normal" sessions, which generally don't run properly in docker. I'm afraid a container environment is special enough that you'll have to design something custom. Perhaps it's possible to find some existing docker image that can be used as a template. Unfortunately we don't have any examples for this.

**Comment by cainmagi** [comment]
> The service is designed for "normal" sessions, which generally don't run properly in docker. I'm afraid a container environment is special enough that you'll have to design something custom. Perhaps it's possible to find some existing docker image that can be used as a template. Unfortunately we don't have any examples for this.

It is sad to hear this. Currently, I find a method for solving this issue. It is just getting the `vncserver` back, the details could be seen here:
https://gist.github.com/plembo/87a429f3bd1f95d4ec59b2ce8ce0a04d

I have to say that this is an ugly solution. But I have not discovered any better solution yet. :disappointed:

**Comment by lagergren** [comment]
This is very unfortunate. It is a huge corporate use case for us to have virtual docker/podman development machines we connect through to VNC.  The need for vncserver working in a container is great. Please reconsider this architecture, or support the old way of running the server process.

**Comment by CendioOssman** [comment]
The issue is that this is not a TigerVNC issue, but a GNOME, or Xfce, or KDE issue. It's the environments that don't want to be started this way and we don't have the time to figure out how to hack around the issues.

We perfectly support running TigerVNC in a container. It's how to start your desktop environment or applications in there that we unfortunately cannot help you with. We provide the vncserver service for the most standard way of starting a desktop environment, since that is fairly robust and straight forward. Anything more odd than that is unfortunately too time consuming and we need to focus on TigerVNC itself.

**Comment by CendioOssman** [comment]
Simply put `Xvnc` with basically the same arguments you previously gave to the `vncserver` script in your container script and you should have a working TigerVNC server up and running. You'll then have to add the commands required to get your applications up and running after that.

**Comment by mwroblinski** [comment]
> Simply put `Xvnc` with basically the same arguments you previously gave to the `vncserver` script in your container script and you should have a working TigerVNC server up and running. You'll then have to add the commands required to get your applications up and running after that.

Thanks Cendio, the following lines work fine for me in a Centos Image (with a nonroot user and having vncpassword set)

```
Xvnc :$terminal -geometry $vncgeometry -PasswordFile=$HOME/.vnc/passwd &
export DISPLAY=:$terminal 
startxfce4
```
I did not get the vnc server to start the windowsmanager implicitly as before. So if anybody has a hint there this would be appreciated although this way it works too.

**Comment by cainmagi** [comment]
> > Simply put `Xvnc` with basically the same arguments you previously gave to the `vncserver` script in your container script and you should have a working TigerVNC server up and running. You'll then have to add the commands required to get your applications up and running after that.
> 
> Thanks Cendio, the following lines work fine for me in a Centos Image (with a nonroot user and having vncpassword set)
> 
> ```
> Xvnc :$terminal -geometry $vncgeometry -PasswordFile=$HOME/.vnc/passwd &
> export DISPLAY=:$terminal 
> startxfce4
> ```
> 
> I did not get the vnc server to start the windowsmanager implicitly as before. So if anybody has a hint there this would be appreciated although this way it works too.

Very good suggestion! I have successfully tested similar commands within my docker image:

```bash
Xtigervnc :1 -depth 24 -geometry 1920x1080 -br -rfbport=5901 -PasswordFile=/home/xubuntu/.vnc/passwd &
export DISPLAY=:1
sh /home/xubuntu/.vnc/xstartup &
```
