### ISSUE TITLE
I have a question that how can I set the tigervnc to accept the connect from UDP？

### ISSUE THREAD

**Issue by sdyby2006** [TigerVNC/tigervnc#1177]
I have a question that how can I set the tigervnc to accept the connect from UDP？
System Version：Centos7
Tigervnc Version：TigerVNC 1.8.0
Sorry for the inconvenience

**Comment by CendioOssman** [comment]
I'm afraid there is no support for running VNC over UDP and I'm not aware of anyone who has tried to construct such a protocol.

**Comment by IJuanDer** [comment]
Hello everyone,

I was wondering if TigerVNC still doesn't support UDP.
