### ISSUE TITLE
Menu Bar not visible on applications in TigerVNC

### ISSUE THREAD

**Issue by agiuffre** [TigerVNC/tigervnc#1181]
TIGERVNC Display issue:
The toolbar menu on all of my applications seem to be hidden. I cannot exit, minimize, change size of applications or move them around in my window. I cannot access my home button, or open any other application unless done through terminal. Switching in/out of fullscreen, changing the resolution, does not work. Cannot access preferences. 

Fn8 opens a preferences menu; option to refresh screen, change resolution, none seem to work. 

**To Reproduce**
Not sure if this was an error going in/out of full screen mode. 

**Screenshots**
Screenshot attached. Menu bar on terminal window is not visible. Cant move terminal window, open or close it without using shortcut keys. 

**Client (please complete the following information):**
 - OS: MacOS Mojave Version 10.14.5
 - VNC client: TigerVNC
 - VNC client version: TigerVNC version 1.11.0
 - Client downloaded from: Oxford GitHub

**Server (please complete the following information):**
 - OS: Windows 
 - VNC server: TigerVNC 
 - VNC server version: TigerVNC version 1.11.0
 - Server downloaded from: TigerVNC version 1.11.0
 - Server was started using: ssh localhost
 - 
![Screen Shot 2021-01-12 at 8 56 21 AM](https://user-images.githubusercontent.com/61321454/104351256-68964800-54c2-11eb-943b-d47d6d2e373a.png)

**Comment by CendioOssman** [comment]
You've specified that you are using Windows on the server, but that screen shot looks very much like a Linux application. Are you sure the details are correct?

And the server download information and how you started the server needs more details for us to be able to help you.

**Comment by agiuffre** [comment]
Hi there

Sorry I am not physically in Oxford so I assumed I was using a Windows server. It very well might be a Linux application.
I’m not sure how to check this.

I use a VPN to establish a remote connection. Then through terminal I use -ssh -C -L 5917:jalapeno.fmrib.ox.ac.uk:5917<http://jalapeno.fmrib.ox.ac.uk:5917> “my username”. After I’ve logged in. I open TigerVNC (screenshot attached) and login using my Oxford username/password (screenshot attached). Once I open my window, I have terminal open/running. I am unable to minimize, move, or close my terminal window. I cannot open Firefox or other applications without doing so in terminal. I’m unable to get to my Home Screen, switch desktops, or see any other settings. If I use fn8 I am able to open an options menu - I attached a screenshot of the screen resolution - I am wondering if that might be the issue too?

Thanks for your help. I really appreciate it.

Adrianna


 [cid:C55D4C95-DFEA-4721-AF3C-EF00C9CF0FC2] [cid:7CBACC37-2C7B-4D47-8FCE-7FEAC11D35EA] [cid:DFB445FA-433A-469C-AF54-5CBC4ED9B13D]

On Jan 18, 2021, at 6:02 AM, Pierre Ossman (Work account) <notifications@github.com<mailto:notifications@github.com>> wrote:

[△EXTERNAL]




You've specified that you are using Windows on the server, but that screen shot looks very much like a Linux application. Are you sure the details are correct?

And the server download information and how you started the server needs more details for us to be able to help you.

**Comment by CendioOssman** [comment]
Unfortunately your attached screenshots are discarded by GitHub's mail gateway. I'm afraid you'll have to post them using the web interface.

We also need to know how the server is started. Have you started it yourself or was it set up by someone else?

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by mzechmeister** [comment]
I have a similar problem. It looks similar like here:
https://askubuntu.com/questions/1259891/xfce-vnc-environment-no-longer-has-control-bar-menus-for-screens-no-close-or-m
The windows have no toolbar/titlebar, thus no close button. The windows cannot be moved, etc.

In my case I have opensuse 15.0.
