### ISSUE TITLE
x0vncserver Dual monitors - Logging in Crashes display

### ISSUE THREAD

**Issue by m00nglum** [TigerVNC/tigervnc#1182]
**Describe the bug**
I'm running x0vncserver on my remote system.  I have tested it on other systems, and it works fine with one display. However, I have 2 displays on this remote system.  Each of them are at 1920x1080 (which is the maximum resolution for the monitors).  The server starts up fine, and tells me the desktop geometry is set to 3840x1080 -- which is what it should be to pull both displays.

The problem is this: as soon as I log remotely in with vncviewer (using tigervnc for server and viewer), the primary monitor crashes, and the other monitor's resolution drops from 1920x1080 to 1600x900.

When this happens, the x0vncserver console reports the following:

 Geometry:    Desktop geometry is set to 3480x1080+0+0
 XDesktop:    Got request for framebuffer resize to 3840x1080
 XDesktop:    1 screen(s)
 XDesktop:        1804289383 (0x6b8b4567): 3840x1080+0+0 (flags 0x00000000)
 XDesktop:    
 XDesktop:    Testing screen layout
 RandR:       Resizing screen framebuffer to 3840x1080
 RandR:       Output 'DP-2' does not support required mode 3840x1080
 XDesktop:    Impossible layout - trying to adjust
 XDesktop:    Adjusted resize request to 1920x1080
 XDesktop:    Changing screen layout
 RandR:       Reconfiguring output 'DP-2' to 1920x1080+0+0

It is as if it is trying to force 3840x1080 to each monitor, rather than across monitors.

**To Reproduce**
1. Install tigervnc 1.10.1+dfsg-3 on Ubuntu or KDE Neon system onto a dual monitor system with 1080p monitors
2. Start the server on the remote system like so:
     screen -S vncserver -d -m /usr/bin/x0vncserver -display :0 -SecurityTypes=VeNCrypt,TLSVnc,X509vnc -X509Cert ~/.vnc/cert/ca_server.crt -X509Key ~/.vnc/cert/ca_server.key -rfbauth /home/cditri/.vnc/passwd -Log *:stderr:100
3. Install the same version of tiger on the remote system, and connect using a command like this:
     vncviewer -SecurityTypes=VeNCrypt,X509Vnc -X509CA ~/.vnc/cert/remote_system.pem 192.168.44.44
4. Watch as it pulls the remote session, then quickly resizes the screen down to one monitor at 1600x900.  Of course, this changes the actual resolution on the remote monitor as well.

As shown above,  you can see it is set properly on the server, then it  promptly changes it to single monitor, at 1600x900, because (at least it looks like) it is trying to apply 3840x1080 to each  monitor, instead of splitting it between the two.  Or maybe the problem is that it only sees "1 screens".

I don't know if it matters, but I do some CAD work now and then, so this system has an NVIDIA Quadro on it with the NVIDIA proprietary drivers.

I've tried forcing the size on the server side with the "-Geometry" option, but it doesn't change anything.  I've tried on both server side and viewer side to use the "-Geometry" -"RemoteResize" and "-Desktop Resize"... the result is always the same. 

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: Distributor ID: Neon
Description:    KDE neon User Edition 5.20
Release:        20.04
Codename:       focal

 - VNC client: [e.g. TigerVNC
 - VNC client version:  1
 - Client downloaded from:my Linux distribution

**Server (please complete the following information):**
 - OS: Description:    KDE neon User Edition 5.20
Release:        20.04
Codename:       focal
 - VNC server: TigerVNC
 - VNC server version: 1.10.1+dfsg-3
 - Server downloaded from: e.g. my Linux distribution
 - Server was started using: x0vncserver

Thank you.

**Comment by CendioOssman** [comment]
It looks like the client is reconfiguring your screen dimensions and things go a bit sideways.

You can disable this feature in either the server or client. On the server this is done via `-AcceptSetDesktopSize=0`, and on the client via `-RemoteResize=0` or the same setting in the GUI.

Does that make things behave better for you?

**Comment by m00nglum** [comment]
Hi Pierre,

Yes, and no...

My command to start it didn't use the '='... most of the parameters  
seem very tolerant not using that (using a space instead), but that  
one (AcceptSetDesktopSize) seems to demand an '='... so when I was  
using it with a space instead, the command kept bombing-out.  I blew  
by it and continued trouble-shooting other strategies.  that was so  
early on, I forgot about it.

Using the '=' sign on the x0vncserver side did the trick. I'm sorry to  
have bothered you, I just missed that one.

Thanks you for your help.

g


Quoting "Pierre Ossman (Work account)" <notifications@github.com>:

**Comment by CendioOssman** [comment]
No problem. There are a lot of settings and easy to miss things. :)
