### ISSUE TITLE
Simultaneous local and vncsessions in centos 8

### ISSUE THREAD

**Issue by imonmondal** [TigerVNC/tigervnc#1183]
The new version of the tigervnc for Centos 8 does not seem to allow the user to have simultaneous local and vnc logins. I am logged out of my local session if a vncsession is open.

Is this done on purpose, or am I missing something really simple?

**Comment by CendioOssman** [comment]
On purpose I'd say. But not by us. It's how the systems are designed these days and I'd advise poking Red Hat about improving things in the future.

This was also reported on #1179.
