### ISSUE TITLE
Authentication failure: No valid VeNCrypt sub-type

### ISSUE THREAD

**Issue by tenzotheskymonk** [TigerVNC/tigervnc#1185]
Hello, I am very new to using VNCs, so apologies if my question is ignorant. I downloaded TigerVNC and tried to connect but I am getting the error: "Authentication failure: No valid VeNCrypt sub-type." I tried unticking "None" and "Standard VNC" in the Encryption and Authentication sections, as my supervisor recommended, but that didn't work. I am not sure how to proceed. Please let me know if you require any other information. As I said, I am very new to VNCs, so I don't know what information is helpful.

**Comment by CendioOssman** [comment]
That error means your server and client failed to find an authentication method that both support. So we need to know more about your setup.

Could you please fill out the issue bug form we have, and not bypass it. The questions on it are important.

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by rasaasar** [comment]
Hello there,

I'm facing the same issue. 

Tigervnc server and client are 1.14v. 
I use pem certificate and key, generated by this guide:
https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection
TLC with X.509 certificates encryption type is selected on the server side.

**Comment by wahibre** [comment]
May help others...  

I've got this error "Authentication failure: No valid VeNCrypt sub-type." when I place config file in a wrong place on a server side. After moving it to $HOME/.config/tigervnc it starts working correctly.  I guess server was running with some default options set by distribution (without Securitytype set to X509Vnc )

**Comment by rasaasar** [comment]
Thank you, wahibre.
It is already solved.  There was a missing authentication type in the config (reg).
