### ISSUE TITLE
vncviewer blurry under MacOS Big Sur

### ISSUE THREAD

**Issue by levens** [TigerVNC/tigervnc#1197]
I am using vncviewer on MacOS (with a "retina" display) to connect to a Linux host. vncviewer is running in "Low Resolution" mode. Since upgrading from Catalina to Big Sur, the vncviewer session is "blurry". This is very obvious when using a pixel font.

**Catalina:**
<img width="642" alt="catalina" src="https://user-images.githubusercontent.com/6270706/107140062-f3caf800-691f-11eb-93f8-202127bcee8c.png">

**Big Sur:**
<img width="642" alt="big_sur" src="https://user-images.githubusercontent.com/6270706/107140069-fcbbc980-691f-11eb-92ac-71259868c6c1.png">

Zooming the images you can see that under Catalina the scaling was simply repeating each pixel 4x. Whereas in Big Sur some sort of anti-aliasing is applied.

**Catalina:**
<img width="801" alt="catalina_zoom" src="https://user-images.githubusercontent.com/6270706/107140151-72c03080-6920-11eb-9eb9-4d198146b3ee.png"> 

**Big Sur:**
<img width="801" alt="big_sur_zoom" src="https://user-images.githubusercontent.com/6270706/107140153-73f15d80-6920-11eb-878d-779fa6463693.png">

I'm not sure if Apple provides any control over this (I guess not).

**Comment by CendioOssman** [comment]
I can see the same thing here, so I have to assume that Apple decided to change things. Perhaps they are considering non-integer scaling and did this to be consistent.

Still, it is outside of our control until #878 gets fixed. And I'm not aware of any settings in macOS for this.
