### ISSUE TITLE
Universal build for Apple Silicon Macs

### ISSUE THREAD

**Issue by levens** [TigerVNC/tigervnc#1199]
Based on the Makefiles provided in #877, I have successfully managed a build a version of vncviewer for Apple Silicon Macs. This is sufficient for my needs, but I guess it would be nice to provide a "Universal" version for download.

I took the latest version of all dependencies and needed to make a few changes to the Makefile to build them:

1. **gmp:** remove the `ABI=64` flag
2. **nettle:** add the `--disable-assembler` flag as it looks like arm64 assembly is not fully supported yet
3. **fltk:** change `OPTION_USE_SYSTEM_LIBPNG` from `0` to `1` otherwise I got an undefined symbol error

I also had to build **pixman** and **libjpeg-turbo** myself. It seems that the released version of libjpeg-turbo includes arm64, but only for iOS, which causes an error.

Anyway, my modified version of the Makefile is attached... I hope it is helpful...

[Makefile.txt](https://github.com/TigerVNC/tigervnc/files/5943471/Makefile.txt)

**Comment by CendioOssman** [comment]
Thank you, but I'm afraid we don't try to maintain a complete build environment for any platform. It's simply too much work and outside the scope of this project. @bphinz might be interested in his build environment though.

Have you looked at contributing to homebrew to get these fixes in there?
