### ISSUE TITLE
Issues connecting to display, files not found, black screen

### ISSUE THREAD

**Issue by kennyparsons** [TigerVNC/tigervnc#1200]
**Describe the bug**
I'm getting several errors in my log after starting the server and only getting a black screen after trying to connect. Logs here: https://pastebin.com/eFj4HX9q

**To Reproduce**
I have a need for a centralized desktop environment. I have a central server at home, running headless debian VMs, which are installed without a desktop environment (when put into production, this VM won't have a physical or logical graphical display). 

- I first installed gnome desktop environment with tasksel. So far so good. 
- I set systemctl to boot to text mode and not launch a desktop environment (to save resources when i'm not vnc'ing in). Also, so far so good. 
- I installed tigervnc packages from apt
- as a non-root user not added to sudo group:
  - ran vncpassword and set the password
  - created xstartup in ~/.vnc/ with the following:
```sh
#!/bin/sh
# Start Gnome 3 Desktop
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -iconic &
dbus-launch --exit-with-session gnome-session &
As the non-root user, I run: 
vncserver -depth 24 -geometry 1440x900 -localhost no
```
Everything works as expected, I can VNC in with the appropriate password to a gui that exits after the vncserver is shutdown. 
Now, the end goal was to create a docker container. This was going to be deployed in an environment where multiple users would need a container for a short time and then close down. I was inspired by [this container](https://github.com/x11vnc/x11vnc-desktop) but it was built on ubuntu with xfce. I don't want ubuntu or xfce, so i decided to roll my own. 

As the base image, I used https://hub.docker.com/r/jgoerzen/debian-base-minimal, which is exactly what I want. Unlike the debian:buster images, it does run systemd and a number of other traditional unix components. And, It was similar to the container i linked above as the inspiration, just Debian based. 

Here is my dockerfile:
```
FROM jgoerzen/debian-base-minimal

COPY scripts/ /opt/scripts/

RUN apt update \
	&& DEBIAN_FRONTEND=noninteractive apt install -y \
		--no-install-recommends \
		apt-utils \
		apt-file \
	&& DEBIAN_FRONTEND=noninteractive apt install -y \
		wget \
		git \
		runit \
		build-essential \
		libssl-dev \
		x11-xserver-utils \
		dbus-x11 \
		dos2unix \
		python \
		python3 \
		python3-distutils \
		python3-tk \
		python3-dbus \
		tigervnc-standalone-server \
		tigervnc-xorg-extension \
		xauth \
		tasksel \
		dialog \
	&& DEBIAN_FRONTEND=noninteractive tasksel install desktop gnome-desktop \
	&& useradd -ms /bin/bash vncuser \
	&& mkdir -p /home/vncuser/.vnc/ \
	&& mv /opt/scripts/xstartup /home/vncuser/.vnc \
	&& chown -R vncuser:vncuser /home/vncuser/.vnc/ /opt/scripts/* \
	&& chmod 700 /home/vncuser/.vnc/xstartup \
	&& chmod 700 /opt/scripts/*
	
ENTRYPOINT ["/bin/bash", "/opt/scripts/010.vncsetup.sh"]
```

At the moment, the entrypoint script just sleeps as a place holder. I start the container with: 
docker run -d -p 5901:5901 --stop-signal=SIGRTMIN+3 --tmpfs /run:size=100M --tmpfs /run/lock:size=100M -v /sys/fs/cgroup:/sys/fs/cgroup:ro gdd:latest

After exec'ing into the container, I attempt to reproduce the same setup steps as with my VM:
su - vncuser (non-root user with no sudo)
create the xstartup file just as above.
vncserver -depth 24 -geometry 1440x900 -localhost no
Here is the output:
```
vncuser@30c00abe898f:~/.vnc$ vncserver -depth 24 -geometry 1440x900 -localhost no
You will require a password to access your desktops.
Password:
Verify:
Would you like to enter a view-only password (y/n)? n
/usr/bin/xauth:  file /home/vncuser/.Xauthority does not exist
New '30c00abe898f:1 (vncuser)' desktop at :1 on machine 30c00abe898f
Starting applications specified in /home/vncuser/.vnc/xstartup
Log file is /home/vncuser/.vnc/30c00abe898f:1.log
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/vncuser/.vnc/passwd 30c00abe898f:1 to connect to the VNC server.
```

**Expected behavior**
When i VNC in it's just a black screen. According to the logs, I'm getting a lot of "connection refused" "cannot open display" and "file not found" errors before I even try to connect, so something is really wrong with my config.

**Screenshots**
![image](https://user-images.githubusercontent.com/5930491/107419358-51f10a00-6add-11eb-9b07-d0859a7bcbca.png)

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: RealVNC
 - VNC client version: 6.20.529
 - Client downloaded from: realvnc directly

**Server (please complete the following information):**
 - OS: debian docker environment
 - VNC server: tigervnc
 - VNC server version: 
```
tigervnc-common/stable,now 1.9.0+dfsg-3+deb10u3 amd64 [installed,automatic]
tigervnc-standalone-server/stable,now 1.9.0+dfsg-3+deb10u3 amd64 [installed]
tigervnc-xorg-extension/stable,now 1.9.0+dfsg-3+deb10u3 amd64 [installed]
```
 - Server downloaded from: debian apt repos
 - Server was started using: vncserver -d 24 -geometry 1440x900 -localhost no

I would be most grateful for some help. I tried the google groups, but didn't get any hits there.

**Comment by CendioOssman** [comment]
I'm afraid we no longer support the old xstartup method. You need to upgrade to TigerVNC 1.11.0 and use the systemd service for stable desktop environment startup. This also means you need to get systemd properly up and running in Docker, which needs some extra steps. It's unfortunately not something we have any guide for though.

**Comment by kennyparsons** [comment]
I can get systemd in docker, but do you have any guides on how to run it properly with systemd instead of xstartup

**Comment by CendioOssman** [comment]
We just added a HOWTO from fedora. You can find it here: https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md
