### ISSUE TITLE
VNCViewer error on macOS 

### ISSUE THREAD

**Issue by wangjia184** [TigerVNC/tigervnc#1202]
**Describe the bug**

The process crashes after exit.

The application still can work properly before crashing.

**To Reproduce**
1. Download the vncviewer.jar 1.11 from web site
2. Click on the downloaded jar file to start
3. exit the application by click X

**Screenshot**
Sorry for Chinese UI.  the screenshot says there is something wrong with the process and it crashed.
![image](https://user-images.githubusercontent.com/2765840/107717507-be068480-6d0e-11eb-8c8c-765fb8276fe3.png)

**Client:**
 - OS: macOS 11.2.1 Big Sur
 - VNC client: VncViewer-1.11.02.jar
 - CPU : Apple silicon M1
 - JRE : Zulu: 15.29.15 for macOS Arm64

```
$java --version
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment Zulu15.29+15-CA (build 15.0.2+7)
OpenJDK 64-Bit Server VM Zulu15.29+15-CA (build 15.0.2+7, mixed mode)
```

**Additional Information**

Here are warnings from command line.
```
$ java -jar VncViewer-1.11.02.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.tigervnc.vncviewer.VncViewer (file:/Users/jerry/Applications/VncViewer-1.11.02.jar) to method com.apple.eawt.Application.getApplication()
WARNING: Please consider reporting this to the maintainers of com.tigervnc.vncviewer.VncViewer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

TigerVNC Java Viewer v1.11.0 (20200908)
Built on 2020-09-08 at 23:40:58
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
```

**Comment by CendioOssman** [comment]
@bphinz , any ideas? Do you know if your builds have been tested on the M1?

**Comment by bphinz** [comment]
I don't think it's M1 related, probably just something new or deprecated in
OpenJDK 15.  I just finished the project that I was on that has been
consuming all of my time for the past year so I should have time to look at
these issues now.

**Comment by bphinz** [comment]
Maybe this is M1 related...?  I don't have access to any M1 hardware, and I can't reproduce this on x86_64 using OpenJDK 8, 11, or 17.  I fixed the cause of the reflection warnings.  They're related to setting the dock icon so it's possible that's the cause, but I don't think that would be processor-specific.  @wangjia184 can you please test the latest night build to see whether or not that's the case?

**Comment by bphinz** [comment]
Closing due to no response.  I'm unable to replicate using various JREs on both Intel and Apple silicon
