### ISSUE TITLE
"readTLS: Error in the pull function (-54)" when trying to access remote Ubuntu machine from Windows

### ISSUE THREAD

**Issue by FurlanMAlp** [TigerVNC/tigervnc#1204]
**Bug description**
Hi there. I have been trying to get a functional VNC server to remotely access an Ubuntu 20.04.2 LTS Machine via Windows 10 for quite a while, trying various options in the process, and the closest I got to achieving this was done by using x0vncserver on the host machine and TigerVNC as a client. 

It runs smoothly, but crashes unexpectedly with no clear patterns of time and action. It may crash as soon as I establish the connection or after some minutes of usage, by typing in the terminal or by scrolling down a webpage. The messages I get are the following, even though I'm only addressing the first of these in this issue. The second one, in portuguese, reads "An established connection was aborted by the software in your host machine", and I believe it is important to link it here as well, as it can (hopefully) shed some light on the issue.

![090221 - TigerVNC - error in the pull function](https://user-images.githubusercontent.com/72931142/107820035-e5823f00-6d58-11eb-9a94-084d8900d48c.png)

![090221~2](https://user-images.githubusercontent.com/72931142/107820203-24b09000-6d59-11eb-93ca-ab58fdd217d4.PNG)

What can be happening here? For the second error, there are plenty of information around the internet, but none of it seem really useful for our particular case, as it seems to happen in the most diverse situations. In contrast, the first has no available information on the internet whatsoever, as far as I can tell. For the sake of truth, there is a similar issue here about the same topic, but it was deemed invalid. 

**Expected behavior**
Running the VNC server without abrupt crashes.

**Client:**
 - OS: Windows 10 64-bit
 - VNC client: TigerVNC 
 - VNC client version: both 1.11.0 and 1.11.80
 - Client downloaded from: https://bintray.com/tigervnc/stable/tigervnc/1.11.0 for the former (vncviewer64-1.11.0.exe) and http://tigervnc.bphinz.com/nightly/viewers/vncviewer64-1.11.80.exe for the latter

**Server:**
 - OS: Ubuntu 20.04.2 LTS
 - VNC server: x0vncserver
 - VNC server version:  1.10.1+dfsg-3
 - Server downloaded from: from my Linux Distribution
 - Server was started using: x0vnc 

**Additional context**
- x0vnc runs the script with the same name, saved in .local/bin/, containing our command line to run x0vncserver;
- It should be noticed that we also had to create a batch file on the client machine to establish the tunnel manually, otherwise TigerVNC would say that the host actively rejected the connection;
- I am also using a laptop, while the host machine is the equivalent of a gamer PC, in my view. If more detail is needed, please ask below;
- We use a Cisco VPN Client, Version 5.0.07.0440.

**Logs**
For now, I will only leave the client log and if more information is needed, I can supply the server log for you. Tried to send these in code but don't know how to do it, as this is my first github issue.

```
>Fri Feb 12 17:12:39 2021
 Win32TouchHandler: The 'Tablet PC Input' service is required for touch
 Win32TouchHandler: Two touch points required, system currently supports: 0

>Fri Feb 12 17:12:41 2021
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to localhost [::1] port 5901
 CConn:       Connected to host localhost port 5901
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Server offers security type VncAuth(2)
 CConnection: Choosing security type VeNCrypt(19)
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CVeNCrypt:   Server offers security type TLSVnc (258)
 CConnection: processing security message
 CVeNCrypt:   Server offers security type VncAuth (2)
 CVeNCrypt:   Choosing security type TLSVnc (258)
 CConnection: processing security message
 TLS:         Anonymous session has been set
 CConnection: processing security message`

>Fri Feb 12 17:12:42 2021
 CConnection: processing security message
 TLS:         TLS handshake completed with
              (TLS1.2)-(ANON-ECDH)-(AES-256-CBC)-(SHA1)
 Win32TouchHandler: The 'Tablet PC Input' service is required for touch
 Win32TouchHandler: Two touch points required, system currently supports: 0

>Fri Feb 12 17:12:44 2021
 CConnection: processing security result message
 CConnection: processing security result message
 CConnection: Authentication success!
 CConnection: reading server initialisation
 CConnection: initialisation done
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 Win32TouchHandler: The 'Tablet PC Input' service is required for touch
 Win32TouchHandler: Two touch points required, system currently supports: 0
 CConnection: Enabling continuous updates

>Fri Feb 12 17:12:49 2021
 DesktopWindow: Requesting framebuffer resize from 1368x768 to 1536x801
 DesktopWindow: 1 screen(s)
 DesktopWindow:     1804289383 (0x6b8b4567): 1536x801+0+0 (flags 0x00000000)
 DesktopWindow: 
 CConn:       SetDesktopSize failed: 3

>Fri Feb 12 17:12:53 2021
 Viewport:    Key pressed: 0x0023 => 0x0068
 Viewport:    Key released: 0x0023 => 0x0068
 Viewport:    Key pressed: 0x0012 => 0x0065
 Viewport:    Key released: 0x0012 => 0x0065
 Viewport:    Key pressed: 0x002d => 0x0078
 Viewport:    Key released: 0x002d => 0x0078
 Viewport:    Key pressed: 0x0013 => 0x0072
 Viewport:    Key released: 0x0013 => 0x0072
 Viewport:    Key pressed: 0x0018 => 0x006f

>Fri Feb 12 17:12:54 2021
 Viewport:    Key pressed: 0x001e => 0x0061
 Viewport:    Key released: 0x0018 => 0x006f
 Viewport:    Key released: 0x001e => 0x0061
 Viewport:    Key pressed: 0x002e => 0x0063
 Viewport:    Key released: 0x002e => 0x0063
 Viewport:    Key pressed: 0x0023 => 0x0068
 Viewport:    Key released: 0x0023 => 0x0068
 Viewport:    Key pressed: 0x001c => 0xff0d
 Viewport:    Key released: 0x001c => 0xff0d

>Fri Feb 12 17:13:01 2021
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52

>Fri Feb 12 17:13:02 2021
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52

>Fri Feb 12 17:13:03 2021
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52

>Fri Feb 12 17:13:04 2021
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52

>Fri Feb 12 17:13:05 2021
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52

>Fri Feb 12 17:13:06 2021
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52

>Fri Feb 12 17:13:07 2021
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52

>Fri Feb 12 17:13:08 2021
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52

>Fri Feb 12 17:13:09 2021
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52

>Fri Feb 12 17:13:10 2021
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52

>Fri Feb 12 17:13:11 2021
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00c8 => 0xff52

>Fri Feb 12 17:13:12 2021
 Viewport:    Key released: 0x00c8 => 0xff52
 Viewport:    Key pressed: 0x00d0 => 0xff54
 CConn:       readTLS: Error in the pull function. (-54)
 Win32TouchHandler: The 'Tablet PC Input' service is required for touch
 Win32TouchHandler: Two touch points required, system currently supports: 0
```

Thank you very much in advance.

**Comment by FurlanMAlp** [comment]
For more clarity, the command on the x0vnc binary is the one below,
`x0vncserver -display :1 -rfbauth ~/.vnc/passwd -rfbport 5901 -AlwaysShared -Log "*:stdout:100" > tigervnc-x0vncserver.log &
`,
where the `-Log "*:stdout:100" > tigervnc-x0vncserver.log` was added to get the logs. 

I have also changed my mind and both the Ubuntu and Windows logs are annexed to this answer, respectively, for practical reasons.
[tigervnc-x0vncserver-issue.log](https://github.com/TigerVNC/tigervnc/files/5974392/tigervnc-x0vncserver-issue.log)
[vncviewer.log](https://github.com/TigerVNC/tigervnc/files/5974401/vncviewer.log)

**Comment by CendioOssman** [comment]
That error is rather generic, yes. It means that the network connection was killed by something external. Since there is no such message on the server, it would be something on your network. Given that you have a VPN client then that would be my first guess. Or perhaps some firewall between you and your VNC server.

Unfortunately we are unable to provide any more help than that. The TigerVNC client just gets information that *something* killed the connection, and no details what. So you'll have to do some testing to figure out what on your network is misbehaving. :/

**Comment by amonott** [comment]
We have been hunting this bug for years, but recently it became nasty. Yesterday we found it, at least for our own version of VNC based on TigerVNC.
The reason is a race condition with errno in separate threads for GnuTLS push and pull. The TigerVNC pull function sets errno to EAGAIN and returns -1 to indicate that no data is available. In the meantime, GnuTLS code in the push line or some completely other code can set a different per-session or global errno value, so that in the pull line we suddenly get a fatal error indicated.
Our solution is to have our own errno_func for the GnuTLS session with our own errno variable, which is only used for pull. Our push never returns -1 and thus avoids a new race here, but the custom errno_func can also check for the correct transport function and deliver the correct value.

The hint about unreliable errno and how to set a custom errno function are there:
https://gnutls.org/manual/html_node/Core-TLS-API.html#gnutls_005ftransport_005fset_005ferrno

**Comment by CendioOssman** [comment]
We don't use threads for GnuTLS, so there is no risk for a race in our code. Also, errno is supposed to be thread safe. So I don't see any reason to mistrust the diagnosis on this bug.

That documentation also mentions that problems can appear if GnuTLS and the application was linked against different C libraries. Could that be what is causing issues for you? If you have more details to your situation then please file a new issue and we can have a look.

**Comment by amonott** [comment]
Well, we are happy with our solution, so I am not going to file a new issue. If you get more similar reports, you now know what might help.
