### ISSUE TITLE
Status 71. Can't start vncserver service. Not listening to port.

### ISSUE THREAD

**Issue by Pluser761** [TigerVNC/tigervnc#1205]
**Describe the bug**
<pre><font color="#06989A"><b>~</b></font> &gt;<font color="#06989A">&gt;</font><font color="#06989A"><b>&gt;</b></font> <font color="#4E9A06">systemctl</font> status vncserver@:1.service</pre>

**To Reproduce**
Just try to start service, you'll get:
<pre>Feb 13 12:58:36 manjaropluser systemd[1]: Starting Remote desktop service (VNC)...
Feb 13 12:58:36 manjaropluser vncsession[5225]: pam_unix(tigervnc:session): session opened for user remote(uid=1001) by (uid=0)
Feb 13 12:58:36 manjaropluser systemd[1]: Started Remote desktop service (VNC).
Feb 13 12:58:36 manjaropluser vncsession[5225]: <font color="#D7D75F"><b>vncsession: vncserver exited with status=71</b></font>
Feb 13 12:58:36 manjaropluser vncsession[5225]: pam_unix(tigervnc:session): session closed for user remote
Feb 13 12:58:36 manjaropluser systemd[1]: vncserver@:1.service: Succeeded.
</pre>

**Expected behavior**
At least, i wanted to see listening port, but ..
<pre><font color="#06989A"><b>~</b></font> &gt;<font color="#06989A">&gt;</font><font color="#CC0000"><b>&gt;</b></font> <font color="#4E9A06">ss</font> -tln                                                                                                                        <font color="#CC0000"> [3]</font>
State           Recv-Q          Send-Q                   Local Address:Port                   Peer Address:Port          Process          
LISTEN          0               128                          127.0.0.1:631                         0.0.0.0:*                              
LISTEN          0               128                              [::1]:631                            [::]:*                  </pre>
and process is dead ..
<pre>● vncserver@:1.service - Remote desktop service (VNC)
     Loaded: loaded (/usr/lib/systemd/system/vncserver@.service; disabled; vendor preset: disabled)
     Active: inactive (dead)

Feb 13 12:48:54 manjaropluser systemd[1]: Started Remote desktop service (VNC).
Feb 13 12:48:54 manjaropluser vncsession[4718]: <font color="#D7D75F"><b>vncsession: vncserver exited with status=71</b></font>
Feb 13 12:48:54 manjaropluser vncsession[4718]: pam_unix(tigervnc:session): session closed for user remote
Feb 13 12:48:54 manjaropluser systemd[1]: vncserver@:1.service: Succeeded.
Feb 13 12:58:36 manjaropluser systemd[1]: Starting Remote desktop service (VNC)...
Feb 13 12:58:36 manjaropluser vncsession[5225]: pam_unix(tigervnc:session): session opened for user remote(uid=1001) by (uid=0)
Feb 13 12:58:36 manjaropluser systemd[1]: Started Remote desktop service (VNC).
Feb 13 12:58:36 manjaropluser vncsession[5225]: <font color="#D7D75F"><b>vncsession: vncserver exited with status=71</b></font>
Feb 13 12:58:36 manjaropluser vncsession[5225]: pam_unix(tigervnc:session): session closed for user remote
Feb 13 12:58:36 manjaropluser systemd[1]: vncserver@:1.service: Succeeded.
</pre>

**PC configuration:**
<pre><font color="#06989A"><b>~</b></font> &gt;<font color="#06989A">&gt;</font><font color="#06989A"><b>&gt;</b></font> <font color="#4E9A06">uname</font> -r                                                                                                                          <font color="#CC0000"> </font>
5.9.16-1-MANJARO
<font color="#06989A"><b>~</b></font> &gt;<font color="#06989A">&gt;</font><font color="#06989A"><b>&gt;</b></font> <font color="#4E9A06">pacman</font> -Qs tiger                                                                                                                  <font color="#CC0000"> </font>
local/tigervnc 1.11.0-6
    Suite of VNC servers and clients. Based on the VNC 4 branch of TightVNC.</pre>

**Additional info**
<pre>
<font color="#06989A"><b>~</b></font> &gt;<font color="#06989A">&gt;</font><font color="#06989A"><b>&gt;</b></font> <font color="#4E9A06">ls</font> <u style="text-decoration-style:single">.vnc</u>                                                                                                                           <font color="#CC0000"> </font>
config	passwd
<font color="#06989A"><b>~</b></font> &gt;<font color="#06989A">&gt;</font><font color="#06989A"><b>&gt;</b></font> <font color="#4E9A06">cat</font> <u style="text-decoration-style:single">.vnc/config</u>                                                                                                                   <font color="#CC0000"> </font>
session=gnome
<font color="#06989A"><b>~</b></font> &gt;<font color="#06989A">&gt;</font><font color="#06989A"><b>&gt;</b></font> <font color="#4E9A06">cat</font> <u style="text-decoration-style:single">/etc/tigervnc/vncserver.users</u>                                                                                                 <font color="#CC0000"> </font>
# TigerVNC User assignment
#
# This file assigns users to specific VNC display numbers.
# The syntax is &lt;display&gt;=&lt;username&gt;. E.g.:
#
# :2=andrew
# :3=lisa

:1=remote
<font color="#06989A"><b>~</b></font> &gt;<font color="#06989A">&gt;</font><font color="#06989A"><b>&gt;</b></font> </pre>

**Comment by CendioOssman** [comment]
So the server is failing to start for some reason. Have you checked for a log in `~/.vnc`?

What does the rest of the journal say when trying to start the server?

**Comment by Pluser761** [comment]
> So the server is failing to start for some reason. Have you checked for a log in `~/.vnc`?
> 
> What does the rest of the journal say when trying to start the server?

Don't have any logs here
![image](https://user-images.githubusercontent.com/29662067/109506518-c56bb300-7aae-11eb-90a1-f829d8dd9f6d.png)

**Comment by CendioOssman** [comment]
Is that as the user `remote`? Your prompt seems to suggest it's as the user `pluser`.

**Comment by Pluser761** [comment]
I don't have home directory for remote user, so i can's see the log. But it doesn't matter. Because if i configure pluser in /etc/tigervnc/vncserver.users (:1=pluser), i'll still get 
<pre><font color="#D7D75F"><b>vncsession: vncserver exited with status=71</b></font></pre>
and no logs in ~/.vnc

**Comment by CendioOssman** [comment]
That means it is failing early during startup. And such failures should end up in the journal. Not quite sure what it is up to in that case. :/

Let's try `sudo strace -f /usr/libexec/vncsession-start :1` and see what that says?

**Comment by Pluser761** [comment]
On that i get
<pre>strace: Can&apos;t stat &apos;/usr/libexec/vncsession-start&apos;: No such file or directory</pre>
but i tried
<pre><font color="#4E9A06"><u style="text-decoration-style:single">sudo</u></font> <font color="#4E9A06">strace</font> -f vncsession-start :1</pre>
and here we are
[output.txt](https://github.com/TigerVNC/tigervnc/files/6074871/output.txt)

**Comment by CendioOssman** [comment]
Something is off with the access on the home directories. I can see this in the log:

```
[pid 48386] openat(AT_FDCWD, "/home/pluser/.vnc/manjaropluser:1.log", O_WRONLY|O_CREAT|O_TRUNC, 0644) = -1 EACCES (Permission denied)
```

What are the access bits on `/home/pluser/.vnc`? Are you using SELinux?

I can also see it writing an error message, so I have no idea why that isn't included in the logs:

```
[pid 48386] write(3, "open: Permission denied\n", 24) = 24
```

**Comment by Pluser761** [comment]
`ls -l -a` shows
<pre>drwxr-xr-x  2 root   root     4096 Feb 13 12:48  .vnc</pre>

**Comment by CendioOssman** [comment]
Yeah, that isn't going to work. Make sure the directory is owned by the user and not root.

**Comment by Pluser761** [comment]
I've changed to `drwxr-xr-x  2 pluser root     4096 Mar  5 11:57  .vnc`
and now i get `status=29`. Log is below
[output.txt](https://github.com/TigerVNC/tigervnc/files/6089703/output.txt)

**Comment by CendioOssman** [comment]
It's getting further now, so you should have a log file now. But I'm also seeing the error in the strace:

> [pid  3437] write(2, "A VNC server is already running "..., 38) = 38

So there is already something running on :1. So either that needs to be killed, or another display should be allocated for the user. After that things should hopefully work fine.

**Comment by rwmjones** [comment]
If anyone else hits status=71, for me it was caused by SELinux on Fedora 43. Setting SELinux to Permissive got around it temporarily. Need to track down the missing permission and update the Fedora policy.
