### ISSUE TITLE
Maintain the Windows VNC server again

### ISSUE THREAD

**Issue by baptx** [TigerVNC/tigervnc#1213]
The GitHub project description says "High performance, multi-platform VNC client and server" but the README file says:
```
WARNING: winvnc is currently unmaintainted and and may not function correctly.
winvnc may not work if the Fast User Switching or Remote Desktop features are in use.
```
Is there any plan to support the TigerVNC Windows server again or we should use other software like TightVNC? If it is no longer supported, it would not be a multi-platform VNC server anymore and the GitHub description should be changed to avoid confusion.

I use Linux but I think a Windows VNC server can be useful to help a Windows user remotely from a Linux computer, as an open-source alternative to proprietary software like TeamViewer. I think the built-in RDP remote desktop feature on Windows can only work over the Internet when using a VPN or configuring the router of the person that wants to share their screen.
With a VNC server like TightVNC, this is not needed when using the reverse VNC feature "Attach Listening Viewer" as long as the VNC client has a public IP address, for example by configuring the router used for the VNC client or with a dedicated server / Virtual Private Server using SSH remote port forwarding.

**Comment by CendioOssman** [comment]
> Is there any plan to support the TigerVNC Windows server again or we should use other software like TightVNC?

For now you are probably better off using a maintained VNC server for Windows. I'm still hoping someone might take an interest and get involved in our WinVNC, but until then it's unlikely there will be any work done.

> If it is no longer supported, it would not be a multi-platform VNC server anymore and the GitHub description should be changed to avoid confusion.

Possibly. We're still multi-platform for the clients so it's not like we want to remove that part from the description. I haven't seen much signs of confusion so far so I think we can keep it for now.

**Comment by baptx** [comment]
@CendioOssman Is the TigerVNC server for MacOS still maintained? Then it would be possible to keep "multi-platform" in the description like that: "multi-platform VNC client and Linux / MacOS server".
The issue could be kept open to give more visibility if someone is interested to contribute.

**Comment by CendioOssman** [comment]
We've never had a macOS server. I'm not aware of any third party VNC servers for that platform.

Vague issues just tend to linger indefinitely unfortunately. We have issues open for the specific known problems with WinVNC if anyone wants to help out.

**Comment by LuffyLee0110** [comment]
is there a guidebook to guid us to build a winvnc server ? I follow the steps in the flie BUILDING.txt, but I get a executable exe not like what i get from the url "https://bintray.com/tigervnc/stable/tigervnc/1.11.0" . For example , my "winvnc4.exe" is 3286KB, but the exe from the url is 28,508KB. There is a large scale from the two exes.

**Comment by CendioOssman** [comment]
Likely you are using the dynamic linking, rather than static. You can enable static linking with `-DBUILD_STATIC=ON` when running `cmake`. Note that it requires your build environment to actually have static libraries, and many don't.

I would advise using the binary you have and simply include the DLLs it needs.
