### ISSUE TITLE
Error connecting to the KeX server. Please try "kex start" to start the service. If the server fails to start, please try "kex kill" or restart your WSL2 session and try again.

### ISSUE THREAD

**Issue by KingHack-X** [TigerVNC/tigervnc#1219]
Everytime I start kex it says: "Error connecting to the KeX server.
Please try "kex start" to start the service.
If the server fails to start, please try "kex kill" or restart your WSL2 session and try again." What can I do?

**Comment by CendioOssman** [comment]
I'm afraid KeX is not something part of TigerVNC so you'll have to contact that project and see if they can help you.

**Comment by bmyy12** [comment]
试试用kex --win -s
或许能成功

**Comment by bmyy12** [comment]
kex --esm --ip -s
试试这个命令,或许能帮助您
