### ISSUE TITLE
Configure yum and apt repos on bintray for downloads

### ISSUE THREAD

**Issue by kim0** [TigerVNC/tigervnc#122]
It would be great to allow downloading releases via yum and apt repos, instead of the current method (file by file) .. This should be almost trivial to implement afaik, but helps users a lot maintain an up2date installation

**Comment by CendioOssman** [comment]
I think that requires us to split things up differently since we have many RPMs for different distributions. And that would probably make things worse for people who just want to download the files.

**Comment by kim0** [comment]
People can are still able to download files manually from any yum repo afaik .. so not really an issue for those not wanting repos

**Comment by CendioOssman** [comment]
But as I understand it we would have to have one RHEL 5 repo, one RHEL 6 repo, one Ubuntu 12.04 repo, one Ubuntu 14.04 repo, etc.?

**Comment by bphinz** [comment]
I'll take a look at setting this up, it's something that I've been meaning
to get to...

-brian

**Comment by bphinz** [comment]
I'm not sure, I need to look into it.  If they were actually in folders the
way that they appear to be when you browse the files then it would be
rather staightforward.  However, the fact that you cannot have two files
with same name makes me think that on-disk it's all stored flat and if
that's the case then this becomes pretty unmanageable...  It's worth
looking into however.

**Comment by bphinz** [comment]
As far as I can tell, Pierre is right and this would require us to create separate "repositories" on bintray for each distro (el5, el6, ubuntu precise, ubuntu trusty, …).  IMO, this seems clumsy and difficult to maintain.

**Comment by CendioOssman** [comment]
So this doesn't seem like something we want to do as the tree layout is more important to us than having an automatic repository. Closing.

**Comment by hildred** [comment]
I don't know about yum, but an aptable repository does not mandate a pool structure. You can leave the binaries where they are. You would still need a specific structure for the release and package files, but as they are not present this would be an add to not a change of your directory structure. If you want I could write the generation scripts.

**Comment by JohnstonJ** [comment]
It's too bad this was closed.  Ubuntu lacks any usable/maintained VNC server: see my problem with xrdp, virt-manager and how TigerVNC fixed my problem here: http://askubuntu.com/a/779661/517965 - thank you TigerVNC!

It would be nice if an apt repository could be maintained, so that my installation (of both TigerVNC and all operating system packages) could be kept updated by way of:

    apt-get update
    apt-get upgrade

instead of having to manually check for updates for this package in particular.  Several other upstream projects maintain their own apt repositories, like X2Go Server, nginx, node.js, and so on... so it must be doable...

**Comment by CendioOssman** [comment]
It's a man power issue, not that it's impossible to do.

But first I'd suggest nagging Debian/Ubuntu to switch over from RealVNC to TigerVNC so that it ends up in the default repos. They might not be fully aware that users want a switch.

**Comment by JohnstonJ** [comment]
> It's a man power issue, not that it's impossible to do.

Understood...

> But first I'd suggest nagging Debian/Ubuntu to switch over from RealVNC to TigerVNC so that it ends up in the default repos.

It looks like there are already some efforts... hopefully they succeed...

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=654924
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=650394

Once that happens, it will probably reach Ubuntu...
