### ISSUE TITLE
Screen (mostly) not refreshing

### ISSUE THREAD

**Issue by tmo1** [TigerVNC/tigervnc#1220]
TigerVNC server doesn't refresh the client window. Keyboard and mouse are properly passed to the server, but the client window remains mostly frozen the way it was at VNC connection initiation. I can move the mouse on the server, and the mouse moves on the client, and vice versa. Clicking on the client has the expected effect. Keypresses on the client are passed through correctly as well.
Although most of the client window is frozen, I did notice that the browser title bar changes correctly when I click on browser tabs. I.e., although the browser content doesn't update and the original tab remains shown, the browser title bar changes appropriately when I click on various browser tabs.

**Clients:**
 - OS: Debian Sid
 - Clients: TigerVNC 1.11.0 and Remmina with VNC plugin (Debian Sid package)

**Server:**
 - OS: Debian Sid
 - VNC server: TigerVNC 1.11.0 (Debian Sid 'tigervnc-xorg-extension' package)

- **Additional context**

I configured the server via a "Load "vnc"" stanza in an Xorg configuration file. The server has an AMD RX-570 GPU, using the amdgpu driver from the distribution kernel (5.10.19).

**Comment by CendioOssman** [comment]
What desktop environment are you using in the VNC session? We've historically had issues with 3D drivers not properly reporting updates.

And do you get an updated image if you press `F8` and select `Refresh screen`?

**Comment by tmo1** [comment]
F8 / Refresh doesn't work.

I'm running a standard Debian Xfce DE. I thought that compositing was off, since I don't usually use it, but this is a relatively new installation and it turns out it was actually on. I turned it off, since I had seen in various discussion threads that compositing has caused trouble for TigerVNC (all VNCs?) in the past, and with it off, screen refresh works!

I'm not clear whether TigerVNC is supposed to support compositing. If it isn't, I suggest that this be documented somewhere.

Thanks for your work on this project!

**Comment by CendioOssman** [comment]
It supports compositing just fine in most cases. This is likely a driver bug we need to chase down.

In issue #1218 the problem seems to be glamor. Could you test if disabling that fixes thing?

**Comment by tmo1** [comment]
I'm happy to do that, but I've just spend a while trying to figure out how to do that without success :|. I tried adding the following stanza to `/etc/X11/xorg.conf.d/10-vnc.conf`:
`
Section "Module"
Disable "glamor"
EndSection
`
But Xorg.0.log still shows glamor loading. What do I do to disable it?

**Comment by joakim-tjernlund** [comment]
Section "Device"
  Identifier "intel"
  Driver "modesetting"
  #BusID  "pci:bus:dev:func"
  Option  "Atomic" "true"
  Option  "AccelMethod" "none"
EndSection

**Comment by joakim-tjernlund** [comment]
Any chance you can downgrade Xorg-server a couple of revisions?

**Comment by tmo1** [comment]
I'll try downgrading X when I get a chance. But about the glamor disabling: there's no Intel GPU here, just an AMD card (it's a workstation without onboard graphics). What do I use for `identifier`? And do I need to enter a `BusID`?

I apologize for all these questions, but I'd have no problem following directions if all this stuff was actually documented somewhere in an understandable fashion ;)

**Comment by joakim-tjernlund** [comment]
Dunno w.r.t glamor and AMD. I suspect glamor is an Intel thing ?

**Comment by joakim-tjernlund** [comment]
Identifier "name of your graphics card here"

Look in you Xorg log what the name is and use that

**Comment by CendioOssman** [comment]
> Dunno w.r.t glamor and AMD. I suspect glamor is an Intel thing ?

It's used by most drivers these days. It's using OpenGL for accelerating 2D stuff in favour of having to have specific code for each card.

**Comment by tmo1** [comment]
Okay, I ran X with this Xorg.conf section:

```
Section "Device"
  Identifier "AMDGPU"
  Driver "modesetting"
  Option  "Atomic" "true"
  Option  "AccelMethod" "none"
EndSection
```

Xorg log now contains `modeset(0): glamor disabled`, and TigerVNC screen refresh now seems to work fine, even with compositing re-enabled, although I have not tested extensively.

Thank you!

**Comment by joakim-tjernlund** [comment]
OK, so then we can be fairly sure this is a glamor vs  libvnc.so issue.
@CendioOssman , time to get some real GPU HW to test on :)

**Comment by joakim-tjernlund** [comment]
@tmo1, can you downgrade xorg-server a few minor 1.20.x releases ?
Do you know on which xorg-server this worked for you?

**Comment by tmo1** [comment]
I'm currently using 1.20.10. I'll look into downgrading when I get a chance.

**Comment by tmo1** [comment]
I just wanted to note that I just had the unpleasant surprise of my Android Emulator starting to crash on startup with exit code 139. Searching the web indicated that this is a problem with hardware graphics acceleration, and sure enough, setting the emulator to use software acceleration allows it to run - but with noticeably poorer performance than previously. I took out the Xorg stanza, and now hardware acceleration works again.

I'll see what I can do about trying out earlier 1.20.x versions of the X server, but it's a tricky process on Debian, where package downgrading isn't supported and is discouraged.

**Comment by CendioOssman** [comment]
Marking this as a duplicate as this seems to be the same issue as #1218.
