### ISSUE TITLE
Finnish translation not up-to-date with translationproject.org

### ISSUE THREAD

**Issue by lanurmi** [TigerVNC/tigervnc#1223]
**Describe the bug**

The current version of `po/fi.po` in git is from 2015. However, on translationproject.org there's a properly submitted 100% translation from 2019, by me, yet it is not committed to git.

http://translationproject.org/PO-files/fi/tigervnc-1.9.90.fi.po

**Comment by CendioOssman** [comment]
Sorry about that. I had gotten the notification but somehow it got lost before actually making it to the repo. It's been fixed in 5ff62b455868fedd619c131108624a645b6d854a.
