### ISSUE TITLE
x0vncserver - Could not map key event to X11 key code -- Ubuntu Focal (20.04)

### ISSUE THREAD

**Issue by delphir-com** [TigerVNC/tigervnc#1224]
I just upgraded from 18.04 to 20.04 and got an issue with the Cyrillic (Russian) locale when using with x0vncserver 1.10.1

each time when I'm expecting to type a cyrillic character I`m getting a console message:

```
XDesktop:    Could not map key event to X11 key code
```

I manually downgraded to 1.7.0 (which is the actual version in 18.04) and the issue disappeared. 
I also tested tigervnc-1.11.80-20210322git06e53809.x86_64 from nightly, but it still has the same issue.

Client:
Ubuntu 20.04 + remmina=1.4.11+ppa202102060756.r0a51356f.deec7640c~ubuntu20.04.1

Server:
Ubuntu 20.04 + x0vncserver above 1.7

let me know if you need any extra info, I can easily reproduce this issue

**Comment by CendioOssman** [comment]
Does this happen with our client as well?

**Comment by delphir-com** [comment]
yes, exactly the same behavior (tigervnc-viewer 1.10.1)

**Comment by delphir-com** [comment]
a bit of an update:

the issue happens when the client's and server's current locale is not the same.

for example if client's current language is set to "EN"glish, but server's "RU"ssian - then no chars appear on the remote.
the same happens if client is RU but server is EN.

if both are RU or both are EN - then the correct characters are printed while typing.

**Comment by CendioOssman** [comment]
I'm afraid then it sounds like things are working as expected. It was some kind of bug (likely ac73038232dd7d6e41006357de2120f580b9f05f and related fixes)  in earlier versions that happened to stumble in to something sane in your specific case.

If you want to ignore the client's keymap then I suggest trying `-RawKeyboard=1` and see if that is more to your liking. Otherwise I'm afraid there isn't much we can do as we can only work with the keys available in the server's keymap.

**Comment by delphir-com** [comment]
then why is it working correctly in x0vncserver 1.7 ?

**Comment by CendioOssman** [comment]
I don't think it worked the way it was supposed there either. It just happened that the buggy behaviour was something that was still useful in your case.

When you had Russian configured on the client and English on the server, I'm assuming you did not get Cyrillic characters in the VNC session?

**Comment by delphir-com** [comment]
yes, I don't get any chars when client/host language is set to a different values. but in your example I would expect to get English chars as like you say "English on the server" so I would expect to get chars in server's locale.

**Comment by CendioOssman** [comment]
That is not how VNC normally works unfortunately. It is designed to follow the client's keymap. If it can't then it shouldn't generate any key events as it cannot properly determine what is right. Hence the behaviour in older TigerVNC was buggy.

Again, please try the `RawKeyboard` setting. It sounds like that is what you are after.

**Comment by aerinmiller** [comment]
RawKeyboard does not work. After an update I only did because unicode wasn't copy/pasting correctly, now I'm not getting ANY characters when I switch my physical keyboard to Arabic and start typing. Before I at least could type in Arabic.
