### ISSUE TITLE
Viewer does not follow DE's DPI settings

### ISSUE THREAD

**Issue by terrancewong** [TigerVNC/tigervnc#1225]
`vncviewer-tigervnc` does not follow DE's DPI, resulting unusable extremely tiny UI/fontDPI.

- Linux 
- XFCE
![Screenshot_2021-03-24_14-00-42 DPI](https://user-images.githubusercontent.com/44456699/112263408-35ceb400-8caa-11eb-953c-b6dbf9190659.png)

**Comment by CendioOssman** [comment]
Please see #369 where this is tracked.
