### ISSUE TITLE
Some keys not working

### ISSUE THREAD

**Issue by tomasmueller** [TigerVNC/tigervnc#1227]
TigerVNC is running on a ubuntu 20.04 machine, i connect to the server using remmina from ubuntu 20.04 and using an app called avncviewer from android devices. I have the same problem with all clients. Some of the keys are not working (§$%&"?*). QWERTZ is enabled on all devices. I could unterstand when there are problem between android and linux but whats the problem when connecting from ubuntu using QWERTZ layout to ubuntu also using QWERTZ layout? I have started tigervncserver wih logging

`-Log *:stderr:100 > tigervnc-viewer.log`

but the file is empty.

**Comment by CendioOssman** [comment]
Could you fill you the issue template so we get a better picture of your setup?

**Comment by tomasmueller** [comment]
**Describe the bug**
The server don't recognize some keys => §$%&"?*

**To Reproduce**
Steps to reproduce the behavior:
This happens every time Tigervnc is started.

**Expected behavior**
All keys from the client should be recognized by the server.

**Client (please complete the following information):**
 - OS: Ubuntu 20.04, Android 9
 - VNC client: Remmina (Ubuntu), VNCViewer (Android)
 - VNC client version: Remmina 1.4.2
 - Client downloaded from: Ubuntu-PPA

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - VNC server: TigerVNC
 - VNC server version: 1.11
 - Server was started using: x0vncserver -passwordfile /home/$USER/.vnc/passwd -display :0

**Comment by CendioOssman** [comment]
Exactly what happens? No key presses at all? Or the wrong symbols?

And could you test with our client to see if the problem is just with some clients?

Finally, what keyboard layouts do you have configured on the client and in the VNC session? You can run `setxkbmap -query` to check.

**Comment by tomasmueller** [comment]
> Exactly what happens? No key presses at all? Or the wrong symbols?

The most keys are working well but some dont work. There is no reaction when i press e.g. "CTRG+7" for the Slash / nothing happens. Nothing works wrong. The most keys are working and some don't.

> And could you test with our client to see if the problem is just with some clients?

Problem occurs with all clients i could test, linux and android client.

> Finally, what keyboard layouts do you have configured on the client and in the VNC session? You can run setxkbmap -query to check.

This is the output of the command for the ubuntu client

`rules: evdev
model: pc105
layout: de`

This is the output on the ubuntu server where tigervnc server is running

`rules:      evdev
model:      pc105
layout:     de
options:    keypad:pointerkeys`

**Comment by CendioOssman** [comment]
> Problem occurs with all clients i could test, linux and android client.

Just to clarify, was one of those clients our? Which version?

Could you add the debug log arguments again? You should get the log output on the console where you start `x0vncserver`. What does it say when you press those keys that do not work?

**Comment by tomasmueller** [comment]
I don't use the tigervnc viewer but tested it and the same problems occurs.

I started the server with this command

`x0vncserver -passwordfile /home/thomas/.vnc/passwd -display :0 -Log *:stderr:100 > /home/thomas/tigervnc-log`

but the file ist empty.

**Comment by CendioOssman** [comment]
Logging goes to stderr and that unfortunately only redirects stdout. You need to specify `2>` instead.

But you should be getting the log lines in the terminal where you started that command.

**Comment by tomasmueller** [comment]
OK, here is the log file. https://pastebin.com/gnbLuPaZ

**Comment by CendioOssman** [comment]
Hmm... Is this with the Android client? The sent events are rather weird and don't seem to match a German layout.

Could you generate a log when using our client?

**Comment by tomasmueller** [comment]
No, this was the remmina client from ubuntu. I've tested our client from the same machine with the same errors.

https://pastebin.com/ndpNsszc

**Comment by CendioOssman** [comment]
It looks like the "-Log" argument was lost in that run. I cannot see any lines detailing what events the server got from the client?

**Comment by tomasmueller** [comment]
Yes, thats true. Here is the correct log again. Using the tiger vnc client from ubuntu 20.04.

https://pastebin.com/REf2iqdH

**Comment by CendioOssman** [comment]
Thank you. The client sends events that are consistent with a German layout. However the server is not behaving in that way. It looks more like US International or similar.

When you ran `setxkbmap` for the server to check the layout, how did you go about doing that? Did you do so via VNC?

**Comment by tomasmueller** [comment]
I did this directly on the server, but i tried it again from the ubuntu client and there is no difference.

**Comment by tomasmueller** [comment]
No ideas? Is there a way to set up qwertz keyboard layout for the vnc server?

**Comment by CendioOssman** [comment]
Not sure why things are going wrong. It seems something is off with the layout on the server, but I don't really know what.

I assume everything works just fine if you use the keyboard locally on the server?

Could you run `xkbcomp $DISPLAY layout.xkb` in the VNC session and attach the file `layout.xkb` here?

**Comment by tomasmueller** [comment]
You mean running this command on the computer with the vnc server?

[layout.zip](https://github.com/TigerVNC/tigervnc/files/6409467/layout.zip)

**Comment by CendioOssman** [comment]
Yes, precisely. It needs to be inside the session though and not via some other method.

The file you attached does not match the last log file you sent. So something is amiss.

The line I'm most interested in is when you are pressing `?`. Do you actually get that character, or do you get something else?

**Comment by tomasmueller** [comment]
OK, again. I logged in from the computer with vnc client to computer with vnc server. Here i opened a terminal and run the command. Here is the file again. I hope this is what you mean.

? is one of the working characters. What not works is / or =.

Maybe as a workaround i can use -remap. How can i find out the "code" for the keys? This is an example from arch wiki
`
"0x3c->0x2c"`

here when i press key '0x3c' on the client its mapped to key '0x2c' on the server.

[layout.zip](https://github.com/TigerVNC/tigervnc/files/6426606/layout.zip)

**Comment by CendioOssman** [comment]
> OK, again. I logged in from the computer with vnc client to computer with vnc server. Here i opened a terminal and run the command. Here is the file again. I hope this is what you mean.

Thank you. This file shows a US layout, which explains the behaviour you are seeing. If you type `setxkbmap de` in a terminal via VNC, does that fix things?

> ? is one of the working characters. What not works is / or =.

Now I'm confused. You stated in your initial comments that `?` was one of the broken characters?

> Maybe as a workaround i can use -remap.

In a hacky way, maybe. But you cannot use it to make things behave like a German layout even though the server has a US layout configured.

> How can i find out the "code" for the keys?

They are X11 keysyms, so you'll need to google that. Most of ASCII uses the same values though, so you can generally start with that.

**Comment by tomasmueller** [comment]
>  If you type setxkbmap de in a terminal via VNC, does that fix things?

Yes, this works but i have to run the command after every reboot. And i don't understand why? I never had problems with the keyboard layout when i "normally" use the machine. Every application uses the german layout. All settings in xfce that i could find was set up to the german layout. What is the difference to the normal layout settings?

> Now I'm confused. You stated in your initial comments that ? was one of the broken characters?

i cant remember what was wrong with me at this time :-)

as i can see at the moments all works. i will test it this weekend.

**Comment by CendioOssman** [comment]
> 
> Yes, this works but i have to run the command after every reboot. And i don't understand why? I never had problems with the keyboard layout when i "normally" use the machine. Every application uses the german layout. All settings in xfce that i could find was set up to the german layout. What is the difference to the normal layout settings?

No idea. There must be some subtle difference somewhere. :/

**Comment by CendioOssman** [comment]
I got a Ubuntu 20.04 machine with Xfce up and running here, and I'm afraid I cannot reproduce the issue you are seeing. I've configured German keyboard layout both locally and remotely, and all keys are working just fine.

You wrote that you are using 1.11.0 though. It's only 1.10.1 that's included in Ubuntu 20.04. So where did you get that build?

**Comment by samhed** [comment]
No response.

**Comment by KebabLord** [comment]
I don't wish to bump an old issue but since this is the first google result, let me share my solution.
Both my target server (running tigervncserver), and client (running xtigervncviewer) had Turkish keyboard layout but some letters such as "Ş" and "i" were not working eventhough "Ü" "Ö" "Ç" was working.

I realized that this option on the server was disabled, and enabling it fixed the issue for me:
![Image](https://github.com/user-attachments/assets/0e90cc6f-063f-4d15-b4d8-517541d0e2d6)
