### ISSUE TITLE
Cannot set resolution at startup

### ISSUE THREAD

**Issue by phil123456** [TigerVNC/tigervnc#1230]
**Describe the bug**

I have a physical screen with limited resolution
I want a virtual screen with a bigger resolution

I tried using /etc/vnc/config.custom with 

`-geometry 1920x1080`

I also tried to do this in ~/.vnc/config

none of this seemed to work

I tried connecting to ip and to ip:1

same issue, nothing works

I really struggle to find documentation about how to do this

**Expected behavior**

I expect to be able to connect to my raspberry pi virtual desktop with a big resolution while the physical screen is only a 7'' touch screen

**Client (please complete the following information):**
 - OS: Win 10
 - VNC client: RealVNC
 - VNC client version: 6.20.529

**Server (please complete the following information):**
 - OS: RPI4 latest version, just updated/upgraded
 - VNC server: ??? vncserver
 - VNC server version: vncserver -v does not work

**Comment by CendioOssman** [comment]
If you are running Raspbian then they are likely using Debian's TigerVNC package, which unfortuntely we cannot properly support as they have their own vncserver script instead of ours. But we can have a quick look and see if there is something obvious.

If you run `ps ax | grep Xtigervnc`, what do you get? I want to confirm that your geometry setting has been properly applied.

**Comment by phil123456** [comment]
nothing apparently:

`pi@raspberrypi:~ $ ps ax | grep Xtigervnc
 1244 pts/0    S+     0:00 grep --color=auto Xtigervnc
`

**Comment by phil123456** [comment]
I been searching around but I  cannot find any repository for debian tigervnc for support

**Comment by bphinz** [comment]
I do not believe that raspberry pi OS offers TigerVNC, only RealVNC.
However, if you find out how to do this I would be interested in knowing
how.  I have an application that requires their cloudconnect feature but
with a different desktop size than the touchscreen and wasn't able to get
that to work either.

**Comment by phil123456** [comment]
such a basic usecase...I dont understand....

**Comment by CendioOssman** [comment]
If it's not our software then it's unfortunately not something we can help you with. So let's check what it is you have. Please run `which vncserver` and `dpkg --search vncserver`.

**Comment by phil123456** [comment]
pi@raspberrypi:~ $ which vncserver
/usr/bin/vncserver

pi@raspberrypi:~ $ dpkg --search vncserver
realvnc-vnc-server: /usr/share/icons/hicolor/48x48/apps/vncserverConnected.png
realvnc-vnc-server: /usr/share/icons/hicolor/48x48/apps/vncserverConnectedError.png
tigervnc-standalone-server: /usr/bin/tigervncserver
realvnc-vnc-server: /usr/share/man/man1/vncserver-x11-serviced.1.gz
realvnc-vnc-server: /usr/share/man/man1/vncserver-x11.1.gz
realvnc-vnc-server: /usr/share/icons/hicolor/48x48/apps/vncserver48x48.png
realvnc-vnc-server: /usr/share/icons/hicolor/48x48/apps/vncserverConnectedWarning.png
realvnc-vnc-server: /usr/share/man/man1/vncserver-virtual.1.gz
realvnc-vnc-server: /usr/bin/vncserver-virtual
realvnc-vnc-server: /usr/share/applications/realvnc-vncserverui-user.desktop
realvnc-vnc-server: /usr/share/applications/realvnc-vncserverui-service.desktop
realvnc-vnc-server: /usr/share/icons/hicolor/48x48/apps/vncserverWarning.png
realvnc-vnc-server: /usr/share/icons/hicolor/48x48/apps/vncserver.png
realvnc-vnc-server: /usr/share/man/man1/vncserver-virtuald.1.gz
realvnc-vnc-server: /usr/bin/vncserver-x11-core
realvnc-vnc-server: /usr/share/icons/hicolor/48x48/apps/vncserverError.png
realvnc-vnc-server: /usr/share/applications/realvnc-vncserverui-virtual.desktop
tigervnc-standalone-server: /usr/share/man/man1/tigervncserver.1.gz
realvnc-vnc-server: /usr/bin/vncserver-x11-serviced
realvnc-vnc-server: /usr/bin/vncserverui
realvnc-vnc-server: /usr/bin/vncserver-x11
realvnc-vnc-server: /usr/bin/vncserver-virtuald

**Comment by phil123456** [comment]
how can I find who's in charge of that package ?
I cannot find any info on google about **realvnc-vnc-server**

**Comment by bphinz** [comment]
Can you run "dpkg --search /usr/bin/vncserver" please?

**Comment by CendioOssman** [comment]
That file isn't directly owned on Debian systems, so unfortunately that doesn't fork.

@phil123456, please run `update-alternatives --list vncserver` and let us know what it says.

**Comment by CendioOssman** [comment]
No response. Closing.
