### ISSUE TITLE
Disable clipboard sharing between client and server

### ISSUE THREAD

**Issue by shahidn86** [TigerVNC/tigervnc#1231]
**Describe the bug**
In previous versions of TigerVNC server started from systemd service files, I added "-AcceptCutText=0", "-SendCutText=0" and "-noclipboard" switches to the vncserver start commands to disable clipboard sharing between client and server. With latest TigerVNC server which is config file based, the clipboard sharing still works (when it should have been disabled) after adding the switches to config file.

**To Reproduce**
1. Add "AcceptCutText=0", "SendCutText=0" and "noclipboard" to config file (see [config](https://github.com/TigerVNC/tigervnc/files/6251504/config.txt) file attachment)
2. Run "sudo systemctl start vncserver@:1"
3. Connect with Remmina VNC client and try to copy text from server window to local machine. It allows text to be copied when it should be disabled.

**Expected behavior**
The copying of text between client and server should be disabled. I expected "-AcceptCutText=0", "-SendCutText=0" and "-noclipboard" switches to be used when Xvnc was called but switches got changed to "-acceptcuttext 0" and "-sendcuttext 0" while "-noclipboard" remains as is. This conflicts with the Xvnc help text which says that the way to turn off a parameter is with "-<param>=0" switch.

**Client (please complete the following information):**
 - OS: Ubuntu 20.04
 - VNC client: Remmina
 - VNC client version: 1.4.2
 - Client downloaded from: Ubuntu-PPA

**Server (please complete the following information):**
 - OS: Centos 8
 - VNC server: TigerVNC
 - VNC server version: 1.10.0
 - Server downloaded from: Centos 8 YUM
 - Server was started using: sudo systemctl start vncserver@:1

**Additional context**
I also tried manually calling xinit command with switches changed to match switches used with previous version of TigerVNC server where clipboard sharing was being disabled. Although the Xvnc gets called with correct switches now and I can connect to VNC client, the text copying is still allowed.

**Comment by CendioOssman** [comment]
I'm afraid this is a known issue. Fortunately it is also fixed and will be in the next release. See #1098 for more details.

Until then please try a nightly build.
