### ISSUE TITLE
Mesa 21.0.1 making TigerVNC server lag?

### ISSUE THREAD

**Issue by usul0184** [TigerVNC/tigervnc#1234]
**Describe the bug**

After I upgraded from Mesa 20.3.4 to 21.0.1 on my TigerVNC server, there was a clear performance hit to remote sessions.  Everything became more laggy, and there is noticeable screen tearing.  After downgrading back to Mesa 20.3.4, the problems disappeared.

**Client (please complete the following information):**
 - OS: Windows 10 Enterprise
 - VNC client: VNC Viewer
 - VNC client version: 6.20.529
 - Client downloaded from: RealVNC website

**Server (please complete the following information):**
 - OS: Manjaro 21.0 XFCE
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: Manjaro official repository
 - Server was started using: vncsession through systemd

**Comment by CendioOssman** [comment]
Have you reported this to Mesa or Manjaro? Unfortunately it sounds more like a Mesa bug than a TigerVNC one. :/

**Comment by usul0184** [comment]
You're probably right.  I did report to Manjaro.  I'm not very experienced with Mesa, though; I was hoping a TigerVNC user could corroborate (or contradict) my experience with Mesa 21 and help figure out what exactly in Mesa 21 is breaking things.

**Comment by CendioOssman** [comment]
I'm afraid I don't have any systems with Mesa 21 yet. :/

Let's see if Manjaro or Mesa find what is causing the slowdown. If they find anything pointing to an issue with TigerVNC we can continue from that point. Until then I'll close this issue as it is likely not an issue we can do anything about.

**Comment by usul0184** [comment]
Actually, in case anyone else stumbles on this, it looks like things are back to normal with Mesa 21.0.2, so whatever problem there was must have been fixed.
