### ISSUE TITLE
Distribution download from bintray.com fails

### ISSUE THREAD

**Issue by accetto** [TigerVNC/tigervnc#1235]
**Describe the bug**
I've got an error by rebuilding my containers (e.g [accetto/ubuntu-vnc-xfce-nodejs-g3](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-nodejs-g3)). The reason is that the distribution point is currently not avaliable (see below).

**To Reproduce**

```shell
wget https://dl.bintray.com/tigervnc/stable/tigervnc-1.11.0.x86_64.tar.gz

# output
--2021-04-12 14:25:14--  https://dl.bintray.com/tigervnc/stable/tigervnc-1.11.0.x86_64.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 18.158.131.58, 35.156.125.116
Connecting to dl.bintray.com (dl.bintray.com)|18.158.131.58|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-12 14:25:14 ERROR 403: Forbidden.
```

**Expected behavior**
The distribution file `tigervnc-1.11.0.x86_64.tar.gz` should be downloaded as previously.

**Client (please complete the following information):**
 - OS: Linux Ubuntu 20.04 LTS

**Additional context**
Is that because of the following message on the bintray.com website?

> Attention: All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021. Learn More.

How will be TigerVNC distributed now?

At the moment I cannot rebuild any of my many containers on Docker Hub. A prompt info would be appreciated.

Thanks,
accetto

**Comment by samhed** [comment]
More info on #1236
