### ISSUE TITLE
Guide says /etc/tigervnc/vncserver.users. Release version 1.11.0 uses /usr/etc/tigervnc/vncserver.users

### ISSUE THREAD

**Issue by topatopa** [TigerVNC/tigervnc#1237]
The guide for 1.11.0 says to use /etc/tigervnc/vncserver.users to map displays to users. I tried running it in version 1.11.0 from the [release page](https://bintray.com/tigervnc/stable/tigervnc/1.11.0) and kept getting `vncsession-start[6583]: No user configured for display :1` even though the configuration is correct.

I eventually realized that /usr/libexec/vncsession-start has it written incorrectly in this build. This line

```
USERSFILE="/usr/etc/tigervnc/vncserver.users"
```

should be

```
USERSFILE="/etc/tigervnc/vncserver.users"
```

I think the release build should be updated as soon as possible because it is the goto place to get the latest stable release if the distro hasn't updated it. For example: I use Kubuntu 20.04 and 1.10.1 (latest version in distro) crashes my plasma shell. So, I need to manually download 1.11.0.

Edit: tigervnc-1.11.0.x86_64.tar.gz is the tarball I am downloading from the release page. I am not sure if the other tarballs have similar incorrect USERSFILE.

**Comment by samhed** [comment]
You mean the guide in `unix/vncserver/HOWTO.md`? That one was quite recently added

**Comment by topatopa** [comment]
Yes, I used that guide. Isn't it made for version 1.11.0 or newer? The release build should match the description but currently it doesn't.

**Comment by samhed** [comment]
Yeah @grulja added that 2 months ago. Technically it wasn't included in 1.11.0, but it should apply.

**Comment by CendioOssman** [comment]
The location of files like this depend on build flags, so we either have to dynamically generate the HOWTO, or avoid giving absolute paths in it. Given that it already has a few other references without path I'm leaning towards the latter.

**Comment by CendioOssman** [comment]
Builds has been fixed to use `/etc` now, and HOWTO.md updated in a8357a530546412799801d5041a157def6588610.

Thanks for spotting this.
