### ISSUE TITLE
Pam option not showing for Xvnc when compiling for iOS.

### ISSUE THREAD

**Issue by Gymxo** [TigerVNC/tigervnc#1238]
I have created a fork of this GitHub and then removed all the limitations to make Xvnc compile for iOS. Even though I’ve changed all the options I could to make patches, I still don’t have the option for it. Is there any spots that make the pam option Unix specific?

**Comment by CendioOssman** [comment]
Yes, please check the top level CMakeLists.txt. We don't enable it on Apple systems as they don't use X11 and hence building the server isn't really useful. So I'm curious to know what your use case is?

**Comment by Gymxo** [comment]
And where would this file be located?
I've gone through and tried to remove/change all the "if Unix" to "if Apple"

**Comment by bphinz** [comment]
https://github.com/TigerVNC/tigervnc/blob/master/CMakeLists.txt

See line 267

**Comment by Gymxo** [comment]
https://github.com/Gymxo/tigervnc/blob/master/CMakeLists.txt#L266
I have already recompiled multiple times with that disabled.

**Comment by Gymxo** [comment]
For I've made a patch regarding that here https://github.com/ProcursusTeam/Procursus/blob/32b189929da83bb47e394d74d14a4795eeff2210/build_patch/tigervnc/0001-Update-CMakeLists.txt.patch

**Comment by bphinz** [comment]
I think you will probably have to drill down and look at some of the lower
level CMakeLists.txt files.  IE: line 78 in
https://github.com/TigerVNC/tigervnc/blob/master/common/rfb/CMakeLists.txt
