### ISSUE TITLE
Accented keys not working when using the Java viewer

### ISSUE THREAD

**Issue by binary-manu** [TigerVNC/tigervnc#1239]
**Describe the bug**
Keys with accented letters, like `ò`, `à`, `è` (and other symbols that use the same keys, like `#` which is ALT-GR+`à`) on an Italian keyboard are not sent to the server when using the Java viewer. If verbose logging is enabled, it says `Viewport: Ignoring KeyEvent with unknown Java keycode`. They work correctly when using the native client.

**To Reproduce**
1. Set locale and keymap information to Italian:
```
System Locale: LANG=it_IT.UTF-8
VC Keymap: it
X11 Layout: it
X11 Model: pc105
X11 Options: terminate:ctrl_alt_bksp
```
2. Start a local Xvnc instance running an application that can accept text.
3. Start the Java TigerVNC viewer and connect to the test server.
4. Notice that while most keys work, accented letters are ignored (don't know how to do that with a different keyboard, but these keys are usually located to the left of RETURN). 

**Expected behavior**
I should be able to use accented letters and other symbols on those keys.

**Client (please complete the following information):**
 - OS: Arch Linux x86-64
 - VNC client:
```
TigerVNC Java Viewer v1.11.0 (20200908)
Built on 2020-09-08 at 23:40:58
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
````
 - Client downloaded from: https://bintray.com/tigervnc/stable/tigervnc

**Server (please complete the following information):**
 - OS: Arch Linux x86-64
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: distro package `tigervnc 1.11.0-6`
 - Server was started using: Xvnc -PasswordFile ~/.vnc/passwd -SecurityTypes VncAuth :2

**Additional context**
While trying to semi-randomly fix the issue, I noticed that if calls to `java.awt.event.KeyEvent.getKeyCode` are replaced with `getExtendedKeyCode`, those characters work. Pressing `à` causes the log to say:

```
Viewport: Key pressed: 0x10000e0 => 0x00e0
Viewport: Key released: 0x10000e0 => 0x00e0
```

**Comment by bphinz** [comment]
Although it might be reasonably safe to fall back to getExtendedKeyCode only when getKeyCode fails...

**Comment by binary-manu** [comment]
> Sorry that I have not had a chance to work on this

No need to apologize. I'm trying to be proactive on this issue as TigerVNC Java Viewer is my de facto standard client when it comes to remote sysadmin stuff. And unfortunately on a typical Italian keyboard accented chars are co-located with `[`, `#` and others you can't really avoid when doing server maintenance.

> Although it might be reasonably safe to fall back to getExtendedKeyCode only when getKeyCode fails...

I'll try and modify the patch do as you say.

Have a nice day.

**Comment by binary-manu** [comment]
I've fixed the patch to prioritize the key code over the extended key code. A new helper method will return the first one that is available among them. So for most events this code should be equivalent to the current state.

**Comment by bphinz** [comment]
Great, thank you.  I will try to get this tested but at a glance it looks
good.  I assume that it passes the "works for me test"?

**Comment by bphinz** [comment]
The biggest thing is usually just verifying that it's consistent across all
platforms.

**Comment by binary-manu** [comment]
I performed some informal, manual testing on Linux, MacOS Catalina and Windows 10, comparing the official Java viewer 1.11.0 against the patched version. Here is what I found so far:

* MacOS: everything was already working with the unpatched version, and the patch seems not to have broken anything.
* Linux: accented keys, either in isolation or combined with Shift/AltGr, don't work in the original version. The patch makes them work, so I can type both, let's say `à` and `#` which is `AltGr+à`.
* Windows: accented keys, either in isolation or combined with Shift/AltGr, don't work in the original version. The patch makes accented letters work in isolation and when combined with Shift. However, combinations involving AltGr still don't work, so that typing `#` on Windows is not possible. The logs say `no symbol for virtual key 0x00000001010000e8`.

Overall, it seems that nothing was broken, and while the situation improved on all platforms, Windows still needs some extra work. Personally, I was mainly concerned about Linux since it is where I use the viewer most, but I will try looking into the issue on Windows provided that time and my Java skills permit.

**Comment by binary-manu** [comment]
I have been able to make it work under Windows too.

The culprit seems to be this piece of code in `Viewport.handleSystemEvent`, that fixes modifiers for `AltGr` on WIndows and creates a modified `KeyEvent`:

```java
mask &= ~CTRL_MASK;
mask &= ~ALT_MASK;
mask |= ALT_GRAPH_MASK
```

When the new event is passed to ` KeyMap.vkey_to_keysym`, the call to `ev.getKeyChar()` returns a very high value (65535) which ultimately causes the method to reach the end and return `NoSymbol`. However, if I pass the original event, `getKeyChar` correctly returns the expected character, including the effects of all modifiers. This way I am able to type both `[` (`AltGr + è`) and `{` (`AltGr + Shift + è`).

Following the spirit of the previous changes, I'm rewriting the code so that it executes the current logic first (tries mapping the event to a symbol using the event with the changed mask). Failing that, that original event is used instead.

I'll do another round of cross-platform tests of this code, and upload the patch ASAP.

**Comment by CendioOssman** [comment]
I guess this can be closed now, @bphinz?
