### ISSUE TITLE
Getting black screen on connection

### ISSUE THREAD

**Issue by coldspark29** [TigerVNC/tigervnc#1240]
**Describe the bug**
I set up the vnc server according to https://wiki.archlinux.org/index.php/TigerVNC except that I am using ``session=plasma``

**To Reproduce**
1. Set up VNC server on KDE Plasma according to the Arch Wiki
2. Start server with ``vncserver :1``
3. connect to the server with ``vncviewer localhost:5901``

**Expected behavior**
The plasma screen should appear

**Screenshots**

**Client (please complete the following information):**
 - OS: Arch Linux
 - VNC client: TigerVNC
 - VNC client version: 1.11.0
 - Client downloaded from: Arch Repo

**Server (please complete the following information):**
 - OS: Arch Linux
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: Arch Repo
 - Server was started using: ``vncserver :1``

**Comment by bphinz** [comment]
Is plasma.desktop a valid xsession in /usr/share/xsessions (on CentOS the file is named differently)?  Make sure that the value of session corresponds to the file name of one of those files (without the .desktop suffix)

**Comment by coldspark29** [comment]
I have ``plasma.desktop`` and just tried installing xfce. It is also present as ``xfce.desktop`` but the server doesn't start when I select it. The Plasma server apparently starts fine, but when I connect (on the same machine to test it), I only see a black screen.

Here is the terminal output of the server:

```
Using desktop session plasma

New 'X380-Yoga:1 (jan)' desktop is X380-Yoga:1

Starting desktop session plasma


Xvnc TigerVNC 1.11.0 - built Nov 24 2020 19:41:47
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12009000, The X.Org Foundation


Wed Apr 28 19:07:06 2021
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5901
 vncext:      created VNC server for screen 0
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
kdeinit5: preparing to launch '/usr/lib/kf5/klauncher'
kdeinit5: Launched KLauncher, pid = 9578, result = 0
kf.init.klauncher: Waiting for already running klauncher to exit.
kf.init.klauncher: Waiting for already running klauncher to exit.
kf.init.klauncher: Another instance of klauncher is already running!
kdeinit5: Communication error with launcher. Exiting!
org.kde.plasma.session: process job  "kcminit_startup" finished with exit code  0
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/pam_kwallet_init.desktop" ("/usr/lib/pam_kwallet_init")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/baloo_file.desktop" ("/usr/bin/baloo_file")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/org.kde.plasmashell.desktop" ("/usr/bin/plasmashell")
2021/04/28 19:07:08 socat[9594] E connect(5, AF=1 "/run/user/1000/kwallet5.socket", 32): Connection refused
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/powerdevil.desktop" ("/usr/lib/org_kde_powerdevil")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/polkit-kde-authentication-agent-1.desktop" ("/usr/lib/polkit-kde-authentication-agent-1")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/xembedsniproxy.desktop" ("/usr/bin/xembedsniproxy")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/kaccess.desktop" ("/usr/bin/kaccess")
Xlib XKB extension major= 1  minor= 0
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/org.kde.kdeconnect.daemon.desktop" ("/usr/lib/kdeconnectd")
org.kde.plasma.session: Starting autostart service  "/home/jan/.config/autostart/org.kde.latte-dock.desktop" ("/usr/bin/latte-dock")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/pulseaudio.desktop" ("/usr/bin/start-pulseaudio-x11")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/org.kde.discover.notifier.desktop" ("/usr/lib/DiscoverNotifier")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/gmenudbusmenuproxy.desktop" ("/usr/bin/gmenudbusmenuproxy")
org.kde.plasma.session: Starting autostart service  "/home/jan/.config/autostart/flameshot.desktop" ("/usr/bin/flameshot")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/geoclue-demo-agent.desktop" ("/usr/lib/geoclue-2.0/demos/agent")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/snap-userd-autostart.desktop" ("/bin/snap", "userd", "--autostart")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/msm_kde_notifier.desktop" ("/usr/bin/msm_kde_notifier")
org.kde.plasma.session: Starting autostart service  "/home/jan/.config/autostart/ulauncher.desktop" ("/usr/bin/env", "GDK_BACKEND=x11", "/usr/bin/ulauncher", "--hide-window")
org.kde.plasma.session: Starting autostart service  "/home/jan/.config/autostart/touchegg.desktop" ("/usr/local/bin/touchegg")
org.kde.plasma.session: Starting autostart service  "/etc/xdg/autostart/dtd-wayland.desktop" ("/usr/bin/dtd-wayland")
org.kde.plasma.session: Starting autostart service  "/home/jan/.config/autostart/ownCloud.desktop" ("/usr/bin/owncloud")
kde.dbusmenuproxy: Failed to register DBus service "org.kde.plasma.gmenu_dbusmenu_proxy"
Touchégg v2.0.8.
Starting Touchégg in client mode
terminate called after throwing an instance of 'std::runtime_error'
  what():  Another instance of Touchégg is already running. If you are sure that Touchégg is not already running, delete the lock file with the following command and try again:
$ rm /home/jan/.config/touchegg/.touchegg.lock
org.kde.plasma.session: failed to parse "/home/jan/.config/autostart/dropbox.desktop" for autostart
MSM Notifier is already running, shutting down.
Shutting down MSM Notifier...
"An instance is already running!, use --replace to restart Latte"
```

For xfce:

```
Using desktop session xfce

New 'X380-Yoga:1 (jan)' desktop is X380-Yoga:1

Starting desktop session xfce


Xvnc TigerVNC 1.11.0 - built Nov 24 2020 19:41:47
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12009000, The X.Org Foundation


Wed Apr 28 19:06:53 2021
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5901
 vncext:      created VNC server for screen 0
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/usr/bin/startxfce4: X server already running on display :1
xfce4-session: Another session manager is already running
xinit: connection to X server lost

waiting for X server to shut down  ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
```

**Comment by bphinz** [comment]
> /usr/bin/startxfce4: X server already running on display :1

:1 is already in use

**Comment by coldspark29** [comment]
Yeah but it isn't

**Comment by CendioOssman** [comment]
The existing X server warning is misleading. Xfce always says that. The complaint about an existing session manager is likely the real reason it fails to start.

However, I'm afraid you can't be logged in locally and over VNC at the same time on most distributions. Does your VNC session work if you start it without having logged in locally?

**Comment by coldspark29** [comment]
It worked perfectly fine with x11vnc. So this is probably a bug.

**Comment by CendioOssman** [comment]
x11vnc is an entirely different type of server, so you cannot compare with that. The TigerVNC equivalent to that is x0vncserver.

**Comment by coldspark29** [comment]
> x11vnc is an entirely different type of server, so you cannot compare with that. The TigerVNC equivalent to that is x0vncserver.

Okay then. What is the difference? I just don't see how I would share my desktop without having logged in locally.

**Comment by CendioOssman** [comment]
x11vnc and x0vncserver are for sharing an existing session, so that sounds like it is what you want.

vncserver/Xvnc are for starting an entirely virtual session that can only be reached using VNC. Generally used when you have a shared server you want many users to use remotely.

So please try x0vncserver instead of vncserver and things should hopefully work well for you.

**Comment by coldspark29** [comment]
Alright, that makes sense. I was wondering why the server would restart my desktop session. Thank you for clearing that up!

**Comment by lhzw** [comment]
Replace sddm to xdm fix the black screen problem, refert to this:
https://forums.opensuse.org/showthread.php/532320-vncserver-blank-screen

```
Switch your Display Manager to XDM, KDM (you would have to install that in Yast, first), or LightDM on the machines you are trying to access.

Code:
su -
and give the password, then:
Code:
update-alternatives --config default-displaymanager
choose your Display Manager from the list.

SDDM does not work well with VNC yet.
```

**Comment by ckhung** [comment]
My apology if commenting on a closed issue is unwelcome. I just want to help people who end up here with their searches, and also let the developers know that there are successful instances of running tigervncserver on top of an existing GUI session.

I am on debian 12.5 running KDE plasma, wayland session, inside virt-manager. My initial tigervncserver attempt was not quite successful because apps started in ~/.vnc/xstartup all wrongly go to the initial login display, leaving the vnc display (which runs openbox) empty. Then I found this:
https://askubuntu.com/questions/1495014/client-apps-are-opened-in-wrong-vnc-display
So I add "unset XDG_RUNTIME_DIR" to xstartup, and then the apps correctly go to the openbox session in vnc! Now I can have both my desktop running KDE plasma wayland AND providing an openbox session via tigervncserver to my host machine. I wish I had enough reputation to upvote that Q&A.

**Comment by dessalines** [comment]
God I wish this bug was fixed. Tigervnc seems to break with every arch update.

Black screen, mouse, nothing else. Tried lxqt, xfce, plasma, all the same result.
