### ISSUE TITLE
XDesktop: Could not map key event to X11 key code ios realvnc client x0vncserver

### ISSUE THREAD

**Issue by fred21O4** [TigerVNC/tigervnc#1241]
**Describe the bug**
cannot type special characters such as @ when using ios realvnc client

**To Reproduce**
1. start x0vncserver
2. connect with ios realvnc client
3. type @ 
4. Nothing gets typed

**Expected behavior**
@ gets typed

**Screenshots**
![image](https://user-images.githubusercontent.com/67189813/116653622-b1273200-a9db-11eb-96c1-809c70cec4d2.png)

**Client (please complete the following information):**
 - OS: Ios
 - VNC client: Realvnc
 - VNC client version: 3.9.3
 - Client downloaded from: App store

**Server (please complete the following information):**
 - OS: Artix linux
 - VNC server: Tigervnc x0vncserver
 - VNC server version: 1.11.0
 - Server downloaded from: Pacman
 - Server was started using: x0vncserver -rfbauth ~/.vnc/passwd -log \*:stdout:100

**Additional context**
This problem does not happen when using x11vnc

**Comment by CendioOssman** [comment]
I'm afraid x0vncserver does not support faking extra keypresses, so any keys sent by the client must be directly available in the server's keyboard layout. Mobile clients commonly fail to fulfil this requirement. Please see #528.
