### ISSUE TITLE
Version 1.11 for Ubuntu 18.04 arm64 installs tigervncserver in /lib, not /usr/bin

### ISSUE THREAD

**Issue by petertorelli** [TigerVNC/tigervnc#1243]
**Describe the bug**
After installing the `.deb` pacakge for arm64, `tigervncserver` is in the wrong location:
```
./bin/tigervncconfig
./bin/tigervncpasswd
./sbin/tigervncsession
./lib/aarch64-linux-gnu/tigervncserver
```

**To Reproduce**
1. Download the 1.11 deb file from bintray for Ubuntu 18.04
2. `sudo dpkg -i ...`

**Expected behavior**
I expected `tigervncserver` to be copied to the `/usr/bin` directory with the other programs.

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - VNC server: TigerVNC
 - VNC server version: 1.11
 - Server downloaded from: https://bintray.com/tigervnc/stable/tigervnc/1.11.0#files/ubuntu-18.04LTS%2Farm64

**Comment by bphinz** [comment]
Thanks for the heads up, I will take a look

**Comment by CendioOssman** [comment]
That is actually correct. That script should no longer be run by hand, hence its move to lib/. Instead you should start sessions via the included systemd service unit. We have a HOWTO that will be included in the next release to get you going:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

**Comment by petertorelli** [comment]
Switching from the `vncserver` script to a service is a departure from VNC historic expectations, that's definitely going to need some on-ramping for folks. Thanks for the heads-up and the doc.
