### ISSUE TITLE
"something has gone wrong" with  gcp startup script

### ISSUE THREAD

**Issue by OliverwengFiltered** [TigerVNC/tigervnc#1245]
Hi there,

I'm using GCP compute engine startup script to start the vncserver, however, I hit something has gone wrong page when accessing it via "novnc" (a vnc viewer client)

and then I'm testing the same startup script when running it manually in terminal in GCP, it works perfectly fine.

I'm wondering anyone has the same issue ?

<img width="703" alt="Screen Shot 2021-05-03 at 6 59 57 PM" src="https://user-images.githubusercontent.com/28814939/116943765-390e7580-ac42-11eb-9092-925781d8d802.png">

**Comment by OliverwengFiltered** [comment]
script that's in startup script in GCP
```sh
sudo apt install tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer -y
sudo apt install ubuntu-gnome-desktop -y
sudo snap install novnc

sudo systemctl enable --now gdm
export HOME=/home/coder
sudo vncserver -SecurityTypes None
sudo novnc --listen 8080 --vnc localhost:5901

```

**Comment by CendioOssman** [comment]
That is the screen GNOME shows when it fails to start up. Unfortunately we are unable to help you with this as the startup script is something specific to Ubuntu/Debian and doesn't come from us. So I'm afraid I'll have to ask you to file an issue with them, and hopefully they can help you out.
