### ISSUE TITLE
Add session line to vncserver-config-defaults with brief explanation

### ISSUE THREAD

**Issue by taranu** [TigerVNC/tigervnc#1248]
**Is your feature request related to a problem? Please describe.**
I started tigervnc server as a service in Fedora 34 (GNOME 40), and found that almost everything worked as expected, except that the top bar was light despite gnome being set to a dark theme. The problem is that I had set `desktop=gnome` in [/etc/tigervnc/vncserver-config-defaults](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/vncserver-config-defaults#L12) rather than `session=gnome` as suggested by the [HOWTO](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md). Evidently at least [one other person](https://bugzilla.redhat.com/show_bug.cgi?id=1879075) did the same and filed a spurious bug report as a result.

**Describe the solution you'd like**
Adding a commented line with `#session=gnome` to `vncserver-config-defaults` would help, along with a brief explanation of the distinction between `session` and `desktop`. Perhaps add a suggestion to check the `vncsession` man page [here](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/vncserver-config-defaults#L6) and/or a reminder to read the HOWTO more closely (I think only trying to run `vncserver` does that?).

After reading the docs some more, I'm also unsure what the default session is - the only other ones I have available in `/usr/share/xsessions/` are `gnome-xorg` and `gnome-classic`.

**Comment by CendioOssman** [comment]
Sounds like reasonable ideas. Should be fixed on `master` now. Thanks!
