### ISSUE TITLE
VNC Issues on SLES 15 SP2 SAP OS

### ISSUE THREAD

**Issue by sr1k5f4** [TigerVNC/tigervnc#1254]
Hi Team,

I have a fresh EC2 instance built from the AWS marketplace image running SLES 15 SP2 for SAP OS. 

we see vnc has no context menu, cannot open additional xterm, cannot resize the default window etc. 

Is there any known issues with this or can you please advise if we are missing any configurations. 

Steps to reproduce the issue

ec2 instance using SLES 15 SP2 AMI (AWS Market Place)
#vncserver
#vncpasswd

Logs from the session

ip-10-99-13-36:~ # cat /root/.vnc/ip-10-99-13-36:1.log

Xvnc TigerVNC 1.9.0 - built ??? ?? ???? ??:??:??
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org  for information on TigerVNC.
Underlying X server release 12003000, The X.Org Foundation

Wed May 19 08:03:17 2021
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Internal error:   Could not resolve keysym XF86WWAN
> Internal error:   Could not resolve keysym XF86RFKill
Errors from xkbcomp are not fatal to the X server
Failed to connect to bus: No such file or directory
xterm: cannot load font "-misc-fixed-medium-r-semicondensed-*-13-120-75-75-c-60-iso10646-1"
xterm: cannot load font "-Misc-Fixed-bold-R-*-*-13-120-75-75-C-60-ISO8859-1"
xterm: cannot load font "-misc-fixed-medium-r-normal-*-13-120-75-75-c-120-iso10646-1"
xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"

also attached a snapshot of what I see on a VNC Session.

NOTE: I HAVE ALREADY TRIED DOING THE BELOW AND STILL SEE THE SAME ISSUES
![aws ec2](https://user-images.githubusercontent.com/80193919/118932851-21cfc780-b966-11eb-9555-eb286c3f2940.PNG)

zypper install xorg-x11-fonts

**Comment by sr1k5f4** [comment]
zypper install xorg-x11-fonts was done, but still same behavior

**Comment by CendioOssman** [comment]
It looks like you have a very minimal session startup configured in `~/.vnc/xstartup`. Unfortunately this is tricky to get right, so in TigerVNC 1.11.0 we've started with a more robust system. We unfortunately cannot support the older versions, so you'll either need to get an upgrade in place or talk to SUSE and see if they can help you out with the older version they include.

**Comment by sr1k5f4** [comment]
Hi,

I still have an on premise VM with the same version and I see its working ok. I am seeing this issue on cloud instances only.

**Comment by sr1k5f4** [comment]
@CendioOssman  Do you think this more cloud specific issue

**Comment by CendioOssman** [comment]
I would doubt it. It might simply be that the cloud instance has very few things installed so there is nothing interesting to start. See if you can compare what's installed, and your `.vnc/xstartup` files on the VM and cloud instance.
