### ISSUE TITLE
CentOS 8.3: vncsession: vncserver exited with status=98

### ISSUE THREAD

**Issue by kelbstf** [TigerVNC/tigervnc#1255]
Hello,

**Error description**
tigervnc-server.x86_64 (1.10.1-9.el8_3) on "CentOS Linux release 8.3.2011" worked fro month without any issue.
After update on 16.5.2021, it never could be launched again with identical workflow.

**To Reproduce**
1. Install & configure tigervnc server according to the readme of tigervnc, except for "restorecon" on .vnc directory
2. systemctl start vncserver@\:1.service
3. systemctl status vncserver@\:1.service -l; journalctl -xe
4. See log listing below

**Expected behavior**
Started service keeps running.

**Server**
 - OS: CentOS Linux release 8.3.2011
 - VNC server: tigervnc-server.x86_64
 - VNC server version: 1.10.1-9.el8_3
 - Server downloaded from: centos repo
 - Server was started using: "systemctl start vncserver@\:1.service"

**Server status**
<pre>
systemctl status vncserver@\:1.service -l
● vncserver@:1.service - Remote desktop service (VNC)
   Loaded: loaded (/etc/systemd/system/vncserver@.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

Mai 20 20:11:31 linuxhost systemd[1]: vncserver@:1.service: Succeeded.
Mai 20 21:34:21 linuxhost systemd[1]: Starting Remote desktop service (VNC)...
Mai 20 21:34:21 linuxhost systemd[1]: Started Remote desktop service (VNC).
Mai 20 21:34:21 linuxhost systemd[1]: vncserver@:1.service: Succeeded.
Mai 20 21:46:33 linuxhost systemd[1]: Starting Remote desktop service (VNC)...
Mai 20 21:46:33 linuxhost systemd[1]: Started Remote desktop service (VNC).
Mai 20 21:46:33 linuxhost systemd[1]: vncserver@:1.service: Succeeded.
Mai 20 21:58:06 linuxhost systemd[1]: Starting Remote desktop service (VNC)...
Mai 20 21:58:06 linuxhost systemd[1]: Started Remote desktop service (VNC).
Mai 20 21:58:06 linuxhost systemd[1]: vncserver@:1.service: Succeeded.
</pre>

**Logifile sample**
<pre>
journalctl:
Mai 20 21:58:06 linuxhost systemd-logind[1593]: New session 54 of user root.
-- Subject: A new session 54 has been created for user root
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A new session with the ID 54 has been created for the user root.
-- 
-- The leading process of the session is 40620.
Mai 20 21:58:06 linuxhost systemd[1]: Started Session 54 of user root.
-- Subject: Unit session-54.scope has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit session-54.scope has finished starting up.
-- 
-- The start-up result is done.
Mai 20 21:58:06 linuxhost vncsession[40620]: pam_unix(tigervnc:session): session opened for user root by (uid=0)
Mai 20 21:58:06 linuxhost systemd[1]: Started Remote desktop service (VNC).
-- Subject: Unit vncserver@:1.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit vncserver@:1.service has finished starting up.
-- 
-- The start-up result is done.
Mai 20 21:58:06 linuxhost vncsession[40620]: vncsession: vncserver exited with status=98
Mai 20 21:58:06 linuxhost vncsession[40620]: pam_unix(tigervnc:session): session closed for user root
Mai 20 21:58:06 linuxhost systemd[1]: vncserver@:1.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
</pre>

<pre>
cat /root/.vnc/linuxhost\:1.log 
A VNC server is already running as :1
</pre>

**SELinux unlikely**
SELinux seems not to be involved, as i disabled it temporarily, which did not help. Also i never found any SELinux error message in this context.

**Possible reason**
I have a complete list of all packages updated on 16th.
Non of them directly related to Gnome or tigervnc.
But possibly related:

<pre>
selinux-policy            noarch               3.14.3-54.el8_3.4                                       baseos                  622 k
selinux-policy-targeted   noarch               3.14.3-54.el8_3.4                                       baseos                   15 M
sudo                      x86_64               1.8.29-6.el8_3.1                                        baseos                  924 k
systemd                   x86_64               239-41.el8_3.2                                          baseos                  3.5 M
systemd-libs              x86_64               239-41.el8_3.2                                          baseos                  1.1 M
systemd-pam               x86_64               239-41.el8_3.2                                          baseos                  456 k
systemd-udev              x86_64               239-41.el8_3.2                                          baseos                  1.3 M
</pre>

I started with attempting to debug the original tigervnc installation that perfectly worked prior to the updates. After this did not help, i completely reinstalled it. But always the same problem.

The ".vnc/linuxhost\:1.log" entry preplexes me, as it is always just that single line. But i can't ever list any running process. Also i can't find any residual temp files or lock files either.

Does anyone have similar experieces or ideas?

Best

**Comment by CendioOssman** [comment]
It checks a couple of things before printing that error message, so I'm going to need to ask you to check all of them:

 * Is there a `/tmp/.X1-lock` file? If there is, it should contain a pid. Is that pid still alive? Try ``ps -q `cat /tmp/.X1-lock` ``
 * The ports 5901 and 6001 both need to be unused. Try `ss -a '( sport == :5901 ) or ( sport == :6001 )'`
 * Is there a `/tmp/.X11-unix/X1` file?

**Comment by kelbstf** [comment]
Hello CendioOssman,

thank you very much for helping!
Unfortunately: none of them.
i also checked /var/run for stale pid files, but actually never can find one. 
If the vnc-log file is removed prior to a fresh launch, it still gets recreated, and then containing just that single line... 
The launch fails pretty fast (so fast i even can't list processes), therefore i am wondering whether it simply can't create one of those required files in the first place. 
The typical culprit that comes to mind is SELinux, but this time no issues there. 
Although i still find the "SELinuxContext=system_u:system_r:vnc_session_t:s0" a bit puzzling, since other files in that directory have different labels...

Because you considered the port: i use port redirection to pipe the access through SSH, but that never was a problem so far...

Best
kelbstf

**Comment by kelbstf** [comment]
Hello,
just wanted to tell you that ivnc seems to work if i *don't* launch gdm prior to vnc.
Something seems to be odd with systemd after my update.
I'll come back if that is sorted out.
Best

**Comment by kelbstf** [comment]
Hello CendioOssman, 
i could not fully determine yet, what exactly happened.
But the last update of systemD seems to have modified numerous service unit files, resulting in a filesize of "0".
Which again caused the OS to mask those services. 
Among others the default target "multi-user" unit which prevented my server from booting up after the update. 
And also gdm.service. After having restored the unit files and unmasked the services, gdm could be launched and afterwards also tigervnc.
GOOGLE told me that Fedora 31 users apparently experienced empty service unit files as well...

Summary: not a problem of TigerVNC, but issues with systemD&GDM.

Thank you again for offering help so fast!

Best regards,
 kelbstf
