### ISSUE TITLE
[Documentation] Update links that refer to nightly

### ISSUE THREAD

**Issue by Technetium1** [TigerVNC/tigervnc#1256]
On many pages there are links to `http://tigervnc.bphinz.com/nightly` which does not resolve, such as [here in the wiki](https://github.com/TigerVNC/tigervnc/wiki/Setup-TigerVNC-server-(Windows)#install-and-setup-tigervnc-server). According to the release notes of TigerVNC 1.11.0 Beta, it seems that it should point to 
`https://sourceforge.net/projects/tigervnc/files/beta`

**Comment by CendioOssman** [comment]
Betas are different from nightly builds, so the link is actually correct. It also resolves just fine here. So I'm afraid there must be some connection issue at your end. Unfortunately that is not something we can help you out with so you'll have to get in touch with your ISP for that.
