### ISSUE TITLE
x11vnc zoom crash - Rect Too Big / Unknown Encoding

### ISSUE THREAD

**Issue by Rojikku** [TigerVNC/tigervnc#1265]
**Describe the bug**
DecodeManager: Unknown encoding 209717600
OR
 CMsgReader:  Rect too big: 256x580 at 0,65535 exceeds 3200x2400

**To Reproduce**
1. Xephyr -once -screen 800x600 :1
2. x11vnc -localhost -display :1 -scale 4:nb -repeat -forever
3. vncviewer localhost:0
4. DISPLAY=:1 discord
5. Move mouse in window (VNC or the Xephyr)
6. See error

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: Archlinux, up to date
 - VNC client: TigerVNC
 - VNC client version: 1.11.0-6
 - Client downloaded from: Repos

**Server (please complete the following information):**
 - OS: Archlinux, up to date
 - VNC server: x11vnc
 - VNC server version: 1:0.9.16-4
 - Server downloaded from: Repo
 - Server was started using: x11vnc -localhost -display :1 -scale 4:nb -repeat -forever

**Additional context**
I ran into this issue while trying to play a game with wine when the game was full screen. I did NOT run into this issue using winecfg. At first I thought it was related to the game, but having reproduced it with discord, I will go with that. Discord is installed through repos on Arch as well.
I assume the issue is related to some sort of exchange between x11vnc and tigervnc, and will replicate on other systems.
Moving the mouse seems somewhat vital to the crash.

Removing the -scale would likely make the crash not happen, but the whole point is to play an 800x600 game at 4x zoom and be able to see what I'm doing on a modern monitor, without messing up my resolution and other workspaces.
I am equally happy to run a tigervnc server, but I didn't see any evidence of it having support to do this.

**Comment by CendioOssman** [comment]
I'm afraid those error messages means we are getting some bogus data from the server. The fact that it only appears with some server settings also indicates that this is an issue in the server.

So I'm afraid I'll have to ask you to report this to @LibVNC and see if they can figure out what causes the server to mess up the data.

(and it is correct that TigerVNC doesn't have any scaling options at this time)
