### ISSUE TITLE
The -localhost flag does not restrict VNC server access to connections originating from the local machine when using the -inetd flag

### ISSUE THREAD

**Issue by CollegiateComputer** [TigerVNC/tigervnc#1268]
**Describe the bug**
I have configured a systemd.socket to emulate the behavior of inetd by configuring the socket with `ListenStream=5900` and `Accept=yes` and created a systemd.service unit file configured with `ExecStart=-/usr/bin/Xvnc -inetd -query localhost -geometry 1920x1080 -once -SecurityTypes=None -localhost` to automatically spawn a VNC server for each connection to the socket. This is essentially the configuration described on https://wiki.archlinux.org/title/TigerVNC#Running_Xvnc_with_XDMCP_for_on_demand_sessions. This configuration works properly and a new VNC server is spawned for each connection to the socket. The issue I've encountered is that even though the `-locahost` flag is set on execution of the VNC server, connections to the server are not restricted to those originating from localhost. Connections are accepted from any interface.

**To Reproduce**
1. Create the systemd.socket unit "xvnc.socket"
```
# cat << EOF > /etc/systemd/system/xvnc.socket
[Unit]
Description=XVNC Server

[Socket]
ListenStream=5900
Accept=yes

[Install]
WantedBy=sockets.target
EOF
```
2. Create the systemd.service unit "xvnc@.service" with `-localhost` flag set on VNC server execution
```
# cat << EOF > /etc/systemd/system/xvnc@.service
[Unit]
Description=XVNC Per-Connection Daemon

[Service]
ExecStart=-/usr/bin/Xvnc -inetd -query localhost -geometry 1920x1080 -once -SecurityTypes=None -localhost
User=nobody
StandardInput=socket
StandardError=syslog
EOF
```
3. Enable XDMCP Server for display manager (in my case - LightDM - this is done by modifying `/etc/lightdm/lightdm.conf` and setting `enabled=true` under the `[XDMCPServer]` section of the config file). The Arch wiki has good documentation on enabling XDMCP Server on other display managers https://wiki.archlinux.org/title/XDMCP.
4. Reload systemd manager configuration
`# systemctl daemon-reload`
5. Start and enable xvnc.socket
`# systemctl enable --now xvnc.socket`
6. Connect to port 5900 on any interface (besides localhost) from another machine on the same network.

**Expected behavior**
TigerVNC server sees that the connection is not originating from localhost and does not allow the connection to proceed.

**Client (please complete the following information):**
 - OS: Fedora 34
 - VNC client: TigerVNC
 - VNC client version: v1.11.0
 - Client downloaded from: my Linux distribution

**Server (please complete the following information):**
 - OS: Fedora 34 (also tested on Debian Testing)
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: my Linux distribution
 - Server was started using: ExecStart from systemd.service unit file with `-/usr/bin/Xvnc -inetd -query localhost -geometry 1920x1080 -once -SecurityTypes=None -localhost`

**Additional context**
Tested this VNC server configuration on both Debian Testing and Fedora 34 and the issue occurs in both distributions.

**Comment by CendioOssman** [comment]
I'm afraid in inetd mode the connections are handled by inetd (or systemd in this case), and not by us. As such most of the settings related to connections have no effect. So please have a look at systemd's documentation to see how to restrict the socket to just localhost.
