### ISSUE TITLE
x0vncserver session should include hostname

### ISSUE THREAD

**Issue by ktbos1** [TigerVNC/tigervnc#1270]
When connecting to an x0vncserver session, the name of the session the client sees is always "x0vncserver".  That can be really confusing when I have multiple clients connected to remote computers that all look the same.  

I found in the x0vncserver.cxx file on lines 250 and 259 (from the last commit on Jan 22, 2021) that there is a hardcoded string that appears to be for the name.  Could that simply have a "@" and hostname added to it?  So it would show as "x0vncserver @ foo"?  

I looked into trying this locally as a test but I don't have the skills to even do the build on my own computer.

**Comment by CendioOssman** [comment]
Sounds like we could do with a more useful default. Changed in 775d432ec72055b3854d22a5fed7c43997e344da. Thanks.
