### ISSUE TITLE
AcceptSetDesktopSize can't be disabled in config

### ISSUE THREAD

**Issue by cloiti** [TigerVNC/tigervnc#1274]
**Describe the bug**
The AcceptSetDesktopSize option cannot be disabled in my ~/.vnc/config file. I get the following error:
`Unrecognized option: 0`

This is what vncserver is trying to invoke Xvnc with:

```
/usr/local/bin/Xvnc :89 -acceptsetdesktopsize 0 -alwaysshared  -geometry 1920
x1080 -passwordfile .vnc/passwd -securitytypes X509Vnc -x509cert .vnc/host.pem -x509key .vnc/host-key.pem -auth '.Xauthority' -desktop ':89' -pn  -rfbauth .vnc/passwd -rfbport 5989 -rfbwait 30000
```

**To Reproduce**
Modifying the AcceptSetDesktopSize option nowhere else but the local user's config file, place the following line in it:
AcceptSetDesktopSize=0

I have also used _no_ and _false_ with similar results.

**Expected behavior**
I expected to run the server disallowing the desktop to be resized using only the local user's config file.

**Server (please complete the following information):**
 - OS: FreeBSD 13.0-RELEAASE
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: pkg
 - Server was started using: vncserver :89

**Additional context**
As a workaround, I can still disable desktop resizing by passing in the appropriate argument directory to vncserver.

**Comment by CendioOssman** [comment]
Please see #1098. This has been fixed on `master` and will be included in the next release.
