### ISSUE TITLE
Multi -monitor, -viewer and -server solution for VNC. Client viewing area. Pointer behavior.

### ISSUE THREAD

**Issue by Term84** [TigerVNC/tigervnc#1275]
I use VNC client to translate all of large virtual desktop (15360px X 1440px) onto several real viewer's PCs with displays 2560px X 1440px.
Therefore, I need to show only part of virtual desktop on each viewer.
Please help me, I cannot find relevant options on the manual of Tiger VNC Viewer.
There is a similar parameter on the x0 Tiger VNC Server named "-Geometry", but this one affects only on position and size of viewer's window.
**Selecting of viewing area for the VNC Viewer would be a handy feature for building multi-monitor systems.**

_Maybe there is another way to solve this problem._

I was try to start many x0 Tiger VNC Servers and connect each of VNC viewers to its own server.
But the result of this a mouse pointer is dublicated to all the viewers and moves there synchronously on different parts of the large virtual desktop.
**Maybe it is a bug or there is a parameter of X0 Tiger VNC server to normalize pointer's behavior when using multiple servers on same desktop.**

_Tiger VNC 1.9.0
Linux Debian 10_

**Comment by CendioOssman** [comment]
Only showing part of the screen in the client is not something in the plans, so I'm afraid TigerVNC is not the right tool for you there.

x0vncserver should be able to do what you want though. The mouse cursor bug is fixed in TigerVNC 1.10.0, so an upgrade should work better for you.

**Comment by Term84** [comment]
Thank you for your answer.
