### ISSUE TITLE
Extra trailing characters in password are ignored

### ISSUE THREAD

**Issue by jpatel-evertz** [TigerVNC/tigervnc#1278]
When entering the password, after typing the correct password if extra trailing characters are added they are ignored and login succeeds even though the password as a whole is actually incorrect.

Server Environment:
CentOS Linux 7 64-bit, GNOME 3.28.2
Xvnc TigerVNC 1.8.0 - built Apr  1 2020 04:46:00

Viewer Environment:
Windows 10 Pro Version 1803 OS build 17134.1304
TigerVNC Viewer 64-bit v1.9.0 Built on: 2018-07-18 22:13

**Comment by MarkMielke** [comment]
You didn't mention which password method you are using. But FYI that if you are using traditional Unix crypt(), then the password only only accounts for the first 8 characters. The rest are always ignored. If you are looking for security, you should use a different password method with VNC.

**Comment by jpatel-evertz** [comment]
Thanks for the explanation Mark.  I didn't know that.  I'll close this issue.
