### ISSUE TITLE
Can't disable  throughput graph obscuring lower-right corner of vncviewer client window

### ISSUE THREAD

**Issue by mmhere** [TigerVNC/tigervnc#1279]
**Describe the bug**
Can't disable  throughput graph obscuring lower-right corner of vncviewer client window

**To Reproduce**
1.  Use xtigervnc-viewer to connect to any vnc server

**Expected behavior**
Be able to use entire area of client window without content being obscured

**Client (please complete the following information):**
 - OS: Ubuntu (any, but I'm using 16.04)
 - VNC client: xtigervnc-viewer
 - VNC client version: 1.11.0

**Server (please complete the following information):**
any

**Additional context**
There should be a config option but I can't find it.  Using "-h" at the command line  to dump available options shows nothing to disable this graph.

Bringing up the options dialog while connected (using the desired Menu Key) also shows no  reference to the graph that appears in the lower right.

The graph tries to show pixel and I/O throughput rates, is partially transparent, and is really quite pretty, but it OBSCURES USEFUL CLIENT VISUALS and renders that portion of the screen useless especially when the graph becomes very busy.

I spelunked the code briefly and could find nothing in the parameters.cxx and parameters.h files.

Why is this graph forced on with no obvious (or even non-obvious) way to disable it!?!?!?

**Comment by mmhere** [comment]
Heh ;-)  I even tried this little hack to see if there were any undocumented options/config-settings/arguments that might be tried:

`strings /usr/bin/xtigervncviewer`

I didn't see anything obvious.  I tentatively conclude that there presently is no way to disable this throughput graph from appearing in the lower right corner of the client viewer window.

**Comment by mmhere** [comment]
Well.  I have always kept the -Log option turned on sending output to stdout and typically capturing it for analysis when things go wrong.

I've used this option for many years:

`    -Log '*:stdout:100'`

Removing this makes the graph go away.

It seems like it would be useful to [a] know that the graph is caused by -Log, [b] have a separate option for [en/dis]abling the graph independently from logging, and [c] have the new appearance of this graph be documented more prominently.

To me, requesting "-Log" means to log information, but it does not imply that a debug graph should be painted.  Seems like this should be separated and or renamed in some way.

I suppose I'll do without the logging then.

**Comment by mmhere** [comment]
I added a blurb to the wiki page that describes the `-Log` command line option.  This blurb states that enabling logging also enables the connection diagnosis graph.

If people are OK with that blurb, the priority of this issue may be lessened a bit.

I'd suggest this be treated as an enhancement request:  create separate options for enabling logging -vs- displaying the diagnosis graph.

I hope I haven't upset anyone with the filing of this issue or the modification of the relevant [wiki page](https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs).

**Comment by CendioOssman** [comment]
The update graph didn't get its own setting as it is only for debugging and I didn't want to pollute the options list for that. It is only enabled when debug logging is enabled, so it shouldn't affect any normal use.

Running in debug logging mode constantly is something I'd strongly recommend against as it will write sensitive things to disk. E.g. it will act as a key logger and log every key stroke you make, including passwords.

(Note that the graph is tied specifically to the "DesktopWindow" log target, so if you turn that specific section down you'll get rid of the graph.)
