### ISSUE TITLE
command vncserver disappeared in latest release, is there a compatible replacement?

### ISSUE THREAD

**Issue by joakim-tjernlund** [TigerVNC/tigervnc#1281]
many of our users use the vncserver cmd for simplicity, just ssh a machine, do some edits in .vncxxx and start vncserver.
No need for any setup by an admin. Is this use case till possible?

**Comment by CendioOssman** [comment]
I'm afraid we don't have anything for that use case, no. That method was very hit-and-miss and we could not handle all the issues that were reported for it. The new method is more robust, but unfortunately not as flexible.
