### ISSUE TITLE
Need to kick hotkeys on release, not press

### ISSUE THREAD

**Issue by dechapo** [TigerVNC/tigervnc#1285]
I used to use Ctrl-Shift combination to switch keyboard layouts (ru <--> us) but in this case i cant use any of the Ctrl-Shift-* hotkeys in any software i try.

I noticed, that the keyboard layout becomes swithced as soon an both keys are DOWN -- pressing any other key is not treated as Ctrl-Shift-\<key\> combination.

For example -- in Windows i also use Ctrl-Shift to switch layouts, but there, the layout becomes switched only when both SHIFT and CTRL keys are UP, and no other key was pressed while they were down -- in that case the whole combination is treated as Ctrl-Shift-\<key\> combination, and the layout is not changed.

See also: https://bugs.freedesktop.org/show_bug.cgi?id=865 and http://bugs.kde.org/show_bug.cgi?id=59303

The pacthed Xorg server is at https://launchpad.net/~nrbrtx/+archive/ubuntu/xorg-hotkeys and https://aur.archlinux.org/packages/xorg-server-bug865/

**Comment by CendioOssman** [comment]
I'm afraid TigerVNC does no layout switching, so there isn't anything we can do about such issues. Once that bug is resolved in Xorg it should work the same in TigerVNC.
