### ISSUE TITLE
After creating multiple vnc processes with the command vncserver -geometry 1920x1080, they cannot continue to be created properly, prompting gnome-session-binary killed by SIGTRAP

### ISSUE THREAD

**Issue by superabbite1** [TigerVNC/tigervnc#1294]
*Server (please complete the following information):**
 - OS: [centos7.9]
 - VNC server: [TigerVNC]
 - VNC server version: [1.8.0]

After creating multiple vnc processes (about the 6th or 7th one) with the command vncserver -geometry 1920x1080 in centos7, the system prompts
 gnome-session-binary killed by SIGTRAP error, can not continue to create normally, but I do not have this problem in centos6.9
![QQ截图20210716185349](https://user-images.githubusercontent.com/79433125/125937157-e4b33bd8-5a70-45e7-b64b-ec4ae20b4681.png)

**Comment by CendioOssman** [comment]
I'm afraid that is some bug in gnome-session and you'll have to report it to them. Since it is an old version you'll likely have to report it to Red Hat rather than GNOME.
