### ISSUE TITLE
vncserver -list issue

### ISSUE THREAD

**Issue by xfgavin** [TigerVNC/tigervnc#1296]
**Describe the bug**
vncserver -list seems to check pid files in .vnc folder and return vnc session based that without making for sure if the process is actually the user's VNC session.

**To Reproduce**
1. Go to .vnc folder
2. create a fake hostname:x.pid file
3. put an existing/non-existing pid in the fake file.
4. vncserver -list
5. You will get a stale status if the pid doesn't exist, but a normal status if the pid exists regardless if the pid is actually user's VNC session or not.

**Expected behavior**
Only show user's existing VNC sessions.

**Client (please complete the following information):**
 - OS: Debian buster
 - VNC client: TigerVNC
 - VNC client version: 1.9.0+dfsg-3+deb10u3
 - Client downloaded from: Debian official repo

**Server (please complete the following information):**
 - OS: Debian buster
 - VNC server: TigerVNC
 - VNC server version: 1.9.0+dfsg-3+deb10u3
 - Server downloaded from: Debian official repo
 - Server was started using: `vncserver`

**Comment by CendioOssman** [comment]
I'm afraid the `vncserver` script has been deprecated. And Debian also includes their own version, rather than the one we used to have. So I'm afraid you'll have to file a report with Debian and see if they can have a look at this issue.

**Comment by xfgavin** [comment]
@CendioOssman Thank you. I actually checked my version of vncserver and found it was the same as tigervncserver.
