### ISSUE TITLE
WARNING: Could not connect to ConsoleKit: The maximum number of active connections for UID 0 has been reached

### ISSUE THREAD

**Issue by superabbite1** [TigerVNC/tigervnc#1297]
- OS: [centos6.9]
 - VNC server: [TigerVNC]
 - VNC server version: [1.1.0]

The command vncserver -geometry 1920x1080 was used and after 30 logs there was a WARNING: Could not connect to ConsoleKit: The maximum number of active connections for UID 0 was reached.
[localhost.localdomain%3A31.log](https://github.com/TigerVNC/tigervnc/files/6834551/localhost.localdomain.3A31.log)

**Comment by superabbite1** [comment]
![QQ截图20210718130137](https://user-images.githubusercontent.com/79433125/126056360-b9fe5037-9592-4e5d-85fd-0e0d1b08b1f0.png)

**Comment by CendioOssman** [comment]
I'm afraid this is not something we can help you with as that's a very old version of TigerVNC. Please file a report with CentOS and see if they can help you figure out why gnome-session doesn't want to work.
