### ISSUE TITLE
Does the vncserver -geometry command not work anymore in version 1.11.0? 

### ISSUE THREAD

**Issue by superabbite1** [TigerVNC/tigervnc#1298]
Does the vncserver -geometry command not work anymore in version 1.11.0? Including vncserver -list which is not available anymore

**Comment by CendioOssman** [comment]
The `vncserver` script is deprecated in TigerVNC 1.11.0. Please see this howto for some initial steps to migrate to the new system:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md
