### ISSUE TITLE
One-shot remote resize

### ISSUE THREAD

**Issue by jwebb** [TigerVNC/tigervnc#1299]
I find myself connecting to the same server from clients with different multi-monitor configurations. While using the client, I'll mostly run full-screen, but occasionally jump out to use the local machine. I don't want my remote window layout messed up every time I do this.

Currently AFAIK getting this to work involves a little dance each time I connect:
- Make connection
- Settings -> Screen -> Enable remote resize
- Go full-screen
- Settings -> Screen -> Disable remote resize

Seems like what I want is one or both of:
1. A single-shot "Resize session to window" menu option, to complement the existing "Resize window to session".
2. Changing the "Resize remote session on connect" option to allow specifying a size that's "whatever my selected fullscreen layout is", which may be non-rectangular.

I'd take a look at implementing these, but I'd appreciate some feedback first on the approach.

**Comment by CendioOssman** [comment]
To be honest, this sounds a little too niche for us to add a special option for it. In most cases the windows jump back to their previous positions when you resize back to full screen. I guess that isn't happening for you?

Have you had a look at the `-DesktopSize` argument? I think it should give you the one shot behaviour you want. You'll have to set up some script to calculate the dimensions first though as it cannot help you with that.

**Comment by jwebb** [comment]
`-DesktopSize` is just the command-line equivalent of the GUI option I mention in (2). AFAIK it's limited to specifying the framebuffer bounding rectangle, i.e. it can't transmit the correct layout information to allow the remote to do things like maximise a window to fill one monitor. The dynamic remote resize logic is actually smart enough to send the full multi-monitor layout to the remote (and for me this correct multi-monitor handling is the single biggest advantage of TigerVNC over its peers).

Extending `-DesktopSize` to support specifying a complete layout would be an option that's consistent with TigerVNC's abilities in general, but seems like bad UX: It would be painful for the user to come up with the correct parameters, and I can't imagine any parameters being chosen other than "what I have physically in front of me". That is, another way to read my suggestion (2) is "Provide a `-DesktopSize=fullscreen` option, supporting multi-monitor layouts, plus equivalent GUI".

Regarding the remote (Gnome) handling resizes gracefully, it sort of mostly works, but seems flaky. It seems to randomly miss windows, change window z-order, and also to move windows one at a time, which for me means shipping all the pixels of a 5760x2160 framebuffer several times over, so it's pretty janky.

**Comment by samhed** [comment]
I think it would be a mistake to complicate the GUI or command line options in this area further.

We're glad to hear that you appreciate TigerVNC, thanks for the kind words!
