### ISSUE TITLE
Cannot modify Xserver clipboard from server's commandline until a first client connects

### ISSUE THREAD

**Issue by marlemion** [TigerVNC/tigervnc#1303]
Hi, I am firing up a tigervnc server on recent arch linux with the following line:

```
/usr/bin/Xvnc :2 -desktop localhost:2 -auth <path-to-xauth-file> -geometry 1024x768 -rfbwait \
30000 -rfbauth <path-to-auth-file>-rfbport 5902 -fp catalogue:/etc/X11/fontpath.d -pn \ 
-AcceptCutText -SendCutText -SendPrimary=0 -SetPrimary=0
```

I can connect both from the VNC and the Xserver side, i.e. connect from a windows client via VNC and fire up xclock on the server in an environmet with 
```
DISPLAY=:2
XAUTHORITY=<path-to-xauth-file>
```
However, I would like to paste a string to the programm running on the Xserver from the command line. Unfortunately, I cannot use
`xte 'str <string>'`
due to its limitations in view of unicode characters. Hence, I have to use
`xclip`
or
`xsel -b `
and after that use
`xte 'keydown Control_L' 'key v' 'keyup Control_L'`
and
`xte 'key Return'`
to paste the data.

This actually works out nicely. However, it only works after I have connected via VNC once. It even doesn't matter whether the VNC client is still connected when pasting the data via xsel or xclip.

I have tried using
`autocutsel -fork`
and
`vncconfig &`
but with no luck. Is there any other option I could try to enable the clipboard mechanism before any VNC client has connected?

I am actually using the XVnc server as a framebuffer on a headless machine to execute X11 programs. These are controlled by mostly xte, but now I am hit by the unicode limitation of xte and would like to be able to paste text with i.e. German umlauts into the running X11 programs. The Vnc functionality is only needed for control purposes.

**Comment by CendioOssman** [comment]
No response. Closing.
