### ISSUE TITLE
"Less then" angle bracket "<" key produces ">" character #734 when using TigerVNC 1.7 on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by sunny127** [TigerVNC/tigervnc#1304]
I tried several VNC clients, the problem persists. The problem is in the server.
According to bug [https://github.com/TigerVNC/tigervnc/issues/734](url) this issue has been fixed in TigerVNC 1.9 . However I am using Ubuntu 18.04 LTS and only TigerVNC 1.7 is available for this Ubuntu version. 
What can be done?

**Comment by CendioOssman** [comment]
You can either try one of our releases (we have packages for Ubuntu 18.04), or you can file a bug with Ubuntu and see if they can fix their package or upgrade it. I'm afraid we can't do anything about their packages.
