### ISSUE TITLE
Bad colors are visible when connecting to x0vncserver 1.7 on ubuntu 18.04 LTS from Windows UltraVNC 1.3.2a viewer

### ISSUE THREAD

**Issue by sunny127** [TigerVNC/tigervnc#1305]
Please see the blue rectangular shape over the highlighted file name. Doesn't happen when the client is "Windows tigerVNC viewer". Any ideas?

![image](https://user-images.githubusercontent.com/8320715/127861850-80a63079-7636-4204-beef-140e36a804c8.png)

**Comment by CendioOssman** [comment]
I'm afraid that is way too old for us to support. Please try the current version of TigerVNC and see if the issue still remains there.
