### ISSUE TITLE
how to diaable the logs the logs cause an error

### ISSUE THREAD

**Issue by seisdr** [TigerVNC/tigervnc#1307]
```
root@localhost:~# cat .vnc/localhost\:1.log
11/08/21 15:14:28 Xvnc version TightVNC-1.3.10
11/08/21 15:14:28 Copyright (C) 2000-2009 TightVNC Group
11/08/21 15:14:28 Copyright (C) 1999 AT&T Laboratories Cambridge
11/08/21 15:14:28 All Rights Reserved.
11/08/21 15:14:28 See http://www.tightvnc.com/ for information on TightVNC
11/08/21 15:14:28 Desktop name 'X' (localhost:1)
11/08/21 15:14:28 Protocol versions supported: 3.3, 3.7, 3.8, 3.7t, 3.8t
11/08/21 15:14:28 Listening for VNC connections on TCP port 5901
it looks like wine32 is missing, you should install it.
multiarch needs to be enabled first.  as root, please
execute "dpkg --add-architecture i386 && apt-get update &&
apt-get install wine32"
Fatal Python error: Py_Initialize: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle

Current thread 0x00000009 (most recent call first):
```
this error 
```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle

Current thread 0x00000009 (most recent call first)
```
also occurs when using `wine App.exe > filename.txt `not vncserver so its a log issue please how to disable logs
also see https://github.com/vifm/vifm/issues/592

**Comment by CendioOssman** [comment]
I'm afraid I don't quite understand what it is you'd like to happen. Could you elaborate a bit more?

**Comment by seisdr** [comment]
well there is an windows program that has python plugins if i happen to run this program with wine using this symbol > it will crash giving me an error otherwise it work fine now that error is the same when using the vncserver i add wine appname.exe to xstartup i start the vncserver by just typing vncserver and nothing shows up in the server and the same error `can't initialize sys standard streams
OSError: [WinError 6] Invalid handle`
