### ISSUE TITLE
Transparent windows using TigerVNC

### ISSUE THREAD

**Issue by saandre15** [TigerVNC/tigervnc#1308]
**Describe the bug**
TigerVNC makes some opaque window transparent. 

**To Reproduce**
1. Open VMD
2. The Main Menu is transparant

**Expected behavior**
TigerVNC keep opaque window opaque.

**Screenshots**
**Look at VMD**
![2021-08-12-142054_3840x1080_scrot](https://user-images.githubusercontent.com/47450248/129257426-ffdb9083-f425-465e-812c-a7cf5d17b335.png)
![2021-08-12-142132_3840x1080_scrot](https://user-images.githubusercontent.com/47450248/129257432-87ffbf7b-1f30-45a2-ba17-e21aa699610a.png)
![2021-08-12-142140_3840x1080_scrot](https://user-images.githubusercontent.com/47450248/129257440-96519ce1-422c-4943-85c7-3fa92fa419af.png)
![2021-08-12-142148_3840x1080_scrot](https://user-images.githubusercontent.com/47450248/129257448-a5d70444-d04e-4be3-9ea8-aff0c5b99225.png)
![2021-08-12-142157_3840x1080_scrot](https://user-images.githubusercontent.com/47450248/129257456-287b8c37-86ed-4e8f-a24e-76dc4cc2e477.png)

**Client (please complete the following information):**
 - Manjaro 20.04
 - TigerVNC 
 - v1.11.0
 - Manjaro Repo

**Server (please complete the following information):**
 - Ubuntu 20.04
 - TigerVNC
 - v1.10.1+dfsg-3
 - Ubuntu Repo: `tigervnc-standalone-server`
 - Started using `vncserver :3 -localhost -geometry 1920x1080 -depth 32`

**Additional context**
When I use `x11vnc` this doesn't occur, however when I use `tigervnc` the window becomes transparent in different circumstances.

**Comment by saandre15** [comment]
It seems to be affecting applications that uses the [FLTK](https://www.fltk.org) graphical library. Is there any workaround to this issue?

**Comment by saandre15** [comment]
I tried this xfce no compositor.

**Comment by CendioOssman** [comment]
It's likely that Xfce doesn't support transparency without compositing, so it's still not entirely clear where the blame lies here.

As I mentioned, could you test with our server builds? If they work then it indicates there is some issue with Ubuntu's builds of Xvnc.

**Comment by CendioOssman** [comment]
No response. Closing.
