### ISSUE TITLE
TightVNC Viewer Closes Suddenly

### ISSUE THREAD

**Issue by githubrjd** [TigerVNC/tigervnc#1312]
My viewer keeps closing for some unknown reason.  Sometimes it will just do it on its own. However Click-Drag-Release to select and copy text seems to make it happen more often.  This happens with multiple servers.

If I use TigerVNC, I don't see the issue at all.

I tried turning on log verbosity as much as I could find, but I didn't see anything in the logs it produced.  I not sure what other steps I can do to supply more information,

**Comment by samhed** [comment]
Things work fine using TigerVNC's viewer, and TigerVNC's server? And you see the problem when using TigerVNC's viewer and other VNC servers? What other VNC servers are you using?

The logical conclusion here is that those other servers are buggy and are closing the connection. Are there any details I'm missing?

**Comment by githubrjd** [comment]
Server was TigerVNC (this is a managed system, so I have no control of server selection).

That being said, I was able to look at the server log and found some sort of missing object causing a KDE crash.  I changed the default to gnome and the problem went away.
