### ISSUE TITLE
VNCServer Security Type Settings RA2, VncViewer  connection failure, No matching security type

### ISSUE THREAD

**Issue by lai-git** [TigerVNC/tigervnc#1315]
**Describe the bug**

**To Reproduce**
1. VNCServer Security Type Settings RA2 only
2. java VncViewer connection VncServer
3. failure: No matching security type

**Expected behavior**
The connection is successful

**Screenshots**
![image](https://user-images.githubusercontent.com/55838404/130609667-8c141871-b4d5-4bbd-84f5-fc2aa6fd5d4d.png)

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC for java
 - VNC client version:  master code
 - Client downloaded from: github

**Server (please complete the following information):**
 - OS: windows server 2012
 - VNC server: RealVNC
 - VNC server version: 5.2.3
 - Server downloaded from: RealVNC website
 - Server was started using: last month

**Additional context**
The code doesn't support it

**Comment by CendioOssman** [comment]
The RA2 security type is unfortunately secret so it's not something we can support. If you can convince RealVNC to document how it works we can look at supporting it, but until then I'm afraid there is nothing we can do.

To make RealVNC's server work with regular VNC clients you need to configure it to use the classical VNC authentication.
