### ISSUE TITLE
libvnc.so does not take input on Intel IRIS GPUs

### ISSUE THREAD

**Issue by joakim-tjernlund** [TigerVNC/tigervnc#1316]
**Describe the bug**
Newer computers uses Intels IRIS GPUs(older is i965) and at the login screen(SDDM) one cannot enter any input chars.

**To Reproduce**
1. Add: 
```
cat /etc/X11/xorg.conf.d/50-vnc.conf 
Section "Module"
	Load "vnc"
EndSection

Section "Screen"
	Identifier "Default Screen"
	Option "PasswordFile" "/root/.vnc/passwd"
	#Option "SecurityTypes" "None"
	#Option "rfbport" "5902"
EndSection
```
2. Try login over VNC and enter user name
3. No chars are accepted.

**Client (please complete the following information):**
 - OS: Gentoo
 - VNC client: Remmina
 - Client downloaded from: [Gentoo]

**Server (please complete the following information):**
 - OS: Gentoo
 - VNC server: TigerVNC 
 - VNC server version: git master 
 - Server downloaded from: TigerVNC at github
 - Server was started using:  libvnc.so Xorg module

**Additional context**
Same SW works on i965 GPUs
Xorg-server: 1.20.13

**Comment by CendioOssman** [comment]
The interfaces are the same, so it's more likely that Glamor forgets to inform the rest of the X server when the GPU is modifying things (a common bug in other hardware acceleration).

Composite isn't strictly necessary. Glamor accelerates all RENDER operations, which SDDM likely uses.

It's odd that the log setting doesn't work. It's obviously picking up your "PasswordFile" setting or you wouldn't be able to authenticate.

Do you get anything in the log that looks like it's from the VNC module?

**Comment by joakim-tjernlund** [comment]
Xorg Server 21.1 RC1 is out, The current libvnc does not build against this Xorg release.
Any chance you can update tigervnc? I would like to test if that one solves this problem.

**Comment by CendioOssman** [comment]
It's unlikely we'll look at that before a final release is out. What errors are you getting?

**Comment by joakim-tjernlund** [comment]
Seems like this issue has healed itself, I can no longer provoke it.

https://github.com/TigerVNC/tigervnc/issues/1218 is still there though.
