### ISSUE TITLE
Xtigervnc did not start up [windows kex error while starting kali linux]

### ISSUE THREAD

**Issue by ghost** [TigerVNC/tigervnc#1319]
Xvnc TigerVNC 1.11.0 - built 2021-03-22 21:21
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12010000, The X.Org Foundation

Sat Aug 28 10:26:06 2021
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5901
 vncext:      created VNC server for screen 0

Sat Aug 28 10:26:36 2021
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
=========================================================================================

tigervncserver: /usr/bin/Xtigervnc did not start up, please look into '/home/himanshu/.vnc/dip.localdomain:5901.log' to determine the reason! -1
![Screenshot (105)](https://user-images.githubusercontent.com/89677955/131206861-01c980e4-d9c4-4623-b8c1-4164d2e31a87.png)

**Comment by CendioOssman** [comment]
Please fill out the issue template so we can understand your setup.

**Comment by CendioOssman** [comment]
No response. Closing.
