### ISSUE TITLE
Fail to enable TLS

### ISSUE THREAD

**Issue by coeusite** [TigerVNC/tigervnc#132]
I did connect to TigerVNC server without encryption by TigerVNC viewer.
However, I fail to set up any encrypted connection.

server: 
vncserver :3 -x509key ~/.pki/server-key.pem -x509cert  ~/.pki/server.pem

log:
```
TigerVNC Viewer 64-bit v1.4.2
Built on: 2015-02-24 17:13
Copyright (C) 1999-2014 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Wed Feb 25 07:21:29 2015
 CConn:       connected to host 127.0.0.1 port 5903
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: No matching security types
 CConn:       No matching security types
```

**Comment by CendioOssman** [comment]
Simply specifying the certificate and key file is unfortunately not enough to enable X509. You should also include `-SecurityTypes=X509Vnc` (or `X509Plain` or whatever you prefer).

**Comment by coeusite** [comment]
Thank you!
