### ISSUE TITLE
ZlibLevel is an invalid option in ~/.vnc/config

### ISSUE THREAD

**Issue by thiled** [TigerVNC/tigervnc#1320]
while I put ZlibLevel option in ~/.vnc/config
```
ZlibLevel=0
```
I got invalid option error

**Comment by thiled** [comment]
The original error is:
(EE) Fatal server error:
(EE) Unrecognized option: /root/.Xauthority        
seems none business with the option  added, but when I remove the ZlibLevel option, the error gone.

**Comment by CendioOssman** [comment]
This is a bug that was fixed for #1098. Please try a pre-release build and this issue should be fixed.
