### ISSUE TITLE
TigerVNC options not saved

### ISSUE THREAD

**Issue by Napryc** [TigerVNC/tigervnc#1321]
**Describe the bug**
Modifications done in the options are not kept when closing Tiger VNC.

**To Reproduce**
1. Go to 'Options'
2. Modify one option
3. Quit the program
4. Launch again TigerVNC
5. Open 'Options': modified option is set back to its default value

**Expected behavior**
Modified options should be persistent after program has been closed

**Client (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - VNC client: TigerVNC
 - VNC client version: 1.11.0 64 bits
 - Client downloaded from: Official Sourceforge page

**Additional context**
I've faced the bug when I've switched to dual monitor setup. TigerVNC always open full-screen extended on the two monitors, and disabling 'Enable full-screen mode over all monitors' is not kept after the program is closed/restarted.
I've tried with another option: 'Misc. > Show dot when no cursor', and same behavior is seen.

Modifying the options value in the registry base before launching the program allow to have the options properly set, but this is still not kept (reverse to default) after closing the program

**Comment by CendioOssman** [comment]
Options are currently saved when you connect, not when you close the options dialog (because reasons). Does that still work on your system?

**Comment by Napryc** [comment]
Ok, didn't try that. It works fine when editing options before to connect. 

If the behavior is not going to change, that could be nice to have this information somewhere in the documentation.
Anyway, I think this can be closed .
