### ISSUE TITLE
Symptom The freerdp Web fails to perform the first clipboard operation on a Windows device. When data is copied from the PC to the Windows device, the clipboard data is not synchronized to the target Windows device

### ISSUE THREAD

**Issue by request-terra** [TigerVNC/tigervnc#1323]
**Describe the bug**
When the local clipboard is copied to the target device, tigerVNC receives the clipboard event but does not send the event to the target device. The sending function is not called

**To Reproduce**
1.Access a FreerDP Web session
2. The clipboard data is copied from the client to the target Windows device. The clipboard data is sent to TigerVNC, but not to the target device
3. Copy data from the target device and perform 2 again. The clipboard data is successfully copied to the target device

**Expected behavior**
The first copy of the clipboard from the client to the target device is expected to be successful

**Screenshots**

tigervnc-1.10.90， Target Windows device Windows 2008

**Additional context**

**Comment by CendioOssman** [comment]
This sounds like an issue with FreeRDP not sending the clipboard correctly. What is it that leads you to us in this issue?

**Comment by request-terra** [comment]
> 这听起来像是 FreeRDP 未正确发送剪贴板的问题。是什么让您在这个问题上找到我们？

Clipboard data has been received in the Linux background, and tigerVNC1.31 clipboard events can be sent normally

**Comment by CendioOssman** [comment]
I'm afraid I still don't see what the issue with TigerVNC is. If you are saying that TigerVNC handles the clipboard events, then this issue should be reported to FreeRDP. Or am I missing something?

**Comment by request-terra** [comment]
> 恐怕我仍然不明白 TigerVNC 的问题是什么。如果您说 TigerVNC 处理剪贴板事件，则应将此问题报告给 FreeRDP。或者我错过了什么？
Tigervnc did not send clipboard data to freerDP after receiving it

**Comment by CendioOssman** [comment]
Does the clipboard work for other applications in the VNC session? And do you have some logs?

**Comment by CendioOssman** [comment]
No response. Closing.
