### ISSUE TITLE
XDMCP access clipboard control fails

### ISSUE THREAD

**Issue by request-terra** [TigerVNC/tigervnc#1324]
**Describe the bug**
XDMCP accessing Linxu devices, SenCutText and AcceptCutText disabling clipboard events can still copy clipboard data from Linux to the client

**To Reproduce**
1.Access an XDMCP session,
2.Copy data from Linux to local
3.Copy success

**Expected behavior**
Expected copy failure after disabling clipboard data

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. centos7]
 - VNC client: [e.g. TigerVNC]
 - VNC client version: [e.g. 1.10.90]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. centos 5/6/7]
 -Desktop[gnome + gdm]

**Additional context**

**Comment by CendioOssman** [comment]
Please describe exactly how this is set up. The most likely explanation is that the settings aren't getting properly applied for some reason.

**Comment by request-terra** [comment]
> 请准确描述这是如何设置的。最可能的解释是由于某种原因设置没有得到正确应用。

Xvnc :1 -rfbport 4001 -localhost -query x.x.x.x -once -from x.x.x.x -desktop root@x.x.x.x -SecurityTypes None -auth /home/shterm/.Xauthority -geometry 1530x914 -depth 16 -pn -extension XKEYBOARD -RecordInput=true -ReadOnly=true -AcceptCutText=false -SendCutText=false -IncrementSize=1048576

**Comment by CendioOssman** [comment]
Those arguments are not something we have in TigerVNC, so it looks like you are running some other VNC server. I'm afraid I'll have to ask you to report your issue to that project or vendor.

**Comment by request-terra** [comment]
> 这些参数在 TigerVNC 中没有，所以看起来您正在运行其他一些 VNC 服务器。恐怕我将不得不要求您向该项目或供应商报告您的问题。

AcceptCutText=false -SendCutText=false The clipboard disable parameters are these two, but they are invalid

**Comment by request-terra** [comment]
> > 这些参数在 TigerVNC 中没有，所以看起来您正在运行其他一些 VNC 服务器。恐怕我将不得不要求您向该项目或供应商报告您的问题。
> 
> AcceptCutText=false -SendCutText=false 剪贴板禁用参数是这两个，但是无效

@CendioOssman
