### ISSUE TITLE
vncserver inactive (dead) in systemctl as long as `SELINUX=enforcing` RHEL8

### ISSUE THREAD

**Issue by pberto** [TigerVNC/tigervnc#1325]
**Describe the bug**
vncserver is not enabled (Active: inactove (dead)) in systemctl as long as `SELINUX=enforcing`

As soon as I set selinux to permissive it runs fine.

**To Reproduce**
1. install default RHEL 8.4
2. follow the steps to install tigervnc-server:
3. systemctl start the vncserver service
4. check systemctl status of vncserver

**Expected behavior**
I would expect the vncserver  to run out of the box with SELINUX=enforced

**Server (please complete the following information):**
 - OS: RHEL8 (8.4)
 - VNC server: TigerVNC
 - VNC server version: 1.11.0-6.el8
 - Server downloaded from: rhel8 
 - Server was started using: `sudo systemctl start vncserver@:2`

**Comment by CendioOssman** [comment]
Unfortunately there has been some back and forth on what SELinux rules TigerVNC should have (see #1189). You should be able to get things running by doing `restorecon` on `~/.vnc`.

**Comment by hardhub** [comment]
> Unfortunately there has been some back and forth on what SELinux rules TigerVNC should have (see #1189). You should be able to get things running by doing `restorecon` on `~/.vnc`.

It was helpful for Fedora 34 as well. After latest TigerVNC upgrade my systemd unit was unable to start.

To restore context I run:

`restorecon -R -v /home/<target username>/.vnc`

After that it was possible to restart VNC even with selinux enforced.
