### ISSUE TITLE
I use vncserver + xfce4 cannot start vncserver ?

### ISSUE THREAD

**Issue by huyifanstar** [TigerVNC/tigervnc#1326]
In the new version, I saw that vncserver was cancelled, and a new executable file of x0vncserver was added? 

- VNC server:  http://tigervnc.bphinz.com/nightly/xc/x86_64/tigervnc-1.11.80-20210902git4d4e3b28.x86_64.tar.gz
- Desktop package: xfce4

System Version：ubuntu 18.04
~# x0vncserver   :0 -localhost -geometry 1920x1080 -depth 32
Parameters can be turned on with -<param> or off with -<param>=0
Parameters which take a value can be specified as -<param> <value>
Other valid forms are <param>=<value> -<param>=<value> --<param>=<value>
Parameter names are case-insensitive.  The parameters are:
........................

~# x0vncserver -display :0 -passwordfile ~/.vnc/passwd
x0vncserver: unable to open display ":0"

How do I start now?
In the historical version (tigervnc-1.10.1.x86_64), my startup command: vncserver: 3 -localhost -geometry 1920x1080 -depth 32
Thank You!

**Comment by CendioOssman** [comment]
`x0vncserver` is for giving access to an existing session, so I'm afraid it is not a replacement for `vncserver`. Instead you need to start your VNC sessions as systemd services. Please see the HOWTO for how to get started:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

**Comment by huyifanstar** [comment]
> `x0vncserver` is for giving access to an existing session, so I'm afraid it is not a replacement for `vncserver`. Instead you need to start your VNC sessions as systemd services. Please see the HOWTO for how to get started:
> 
> https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

I use a binary program to start vncserver,But now there is no vncserver file?
VNC server: http://tigervnc.bphinz.com/nightly/xc/x86_64/tigervnc-1.11.80-20210902git4d4e3b28.x86_64.tar.gz

**Comment by CendioOssman** [comment]
That is correct. You need to use a service instead as described in the HOWTO.

**Comment by huyifanstar** [comment]
> That is correct. You need to use a service instead as described in the HOWTO.

Thank you for your patience, I use docker to run vncserve, no systemctl!

root@735d18f14ccf:/# x0vncserver -display :0 -passwordfile /home/user/.vnc/passwd -rfbport 5900
x0vncserver: unable to open display ":0"

I have consulted a lot of information and still haven't been able to solve it，Can you help me?

Thank you!

**Comment by MarkMielke** [comment]
The upstream project admin have deprecated and eliminated the capability you are looking for.

Those of us who still require this function have forked a prior version of "vncserver" script. It continues to work fine, as it did before. I have updated our fork significantly since this time to make it better than before. But, I remain unsure of what next step to take since it seems there will not be appetite to re-accepting this into the main project and I don't want to create a competing project. For the time being - I recommend you fork a prior version of the script and use it. If the project admin do want to accept my changes into the main project, I will be happy to provide them.

**Comment by huyifanstar** [comment]
> The upstream project admin have deprecated and eliminated the capability you are looking for.
> 
> Those of us who still require this function have forked a prior version of "vncserver" script. It continues to work fine, as it did before. I have updated our fork significantly since this time to make it better than before. But, I remain unsure of what next step to take since it seems there will not be appetite to re-accepting this into the main project and I don't want to create a competing project. For the time being - I recommend you fork a prior version of the script and use it. If the project admin do want to accept my changes into the main project, I will be happy to provide them.

I upgraded from a historical version to tigervnc-1.11.80, I need to solve the following problems
https://github.com/TigerVNC/tigervnc/issues/1322

But after the upgrade, the previous method cannot start normally
What should I do now ?  

Thank you

**Comment by MarkMielke** [comment]
It's just a script. Copy it from older version. But if you cannot figure out how to do this, then this is where the dilemma begins. Providing official support beyond do it yourself creates a direct contradiction with upstream project and I'm still not ready to do this.

**Comment by CendioOssman** [comment]
> The upstream project admin have deprecated and eliminated the capability you are looking for.
> 
> Those of us who still require this function have forked a prior version of "vncserver" script. It continues to work fine, as it did before. I have updated our fork significantly since this time to make it better than before. But, I remain unsure of what next step to take since it seems there will not be appetite to re-accepting this into the main project and I don't want to create a competing project. For the time being - I recommend you fork a prior version of the script and use it. If the project admin do want to accept my changes into the main project, I will be happy to provide them.

Such a script will indeed not be accepted to this project at this time as it would mean a return of all the issues surrounding it. But if you set up a separate repository for it then it would be something we can reference for people to try without implying that the TigerVNC project would also support issues with it.
