### ISSUE TITLE
Automatically selects "gnome classic" shell

### ISSUE THREAD

**Issue by byron-hawkins** [TigerVNC/tigervnc#1329]
When I run tigervnc using `systemctl start vncserver@:1` it automatically logs in and chooses "gnome classic" as the shell. This makes it very hard to use. The new gnome shell can be selected by specifying the `session` parameter in the file `/etc/tigervnc/vncserver-config-defaults`. Nowhere in the `man` page for `vncserver` is this mentioned, neither is there any reference to the easter-egg file `/usr/share/doc/tigervnc/HOWTO.md`. The only way I could figure this out was by `vncserver --help` and then following the easter-egg hint. 

This HOWTO file should be referenced in the `man` page and also on the front page of this github repository.

**Comment by CendioOssman** [comment]
Are you perhaps using a Red Hat packaging of TigerVNC? We haven't made a release with the HOWTO included yet. The man page does mention the special `session` parameter, so I'm wondering if you might have some packaging that has an older version of it.

**Comment by byron-hawkins** [comment]
Searching for "session" in the man page gives me 3 results, none related to the gnome session. A search for "gnome" gives no results. My install of TigerVNC is indeed from a fedora 34 package. Here's the version:

    > vncserver -version
    vnc TigerVNC 1.11.0 - built Jun 16 2021 00:00:00
    Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
    See https://www.tigervnc.org for information on TigerVNC.
    Underlying X server release 12011000, The X.Org Foundation

**Comment by CendioOssman** [comment]
Ah, I see that Fedora still ships an old man page even though they've upgraded to TigerVNC 1.11.0. In our version we have:

>               The  special  option session can be used to control which session type will be started.
>               This should match one of the files in /usr/share/xsessions. E.g. if  there  is  a  file
>               called "gnome.desktop", then "session=gnome" would be set to use that session type.

This can also be found in Fedora in the "vncsession" man page.

As this is an issue specific to Fedora's packaging, I'm afraid I'll have to direct you to report the issue to them. @grulja, you might want to have a look at seeing what you can clear up here.

**Comment by grulja** [comment]
I updated Fedora package in Rawhide to 1.11.90 and dropped the old man page.
