### ISSUE TITLE
error connect vncviewer: x input 2 (or never) is not available

### ISSUE THREAD

**Issue by IgorVM2009** [TigerVNC/tigervnc#1333]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC client: [e.g. TigerVNC, or UltraVNC]
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC server: [e.g. TigerVNC, or UltraVNC]
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver`]

**Additional context**

**Comment by CendioOssman** [comment]
Please fill out the issue form so that we can understand your setup.

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by uli42** [comment]
Just for reference for anyone seeing this error: It happens when the display X server is not offering the Xinput extension in version 2. You can check this by running `xdpyinfo -ext XInputExtension`. It will display the version number of the extension. So you probably can get around this by switching to another X server.

**Comment by e70838** [comment]
Hello, I have encountered the same issue.
My server is a virtual server launched with the command
`/usr/bin/Xvnc :2 -listen tcp -SecurityTypes None -AlwaysShared -geometry 520x444`

My vncviewer is launched with the command `DISPLAY=server13:0.0 vncviewer :2`
the same command works on another display `DISPLAY=server17:0.0 vncviewer :2`

I have tried `DISPLAY=:2 xdpyinfo -ext XInputExtension` , it was XInputExtension version 2.3
Then I have tried strace to see the differences:
Fail:
```
10:09:26 recvmsg([{iov_base="\1\0\\\0\0\0\0\0\1\203B\201\16V\0\0\0\31%+\377\177\0\0000\36\262\260\16V\0\0", 
10:09:26 recvmsg([{iov_base="\1\0]\0\0\0\0\0\1\203B\201\16V\0\0\0\31%+\377\177\0\0000\36\262\260\16V\0\0", 10:09:26 recvmsg({[{iov_base="\1\1^\0\0\0\0\0\1\0\3\0\1V\0\0\0\0\0\0\0\0\0\0@\36\262\260\16V\0\0", iov_len=4096}], 10:09:26 recvmsg([{iov_base="\1~_\0\0\0\0\0\1\203B\201\16V\0\0\0\31%+\377\177\0\0000\36\262\260\16V\0\0", iov_len=4096}], 10:09:26 recvmsg([{iov_base="\1\1`\0\0\0\0\0\1\0\3\0\1V\0\0\0\0\0\0\0\0\0\0@\36\262\260\16V\0\0", iov_len=4096}], 
```
Success:
```
10:09:02 recvmsg([{iov_base="\1\0^\0\0\0\0\0\1\203B\201\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], 
10:09:02 recvmsg([{iov_base="\1\0_\0\0\0\0\0\1\203B\201\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], 
...
```
Then I tried `DISPLAY=server13:0.0 xdpyinfo -ext XInputExtension` , it was XInputExtension version 1.3

XInputExtension was version 2.3 on server running RedHat Release 7.7. It is version 1.3 on server running RedHat Release 8.8. I will contact IT.

Why do you limit on XInputExtension >= 2 ? It seems that version 1 is not obsolete. I have not encountered this problem with RealVNC viewer.

**Comment by CendioOssman** [comment]
XInput 2 is over 17 years old. Anything not supporting that would need to be absolutely ancient. It would not be impossible for us to support older systems. But given how long ago that is, we cannot justify all that extra effort.

Red Hat 8 definitely much more recent than 17 years, so it sounds like something is misbehaving there.

**Comment by e70838** [comment]
Further investigation found that the physical display is :5 and displays :0 :1 :2 are virtual displays provided by RealVNC(!) :

VNC(R) Server 6.10.0 (r47347) x64 (Jun 29 2022 12:52:22)
Copyright (C) RealVNC Ltd.

Is it possible that RealVNC does not support XInputExtension >= 2 ? Would it be a good justification to use Tiger VNC instead of RealVNC ?

**Comment by CendioOssman** [comment]
One would have hoped that RealVNC keeps their server up to date. But their focus seems to be elsewhere, so their virtual session product might have stagnated that badly, unfortunately. :/

Using TigerVNC would definitely be a better choice in that case.

I'm a bit unclear on the use case here, though. Why the need to run VNC in VNC?

**Comment by joakim-tjernlund** [comment]
X2Go still uses Xinput 1.3 and other VNCs like turbovnc/tightvnc  supports v. 1.3
 You may want to reconsider adding Xinput 1.3 to tigerVNC

**Comment by joakim-tjernlund** [comment]
> I'm a bit unclear on the use case here, though. Why the need to run VNC in VNC?

Use case is: connect to a remote PC using X2Go, from within that X2Go session, start a VNC session to an instrument running a VNC server. It is not possible to access the instruments directly from outside since
these are only accessible from within that site.
