### ISSUE TITLE
invisible cursor when used with UltraVNC server 1.3.4.1

### ISSUE THREAD

**Issue by ajschorr** [TigerVNC/tigervnc#1335]
**Describe the bug**
I have a Linux Fedora 34 workstation with tigervnc 1.11.0 installed. When I connect to a Windows 10 Pro PC
running UltraVNC 1.3.4.1 server, the cursor/mouse is completely invisible. I tried using the beta 1.11.90 version
of the tigervnc client, and it still has the same problem. This problem has been present with past versions of
UltraVNC as well.

**To Reproduce**
1. On a Windows 10 Pro PC, run UltraVNC server 1.3.4.1
2. On a Linux PC, connect using the tigervnc vncviewer client.
3. Observe that the mouse is invisible.
4. This problem does not occur with other VNC clients such as vinagre, realvnc, and remmina.

**Expected behavior**
The cursor should be visible.

**Screenshots**

**Client (please complete the following information):**
 - OS: Fedora 34
 - VNC client: TigerVNC
 - VNC client version: 1.11.0 and 1.11.90
 - Client downloaded from: Fedora and from tightvnc sourceforge site

**Server (please complete the following information):**
 - OS: Windows 10 Pro
 - VNC server: UltraVNC
 - VNC server version: 1.3.4.1, but I have observed this in prior versions as well.
 - Server downloaded from: uvnc.com
 - Server was started using: standard ultravnc installation

**Additional context**

**Comment by ajschorr** [comment]
I tested previous releases, and this worked fine throough 1.10.1. It is broken in 1.11.0. I guess somebody should run a git bisect. Maybe I will get time to do that...

**Comment by ajschorr** [comment]
I ran git bisect on it. Here is the offending commit:
[schorr@asny-nuc ~/tigervnc]$ git bisect bad
2cd3cb48164f105a1c066102c8430317d94bb9f0 is the first bad commit
commit 2cd3cb48164f105a1c066102c8430317d94bb9f0
Author: Pierre Ossman <ossman@cendio.se>
Date:   Mon Dec 23 16:26:40 2019 +0100

    Set initial blank cursor
    
    If the server doesn't support local cursors and want to render them
    itself then we need to make sure the local cursor is invisible.
    
    This also makes sure we always have some cursor allocated, so we can
    remove the checks in some places.

 vncviewer/Viewport.cxx | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

**Comment by ajschorr** [comment]
Reverting that patch fixes the problem. Is that patch beneficial in other scenarios?

**Comment by CendioOssman** [comment]
Yes, that change is needed to avoid double cursors for servers that do not support local cursors.

I'm afraid what you are seeing indicates a bug in UltraVNC. It's something we've seen before in that the server doesn't send over the cursor until the first time the cursor changes. So I'm afraid you'll have to report this issue to UltraVNC and see if they can come up with a fix.

Until then, the workaround we have is the setting "Show dot when no cursor".

**Comment by ajschorr** [comment]
Thanks for the response. FYI, the "show dot when no cursor" setting does not work when set from the option menu after starting vncviewer. The cursor remains invisible. However, if one invokes vncviewer with the -DotWhenNoCursor option, that does seem to work. I had not tried the latter previously. Why does it not work from the option menu?

**Comment by CendioOssman** [comment]
That would be a bug in that case. Let me have a look...

**Comment by CendioOssman** [comment]
I can reproduce that here, so I've added #1340. Thanks for noticing.

**Comment by ajschorr** [comment]
You're welcome. I  will try reporting this to UltraVNC. But isn't the UltraVNC server widely used? It seems to me that there should be some effort to make sure that the tigervnc viewer works with UltraVNC. Or am I the only one using UltraVNC? It feels not OK to me to put out a viewer that simply doesn't work with UltraVNC. The dot cursor is rather sucky, to use a technical term. Just not visually prominent enough.

**Comment by CendioOssman** [comment]
It is popular, but unfortunately we cannot work around this bug without breaking things for servers that are correctly implementing things. And we don't want to punish those that try their best to follow the protocol properly. UltraVNC is fortunately an active project so hopefully they can get this fixed.

**Comment by CendioOssman** [comment]
I would guess they misbehave against servers that want server side cursors, yes. They are rare though, so it's quite possible they haven't gotten any reports for it (or don't care). And after all, we fixed it in TigerVNC fairly recently.

**Comment by ajschorr** [comment]
I posted a message in the UltraVNC forum here:
https://forum.ultravnc.net/viewtopic.php?f=3&t=37411&p=110008&hilit=tigervnc&sid=71fd232bf3fa50013d3ed0a6c620c1bc#p110008
I hope that somehow one or both sides can come up with a fix for this. The current situation
is totally broken.

Thanks,
Andy

**Comment by ajschorr** [comment]
Here's a patch to add a -UseLocalCursor option:

diff --git a/vncviewer/Viewport.cxx b/vncviewer/Viewport.cxx
index 2f8a92c6..0c1979a6 100644
--- a/vncviewer/Viewport.cxx
+++ b/vncviewer/Viewport.cxx
@@ -185,8 +185,9 @@ Viewport::Viewport(int w, int h, const rfb::PixelFormat& serverPF, CConn* cc_)
 
   OptionsDialog::addCallback(handleOptions, this);
 
-  // Make sure we have an initial blank cursor set
-  setCursor(0, 0, rfb::Point(0, 0), NULL);
+  if (!useLocalCursor)
+    // Make sure we have an initial blank cursor set
+    setCursor(0, 0, rfb::Point(0, 0), NULL);
 }
 
 
@@ -582,7 +583,8 @@ int Viewport::handle(int event)
     return 1;
 
   case FL_ENTER:
-    window()->cursor(cursor, cursorHotspot.x, cursorHotspot.y);
+    if (!useLocalCursor || cursor)
+      window()->cursor(cursor, cursorHotspot.x, cursorHotspot.y);
     // Yes, we would like some pointer events please!
     return 1;
 
@@ -1315,7 +1317,7 @@ void Viewport::popupContextMenu()
   handle(FL_FOCUS);
 
   // Back to our proper mouse pointer.
-  if (Fl::belowmouse())
+  if (useLocalCursor ? ((Fl::belowmouse() == this) && cursor) : (Fl::belowmouse() != NULL))
     window()->cursor(cursor, cursorHotspot.x, cursorHotspot.y);
 
   if (m == NULL)
diff --git a/vncviewer/parameters.cxx b/vncviewer/parameters.cxx
index 18384f3a..400db5a7 100644
--- a/vncviewer/parameters.cxx
+++ b/vncviewer/parameters.cxx
@@ -64,6 +64,8 @@ BoolParameter emulateMiddleButton("EmulateMiddleButton",
 BoolParameter dotWhenNoCursor("DotWhenNoCursor",
                               "Show the dot cursor when the server sends an "
                               "invisible cursor", false);
+BoolParameter useLocalCursor("UseLocalCursor",
+                              "Force a local cursor", false);
 
 BoolParameter alertOnFatalError("AlertOnFatalError",
                                 "Give a dialog on connection problems rather "
@@ -177,6 +179,7 @@ static VoidParameter* parameterArray[] = {
   &SecurityClient::secTypes,
   &emulateMiddleButton,
   &dotWhenNoCursor,
+  &useLocalCursor,
   &reconnectOnError,
   &autoSelect,
   &fullColour,
diff --git a/vncviewer/parameters.h b/vncviewer/parameters.h
index 1dd9aca2..c20c5af6 100644
--- a/vncviewer/parameters.h
+++ b/vncviewer/parameters.h
@@ -34,6 +34,7 @@
 extern rfb::IntParameter pointerEventInterval;
 extern rfb::BoolParameter emulateMiddleButton;
 extern rfb::BoolParameter dotWhenNoCursor;
+extern rfb::BoolParameter useLocalCursor;
 
 extern rfb::StringParameter passwordFile;
 
diff --git a/vncviewer/vncviewer.man b/vncviewer/vncviewer.man
index 894787c0..1b581846 100644
--- a/vncviewer/vncviewer.man
+++ b/vncviewer/vncviewer.man
@@ -285,6 +285,10 @@ Use custom compression level. Default if \fBCompressLevel\fP is specified.
 Show the dot cursor when the server sends an invisible cursor. Default is off.
 .
 .TP
+.B \-UseLocalCursor
+Force a local cursor; needed to work around an UltraVNC interoperability problem. Default is off.
+.
+.TP
 .B \-PointerEventInterval \fItime\fP
 Time in milliseconds to rate-limit successive pointer events. Default is
 17 ms (60 Hz).

**Comment by ajschorr** [comment]
FYI, I created a pull request for this patch:
https://github.com/TigerVNC/tigervnc/pull/1342

**Comment by ajschorr** [comment]
FYI, I opened an UltraVNC issue on this topic here:

https://github.com/ultravnc/UltraVNC/issues/24

**Comment by RudiDeVos** [comment]
Did a little research:
Seems TigerVNC send the pseudoEncoding before the actual encoding causing UltraVNC to ignore it.
Changed our code so that it's cached.
UltraVNC now send proper the cursor shapes.

TigerVNC support rfbEncodingXCursor/rfbEncodingRichCursor but not rfbEncodingPointerPos
The server can send the shapes, but can't send a position move, if the cursor moves on the server it isn't visible on the viewer, for that rfbEncodingPointerPos also need to be implemented.
