### ISSUE TITLE
1.11.90 vncviewer does not work on Windows due to wrong JPEG library version

### ISSUE THREAD

**Issue by johahauf** [TigerVNC/tigervnc#1336]
**Describe the bug**
When establishing a connection I get the following error message

![image](https://user-images.githubusercontent.com/74980879/133604759-f1ffbfc6-f25b-4614-8158-8f891702abba.png)

When I do the same thing with the version I compiled locally it is working fine.

**To Reproduce**
1. Download vncviewer 1.11.90. from beta site at source forge
2. Run it, select vnc server, enter password than dialog pops up

**Expected behavior**
No error should happen, same as my local build.

**Client (please complete the following information):**
 - OS: Windows 10 (Version 1803)
 - VNC client version: 1.11.90
 - Client downloaded from: https://sourceforge.net/projects/tigervnc/files/beta/1.12beta/

**Server (please complete the following information):**
 - OS: Linux Redhat 7
 - VNC server: Xvnc TigerVNC 1.8.0 - built Jan 18 2018 08:01:21

**Comment by bphinz** [comment]
Ugh.  Definitely a build issue.  Thanks for the heads up, I’ll fix and re-publish tonight

**Comment by bphinz** [comment]
Thanks for reporting this.  The build issue has been fixed and the corrected files re-published.
