### ISSUE TITLE
[Feature Request]: Remember login username and password of remote host

### ISSUE THREAD

**Issue by evan0greenup** [TigerVNC/tigervnc#1338]
**Is your feature request related to a problem? Please describe.**
Every time, when user what to login to remote host via `vncviewer`, he need to type username and password again in login screen of remote host. This is a great inconvenient to users.

**Describe the solution you'd like**
I am not sure how vnc protocol like, not may be it is possible to pass username and password through connection.

**Describe alternatives you've considered**
If it is not feasible like what describes above, it would be nice to add auto-fill function in `vncviewer`, and everytime login, it will auto fill the username and password.

**Comment by CendioOssman** [comment]
Unfortunately integrating with the desktop environment in such a way is a bit outside our scope. I'm not even aware of any interfaces where we could do such a thing even if we wanted do.

What I would recommend in such cases is disabling the screen saver and relying on the authentication in the VNC server instead.

**Comment by evan0greenup** [comment]
@CendioOssman , if both server side and client side use tigervnc is there a way to auto login?
