### ISSUE TITLE
VNCViewer Connection Details Window (Startup Window) not at centre of screen. 

### ISSUE THREAD

**Issue by evan0greenup** [TigerVNC/tigervnc#1339]
**Describe the bug**
When start `vncviewer`, the `Connection Details` will appear at the left up corner of screen. 

But for majority applications, the startup window should stay at the center of screen.

**To Reproduce**

1. Launch the `vncviewer`.

**Expected behavior**
locate at the center of screen

**Client (please complete the following information):**
 - OS: Linux
 - VNC client: TigerVNC
 - VNC client version: 1.11.0
 - Client downloaded from: Linux distribution package.

**Comment by CendioOssman** [comment]
Hmm.. We're supposed to let the window manager decide. And here on my Fedora machine it seems to be placed the same way as other windows.

What distribution and desktop environment are you using on your client machine?

**Comment by CendioOssman** [comment]
No response. Closing.
