### ISSUE TITLE
VNC viewer showing blank screen .

### ISSUE THREAD

**Issue by tanmaydash12** [TigerVNC/tigervnc#1341]
Hi ,
I tried connecting with vncserver using vnc viewer . But i see only blue screen and not the CLI .
I checked the logs and it shows connected .

Server side : 
 command :   vncserver :1

Client side: 
host:5901
Please help to solve the issue 

![VNC_error](https://user-images.githubusercontent.com/59669680/134131501-d8dfa015-027d-4c3b-b13c-9ef0af36d11b.PNG)
[OPCITSNAL0065%3A1.log](https://github.com/TigerVNC/tigervnc/files/7201295/OPCITSNAL0065.3A1.log)

**Comment by CendioOssman** [comment]
I'm afraid the vncserver script is no longer support. Please upgrade to TigerVNC 1.11.0 and try the new vncserver systemd service instead. It should hopefully work better at starting up your session.
