### ISSUE TITLE
VNCSERVER -kill wants wrong PID file

### ISSUE THREAD

**Issue by davavra** [TigerVNC/tigervnc#1343]
**Describe the bug**
The PID file seems to have been changed to **/run/vncserver-[display].pid**
but **vncserver -kill <display>** wants something like **[user home]/.vnc/[hostname][display].pid**
which it can't find.

#**systemctl stop vncserver@:1** does nothing

UPDATE:
I have a new install on one machine and an older one on another.
The older one works as expected but the new install doesn't work
from **systemd**. I can only start a vnc session using  **vncsession-start**

I still don't know why.
I've set selinux enforcement to Permissive so I can monitor problems.

**To Reproduce**
Start vnc
Try to kill it

**Expected behavior**
Consistent name of PID file

**Screenshots**
N/A.

**Client (please complete the following information):**
N/A

**Server (please complete the following information):**
 - OS: Fedora 34
 - VNC server: TigerVNC
 - VNC server version: 1.11.0-12.fc34
 - Server downloaded from: FC34 distribution
 - Server was started using: vncserver-start or systemctl start vncserver@:1

**Additional context**
N/A

**Comment by CendioOssman** [comment]
The correct way is to use systemctl, so the question is why that isn't working for you. Have you checked what the journal and the VNC log file say when you try to stop things?

**Comment by davavra** [comment]
Yes everything seems to work until vncserver is called then it just stops and 
never seems to finish. At least never has a process listening for port 59xx.

> Sep 23 03:20:55 fred.dvavra.com systemd[1]: Started Remote desktop service (VNC).
> Sep 23 03:20:58 fred.dvavra.com systemd[1]: vncserver@:5.service: Deactivated successfully.

Something is likely missing between the two systems but it's a rather tedious process looking for it.
