### ISSUE TITLE
Invisible cursor when used with x11vnc

### ISSUE THREAD

**Issue by fottsia** [TigerVNC/tigervnc#1346]
Hi, when students are using tigervnc to view their teacher screens, the teachers mouse cursor is invisible, so the students cannot see where the teachers are focusing or clicking.

To reproduce:
Teacher runs: `x11vnc`
Student runs: `xtigervncviewer teacher-ip` (with or without `-DotWhenNoCursor`)

 - OS: Ubuntu MATE 20.04
 - VNC client:  tigervnc-viewer 1.10.1+dfsg-3
 - VNC server: x11vnc 0.9.16-3

What other viewers do:
- xtightvncviewer: works out of the box
- ssvncviewer: works out of the box
- xvnc4viewer: needs the `-UseLocalCursor=0` parameter, which is not available in tigervnc

**Comment by CendioOssman** [comment]
I'm afraid that is some bug in x11vnc. Their documentation states that it should be providing the cursor as part of the screen updates, so there must be something that isn't working as intended. Please report the issue to x11vnc and they can hopefully have a look at it.

**Comment by robark** [comment]
This can be fixed with the switch -DotWhenNoCursor for xtigervncviewer
