### ISSUE TITLE
Unfortunately this is likely a bug in VirtualBox as it works just fine on real hardware. Judging from your screenshots I would guess the bug has to do with alpha cursors, but old bitmap cursors work just fine.

### ISSUE THREAD

**Issue by hom-mp** [TigerVNC/tigervnc#1351]
Unfortunately this is likely a bug in VirtualBox as it works just fine on real hardware. Judging from your screenshots I would guess the bug has to do with alpha cursors, but old bitmap cursors work just fine.

Could you test the following URL in Firefox inside your VNC session, as well as directly in Windows 10 in the VM:

http://jsfiddle.net/uxto5c3y/2/

When hovering over the black outlined rectangle in the bottom right section you should get a fancy cursor. Please let us know how it looks in different scenarios.

_Originally posted by @CendioOssman in https://github.com/TigerVNC/tigervnc/issues/1088#issuecomment-688772157_

**Comment by CendioOssman** [comment]
Let's continue on #1088.
