### ISSUE TITLE
TigerVNC server keeps disconnecting even with all flags of idle disabled

### ISSUE THREAD

**Issue by caio-vinicius** [TigerVNC/tigervnc#1353]
**Describe the bug**
I have a TigerVNC server running in a ubuntu 20.04 environment that is running very good, but always keep disconnecting with 1 minute of idle time. I already try to use and set all the Xvnc flags for idle to 0:

-IdleTimeout 0 -MaxDisconnectionTime 0 -MaxConnectionTime 0 -MaxIdleTime 0

And even so I keep being disconnected from the server.
Also, I was checking if was not the screensaver that was causing the issue (I'm using Xfce), and disabled it and the problem keeps.

**To Reproduce**
1. Download https://deac-fra.dl.sourceforge.net/project/tigervnc/stable/1.10.1/tigervnc-1.10.1.x86_64.tar.gz
2. Install TigerVNC
3. Initiate "vncserver $DISPLAY -Log *:syslog:100 -IdleTimeout 0 -MaxDisconnectionTime 0 -MaxConnectionTime 0 -MaxIdleTime 0 -depth $VNC_COL_DEPTH -geometry $VNC_RESOLUTION"
4. Connect to it
5. After 1 minute without interaction, the connection is dropped

**Expected behavior**
The connection remain connected without being dropped

**Client (please complete the following information):**
 - OS: Ubuntu 20.04
 - VNC client: Remmina Desktop Client, VNC plugin
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: 1.4.20

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - VNC server: TigerVNC
 - VNC server version: 1.10.1
 - Server downloaded from: https://deac-fra.dl.sourceforge.net/project/tigervnc/stable/1.10.1/tigervnc-1.10.1.x86_64.tar.gz
 - Server was started using: vncserver $DISPLAY -Log *:syslog:100 -IdleTimeout 0 -MaxDisconnectionTime 0 -MaxConnectionTime 0 -MaxIdleTime 0 -depth $VNC_COL_DEPTH -geometry $VNC_RESOLUTION

**Comment by caio-vinicius** [comment]
Tried with 3600 seconds instead of 0, the problem persists.

**Comment by CendioOssman** [comment]
Could you proivde a server log of when this happens? That should show us why the connection is dropped. You should find the log in `~/.vnc`.

I also saw you commenting on #586. Did it help forcing a TCP keep-alive?

**Comment by caio-vinicius** [comment]
Also, find out this issue in kubernetes repository: https://github.com/kubernetes/kubernetes/issues/80298

This is any way could be related to use of IPVS (Linux Virtual Server administration)? 

Output of timeout in ipvsadm
```bash
ipvsadm -l --timeout 
Timeout (tcp tcpfin udp): 900 120 300
```

Output of https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
```bash
cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
cat /proc/sys/net/ipv4/tcp_keepalive_intvl
75
cat /proc/sys/net/ipv4/tcp_keepalive_probes
9
```

Let me know if this question run away of the topic of this discussion, since it's already related to my current environment of running TigerVNC.
