### ISSUE TITLE
Remove Fullscreen mode requirement for passing system keys directly to server

### ISSUE THREAD

**Issue by ercanal** [TigerVNC/tigervnc#1358]
**Is your feature request related to a problem? Please describe.**
Passing system keys directly to server requires to be in fullscreen mode. I don't think, this is a must. 

**Describe the solution you'd like**
Remove fullscreen mode requirement for passing system keys directly to server.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by samhed** [comment]
Agreed, this would be nice.

**Comment by CendioOssman** [comment]
This is discussed on #102.
