### ISSUE TITLE
Connection to Mac OS fails: BufferedInStream overrun requested size of 5197068 bytes exceeds maximum of 4194304 bytes

### ISSUE THREAD

**Issue by darvin** [TigerVNC/tigervnc#1360]
**Describe the bug**f
trying to connect to system built in mac os big sur vnc server using correct login and password

**To Reproduce**
1. launch screenshare on Mac os big sur in settings, note address
2. launch tigervnc latest release on windows on different machine
3. try to connect.

**Expected behavior**
connection

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC client: [e.g. TigerVNC, or UltraVNC]
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]
![TigerVNC Viewer 10_27_2021 7_08_34 AM](https://user-images.githubusercontent.com/309302/139082456-6493c138-3007-46a5-bfab-92730777b9aa.png)

**Server (please complete the following information):**
 -buillt in vnc server of mac os big sur, enabled by checkboxing "screen sharing" in sharing settings

**Comment by adalinesimonian** [comment]
Reproducing this consistently using TigerVNC Viewer 1.12 beta. The connection works when using TightVNC Viewer 2.8.63 as a client.

Server is the built-in Remote Management VNC server in macOS Big Sur 11.6.1

Client is running Windows 11 21H2.

<details>
<summary>Logs:</summary>
<pre>
<code>Tue Nov 02 16:28:11 2021
 Win32TouchHandler: The 'Tablet PC Input' service is required for touch
 Win32TouchHandler: Two touch points required, system currently supports: 0

Tue Nov 02 16:28:13 2021
 DecodeManager: Detected 32 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)

Tue Nov 02 16:28:14 2021
 TcpSocket:   Connecting to Adalines-MacBook-Pro.local
              [fe80::427:55b3:1e98:47b5%21] port 5900
 CConn:       Connected to host Adalines-MacBook-Pro.local port 5900
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.889
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: processing security types message
 CConnection: Server offers security type \[unknown secType](30)
 CConnection: Server offers security type \[unknown secType](33)
 CConnection: Server offers security type \[unknown secType](36)
 CConnection: Server offers security type VncAuth(2)
 CConnection: Server offers security type \[unknown secType](35)
 CConnection: Choosing security type VncAuth(2)
 CConnection: processing security message
 CConnection: processing security message
 Win32TouchHandler: The 'Tablet PC Input' service is required for touch
 Win32TouchHandler: Two touch points required, system currently supports: 0

Tue Nov 02 16:28:15 2021
 CConnection: processing security result message
 CConnection: processing security result message
 CConnection: Authentication success!
 CConnection: reading server initialisation

Tue Nov 02 16:28:16 2021
 CConnection: reading server initialisation
 CConnection: initialisation done
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 Win32TouchHandler: The 'Tablet PC Input' service is required for touch
 Win32TouchHandler: Two touch points required, system currently supports: 0

Tue Nov 02 16:28:18 2021
 CConn:       BufferedInStream overrun: requested size of 7520252 bytes exceeds
              maximum of 4194304 bytes
 Win32TouchHandler: The 'Tablet PC Input' service is required for touch
 Win32TouchHandler: Two touch points required, system currently supports: 0</code>
</pre>
</details>

**Comment by CendioOssman** [comment]
Unfortunately no clues there. The mac I have here is running macOS 12. Any possibility of upgrading your machine and see if that fixes the issue?

**Comment by adalinesimonian** [comment]
Alas, my Mac is just barely too old to be eligible for macOS 12, it's a mid-2014 MBP and Monterey only will install on early 2015 MBPs and later. Any kind of logs or data I could collect, either using the viewer here or another or any other tool, that would be helpful in figuring out what's gone wrong?

**Comment by CendioOssman** [comment]
I've been able to reproduce the issue here. It has to do with the resolution of the monitor. So large high dpi screens will trigger this issue, but not standard resolution monitors.

**Comment by CendioOssman** [comment]
Should be fixed in 479ec11a2ee29a5321a28118c2d69307d752e216. I've also added it to the upcoming 1.12 release.
