### ISSUE TITLE
TigerVNC compiled from source on MacOS M1 has resizing issues

### ISSUE THREAD

**Issue by MatteCarra** [TigerVNC/tigervnc#1365]
**Describe the bug**
I compiled TigerVNC from a M1 Mac (14") with this[brew formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/tiger-vnc.rb).
The image does not fill the screen and has a grey area around, BUT clicks in the grey area of the canvas click the correct (but hidden) portion of the screen.
The screen also does not seem to update correctly when it changes from an other vnc session.
I edited the brew formula to compile 1.11.90 and I had the same issue.
The pre-compiled x86 version that you offer for download does **not** have that issue under Rosetta.

**To Reproduce**
1. brew install tiger-vnc on a M1 Mac
2. Connect to a tiger vnc server

**Screenshots**
<img width="1496" alt="Screenshot 2021-10-31 at 13 14 18" src="https://user-images.githubusercontent.com/11074527/139582687-a0824dcf-8544-4648-b6ed-bd42a3df5b7c.png">

**Client (please complete the following information):**
 - OS: MacOS 12
 - VNC client: TigerVNC
 - VNC client version: both 1.11.0 and 1.11.90
 - Client downloaded from: compiled with brew formula

**Server (please complete the following information):**
 - OS: Linux
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: Manjaro Linux
 - Server was started using: systemd

Config:
```
session=i3-gnome
geometry=3024x1964
x509key=/home/matteo/.vnc/vnc-server-private.pem
x509cert=/home/matteo/.vnc/vnc-server.pem
SecurityTypes=X509Vnc
RawKeyboard
alwaysshared
```

**Comment by CendioOssman** [comment]
I'm afraid that is a packaging issue. Please use the `make dmg` target and it will correctly package the client in way that works.

**Comment by MatteCarra** [comment]
It worked, thanks

**Comment by pwillis-eiq** [comment]
The same problem happened for me; built package with `make dmg`, and vncviewer built, although build then failed with

```
[100%] Built target vncviewer
install: po/bg.mo: No such file or directory
make[3]: *** [release/CMakeFiles/dmg] Error 71
make[2]: *** [release/CMakeFiles/dmg.dir/all] Error 2
make[1]: *** [release/CMakeFiles/dmg.dir/rule] Error 2
```

Same screen as original poster

**Comment by chaosbunker** [comment]
@pwillis-eiq 

somehow the mo files are not generated. i worked around it by downloading the source, running `cmake -DJPEG_INCLUDE_DIR=/opt/homebrew/opt/jpeg-turbo/include -DJPEG_LIBRARY=/opt/homebrew/opt/jpeg-turbo/lib/libjpeg.dylib .`, then navigating into the po directory and running `make` and after that i could compile `make dmg` successfully

**Comment by sydnash** [comment]
> I'm afraid that is a packaging issue. Please use the `make dmg` target and it will correctly package the client in way that works.

why after make dmg,  the tigervnc window will became blur？
this screen is start from make dmg.
<img width="442" alt="image" src="https://github.com/TigerVNC/tigervnc/assets/5484932/c4cdf6a4-bd08-4cc8-ab38-6d29de3f4029">
this screen is start from ./vncviewew/vncviewer, and this will half screen while connect to sever.
<img width="433" alt="image" src="https://github.com/TigerVNC/tigervnc/assets/5484932/80876486-3aec-4845-91be-cf29c7916805">
