### ISSUE TITLE
deb install fails on 1.11 with "update-alternatives: error: alternative vncserver can't be slave of vncsession: it is a master alternative"

### ISSUE THREAD

**Issue by aleqx** [TigerVNC/tigervnc#1368]
Ubuntu 16.04. Trying to install the latest deb (also tried the deb from 1.12beta) fails with
```
$ sudo dpkg -i tigervncserver_1.11.0-1ubuntu1_amd64.deb
tigervncserver_1.11.0-1ubuntu1_amd64.deb   tigervncserver_1.11.90-1ubuntu1_amd64.deb
root@elan:~# dpkg -i tigervncserver_1.11.0-1ubuntu1_amd64.deb
Selecting previously unselected package tigervncserver.
(Reading database ... 511423 files and directories currently installed.)
Preparing to unpack tigervncserver_1.11.0-1ubuntu1_amd64.deb ...
Unpacking tigervncserver (1.11.0-1ubuntu1) ...
Setting up tigervncserver (1.11.0-1ubuntu1) ...
Installing new version of config file /etc/tigervnc/vncserver-config-defaults ...
Installing new version of config file /etc/tigervnc/vncserver-config-mandatory ...
update-alternatives: error: alternative vncserver can't be slave of vncsession: it is a master alternative
dpkg: error processing package tigervncserver (--install):
 subprocess installed post-installation script returned error exit status 2
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 tigervncserver
```

I was trying to upgrade from 1.8 (which did install fine a while ago)

**Comment by CendioOssman** [comment]
I'm afraid I don't have a 16.04 system to test on right now. Does this happen if you remove the old version and install the new one instead of doing an upgrade?

**Comment by aleqx** [comment]
Didn't think of that so I tried it today. It didn't give an error, but it also didn't set the alternative for `vncserver` so services etc fail as they can't find any `vncserver` binary. Output below

```
$ sudo dpkg -i tigervncserver_1.11.0-1ubuntu1_amd64.deb
Selecting previously unselected package tigervncserver.
(Reading database ... 512251 files and directories currently installed.)
Preparing to unpack tigervncserver_1.11.0-1ubuntu1_amd64.deb ...
Unpacking tigervncserver (1.11.0-1ubuntu1) ...
Setting up tigervncserver (1.11.0-1ubuntu1) ...
update-alternatives: using /usr/sbin/tigervncsession to provide /usr/sbin/vncsession (vncsession) in auto mode
update-alternatives: using /usr/bin/Xtigervnc to provide /usr/bin/Xvnc (Xvnc) in auto mode
update-alternatives: using /usr/bin/x0tigervncserver to provide /usr/bin/x0vncserver (x0vncserver) in auto mode
update-alternatives: using /usr/bin/tigervncpasswd to provide /usr/bin/vncpasswd (vncpasswd) in auto mode
```

**Comment by aleqx** [comment]
It seems that setting vncserver as slave to vncsession causes this. This is what changed in 1.11 as opposed to pre-1.10:

excerpt from 1.10 postinst:
```
    update-alternatives --install \
       $BIN/vncserver       vncserver       $BIN/tigervncserver 64 \
       --slave \
       $MAN/vncserver.1.gz  vncserver.1.gz  $MAN/tigervncserver.1.gz
```

excerpt from 1.11 postinst:
```
    update-alternatives --install \
       $SBIN/vncsession          vncsession      $SBIN/tigervncsession 64 \
       --slave \
       $LIB/vncserver            vncserver       $LIB/tigervncserver \
       --slave \
       $MAN/man8/vncsession.8.gz vncsession.8.gz $MAN/man8/tigervncsession.8.gz \
       --slave \
       $MAN/man8/vncserver.8.gz  vncserver.8.gz  $MAN/man8/tigervncserver.8.gz
```

**Comment by CendioOssman** [comment]
The `vncserver` script is gone in 1.11.0 and replaced by the `vncserver@.service` service, so that is expected. I'm afraid you'll have to port your usage over to the new model.

The postinst script is correct for a new install, but it seems it would have needed a cleanup of the old stuff to handle upgrades. Unfortunately we don't build packages for Ubuntu 16.04 anymore so it's too late for any fix there. So the workaround of uninstalling and installing will have to do as the final fix here.

**Comment by aleqx** [comment]
I see. I was wondering why it was using `$LIB` instead of `$BIN`

**Comment by aleqx** [comment]
> I'm afraid you'll have to port your usage over to the new model.

I know I'm going a little offtopic (apologies in advance), but I just gave that a go (edited /etc/tigervnc/tigervnc-users and tigervnc-default-config) with the same options as I used before so that the Xvnc command line is identical to the one I had in 1.10. I get a black screen on 1.11 (started with `systemctl start vncserver@:11001`). Thoughts?

on 1.10
```
# ps afxu|grep [v]nc
EDITED   20816  2.7  0.0 373996 58132 ?        Sl   17:27   0:00 /usr/bin/Xvnc :11001 -geometry 1600x900 -localhost -nolisten tcp -securitytypes none,vncauth,tlsvnc -auth /home/EDITED/.Xauthority -desktop elan:11001 (EDITED) -fp /usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1 -pn -rfbauth /home/EDITED/.vnc/passwd -rfbport 16901 -rfbwait 30000
```

on 1.11
```
root     25974  0.0  0.0      0     0 ?        Z    17:31   0:00  \_ [vncsession] <defunct>
EDITED   25975  0.0  0.0  16060   936 ?        S    17:31   0:00  \_ xinit /etc/X11/Xsession /usr/lib/gnome-flashback/gnome-flashback-compiz -- /usr/bin/Xvnc :11001 -geometry 1600x900 -localhost -nolisten tcp -securitytypes none,vncauth,tlsvnc -auth /home/EDITED/.Xauthority -desktop elan:11001 (EDITED) -fp /usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1 -pn -rfbauth /home/EDITED/.vnc/passwd -rfbport 16901 -rfbwait 30000
EDITED   25980  0.0  0.0 366600 51692 ?        Sl   17:31   0:00      \_ /usr/bin/Xvnc :11001 -geometry 1600x900 -localhost -nolisten tcp -securitytypes none,vncauth,tlsvnc -auth /home/EDITED/.Xauthority -desktop elan:11001 (EDITED) -fp /usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1 -pn -rfbauth /home/EDITED/.vnc/passwd -rfbport 16901 -rfbwait 30000
```

on 1.10 i login, see the desktop, and it all works just fine.

on 1.11 i login, see a black screen with a modal dialog asking me if i want to upgrade the distribution. Adding -verbose 10 didn't show anything peculiar.

Thoughts?

**Comment by aleqx** [comment]
... wait, I'm using xfce, not gnome. I wonder why xinit starts gnome-flashback-compiz

**Comment by CendioOssman** [comment]
No, it uses the system configuration now. So you need to add the setting `session` to control which desktop you want. By default it just picks the first one it finds. Please see the **vncsession** man page for details on the configuration.

**Comment by aleqx** [comment]
I see, thanks. Was this change made because the other VNC server alternatives did the same? They all used to read ~/.vnc/xstartup

**Comment by CendioOssman** [comment]
We are probably the first. This was done because more and more things do not start correctly from a simple script such as xstartup and we had to do something about all the bug reports we got that desktops weren't starting correctly. So we switched to starting the desktops in the same way as what happens when you log on locally.

**Comment by aleqx** [comment]
Thanks, appreciate your time on this
