### ISSUE TITLE
crash with unknown message type 20 when connecting to OS X 10.8.5

### ISSUE THREAD

**Issue by tlatorre-uchicago** [TigerVNC/tigervnc#137]
When I connect to a machine running OS X 10.8.5 the program runs for a while, often when I click another window and then crashes with an unknown message type 20. Here is the last part of the log:

```
Wed Feb 25 14:29:12 2015
 DesktopWindow: selection (1) time is 331671431, later 1
 DesktopWindow: no selection (439)
 DesktopWindow: cut buffer time is 0, later 0
 DesktopWindow: sending primary selection to server
unknown message type 20
 main:        unknown message type
```

I am running CentOS 6.6. I have tested this with version 1.1 of `vncviewer` from the CentOS repositories and version 1.4.2 from bintray.
##

**Comment by CendioOssman** [comment]
That indicates some kind of protocol bug. I assume this is the built-in server in OS X? I'm always cautious about that thing since they've had a history of violating the protocol with it.

**Comment by tlatorre-uchicago** [comment]
Yes, it is the default server.

**Comment by CendioOssman** [comment]
I'm afraid it is unlikely anyone will be looking at this problem in that case. The extensions and hacks in Apple's fork of VNC are not documented and well known.

**Comment by CendioOssman** [comment]
This doesn't seem to happen in current versions of macOS, so I'm assuming Apple has fixed this bug.
