### ISSUE TITLE
Xvnc v1.12.x can no longer listen on -rfbunixpath only

### ISSUE THREAD

**Issue by s53g4z** [TigerVNC/tigervnc#1374]
**Describe the bug**
Xvnc v1.11.x was able to listen only on a Unix domain socket (rather than IPv* sockets). Xvnc v1.12.x loses this ability and emits the error message `(EE) vncExtInit: createTcpListeners: no addresses available: Cannot assign requested address (99)` when Unix domain socket listening only is requested of the program.

**To Reproduce**
1. Run `Xvnc -rfbunixpath /tmp/test_vnc -UseIPv4=0 -UseIPv6=0 :2222`
2. Observe that Xvnc exits with an error.

**Expected behavior**
The v1.11.x behavior is expected where configuration of Xvnc to listen solely on a Unix domain socket is possible.

**Client (please complete the following information):**
 - OS: Arch Linux
 - VNC client: N/A
 - VNC client version: 1.12.0
 - Client downloaded from: my Linux distribution software repositories via `pacman`

**Server (please complete the following information):**
 - OS: Arch Linux
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: my Linux distribution software repositories via `pacman`
 - Server was started using: `Xvnc -rfbunixpath /tmp/test_vnc -UseIPv4=0 -UseIPv6=0 :2222`

**Additional context**
This bug is a regression since older versions of Xvnc do not exhibit the incorrect behavior.

**Comment by CendioOssman** [comment]
The behaviour here was changed to allow people to use both methods at the same time. You need to explicitly disable TCP by specifying `-rfbport=-1` if you only wish to have a Unix socket.
