### ISSUE TITLE
VNC session not running .bash_profile

### ISSUE THREAD

**Issue by sproott** [TigerVNC/tigervnc#1376]
**Describe the bug**
When connecting remotely to the VNC server, .bash_profile does not get run.

**To Reproduce**
1. Install Arch Linux with some DE (tested on Awesome WM and Gnome, the problem happens on both)
2. Install the `tigervnc` package
3. Add something to .bash_profile (e.g. a PATH variable modification) 
4. Start the VNC server via the systemd service
5. Connect to it

**Expected behavior**
The .bash_profile file should run and the PATH variable should get modified

**Client:**
 - OS: Arch Linux
 - VNC client: TigerVNC
 - VNC client version: 1.12.0
 - Client downloaded from: Arch package repository

**Server:**
 - OS: Arch Linux
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: Arch package repository
 - Server was started using: `vncserver` systemd service

**Comment by CendioOssman** [comment]
That should be handled by your system, not TigerVNC. So it sounds like something is off there. On Red Hat systems this is handled by `/etc/X11/xinit/Xsession` which does:

```
exec $CK_XINIT_SESSION $SSH_AGENT /bin/sh -c "exec -l $SHELL -c \"$1\""
```

I'm not familiar with Arch unfortunately, but it should have something similar. Do you have that file? And some line that includes `exec -l`?

**Comment by sproott** [comment]
I looked at the way Xsession is handled by the Arch package. It ships its own custom Xsession, which doesn't include the line you mentioned. After adding it to the Xsession file, it indeed works properly. So the next course of action will be probably to somehow report it to the package maintainer, which I'm not sure how to do.

**Comment by CendioOssman** [comment]
I'm afraid I don't know either, but I assume Arch has some form of issue tracker for people to report bugs.

Since this is something custom for Arch, I'm afraid there isn't anything else we can help you with.

Please update this issue though if you're able to report the issue to Arch. It will help other users if they encounter the same problem.
