### ISSUE TITLE
Linux viewer (Ubuntu) does not pass mapped Caps Lock

### ISSUE THREAD

**Issue by timkgh** [TigerVNC/tigervnc#1379]
**Describe the bug**
TigerVNC viewer 1.11.0 running on Ubuntu 21.10
I like to map Caps Lock to be another Ctrl key, but the viewer does not send it as Ctrl to the server, it sends it as CapsLock and things like Ctrl+S end up as Ctrl+Shift+S

I also use the same viewer on macOS where I also map Caps Lock to Ctrl and it seems to behave correctly. Is there any way to get this behavior on Linux also?

**To Reproduce**
See above description
Map CapsLock to be another Ctrl via the Tweaks tool in Ubuntu/Gnome 3.

**Expected behavior**
Mapped CapsLock should pass the mapped key, I believe that's the reasonable expectation of any user.

**Client (please complete the following information):**
 - OS: [e.g. Windows 8.1] Ubuntu 21.10
 - VNC client: [e.g. TigerVNC, or UltraVNC] TigerVNC 1.11.0
 - VNC client version: [e.g. 1.8.0] 1.11.0
 - Client downloaded from: [e.g. my Linux distribution] Ubuntu

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1] Arch Linux
 - VNC server: [e.g. TigerVNC, or UltraVNC] TigerVNC 1.11.0
 - VNC server version: [e.g. 1.8.0] 1.11.0
 - Server downloaded from: [e.g. my Linux distribution] Arch
 - Server was started using: [e.g. `vncserver`] systemd

**Additional context**
macOS seems to have the desired behavior, please don't break it to make it consistent with the Linux behavior :)

**Comment by CendioOssman** [comment]
Hmm... That should be respected by the client. Could you enable debug logs on the client and server so we can see the details of what is communicated? Instructions here:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs

**Comment by timkgh** [comment]
FWIW, Remmina, Vinagre behave the same way. I'm mapping CapsLock to Ctrl via the Tweaks tool in Ubuntu/Gnome 3, maybe that's why and I may need to do it in a different way (xmodmap?). I also have `XKBOPTIONS="ctrl:nocaps"` in `/etc/default/keyboard` but that doesn't help either.

I will enable debug and report back.

**Comment by timkgh** [comment]
Fixed it!

In Tweaks I switched from:
`Caps Lock behavior: Caps Lock is also Ctrl`
to
`Caps Lock behavior: Disabled`
`Ctrl position: Caps Lock as Ctrl`

gsettings now reports this:
```
> gsettings get org.gnome.desktop.input-sources xkb-options
['altwin:prtsc_rwin', 'terminate:ctrl_alt_bksp', 'ctrl:nocaps']
```

This fixes TigerVNC, Remmina and Vinagre.

**Comment by timkgh** [comment]
Now only if I can get scaling in the Linux client :-)

https://github.com/TigerVNC/tigervnc/issues/369#issuecomment-974693129

Somehow I find the combo TigerVNC server+client to have the best performance and quality, not sure what makes it so special, but now I'm hitting this HiDPI issue on the client side.

**Comment by CendioOssman** [comment]
Ah, that explains it. Seems like TigerVNC was doing the right thing and the XKB settings were just confusingly described. :)
