### ISSUE TITLE
Support xorg-server 21.x

### ISSUE THREAD

**Issue by paulmenzel** [TigerVNC/tigervnc#1384]
[X server 21.1.0 was released in Octobor 2021,](https://lists.x.org/archives/xorg/2021-October/060799.html), and [X server 21.1.1 at the beginning of November 2021](https://lists.x.org/archives/xorg/2021-November/060806.html).

It’d be great if a patch file for that version could be provided.

```
patching file configure.ac
Hunk #1 succeeded at 72 (offset -2 lines).
Hunk #2 succeeded at 1714 (offset -64 lines).
Hunk #3 succeeded at 1753 with fuzz 2 (offset -64 lines).
Hunk #4 succeeded at 1963 (offset -73 lines).
Hunk #5 succeeded at 2345 with fuzz 1 (offset -226 lines).
patching file hw/Makefile.am
Hunk #1 FAILED at 38.
1 out of 1 hunk FAILED -- saving rejects to file hw/Makefile.am.rej
patching file mi/miinitext.c
Hunk #1 succeeded at 106 with fuzz 2 (offset -1 lines).
```

**Comment by CendioOssman** [comment]
This was just fixed via #1383. :)

**Comment by paulmenzel** [comment]
Awesome, you are the best!

**Comment by leahneukirchen** [comment]
Can you please tag a release for this? Downstream distros will be thankful.
