### ISSUE TITLE
Allow to start VNC server as unprivileged user

### ISSUE THREAD

**Issue by paulmenzel** [TigerVNC/tigervnc#1385]
https://github.com/TigerVNC/tigervnc/blob/0c5a2b2e7759c2829c07186cfce4d24aa9b5274e/unix/vncserver/HOWTO.md?plain=1#L1-L11

Does that mean, since TigerVNC 1.10.0 it’s not possible anymore to easily start the VNC server as an unprivileged user? If so, could you provide systemd *user* service units to do the same. What privileged rights are needed since version 1.10.0?

**Comment by CendioOssman** [comment]
I'm afraid we're not aware of any unprivileged way of starting sessions. You need to have the rights with systemd to initiate new user sessions. The two methods I'm aware of is via PAM or machinectl, both require privilege. User services run under the user's slice, but they cannot start new sessions.

So until someone finds some other way, or systemd provides something new, then I'm afraid this won't change. :/
Until then I would suggest looking at using sudo in some way. It can be locked down pretty well, e.g. by only executing a script that only starts the things you want to entrust users.
