### ISSUE TITLE
hope it will not automatically scale the program interface according to the windows scale

### ISSUE THREAD

**Issue by whoyz** [TigerVNC/tigervnc#1392]
I would like to be able to not automatically scale the application interface according to the windows scaling.
I am now using windows system will set the scaling to 200%. windows system set the scaling will cause the remote vnc session interface will also be very roughly zoomed, thus causing the interface to be blurred.
Now I can only set the dpi scaling compatibility option of the application for the application in advance.

Comparison of the interface after the two settings：

![image](https://user-images.githubusercontent.com/32080977/145583674-f245b9e4-dd1f-49a0-b3de-d77d46496b0d.png)

![image](https://user-images.githubusercontent.com/32080977/145584549-f7e9898d-9474-4c2a-970a-23437c0b3d47.png)

![image](https://user-images.githubusercontent.com/32080977/145584941-07c32bd9-b629-476c-98fb-08cf47ee4d0b.png)

**Comment by CendioOssman** [comment]
Please see #369.
