### ISSUE TITLE
Greek and Cyrillic keyboards don't work on macOS

### ISSUE THREAD

**Issue by CendioOssman** [TigerVNC/tigervnc#1396]
**Describe the bug**
TigerVNC currently refuses to use non-Latin keyboard layouts on macOS. This is partly intended, partly unintended. The goal was to ignore layouts that use input methods, but there are non-Latin layouts that also get caught up in this, prominently Greek and Cyrillic layouts.

**To Reproduce**
1. Configure Greek or Russian keyboard layout
2. Start TigerVNC and connect

**Expected behavior**
The Greek or Russian keyboard layout is still active instead of switching to a Latin layout.

**Client (please complete the following information):**
 - OS: macOS 12
 - VNC client: TigerVNC
 - VNC client version: 1.12.0
 - Client downloaded from: Own build

**Server (please complete the following information):**
 - OS: Linux
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: Own build
 - Server was started using: Just Xvnc

**Additional context**
This is really a bug in FLTK as the magic for this is in there.

**Comment by CendioOssman** [comment]
@bphinz, does FLTK on your build machine include this fix? If so then we can close this.

**Comment by bphinz** [comment]
I had to modify the patch a little bit in order to apply it against 1.3.8
but it's fine as far as I can tell.  Can you please test the latest nightly
build and confirm?

**Comment by bphinz** [comment]
I don't think so, but I will check tonight and add if not.

**Comment by CendioOssman** [comment]
Sorry for the delay. I've tested it here and can confirm that this works in the nightly builds, but not in 1.12.0. :)
