### ISSUE TITLE
x0vncserver - Could not map key event to X11 key code

### ISSUE THREAD

**Issue by aerinmiller** [TigerVNC/tigervnc#1400]
Having the same issue as #1224.

RawKeyboard does not work. After an update I only did because unicode wasn't copy/pasting correctly, now I'm not getting ANY characters when I switch my physical keyboard to Arabic and start typing. Before the update I at least could type in Arabic, now even that isn't working.

My current version of tigervnc is 1.12.0, the newest release. I'm on Ubuntu 20.04 as well. 

Changing my remote locale entirely, logging back in, and trying to paste Arabic still does not work.

_Originally posted by @aerinmiller in https://github.com/TigerVNC/tigervnc/issues/1224#issuecomment-1000960411_

**Comment by CendioOssman** [comment]
Please fill out the bug template so we get the basic details of your setup.

**Comment by CendioOssman** [comment]
No response. Closing.
