### ISSUE TITLE
XDG_CURRENT_DESKTOP should be set

### ISSUE THREAD

**Issue by code0815** [TigerVNC/tigervnc#1404]
Problem:
I'm currently using your Tigervnc 1.12 package on Ubuntu 20.04 LTS. If I log into the VNC session the Ubuntu desktop does look like the default Gnome desktop and not like the Ubuntu-Gnome desktop. Have a look at [https://github.com/TigerVNC/tigervnc/issues/1168#issuecomment-752994435](https://github.com/TigerVNC/tigervnc/issues/1168#issuecomment-752994435) to see what the difference is. This does happen even if I set the $session variable inside **~/.vnc/config**.

The reason for that is, that tigervnc does not set the XDG_CURRENT_DESKTOP variable. So inside a VNC session the variable seems to drop back to a default of "GNOME" (I do not know, where this default value is set yet):
`XDG_CURRENT_DESKTOP=GNOME`

If I log in locally though GDM I do get get "ubuntu:GNOME" instead:
`XDG_CURRENT_DESKTOP=ubuntu:GNOME`

The XDG_CURRENT_DESKTOP variable is set through GDM session usually. You'll find it inside **gdm-session.c** file inside the GDM source code. As far as I understand (I'm not a programmer and I've just basic skill in reading code) the variable is assembled from desktop group (GNOME) and desktop name (ubuntu).

Furthermore you'll find a lot of matches, if you grep for XDG_CURRENT_DESKTOP on an Ubuntu system. It is used/looked-up by **xdg-open** and others. So it seems to me, that it is a more important variable for the Ubuntu desktop environment and probably for other Gnome desktop environments, too. So I could imagine, that there are more glitches than the one I did describe at the beginning, if XDG_CURRENT_DESKTOP is not set correctly.

So I think you should set the XDG_CURRENT_DESKTOP somewhere inside your code like you're doing for DESKTOP_SESSION, GDM_SESSION and XDG_SESSION_DESKTOP already, because loading a session through tigervnc does replace loading the session through GDM (as far as I understand). So tigervnc code should set all the things, that are set by GDM usually, shouldn't it?

As a workaround for now, I can set the XDG_CURRENT_DESKTOP myself inside the **~/.xsessionrc** file using
`export XDG_CURRENT_DESKTOP=ubuntu:GNOME`

The VNC session will look the same, like a local session then.

But I would expect, if I configure the "$session" variable inside of one of the tigervnc config files, that I would not have to hack around setting the basic desktop environment variables - unless I would have an extraordinary desktop set-up (which I do not have).

Thanks in advance!

**Comment by CendioOssman** [comment]
Doh! I apparently had a brain fart in 537a39373cd0bb1867101d5adb07621c17fd0d97 and used the wrong name. Fixed in 6c9a9cba2ed6f97c96856620aa59f3708bba3037.
