### ISSUE TITLE
Parameters:  Unknown parameter via on line 26 in file /Users/user/.vnc/default.tigervnc

### ISSUE THREAD

**Issue by hbergh** [TigerVNC/tigervnc#1406]
I would like to specify the via parameter in a tigervnc config file, but the macOS TigerVNC Viewer (v1.11.0) doesn't recognize this parameter. I get the error message reported in the subject. It looks like there are other parameters that are not recognized, such as passwd/PasswordFile. I haven't tried all parameters, there may be others that are missing.

**Comment by CendioOssman** [comment]
Right now it only supports those parameters that can be changed via the UI. Please see #398 for improving this.
