### ISSUE TITLE
TigerVNC Java connection timeout is too short

### ISSUE THREAD

**Issue by pdlan** [TigerVNC/tigervnc#1414]
**Describe the bug**
TigerVNC Java version has a fixed connection timeout of 250ms, which is too short in some cases.

**To Reproduce**
Connect to a server using TigerVNC Java version in poor network condition.

**Expected behavior**
Set a longer timeout (at least 1s, I think) or use an adjustable timeout.

**Comment by pdlan** [comment]
FYI, I need to connect to a server in east asia from US. Ping can reach about 300ms, which makes me constantly fail to connect to it with TIgerVNC Java.

**Comment by CendioOssman** [comment]
250 ms sounds absurdly low. Normal TCP connection timeout is in the order of minutes.

**Comment by bphinz** [comment]
I've increased the timeout to 3 seconds
