### ISSUE TITLE
Black/grey screen on connection without errors in log

### ISSUE THREAD

**Issue by martinsson** [TigerVNC/tigervnc#1416]
**Describe the bug**
Connecting a client to the server gives a black screen on both fedora:31 and amazon-linux-2

I do get prompted with login and the connection establishes, as I can see in the server log. 
However the screen remains grey with message "an error occurred" or black.

I get the grey screen when I use a dedicated vnc user, and the grey when I configure a dedicated vnc user.
I'm not logged in as the user while trying to connect.

I've spent quite some time and I don't understand what I'm doing wrong. I sure could use some help

**To Reproduce**
1. Followed instructions on https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/infrastructure-services/TigerVNC/
2. Connect using tigervnc client (or screen sharing app on macos)

**Expected behavior**
UI displayed

**Screenshots**
<img width="1028" alt="vnc black screen" src="https://user-images.githubusercontent.com/182208/150678206-d01dc99a-1044-4ffe-a91a-79c59184aed0.png">
<img width="1022" alt="vnc grey screen" src="https://user-images.githubusercontent.com/182208/150678208-d1189dbb-da86-4295-9b98-c55046dbe5e3.png">

**Client (please complete the following information):**
 - OS: macos big sur
 - VNC client: TigerVNC
 - VNC client version: 1.12.0
 - Client downloaded from: brew

**Server (please complete the following information):**
 - OS: fedora:31/amazon-linux-2
 - VNC server: TigerVNC 
 - VNC server version: 1.10.1
 - Server downloaded from: fedora
 - Server was started using: systemctl

**Additional context**
Content of logfile 
```
...skipping...

Xvnc TigerVNC 1.10.0 - built Apr 19 2020 00:00:00
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12006000, The X.Org Foundation


Sun Jan 23 13:31:52 2022
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0

Sun Jan 23 13:31:53 2022
 Connections: accepted: 192.168.5.221::60498
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type TLSVnc (258)

Sun Jan 23 13:31:55 2022
 SConnection: AuthFailureException: Authentication failure
 VNCSConnST:  closing 192.168.5.221::60498: Authentication failure:
              Authentication failure
 EncodeManager: Framebuffer updates: 0
 EncodeManager:   Total: 0 rects, 0 pixels
 EncodeManager:          0 B (1:-nan ratio)
 TLS:         TLS session wasn't terminated gracefully
 Connections: closed: 192.168.5.221::60498
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)

Sun Jan 23 13:31:58 2022
 Connections: accepted: 192.168.5.221::60504
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type TLSVnc (258)

Sun Jan 23 13:32:00 2022
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
```

**Comment by CendioOssman** [comment]
I'm afraid that old version is not something we can support. Please file a request with Fedora or Amazon and see if they can help you out.

Current versions of TigerVNC uses a different setup in order to avoid issues like this. So if you can, please try that and see if it works better.

@grulja, it looks like someone needs to update the Fedora documentation as that guide is no longer correct.

**Comment by grulja** [comment]
> I'm afraid that old version is not something we can support. Please file a request with Fedora or Amazon and see if they can help you out.
> 

Fedora 31 is already not supported. Currently supported Fedora versions are Fedora 34 and Fedora 35.

> Current versions of TigerVNC uses a different setup in order to avoid issues like this. So if you can, please try that and see if it works better.
> 
> @grulja, it looks like someone needs to update the Fedora documentation as that guide is no longer correct.

I'll look into that. Thanks.

**Comment by martinsson** [comment]
Sorry about the old version of fedora. It was just a second version I tried. As mentioned above I tried this using amazon linux 2 as well. To be more precise, I'm using this version

```
5.10.82-83.359.amzn2.x86_64
```

I set this up using [this documentation](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-linux-2-install-gui/) from aws


I also upgraded the fedora to 35 and tried a few things. Is the procedure for fedora not up to date you say?  https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/infrastructure-services/TigerVNC/

Reading the output of the systemctl command there seems to be a problem with permissions:

```
 vncserver@:3.service: Can't convert PID files /home/myvnc/.vnc/localhost.localdomain:3.pid O_PATH file descriptor to proper file descriptor: Permission denied
```

However there are no change even if I add permissions to this file.

Is there a distribution of linux that is easier to set up with tigervnc? Any distribution would work fine for me.

**Comment by CendioOssman** [comment]
Those instructions for Amazon are probably correct given that version of TigerVNC. However that old version was unreliable, so we do not support it. Amazon should though, since they still include it. So a support issue with them would be the best way forward.

> I also upgraded the fedora to 35 and tried a few things. Is the procedure for fedora not up to date you say?

I'm afraid so. Someone must have missed that in the upgrade to TigerVNC 1.11. Please see `/usr/share/doc/tigervnc/HOWTO.md` on your Fedora system instead.

**Comment by martinsson** [comment]
OK the Readme will be perfect
