### ISSUE TITLE
[x0vncserver] Clipboard events don't work anymore (past commit removed needed command line arguments)

### ISSUE THREAD

**Issue by gima** [TigerVNC/tigervnc#1420]
**Describe the bug**

Flags necessary to enable clipboard functionality with `x0vncserver` have been removed, even though the feature worked fine when I previously used this.

**To Reproduce**
Add `-SendCutText=on -AcceptCutText=on` to `x0vncserver` command line arguments

**Expected behavior**
`x0vncserver` starts, accepts connections, and conveys clipboard events to and from connected host.

**Observer behavior**
`x0vncserver` quits and displays usage help, as it didn't understand some of the provided command line arguments.

**Screenshots**
Not Applicable

**Client (please complete the following information):**
<details>
  <summary>Not Applicable, as this is a `x0vncserver` problem.</summary>

- OS: Arch Linux
- VNC client: Remmina
- VNC client version: 1:1.4.23-3
- Client downloaded from: Arch's own repos
</details>

**Server (please complete the following information):**
 - OS: Arch Linux
 - VNC server: tigervnc; x0vncserver
 - VNC server version: 1.12.0-1
 - Server downloaded from: Arch's own repos; https://archlinux.org/packages/community/x86_64/tigervnc/
 - Server was started using: `x0vncserver -Log '*:stderr:100' -localhost -display :0 -SecurityTypes=none -SendCutText=on -AcceptCutText=on -AlwaysShared=on`

**Additional context**
Commit where these flags were removed, claiming that the functionality was not implemented:
> **Don't list clipboard parameters for x0vncserver**
> Better to just hide these parameters rather than stating that they are unused in the man page.
>
> Commit: 17aee6306628a4b949afb4aa9cc950507daaf2f6

**Comment by CendioOssman** [comment]
That must have been some placebo effect as there has never been any clipboard code in x0vncserver. See #529.

**Comment by gima** [comment]
Hmm. I managed my way with `x11vnc` without any additional parameters. It's been a while since the last time, so must have mixed these up. Sorry.

**Comment by CendioOssman** [comment]
No worries. :)
