### ISSUE TITLE
Add package for debian bullseye

### ISSUE THREAD

**Issue by andrewchen5678** [TigerVNC/tigervnc#1421]
Can we have a .deb package for debian bullseye? I tried the ubuntu 20.04 package but it says Dependency is not satisfiable: libjpeg-turbo8.

**Comment by CendioOssman** [comment]
Debian already includes TigerVNC so you should be able to get it from your normal repos. We try to avoid getting involved in packaging as it's not our expertise and it takes time away from working on TigerVNC itself.
