### ISSUE TITLE
[Ubuntu_18.04/Mint_19.3] tigervncserver 1.3.10-0ubuntu4 error - vncserver: couldn't find "/usr/local/bin/Xvnc" - resolved by "sudo ln -s /usr/bin/Xvnc /usr/local/bin/Xvnc"

### ISSUE THREAD

**Issue by mikebdp2** [TigerVNC/tigervnc#1424]
Using a freshly-installed tigervncserver 1.3.10-0ubuntu4 on Ubuntu_18.04/Mint_19.3 , trying to launch a vncserver command results in:

`vncserver: couldn't find "/usr/local/bin/Xvnc"`

This is easily resolved by creating a symbolic link from `/usr/local/bin/Xvnc` to `/usr/bin/Xvnc` :

`sudo ln -s /usr/bin/Xvnc /usr/local/bin/Xvnc`

Probably this is a packaging bug, but reporting it also here just in case

**Comment by CendioOssman** [comment]
It seems like that package is built incorrectly. Where did you download it?

**Comment by bphinz** [comment]
Based on the version number, I'd say that's tightvnc rather than tigervnc:

https://packages.ubuntu.com/bionic/tightvncserver

**Comment by CendioOssman** [comment]
Ah. Well spotted. We've never had a 1.3.10 release. So I'm afraid you'll have to report this to Ubuntu, @mikebdp2.
