### ISSUE TITLE
VNC Viewer launches in unexpected language on Mac OS

### ISSUE THREAD

**Issue by DrLex0** [TigerVNC/tigervnc#1427]
**Describe the bug**
TigerVNC Viewer launches in my least preferred system language.

**To Reproduce**
1. In Language & Region system settings, set languages in this order:
   1. English (UK)
   2. English
   3. 简体中文 (Simplified Chinese)
   4. Nederlands (Dutch, Belgium)
2. Launch TigerVNC Viewer

**Expected behavior**
It should launch in the first preferred language it supports.
It is plausible that there is no UK-specific English translation, but then it should pick the generic English one (I have also tried adding US English as second language but it made no difference). I do find a zh_CN folder in the application bundle, but for some reason it still prefers the last language in my list.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/16401844/153380213-1ccc2317-9c91-4c77-939d-23c27b04d5fc.jpg)

**Client (please complete the following information):**
 - OS: Mac OS 10.14.6
 - VNC client: TigerVNC Viewer
 - VNC client version: 1.12.0
 - Client downloaded from: SourceForge

**Server (please complete the following information):**
 Irrelevant

**Comment by CendioOssman** [comment]
Please see #1381. This should be fixed if you try a nightly build, and will also be included in the next stable release.
