### ISSUE TITLE
Language settings in TigerVNC

### ISSUE THREAD

**Issue by yulychan** [TigerVNC/tigervnc#1428]
I just downloaded the latest version of TigerVNC for Mac TigerVNC-1.12.0.dmg: (https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/TigerVNC-1.12.0.dmg/download) and my login window appears in Spanish. Anyone else having this issue with the Mac version?

**Comment by samhed** [comment]
This was a bug in a build dependency of TigerVNC, see #1381. It is fixed in the nightly builds but not in the 1.12.0 release.
