### ISSUE TITLE
get_rects() crash when using Intel VTune

### ISSUE THREAD

**Issue by msijka** [TigerVNC/tigervnc#1429]
Xvnc crashes quite frequently when using TigerVNC 1.9.0 on Centos 8 x64 with a Intel VTune). The client is TigerVNC  Viewer 1.10.1 on windows 10.  It takes a couple of minutes to happen, seems related to clicking on things and resizing.

`Core was generated by `/usr/bin/Xvnc :3 -auth /home/cyc/.Xauthority -desktop spiceinit28-u32-mgmt.hop.'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fb8485448df in raise () from /usr/lib64/libc.so.6
[Current thread is 1 (Thread 0x7fb84b56eb40 (LWP 3294))]
Missing separate debuginfos, use: yum debuginfo-install tigervnc-server-minimal-1.9.0-14.el8_1.x86_64
(gdb) bt
#0  0x00007fb8485448df in raise () from /usr/lib64/libc.so.6
#1  0x00007fb84852ecf5 in abort () from /usr/lib64/libc.so.6
#2  0x000055f5c17e0830 in OsAbort ()
#3  0x000055f5c17e5389 in AbortServer ()
#4  0x000055f5c17e61fd in FatalError ()
#5  0x000055f5c17ddb35 in OsSigHandler ()
#6  <signal handler called>
#7  0x000055f5c174af87 in rfb::Region::get_rects(std::vector<rfb::Rect, std::allocator<rfb::Rect> >*, bool, bool, int) const ()
#8  0x000055f5c174f70f in rfb::ComparingUpdateTracker::compare() ()
#9  0x000055f5c174da22 in rfb::VNCServerST::writeUpdate() ()
#10 0x000055f5c174dc9a in rfb::VNCServerST::handleTimeout(rfb::Timer*) ()
#11 0x000055f5c174b80d in rfb::Timer::checkTimeouts() ()
#12 0x000055f5c174bf61 in rfb::VNCServerST::checkTimeouts() ()
#13 0x000055f5c173e72d in XserverDesktop::blockHandler(int*) ()
#14 0x000055f5c1733071 in vncCallBlockHandlers ()
#15 0x000055f5c178ea80 in BlockHandler ()
#16 0x000055f5c17d7f49 in WaitForSomething ()
#17 0x000055f5c1789e0b in Dispatch ()
#18 0x000055f5c178e0e6 in dix_main ()
#19 0x00007fb848530873 in __libc_start_main () from /usr/lib64/libc.so.6
#20 0x000055f5c1661e6e in _start ()
`

This seems very similar to https://github.com/TigerVNC/tigervnc/issues/237

**Comment by CendioOssman** [comment]
I'm afraid that version is too old for us to help you with. Please try a later version, or report the issue to Red Hat and see if they can have a look at it.
