### ISSUE TITLE
Please add back ability to start vncserver directly 

### ISSUE THREAD

**Issue by arvidjaar** [TigerVNC/tigervnc#1432]
**Is your feature request related to a problem? Please describe.**
For years my primary use case was to ssh into a remote system and start vncserver manually if GUI was needed. It seems that since version 1.12 this possibility was removed and one can only connect to predefined VNC instances.

**Describe the solution you'd like**
Keep ability to manually run vncserver on demand in addition to central systemd activation.

**Describe alternatives you've considered**
While it's still possible to manually start Xvnc and even use /usr/libexec/vncserver (which works when started manually) it is very user unfriendly because

- vncserver is no more in PATH
- vncserver no more does auto-selection of available X server address
- started Xvnc runs in foreground
- no convenient way to stop started Xvnc (`vncserver -kill`)

Please keep old vncserver script for compatibility for those who successfully used it and do not need additional features.

**Comment by bigntallmike** [comment]
Agreed.  I use this functionality all the time on headless systems to run one-time GUI installers.  I have no need for long-running vnc services and in fact would prefer *not* to run them.  vncserver is the fast and easy way to get a GUI on a remote server box.

**Comment by CendioOssman** [comment]
I'm afraid that isn't feasible. We need to clearly convey what we support and what we don't support. And the clearest way is in choosing what we include in our packages or not. And I'm afraid we haven't found a way to do what you want that works reliably enough that we can support it.

The old `vncserver` script was just a single file. So if that works for you then feel free to keep a copy around and continue using it. It is just no longer included under the TigerVNC umbrella.
