### ISSUE TITLE
xtigervncviewer temporarily freezes entire X11 UI on startup (using xmonad window manager)

### ISSUE THREAD

**Issue by afcady** [TigerVNC/tigervnc#1433]
**Describe the bug**
When first starting up, after displaying the remote screen, the entire X GUI is frozen (unresponsive to clicks and keyboard, but still shows mouse pointer movement) for some number of seconds.

I think it has to do with the popup notification that talks about the F8 escape key.  It appears that, during the F8 notification, the GUI is locked up.

It is possibly related to the use of the `xmonad` window manager on the client side.

I might try disabling this notification in the source to see if it fixes the issue.

First I will try timing the lockup to see if it's consistent.

**To Reproduce**

1. Launch local X server with `xmonad` as WM.
2. Open any window e.g. an xterm.
3. Connect to a remote VNC server using `xtigervncviewer`.
4. Try to switch windows by clicking on another window or pressing `mod-tab`.
5. Witness that neither works.  Nor does the remote side respond to clicks or keypresses during this time.

**Expected behavior**
Immediate responsiveness.

**Client (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - VNC client: tigervnc-viewer
 - VNC client version: 1.11.0+dfsg-2
 - Client downloaded from: Debian

**Server (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - VNC server: x11vnc
 - VNC server version: 0.9.13-6+deb10u1
 - Server downloaded from: Debian
 - Server was started using: x11vnc -noxrecord -nopw -ncache -ncache_cr -localhost -display :0

**Comment by afcady** [comment]
Wow I just posted this and go to time it, and now I can't reproduce the bug at all!  WTF?  It was totally consistent until I filed a report =D.

Leaving this bug up here because, still, something is wrong.  It's just not so simple as what I said up there!

**Comment by afcady** [comment]
The freezing came back and I was able to confirm with three tests in a row that the lockup lasts 15 seconds.

I used the stopwatch function my phone.  I started the timer when I saw the `xtigervncviewer` window pop up.  I then middle-clicked on the `xtigervncviewer` window to close it.  I stopped the time when the window was removed from the screen.  The delay was always 15 seconds.

If the notification is 15 seconds long, then I think this implies it is the notification.

Sometimes, there's no lockup at all.

Anyway I have a hunch that the notification time is 15 seconds.

**Comment by CendioOssman** [comment]
The overlay is up for just 4 seconds, so that doesn't match. It is also not blocking in any way.

Just to make things clear, is everything unresponsive on your client when you do this? Or do other applications continue to work?

Is vncviewer responsive to pressing F8? Or closing it?

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by afcady** [comment]
Sorry I didn't get back to this. I stopped using xtigervncviewer and switched to xtightvncviewer so I didn't continue debugging this.   For the record, everything was unresponsive.  Well, applications than xmonad weren't visible, but xmonad was unresponsive either to mouse or keyboard.

Eventually I'll probably try tiger again and see if I can reproduce this again, again sorry for the delay.
