### ISSUE TITLE
An official dmg for M1

### ISSUE THREAD

**Issue by twhitehead** [TigerVNC/tigervnc#1434]
From #1365 it sounds like it is possible to build a MacOS M1 version.

It would be great if the official MacOS binaries could provide a M1 dmg (assuming it isn't some sort of fat binary already). Thanks!

**Comment by CendioOssman** [comment]
Rosetta seems to be working fine, so we have no major functional need for this. So I'd say this is a bonus.

@bphinz, is this possible in your build environment?

We should also see if we can get our GitHub actions to build for M1 as well.

**Comment by bphinz** [comment]
Unfortunately I don't have any M1 hardware yet. I looked into
cross-compiling and making a universal binary but that seems to be quite
involved

**Comment by twhitehead** [comment]
Maybe best to just leave this for the future then until M1 hardware is more common?

Thanks very much for looking into it.

**Comment by eszense** [comment]
Unfortunately Rosetta seems to be not working fine in my case.

I use TigerVNC on regular basis with M1. It usually works, but always crashes when I click on the Options button. Error message as below, I assume segmentation fault is related to architecture problem.

```TigerVNC Viewer 64-bit v1.12.0
Built on: 2021-11-10 03:52
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
zsh: segmentation fault  "/Applications/TigerVNC Viewer 1.12.0.app/Contents/MacOS/TigerVNC Viewer"
```

There are also freezes here and there (e.g. after the M1 wake from sleep), which I am not sure if it is an M1 issue or a general MacOS version issue.

**Comment by CendioOssman** [comment]
That's actually just a plain ol' bug. Please see #1423. The nightly builds have a fix in place for that.

@bphinz, I suppose cross compilation will need to be sorted at some point since x86 and ARM will likely coexist for a while. Unless you want to have two build machines. :)

**Comment by caparomula** [comment]
I tried 1.12.0 built natively (via homebrew) as well as run via Rosetta on my Mac Studio.  Both exhibited discernible lag of the sort that would not be a problem for casual use, but which is very distracting when trying to get actual work done. I had been using the native intel viewer on both Windows and linux clients to connect to my office workstation for heavy work since the pandemic started, with exceptional usability.  I tried the java version on M1 and found that it was quite snappy.  It's just the MacOS intel and M1 builds themselves that seem in need of some optimization, at least on Apple silicon.

**Comment by bphinz** [comment]
Can someone with an M1 please test this fat binary?

https://s3.amazonaws.com/tigervnc.bphinz.com/experimental/TigerVNC-1.13.80.dmg

**Comment by RobyB** [comment]
@bphinz Tried it out for a few days.
Running Ventura 13.1 on a Apple M1 Pro.
No fancy setup, just running in full screen on an external monitor.
Works as expected, no issues so far.
But as i said, didn't perform any detailed debugging and/or trying different setups/options

**Comment by bphinz** [comment]
Thanks.  We'll deal with any issues that come up I suppose.  The latest nightly is a universal x86_64/arm64 fat binary.

**Comment by RobyB** [comment]
Could it be possible to also have a M1 version compiled in the nightly?
If it becomes available for sure many more people will give it a try.

**Comment by bphinz** [comment]
There was a problem with the CI task that prevented it from uploading the new fat dmg but it's there now.

**Comment by CendioOssman** [comment]
I've now also tested on both a x86_64 and arm64 mac and it works fine on both. Nice work!

I also quickly compared performance between Rosetta and native. I only got a minor difference in my quick test. 74% CPU usage vs 79%.

**Comment by twhitehead** [comment]
@bphinz Thanks for this! :+1:
