### ISSUE TITLE
New release with updated code

### ISSUE THREAD

**Issue by Orangian** [TigerVNC/tigervnc#1435]
**Is your feature request related to a problem? Please describe.**
Hi, 
The ArchLinux package is on the last official release, which does not include a patch for #1373, which is causing some issues for me, so I've been trying to build a version off the latest git commit.  I've tried to [modify the existing Arch PKGBUILD](https://raw.githubusercontent.com/Osmium-Linux/pkgbuilds/master/tigervnc/PKGBUILD) to get it to work with modern X Servers and the latest tigervnc commits, but[ I've been as of yet unsuccessful. ](https://gist.github.com/Orangian/272d8deb771c8762f21bb74917e629e7)

**Describe the solution you'd like**
A new release or hotfix(?) with the commits over the last few months included. This would allow the X11 extension to actually function, as distros would update to match the latest release.

**Describe alternatives you've considered**
I've been trying to compile the code as stated above, but been unsuccessful. The tigervnc-git package is also broken, as it has not been updated since 2018.

Any thoughts would be appreciated.

**Comment by CendioOssman** [comment]
I would suggest just adding #1383 on top of your already stable packaging for TigerVNC 1.12.0. If you grab `master` then you'll get a lot more stuff that hasn't seen as much testing. Grabbing small fixes like this is usually how packagers handle blocking issues between releases.

A new release will be out eventually, but there is no plans for that in the immediate future.
