### ISSUE TITLE
Conflict between xorg and vnc (10-vnc.conf)

### ISSUE THREAD

**Issue by kinggx9** [TigerVNC/tigervnc#1437]
Here are the details:
I didn't come across this situation before

Describe the bug
I will be stuck at xorg with the error: 
`xinit: giving up`
`xinit: unable to connect to X server: Connection refused`
`xinit: server error`

It happens when I use the file /etc/X11/xorg.conf.d/10-vnc.conf
`Section "Module"`
`Load "vnc"`
`EndSection`
`Section "Screen"`
`Identifier "Screen0"`
`Option "UserPasswdVerifier" "VncAuth"`
`Option "PasswordFile" "/home/user/.vnc/passwd"`
`EndSection`
The server will work fine if I don't use /etc/X11/xorg.conf.d/10-vnc.conf

Server
OS: Arch Linux, kernel 5.4.180-arch1-1
DE: Xfce
VNC client: TigerVNC (vncviewer)
VNC client version: 1.12.0
Client downloaded from: Arch repository

**Comment by dsmaynard** [comment]
> Here are the details: I didn't come across this situation before
> 
> Describe the bug I will be stuck at xorg with the error: `xinit: giving up` `xinit: unable to connect to X server: Connection refused` `xinit: server error`
> 
> It happens when I use the file /etc/X11/xorg.conf.d/10-vnc.conf `Section "Module"` `Load "vnc"` `EndSection` `Section "Screen"` `Identifier "Screen0"` `Option "UserPasswdVerifier" "VncAuth"` `Option "PasswordFile" "/home/user/.vnc/passwd"` `EndSection` The server will work fine if I don't use /etc/X11/xorg.conf.d/10-vnc.conf
> 
> Solved:: `nano ~/.xprofile` Add: `x0vncserver -rfbauth ~/.vnc/passwd &`


Just to check, where you had /home/user/.vnc/passwd, here "user" is your login name correct? From looking at other sources it sometimes seems to be "root" rather than user. Was wondering what worked for you.
