### ISSUE TITLE
vncserver script does not parse -localhost, causing desired port (display) number to be ignored (causing port contention on startup of multiple concurrent vnc server sessions)

### ISSUE THREAD

**Issue by jhgit** [TigerVNC/tigervnc#1438]
**Describe the bug**
Passing -localhost interferes with option parsing in vncserver script, preventing desired display number (e.g., :2 passed on the command line) from being used.  This can cause port conflicts when multiple vncserver session are starting together (like at boot, for example) - a thundering herd all trying to use port 5901, for instance, due to races finding an unused port and then actually using it.

**To Reproduce**
1. vncserver -localhost :1 & vncserver -localhost :2 & vncserver -localhost :3 &  (add more if you like)
2. Notice that not all vnc sessions are started.  YMMV depending on how your OS can run code concurrently.  That is, your system may race to find unused ports and use those ports differently than another system.
3. Read startup error logs (stdout/err from vncserver and/or .log file in ~/.vnc).  Look for 'failed to bind socket: Address already in use'.

**Expected behavior**
3 vnc servers listening on localhost only tcp sockets 5901, 5902 and 5903.
But since they all try to find a free port instead of using the display number on the command line, there is a port conflict on 5901.

**Server (please complete the following information):**
 - OS: centos 7
 - VNC server: TigerVNC
 - VNC server version: 1.8.0 with Redhat mods (rpm tigervnc-server-1.8.0-22)
 - Server downloaded from: CentOS distribution
 - Server was started using: vncserver

**Additional context**
The problem is that the vncserver script does not know about -localhost, and the logic to determine the display number is borked.

This perl code snippet is confused is ARGV is "-localhost :2":

# Find display number.
if ((@ARGV > 0) && ($ARGV[0] =~ /^:(\d+)$/)) {
 .
 .

It does not find the display number because ARGV[0] is -localhost.

Workaround: put 'localhost' in ~/.vnc/config.  That doesn't work very well if you want some localhost servers and some without.

Possible fix: Modify ParseOptions to understand -localhost, set a flag and remove it from ARGV before the "Find display number" code uses ARGV.

**Comment by jhgit** [comment]
Other possible fixes:

Instead of looking at ARGV[0], look through all args for a display number (:display#).  Trying to have vncserver parse all possible Xvnc options set flags for each, just look for the display number and use it.  vncserver does not necessarily need to know about all possible Xvnc args, just the ones it is interested in.

Put a interprocess lock around the "find a port / open a port" sequence.  This is perverse.  Please don't try to implement such a large lock.  Plus this does not address the fact that the desired port (display) is ignored.

Other workarounds:

Add delay between invocations of vncserver.  Problems: how much delay?  how to guarantee two "delay periods" for two (or more) vncservers don't expire at the same time?

**Comment by CendioOssman** [comment]
I'm afraid that is an old version of TigerVNC that we cannot support, and that way of starting a VNC server has been deprecated.

If you need help with that version of TigerVNC I'm afraid I'll have to point you to Red Hat.

**Comment by jhgit** [comment]
What do you mean "that way of starting a VNC server has been deprecated"?  I see vncserver in the current repository with a commit two months ago.  Is there some deprecation notice I can look at?

**Comment by CendioOssman** [comment]
There's a HOWTO included now to get you started with the new method. You can find it here:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

**Comment by jhgit** [comment]
> There's a HOWTO included now to get you started with the new method. You can find it here:
> 
> https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

That HOWTO is written for unix-ish platforms that have systemd.  In the systemd unit file, it points to using vncsession.

But...

    /usr/local/sbin/vncsession someuser :1
    This program needs to be run as root!

The HOWTO could be updated, of course.  But with what?  If vncserver is deprecated, is the recommended way to start a vnc server as a regular user now going back to calling Xvnc directly?

**Comment by jhgit** [comment]
Opened a new bug for this, issue #1597
