### ISSUE TITLE
vncserver as a system service doesn't work.

### ISSUE THREAD

**Issue by Thatoo** [TigerVNC/tigervnc#1444]
**Describe the bug**
vncserver as a systemd deamon on Zorin OS (Gnome) doesn't work.

**To Reproduce**
1. As TigerVNC isn't plug&play, and I couldn't find any documentation (except for windows) on the wiki, to install it on Zorin OS 16 (based on Ubuntu 20.04 with Gnome), I have followed this precise tutorial : https://bytexd.com/how-to-install-configure-vnc-server-on-ubuntu-20-04/
2. launching the command `ssh -L 59000:localhost:5901 -C -N -l server_user_name server_ip_address` works!
3. creating the following system service doesn't work : `sudo nano /etc/systemd/system/vncserver@.service` 

```
[Unit]
Description=Start TigerVNC server at startup
After=syslog.target network.target

[Service]
Type=forking
User=YOUR_USERNAME
Group=YOUR_USERNAME
WorkingDirectory=/home/YOUR_USERNAME

PIDFile=/home/YOUR_USERNAME/.vnc/%H:%i.pid
ExecStartPre=-/usr/bin/vncserver -kill :%i > /dev/null 2>&1
ExecStart=/usr/bin/vncserver -depth 24 -geometry 1280x800 -localhost :%i
ExecStop=/usr/bin/vncserver -kill :%i

[Install]
WantedBy=multi-user.target
```
It doesn't work. I get this screen when I connect to VNC
![image](https://user-images.githubusercontent.com/464782/158336949-9175b46d-3b29-40dd-a4f5-03d0c76ae2e5.png)

**Expected behavior**
Well, I wish we could simply have to do `sudo apt install tigervnc` and the installer could detect the most common desktop environments (GNOME, XFCE, LXQt, LXDE, KDE Plasma, MATE and Cinnamon) and do what this tutorial is explaining with a prompt for the password and the creation of the adequate system service and ~/.vnc/xstartup file.
Or at least find the content of such tutorial withing this wiki https://github.com/TigerVNC/tigervnc/wiki 
And well that it works at the end as a system service that could start on boot.

**Client (please complete the following information):**
 - OS: Debian 11
 - VNC client: Remmina
 - VNC client version:1.4.11
 - Client downloaded from: Debian 11

**Server (please complete the following information):**
 - OS: Zorin OS 16 (based on Ubuntu 20.04 with Gnome)
 - VNC server: TigerVNC
 - VNC server version: the one in Ubuntu 20.04 repository
 - Server downloaded from: Ubuntu 20.04 repository
 - Server was started using: with `vncserver` command it works but not launched within a system service

**Additional Information**
I have tried a lot of different system service file such as https://gist.github.com/spinxz/1692ff042a7cfd17583b but the result is exactly the same.
From all remote desktop system I have tried so far, Vigo, X2Go, Xpra, TigerVNC was the closest to answer my needs (not only theoricaly but practicaly also, except I can't make it start at boot). Hoping for a solution to this issue, I'm going to give xrdp a try.

Cheers,

**Comment by CendioOssman** [comment]
I'm afraid that script and startup is specific to Ubuntu, so not something we can help out with. You'll either have to file a bug with Ubuntu so they can have a look at it, or you can try our builds for Ubuntu 20.04 that has a different service to start sessions.

**Comment by Thatoo** [comment]
@CendioOssman thank you for your answer. Could you tell me where to find the build for Ubuntu 20.04?
I did install TigerVNC with `sudo apt install tigervnc-standalone-server` 
And, could you indicate me where to find the explanation to do a proper installation of TigerVNC on Ubuntu?

**Comment by CendioOssman** [comment]
Our build can be found under our release information. There is a link to releases on https://tigervnc.org, and on the "Code" tab of the repo here.

We have this documentation to get you started with the new service:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

**Comment by intraxit** [comment]
On debian-12 type=forking stopped working and tigervncserver.service did not load without any clear error message!
I switched to type=simple and it started working again...
WTF seriously !
