### ISSUE TITLE
Problems starting in uos system

### ISSUE THREAD

**Issue by Tangguilinyy** [TigerVNC/tigervnc#1447]
I configured tigervnc using https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md and tried to start the tigervnc service. When you run into some problems and want to ask for help, it's hard to tell where the problem is because there is no other error message.
![image](https://user-images.githubusercontent.com/89759273/160096344-b494a082-1c52-4910-bc1d-fdf4fe8abf17.png)
![image](https://user-images.githubusercontent.com/89759273/160096506-fe44b8e3-244c-46a1-b875-0a8e437b1415.png)

**Comment by CendioOssman** [comment]
Please fill out the bug report completely so we can understand your setup.

**Comment by Tangguilinyy** [comment]
@CendioOssman Thanks, I think I solved the problem. When I restarted the service was running normally. Does the installation have to be restarted?

**Comment by CendioOssman** [comment]
No, systemd should pick up any new services automatically. So there is something amiss there.

Since the issue has been resolved I'll go ahead and close this though.
