### ISSUE TITLE
the connection to x0vncserver always broken but no persistent.

### ISSUE THREAD

**Issue by iysheng** [TigerVNC/tigervnc#1449]
**Describe the bug**
I install tigervnc on a laptop, the laptop installed solus OS. Then I make a system service with x0vncserver, the script is :
``` bash
[Unit]
Description=Remote desktop service (VNC) for :0 display

# Require start of
Requires=display-manager.service

# Wait for
After=network-online.target
After=display-manager.service

[Service]
Type=forking

# Set environment
Environment=HOME=/root

# Start command
ExecStart=/usr/local/bin/x0vnc.sh

# Restart service after session log out
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
The content of related x0vnc.sh is
``` bash
#! /bin/bash

# Export an environment variable of the Display Manager
export XAUTHORITY="/var/run/lightdm/root/:0"

# Start VNC server for :0 display in background
## Set path to binary file
VNC_BIN=/usr/bin/x0vncserver

## Set parameters
PARAMS="-display :0 -SecurityTypes Vncauth"
if [[ -f /etc/vnc.conf ]];
then
	## Launch VNC server
	($VNC_BIN $PARAMS) &
else
	## Add parameters
	#PARAMS+=" --I-KNOW-THIS-IS-INSECURE"
	PARAMS+=" -rfbauth /home/yangyongsheng/.vnc/passwd"
	
	## Launch VNC server
	($VNC_BIN $PARAMS) &
fi

# Provide clean exit code for the service
exit 0
```
Although I can use tigervnc viewer connect the laptop with another win7 pc, But the connection is no persistent. I always get connection broken as:

**To Reproduce**
just on a win7 latop use Tigervnc viewer to connect the pc instlled solus with x0vncserver running.
**Expected behavior**
I want the connection is persistent.

**Screenshots**
![](https://s3.bmp.ovh/imgs/2022/04/03/d7b680291933d8a8.png)

**Client (please complete the following information):**
 - OS: [Windows 7]
 - VNC client: [TigerVNC]
 - VNC client version: 
 - ![](https://s3.bmp.ovh/imgs/2022/04/03/097600e004f9ae80.png)

**Server (please complete the following information):**
 - OS: [solus]
 - VNC server: [TigerVNC]
 - VNC server version: [TigerVNC Server version 1.11.0, built Nov 11 2021 20:27:02]
 - Server downloaded from: [my Linux distribution]
 - Server was started using: [e.g. `x0vncserver`]

**Comment by CendioOssman** [comment]
I'm afraid that error means that something killed the connection. This might be a firewall or antivirus or such. If it happens after a while it is likely a firewall that has some idle timeout.

Unfortunately this is outside of our control and not something we can help you with. You'll have to find what device is killing your connection and see how to configure it to not do so.

**Comment by iysheng** [comment]
> I'm afraid that error means that something killed the connection. This might be a firewall or antivirus or such. If it happens after a while it is likely a firewall that has some idle timeout.
> 
> Unfortunately this is outside of our control and not something we can help you with. You'll have to find what device is killing your connection and see how to configure it to not do so.

thanks for quick response, is there a log file I can see with x0vncserver on the solus laptop?

**Comment by CendioOssman** [comment]
x0vncserver by default logs to stderr, so it should end up as the log entries for the service you set up.

**Comment by iysheng** [comment]
Oh, I will look then, thanks.

**Comment by iysheng** [comment]
@CendioOssman Hello, after I track x0vncserver's log, I found the error as:
``` bash
 75 [xcb] Unknown sequence number while processing queue
 76 [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
 77 [xcb] Aborting, sorry about that.
 78 x0vncserver: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
is there a bug here or something wrong ?

**Comment by CendioOssman** [comment]
Yes, that's a bug. But it's in the system libraries, not in TigerVNC. Please see #300 and #869.

This should be reported to your distribution or Xorg so they can see why the X libraries are crashing.
