### ISSUE TITLE
url svn.easysw.com not working

### ISSUE THREAD

**Issue by obsider** [TigerVNC/tigervnc#145]
Hello,

I am currently trying to build the 1.4.3 release of tigervnc by following the BUILDING.txt. In the 'Building FLTK' section, the address given 'svn.easysw.com' is not working. Trying it on a navigator redirects to an electronic cigarette website. Is there a working address available ?

Regards

**Comment by CendioOssman** [comment]
You can download FLTK from fltk.org instead. Preferably use FLTK 1.3.3 as it requires no patches.

**Comment by obsider** [comment]
Will do, thanks !

Maybe it would be good to modify BUILDING.txt to reflect those changes.

In any case, closing the ticket.
