### ISSUE TITLE
Startup error "readTLS: The TLS connection was non-properly terminated. (-110)" with 1.12.0 (regression)

### ISSUE THREAD

**Issue by andreas-luik** [TigerVNC/tigervnc#1450]
**Describe the bug**
When running TigerVNC 1.12.0 (Windows) and connecting to a server with TLS enabled, startup fails with the error message
An unexpected error occurred when communicating with the server:
readTLS: The TLS connection was non-properly terminated. (-110)

The VNC server is x11vnc-0.9.16-3.el8.x86_64 (Linux), https://github.com/LibVNC/x11vnc
with TLS enabled using these options:
-ssl /tmp/vnc.hWYl7l67SL/vnc.pem -vencrypt nodh:support -anontls never

TigerVNC 1.11.0 works fine with this server.

**To Reproduce**
happens always

**Expected behavior**
same behaviour as with 1.11.0

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC
 - VNC client version: 1.12.-
 - Client downloaded from: tigervnc.org

**Server (please complete the following information):**
 - OS: Rocky Linux 8.5
 - VNC server: x11vnc
 - VNC server version: 0.9.16
 - Server downloaded from: rocky.org
 - Server was started using: /usr/bin/x11vnc -q -shared -forever -N -nopw -ssl /tmp/vnc.hWYl7l67SL/vnc.pem -vencrypt nodh:support -anontls never

**Additional context**

**Comment by CendioOssman** [comment]
Thanks for reporting. I can reproduce the issue here, and a bisect indicates that e9425ac04d70481f7cb168a19bcbc47728f838c7 is the culprit. I'll see if I can find why things go wrong.

**Comment by CendioOssman** [comment]
This turned out to be because of some unexpected behaviour by GnuTLS:

https://gitlab.com/gnutls/gnutls/-/issues/1251

A workaround is in place in cee5a417c8411adbeba7cee9e22c1bd519cf39c6. Please try the next nightly build and the issue should be resolved.

**Comment by snakysnake** [comment]
Got this issue on my pc on arch linux

**Comment by dessalines** [comment]
Confirm, this is still an issue on arch linux.

**Comment by james7x1** [comment]
This is still an issue in Windows as well. Happens for me when there is an interruption in network connection. The server is still up and accessible via VNCViewer or any other VNC product, just not TigerVNC.

**Comment by CendioOssman** [comment]
The original issue here got a fix, so it's easily confusing if we start discussing similar problems.

Please open a new issue with a filled out bug template and we can continue investigating there.
