### ISSUE TITLE
KERNEL32.dll related error when lauching on windows 7

### ISSUE THREAD

**Issue by iamtherobin** [TigerVNC/tigervnc#1453]
When I try to launch TigerVNC server on windows 7 x64, I always get an error about CreateProcessAsUserA and Kernel32.dll and the program fails to start. It does not matter configuration I use, single application or service, or if I use the 32bit or the 64bit version. I also tried the latest release and pre-release versions.

<a href="https://imgur.com/PV5p5FR"><img src="https://i.imgur.com/PV5p5FR.png" title="source: imgur.com" /></a>

**Comment by bphinz** [comment]
I'm afraid that Windows 7 hasn't been supported for some time now. However, you should be able to go back to an older version of TigerVNC (I don't remember exactly when the minimum supported version was bumped, maybe around 1.9.0?).

**Comment by CendioOssman** [comment]
We haven't formally dropped Windows 7 support yet. We raised the requirement to Vista in 1.7.0, and to Windows 7 in 1.11.0. We haven't changed it since.

Also, Microsoft claims that function is available since Windows XP, so there is something odd going on here.

**Comment by iamtherobin** [comment]
This is a really old post but could it be related? https://forum.powerbasic.com/forum/user-to-user-discussions/programming/19623-createprocessasuser-kernel32-dll-advapi32-dll

**Comment by CendioOssman** [comment]
I checked my builds here and `objdump` shows that `CreateProcessAsUserA` is correctly grabbed from `advapi32.dll`:

```console
$ objdump -x winvnc4.exe
...
        DLL Name: ADVAPI32.dll
...
        4f7f4a    123  CreateProcessAsUserA
...
```

So I guess there is something off with the build system on your machine, @bphinz. We're using mingw-w32 3.3.0 here. That is admittedly an ancient version, but the current version still has that symbol in the correct DLL:

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-crt/lib32/advapi32.def

**Comment by bphinz** [comment]
Are your builds statically linked?  advapi32.a on my build host has the
symbol but I don't think it's being linked in.  I don't see where
CreateProcessAsUserA is being called in the src, only CreateProcessAsUser
in win/rfb_win32/LaunchProcess.cxx and win/winvnc/VNCServerService.cxx.

**Comment by CendioOssman** [comment]
> Are your builds statically linked?

Yes and no. l use the `BUILD_STATIC` flag, but system libraries are all dynamically linked. If you check with `objdump` as I did, it will list which DLL it expects to find things in.

> advapi32.a on my build host has the symbol but I don't think it's being linked in. 

The fact that it is a `.a` file is just a quirk of how Windows works. That is just a stub that will result in a dynamic dependency in the end. It should be included in the default list of libraries by the compiler. And we explicitly add it when doing our "static" builds.

>I don't see where CreateProcessAsUserA is being called in the src, only CreateProcessAsUser in win/rfb_win32/LaunchProcess.cxx and win/winvnc/VNCServerService.cxx.

Another Windows quirk. That's the same thing. They magically add that `A` (or `W`) using the system headers.

**Comment by haboustak** [comment]
I received the same error on `Windows 7` for a project that I build using `mingw64` that also calls `CreateProcessAsUser`. In my case, the failures started when I upgraded my build environment to `Fedora 36`, which ships `mingw64 9.0.0`. I had been building using `Fedora 27` and `mingw64 5.0.2`

Long story short, after a bit of effort bisecting mingw releases using Fedora, I found that something changed between `6.0.0` and `7.0.0` that resulted in `CreateProcessAsUser` getting imported from `KERNEL32` rather than `ADVAPI32`. I'm not entirely sure what changed, but it seems like a link order problem, because in my project I was never explicitly linking with the `ADVAPI32` import library. It seems that `mingw >= 7.0.0` has a `CreateProcessAsUser` definition in `KERNEL32` and so mingw is importing it from that library, but that symbol is not present on Windows 7.

If I explicitly add `-ladvapi` to my linker flags, then it imports the symbol from `ADVAPI32` and Windows 7 stops complaining. You could try the [same solution](https://github.com/TigerVNC/tigervnc/blob/07d4e29042409a0c2d4912d25af8fab71fa71f33/win/winvnc/CMakeLists.txt#L14) when building `winvnc` and friends.

Fedora versions in case they help:
```
$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)
$ dnf list installed | grep mingw64-crt
mingw64-crt.noarch                  6.0.0-4.fc32                    @fedora

$ cat /etc/fedora-release 
Fedora release 33 (Thirty Three)
$ dnf list installed | grep mingw64-crt
mingw64-crt.noarch                  7.0.0-2.fc33                    @fedora         
```

**Comment by CendioOssman** [comment]
Nice detective work! Thanks!

It seems mingw has noticed this as well:

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/49a56d453d474be6be50a1e4b0edab94a1f25ea7/

That commit is very recent, though. So it doesn't look like it is included in the latest stable release.

@bphinz, any chance you can apply a fix to your mingw?

**Comment by iamtherobin** [comment]
So I have installed the latest builds. It installs and runs now on my Windows 7 build. However, when I try to connect to the TigerVNC server, my system throws a Visual C++ assertion error curiously containing @bphinz name

<a href="https://imgur.com/2jkmxVY"><img src="https://i.imgur.com/2jkmxVY.png" title="source: imgur.com" /></a>

I assume this is something hardcoded in the build process?

**Comment by bphinz** [comment]
Yes, that directory is from the build process

**Comment by CendioOssman** [comment]
I'm afraid that's an unrelated error. So let's close this issue, since the original problem seems to be resolved. The new issue is being discussed on #1500 (where it doesn't strictly belong, either…)

**Comment by bphinz** [comment]
I can replicate that, and if I hit the ignore button on the server side
twice then it works

**Comment by bphinz** [comment]
Wow, that was a really great find.  @iamtherobin - can you please test the
nightly build located here <http://tigervnc.bphinz.com/nightly/>?  I don't
have ready access to a Win7 box at the moment.
