### ISSUE TITLE
20 second startup delay when using -via

### ISSUE THREAD

**Issue by deeptho** [TigerVNC/tigervnc#1454]
**Describe the bug**
20 seconds delay before password prompt is shown when connecting with -via
This seems to be because of the default tunnel command:
/usr/bin/ssh -f -L "$L":"$H":"$R" "$G" sleep 20.

With the following command, the delay is eliminated
VNC_VIA_CMD='/usr/bin/ssh -f -L "$L":"$H":"$R" "$G" sleep 1' vncviewer -via remote_host :0

Why is there a 20 second delay by detault? 20 seconds is very long
Why run a "sleep" command at all?
 
The following version seems to work without a 20 second delay
VNC_VIA_CMD='/usr/bin/ssh -f -L "$L":"$H":"$R" "$G" -N' vncviewer -via remote_host :0

As there anything detrimental about this version? 
And why is this then not the default for VNC_VIA_CMD?

**To Reproduce**

Connect to remote server as follows (client and server running fedora34)
vncviewer -via remote_host  :0
It takes 20 seconds before a password prompt is shown

**Expected behavior**
Immediate password prompt

**Client (please complete the following information):**
 - OS:fedora 34 on client and server
 - VNC client: 
 vncviewer
 tigervnc-1.11.0-12.fc34.x86_64

**Server (please complete the following information):**
 - OS:  fedora 34
 - VNC server: 
 - x11vnc-0.9.16-6.fc34.x86_64

- Server was started using: [e.g. `vncserver`]
sudo systemctl start x11vnc

**Comment by CendioOssman** [comment]
There is something wonky with your setup in that case because that sleep should not delay the connection. In fact, it should be very large, as otherwise the viewer will fail to connect. It is there so that ssh doesn't terminate in the time between ssh setup and the viewer opening the connection to the server.

If you add a `-vvv` to your ssh command line, you might see what it is up to that takes so long.

**Comment by deeptho** [comment]
I believe it may be related to the following in ~/.ssh/config:
ControlMaster auto
ControlPath ~/.ssh/ssh_mux_%h_%p_%r

This option leads to faster connections but seems to interfere with vncviewer, even
if this is a brand new ssh connection.

With or without the above options:
"sleep 1" seems to work just as well as "sleep 20" (vncviewer connects; session runs fine)

Something like this (which would return immediately) also works:
VNC_VIA_CMD='/usr/bin/ssh -f  -L "$L":"$H":"$R" "$G" /bin/true' vncviewer -via remote_host  :0

So for me the solution is the lattter, as it works.  I understand there might be a data race, but 
in practice it does not happen en with the defaults,  have the 20 seconds delay. I have noticed that on some occaions the 20 seconds delay does not occur. So there is a random factor as well.

**Comment by CendioOssman** [comment]
By using a master connection, I can reproduce the issue you are seeing. It would seem that there is some incompatibility between that and the `-f` flag.

I would suggest reporting this issue to OpenSSH, as this doesn't adhere to what `-f` is documented to do. Until then, user's affected by this can set `VNC_VIA_CMD` to something different.
