### ISSUE TITLE
Black screen on Ubuntu server

### ISSUE THREAD

**Issue by mauricev** [TigerVNC/tigervnc#1455]
**Describe the bug**
I setup tigervnc server on Ubuntu and when I connect to it, I get a black screen

**To Reproduce**
1 install tigervnc to Ubuntu (this involves a few steps)
1a sudo dpkg -i xtigervncviewer_1.12.0-1ubuntu1_amd64.deb
1b sudo apt install libfltk1.3
1c sudo apt --fix-broken install 

**Expected behavior**
I should see and be able to manipulate the remote screen

**Screenshots**
Black screen is pretty self-explanatory

**Client (please complete the following information):**
 - OS: Mac Monterey
 - VNC client: tigervnc
 - VNC client version: 1.12.0
 - Client downloaded from: brew

**Server (please complete the following information):**
 - OS: Ubuntu 21.10
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: this site
 - Server was started using: systemd file (e.g., /usr/lib/x86_64-linux-gnu/vncsession-start %i)

**Additional context**
Is there logging anywhere that I can attach?

**Comment by CendioOssman** [comment]
Yes. Some basic logging is done for the service itself. You'll find that in `journalctl`. The session it starts will log to a file in `~/.vnc`. Some applications and desktops will ignore that file and log to the journal as well though.

Please have a look in both the journal and that log file and let us know what it says. Hopefully there is a clue to what goes wrong.

**Comment by mauricev** [comment]
journalctl doesn't be logging anything relevant. The vnc log says

```
Using desktop session ubuntu-xorg

New 'u21:1 (maurice)' desktop is u21:1

Starting desktop session ubuntu-xorg


Xvnc TigerVNC 1.12.0 - built Nov 10 2021 03:52:32
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12011000, The X.Org Foundation


Tue Apr 19 14:26:29 2022
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
xinit: XFree86_VT property unexpectedly has 0 items instead of 1

Tue Apr 19 14:26:40 2022
 Connections: accepted: 10.49.150.83::63606
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Tue Apr 19 14:26:46 2022
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST:  Client pixel format depth 6 (8bpp) rgb222
```

**Comment by CendioOssman** [comment]
Are you perhaps logged in locally as the same user as well? Modern systems unfortunately don't really support that.

**Comment by CendioOssman** [comment]
No response. Closing.
