### ISSUE TITLE
Quick Newbie Question: Differences in installers for compiled binaries for Win64?

### ISSUE THREAD

**Issue by DavidDurlach** [TigerVNC/tigervnc#1456]
Apologies for such a basic question, but after significant searching, I failed to find an answer (and didn't want to "overly" experiment by "randomly" installing stuff...).  (Also, did not find a more-appropriate place to ask my question; forgive me if this is the wrong place.)

**0)**  Context for question:  This page of downloads:  https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/

**1)**  I believe that "**tigervnc64-winvnc-x.xx.xx.exe**" is the installer for Windows 64 bit *Server*. So (unless I am wrong) I don't have a question there.

**2)**  However, I am confused about the difference between:

**a)**  "**vncviewer64-1.12.0.exe**" with size 25.6 MB and Properties for exe showing "TigerVNC Client for Win64".

	(versus)

**b)**  "**tigervnc64-1.12.0.exe**" with size just 4.6 MB (only a fraction of (a) above), and Properties showing "TigerVNC Setup", and/but where when I run this installer exe (the only one I have so far run), it appears to set up the TigerVNC Viewer (what I imagine (a) would do, but where (a)'s file size is much larger...).

Comments?

Thank you.

**Comment by samhed** [comment]
Correct, winvnc is a TigerVNC server for windows.

vncviewer64-1.12.0.exe could be called a "movable executable", i.e. one .exe file that includes everything that is needed to run the vncviewer right out of the box.

tigervnc64-1.12.0.exe is an installer for vncviewer, and an installation step is required before this vncviewer can be used. This means the files can be compressed in the installer package, thus the smaller size.

**Comment by DavidDurlach** [comment]
Thank you for the quick and clear response!  Most appreciated.
