### ISSUE TITLE
F8 Sometimes Not Work in TigerVNC under Plasma (Wayland) Desktop

### ISSUE THREAD

**Issue by qrqiuren** [TigerVNC/tigervnc#1459]
**Describe the bug**
F8 is the default menu key of TigerVNC. However, sometimes it could not call the TigerVNC menu.

**To Reproduce**
1. Under Plasma (Wayland), log in to TigerVNC, and then make sure it is in fullscreen mode
2. Press F8, and there should be a pop up menu of TigerVNC
3. Click the other place to exit the menu
4. Press F8 again, but this time, the menu does not pop up

**Expected behavior**
The menu should pop up in the second time after pressing F8.

Under Plasma (X11), it works fine.

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: OpenSUSE Tumbleweed 20220419-0 (kernel: Linux 5.17.3-1-default x86_64)
 - VNC client: TigerVNC 1.12.0
 - VNC client version: 1.12.0
 - Client downloaded from: Installed by default during OpenSUSE Tumbleweed installation
 - Desktop environment: Plasma 5.24.4

**Server (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core) (kernel: 3.10.0-1160.59.1.el7.x86_64)
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: TigerVNC official download
 - Server was started using: `vncserver`
 - Desktop environment: Xfce in CentOS 7.9 repository

**Additional context**
Possibly related to issue #1458 .

**Comment by CendioOssman** [comment]
That's odd. If it works under X11, but not Wayland, then I'm afraid it sounds like a bug in KDE (just like #1458).

Does it only happen in full screen?

**Comment by CendioOssman** [comment]
No response. Closing.
