### ISSUE TITLE
Signed RPM

### ISSUE THREAD

**Issue by snmishra** [TigerVNC/tigervnc#146]
It's encouraging that the recent 1.4.3 release is signed for MacOS X. It would be nice if the RHEL RPM files were signed as well.

**Comment by bphinz** [comment]
On Wednesday, March 4, 2015, snmishra <notifications@github.com> wrote:

> It's encouraging that the recent 1.4.3 release is signed for MacOS X. It
> would be nice if the RHEL RPM files were signed as well.
>
Agreed.  It's been a long-term goal of mine to get 100% signed
deliverables.  I added rpm signing to the build process yesterday and was
working on doing the same for the Debian packages when my ISP connection
went down.  The rpms from the last set of nightlies that I published might
be signed,  but honestly I can't even check.

-brian


-- 
Sent from Gmail Mobile

**Comment by bphinz** [comment]
Everything is now signed (RPMs, debs, exe, dmg, jar).  Instructions for installing the GPG key are on the nightly build page.

**Comment by snmishra** [comment]
Thanks for the quick fix.

**Comment by snmishra** [comment]
It might be a good idea to publish the key fingerprint on the tigervnc.org website and on Github readme.

**Comment by bphinz** [comment]
On Mon, Mar 9, 2015 at 3:54 PM, snmishra <notifications@github.com> wrote:

> It might be a good idea to publish the key fingerprint on the tigervnc.org
> website and on Github readme.
>
When I publish the next release to bintray it will certainly be added to
the release notes there.

**Comment by snmishra** [comment]
I see that the new 1.5.0 RPM files are signed, but I can't verify the signature. I imported the key ID 4582a460 from a PGP keyserver. Is there something I else I need to do?
```
$ rpm --checksig --verbose TigerVNC/tigervnc-1.5.0-21.el6.x86_64.rpm
TigerVNC/tigervnc-1.5.0-21.el6.x86_64.rpm:
    Header V4 RSA/SHA1 signature: BAD, key ID 4582a460
    Header SHA1 digest: OK (d3a738158ea85a562f854de024f368bed24eac51)
    V4 RSA/SHA1 signature: BAD, key ID 4582a460
    MD5 digest: OK (7736c06520321239adb79de9df381aa7)
```

**Comment by bphinz** [comment]
On Tue, Jul 14, 2015 at 8:45 AM, snmishra <notifications@github.com> wrote:

> I see that the new 1.5.0 RPM files are signed, but I can't verify the
> signature. I imported the key ID 4582a460 from a PGP keyserver. Is there
> something I else I need to do?
>
> $ rpm --checksig --verbose TigerVNC/tigervnc-1.5.0-21.el6.x86_64.rpm
> TigerVNC/tigervnc-1.5.0-21.el6.x86_64.rpm:
>     Header V4 RSA/SHA1 signature: BAD, key ID 4582a460
>     Header SHA1 digest: OK (d3a738158ea85a562f854de024f368bed24eac51)
>     V4 RSA/SHA1 signature: BAD, key ID 4582a460
>     MD5 digest: OK (7736c06520321239adb79de9df381aa7)
>
> Interesting.  You are able to install the package, just not verify the
signature, correct?  (which basically defeats the point of the
signature...)  There are various bugs reported like this (
http://serverfault.com/questions/624888/bad-signatures-or-nokey-errors-on-rpms-i-just-signed,
https://technosorcery.net/blog/2010/10/10/pitfalls-with-rpm-and-gpg/,
etc.).  I'll have to sort this out when I return from vacation next week.
Thanks for point this out.

-brian

**Comment by snmishra** [comment]
Thanks for the pointer. The "BAD signature" is a RHEL 5 bug, not anything wrong with with the packages. They check out fine on RHEL 6.
