### ISSUE TITLE
Can remote desktop sessions and local sessions be synchronized using Xvnc

### ISSUE THREAD

**Issue by Tangguilinyy** [TigerVNC/tigervnc#1460]
I found out when using Xvnc that it creates a new X session. This session is independent of the existing local X session. Is there any way to solve this problem?

**Comment by CendioOssman** [comment]
`Xvnc` is indeed for creating an independent session. If you wish to access an existing session, you should use `x0vncserver`, or the Xorg module `libvnc.so`.
