### ISSUE TITLE
Windows Start menu shown when pressing 'Super' key in TigerVNC client windows mode

### ISSUE THREAD

**Issue by gaotxg** [TigerVNC/tigervnc#1461]
**Describe the bug**
Windows Start menu shown when pressing 'Super'(Windows Label) key in TigerVNC client windows mode

**To Reproduce**
1. On Microsoft Windows, start VNC viewer.
2. Connent to VNC server and login (better to use GNOME shell because 'super' key is used to see Activities)
3. Click on 'Super'
4. Windows start menu activited.(Which is the bug)

**Expected behavior**
Windows start menu activited only when cursor is out of VNC viewer

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC
 - VNC client version: 1.12.0
 - Client downloaded from: Sourceforge

**Server (please complete the following information):**
 - OS: Red Hat Enterprise Linux 8.5
 - VNC server: TigerVNC
 - VNC server version: 1.11.0
 - Server downloaded from: system repo
 - Server was started using: Xvnc systemd socket (XDMCP)

**Comment by CendioOssman** [comment]
I'm afraid that is the expected behaviour. In windowed mode, we always respect the system key bindings, so the desktop will grab the Windows key. Please see #102 for allowing keyboard grabs in windowed mode.

**Comment by gaotxg** [comment]
Thank you for so quickly response!

Have you ever used virtual machine with a guest addon? (e.g. VirtualBox or VMware)

They will grab nearly everything (except Ctrl+Alt+Del) to the guest and ignore most system key bindings when mouse integration is activited and cursor is in the vm window. When anyone want to use system keys, simply move the mouse out of the vm window and that's it.

Probably this is a more reasonable and expected behavior for most people, I guess. Because nowadays most OSs or DEs share lots of system key bindings, current behavior makes VNC client hard to use when we want to use keyboard to control the remote client. 

As this bug mentioned, after pressing super key, Windows start menu and GNOME activity are both activited, which is confusing for most users.

It should be an enhancement if an option exists for this feature.

**Comment by gaotxg** [comment]
@CendioOssman

**Comment by CendioOssman** [comment]
Those kinds of enhancement are precisely what #102 is about. So please see that issue.
