### ISSUE TITLE
X Input 2 (or newer) is not available. On Ubuntu 21.04

### ISSUE THREAD

**Issue by jphein** [TigerVNC/tigervnc#1462]
When using ltsp and epoptes I get this error when trying to assist a client. 

**To Reproduce**
```
add-apt-repository ppa:ltsp
apt install --install-recommends ltsp ltsp-binaries dnsmasq nfs-kernel-server openssh-server squashfs-tools ethtool net-tools epoptes
gpasswd -a administrator epoptes
epoptes &
```
Then click on "Take control of user's computer" button. 

**Expected behavior**
I should be able to control the computer.

**Screenshots**
![Screenshot from 2022-04-25 10-48-45](https://user-images.githubusercontent.com/19301265/165146533-97db745e-6e44-458b-a984-33fb1536e2c2.png)

**Client (please complete the following information):**
 - OS: Ubuntu 21.04
 - VNC client: TigerVNC, 
 - VNC client version: TigerVNC Viewer 64-bit v1.11.0
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
same

**Additional context**
I'm actually accessing the computer using X2go with fluxbox manager.

**Comment by CendioOssman** [comment]
I'm afraid that it looks like X2go is a bit behind and doesn't support current X11 standards. So unfortunately you'll have to reach your machine using something other than X2go. Using the TigerVNC server might be an option.

**Comment by peanutbutterandcrackers** [comment]
Hey there,

For anybody else running into this issue, installing `ssvnc` fixed the issue. `ssvnc` is "Enhanced TightVNC viewer with SSL/SSH tunnel helper". On Debian 12, it's just `apt install ssvnc`. LTSP switches to `ssvnc` instead of `tigervnc`, automatically, at least on Debian 12, and everything just works.

Hope this helps!

Referencing https://github.com/TigerVNC/tigervnc/issues/1333 too.

**Comment by jphein** [comment]
> Hey there,
> 
> For anybody else running into this issue, installing `ssvnc` fixed the issue. `ssvnc` is "Enhanced TightVNC viewer with SSL/SSH tunnel helper". On Debian 12, it's just `apt install ssvnc`. LTSP switches to `ssvnc` instead of `tigervnc`, automatically, at least on Debian 12, and everything just works.
> 
> Hope this helps!
> 
> Referencing #1333 too.

This worked for me in Ubuntu 22.04!! Thank you so much.
