### ISSUE TITLE
Allow Xserver being able to listen on TCP to wait for XClient connection

### ISSUE THREAD

**Issue by sequencer** [TigerVNC/tigervnc#1466]
**Is your feature request related to a problem? Please describe.**
Here is my use case: I have a cluster where I only wanna have a "display server", which serves as a `xserver`, and all other nodes on this cluster directly set `DISPLAY` to `display_server:PORT`.

I found there is no opinion for tigervnc to allow the `Xserver` to listen on TCP port. For other DM they have their [own options](https://askubuntu.com/questions/34657/how-to-make-x-org-listen-to-remote-connections-on-port-6000)

**Describe the solution you'd like**
Adding `AllowXServerListeningTCP` option and listen on `6000+DISPLAY` port.

**Comment by CendioOssman** [comment]
`Xvnc` is a normal Xorg server, so it supports all the standard flags there. Please see the documentation for Xorg for available flags.

In your case, it sounds like you want to add `-listen tcp`

**Comment by sequencer** [comment]
Thanks @CendioOssman, where should I add this? In the `.vnc/config` file?
