### ISSUE TITLE
VNCviewer unresponsive keyboard after login in LightDM session

### ISSUE THREAD

**Issue by kb-elmo** [TigerVNC/tigervnc#1468]
**Describe the bug**
When using VNCviewer under windows to log into a LightDM session (Archlinux with i3-wm) the keyboard input stops working.  
On the LightDM login screen the input works just fine. After the login only the mouse works.

This only happens with the TigerVNC viewer.
All other VNC clients that I tested (UltraVNC, RealVNC Viewer, TightVNC) do not have this issue so this must be something related to the TigerVNC viewer.

I also could not find any error messages on the server side so this must be a client problem.

**To Reproduce**
1. Login to a LightDM session running on x0vncserver
2. The keyboard will stop working and only mouse input works

**Expected behavior**
The keyboard should not stop working after logging into the session

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC Viewer
 - VNC client version: 1.12.0
 - Client downloaded from: TigerVNC sourceforge (prebuilt binary)

**Server (please complete the following information):**
 - OS: Archlinux (Linux 5.17.5) with LighDM session manager and i3-wm desktop
 - VNC server: TigerVNC x0vncserver
 - VNC server version: 1.12.0
 - Server downloaded from: Archlinux repository
 - Server was started using: x0vncserver -display :0 (as systemd service)

**Additional context**
I don't think that this is related to https://github.com/TigerVNC/tigervnc/issues/1150
The remote host does not have xscreensaver or any other screenlocker installed and this issue only happens with the TigerVNC viewer.

**Comment by CendioOssman** [comment]
Could you share the log output from `x0vncserver` for us, so we can see if there are any clues there? You should be able to get it using `sudo journalctl -u <name of service>`.

**Comment by kb-elmo** [comment]
Output of the x0vncserver:
```
Mon May 16 09:17:19 2022
 Connections: accepted: 192.168.16.4::1208
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 SVeNCrypt:   Client requests security type TLSVnc (258)
Mon May 16 09:17:22 2022
 XDesktop:    Enabling 8 buttons of X pointer device
 XDesktop:    Allocated shared memory image
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
Mon May 16 09:18:17 2022
 VNCSConnST:  closing 192.168.16.4::1208: Clean disconnection
 EncodeManager: Framebuffer updates: 3447
 EncodeManager:   Tight:
 EncodeManager:     Solid: 43 rects, 228.978 kpixels
 EncodeManager:            688 B (1:1332.02 ratio)
 EncodeManager:     Bitmap RLE: 13 rects, 2.892 kpixels
 EncodeManager:                 427 B (1:27.4567 ratio)
 EncodeManager:     Indexed RLE: 198 rects, 1.52342 Mpixels
 EncodeManager:                  161.044 KiB (1:36.9661 ratio)
 EncodeManager:   Tight (JPEG):
 EncodeManager:     Full Colour: 517 rects, 13.3701 Mpixels
 EncodeManager:                  4.63252 MiB (1:11.011 ratio)
 EncodeManager:   Total: 771 rects, 15.1254 Mpixels
 EncodeManager:          4.79085 MiB (1:12.0453 ratio)
```

Like I already said there's nothing visible on the server in any of the logs and the issue only appears with the TigerVNC client.  
All other clients don't have this issue and the server itself seems to work perfectly fine.

**Comment by kb-elmo** [comment]
Something that I just noticed that I should have tested before:

It is only the windows key that does not work!
I didn't notice this because the windows key is my mod key in i3 and without it working I wasn't able to do anything on my desktop there. 

And even weirder: It seems that the windows key gets blocked completely for some reason.
Meaning it doesn't only not work in the VNC. It also doesn't work in Windows either as long as the TigerVNC session is open.

I have to close TigerVNC to get the windows key back to working again.
When I log back into the already running LightDM session everything works fine.

It just stops working when I go through the LightDM login in the TigerVNC client.

**Comment by CendioOssman** [comment]
Are you running the client in windowed mode or in full screen? And is "send system keys" enabled in the client?

Could you add `-Log *:stderr:100` to the `x0vncserver` command line? That should give us more detailed output in the log whenever you press a key. Please compare a working client with a non-working one and let's see what the difference is.

**Comment by kb-elmo** [comment]
Client is running in fullscreen with system key passing enabled (otherwise using i3-wm would not be possible since it relies on those keys for the different desktop actions)

I'm not going to post the verbose log here for obvious reasons (being the keystrokes for my login password being visible in it).

What I can say is that the windows key does not create any log output when it's being pressed.
All other keys show up just fine in the log (alt, ctrl, menu as well). Just the win/super key does not work.

**Comment by CendioOssman** [comment]
That's surprising. On Windows we normally get events for the Windows key even without grabbing system keys.

Please enable debug logging for the client and see what it says when you press the Windows key. Instructions for enabling that logging can be found here:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs#client-1

**Comment by kb-elmo** [comment]
Welp...
I have no idea why but for some reason the bug disappeared (for now).
I'll test this some more and see if it comes back. If not I'll close this issue in a few days.
Thanks for the help so far :)

**Comment by CendioOssman** [comment]
That's very unexpected. Could you try enabling debug logging on the server instead?

**Comment by CendioOssman** [comment]
Any update, @kb-elmo?

**Comment by kb-elmo** [comment]
Not really.  
I moved on to another VNC viewer (RealVNC) that doesn't have this issue.

The system that I was using this for is for my work.
So I didn't really have much time to debug this futher since I needed it working.

**Comment by CendioOssman** [comment]
Alright. Thank you for the update. I'll go ahead and close this issue then, since it won't be progressing.
