### ISSUE TITLE
Xinerama support

### ISSUE THREAD

**Issue by ercanal** [TigerVNC/tigervnc#147]
For compiled linux binaries, Xinerama support should be added to Xvnc server (disabled by default). User can enable xinerama while starting vnc server. While using multi monitor setup with multi window tools, xinerama support is very helpful to the users.

**Comment by CendioOssman** [comment]
Which binaries are you using? Xinerama is active when I test my builds here:

```
$ xdpyinfo  | grep -i xinera
    XINERAMA
```

(Xinerama is also very much legacy. Modern applications use RandR for multi-monitor things.)

**Comment by ercanal** [comment]
I am using redhat el6 rpms

**Comment by CendioOssman** [comment]
I cannot find the reason for this. It was inherited from Red Hat, which added it here without much rationale:

http://pkgs.fedoraproject.org/cgit/tigervnc.git/commit/tigervnc.spec?id=6fff40ec0c20803eba7bd5abf27bde4bc5139585

@bphinz ? @twaugh ?

**Comment by ercanal** [comment]
I also can't see XINERAMA extension in tigervnc-Linux-x86_64-1.4.3.tar.gz. I think you don't compile this binary with rpmbuild.

**Comment by CendioOssman** [comment]
We do. It's based off the RHEL 5 build.

**Comment by twaugh** [comment]
I'm not entirely sure what build error prompted the spec-file change. It's likely not to be an issue now.

I've set Fedora builds going that re-enable that extension.

**Comment by twaugh** [comment]
How can I test the xinerama extension? Do I need a special VNC viewer tool?

**Comment by CendioOssman** [comment]
You can check if the extension is on with `xdpyinfo`. As for some proper tools, it's way too long since I used xinerama to remember what the command line tools were, or if they still exist. :)

**Comment by ercanal** [comment]
In GNOME 2, Maximizing a window should fill only one screen not all of them.

**Comment by twaugh** [comment]
ercanal: I understand that, but how do I start and view a VNC session with more than one screen?

**Comment by CendioOssman** [comment]
@twaugh , you can't directly. But run vncviewer on a multi-head machine and go into full screen over all monitors. It will then reconfigure the server with the client's monitor configuration.

**Comment by twaugh** [comment]
OK, got it.

**Comment by bphinz** [comment]
Xinerama has been enabled in all of the latest nightly builds.  Please test it out and report back if there are any issues related to this feature.  Thanks.

**Comment by bphinz** [comment]
Closing this issue as the option is now enabled in our builds.  If there are problems using Xinerama open up a new ticket please.
