### ISSUE TITLE
vncserver command only works with "sudo" privilege on Ubuntu 22.04

### ISSUE THREAD

**Issue by hslyu** [TigerVNC/tigervnc#1470]
**Describe the bug**
On ubuntu 22.04, I have installed several packages for vnc by executing
```
$ sudo apt-get install --no-install-recommends ubuntu-desktop
$ sudo apt install light-themes gnome-tweaks tigervnc-standalone-server tigervnc-xorg-extension -y
```
Then, I tested to make vnc session using the below command:
```
$ vncserver -localhost no
```
and get this error:

![image](https://user-images.githubusercontent.com/33674492/168594210-f4ecb9ef-dbcf-4bef-a6a8-029f50eb3a3e.png)
```
=================== tail /home/aislab/.vnc/aislab-9:5901.log ===================
Terminated
X connection to :1 broken (explicit kill or server shutdown).
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
Killing Xtigervnc process ID 8457... success!
================================================================================

Session startup via '/etc/X11/Xtigervnc-session' cleanly exited too early (< 3 seconds)!
```
## **However, when I execute the same command with "sudo", then all problems are gone.**
![image](https://user-images.githubusercontent.com/33674492/168594451-670ceac2-aab3-4ac3-8be1-efc44f6559e1.png)

I've been used tigervnc so many years, but this kind of error has not occurred in previous Ubuntu version.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: Tigervnc
 - VNC client version: 1.12.0
 - Client downloaded from: sourceforge

**Server (please complete the following information):**
 - OS: ubuntu 22.04 LTS
 - VNC server: tigervnc
 - VNC server version: stable apt install version. (1.12.0)
 - Server downloaded from: apt
 - Server was started using: 
```
vncserver -localhost no
```
**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid that startup script is specific to Ubuntu, so it's not something we can support. Please file a bug with Ubuntu and they can hopefully help you out.
