### ISSUE TITLE
Unable to stop and start tigervncserver using systemctl

### ISSUE THREAD

**Issue by sdarwin** [TigerVNC/tigervnc#1471]
**Describe the bug**
Using the latest version of tigervnc the supported method of operation is systemd. The systemctl command should work to stop and start the service.    On Ubuntu 21.10 and 21.04 that was successful. On Ubuntu 22.04 the stop command doesn't stop all the processes. After that, start won't work. 

Your feedback would be greatly appreciated, especially if you try these steps and see a different result. 

**To Reproduce**
1. Using Ubuntu 22.04 Install tigervnc and all dependencies.
2. Start vnc.  It might already be started.  `sudo systemctl start tigervncserver@:1.service`
3. Check vnc processes. There are a few. `ps -ef | grep vnc`
4. Stop vnc. `sudo systemctl stop tigervncserver@:1.service`
5. Check vnc processes. There shouldn't be any. But there are. `ps -ef | grep vnc`
6. Try to start vnc. It fails. `sudo systemctl start tigervncserver@:1.service`

**Expected behavior**
The expected behavior, and what works correctly on Ubuntu 21.04 and 21.10 is
1. Start vnc.  It might already be started.  `sudo systemctl start tigervncserver@:1.service`
2. Check vnc processes. There are a few. `ps -ef | grep vnc`
3. Stop vnc. `sudo systemctl stop tigervncserver@:1.service`
4. Check vnc processes. There shouldn't be any. `ps -ef | grep vnc`
5. Start vnc.  `sudo systemctl start tigervncserver@:1.service`
4. Check vnc processes. Everything is running normally. `ps -ef | grep vnc`

**Client (please complete the following information):**
 - OS: Ubuntu 20.04
 - VNC client: remmina
 - VNC client version: remmina 1.4.2+dfsg-1ubuntu1 amd64 GTK+ Remote Desktop Client
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: So far, tested on Ubuntu 22.04 in the cloud, aws.  
 - VNC server: TigerVNC
 - VNC server version: tigervnc-standalone-server 1.12.0+dfsg-4 amd64 Standalone virtual network computing server
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: sudo systemctl start tigervncserver@:1.service

**More information**

Here is the output from the commands.

```
sudo systemctl start tigervncserver@:1.service
```

```
$ ps -ef | grep vnc
root        8677       1  0 14:58 ?        00:00:00 /usr/sbin/tigervncsession ubuntu :1
ubuntu      8678    8677  3 14:58 ?        00:00:00 /usr/bin/perl /usr/bin/tigervncserver -fg :1
ubuntu      8684    8678  8 14:58 ?        00:00:00 /usr/bin/Xtigervnc :1 -localhost=1 -desktop ip-10-0-5-177.ec2.internal:1 (ubuntu) -rfbport 5901 -PasswordFile /home/ubuntu/.vnc/passwd -SecurityTypes VncAuth -auth /home/ubuntu/.Xauthority -geometry 1920x1200 -depth 24
ubuntu      8687    8678  0 14:58 ?        00:00:00 /bin/sh /etc/X11/Xtigervnc-session env GNOME_SHELL_SESSION_MODE=ubuntu /usr/bin/gnome-session --session=ubuntu
ubuntu      8691    8687  0 14:58 ?        00:00:00 tigervncconfig -iconic
ubuntu      8962    2018  0 14:58 pts/0    00:00:00 grep --color=auto vnc
```

```
sudo systemctl stop tigervncserver@:1.service
```

```
$ ps -ef | grep vnc
ubuntu       925       1  0 15:21 ?        00:00:00 /bin/sh /etc/X11/Xtigervnc-session env GNOME_SHELL_SESSION_MODE=ubuntu /usr/bin/gnome-session --session=ubuntu
ubuntu      2085    1974  0 15:22 pts/0    00:00:00 grep --color=auto vnc
```

Attempt to start again.  But it won't work.

```
sudo systemctl start tigervncserver@:1.service
```

```
$ ps -ef | grep vnc
ubuntu       925       1  0 15:21 ?        00:00:00 /bin/sh /etc/X11/Xtigervnc-session env GNOME_SHELL_SESSION_MODE=ubuntu /usr/bin/gnome-session --session=ubuntu
ubuntu      2085    1974  0 15:22 pts/0    00:00:00 grep --color=auto vnc
```

**Comment by CendioOssman** [comment]
I'm afraid Ubuntu replaces the session handling with their own stuff, so it isn't something we can help you with. Please file a bug with Ubuntu and they can have a look at what is wrong.
