### ISSUE TITLE
Black screen after some idle time in a docker container

### ISSUE THREAD

**Issue by Formartha** [TigerVNC/tigervnc#1472]
Hello,

I'm using XFCE4 as a GUI and connect to it via TigerVNC. I was able to boot the image and everything works fine, but there's an issue which I can't solve.
After some idle time, the screen turns black and I can't see anything in the GUI itself, however, the docker is still alive, the VNC is up and running and the XFCE4 interface is working (per services query).

I thought it's related to the outdated xstartup and I ported the entry-point.sh use Xvnc directly and it's still not working.

Anyone can guide me or at least help with this issue? it's blocking me from proceeding in the project we have.

Cheers,
-M

**Comment by CendioOssman** [comment]
Please fill out the issue form completely so we can understand your setup.

**Comment by MHM98** [comment]
Hello,
I faced the exact same issue(same utilities used) with @Formartha so I'm not going to open another issue. I want to run vncserver inside a docker container and use noVNC to access my display. I used Xfce as the desktop environment.
here is my xstartup script:
`#!/bin/sh `
 `unset SESSION_MANAGER`
` unset DBUS_SESSION_BUS_ADDRESS`
` exec startxfce4
`

After running vncserver, the screen gets black after some idle time.although,vnc server and Xfce are still running in the background and don't create any logs related to this event.
I tried to run vnc server using Xvnc command:
`
Xvnc :1 && export DISPLAY:=1 && startxfce4
`
But still facing the same issue.
Could anyone guild me to solve this problem?

**Comment by Formartha** [comment]
Hi,
It seems like I was able to resolve the issue. In my case, the screen saver was poping, I disabled it and it worked.
Please confirm it by logging via ssh to the machine (terminal) and close the screensaver process.

Let me know if it worked.

**Comment by MHM98** [comment]
@Formartha it solves my problem.
Thank you in advance.
