### ISSUE TITLE
Localhost Problem in TigerVnc 1.12.0

### ISSUE THREAD

**Issue by elkind00** [TigerVNC/tigervnc#1476]
The -localhost option is being added to the Xvnc command line when not requested in version 1.12.0.

Previously I was using TigerVNC 1.1.0 built March 22, 2017, on a Centos 6 system, but I'm moving to a freshly minted Almalinux 8 cloud server and followed these steps:

1. I installed TigerVNC:

        sudo dnf install tigervnc-server

2. I read /usr/share/doc/tigervnc/HOWTO.md.  There are many changes in 1.12.0, but I don't know which are specific to it and which occurred in earlier releases.

3. I added users to the /etc/tigervnc/vncserver.users file.

4. I left the /etc/tigervnc/vncserver-config-defaults file and the /etc/tigervnc/vncserver-config-mandatory file alone.  The only parameter that was specified was "session=gnome" in the defaults file.

5. I placed these settings in the ~/.vnc/config file because they were what was suggested:

        session=gnome
        geometry=1920x1200
        localhost
        alwaysshared

6. I set the password using vncpasswd.

7. I started the VNC server using this command:

        systemctl start vncserver@:1

8. I used RealVNC from a Mac to access the server and received a "connection refused" style message.
 
9. I poked around quite a bit and eventually noticed the -localhost option on the Xvnc command line, and looking at the documentation discovered it prevents remote connections.

10. I thought this would be an easy fix, that I need only comment out the "localhost" line in the ~/.vnc/config file, but that wasn't the case.  I experimented a bit and eventually discovered that only when there is no ~/.vnc/config file would the -localhost option be left off the Xvnc command line, and then I was able to connect to the server remotely using RealVNC.

I also tried "localhost=no" in the ~/.vnc/config file, but that didn't work.  However, as long as the ~/.vnc/config file did not exist then that same line in the /etc/tigervnc/vncserver-config-defaults file caused the Xvnc command line to include the option "-localhost no".

My experimenting wasn't exhaustive, but that was the permutation I found that worked.  This seems an obvious bug to have escaped notice, which often means user error is the actual culprit, but I did attempt due diligence.

**Comment by CendioOssman** [comment]
Hmm... That's unexpected. What is the contents of `/etc/tigervnc/vncserver-config-defaults`?

What does the complete command line to `Xvnc` look like when you have `localhost=no` in `~/.vnc/config`?

**Comment by elkind00** [comment]
Thanks for the reply.  Sorry to take so long to answer.

I put the ~/.vnc/config file back the way it was and now everything works perfectly.  This is a clear case of user error and I apologize.  Without VNC I was a bit hamstrung and must 
have screwed up and not been getting the files into the states I thought they were.

**Comment by CendioOssman** [comment]
No worries. Mistakes happen. :)

Thanks for letting us know!
