### ISSUE TITLE
suggestions to improve the Wiki article for Windows server

### ISSUE THREAD

**Issue by joey04** [TigerVNC/tigervnc#1479]
This weekend I successfully installed TigerVNC server on a new Win10 machine so that I can control it from my main Windows PC (with a better ergonomic arrangement).

The [wiki article](https://github.com/TigerVNC/tigervnc/wiki/Setup-TigerVNC-server-%28Windows%29) for setting up the server on Windows was essential, but it could use some improvements:

* Clearly state up-front that this is not officially supported [since September 2020](https://github.com/TigerVNC/tigervnc/releases/tag/v1.11.0). I obtained that link from the Wikipedia article.

* Clearly state that the current Stable version should be used. That's the one that works. Given the link in the wiki to nightly builds, I first tried the latest 1.12.80 server build. It crashed every time a connection was attempted, so I uninstalled, and thankfully the stable 1.12.0 is working fine with the exact same settings.

* Add that server settings are stored in the registry. Per the prior point, these were populated when I first opened the 1.12.0 settings window, after changing them for the initial .80 install.

If you want, I can make these changes to the article. But since I'm new here, I won't do so without developer consent.

**Comment by CendioOssman** [comment]
Sure, go ahead! Those sound like welcome changes to me.

**Comment by joey04** [comment]
I made the changes. ([diff](https://github.com/TigerVNC/tigervnc/wiki/Setup-TigerVNC-server-(Windows)/_compare/8bc35c48fa3d467444704e39d2f25daa2a91ec92...fcdc32c73acd50c5b14c35797f04cd16440733aa))

**Comment by CendioOssman** [comment]
Looks good! Thanks!
