### ISSUE TITLE
VNC service works but cannot log locally

### ISSUE THREAD

**Issue by IanTrudel** [TigerVNC/tigervnc#1481]
**Describe the bug**
Systemd starts vncserver upon booting, as expected, and is accessible through port 5901, base on the instructions here: https://techviewleo.com/install-and-configure-vnc-server-on-rocky-linux/

Unfortunately, gdm would not let me login locally to the user attached to vnc as defined in `/etc/tigervnc/vncserver.users`. I type in my password, it tries to open gnome, but nothing, comes back to gdm.

Also, seems like it has some troubles starting gnome applications and I have to (sometimes) start them with `dbus-launch gnome-terminal &`.

What happened to `~/.vnc/xstartup`, guys? What's the alternative? #1271

**Expected behavior**
A smooth experience. How about that! :D

**Client (please complete the following information):**
 - OS: Arch Linux (rolling)
 - VNC client: TigerVNC
 - VNC client version: 1.12.0-3
 - Client downloaded from: packaged on Arch repository

**Server (please complete the following information):**
 - OS: Rocky Linux 8.6
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: packaged on Rocky Linux repository (probably epel?)
 - Server was started using: as a service, see below.

**Additional context**

File `/etc/systemd/system/vncserver@:1.service`:
```
[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
ExecStartPre=+/usr/libexec/vncsession-restore %i
ExecStart=/usr/libexec/vncsession-start %i
PIDFile=/run/vncsession-%i.pid
SELinuxContext=system_u:system_r:vnc_session_t:s0

[Install]
WantedBy=multi-user.target
```

**Comment by IanTrudel** [comment]
Why are you writing off my issue so quickly? I have some trouble understanding how TigerVNC remains useful if it only plans to support a specific vnc user that is not a local user, as it used to. It was working before I used systemd instead of vncserver, as it was marked as deprecated.

**Comment by CendioOssman** [comment]
I'm afraid the issue is already well known, so your report isn't unclear or unexpected.

We are unfortunately not in a position where we can dictate how the applications and desktop environments work. They changed and we had to follow. So for the old methods to return, systemd, GNOME and everything else needs to add back support for multiple sessions. I'm afraid this is not something the TigerVNC project can do.

**Comment by LavaDanny** [comment]
Hello, I am currently running into this issue and was wondering how to back out of these systemd changes and log back into the machine. Currently getting bounced to gdm.
