### ISSUE TITLE
tigervncserver listening on UNIX sockets dies after -ClientWaitTimeMillis ms

### ISSUE THREAD

**Issue by calestyo** [TigerVNC/tigervnc#1485]
**Describe the bug**
When running `tigervncserver` with listening on UNIX sockets and while it simply waits for the first client to connect (i.e. no attempt to connect is made yet), it dies after `-ClientWaitTimeMillis` ms.

The reasons seems to be, that as soon as I add `-rfbunixpath` no session is started, thus no `xterm` whatsoever is invoked either.
Even when I manually specify a session command like in:
`tigervncserver -fg -localhost=yes -nolisten=tcp -rfbunixpath=/home/calestyo/remsock :5 -- /usr/bin/xterm`
or
`tigervncserver -fg -localhost=yes -nolisten=tcp -rfbunixpath=/home/calestyo/remsock :5 -- /etc/X11/Xtigervnc-session`
nothing happens (i.e. `xterm` nor the session get started).

**To Reproduce**
1. `tigervncserver -fg -localhost yes -nolisten tcp -rfbunixpath /tmp/someSocket`
2. wait 30 s (default of `-ClientWaitTimeMillis` is 30000 ms)
3. it dies

**Expected behavior**
It should start the `session` just as it would do when using TCP.

**Client (please complete the following information):**
not relevant

**Server (please complete the following information):**
 - OS: Debian bullseye
 - VNC server: TigerVNC
 - VNC server version: 1.11.0+dfsg-2

Any ideas?

Thanks,
Chris.

**Comment by calestyo** [comment]
When I manually start e.g. `DISPLAY=:5 xman` then it seems to work.

Interestingly, when subsequentially killing `xman`, the vnc server stays alive,... even after the 30s, which AFAIU the description of `-ClientWaitTimeMillis` shouldn't be the case either.

**Comment by calestyo** [comment]
What's even more weird... the above works only when I directly start e.g.:
```
/usr/bin/Xtigervnc :5 -rfbport 5905 -localhost=1 -SecurityTypes VncAuth -PasswordFile /home/calestyo/.vnc/passwd -rfbunixpath /home/calestyo/remsock -ClientWaitTimeMillis 30000 -geometry 1920x1200 -desktop ddd -depth 24 -auth /home/calestyo/.Xauthority -nolisten
```
When I then launch `xman` on another terminal for `:5` I can connect to the server **and** it stays running.

When doing the same but with:
```
/usr/bin/tigervncserver  -localhost yes -nolisten tcp -rfbunixpath /home/calestyo/remsock :5
```
(which produces the very `Xtigervnc` command from above) I can also connect and see the running `xman`, but it's still killed after 30s.

**Comment by CendioOssman** [comment]
`-ClientWaitTimeMillis` is¹ a rather internal option and does not have any effect on the lifetime of the server. It controls how responsive the server is when there are network problems. So whatever is going on is likely something else.

Since `Xtigervnc` works, but `tigervncserver` doesn't, I'm afraid I'll have to ask you to file a bug with Debian. The latter command is something they've written, and doesn't come from us. So it's unfortunately not something we know much about, or can fix.

¹ or rather was, since it is gone in TigerVNC 1.12.0

**Comment by CendioOssman** [comment]
> Sorry that I had’t noticed that... but since the (somewhat older) tigervnc package of SLES also contains a corresponding `vncserver` script, I thought that it was part of upstream, without checking any further.
> 

We had a script called that here, which hopefully SUSE used. But Debian decided to replace that with their own script with the same name (and roughly the same syntax).

We've dropped that script now, though, in favour of starting sessions from a service. This change was needed to make modern stuff reliable.

> For the records, forwarded this downstream at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013979

Thanks for adding a reference for others to find.

**Comment by calestyo** [comment]
@CendioOssman, coming back to this... it may still be buggy in upstrem as well.

I've just tried starting the VNC server via systemd, which in Debian seems to be the same than what upstream does (they just prefixed all the files with `tiger`, e.g. `tigervncsession`, but I couldn't find any patches on the source of that).

Again, when starting the server with e.g. `rfbunixpath=/home/calestyo/.vnc/socket` in `~/.vnc/config`, it actually comes up, but not starting any session, dying soon after.

Without that setting it works just normal.

On that system there is no `/usr/share/xsessions/*`, but even if I manually set e.g. `session=/usr/bin/xman` it does work with port-listening, but not with socket listening.

**Comment by calestyo** [comment]
pinging the Debian maintainer @JoachimFalk ;-)

**Comment by CendioOssman** [comment]
I'm afraid that I strongly suspect it is still using Debian's script to start the session, once `tigervncsession` has done all the low-level work for it.

Unfortunately, we don't have any Debian builds here, but I don't know if you can adapt one of the Ubuntu builds and try that?

**Comment by JoachimFalk** [comment]
Hi Pierre,

Am 29.06.22 um 08:21 schrieb Pierre Ossman (Work account):
> I'm afraid that I strongly suspect it is still using Debian's script to start the session, once |tigervncsession| has done all the low-level work for it.

it does. I will try to take a look this weekend.

Best,

Joachim
