### ISSUE TITLE
tigervncserver listening on UNIX sockets doesn't daemonise

### ISSUE THREAD

**Issue by calestyo** [TigerVNC/tigervnc#1486]
**Describe the bug**
When running `tigervncserver` with listening on UNIX sockets and even without `-fg` it won’t daemonise and continues to run in foreground.

**To Reproduce**
1. `tigervncserver -rfbunixpath=/home/calestyo/remsock :5`

**Expected behavior**
Should go in background, and subsequentially be killable just when listening on TCP via `-kill`

**Screenshots**

*Client (please complete the following information):**
not relevant

**Server (please complete the following information):**
 - OS: Debian bullseye
 - VNC server: TigerVNC
 - VNC server version: 1.11.0+dfsg-2

Cheers,
Chris.

**Comment by CendioOssman** [comment]
Like #1485, `tigervncserver` is not something from us, but rather something from Debian themselves. So it's unfortunately outside of what we can help out with.

Please report the issue to Debian, and hopefully they can help.

**Comment by calestyo** [comment]
Sorry that I had’t noticed that... but since the (somewhat older) tigervnc package of SLES also contains a corresponding `vncserver` script, I thought that it was part of upstream, without checking any further.

For the records, forwarded this downstream at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013978
