### ISSUE TITLE
Caps lock spam on kernel panic of host vm

### ISSUE THREAD

**Issue by SylvianHemus** [TigerVNC/tigervnc#1493]
TigerVNC's vncviewer on gentoo gnu+linux returns what I interpret to be a bizarre error. On kernel panic of virsh qemu vm (host vm unmountable rootfs), it spams the caps lock key on my keyboard,  when vncviewer is the focus of my window manager.

This seems like it could be something bad. I'm not exactly what's going on, but I wonder if it would be possible to use something like this for arbitrary code execution on a computer connected to a VM. But, in the words of Jeff Sokol, "Isn't that all just speculation?". Thought I would share nonetheless.

**Comment by CendioOssman** [comment]
Please fill out the issue form, so we get a better picture of your setup, like the versions of the client and server, and the steps we need to do to reproduce this.

**Comment by CendioOssman** [comment]
No response. Closing.
