### ISSUE TITLE
The clipboard uses UTF-8 to send Chinese characters, displaying garbled characters

### ISSUE THREAD

**Issue by lv-cpp** [TigerVNC/tigervnc#1498]
Server:
Xvnc TigerVNC 1.12.0 - built May 31 2022 00:00:00
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12014000, The X.Org Foundation

Client: 
     by myselft

i run Xvnc in the fedora。
the app is wps office  that like Microsoft Word 。

What should I do with clipboard encoding？
![image](https://user-images.githubusercontent.com/28625121/180350125-66dff2b8-7e71-4b39-bce3-0b884d9ef5db.png)

**Comment by lv-cpp** [comment]
here is my code 
![Uploading image.png…]()

**Comment by lv-cpp** [comment]
char str[] = {0xE4, 0xBD, 0xA0, 0xE5, 0xA5, 0xBD, 0}; // "你好"
        rfbClientCutTextMsg message;
		memset(&message, 0, sizeof(rfbClientCutTextMsg));
		message.type = rfbClientCutText;
		message.length = Swap32IfLE(strlen(str));
        WriteToRFBServer(rfb_client, (char *)&message, sz_rfbClientCutTextMsg);
        WriteToRFBServer(rfb_client, str, strlen(str));

**Comment by lv-cpp** [comment]
> 默认情况下，剪贴板数据以 Latin-1 编码。如果要使用 UTF-8，则应使用[扩展剪贴板伪编码](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#id122)。

大佬， 我可以问下其他的问题嘛。

**Comment by ximury** [comment]
Who can tell me how to use ”Extended Clipboard Pseudo-Encoding“?

**Comment by huijiecai** [comment]
> Who can tell me how to use ”Extended Clipboard Pseudo-Encoding“?

Has anyone answered this question? Please give an example.

**Comment by huijiecai** [comment]
@pdlan hello，"Is there an example?"

**Comment by huijiecai** [comment]
@pdlan hello，Is there an example?
