### ISSUE TITLE
Unable start tiger vnc service on CentOS6.5

### ISSUE THREAD

**Issue by makubex99** [TigerVNC/tigervnc#15]
I try to install tigervnc 1.1.0.8 on CentOS6.5 and got this error message tigervnc service can't start. if anyone know this issue B4 please give me link how to solve it.

from vnc log

Thu Jul 17 10:08:21 2014
 vncext: VNC extension running!
 vncext: Listening for VNC connections on all interface(s), port 5901
 vncext: Listening for HTTP connections on all interface(s), port 5801
 vncext: created VNC server for screen 0
GNOME_KEYRING_SOCKET=/tmp/keyring-mYurSW/socket
SSH_AUTH_SOCK=/tmp/keyring-mYurSW/socket.ssh
GNOME_KEYRING_PID=22938

(polkit-gnome-authentication-agent-1:22974): GLib-GObject-WARNING **: cannot register existing type `_PolkitError'

(polkit-gnome-authentication-agent-1:22974): GLib-CRITICAL **: g_once_init_leave: assertion `initialization_value != 0' failed
W: main.c: This program is not intended to be run as root (unless --system is specified).
Failed to play sound: Not available

*\* (gnome-user-share:22989): WARNING *_: gnome-user-share cannot be started as root for security reasons.
*_ Message: applet now removed from the notification area
Initializing nautilus-open-terminal extension
Initializing nautilus-gdu extension
*\* Message: applet now embedded in the notification area

Thu Jul 17 10:08:32 2014
 Connections: accepted: 192.168.0.33::29856
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Thu Jul 17 10:08:33 2014
 VNCSConnST: Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST: Client pixel format depth 8 (8bpp) color-map

(nautilus:22969): Nautilus-GDU-WARNING **: unable to query info: The specified location is not supported

*\* (nm-connection-editor:23239): WARNING **: dispose: CEPolkitButton object 0x946240 disposed twice

*\* (nm-connection-editor:23239): WARNING **: dispose: CEPolkitButton object 0x946360 disposed twice

(nautilus:22969): Nautilus-GDU-WARNING **: unable to query info: The specified location is not supported

XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":1"

```
  after 151 requests (151 known processed) with 0 events remaining.
```

polkit-gnome-authentication-agent-1: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gnome-power-manager: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
Window manager warning: gnome-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gnome-settings-daemon: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gnome-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
bluetooth-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
Fatal IO error 11 (Resource temporarily unavailable) on display ':1'.
abrt-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gdu-notification-daemon: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
nm-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
nautilus: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

*\* (gnome-volume-control-applet:22998): WARNING **: Connection failed, reconnecting...
gnome-volume-control-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
applet.py: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
evolution-alarm-notify: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gnome-screensaver: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gpk-update-icon: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

**Comment by wolfbill** [comment]
I don't think it a good way to solve the problem.Do you have another way to solve the problem.

**Comment by durack1** [comment]
@CendioOssman it seems that I'm hitting a similar problem with `tigervnc-1.7.1` on `RHEL6.8`:
```
[~/.vnc]$ Xvnc -version
Xvnc TigerVNC 1.7.1 - built Jan 19 2017 18:38:20
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11704000, The X.Org Foundation
```
And the tail of the error log after it fails:
```
[~/.vnc]$ tail -n 30 ocean.llnl.gov:1.log
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 885 requests (885 known processed) with 0 events remaining.
Window manager warning: gnome-settings-daemon: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gnome-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
Fatal IO error 11 (Resource temporarily unavailable) on display ':1'.
nautilus: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gnome-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
evolution-alarm-notify: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gdu-notification-daemon: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
abrt-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
bluetooth-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gnome-power-manager: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
<unknown>: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
rhsm-icon: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
gedit: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
eog: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
<unknown>: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
kdeinit4: Fatal IO error: client killed
gnome-screensaver: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
klauncher: Exiting on signal 15
gnome-volume-control-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
XIO:  fatal IO error 4 (Interrupted system call) on X server ":1.0"
      after 21 requests (21 known processed) with 0 events remaining.
<unknown>: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.
kDebugStream called after destruction (from virtual Konsole::SessionManager::~SessionManager() file /builddir/build/BUILD/kdebase-4.3.4/apps/konsole/src/SessionManager.cpp line 301)
Konsole SessionManager destroyed with sessions still alive
```
Has this `Fatal IO error 11 (Resource temporarily unavailable)` error popped up anywhere else before?

**Comment by hildred** [comment]
Fatal IO error 11 (Resource temporarily unavailable) on X server  is a client side error that basically means I was talking to the Xserver and all of a sudden it quit talking to me. It is almost always seen when xkill is used or when a xserver dies. The only interesting error is the segfault on the server, everything else follows from that.

**Comment by durack1** [comment]
@hildred thanks for the heads up.. This segfault is reproducible each and every time.. I quit the [Ferret software package](http://ferret.pmel.noaa.gov/Ferret/downloads/downloading_ferret) and segfaults.. I haven't tested this with other graphics windows, but am wondering what I should do to try and determine the issue..

**Comment by yongpro** [comment]
I have a similar alarms, and resolved the issue by change the  “/etc/sysconfig/vncservers”:

[root@frank ~]# vim /etc/sysconfig/vncservers
VNCSERVERS="1:root 2:cisco"
VNCSERVERARGS[3]="**-geometry 800x600 -depth 24**"
