### ISSUE TITLE
vncviewer crashes Windows after showing usage

### ISSUE THREAD

**Issue by PenaPP** [TigerVNC/tigervnc#1501]
**Describe the bug**
Both vncviewer and vncviewer64 crash on Segmentation Fault on Windows while trying to use -via option.

**To Reproduce**
1. Run vncviewer like this...
```
vncviewer-1.12.0.exe -via user@some.hostname.com localhost:1
```
2. Help is displayed with "Segmentation fault" at the end

**Expected behavior**
Connection is established and remote screen is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4574899/181004632-d20db8be-0d52-4c8f-ad5d-c888a59bc2dc.png)

**Client (please complete the following information):**
 - OS: e.g. Windows 10 21H2 (build 19044.1766)
 - VNC client: TigerVNC vncviewer
 - VNC client version: 1.12.0
 - Client downloaded from: [https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/]

**Server (please complete the following information):**
 - OS: Linux
 - VNC server: TigerVNC
 - VNC server version: 1.8.0
 - Server downloaded from: not sure
 - Server was started using: `vncserver`

**Additional context**
It seems to happen also if I run the following...
```
vncviewer-1.12.0 --help
```

**Comment by CendioOssman** [comment]
Ehmm… `-via` is not supposed to work at all on Windows. So, this is very odd. Let me have a look…

**Comment by CendioOssman** [comment]
Ah. So `-via` is a red herring. It simply crashes on every case where it tries to show the usage. I can reproduce it here, and it is apparently a FLTK bug:

https://www.fltk.org/str.php?L3484
https://github.com/fltk/fltk/commit/339ba4c8b307f025c5ef8999f8539656057d69b7

@bphinz, do you think you can have a look at patching your FLTK?

**Comment by CendioOssman** [comment]
@bphinz, a fix is now in place: https://github.com/fltk/fltk/commit/40b82358ed3315b5ed6cdaae959e00348b165ad3

**Comment by PenaPP** [comment]
Thanks for fixing the SegFault :)

Is there a chance to get the `-via` argument supported on Windows? Since there is OpenSSH the Windows machines can have the `ssh` in PATH just like linux machines.

**Comment by CendioOssman** [comment]
Not easily, no. Windows doesn't have a good system for running subprocesses like you can on Unix systems. So it would basically have to be a new method there.

@bphinz, have you had the chance to try to add the fix to your build?

**Comment by bphinz** [comment]
No, but I'll do so tonight

**Comment by bphinz** [comment]
That patch has been applied and new nightly builds posted

**Comment by CendioOssman** [comment]
I can confirm that the crash is gone here now. Thanks!
