### ISSUE TITLE
Digital Signature Check of EXE files shows countersignatures not valid

### ISSUE THREAD

**Issue by Saxomania** [TigerVNC/tigervnc#1503]
**Describe the bug**
Digital Signature Check of EXE files shows countersignatures not valid

**To Reproduce**
click on EXE file -> Properties -> Digital Signatures -> Details -> there is shown that "one of the counter signatures is not vaild. The file may have been altered."

**Expected behavior**
it should show a valid result

**Screenshots**
![JPFTQdqzvs](https://user-images.githubusercontent.com/11755505/181297656-aca110f4-1901-40c4-80ba-4dbda496c6f6.png)

**Client (please complete the following information):**
 - OS: Windows 10, Server 2019 (company devices)
 - VNC client: TigerVNC (vncviewer64.exe but has it on all EXE files)
 - VNC client version: 1.12.0
 - Client downloaded from: sourceforge

**Additional context**
double checked the problem - same error message on my private Windows 10 laptop at home

**Comment by bphinz** [comment]
Hmmm.  I'll have to look into that, thanks for bringing it to my attention

**Comment by bphinz** [comment]
This turned out to be annoyingly difficult to resolve, but it is now fixed beginning with the nightly build that I just posted.  Thanks again for raising this issue.

**Comment by bphinz** [comment]
Just for the record, the fix required: 
(1) making sure the full CA chain for the TSA cert was installed to truststore on the buildhost running osslsigncode
(2) using a newer (>2.2?) version of osslsigncode
(3) using the '-ts' (force RFC 3161 signing) rather than '-t' option to osslsigncode
