### ISSUE TITLE
`Xtigervnc -displayfb 3 ...` fails

### ISSUE THREAD

**Issue by iva2k** [TigerVNC/tigervnc#1507]
**Describe the bug**
Trying to run Xtigervnc without -display :N - there's -displayfb option in Xorg which should allow that.

**To Reproduce**
```bash
 sudo apt-get install tigervnc-standalone-server
exec 3>&2
Xtigervnc -displayfb 3
```

**Expected behavior**
Should load and run.

**Screenshots**
```bash
Unrecognized option: -displayfb
use: X [:<display>] [option]
```

**Client (please complete the following information):**
[N/A] (TigerVNC server Xtigervnc fails to start)

**Server (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - VNC server: [TigerVNC]
 - VNC server version: [Xvnc TigerVNC 1.12.0 - built 2022-03-25 17:06]
 - Server downloaded from: [my Linux distribution]
 - Server was started using: [`Xtigervnc -displayfb 3`]

**Additional context**
Changing parameter "-displayfb 3" to ":21" works with no problem. However, it is not an acceptable workaround (need multiple Xvnc instances).

**Comment by CendioOssman** [comment]
I don't get any google hits for a `-displayfb`. Where have you found that?

And what is it you are trying to achieve?

**Comment by iva2k** [comment]
@CendioOssman - you're right, somehow this Xorg option is nowhere to be found with Google.

I tried to find free display index to create virtual Xorg server under VNC for terminal server use.

I found about `-displayfb` option here: <https://stackoverflow.com/a/18166600/2694949>, and first mention here: <https://stackoverflow.com/questions/12153552/how-high-do-x11-display-numbers-go/12169545#12169545>.

I recall also seeing it in something like `man Xorg` on Ubuntu 22.04 LTS, but I'm not 100% sure about that. What I did is I confirmed Xorg does indeed provide a new free display assignment suitable for a "terminal sever" use with `-displayfb` option, and can do it many times.

Dancing around finding free display IDs is not easy, and many point out that it should not be async (find free display, then open Xorg on it), as it will lead to race conditions if multiple users do that, instead `Xorg -displayfb` is the only correct way to do it. 

So I tried `Xtigervnc -displayfb N` and discovered it did not pass it to Xorg. It would be great to make Xtigervnc just pass it to Xord unmodified, then terminal server will be trivial.

**Comment by CendioOssman** [comment]
Ah, I see the issue. The argument is `-displayfd`, not `-displayfb`. That argument I can find. :)

And a quick test here indicates it works just fine:

```console
$ exec 3>&2
$ Xvnc -displayfd 3
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running

Xvnc TigerVNC 1.12.0 - built May 31 2022 00:00:00
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12014000, The X.Org Foundation


Mon Aug 29 14:06:34 2022
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
1
```

So adjust your command line and things should hopefully work just fine.
