### ISSUE TITLE
Remembering settings?????

### ISSUE THREAD

**Issue by DocMAX** [TigerVNC/tigervnc#1509]
I would like to ask you for a most common thing: Safe settings anywhere????
What bothers me is i have to remove the menu key every time i launch the viewer:
And what an ugly interface from the 90s is that???

![grafik](https://user-images.githubusercontent.com/5351323/183374327-37279213-69d0-4695-a4b6-b8ac2a003ef9.png)

**Comment by CendioOssman** [comment]
Settings are saved if you change them before connecting. They are not saved when changed whilst connected. Which I can admit is a bit odd. It's been like that forever, though, and no one has suggested an alternative behaviour. The OK/Cancel design is probably out of fashion as well.

**Comment by DocMAX** [comment]
I change before connecting, but the Menu Key stays F8!

**Comment by CendioOssman** [comment]
Then that's a bug. Which platform is this?

**Comment by DocMAX** [comment]
It's windows.
![grafik](https://user-images.githubusercontent.com/5351323/186101127-fe13a6a9-3425-4c85-b064-f48f7bd922a6.png)

**Comment by DocMAX** [comment]
Sorry, i retested with you suggestion. It works, but you have to get used to it. It saving ONLY on CONNECT, not on OK.
