### ISSUE TITLE
In Linux Mint 21, the cursor can’t click

### ISSUE THREAD

**Issue by mauricev** [TigerVNC/tigervnc#1511]
**Describe the bug**
In Linux Mint 21, the cursor can’t click.

**To Reproduce**
1. Install tigervncserver_1.12.0-1ubuntu1_amd64.deb
2. Set it up for a single user
4. Login with a VNC client 
6. The GUI appears and the mouse cursor can move around and that’s all.

**Expected behavior**
Mint should respond to mouse clicks, but it’s ignoring them.

**Client (please complete the following information):**
 - OS: Mac Monterey
 - VNC client: RealVNC
 - VNC client version: 6.22.515
 - Client downloaded from: RealVNC site

**Server (please complete the following information):**
 - OS: Mint 21
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: sourceforge
 - Server was started using: systemctl

**Comment by samhed** [comment]
Could you test the TigerVNC viewer? Perhaps its some kind of issue with RealVNC's client?

**Comment by mauricev** [comment]
I tried it again and now it's working with RealVNC. Real problem, https://github.com/TigerVNC/tigervnc/issues/1504, remains.
