### ISSUE TITLE
Crash of TigerVNC v1.12.0 on apple m1 silicon 

### ISSUE THREAD

**Issue by abrekhov** [TigerVNC/tigervnc#1515]
**Describe the bug**
App crashes if click to Options button.

**To Reproduce**
1. Go to TigerVNC.app
2. Click on 'Options'

**Expected behavior**
Open window with options.

**Client (please complete the following information):**
 - OS: macos Monterey
 - VNC client: TigerVNC
 - VNC client version: 1.12.0
 - Client downloaded from: brew and sourceforge

**Additional context**

**Comment by CendioOssman** [comment]
This should be fixed for the next version. Please try the nightly build until a new stable release is out.
