### ISSUE TITLE
Bintray does not have any binaries for latest 1.4.3

### ISSUE THREAD

**Issue by jeffmcneill** [TigerVNC/tigervnc#152]
None listed here: https://bintray.com/tigervnc/stable/tigervnc/1.4.3

**Comment by CendioOssman** [comment]
To see all binaries you have to click on "Files". The first page only shows some quick shortcuts (which were overlooked for 1.4.3).

**Comment by jeffmcneill** [comment]
That is still highly misleading. I try and navigate by breadcrumbs and versions and nothing shows up, while it does for other versions. Either remove the quick shortcuts page/breadcrumb navigation and default to files, or add the quick shortcuts.

**Comment by CendioOssman** [comment]
I'm afraid I don't think there are any settings that can control that. It's not like there's a lot of options for hosting our files, so we're going to have to make due with bintray's quirks.

**Comment by jeffmcneill** [comment]
Why not put the binaries on Github? Or Sourceforge?

**Comment by CendioOssman** [comment]
github doesn't have a good way of managing a lot of files (no folders). They've also been a bit sceptical about allowing too many binaries, so we'll most likely get told to stop if we start putting stuff here.

Sourceforge is not a general file hosting, and it would be confusing to have a project both here and there. They've also had some less than desirable ways of handling ads in connection with downloads. We do still use them for the nightly builds though, but that's because we haven't found anything else.

**Comment by jeffmcneill** [comment]
I understand the issue better now. Though there are many open source projects who do use sourceforge for downloads, in addition to having files in other locations as well as a separate website. I've always thought that was the most common free way to go for open source (Sourceforge + Github). From a user perspective that is more common (and easier to navigate), IMO.

**Comment by bphinz** [comment]
On Tue, Mar 17, 2015 at 5:58 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> I'm afraid I don't think there are any settings that can control that.
> It's not like there's a lot of options for hosting our files, so we're
> going to have to make due with bintray's quirks.
>
I had looked several times at this and just now figured out how to do it.
When you go to the "files" section there is an "actions" drop down list on
the right side that allows you to add a file to the direct downloads page.
However, I noticed that for the last item in the list the options in the
drop down list are obscured by their page footer (at least as rendered by
safari…).

-brian

**Comment by bphinz** [comment]
On Tue, Mar 17, 2015 at 6:17 AM, Brian Hinz wrote:

> On Tue, Mar 17, 2015 at 5:58 AM, Pierre Ossman (Work account) <
> notifications@github.com> wrote:
>
>> I'm afraid I don't think there are any settings that can control that.
>> It's not like there's a lot of options for hosting our files, so we're
>> going to have to make due with bintray's quirks.
>>
> I had looked several times at this and just now figured out how to do it.
> When you go to the "files" section there is an "actions" drop down list on
> the right side that allows you to add a file to the direct downloads page.
> However, I noticed that for the last item in the list the options in the
> drop down list are obscured by their page footer (at least as rendered by
> safari…).
>

I've gone back and updated the downloads list for all releases, as well as
added a note in the description instructing users to browse the files
section for access to the pre-built distro packages (putting them all on
the direct downloads list is too cluttered and, in the case of
indistinguishable package names, not always possible).

I also put in a ticket with bintray support regarding the page footer
issue, which at the moment prevents me from adding the 64-bit Windows
viewer to the direct downloads list.

-brian
