### ISSUE TITLE
vncserver doesn't work with LDAP user on CentOS 7

### ISSUE THREAD

**Issue by phyzhenli** [TigerVNC/tigervnc#1530]
**Describe the bug**
I use tigervnc 1.8 on CentOS 7. The command `vncserver :88` works perfectly with a local user1. However, when with a LDAP user2, the command doesn't work and outputs an error:
```
/home/$USER/.vnc/xstartup: line 5:  7804 Trace/breakpoint trap   (core dumped) /etc/X11/xinit/xinitrc
Killing Xvnc process ID 7754
```
Strangely, the same command can work on another machine (ubuntu 18.04) with LDAP user2.
I found `/etc/pam.d/tigervnc` on ubuntu, but there is no existing same file on CentOS. I searched for the error and checked the past issues and discussions but still can not solve it.

**To Reproduce**
1. On CentOS 7: install tigervnc and configure a user using LDAP that does not appear as a local system user.
2. Run `vncserver :88`.
3. See `~/.vnc/$hostname:88.log`.

**Expected behavior**
The vncserver starts successfully.

**Screenshots**
N/A

**Client (please complete the following information):**
N/A

**Server (please complete the following information):**
 - OS: CentOS 7
 - VNC server: TigerVNC
 - VNC server version: 1.8.0
 - Server downloaded from: my Linux distribution
 - Server was started using: `vncserver :88`

**Additional context**
The `/var/log/messages` after running `vncserver :88`:
```
Sep 26 16:04:22 venus gnome-session: gnome-session-binary[32453]: ERROR: Failed to connect to system bus: Exhausted all available authentication mechanisms (tried: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS) (available: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS)
Sep 26 16:04:22 venus gnome-session: aborting...
Sep 26 16:04:22 venus kernel: traps: gnome-session-b[32453] trap int3 ip:7f5e7c147be1 sp:7fff714b7110 error:0 in libglib-2.0.so.0.5600.1[7f5e7c0f6000+114000]
Sep 26 16:04:22 venus gnome-session-binary[32453]: ERROR: Failed to connect to system bus: Exhausted all available authentication mechanisms (tried: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS) (available: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS)#012aborting...
Sep 26 16:04:23 venus abrt-hook-ccpp: Process 32453 (gnome-session-binary) of user 1500 killed by SIGTRAP - dumping core
Sep 26 16:04:23 venus org.a11y.atspi.Registry: X connection to :88 broken (explicit kill or server shutdown).
Sep 26 16:04:23 venus com.redhat.imsettings: [ 1664179463.190554]: IMSettings-Daemon[32516]: INFO: Release the ownership of com.redhat.imsettings
Sep 26 16:04:23 venus org.gtk.vfs.Daemon: A connection to the bus can't be made
Sep 26 16:04:23 venus com.redhat.imsettings: Exiting...
Sep 26 16:04:23 venus com.redhat.imsettings: [ 1664179463.191456]: GLib-GIO[32516]: CRITICAL **: Error while sending AddMatch() message: The connection is closed
Sep 26 16:04:23 venus com.redhat.imsettings: [ 1664179463.191664]: GLib-GIO[32516]: CRITICAL **: Error while sending AddMatch() message: The connection is closed
```

**Comment by CendioOssman** [comment]
Unfortunately, TigerVNC 1.8.0 is very ancient, and not something we can really support anymore. Could you try with the latest version from us instead? You can find packages on our release page.

Note that sessions are set up a bit different in the current versions of TigerVNC:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

**Comment by phyzhenli** [comment]
> Unfortunately, TigerVNC 1.8.0 is very ancient, and not something we can really support anymore. Could you try with the latest version from us instead? You can find packages on our release page.
> 
> Note that sessions are set up a bit different in the current versions of TigerVNC:
> 
> https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

Thank you very much for your prompt reply! I will try it.

**Comment by quyleanh** [comment]
Same here. The Redhat 7 server has installed TigerVNC 1.8.0 and I can't connect.
