### ISSUE TITLE
How to force user vnc password to expire？

### ISSUE THREAD

**Issue by ChangJieWuAi** [TigerVNC/tigervnc#1531]
I want to try to expire the user's vnc password, is there any way to achieve this?
I forced the user's login password to expire, but his vnc can still log in with the old password. After all, the user password is different from the vnc password.
Is there a way to make the user password match the vnc password, or force the vnc password to expire?

**Comment by CendioOssman** [comment]
I'm afraid there is no mechanism about forcing password changes in VNC, so all you can do is change the VNC password. To do that, you'll need to run `vncpasswd` as the user.

You can use system passwords if you use the "Plain" security types. However, that also requires the VNC server to run as root, which can be a security risk.
