### ISSUE TITLE
how to configure and make in centos7.9

### ISSUE THREAD

**Issue by blatwo** [TigerVNC/tigervnc#1534]
The following is my processes，but make with error：
make[2]: *** No rule to make target `tigervnc/common/network/libnetwork.la', needed by `libvnc.la'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CXXLD    libvnccommon.la
make[2]: Leaving directory `/root/tigervnc/unix/xserver/hw/vnc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/tigervnc/unix/xserver/hw'
make: *** [all-recursive] Error 1

----------------------------------------------------------
yum install -y automake autoconf libtool libtool-ltdl-devel 
yum install -y xorg-x11-util-macros xorg-x11-font-utils xorg-x11-xtrans-devel pixman pixman-devel \
               libX11-devel mesa-libGL-devel libXfont2 libXfont2-devel libxkbfile libxkbfile-devel pam pam-devel
yum install -y xorg-x11-server-source

cd tigervnc 
cp -R /usr/share/xorg-x11-server-source/* unix/xserver/
cd unix/xserver/ 
patch -p1 < /root/tigervnc/unix/xserver120.patch

autoreconf -fiv

./configure --with-pic --without-dtrace --disable-static --disable-dri \
      --disable-xinerama --disable-xvfb --disable-xnest --disable-xorg \
      --disable-dmx --disable-xwin --disable-xephyr --disable-kdrive \
      --disable-config-dbus --disable-config-hal --disable-config-udev \
      --disable-dri2 --enable-install-libxf86config --enable-glx \
      --with-default-font-path="catalogue:/etc/X11/fontpath.d,built-ins" \
      --with-fontdir=/usr/share/X11/fonts \
      --with-xkb-path=/usr/share/X11/xkb \
      --with-xkb-output=/var/lib/xkb \
      --with-xkb-bin-directory=/usr/bin \
      --with-serverconfig-path=/usr/lib[64]/xorg \
      --with-dri-driver-path=/usr/lib[64]/dri \
      {additional configure options}

export CPPFLAGS='-I/root/tigervnc/unix/vncconfig -I/root/tigervnc/unix/common -I/root/tigervnc/common'

make -j$(nproc) TIGERVNC_SRCDIR=tigervnc

**Comment by CendioOssman** [comment]
You need to build the normal parts of TigerVNC first. I.e. run cmake and make in the root directory.

You also shouldn't override CPPFLAGS. It should find things on itself.

I suggest looking at how the RPM is built for RHEL 7:

https://github.com/TigerVNC/tigervnc/blob/master/contrib/packages/rpm/el7/SPECS/tigervnc.spec

Build logs here:

https://github.com/TigerVNC/tigervnc/actions/runs/3007769731/jobs/4830696093
