### ISSUE TITLE
Seg fault with libvnc.so for Xorg-server-21.1.4-1

### ISSUE THREAD

**Issue by vielfarbig** [TigerVNC/tigervnc#1536]
**Describe the bug**
There is a segfault with libvnc.so for Xorg-server-21.1.4-1 like in https://github.com/TigerVNC/tigervnc/pull/1383:
```
(EE) 
(EE) Backtrace:
(EE) 0: /usr/lib/Xorg (dri3_send_open_reply+0xdd) [0x558eff20ebad]
(EE) 1: /usr/lib/libc.so.6 (__sigaction+0x50) [0x7ff0007e2a00]
(EE) 2: /usr/lib/Xorg (xf86OptionValue+0xb) [0x558eff21b50b]
(EE) 3: /usr/lib/xorg/modules/extensions/libvnc.so (vncExtensionInit+0xa31) [0x7fefffe3e2f1]
(EE) 4: /usr/lib/Xorg (InitExtensions+0x89) [0x558eff0faf29]
(EE) 5: /usr/lib/Xorg (SProcXkbDispatch+0x1809) [0x558eff0ee054]
(EE) 6: /usr/lib/libc.so.6 (__libc_init_first+0x90) [0x7ff0007cd290]
(EE) 7: /usr/lib/libc.so.6 (__libc_start_main+0x8a) [0x7ff0007cd34a]
(EE) 8: /usr/lib/Xorg (_start+0x25) [0x558eff0ef475]
(EE) 
(EE) Segmentation fault at address 0x100000011
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
```

**To Reproduce**
1. Install/Update Archlinux
2. Install tigervnc (Version tigervnc-1.12.0-3)
3. Restart
gmd does not start, because xorg crashes because of the seg fault with the vncextension

I am not completly sure if it is on the vncextension, but if i remove tigervnc, the segfault does not appear, if I am `startx`

**Comment by vielfarbig** [comment]
Yes that could be the issue, but I cannot verify it. https://archlinux.org/packages/community/x86_64/tigervnc/ refers to https://github.com/archlinux/svntogit-community/tree/packages/tigervnc/trunk where the PKGBUILD does not contain specific version numbers. But the build could be older. Someone how has more experience regarding the arch building should have a look.

**Comment by CendioOssman** [comment]
There is actually a version number for xorg in there; "1.20.9". And from what I can see, the actual X server i on version 21.1.4. So that is the most likely cause for the crashes.

Please file a bug with the Arch TigerVNC maintainer so they can have a look at rebuilding TigerVNC for the new X server. If it still crashes after that, then we can dig further.
