### ISSUE TITLE
vncserver: couldn't find "/bin/Xvnc"

### ISSUE THREAD

**Issue by Tomquim** [TigerVNC/tigervnc#1537]
I am trying to install tigervnc on a buildroot system.
I installed version v1.10.1 ( if I am not wrong, the same version installed by apt-get ) 
when I run a command with vncserver I get the error:
```
# vncserver 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
vncserver: couldn't find "/bin/Xvnc".
```

Indeed, /bin/Xvnc is not installed on my system but it seems to be installed when I do `apt-get install tigervnc-standalone-server`.
How could I build tigervnc to have Xvnc installed on my buildroot system?

My .mk and Config.in look like that:

```
################################################################################
#
# Tiger vnc
#
################################################################################
TIGERVNC_VERSION = v1.10.1
TIGERVNC_SITE = https://github.com/TigerVNC/tigervnc
TIGERVNC_SITE_METHOD = git
TIGERVNC_DEPENDENCIES = jpeg-turbo fltk gnutls linux-pam pixman

$(eval $(cmake-package))
```

and 

```
config BR2_PACKAGE_TIGERVNC
    bool "tigervnc"
    select BR2_PACKAGE_JPEG_TURBO
    select BR2_PACKAGE_FLTK
    select BR2_PACKAGE_GNUTLS
    select BR2_PACKAGE_LINUX_PAM
    select BR2_PACKAGE_PIXMAN
    help
        TigerVNC is a high-speed version of VNC based on the RealVNC 4
        and X.org code bases. TigerVNC started as a next-generation
        development effort for TightVNC on Unix and Linux platforms,
        but it split from its parent project in early 2009 so that
        TightVNC could focus on Windows platforms.
        TigerVNC supports a variant of Tight encoding that is greatly
        accelerated by the use of the libjpeg-turbo JPEG codec.
```

**Comment by CendioOssman** [comment]
I'm afraid I don't know what build system that is, so I can't give much in the way of specifics. But the general answer is to look in `BUILDING.txt` for how to build Xvnc.

Note that building an X server can be a complex beast, so it can be useful to look at how your distribution builds X and try to copy that. I think the instructions in `BUILDING.txt` are based on how Red Hat used to do things.
