### ISSUE TITLE
Stuck `Alt` key when pressing`Cmd` + `Shift` + `4`, then releasing `Cmd`, `Shift` and `4` in the same order

### ISSUE THREAD

**Issue by matlupi** [TigerVNC/tigervnc#1539]
Following the discussion in #345 linked here:

        @lodagro The original issue turned out to be a problem with the TurboVNC Viewer's keyboard handling logic, so this specific issue was not a TigerVNC bug.  You may be experiencing an unrelated issue.

_Originally posted by @dcommander in https://github.com/TigerVNC/tigervnc/issues/345#issuecomment-351469993_
      
My system:
Viewer: v1.11.0 (on macOS 12.5)
Server: v1.9.0 (on CENTOS 7.5)

**Comment by CendioOssman** [comment]
I'm a bit confused, are you getting Ctrl stuck even though you don't actually press that specific key?

Exactly how are you seeing that Ctrl is stuck?

**Comment by matlupi** [comment]
This is the part it took me the most to figure out.
Whenever this bug is manifesting, the keyboard gets remapped as if `Ctrl` is continuously pressed.
This means (on a terminal, but the same effect is obtained on an open IDE)

Press `b` -> cursor moves left
Press `p` -> cursor moves up
Press `n` -> cursor moves down 
etc.

Let me know if you have any additional question.

**Comment by CendioOssman** [comment]
I tried to reproduce it here, and I'm unable to get the behaviour of a stuck `Ctrl`. If I press `b`, it moves one word, which is consistent with a stuck `Alt`. A stuck `Ctrl` should move just a single character. At least with bash.

What terminal and shell are you using? In my test it was mate-terminal and bash.

**Comment by CendioOssman** [comment]
I tried gnome-terminal (3.44.1) and csh (6.24.01) here, and I'm afraid I'm still just getting a stuck `Alt`, not a stuck `Ctrl`.

Just to double check, when everything is working correctly, does the cursor move a single character to the left when you press `Ctrl`+`b`? And a whole word when you press `Cmd`+`b`?

**Comment by matlupi** [comment]
I just reproduced the issue and effectively the cursor moves by a full word which is compatible with the `Alt` key getting stuck.

I can also confirm that when pressing `Cmd`+`b` (on a mac, `Alt`+`b` on a linux machine) the cursor advances by a whole word in gnome-terminal, in the VNC session.

**Comment by CendioOssman** [comment]
Great. I just wanted to make sure we're seeing the same thing. Alt should of course also not get wedged.

I think there is a fixe for this in #1375. It's not trivial to port to `master`, though, but I can try to have a look.

**Comment by CendioOssman** [comment]
It should be fixed in 4f6d4895c3420e5ac301a916bced4a0065a19183. Please try the next nightly build and things should work better.
