### ISSUE TITLE
Can no longer start a Session

### ISSUE THREAD

**Issue by m00nglum** [TigerVNC/tigervnc#1542]
I just updated my system, and got the 1.12.0 version.

Since then, I have not been able to start a vnc server with a Plasma session.  I'm testing everything locally, and I've stripped down my command (for testing purposes) to something very simple:
tigervncserver -xstartup /home/me/.vnc/xstartup

It is the same xstartup I always used, and it worked until the update.  The contents are:

dbus-launch /usr/bin/startplasma-x11 &

I've tried using exec, and tried just running startplasma-x11 directly, and of course, that doesn't work either.

So I back down to something even simpler (as suggested by the tigervncserver output):
tigervncserver -xstartup /usr/bin/xterm

That launches fine.  I'm able to connect to the xterm.  If I fire up plasma-x11 from there, it seems to work.. same for twm. but if I try to start either directly from my xstartup -- it fails.  I'm using KDE Neon with the Ubuntu base of 22.04.  

The error output I get when trying to launch it (with the xstartup file conaining "dbus-launch /usr/bin/startplasma-x11 &"):
New Xtigervnc server 'me-lin2:1 (me)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /home/me/.vnc/passwd :1 to connect to the VNC server.

=================== tail /home/me/.vnc/me-lin2:5901.log ===================
======================================================================================

Session startup via '/home/me/.vnc/xstartup' cleanly exited too early (< 3 seconds)!

Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
The X session cleanly exited!
Killing Xtigervnc process ID 31652... success!

The contents of /home/me/.vnc/me-lin2:5901.log
Fri Nov  4 08:31:56 2022
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5901
 vncext:      created VNC server for screen 0
[mi] mieq: warning: overriding existing handler (nil) with 0x55e7f3065400 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x55e7f3065400 for event 3
3NI3X0 New Xtigervnc server 'me-lin2:1 (me)' on port 5901 for display :1.
3NI3X0 Use xtigervncviewer -SecurityTypes VncAuth -passwd /home/me/.vnc/passwd :1 to connect to the VNC server.
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
$DISPLAY is not set or cannot connect to the X server.

Something changed, I just don't know what it wants from me now...

Thank you.

**Comment by m00nglum** [comment]
They might do that... but I don't use their services... I just run it  
ala carte...


Quoting "Pierre Ossman (Work account)" ***@***.***>:

**Comment by m00nglum** [comment]
Hi.

As I stated, I'm not using this the "ubuntu way".  I'm just launching  
a server from one machine, and using the client on the other machine.   
It comes straight from the man pages -- not the ubuntu documentation.  
I have no interest in learning methods of administration that work on  
only one flavor of linux... I deal with too many.

Anyway, I figured this out.  It makes no sense to me, but it works:   
eliminate the '&' at the end of the xstartup command, and it works.   
For over a decade, I've used an & at the end of the command, but for  
whatever reason, this has changed.  Just get rid of it, and it works  
much like it always has.  I assume this change was deliberate (though  
I couldn't find it documented anywhere), and probably not a bug.

Hopefully this post helps someone else.

G



Quoting "Pierre Ossman (Work account)" ***@***.***>:

**Comment by Cusbt1986** [comment]
New Xtigervnc server 'localhost.localdomain:0 (kali)' on port 5900 for display :0.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /home/kali/.config/tigervnc/passwd :0 to connect to the VNC server.


=================== tail /home/kali/.config/tigervnc/localhost.localdomain:0.log ===================
[mi] mieq: warning: overriding existing handler (nil) with 0x30001e8920 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x30001e8920 for event 3
X connection to :0 broken (explicit kill or server shutdown).

Tue Mar 24 12:00:04 2026
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:nan ratio)
Killing Xtigervnc process ID 5546... success!
====================================================================================================

Session startup via '/etc/X11/Xtigervnc-session' cleanly exited too early (< 3 seconds)!

Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
The X session cleanly exited!
The Xtigervnc server cleanly exited!

Somboy help me please
