### ISSUE TITLE
Wrapper.pm doesn't create temporary directory for passwdfile

### ISSUE THREAD

**Issue by dobsonaron** [TigerVNC/tigervnc#1543]
When starting the server, the passwd file from the user's home directory (~/.vnc/passwd) isn't copied to /tmp/tigervnc.XXXXXX folder, because the folder is not created by Wrapper.pm.
Ubuntu 22,10 fresh upgrade, tigervnc-common-1.12.0+dfsg-5 

Actually checking things, it seems that line 961 in Wrapper.pm is the problem, specifying  CLEANUP => 1 for newdir() means that the temporary folder is being deleted after the wrapper script exits. Changing it to 0 (disabling cleanup) solves the problem.

**To Reproduce**
simply start the vncserver or tigervncserver (I also specify "-PasswordFile" as an option, but it should default to ~/.vnc/passwd), and try to connect to the server with a client. Password will not be accepted because the passwd file in /tmp is missing.

**Expected behavior**
Passwd file is in /tmp and password is accepted by the server.

**Client (please complete the following information):**
 - OS: windows 11
 - VNC client: TigerVNC on windows (but it doesn't really matter in my case)
 - VNC client version: 1.12.0
 - Client downloaded from: internet somewhere

**Server (please complete the following information):**
 - OS: ubuntu 22.10 on a PI4b
 - VNC server: [TigerVNC
 - VNC server version: 1.12.0+dfsg-5
 - Server downloaded from: ubuntu repo with apt
 - Server was started using: vncserver -localhost no -verbose  -autokill no -PasswordFile=/home/aron/.vnc/passwd :20

Error message from the session log:
 SVncAuth:    opening password file '/tmp/tigervnc.5YL0x0/passwd' failed
 SConnection: AuthFailureException: Authentication failure: No password
              configured for VNC Auth

The folder doesn't exist in /tmp.

**Comment by CendioOssman** [comment]
`Wrapper.pm` is unfortunately not part of standard TigerVNC, but is something special that Debian/Ubuntu adds. So I'm afraid we cannot help you out with that. You'll need to file a report with Ubuntu.
