### ISSUE TITLE
Program crashes on connecting to a SSDNodes VPS 

### ISSUE THREAD

**Issue by vivekteega** [TigerVNC/tigervnc#1544]
**Describe the bug**
The TigerVNC app crashes upon trying to connect to a SSDNodes VPS 

**Log Report**
TigerVNC crash log report [Github gist ](https://gist.github.com/vivekteega/4fe554b084b525f3822dc04d5feacd38)

**Comment by CendioOssman** [comment]
Thanks for your bug report.

The crash looks secondary, though, as it is happening as TigerVNC is shutting down. There seems to be something else that goes amiss first.

Could you try enabling debug logging, as described here, and see what you get:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs#os-x

**Comment by CendioOssman** [comment]
No response. Closing.
