### ISSUE TITLE
`Invalid PixelBuffer width of 23073 pixels requested` error on connect

### ISSUE THREAD

**Issue by matlupi** [TigerVNC/tigervnc#1546]
**Describe the bug**
Strange bug on connect using TigerVNC.
Session was already working, after disconnect and re-connect it does not work any more.

**To Reproduce**
1. Connect to a running server
2. Disconnect
3. Reconnect with `vncviewer <host>:<display> -passwd <path-to-passwd-file>`

**Bug behaviour**

See last line, `Invalid PixelBuffer width of 23073 pixels requested`

```
TigerVNC Viewer 64-bit v1.12.0
Built on: 2021-11-09 07:55
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Tue Nov  8 09:11:16 2022
 DecodeManager: Detected 6 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       Connected to host micgate03 port 5973
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VeNCrypt(19)
 CVeNCrypt:   Choosing security type TLSVnc (258)
 CConn:       Invalid PixelBuffer width of 23073 pixels requested
```

**Expected behavior**

**Client (please complete the following information):**
 - OS: CentOS 7.5 (same behaviour on on macOS 12.5 with same client version)
 - VNC client: TigerVnc
 - VNC client version: `TigerVNC Viewer 64-bit v1.12.0 Built on: 2021-11-09 07:55`
 - Client downloaded from: Linux Distro

**Server (please complete the following information):**
 - OS: CentOS 7.5
 - VNC server: TigerVnc
 - VNC server version: v1.9.0 (on CENTOS 7.5)
 - Server downloaded from: Linux Distro
 - Server was started using: `vncserver`

**Comment by CendioOssman** [comment]
That usually means some bug in the protocol handling.

Could you add the parameter `-Log *:stderr:100` to the client and see if we get more details?

**Comment by matlupi** [comment]
Thanks for the quick answer.
Will do, need to wait for next occurrence though.

**Comment by CendioOssman** [comment]
Have you seen any more cases of this issue?

**Comment by matlupi** [comment]
Not since beginning of November. 

I see it sporadically.
When it happens is has a big impact as I have to kill and re-start the session.
I'll post here the answer to the question above once I see it again.

**Comment by CendioOssman** [comment]
Thanks for the update. I'll close this for now, but we can reopen it once there are some more details to investigate.

**Comment by matlupi** [comment]
It happened again. Here is the log:

```
>>>
TigerVNC Viewer 64-bit v1.12.0
Built on: 2021-11-09 07:55
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Thu Jan 26 09:37:59 2023
 Config:      set PasswordFile(String) to
              <REDACTED>
 DecodeManager: Detected 6 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to <REDACTED> [<REDACTED>] port <REDACTED>
 CConn:       Connected to host <REDACTED> port <REDACTED>
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: processing security types message
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Choosing security type VeNCrypt(19)
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CVeNCrypt:   Server offers security type TLSVnc (258)
 CVeNCrypt:   Choosing security type TLSVnc (258)
 CConnection: processing security message
 TLS:         Anonymous session has been set
 TLS:         Deferring completion of TLS handshake: Resource temporarily
              unavailable, try again.
 CConnection: processing security message
 TLS:         Deferring completion of TLS handshake: Resource temporarily
              unavailable, try again.
 CConnection: processing security message
 TLS:         TLS handshake completed with
              (TLS1.2)-(ANON-ECDH)-(AES-256-CBC)-(SHA1)
 CConnection: processing security result message
 CConnection: processing security result message
 CConnection: Authentication success!
 CConnection: reading server initialisation
 CConnection: reading server initialisation
 CConnection: initialisation done
 Viewport:    No key mapping for key LVL3
 Viewport:    No key mapping for key I178
 Viewport:    No key mapping for key I182
 Viewport:    No key mapping for key I183
 Viewport:    No key mapping for key MDSW
 Viewport:    No key mapping for key ALT
 Viewport:    No key mapping for key META
 Viewport:    No key mapping for key SUPR
 Viewport:    No key mapping for key HYPR
 Viewport:    No key mapping for key I248
 Viewport:    No key mapping for key I249
 Viewport:    No key mapping for key I250
 Viewport:    No key mapping for key I251
 Viewport:    No key mapping for key I252
 Viewport:    No key mapping for key I253
 Viewport:    No key mapping for key I254
 PlatformPixelBuffer: Using shared memory XImage
 CConn:       Invalid PixelBuffer width of 32193 pixels requested
```

**Comment by matlupi** [comment]
@CendioOssman, can we re-open the issue? I belive I do not have the permission to do so.

**Comment by matlupi** [comment]
Hi, at the moment I'm NOT in the measure to change the server version for time being (it will take time to arrange sandbox configuration for that). Will keep you posted as soon as it is ready and running.

Posting the log of the correct connection in a minute.

**Comment by matlupi** [comment]
Here is the log of a succesful connection

```
>>>

TigerVNC Viewer 64-bit v1.12.0
Built on: 2021-11-09 07:55
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Thu Jan 26 17:46:15 2023
 Config:      set PasswordFile(String) to
              <REDACTED>
 DecodeManager: Detected 6 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to <REDACTED> [<REDACTED>] port <REDACTED>
 CConn:       Connected to host <REDACTED> port <REDACTED>
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: processing security types message
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Choosing security type VeNCrypt(19)
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CVeNCrypt:   Server offers security type TLSVnc (258)
 CVeNCrypt:   Choosing security type TLSVnc (258)
 CConnection: processing security message
 TLS:         Anonymous session has been set
 TLS:         Deferring completion of TLS handshake: Resource temporarily
              unavailable, try again.
 CConnection: processing security message
 TLS:         Deferring completion of TLS handshake: Resource temporarily
              unavailable, try again.
 CConnection: processing security message
 TLS:         TLS handshake completed with
              (TLS1.2)-(ANON-ECDH)-(AES-256-CBC)-(SHA1)
 CConnection: processing security result message
 CConnection: processing security result message
 CConnection: Authentication success!
 CConnection: reading server initialisation
 CConnection: reading server initialisation
 CConnection: initialisation done
 Viewport:    No key mapping for key LVL3
 Viewport:    No key mapping for key I178
 Viewport:    No key mapping for key I182
 Viewport:    No key mapping for key I183
 Viewport:    No key mapping for key MDSW
 Viewport:    No key mapping for key ALT
 Viewport:    No key mapping for key META
 Viewport:    No key mapping for key SUPR
 Viewport:    No key mapping for key HYPR
 Viewport:    No key mapping for key I248
 Viewport:    No key mapping for key I249
 Viewport:    No key mapping for key I250
 Viewport:    No key mapping for key I251
 Viewport:    No key mapping for key I252
 Viewport:    No key mapping for key I253
 Viewport:    No key mapping for key I254
 PlatformPixelBuffer: Using shared memory XImage
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 Config:      set FullScreen(Bool) to 1
 CConnection: Enabling continuous updates
 CConn:       Throughput 19998 kbit/s - changing to quality 8
 Config:      set QualityLevel(Int) to 8
 DesktopWindow: Ignored synthetic focus event cause by grab change
 DesktopWindow: Ignored synthetic focus event cause by grab change

Thu Jan 26 17:46:16 2023
 DesktopWindow: Requesting framebuffer resize from 5120x1440 to 1024x768
 DesktopWindow: 1 screen(s)
 DesktopWindow:              0 (0x00000000): 1024x768+0+0 (flags 0x00000000)
 DesktopWindow: 
 Viewport:    Resizing framebuffer from 5120x1440 to 1024x768
 PlatformPixelBuffer: Using shared memory XImage
 PlatformPixelBuffer: Freeing shared memory XImage

Thu Jan 26 17:46:19 2023
 DesktopWindow: Ignored synthetic focus event cause by grab change
 DesktopWindow: Ignored synthetic focus event cause by grab change
 DesktopWindow: Failure grabbing keyboard
 DesktopWindow: Failure grabbing keyboard
```

**Comment by CendioOssman** [comment]
Unfortunately, they are identical up to the failure, so no clue there. :/

I've been assuming a protocol bug here, but perhaps we should make sure the screen isn't screwed up in some way.

Do you have a server log from when the reconnects fail?

And can you log in some other way (e.g. ssh) and run `xrandr` for the X server? You'll need to set `DISPLAY` to the proper value first.

**Comment by matlupi** [comment]
The issue appeared again while running on a sandbox server running a more recent version (1.13.0 beta, i.e. 1.12.90).

Here is the client-side log (logging increased) on a mac

```
<REDACTED>@<REDACTED> % vncmic 73

TigerVNC Viewer v1.12.90
Built on: 2022-12-22 22:12
Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Mon Feb 27 09:39:11 2023
 Config:      set PasswordFile(String) to /Users/<REDACTED>/.vnc/<REDACTED>
 Config:      set UseIPv6(Bool) to 0(0)
 Config:      set PointerEventInterval(Int) to 50
(<REDACTED>@<REDACTED>) Password: 

Mon Feb 27 09:39:15 2023
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to <REDACTED> [<REDACTED>] port <REDACTED>
 CConn:       Connected to host <REDACTED> port <REDACTED>

Mon Feb 27 09:39:16 2023
 CConnection: reading protocol version
 CConn:       End of stream
 CConn:       The connection was dropped by the server before the session could
              be established.
 DecodeManager:   Total: 0 rects, 0 pixels
 DecodeManager:          0 B (1:nan ratio)
```

Here is the client-side log (logging increased) on a linux machine

```
[<REDACTED>@<REDACTED> ~]$ vncmic 73

TigerVNC Viewer v1.12.90
Built on: 2022-12-15 15:53
Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Mon Feb 27 10:44:14 2023
 Config:      set PasswordFile(String) to
              /<REDACTED>/.vnc/<REDACTED>
 DecodeManager: Detected 6 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to <REDACTED> [<REDACTED>] port <REDACTED>
 TcpSocket:   Failed to connect to address <REDACTED> port <REDACTED>: 111
 CConn:       unable to connect to socket: Connection refused (111)
 DecodeManager:   Total: 0 rects, 0 pixels
 DecodeManager:          0 B (1:-nan ratio)
```

I'm trying to get the server logs.
Will post them if available.

**Comment by matlupi** [comment]
> The issue appeared again while running on a sandbox server running a more recent version (1.13.0 beta, i.e. 1.12.90).
> 
> Here is the client-side log (logging increased) on a mac
> 
> ```
> <REDACTED>@<REDACTED> % vncmic 73
> 
> TigerVNC Viewer v1.12.90
> Built on: 2022-12-22 22:12
> Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
> See https://www.tigervnc.org for information on TigerVNC.
> 
> Mon Feb 27 09:39:11 2023
>  Config:      set PasswordFile(String) to /Users/<REDACTED>/.vnc/<REDACTED>
>  Config:      set UseIPv6(Bool) to 0(0)
>  Config:      set PointerEventInterval(Int) to 50
> (<REDACTED>@<REDACTED>) Password: 
> 
> Mon Feb 27 09:39:15 2023
>  DecodeManager: Detected 4 CPU core(s)
>  DecodeManager: Creating 4 decoder thread(s)
>  TcpSocket:   Connecting to <REDACTED> [<REDACTED>] port <REDACTED>
>  CConn:       Connected to host <REDACTED> port <REDACTED>
> 
> Mon Feb 27 09:39:16 2023
>  CConnection: reading protocol version
>  CConn:       End of stream
>  CConn:       The connection was dropped by the server before the session could
>               be established.
>  DecodeManager:   Total: 0 rects, 0 pixels
>  DecodeManager:          0 B (1:nan ratio)
> ```
> 
> Here is the client-side log (logging increased) on a linux machine
> 
> ```
> [<REDACTED>@<REDACTED> ~]$ vncmic 73
> 
> TigerVNC Viewer v1.12.90
> Built on: 2022-12-15 15:53
> Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
> See https://www.tigervnc.org for information on TigerVNC.
> 
> Mon Feb 27 10:44:14 2023
>  Config:      set PasswordFile(String) to
>               /<REDACTED>/.vnc/<REDACTED>
>  DecodeManager: Detected 6 CPU core(s)
>  DecodeManager: Creating 4 decoder thread(s)
>  TcpSocket:   Connecting to <REDACTED> [<REDACTED>] port <REDACTED>
>  TcpSocket:   Failed to connect to address <REDACTED> port <REDACTED>: 111
>  CConn:       unable to connect to socket: Connection refused (111)
>  DecodeManager:   Total: 0 rects, 0 pixels
>  DecodeManager:          0 B (1:-nan ratio)
> ```
> 
> I'm trying to get the server logs. Will post them if available.

Sorry, I've figured out that there was a problem with the machine the server is running on.
It was rebooted.

Please ignore the previous message.

**Comment by CendioOssman** [comment]
Thanks for the update.

Are all issues resolved now so that we can close the issue?
