### ISSUE TITLE
The wiki has been edited to have a link to ransomware

### ISSUE THREAD

**Issue by Zinvoke** [TigerVNC/tigervnc#1547]
Happened to polybar last night aswell and others

The download links in the wiki redirect to:
https://github.com/AhmedAboSamra/VideoCaptureUtility/releases/tag/42

The wiki page:
https://github.com/TigerVNC/tigervnc/wiki/Setup-TigerVNC-server-(Windows)

**Comment by CendioOssman** [comment]
Yeah, it's an ongoing struggle. We've reported the issue to GitHub, but they don't seem to really care that their site is turning in to a malware haven. :/
