### ISSUE TITLE
"Resize remote session to the local window" feature doesn't work

### ISSUE THREAD

**Issue by cdwilson** [TigerVNC/tigervnc#155]
I'm trying to get the "Resize remote session to the local window" feature to work, but resizing the local window doesn't seem to change the resolution of the remote display.   I'm on RHEL 6.2 running Xvnc TigerVNC 1.1.0 for server and Windows vncviewer-1.4.3.exe client.  Does the 1.1.0 server support this feature?  (the server is a workstation at my work and I don't have any ability to update the server software to something newer)

**Comment by CendioOssman** [comment]
Yes, we've had that support since version 1.0. Check the logs of both the client and server for errors. You might need to up the logging a bit with `-Log *:stderr:100`.

**Comment by cdwilson** [comment]
I started a new vnc server (` vncserver -log "*:stderr:100"`) and tried to resize the client window by dragging the corners and clicking the maximize button.  I get the `XserverDesktop: setScreenLayout: Could not find a matching mode` message in the logs below:
```
Fri Mar 20 11:07:25 2015
 SConnection: processing security message
 SVncAuth:    reading password file
 VNCServerST: starting desktop
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 SConnection: reading client initialisation
 VNCSConnST:  non-shared connection - closing clients
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888

** (gnome-settings-daemon:22304): WARNING **: Connection failed, reconnecting...

Fri Mar 20 11:07:28 2015
 XserverDesktop: setScreenLayout: Could not find a matching mode

** (gnome-volume-control-applet:22329): WARNING **: Connection failed, reconnecting...

Fri Mar 20 11:07:30 2015
 XserverDesktop: setScreenLayout: Could not find a matching mode

Fri Mar 20 11:07:33 2015
 XserverDesktop: setScreenLayout: Could not find a matching mode

** (gnome-settings-daemon:22304): WARNING **: Connection failed, reconnecting...

** (gnome-volume-control-applet:22329): WARNING **: Connection failed, reconnecting...

Fri Mar 20 11:07:34 2015
 XserverDesktop: setScreenLayout: Could not find a matching mode

Fri Mar 20 11:07:36 2015
 XserverDesktop: client gone, sock 17
 Connections: closed: 10.24.217.205::49944 (read: Connection reset by peer
              (104))
 SMsgWriter:  framebuffer updates 8
 SMsgWriter:    Tight rects 18, bytes 48179
 SMsgWriter:    raw bytes equivalent 3186184, compression ratio 66.132215
 VNCServerST: no authenticated clients - stopping desktop

```
However, if I perform the following steps, I can get the window to resize:

1. Start a new vncserver session
2. Click the "Maximize" button on the local client to make the window fill the entire screen
3. No resize happens (just a black border is added to fill the space between the window edges and the remote desktop resolution)
4. Click the "Maximize" button on the local client again to restore the window to the original size
5. (you can keep clicking the "Maximize" button forever, no resize will happen)
6. Open the Display Preferences GUI
7. Check that the custom resolution (2560x1378 when maximized) has been added to the list of resolutions (note: I have no idea how it got into this list, I'm guessing that by clicking the "Maximize" button earlier, and opening the Display Preferences, it somehow magically got appended to the list???)
8. Click the "Maximize" button on the local client again to make the window fill the entire screen
9. The resize finally works, but only for the resolution 2560x1378.  Dragging the window to any other resolution still does not work...

Here's the log snippet from when the resize worked at 2560x1378:
```
Fri Mar 20 11:14:54 2015
 VNCSConnST:  pixel buffer changed - re-initialising image getter
 PixelBuffer: reallocating managed buffer (2560x1378)
```
I'm not exactly sure what's going on, but it seems like the window won't resize until the custom resolution somehow makes it's way into the list of resolutions in the Display Preferences window.  Once a resolution has made it to this list, resizing to that resolution seems to work, but any other resolution will not result in a resize happening.  

Any ideas what's going on here?

**Comment by CendioOssman** [comment]
Not really. But 1.1.0 is old. Perhaps it is not interacting well with the Xorg base used in RHEL 6. Ideally I'd like you to try something newer as it is likely the bug could have already been fixed.

You said you couldn't install things, but can you run things out of your home directory? If so, then download the Linux tar balls of 1.4.3 and just execute the updated Xvnc directly:

```
$ ./usr/bin/Xvnc -SecurityTypes None -Log *:stderr:100 -retro :2
```

Then connect to <your machine>:2 and see if resize works.

**Comment by cdwilson** [comment]
1.4.3 seems to work flawlessly, thanks for pointing me in the right direction.  You're probably right, something about 1.1.0 doesn't work well with whatever they are running on our work machines...

For those that run across this in the future, I simply extracted the Linux tarball into my home directory, added `~/usr/bin` to the front of my `PATH` (to override the built in `vncserver` and friends), and ran `vncserver` to start the server.  Connecting with the 1.4.3 local viewer now supports resize to any custom resolution.
