### ISSUE TITLE
How to reset settings of tigerVNC viewer on MacOS 12.6.1?

### ISSUE THREAD

**Issue by LowryJK** [TigerVNC/tigervnc#1550]
I accidentally enabled some weird zoom mode by accident. I now want to reset the tigervnc settings so I can get back to coding. How to do that with MacOS 12.6.1?

**Comment by CendioOssman** [comment]
Which client are you using? The native viewer doesn't have any zoom mode, but I think the Java one does. @bphinz?

**Comment by bphinz** [comment]
The Java viewer is capable of scaling but those features are not bound to
hotkeys or anything so it doesn't sound to me like that's the problem.  You
should be able to check from the F8 menu under the "Screen" tab.  It's most
likely some hotkey combination that was passed to macOS itself (that
happens to me all the time when I'm editing in vim...)

**Comment by LowryJK** [comment]
Hi, here's a picture of what my TigerVNC looks like this as it opens. I don't think i have a Java viewer I think it's the native.

<img width="1026" alt="Screenshot 2022-11-16 at 13 58 25" src="https://user-images.githubusercontent.com/105065684/202175244-34bfe914-9f89-44b5-87be-bbf8c49b1360.png">

**Comment by LowryJK** [comment]
The screen moves with the cursor and as I said it's "zoomed" but I'm not sure if that's the right term in this case.

**Comment by CendioOssman** [comment]
Sounds like perhaps it's a server thing, then. What server are you using? And have you tried restarting it?

**Comment by CendioOssman** [comment]
No response. Closing.
