### ISSUE TITLE
Multiple virtual sessions for same user

### ISSUE THREAD

**Issue by naizarak** [TigerVNC/tigervnc#1552]
Hello, with the following vncserver.users config

```
:1=user
:2=user
```

I was able to start multiple sessions for the same user in v1.11.  This was useful for emulating the behavior of multiple screens and, for example, running automated apps in display 1 without interfering with the user's active tasks in display 2.

However after updating to v1.12 this no longer works.  Starting the 2nd display produces the following error output:
```
Segmentation fault
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
Killing Xtigervnc process ID 1069... success!
```
Interestingly, it works fine if the session is started manually:
` /usr/sbin/tigervncsession user :2`

**Client (please complete the following information):**
 - OS: Win 10 LTSC
 - VNC client: TigerVNC
 - VNC client version: 1.11.0

**Server (please complete the following information):**
 - OS: Debian 12
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: Debian repos
 - Server was started using: tigervncserver@:X.service

**Comment by CendioOssman** [comment]
Starting multiple sessions is unfortunately not something that distributions support anymore, so this setup is likely not feasible. :/

But can we have a bit more context to that error message? Exactly which process is it that crashes with a segmentation fault?

**Comment by naizarak** [comment]
That's unfortunate, I wasn't aware it was a distro-level limitation.   Guess it doesn't qualify as a bug then, but I have attached the full log for reference:

```
Xvnc TigerVNC 1.12.0 - built 2022-07-09 14:10
Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12101004, X.Org


Mon Nov 21 15:27:01 2022
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5902
 vncext:      created VNC server for screen 0
[mi] mieq: warning: overriding existing handler (nil) with 0x55d5ac739060 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x55d5ac739060 for event 3
3NI3X0 New Xtigervnc server 'debian:2 (user)' on port 5902 for display :2.
3NI3X0 Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /tmp/tigervnc.Rk01JF/passwd debian:2 to connect to the VNC server.
Segmentation fault

Mon Nov 21 15:27:02 2022
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
Killing Xtigervnc process ID 1271... success!
```
