### ISSUE TITLE
IdleTimeout option not work

### ISSUE THREAD

**Issue by chiefliu** [TigerVNC/tigervnc#1558]
**Describe the bug**
When Started vncserver with config  IdleTimeout=10, the vncserver process is never exited even though no connection connected for  given timeout time

**To Reproduce**
step 1:
config file :
session=gnome
securitytypes=none
IdleTimeout=10
step 2:
 vncserver :1 &

step3 ：
wait for about  15seconds

![process](https://user-images.githubusercontent.com/24840282/206634649-147ce629-9f9b-468a-ad84-f9c418639895.png)

**Expected behavior**
The VNC process EXITED

**Screenshots**

**Client (please complete the following information):**

![client](https://user-images.githubusercontent.com/24840282/206634181-177bd347-b7b4-4b35-bfdf-ee348ffba995.png)

**Server (please complete the following information):**
 - OS: Ubuntu 16
 - VNC server: TigerVNC
 - VNC server version: tigervnc-1.12.0.x86_64
 - Server downloaded from: github release 

**Additional context**

**Comment by CendioOssman** [comment]
It sounds like what you really want is `MaxIdleTime`, not `IdleTimeout`. The latter only disconnects idle clients, whilst the former kills the entire server.

Please give that a try and hopefully it will work better.
