### ISSUE TITLE
Attempting to open 'Options...' causes TigerVNC viewer to crash on macOS Ventura 13.0.1

### ISSUE THREAD

**Issue by TidbitSoftware** [TigerVNC/tigervnc#1559]
**Describe the bug**
Attempting to open 'Options...' either from the initial window or in the context menu after establishing a connection causes TigerVNC viewer to crash.

**To Reproduce**
See bug description.

**Expected behavior**
The expectation is that an options dialog would start.

**Client (please complete the following information):**
 - OS: macOS Ventura 13.0.1
 - VNC client: TigerVNC Viewer
 - VNC client version: 1.12.0
 - Client downloaded from: [TigerVNC](https://sourceforge.net/projects/tigervnc/)

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - VNC server: TightVNC
 - VNC server version: Xvnc version TightVNC-1.3.10
 - Server downloaded from: apt package manager
 - Server was started using: `vncserver :1 -geometry 1920x1080 -depth 24`

**Comment by CendioOssman** [comment]
This is likely #1423 or #1442. Please try a nightly build and it should hopefully not crash for you.
