### ISSUE TITLE
CapsLock keyboard sync

### ISSUE THREAD

**Issue by a-raccoon** [TigerVNC/tigervnc#156]
TigerVNC viewer handles CapsLock in a weird way.  If the remote computer has Caps On, and the local computer has Caps Off, the remote computer will always have an inverted CapsLock state, even if you minimize the viewer and toggle your local Caps to match.  The only solution seems to be closing the viewer, toggle your local caps, and reconnect.
##

**Comment by CendioOssman** [comment]
We don't have CapsLock sync, no. But it should keep track of CapsLock in both ends and do the right thing.

Are you running TigerVNC 1.4.3 on both ends? What platforms?

**Comment by a-raccoon** [comment]
Yes, I'm running 1.4.3 and both systems are Windows 7 64-bit.

CapsLock does sync, but not in a useful way.  If the remote PC has caps on, and the local PC has caps off, they will always inversely flip-flop and never match unless you close the viewer, hit CapsLock, and open the viewer again.

The behavior that should be expected is that the CapsLock state is only toggled remotely when TigerViewer is the active window.  When the user minimizes TigerViewer, and toggles CapsLock locally, it should not send the state change to the remote PC.  It currently does.

**Comment by CendioOssman** [comment]
Ah. I'm not entirely familiar with the WinVNC keyboard handling (we lack a maintainer for that). Sounds like it isn't filtering lock keys properly, like the Unix server does.

**Comment by CendioOssman** [comment]
Hmm.. I had a look at WinVNC's code, and I can't see any handling for the lock keys. Which means that they should be ignored. It does however seem to fail to consider the state of CapsLock on the server though. But in that case you should not have to restart the viewer. Simply pressing CapsLock once should get them in sync and everything should be fine.

**Comment by CendioOssman** [comment]
Should be fixed as of #513 .
