### ISSUE TITLE
x0vncserver exited with status 1

### ISSUE THREAD

**Issue by markd89** [TigerVNC/tigervnc#1560]
**Describe the bug**
Starting x0vncserver exits with status 1

**To Reproduce**
Running under Debian Bookworm (testing).
TigerVNC Server version 1.12.0, built 2022-07-09 14:10

1. Try to run one of these:
$x0vncserver -display:0 -SecurityTypes None
$AUTHORITY=/var/run/lightdm/root/:0 x0vncserver -display :0 -SecurityTypes None

2. Result:
0vncserver: /usr/bin/X0tigervnc exited with status 1, please look into '/home/mark/.vnc/[machine-name-redacted]:5900.log' to determine the reason! -2
Can't locate object method "cleanup" via package "File::Temp::Dir" at /usr/share/perl5/TigerVNC/Wrapper.pm line 1347, <GEN3> line 100.

Looking at the referenced .log file, there are no details. It just contains the usage. I realize that the Wrapper.pm code is not yours, but I think the failing to start x0vncserver is probably an issue that belongs here.

Thanks!

**Comment by CendioOssman** [comment]
I'm afraid the most likely reason is that Debian's x0vncserver script is calling our binary incorrectly. So I'm afraid I'll have to point you to Debian's bug tracker for this one. We can revisit it here if they think the command line is correct.

**Comment by markd89** [comment]
Thanks @CendioOssman, I tried and am able to run X0tigervnc without an error. I will tell Debian to look here.

**Comment by gsshiva** [comment]
> $x0vncserver -display:0 -SecurityTypes None

does not have a space between the `-display` option and the display number `:0`

I had a similar error when running on `Ubuntu 22.10` but when I added the space, it works fine. Here is my command line that worked on `Ubuntu 22.10`  (as a systemd service)
> CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/app-x0vncserver.slice/x0vncserver@0.service
             ├─17851 /usr/bin/perl /usr/bin/x0vncserver -passwordfile /xxx/passwd -display :0 -localhost no
             └─17852 /usr/bin/X0tigervnc -display :0 -localhost=0 -desktop "YYYY" -rfbport 5900 -PasswordFile /tmp/tigervnc.XQ1quy/passwd -SecurityTypes VncAuth,TLSVnc
