### ISSUE TITLE
Blank screen on macOS Ventura13.1

### ISSUE THREAD

**Issue by RobyB** [TigerVNC/tigervnc#1561]
**Describe the bug**
When opened in full screen on an external monitor, if i switch to an macOS app on the other screen when i switch back to tigervnc the screen is black.
The only way to get back screen contents is to select F8 + options and press enter. Even f8 + refresh screen does not work.

**To Reproduce**
1. Make TigerVnc full screen on an external monitor
2. Switch to any macOS app in the other monitor
4. Switch back to TigerVnc
6. Screen is blank

**Expected behavior**
Switching back and forth between TigerVnc (in full screen mode) and any macOS application should not blank the screen.

**Client (please complete the following information):**
 - OS: [macOS Ventura 13.1]
 - VNC client: [TigerVNC]
 - VNC client version: [1.12.80]
 - VNC client mdsum: f4be263abdb1ff1490c7b214aba0d3ed
 - Client downloaded from: [http://tigervnc.bphinz.com/nightly/]

**Server (please complete the following information):**
 - OS: [Centos 7]
 - VNC server: [TigerVNC]
 - VNC server version: [1.8.0-22.el7]
 - Server downloaded from: [epel repo]

**Additional context**
Same combination of Server/Client was working correctly with macOS monterey 12.6.x.
Unfortunately i have no way to upgrade the server.

**Comment by CendioOssman** [comment]
Thanks for your bug report. I can see the same thing here. It seems Apple has changed something. :/

**Comment by CendioOssman** [comment]
Note that a possible workaround is to disable "Send system keys". Unfortunately it means that some key presses won't be sent to the remote side.

**Comment by RobyB** [comment]
I confirm that new nightly solves the issue.
Thank you so much

**Comment by CendioOssman** [comment]
Great. Thanks for testing!

**Comment by pritampanda15** [comment]
I am facing similar issue with MacOS Ventura OS 13.2.1. The screen goes blank (black). I am using the latest release 4.14.0.

**Comment by samhed** [comment]
@pritampanda15 that is the ThinLinc client, not TigerVNC. Please reply to this thread in the ThinLinc Community:

https://community.thinlinc.com/t/thinlinc-client-in-full-screen-results-in-black-screen-on-macos-13/519
