### ISSUE TITLE
Kex and Vncserver not working

### ISSUE THREAD

**Issue by HangWithCmm** [TigerVNC/tigervnc#1564]
I try to run "$ kex --win -s" and i get the error:
Error connecting to the KeX server.
Please try "kex start" to start the service.
If the server fails to start, please try "kex kill" or restart your WSL2 session and try again.

I tried "$ kex start", "$ kex kill" and restarting my WSL2 but it doesn't work so I tried starting vncserver again with "$ vncserver" and i get the errors:

```
(EE) Failed to open authorization file "/home/kali/.Xauthority": Permission denied
/usr/bin/iceauth:  creating new authority file /mnt/wslg/runtime-dir/ICEauthority
(xfsettingsd:534): libupower-glib-WARNING **: 20:49:14.217: Couldn't connect to proxy: Could not connect: No such file >
(wrapper-2.0:550): Gtk-WARNING **: 20:49:14.764: gtk_widget_size_allocate(): attempt to allocate widget with width -3 a>
(wrapper-2.0:556): GLib-GIO-CRITICAL **: 20:49:14.771: g_file_new_for_path: assertion 'path != NULL' failed
```
PSA: these are from the log file^^^^

So I see "Permission denied" so i run it as sudo so "$ sudo vncserver" and I get the error:

```
_XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
_XSERVTransSocketCreateListener: failed to bind listener
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
```

And now I have no idea what to do please help

**Comment by CendioOssman** [comment]
I'm afraid this falls outside what we can help you with. We no longer include `vncserver`, so it must be an old TigerVNC, or some other custom packaging (e.g. Debian or Ubuntu).

So I'm afraid I'll have to point you to wherever you got TigerVNC from. Or try one of our packages and see if that works better for you.

**Comment by CendioOssman** [comment]
I'm afraid I'm not familiar with Kali Linux, so I'm not sure. You could try our Ubuntu packages, since Kali seems to be using .deb. Otherwise please use the general `tigervnc-1.12.0.x86_64.tar.gz`. Files are available on the release page:

https://github.com/TigerVNC/tigervnc/releases

**Comment by Paciupa** [comment]
Yes, this is not a TigerVNC problem at all. [Here](https://github.com/microsoft/WSL/discussions/6675) and [here](https://github.com/microsoft/WSL/issues/9303) WSL issues and solutions also.
