### ISSUE TITLE
Documentation of https://tigervnc.org/doc/x0vncserver.html improvement

### ISSUE THREAD

**Issue by hashimx** [TigerVNC/tigervnc#1567]
**Is your feature request related to a problem? Please describe.**
I'm looking forward to use x0vncserver in a "ubuntu 22.04 container image" command line as described in https://tigervnc.org/doc/x0vncserver.html, but I don't seem to understand how to install x0vncserver , the Command always says not found 

root@3596712b11ad:~# x0vncserver
bash: x0vncserver: command not found

I'm trying to use it inside container but I'm finding that tigervnc is not at all user friendly.

**Describe the solution you'd like**
Clear explanation of installation and execution of tigervnc commands using command line. 

**Describe alternatives you've considered**

**Additional context**

**Comment by CendioOssman** [comment]
How to install things on different distributions is a bit outside of project focus, so I'm going to have to refer you to Ubuntu's documentation. It should be `sudo apt install tigervnc-scraping-server`.

Also note that they tend to rename the binaries to something including "tigervnc". I would guess the command is instead called "x0tigervncserver" there.
