### ISSUE TITLE
Shells opened in UI start from root directory instead of home directory

### ISSUE THREAD

**Issue by anandbibek** [TigerVNC/tigervnc#1569]
**Describe the bug**
When Tiger VNC Service is started via systemd, all bash shells opened from UI start with `/` root directory instead of user home directory.

**To Reproduce**
1. Configure VNC Service as described by /usr/share/doc/tigervnc/HOWTO.md
2. systemctl start vncserver@:1
3. Connect via VNC Viewer
4. Open bash shell - initial directory is `/`

**Expected behavior**
Newly opened shells should start with user home directory `~`

**Client (please complete the following information):**
 - OS: [Windows 11]
 - VNC client: [TigerVNC]
 - VNC client version: [e.g. 1.12.0]
 - Client downloaded from: [SourceForge]

**Server (please complete the following information):**
 - OS: [Oracle Linux 8]
 - VNC server: [TigerVNC]
 - VNC server version: [e.g. 1.11.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `systemctl`]

**Additional context**
Bash or other shells seem to pick the working directory of parent processes by default. If I start server using `vncserver` command, it uses my home directory and runs as non-root user, thereby allowing all shells in UI to start with `~` directory.

However, when systemd starts the server, it appears to do so from root, which uses `/` and passes it on to child processes.

**Comment by CendioOssman** [comment]
This was fixed in TigerVNC 1.12.0. Please upgrade your TigerVNC server and it should work better.

**Comment by anandbibek** [comment]
I just upgraded and disabled + re-enabled the service. Still I notice the same behavior of shells starting in `/`. I'm just wondering if I'm missing any recommended setup process.

**Comment by CendioOssman** [comment]
Which version of TigerVNC do you have installed now after the upgrade?

**Comment by anandbibek** [comment]
My bad. I mistakenly updated only the viewer first time. After updating the server to 1.12.0, the shells are staring correctly in `~` .
Many thanks and have a happy new year :)
