### ISSUE TITLE
How can send a popup message after crossing the 50 session of a user

### ISSUE THREAD

**Issue by csutar** [TigerVNC/tigervnc#157]
Hi,

I have configuure  per_source = 50 in Xvnc configuration file. I want to popup a message like "user exceed the limit" , when the user can open 51 session. please find the configuration file.
bash-4.1$ cat /etc/xinetd.d/Xvnc
service Xvnc
{
  accept_reject_mesg = Exceed the Limit
  disable = no
  flags = IPv4
  socket_type = stream
  protocol = tcp
  per_source = 50
  wait = no
  user = nobody
  server = /usr/bin/Xvnc
  server_args = -inetd -once -query localhost -SecurityTypes=VeNCrypt,TLSnone -geometry 1280x1024 -depth 24 -extension XFIXES
}

**Comment by CendioOssman** [comment]
I'm afraid that's not possible. The connection limit is handled by xinetd, not us. So we can't really tell what it's up to.

**Comment by csutar** [comment]
Hi Cendio,

Thanks for your reply. i have a another query, can i add two user and each having 50 sessions in Xvnc configuration file.

Thanks in advance
