### ISSUE TITLE
[Feature request] change interface language regardless of OS one

### ISSUE THREAD

**Issue by syryyndypyty** [TigerVNC/tigervnc#1570]
On macOs the Viewer interface always matches the operating system display language.
Would like to have the option to use system language (default) or choose among those available.

For example be able to have macOS in french and tigervnc UI in German or Arabic. A lot of applications support this even some mobile operating systems allow to configure individual languages/localization for each app.

**Comment by CendioOssman** [comment]
The described use case for this was to work around #1571, so let's try to focus on resolving that issue instead.

**Comment by syryyndypyty** [comment]
This feature is not really needed within tigervnc, since macOS allows to set specific locale when launching from Terminal:
```
LANG=ru_RU open -a /Applications/TigerVNC\ Viewer\ 1.12.90.app
LANG=ru_RU open -a '/Applications/TigerVNC Viewer 1.12.90.app'
```
