### ISSUE TITLE
[Feature request]: VncPlain security type

### ISSUE THREAD

**Issue by twaik** [TigerVNC/tigervnc#1573]
Hi. Is it possible to make X0tigervnc check user password with PAM, but report VncAuth security? It will allow users to use custom PAM modules for secure logins (or to send login reports somewhere). Using Plain and TLSPlain did not work for me.

**Comment by CendioOssman** [comment]
Not quite sure how that would work. PAM needs a username, which we don't get for VncAuth.

PAM also often requires root, which is probably even more problematic with x0vncserver than Xvnc or libvnc.so.

In what way doesn't Plain work for you? If that doesn't work, then it is unlikely some other variation with PAM will either.

**Comment by twaik** [comment]
You are right. PAM requires root permissions. I think we can get username using `getlogin_r` and then run something like `su - $(user) -c "echo success` and expect to receive something like `Password: success` or `Password: su: Authentication failure`. Or we can use some suid helper which will check credentials.

> In what way doesn't Plain work for you? If that doesn't work, then it is unlikely some other variation with PAM will either.

With `sudo X0tigervnc -display=:0 -SecurityTypes=TLSPlain,X509Plain,Plain` I get `VNCSConnST:  closing 10.0.0.8::34204: Clean disconnection` and client responds `The VNC server is not configured to use a compatible security type. Please make sure the VNC server is configured to accept VNC authentication`. I think a client supports only `-SecurityTypes=None,VncAuth` because it does not support any other of security types. I think new mode `VncPlain` should report `VncAuth` authentication type. Of cource uf you want to implement it. Thank you.

**Comment by CendioOssman** [comment]
We probably don't want to add all this complexity just to support simple clients. An advanced client will generally be required for advanced features.

Which client is it you are using? And why not use our client?

**Comment by twaik** [comment]
I use `Jump Desktop` for Android. It is a bit outdated but still enough comfortable.

**Comment by CendioOssman** [comment]
I'm afraid I'm going to have to suggest looking at a more capable viewer. bVNC for Android claims support for VeNCrypt, so that should hopefully work. We've also added support for RealVNC's authentication in the 1.13.0 beta, which means that RealVNC's Android client should hopefully work.

Hopefully, one of those can give you the functionality you need.
