### ISSUE TITLE
X0tigervnc - fresh reboot -  Invalid MIT-MAGIC-COOKIE-1 key

### ISSUE THREAD

**Issue by markd89** [TigerVNC/tigervnc#1576]
Debian Bookworm, Mate desktop

I had previously been using x11vnc and am trying to migrate to using X0tigervnc.

On a freshly rebooted host, I connect via SSH and try to start the server:

```
/usr/bin/X0tigervnc -display :0 -localhost 

Invalid MIT-MAGIC-COOKIE-1 key

/usr/bin/X0tigervnc: unable to open display ":0"
```

If I walk over to the host machine and login to the GUI, then the above command via SSH works. Of course, I want to be able to login to the host when it is not sitting in the next room and do so when it has been rebooted.

How can I start the X0tigervnc server via SSH without first once logging in to the GUI?

Thank you!

**Comment by CendioOssman** [comment]
Generally, that is very difficult to get working. But if you had a working setup with x11vnc, then you should be able to switch that to TigerVNC easily.

How are things set up when you are using x11vnc?

**Comment by CendioOssman** [comment]
No response. Closing.
