### ISSUE TITLE
Kill stale process ID does not work

### ISSUE THREAD

**Issue by mdatres** [TigerVNC/tigervnc#1581]
Dear all, 

the command `vncserver --list` outputs the following:

```

TigerVNC server sessions:

X DISPLAY #	RFB PORT #	RFB UNIX PATH	PROCESS ID #	SERVER
1         	5901      	             	106657      	Xtigervnc
2         	5902      	             	13113 (stale)	Xtigervnc
5         	5905      	             	198811 (stale)	Xtigervnc
```
I want to remove the stale processes 2 and 5, but the commands `vncserver -kill :2` and `vncserver -kill :5` do not find them. Do you know what they are and if there is a way to "kill" them. 

Thanks in advance, 

Max

**Comment by CendioOssman** [comment]
I'm afraid you'll have to report that issue to your distribution, as that is a custom `vncserver` script from Debian/Ubuntu. I.e. it's not something from us, so it's not something we have the expertise to help you with.
