### ISSUE TITLE
I can only create about 50 vnc session

### ISSUE THREAD

**Issue by nguoido** [TigerVNC/tigervnc#1584]
**Describe the bug**
I can only create about 50 vnc sessions. 

**To Reproduce**
1. for i=1 --> i = 100;
2. create vnc with port i

**Expected behavior**
I get 100 vnc sessions

**Server (please complete the following information):**
 - OS: Centos stream 9 and Centos 7.9
 - VNC server: TigerVNC

**Additional context**
The log system when create vnc fail

Jan 12 20:56:47 local sshd[92969]: pam_systemd(sshd:session): Failed to create session: Connection reset by peer
Jan 12 20:56:47 local sshd[92969]: pam_unix(sshd:session): session opened for user avion48 by (uid=0)
Jan 12 20:56:51 local gnome-session-binary[93018]: ERROR: Failed to connect to system bus: GDBus.Error:org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of active connections has been reached aborting...
Jan 12 20:56:51 local abrt-hook-ccpp[93171]: Process 93018 (gnome-session-binary) of user 1161 killed by SIGTRAP - dumping core

**Comment by CendioOssman** [comment]
I'm afraid that's a limitation of your distribution and is not an issue in TigerVNC. You should be able to raise the limit by changing the setting `max_connections_per_user`:

https://dbus.freedesktop.org/doc/dbus-daemon.1.html
