### ISSUE TITLE
Fullscreen with failure to resize causes clipping

### ISSUE THREAD

**Issue by larsch** [TigerVNC/tigervnc#1585]
**Describe the bug**

When connect to a server that does not allow resizing, the client resizes down to a smaller size than the remote size.

**To Reproduce**

1. Connect to QEMU display in console mode. (E.g. 1280x800)
2. Go full-screen (resize fails, but then resizes to 1280x768, clipping the bottom lines of the console)
3. Restore window (is resized back to 1280x800, everything visible)
4. Resize window (pull corner) - again, resized to 1280x768 with missing lines, no way to restore 1280x800.

**Expected behavior**

Client should retain the original 1280x800 resolution.

**Screenshots**

Before:

![image](https://user-images.githubusercontent.com/15712/213223534-5d208244-cd91-4143-aa6b-7108aa583b65.png)

After (bottom lines missing, including cursor).

![image](https://user-images.githubusercontent.com/15712/213223703-fed4fac0-c480-40a8-95b0-9328f0add2db.png)

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC
 - VNC client version: 1.12.90
 - Client downloaded from: SF

**Server (please complete the following information):**
 - OS: Linux
 - VNC server: QEMU
 - VNC server version: 7.2.0
 - Server downloaded from: Arch Linux
 - Server was started using: qemu -vnc 

**Additional context**

When maximizing window:

```
Wed Jan 18 16:52:54 2023
 DesktopWindow: Requesting framebuffer resize from 1280x800 to 2560x1387
 DesktopWindow: 1 screen(s)
 DesktopWindow:              0 (0x00000000): 2560x1387+0+0 (flags 0x00000000)
 DesktopWindow: 
 CConn:       SetDesktopSize failed: 4
 Viewport:    Resizing framebuffer from 1280x800 to 1280x768

Wed Jan 18 16:52:56 2023
 DesktopWindow: Requesting framebuffer resize from 1280x768 to 1280x800
 DesktopWindow: 1 screen(s)
 DesktopWindow:              0 (0x00000000): 1280x800+0+0 (flags 0x00000000)
 DesktopWindow: 
 CConn:       SetDesktopSize failed: 4
 Viewport:    Resizing framebuffer from 1280x768 to 1280x800
```

When manually resizing window:

```
Wed Jan 18 16:59:47 2023
 DesktopWindow: Requesting framebuffer resize from 1280x800 to 1516x906
 DesktopWindow: 1 screen(s)
 DesktopWindow:              0 (0x00000000): 1516x906+0+0 (flags 0x00000000)
 DesktopWindow: 
 CConn:       SetDesktopSize failed: 4
 Viewport:    Resizing framebuffer from 1280x800 to 1280x768
```

**Comment by larsch** [comment]
It's of course entirely possible that this is a server side issue.

**Comment by CendioOssman** [comment]
I'm afraid that I think that it is indeed a server-side issue. I'm looking at our client code, and it should never resize the screen except when requested by the server.

That failure code is not a true failure, but rather that QEMU doesn't know whether the request will succeed or not. It looks like it does succeed, just that the resize handling seems to be picking a poor choice.

Unfortunately, that means I'll have to direct you to QEMU and report the issue to them.
