### ISSUE TITLE
can i add two user and each having 50 sessions in Xvnc configuration file

### ISSUE THREAD

**Issue by csutar** [TigerVNC/tigervnc#159]
Hi Cendio,

Thanks for your reply. i have a another query, can i add two user and each having 50 sessions in Xvnc configuration file.

Thanks in advance

**Comment by CendioOssman** [comment]
No, I'm afraid that Xvnc has no concept of sessions so it cannot keep track of any count. It only knows of connections to its specific session. So this unfortunately falls outside of the scope of things we can handle.
