### ISSUE TITLE
Flathub submission

### ISSUE THREAD

**Issue by acperkins** [TigerVNC/tigervnc#1590]
I am working on a Flatpak build of TigerVNC and would like to submit it to Flathub. The build is working well and I believe it would be useful to others. I have two requests related to this:

1. Could I get your blessing to submit this to Flathub?
2. Am I permitted to use `org.tigervnc` at the start of the app ID?

The current state of the pull request is at the following URL: https://github.com/flathub/flathub/pull/3868.

Many thanks!
Anthony

**Comment by CendioOssman** [comment]
Sure, go right ahead. It's always nice to see more ways for people to use TigerVNC. :)
