### ISSUE TITLE
Instructions for one off build/compile for linux  distros

### ISSUE THREAD

**Issue by dkebler** [TigerVNC/tigervnc#1591]
There is some detailed information for compiling for windows in the wiki but nothing for linux (in particular debian), just some info on making releases. 

If there is such information  then where?  otherwise can it be added to the wiki.

In particular I need a build for debian/bullseye.  None of the ubuntu beta releases work because of missing dependencies.  Not sure I could track down whatever their equivalents would be in debian but the bullseye stable branch has 1.11 which is now 3 years old.

**Comment by CendioOssman** [comment]
It's generally much easier to build for Linux, so there hasn't been a need for a more detailed wiki page. The instructions in the building document should be correct:

https://github.com/TigerVNC/tigervnc/blob/master/BUILDING.txt

It should be trivial to adapt one of the Ubuntu packages to build on Debian instead. The distributions are extremely similar. Have you tried just building it using one of the Ubuntu packaging recipes?

**Comment by dkebler** [comment]
well this is some info there nothing like a functional script (to load deps and configure and build) and nothing specific about ubuntu (nor debian)

```   
 (NOTE: This is merely an example that works with Red Hat Enterprise/CentOS
    6 and recent Fedora releases.  You should customize it for your particular
    system.  In particular, it will be necessary to customize the font, XKB,
    and DRI directories.)
```
Being as I am not a C  programmer I can usually bumble my way through compiling something but as such I need more details.   I was looking around github trying to find a dockerized container build for tigervnc as that usually can be tweeked to work and plus doesn't require "messing up" my dev with tools and libraries I'll not be using otherwise, but I didn't find any.  @CendioOssman Do you know of such a Dockerfile/repo?

**Comment by bphinz** [comment]
Take a look at the shell script that the github actions bot runs, that
should help:

https://github.com/TigerVNC/tigervnc/blob/master/.github/containers/jammy/build.sh

**Comment by CendioOssman** [comment]
Unfortunately, there is too much variation between the distributions of exactly what they call packages for us to maintain a list. You can usually find them fairly easily when searching for the names of the components, though.

As Brian mentioned, please have a look at the containers we use for our GitHub builds if you want to explore that option.
