### ISSUE TITLE
Xvnc not working

### ISSUE THREAD

**Issue by Moe-Sherif** [TigerVNC/tigervnc#1593]
I'm Using WSL2 i have been suffering for a while form this error kex on kali when using vncserver command and on ubuntu when using the Xvnc command and I'm sure there is no other xserver running but if there is a certain way to make sure please provide me with the method 
output when using the command:
 
Xvnc
_XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)

**Comment by CendioOssman** [comment]
There is something broken with `/tmp/.X11-unix` on your system, which is preventing Xvnc from starting correctly. I'm afraid that is something that should be handled by the OS, so it's not something that we can offer much assistance with.

I would advise reporting the issue to Kali or Ubuntu and see if they can help you see why that folder is broken.
