### ISSUE TITLE
X-Session Crash exiting x0vncserver session

### ISSUE THREAD

**Issue by greyhair-atx** [TigerVNC/tigervnc#1598]
**Describe the bug**
On a RHEL 8 system (using tigervnc v1.12.0-8, v1.12.0-9, or 1.12.90-1 [via sourceforge])
When using the following command:
 `gnome-terminal --title="Test VNC" -- /usr/bin/x0vncserver -Geometry 1440x900+0+0 -AlwaysShared -AcceptKeyEvents=0 -AcceptPointerEvents=0 -QueryConnect -PasswordFile ${HOME}/.vnc/passwd  `
 
 Vncviewer is able to connect.  Upon *either* the guest vncviewer closing *or* exiting the host gnome-terminal, the hosting system's x-session crashes.

**To Reproduce**
1.  Install RHEL 8 - release 8.7 (Ootpa)
2.  Open a terminal window and run the code above.
3.  Connect from an external system to the VNC session
4.  Close the external VNC session
5.  Host x-session crashes

**Expected behavior**
Clean exit, no x-session crash.

**Screenshots**
None

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC, RemoteRipple, RealVNC
 - VNC client version: 1.13.0, 1.0.4, 7.0.1
 - Client downloaded from: Tigernvc sourceforge, TightVNC site, RealVNC site.

**Server (please complete the following information):**
 - OS: RHEL 8 release 7
 - VNC server: TigerVNC
 - VNC server version: v1.12.0-8, v1.12.0-9, and 1.12.90-1
 - Server downloaded from: Redhat, Redhat, TigerVNC Sourceforge el8.
 - Server was started using: /usr/bin/x0vncserver -Geometry 1440x900+0+0 -AlwaysShared -AcceptKeyEvents=0 -AcceptPointerEvents=0 -QueryConnect -PasswordFile ${HOME}/.vnc/passwd  

**Additional context**
Rolling back to RHEL 8 v1.12.0-7 works as expected, but obviously does not have the security/bug updates/fixes.

Example crash output with these rpms installed: 
tigervnc-server-1.12.90-1.el8.x86_64.rpm
tigervnc-server-minimal-1.12.90-1.el8.x86_64.rpm

Commands run:
`systemd-cat echo "starting vnc test"; systemd-cat gnome-terminal --title="Test VNC" -- /usr/bin/x0vncserver -Geometry 1440x900+0+0 -AlwaysShared -AcceptKeyEvents=0 -AcceptPointerEvents=0 -QueryConnect -PasswordFile ${HOME}/.vnc/passwd; systemd-cat "session is open";`

Once the window was open the following commands were run:
`systemd-cat echo "VNC Password requested"`   
`systemd-cat echo "VNC session accepted" `   
`systemd-cat echo "In a moment session will close by the client exiting the vnc viewer program"`  

Journalctl output:

Feb 15 14:05:48 testGUI.examplei.com systemd[9242]: Started GNOME Terminal Server.
Feb 15 14:05:48 testGUI.examplei.com org.gnome.Shell.desktop[14111]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
Feb 15 14:05:48 testGUI.examplei.com org.gnome.Shell.desktop[14111]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
Feb 15 14:05:48 testGUI.examplei.com org.gnome.Shell.desktop[14111]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
Feb 15 14:05:58 testGUI.examplei.com gsd-color[13786]: unable to get EDID for xrandr-Virtual1: unable to get EDID for output
**Feb 15 14:06:02 testGUI.examplei.com unknown[14256]: starting vnc test**
Feb 15 14:06:03 testGUI.examplei.com gnome-terminal[14257]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
Feb 15 14:06:03 testGUI.examplei.com gnome-terminal[14257]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
Feb 15 14:06:03 testGUI.examplei.com gnome-terminal[14257]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
Feb 15 14:06:06 testGUI.examplei.com systemd[1]: systemd-hostnamed.service: Succeeded.
Feb 15 14:06:12 testGUI.examplei.com systemd[1]: systemd-localed.service: Succeeded.
Feb 15 14:06:28 testGUI.examplei.com geoclue[13695]: Service not used for 60 seconds. Shutting down..
Feb 15 14:06:28 testGUI.examplei.com systemd[1]: geoclue.service: Succeeded.
**Feb 15 14:06:44 testGUI.examplei.com unknown[14282]: VNC Password requested**
**Feb 15 14:06:57 testGUI.examplei.com echo[14289]: VNC session accepted**
**Feb 15 14:07:39 testGUI.examplei.com unknown[14296]: In a moment session will close by the client exiting the vnc viewer program**
Feb 15 14:07:43 testGUI.examplei.com kernel: show_signal: 2 callbacks suppressed
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: gsd-color[13786] trap int3 ip:7f1077dda895 sp:7fff94bcbac0 error:0 in libglib-2.0.so.0.5600.4[7f1077d87000+116000]
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: gsd-media-keys[13802] trap int3 ip:7fb1b0240895 sp:7fff63e269d0 error:0 in libglib-2.0.so.0.5600.4[7fb1b01ed000+116000]
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: gsd-wacom[13770] trap int3 ip:7f19a1efc895 sp:7ffd0ad6af20 error:0 in libglib-2.0.so.0.5600.4[7f19a1ea9000+116000]
Feb 15 14:07:43 testGUI.examplei.com gsd-color[13786]: The program 'gsd-color' received an X Window System error.
                                                               This probably reflects a bug in the program.
                                                               The error was 'BadValue (integer parameter out of range for operation)'.
                                                                 (Details: serial 166 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                 (Note to programmers: normally, X errors are reported asynchronously;
                                                                  that is, you will receive the error a while after causing it.
                                                                  To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                  variable to change this behavior. You can then get a meaningful
                                                                  backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com gsd-media-keys[13802]: The program 'gsd-media-keys' received an X Window System error.
                                                                    This probably reflects a bug in the program.
                                                                    The error was 'BadValue (integer parameter out of range for operation)'.
                                                                      (Details: serial 152 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                      (Note to programmers: normally, X errors are reported asynchronously;
                                                                       that is, you will receive the error a while after causing it.
                                                                       To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                       variable to change this behavior. You can then get a meaningful
                                                                       backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: gsd-xsettings[13769] trap int3 ip:7fabafbe9895 sp:7fff72382800 error:0 in libglib-2.0.so.0.5600.4[7fabafb96000+116000]
Feb 15 14:07:43 testGUI.examplei.com gsd-wacom[13770]: The program 'gsd-wacom' received an X Window System error.
                                                               This probably reflects a bug in the program.
                                                               The error was 'BadValue (integer parameter out of range for operation)'.
                                                                 (Details: serial 167 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                 (Note to programmers: normally, X errors are reported asynchronously;
                                                                  that is, you will receive the error a while after causing it.
                                                                  To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                  variable to change this behavior. You can then get a meaningful
                                                                  backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com gsd-xsettings[13769]: The program 'gsd-xsettings' received an X Window System error.
                                                                   This probably reflects a bug in the program.
                                                                   The error was 'BadValue (integer parameter out of range for operation)'.
                                                                     (Details: serial 180 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                     (Note to programmers: normally, X errors are reported asynchronously;
                                                                      that is, you will receive the error a while after causing it.
                                                                      To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                      variable to change this behavior. You can then get a meaningful
                                                                      backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com evolution-alarm[13911]: The program 'evolution-alarm-notify' received an X Window System error.
                                                                     This probably reflects a bug in the program.
                                                                     The error was 'BadValue (integer parameter out of range for operation)'.
                                                                       (Details: serial 152 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                       (Note to programmers: normally, X errors are reported asynchronously;
                                                                        that is, you will receive the error a while after causing it.
                                                                        To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                        variable to change this behavior. You can then get a meaningful
                                                                        backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: evolution-alarm[13911] trap int3 ip:7f63ccce3895 sp:7ffec9420b60 error:0 in libglib-2.0.so.0.5600.4[7f63ccc90000+116000]
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: classification-[13909] trap int3 ip:7fe50f9a4895 sp:7ffdaf96a500 error:0 in libglib-2.0.so.0.5600.4[7fe50f951000+116000]
Feb 15 14:07:43 testGUI.examplei.com classification-[13909]: The program 'classification-banner' received an X Window System error.
                                                                     This probably reflects a bug in the program.
                                                                     The error was 'BadValue (integer parameter out of range for operation)'.
                                                                       (Details: serial 414 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                       (Note to programmers: normally, X errors are reported asynchronously;
                                                                        that is, you will receive the error a while after causing it.
                                                                        To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                        variable to change this behavior. You can then get a meaningful
                                                                        backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: gsd-keyboard[13803] trap int3 ip:7f96763b5895 sp:7ffd10ddf500 error:0 in libglib-2.0.so.0.5600.4[7f9676362000+116000]
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: gsd-clipboard[13790] trap int3 ip:7efd3ccf0895 sp:7ffce4248ad0 error:0 in libglib-2.0.so.0.5600.4[7efd3cc9d000+116000]
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: gsd-power[13758] trap int3 ip:7fd985d41895 sp:7ffc62784c30 error:0 in libglib-2.0.so.0.5600.4[7fd985cee000+116000]
Feb 15 14:07:43 testGUI.examplei.com kernel: traps: vmtoolsd[13924] trap int3 ip:7f125e4a4895 sp:7ffe3cfa1b40 error:0 in libglib-2.0.so.0.5600.4[7f125e451000+116000]
Feb 15 14:07:43 testGUI.examplei.com gsd-keyboard[13803]: The program 'gsd-keyboard' received an X Window System error.
                                                                  This probably reflects a bug in the program.
                                                                  The error was 'BadValue (integer parameter out of range for operation)'.
                                                                    (Details: serial 156 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                    (Note to programmers: normally, X errors are reported asynchronously;
                                                                     that is, you will receive the error a while after causing it.
                                                                     To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                     variable to change this behavior. You can then get a meaningful
                                                                     backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com gsd-clipboard[13790]: The program 'gsd-clipboard' received an X Window System error.
                                                                   This probably reflects a bug in the program.
                                                                   The error was 'BadValue (integer parameter out of range for operation)'.
                                                                     (Details: serial 186 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                     (Note to programmers: normally, X errors are reported asynchronously;
                                                                      that is, you will receive the error a while after causing it.
                                                                      To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                      variable to change this behavior. You can then get a meaningful
                                                                      backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com gsd-power[13758]: The program 'gsd-power' received an X Window System error.
                                                               This probably reflects a bug in the program.
                                                               The error was 'BadValue (integer parameter out of range for operation)'.
                                                                 (Details: serial 172 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                 (Note to programmers: normally, X errors are reported asynchronously;
                                                                  that is, you will receive the error a while after causing it.
                                                                  To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                  variable to change this behavior. You can then get a meaningful
                                                                  backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com vmtoolsd[13924]: The program 'vmware-user' received an X Window System error.
                                                              This probably reflects a bug in the program.
                                                              The error was 'BadValue (integer parameter out of range for operation)'.
                                                                (Details: serial 1226 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                (Note to programmers: normally, X errors are reported asynchronously;
                                                                 that is, you will receive the error a while after causing it.
                                                                 To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                 variable to change this behavior. You can then get a meaningful
                                                                 backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com gnome-terminal-[14116]: The program 'gnome-terminal-server' received an X Window System error.
                                                                     This probably reflects a bug in the program.
                                                                     The error was 'BadValue (integer parameter out of range for operation)'.
                                                                       (Details: serial 11572 error_code 2 request_code 136 (XKEYBOARD) minor_code 8)
                                                                       (Note to programmers: normally, X errors are reported asynchronously;
                                                                        that is, you will receive the error a while after causing it.
                                                                        To debug your program, run it with the GDK_SYNCHRONIZE environment
                                                                        variable to change this behavior. You can then get a meaningful
                                                                        backtrace from your debugger if you break on the gdk_x_error() function.)
Feb 15 14:07:43 testGUI.examplei.com systemd[9242]: gnome-terminal-server.service: Main process exited, code=dumped, status=5/TRAP
Feb 15 14:07:43 testGUI.examplei.com systemd[9242]: gnome-terminal-server.service: Failed with result 'core-dump'.
Feb 15 14:07:43 testGUI.examplei.com gnome-session[13578]: gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.XSettings.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session[13578]: gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Wacom.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session[13578]: gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Color.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.XSettings.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Wacom.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Color.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE)
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) Backtrace:
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 0: /usr/libexec/Xorg (xorg_backtrace+0x7d) [0x55b4724dee9d]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 1: /usr/libexec/Xorg (0x55b472324000+0x1bec5d) [0x55b4724e2c5d]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 2: /lib64/libpthread.so.0 (0x7fb49d89c000+0x12cf0) [0x7fb49d8aecf0]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 3: /lib64/libc.so.6 (__libc_malloc+0x143) [0x7fb49d572ad3]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 4: /usr/libexec/Xorg (DeletePassiveGrabFromList+0xa3) [0x55b47239ae93]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 5: /usr/libexec/Xorg (0x55b472324000+0x15066d) [0x55b47247466d]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 6: /usr/libexec/Xorg (0x55b472324000+0x5c5ce) [0x55b4723805ce]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 7: /usr/libexec/Xorg (0x55b472324000+0x60676) [0x55b472384676]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 8: /lib64/libc.so.6 (__libc_start_main+0xe5) [0x7fb49d510d85]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) 9: /usr/libexec/Xorg (_start+0x2e) [0x55b47236e01e]
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE)
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) Segmentation fault at address 0x7fb48ceb8730
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE)
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: Fatal server error:
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) Caught signal 11 (Segmentation fault). Server aborting
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE)
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: Please consult the The X.Org Foundation support
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]:          at http://wiki.x.org
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]:  for help.
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) Please also check the log file at "/home/theadmin/.local/share/xorg/Xorg.1.log" for additional information.
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE)
Feb 15 14:07:43 testGUI.examplei.com gnome-session[13578]: gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Power.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session[13578]: gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Clipboard.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session[13578]: gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.MediaKeys.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session[13578]: gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Keyboard.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Power.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Clipboard.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.MediaKeys.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com gnome-session-binary[13578]: WARNING: Application 'org.gnome.SettingsDaemon.Keyboard.desktop' killed by signal 5
Feb 15 14:07:43 testGUI.examplei.com /usr/libexec/gdm-x-session[13568]: (EE) Server terminated with error (1). Closing log file.
Feb 15 14:07:43 testGUI.examplei.com pulseaudio[13117]: X connection to :1 broken (explicit kill or server shutdown).

**Comment by CendioOssman** [comment]
Please see #1595. It sounds like another variation of that.
