### ISSUE TITLE
[Feature Request] Turn off the screen, keyboard and mouse while connected to a real session x:0 (x0vncserver)

### ISSUE THREAD

**Issue by git70** [TigerVNC/tigervnc#1600]
Use case:
When I'm at home and using a remote connection to my office computer (real screen, not virtual), my remote computer is unlocked and vulnerable to third party manipulation.
For example: I'm a lawyer and I'm writing a confidential letter on a remote computer, then anyone who passes by my desk can't look at my remote screen.

NoMachine has a similar function, but it's not Open Source:
https://www.nomachine.com/protecting-the-host-screen-during-a-remote-control-session
https://kb.nomachine.com/AR07M00851

x11vnc has a similar function, but it is only a workaround and is not bulletproof: `-clientdpms`
Additionally, x11vnc seems to be a dead project.

**Comment by CendioOssman** [comment]
Please see #663.
