### ISSUE TITLE
 vncviewer traps input on one display/monitor on multiple zaphod display/monitor configurations

### ISSUE THREAD

**Issue by ileGITimo** [TigerVNC/tigervnc#1604]
**Describe the bug**
This is like bug #447 but monitors are on different zaphod configured displays, e.g. :0.1 and :0.2

**To Reproduce**
1. Need minimum two monitors
2. Start X11 with a zaphod configuration (independent monitors)
3. Start vncviewer on one monitor, go to full screen via F8
4. Move mouse to other monitor
5. Can get focus anywhere on that monitor

**Expected behavior**
Interact with windows on that monitor until getting back to the one where vncviewer is running

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS:  Fedora 35
 - VNC client: tigervnc-1.13.0-4.fc37.x86_64
 - VNC client version: x11vnc-0.9.16-10.fc37.x86_64
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC server: [e.g. TigerVNC, or UltraVNC]
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver`]

**Additional context**
N/A

**Comment by CendioOssman** [comment]
Zaphod is rarely used these days, so it's something we probably never tested. That said, I would have expected to work. The keyboard is shared between the screens, so I would have expected focus and mouse events when switching to the other monitor.

**Comment by ileGITimo** [comment]
I've been using zaphod head configurations ever since I've got more than one monitor, thus for me is not rare :-)

Never used fltk, mostly just Xlib a long time ago.  Looking through the online docs there is no mention of display ever. I suspect, and the behavior makes it look like it, the event_x and event_y calls are just returning values within the full window boundaries, oblivious that the display is not the same.  

I use fvwm with identical DesktopGeometrySizes on both monitors, and when I move my mouse to the other monitor and start clicking on the background, left or right buttons, which page left or right, the monitor with vncviewer starts paging left or right.

I've downloaded the source, will add some logging in the section where the leave/enter is handled, to check what coordinates it gets.

**Comment by CendioOssman** [comment]
We can see how much this snowballs, but otherwise tigervnc-devel is the appropriate list for developer discussion. :)

Since the cursor is captured, it is expected to get a FL_MOVE with coordinates outside the viewer window. A FL_LEAVE is unexpected, but should also work. What is broken is the NULL window, though. The event should always be directed at our window, so you'll need to do some digging and figure out what has gone wrong there.

**Comment by CendioOssman** [comment]
Fixed by 7a2af97.
