### ISSUE TITLE
Add certificate exception handling

### ISSUE THREAD

**Issue by deckaddict** [TigerVNC/tigervnc#1605]
**Is your feature request related to a problem? Please describe.**
When stuck with needing to use self-signed certificates for encryption one can add a specific one to trust in the options.
But if one has to deal with many of these over time it would be easier to verify that it is the right certificate when connecting and then making an exception that is remembered.
Today it is easy to make the exception but you end up being vulnerable to a man in the middle attack since your exception is only for the server address. In environments with multiple users this could be an issue.

**Describe the solution you'd like**
I would prefer the solution that is like today's setup where you are asked if you want to make an exception for the server, but instead having the exception made for the combination of the server and the certificate.

**Describe alternatives you've considered**
No other solutions have been thought of.

**Additional context**
No additionally needed context has been identified.

**Comment by CendioOssman** [comment]
I'm afraid I don't understand your request. We already have this? If the certificate isn't trusted, you get a prompt asking if you wish to continue. We then remember this exception and don't prompt for the same combination of server and certificate again.

**Comment by deckaddict** [comment]
Thanks for the really quick feedback.
I had done some testing, which must have been incorrectly performed, that indicated that even with a new certificate I was passed directly to the password prompt.
I have done more testing now based on your comment and you are perfectly right.
Sorry for taking up your time.
