### ISSUE TITLE
after IP change, server closes connection immediately!

### ISSUE THREAD

**Issue by GustelDE** [TigerVNC/tigervnc#1608]
Hi,

we used tigerVNC with xinetd for many year without problems. Like described here:
https://access.redhat.com/documentation/de-de/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-tigervnc#vnc-based-on-xinetd

Now we had to cahnge the IP of one server and since that, the VNC connection is terminated almost immediately. We did this task in the past a few times without any problems.

The interesting point is, if we change tht IP back to the old IP, it works again! It seems somewhere is a binding: old-IP<->port 5900.

If we change the port in the /etc/services file to a different port than 5900, like 5901, it works too.

Is there a solution so we can use port 5900 again?
Our Linux is a Orcale-Linux 8, most recent version, TigerVNC also most recent version available.

**Comment by CendioOssman** [comment]
No response. Closing.
