### ISSUE TITLE
Question about encryption

### ISSUE THREAD

**Issue by upstroke-version** [TigerVNC/tigervnc#1609]
I first want to apologize that I wrote this newb question at here. (I don't have a google acount to write on community forum...)

I'm planing to connect macOS client from outside of my local network to windows server at home.
My initial plan was using VPN server on router to access home network and just using normal unencrypted VNC, thinking using with VPN would mitigate most of security problems of vnc.
However, I just learned that "VPN" doesn't necessarily mean full encryption, my router apparently only supports L2TP, not L2TP\IPsec. So I looked for cross platform encrypted vnc and TigerVNC seems like only option.

My question is...
1. When using [TLS encryption with tigervnc](https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection), does it mean full end-to-end encryption? So everything like  screen video feed, keystroke from client, clipboard sharing, authentication are all secure with encryption?

2. It looks like[ RSA-AES option](https://github.com/TigerVNC/tigervnc/pull/1519) is recently added, Should I enable this option along with "TLS with X.509 certificates" option If I were to follow the [guide from wiki](https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection), or choose between two? I'm not sure what this option does.

3. Should I use version 1.12.0 of winvnc as the wiki says, or use latest version to use new security settings like RSA-AES option?

4. I guess macOS's default "Screen sharing" app won't be compatible with TigerVNC's encryption, am I correct?

Once again I'm sorry for all these questions, and thanks for all contributors of this project for making this awesome program!

**Comment by CendioOssman** [comment]
> I first want to apologize that I wrote this newb question at here. (I don't have a google acount to write on community forum...)

Yeah, they want you to think that. You should be able to register using any email address by using the links on tigervnc.org, though.

> I'm planing to connect macOS client from outside of my local network to windows server at home.

Note that TigerVNC's Windows server is unmaintained and may not work correctly. I'm afraid that I'm not aware of any other VNC server for Windows that supports encryption.

> 1. When using [TLS encryption with tigervnc](https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection), does it mean full end-to-end encryption? So everything like  screen video feed, keystroke from client, clipboard sharing, authentication are all secure with encryption?

Yes, everything, except the initial handshake, will be encrypted.

> 2\. It looks like[ RSA-AES option](https://github.com/TigerVNC/tigervnc/pull/1519) is recently added, Should I enable this option along with "TLS with X.509 certificates" option If I were to follow the [guide from wiki](https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection), or choose between two? I'm not sure what this option does.

That is an entirely different encryption scheme from RealVNC. I would recommend TLS as that has had a lot more effort put in to it. RSA-AES would only be recommended when you need to be compatible with a RealVNC client or server.

(both can be enabled at the same time, though)

> 3\. Should I use version 1.12.0 of winvnc as the wiki says, or use latest version to use new security settings like RSA-AES option?

I don't see anything about specific versions on that page?

In general, the latest version is always the recommended one.

> 4\. I guess macOS's default "Screen sharing" app won't be compatible with TigerVNC's encryption, am I correct?

That is correct. I don't know if they support any encryption. If they do, it is secret and someone needs to reverse engineer it first.

**Comment by upstroke-version** [comment]
Thank you for fast and detailed answer.
I will close this issue.

**Comment by Neustradamus** [comment]
Dear @TigerVNC team, @CendioOssman: There is a problem in changelog and in releases:
- https://github.com/TigerVNC/tigervnc/releases/tag/v1.12.90
- https://github.com/TigerVNC/tigervnc/releases/tag/v1.13.0

Here too:
- https://groups.google.com/g/tigervnc-announce/c/HNjNihckpEY
- https://groups.google.com/g/tigervnc-announce/c/zpZ-AzT6z7o
- https://launchpad.net/debian/+source/tigervnc/1.13.1+dfsg-1

"The servers and native viewer now support RealVNC's RSA-AES authentication methods and encryption"

It is not supported in TigerVNC Server.

Can you replace by:
"The native viewer now support RealVNC's RSA-AES authentication methods and encryption"

Thanks in advance.

**Comment by CendioOssman** [comment]
The servers very much supports RSA-AES. I'm not sure where you got a different impression. Please use our discussion forum if you need assistance setting those up.

**Comment by Neustradamus** [comment]
@CendioOssman: I have tested, no options for RSA-AES in TigerVNC Server and when I try to connect the machine, it is old historical password.

```
None
Anonymous TLS
TLS with X.509 certificates
```

Can you update the changelog to be correct?

Thanks in advance.

cc: @pdlan, @bphinz.
