### ISSUE TITLE
very low frame rate and visual artifacts

### ISSUE THREAD

**Issue by upstroke-version** [TigerVNC/tigervnc#1610]
**Describe the bug**
TigerVNC frame rate is very low on my device, and I think this is not normal behavior.
I've uploaded video file to show how it looks.
Connection speed shouldn't be an issue, since server is connected via gigabit ethernet with router and client is connected via high speed wifi(about 500mbps) at same local network. Also, both machines are decently powerful (server: i7 GTX1060, client: Apple M1), so performance shouldn't be an issue too.
I tried various compression settings, but nothing improved frame rate and visual artifacts. though resolution and color look quite decent.

**This is the video recording.**
[recording.mp4.zip](https://github.com/TigerVNC/tigervnc/files/10948521/recording.mp4.zip)

**Client (please complete the following information):**
 - OS: macOS 13.2.1
 - VNC client: TigerVNC
 - VNC client version: 1.13.1
 - Client downloaded from: homebrew

**Server (please complete the following information):**
 - OS: windows 10
 - VNC server:  TigerVNC(tigervnc64-winvnc-1.13.1.exe)
 - VNC server version:  1.13.1
 - Server downloaded from: sourceforge
 - Server was started using: [e.g. `vncserver`]

**Comment by samhed** [comment]
Yeah, that looks horrible indeed. Unfortunately, TigerVNC's Windows server isn't very well maintained. Most development resources goes towards the Linux server. I'd recommend testing a different VNC server that is more focused on Windows. Windows is not my area of expertise, but perhaps you will have better luck with UltraVNC? You can still use the TigerVNC client for your Mac if you like.

If you're stuck with TigerVNC for the Windows server, try disabling as much visual bling as possible. It might help.

**Comment by CendioOssman** [comment]
We already have #277 for this issue, so I'll go ahead and mark this one as a duplicate.
