### ISSUE TITLE
Restoring the resize remote session screen option

### ISSUE THREAD

**Issue by steve8988** [TigerVNC/tigervnc#1613]
Would it be possible to restore the two options (shown in attached screenshot of older version):

- resize remote session on connect
- resize remote session to the local window

to the connection options in vnc viewer?  I need to disable the resize in my set up and I noticed these options were left out of the latest version of vnc viewer.  I am aware this can be disabled in command line, but it would be greatly convenient to put them back into the options.  Thank you very much.

![oldvnc](https://user-images.githubusercontent.com/17192859/227182830-f860ad52-646a-4196-9a60-d64dc6667b2d.png)

**Comment by CendioOssman** [comment]
The old interface was very complex and confusing, so we tried to focus on the use cases we believed most useful to users.

Would you mind describing the setup you have and why it is desirable to disable the resizing?

**Comment by steve8988** [comment]
I use tigervnc to remotely access my work PC, which has a dual monitor setup, with a resolution of 3840x1080.  The server is a x0vncserver.  When I remote into it from home, the automatic resizing changes it to a much smaller resolution (something like 1280 x 720).  So the desktop isn't extended to the second monitor and all my windows from both monitors become clustered into one.  So I have to disable the resizing setting to prevent this from happening.

**Comment by derekschrock** [comment]
The use case is, believe it or not, that you don't want the client to resize the remote server.  While testing I might be on a different size display but I want to connect and view the existing/untouched session.

**Comment by samhed** [comment]
But as per @steve8988's explanation, the decision of not wanting the application windows to be clustered together, is bound to the content in the remote. It doesn't change depending on which viewer or machine you connect from. In my mind, that means it is logical for this to be a server-side configuration – “don't let any clients resize this remote”.

Do we have any arguments as to why this decision belongs on the viewer side?

**Comment by CendioOssman** [comment]
I don't see any discussion that points to a different use case than that, so I'll go ahead and close this for now.
