### ISSUE TITLE
Tigervnc 1.12.0 installed on RHEL 8.7 server shows black screen on connecting by vnc client for some users

### ISSUE THREAD

**Issue by RameshSharmaGithub** [TigerVNC/tigervnc#1618]
**Describe the bug**
Tigervnc 1.12.0 installed on RHEL 8.7 server shows black screen on connecting by vnc client for some users.
All the steps mentioned in the below link was followed to do the setup:-

https://www.golinuxcloud.com/setup-vnc-server-centos-8

**To Reproduce**
1. Go to tight vnc client and connect to the tigervnc server using the ip address and port number.
2. Click on Connect button.
3. A black screen appears.

**Expected behavior**
A graphical user interface should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/58744116/231832664-2918109a-6970-4365-b201-06ceb6145e5a.png)

**Client (please complete the following information):**
 - OS: Windows
 - VNC client: TigerVNC and TightVNC
 - VNC client version: 1.12.0
 - Client downloaded from: https://sourceforge.net/projects/tigervnc/files/stable/1.12.0/

**Server (please complete the following information):**
 - OS: RHEL 8.7
 - VNC server: TigerVNC
 - VNC server version: 1.12.0
 - Server downloaded from: yum repository.
 - Server was started using: Followed the link 
 https://www.golinuxcloud.com/setup-vnc-server-centos-8

**Additional context**
Out of 10 users, 1 user worked fine, and 9 users are getting black screen on connecting. Please suggest what is wrong when all the 10 users are having the same configuration.

**Comment by samhed** [comment]
That seems like some sort of application issue on the server side? The buttons shown in the screenshot don't look like they belong to either TigerVNC's viewer or to Windows.

I'm confused, however. That guide you linked seems to set up GNOME sessions to run on the VNC server. That is not what you have done?

**Comment by stoicdev81** [comment]
I had this same issue and tried so many things to try to get it to work. Eventually I stumbled up https://community.spiceworks.com/topic/2314270-installed-tightvnc-on-windows-machine-but-screen-is-black-when-i-connect which reminded me that to use VNC the VM needs to believe it has a monitor. Apparently this is not true of a Hyper-V VM, at least not the way I made it. Coincidentally I also wanted to change the resolution of the VM, a bit small for my taste, but you can't do it from the VM, have to do it from PowerShell a la https://learn.microsoft.com/en-us/answers/questions/341631/how-to-adjust-virtual-machine-display-resolution-t. After doing that the VNS worked.

**Comment by CendioOssman** [comment]
No response from original poster. Closing.
