### ISSUE TITLE
CMake Ninja generates errors while Make does not on Ubuntu

### ISSUE THREAD

**Issue by bob333** [TigerVNC/tigervnc#1619]
**Describe the bug**
The bug is related to the CMake Ninja generator, which triggers errors during the building process, while building with Make does not produce any errors.

**To Reproduce**
1. $ cmake -G "Ninja" -S /home/bob/src/tigervnc_project/tigervnc/ -B /home/bob/src/tigervnc_project/build
2. $ cmake --build /home/bob/src/tigervnc_project/build
ninja: error: '/home/bob/src/tigervnc_project/tigervnc/po/*.po', needed by 'vncviewer/vncviewer.desktop', missing and no known rule to make it
3. Expected to see no errors

While the same with "Unix Makefiles" generator does not produce any erro
$ cmake -G "Unix Makefiles" -S /home/bob/src/tigervnc_project/tigervnc/ -B /home/bob/src/tigervnc_project/build
$ cmake --build build # compiles fine

Compiled at the commit 640c5503c1b74d518a34bbce0fb7392876e8fb6d 

**Client (please complete the following information):**
$ ninja --version
1.10.1

$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by CendioOssman** [comment]
Thanks for reporting. I can reproduce the issue here on Fedora 36.

Any specific problems that led you to use Ninja instead of make?

**Comment by CendioOssman** [comment]
It should be fixed in 57cdcedf1bde06195f782fd2cfcf302050245da6.

Note that we rarely use Ninja, so I'm afraid I can't promise it won't break again. Please let us know if it does, though.
