### ISSUE TITLE
openGL problems - redhat6.6

### ISSUE THREAD

**Issue by durack1** [TigerVNC/tigervnc#162]
It seems that running glxgears or even glxinfo doesn't appear to work in TigerVNC 1.4.2 as below:

```
[user1 ~]$ glxinfo
name of display: :1.0
Error: couldn't find RGB GLX visual or fbconfig
[user1 ~]$ glxgears
Error: couldn't get an RGB, Double-buffered visual
[user1 ~]$ uname -a
Linux machinename 2.6.32-504.12.2.el6.x86_64 #1 SMP Sun Feb 1 12:14:02 EST 2015 x86_64 x86_64 x86_64 GNU/Linux
[user1 ~]$ more /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.6 (Santiago)
[user1 ~]$ vncserver --version | grep TigerVNC

WARNING: The first attempt to start Xvnc failed, possibly because the font
catalog is not properly configured.  Attempting to determine an appropriate
font path for this system and restart Xvnc using that font path ...
Could not start Xvnc.

Xvnc TigerVNC 1.4.2 - built Jan 23 2015 19:04:52
Copyright (C) 1999-2015 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
```

Is this behaviour expected?

**Comment by CendioOssman** [comment]
Do you have a proprietary graphics driver installed (e.g. Nvidia's or AMD's)? If so, then it is expected as those modify the system libraries in incompatible ways.

**Comment by bphinz** [comment]
On Thursday, April 9, 2015, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Do you have a proprietary graphics driver installed (e.g. Nvidia's or
> AMD's)? If so, then it is expected as those modify the system libraries in
> incompatible ways
>
If that's the case, then a possible workaround is to use the "generic"
binaries ( which are really just the unpacked el5 RPMs).  These include a
private libGL and thus can be used on systems where 3rd party graphics
drivers have supplanted the system libGL.

HTH,
-brian


-- 
Sent from Gmail Mobile

**Comment by durack1** [comment]
@CendioOssman @bphinz this is just a generic redhat 6 installation which has been patched up to 6.6. It's a Dell PowerEdge R720 (Xeon E5-2643) with no onboard video card - so no hardware and no (non redhat6.6) proprietary drivers either.

For completeness here are the currently installed (default redhat6.6) xorg drivers:
```
[durack1@oceanonly ~]$ rpm -qa | grep drv
xorg-x11-drv-ast-0.98.0-1.el6.x86_64
xorg-x11-drv-mutouch-1.3.0-5.el6.x86_64
xorg-x11-drv-xgi-1.6.0-20.20121114git.el6.x86_64
xorg-x11-drv-elographics-1.4.1-3.el6.x86_64
xorg-x11-drv-r128-6.9.1-8.el6.x86_64
xorg-x11-drv-vmware-13.0.1-9.el6.x86_64
xorg-x11-drv-wacom-0.23.0-4.el6.x86_64
xorg-x11-drv-fpit-1.4.0-6.el6.x86_64
xorg-x11-drv-savage-2.3.7-2.el6.x86_64
xorg-x11-drv-ati-7.3.99-2.el6.x86_64
xorg-x11-drv-i128-1.3.6-10.el6.x86_64
xorg-x11-drv-sisusb-0.9.6-10.el6.x86_64
xorg-x11-drv-nouveau-1.0.10-1.el6.x86_64
xorg-x11-drv-evdev-2.8.2-4.el6.x86_64
xorg-x11-drv-mach64-6.9.4-8.el6.x86_64
xorg-x11-drv-rendition-4.2.5-10.el6.x86_64
xorg-x11-drv-v4l-0.2.0-36.el6.x86_64
xorg-x11-drv-vmmouse-13.0.0-2.el6.x86_64
xorg-x11-drv-apm-1.2.5-10.el6.x86_64
xorg-x11-drv-glint-1.2.8-10.el6.x86_64
xorg-x11-drv-modesetting-0.8.0-14.el6.x86_64
xorg-x11-drv-siliconmotion-1.7.7-9.el6.x86_64
xorg-x11-drv-voodoo-1.2.5-10.el6.x86_64
xorg-x11-drv-dummy-0.3.6-15.el6.x86_64
xorg-x11-drv-i740-1.3.4-11.el6.x86_64
xorg-x11-drv-penmount-1.5.0-5.el6.x86_64
xorg-x11-drv-tdfx-1.4.5-10.el6.x86_64
xorg-x11-drv-openchrome-0.3.3-6.el6.x86_64
xorg-x11-drv-acecad-1.5.0-7.el6.x86_64
xorg-x11-drv-fbdev-0.4.3-16.el6.x86_64
xorg-x11-drv-mga-1.6.3-5.el6.x86_64
xorg-x11-drv-s3virge-1.10.6-10.el6.x86_64
xorg-x11-drv-vesa-2.3.2-15.el6.x86_64
xorg-x11-drv-qxl-0.1.1-15.el6.x86_64
xorg-x11-drv-hyperpen-1.4.1-5.el6.x86_64
xorg-x11-drv-sis-0.10.7-10.el6.x86_64
xorg-x11-drv-intel-2.99.911-6.el6.x86_64
xorg-x11-drv-keyboard-1.8.0-1.el6.x86_64
xorg-x11-drv-trident-1.3.6-10.el6.x86_64
xorg-x11-drv-ati-firmware-7.3.99-2.el6.noarch
xorg-x11-drv-aiptek-1.4.1-5.el6.x86_64
xorg-x11-drv-mouse-1.9.0-1.el6.x86_64
xorg-x11-drv-void-1.4.0-23.el6.x86_64
xorg-x11-drv-cirrus-1.5.2-2.el6.x86_64
xorg-x11-drv-nv-2.1.20-5.el6.x86_64
xorg-x11-drv-synaptics-1.7.6-1.el6.x86_64
```

**Comment by bphinz** [comment]
2015-04-09 12:24 GMT-04:00 Paul J. Durack <notifications@github.com>:

> @CendioOssman <https://github.com/CendioOssman> @bphinz
> <https://github.com/bphinz> this is just a generic redhat 6 installation
> which has been patched up to 6.6. It's a Dell PowerEdge R720 (Xeon E5-2643)
> with no onboard video card - so no hardware and no (non redhat6.6)
> proprietary drivers either.
>
> For completeness here are the currently installed (default redhat6.6) xorg
> drivers:
>
> [durack1@oceanonly ~]$ rpm -qa | grep drv
>
> How about rpm -qa | grep tigervnc?

TIA,
-brian

**Comment by durack1** [comment]
@bphinz that was listed in the original issue comment:
```
Xvnc TigerVNC 1.4.2 - built Jan 23 2015 19:04:52
```
The redhat repos are a long way behind the times with TigerVNC, so it was installed locally..

**Comment by bphinz** [comment]
On Thu, Apr 9, 2015 at 12:55 PM, Paul J. Durack <notifications@github.com>
wrote:

> @bphinz <https://github.com/bphinz> that was listed in the original issue
> comment:
>
> Xvnc TigerVNC 1.4.2 - built Jan 23 2015 19:04:52
>
> The redhat repos are a long way behind the times with TigerVNC, so it was
> installed locally..
>
Yup.  I'm trying to determine where the vncserver script came from.  (I
don't believe that it's changed, but...)

**Comment by durack1** [comment]
Here's the version on the machine: https://gist.github.com/durack1/5d41a808e599f21a62d1#file-vncserver

**Comment by bphinz** [comment]
On Thu, Apr 9, 2015 at 2:28 PM, Paul J. Durack <notifications@github.com>
wrote:

> Here's the version on the machine:
> https://gist.github.com/durack1/5d41a808e599f21a62d1#file-vncserver
>
Can you explain what you've done to install this?  The timestamp matches
the one from the generic binary.  Why didn't you just install the el6 rpms?
no root access?  openGL works for me using the generic binary on el6, even
running locally from my home directory.  I didn't test the vncserver
script, I just unpacked the tarball and ran "./usr/bin/Xvnc :1 …".  The
generic Xvnc binary is linked against the libraries in the
../lib64/tigervnc directory (relative to Xvnc), so if you simply extracted
the executable and discarded those libraries (or rearranged their
locations), that might explain why openGL appears broken.  Without knowing
more about your setup it's difficult to debug though.

-brian

**Comment by durack1** [comment]
@bphinz thanks for the prompt.. I just reinstalled tigervnc using the 1.4.3 binaries and I seem to be working perfectly this time around.. It seems the previous installation was partial, with some libraries not having been installed..

Thanks for the prompt and tips..
