### ISSUE TITLE
We Really need a tutorial

### ISSUE THREAD

**Issue by Moe-Sherif** [TigerVNC/tigervnc#1620]
I have been using tiger vnc viewer for a long time but i always had issues with the server as it's configuration is really complex comparing to another vnc servers like turbo vnc for example that works right out of the box. I really wish you can upload a small tutorial showing us the simplest way to configure the server as there's a lot of people that want to enjoy tiger vnc unique features but can't due to configuration complexity

**Comment by CendioOssman** [comment]
There is a HOWTO included with the new service-based approach to starting sessions:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

Please have a look there as it contains step-by-step instructions to get going.
