### ISSUE TITLE
Feature: Controlling dot when there is no cursor option through a command line flag

### ISSUE THREAD

**Issue by gvking** [TigerVNC/tigervnc#1622]
Hello,

In the TigerVNC settings, you are able to select the option of "show dot when there is no cursor". However, if I'm running tigervnc via command line for testing or other purposes, I'd like the ability to configure this option as true in the command line itself instead of opening another window up, selecting my option, and then rebooting or loading the vncviewer again.

Thanks,
Vikram

**Comment by CendioOssman** [comment]
All settings are available from the command line. In this case, the setting is `DotWhenNoCursor`. You can find them all listed here:

https://tigervnc.org/doc/vncviewer.html
