### ISSUE TITLE
Display output is not active bug

### ISSUE THREAD

**Issue by gvking** [TigerVNC/tigervnc#1623]
Hello,

I was following [these steps](https://chromium.googlesource.com/chromiumos/docs/+/master/cros_vm.md) to set up Simple Chrome for ChromiumOS on a general Linux distribution.

When I install tigervnc through sudo apt install, and remove it via sudo apt remove, and then install again, when I run tigervnc connecting to my QEMU emulator, I get a screen that shows "display output is not active". Once in a while my expected output, a Chromium Login, shows but then disappears within a half second and when it does show, it only renders the blue pixels..?

Thank you!

**Comment by CendioOssman** [comment]
I'm afraid that sounds like something coming from your server, so it's not something we can help out with on our end. I suggest you ask the QEMU crowd, and hopefully, they can help you out with why you aren't getting a display.
