### ISSUE TITLE
Multible Mouse Pointer on RHEL 8.7

### ISSUE THREAD

**Issue by Baefisch** [TigerVNC/tigervnc#1625]
**Describe the bug**
If i start vnc sessions through systemd, i will have multible Mouse Pointers on each session. Allready tried different viewer servers and options. Each User which is connecting creates a Mousepointer on each session.

**To Reproduce**
1. Install Rhel8.7
2. dnf install tigervnc-server
3. systemctl start vncserver@\:1.service
4. systemctl start vncserver@\:2.service
5. Connect to each session

**Expected behavior**
One Mouse Pointer per session.

**Screenshots**
https://woidcloud.de/index.php/s/SPXKba5bY685i82

**Client:**
 - OS:  Windows 10
 - VNC client: realVnc Viewer
 - VNC client version: 7.0.1
 - Client downloaded from: realvnc

**Server:**
 - OS: Rhel8.7
 - VNC server: [tigervnc-server.x86_64
 - VNC server version: 1.12.0-9.el8_7.3 
 - Server downloaded from: Redhat Repo
 - Server was started using: systemctl start vncserver@\:1.service

**Additional context**

**Comment by CendioOssman** [comment]
There appears to be some artefacts there that might be interesting. Do you think you could do a screenshot rather than a photo and attach here?

**Comment by Baefisch** [comment]
allready pasted and shared on my owncloud. 
https://woidcloud.de/index.php/s/SPXKba5bY685i82

**Comment by CendioOssman** [comment]
I'm afraid I'm only seeing a photo there. We would need a normal screenshot to see the specific details of the cursor corruption.

**Comment by Baefisch** [comment]
it´s not possible to do a screenshot, because the mousepointers are not shown. Windows & Linux is hiding mousepointers on a screenshot. Then i tried to record with windows steps recorder. On this pictures there is only one mousepointer. Strange!!! Will atach a new Photo. Maybe this helps. 
https://woidcloud.de/index.php/s/FXqkm9BgcqttP4X

**Comment by CendioOssman** [comment]
That is very strange indeed.

Does this weird cursor stay the same as you move it around? Or does the corruption change in some way?

Does this happen with other clients? E.g. the TigerVNC client?

**Comment by Baefisch** [comment]
Yes, it stays. Cursor will change in the way it should. For example for selecting text in a terminal. But all of them are twice if two useres are connected. If three users are connected its three time. 
Yes, also on TigerVNC client.

**Comment by CendioOssman** [comment]
Thanks for testing. If both the RealVNC viewer and the TigerVNC viewer show the issue, then the problem is likely on the server.

Could you test with our builds of the server, instead of Red Hat's? You'll find them via the release page.

**Comment by CendioOssman** [comment]
No, I'm afraid we don't have any repository setup. The packages should have the same structure as Red Hat's original packages. What dependency issue did you see?

**Comment by CendioOssman** [comment]
No response. Closing.
