### ISSUE TITLE
OpenGL/Vulkan GPU acceleration support

### ISSUE THREAD

**Issue by Forza-tng** [TigerVNC/tigervnc#1626]
TigerVNC is great because it let's me run X apps on my remote servers and not have to run a full desktop environment (currently using openbox).

What I would like to see is the ability to use gl acceleration on the host for the apps. Currently, only software rendering through mesa is supported. Would it be possible to allow HW accel with TigerVNC somehow? I have some years back tried VirtualGL, but found it difficult to use and resource demanding, and had bugs on my system.

Just to clarify, I am not looking to render GL on the VNC clients in this ticket, although that would also be an awesome thing to have someday :)

I have qemu/KVM guests that run with virtio GPU, which works really well. Having similar in bare-metal TigerVNC would great.

**Comment by CendioOssman** [comment]
That would be nice. Unfortunately, we cannot compare things with QEMU as it can use the "normal" way of doing things by virtue of QEMU faking a complete graphics card for the system. We would need some more strange combination, as we want the GPU to render in to our separate, "fake" display.

Not impossible, but not clear on how that would need to be set up. So for the moment, VirtualGL is the recommended way to accelerate things.

**Comment by CendioOssman** [comment]
Vulkan is probably also interesting to accelerate.

**Comment by CendioOssman** [comment]
We now have GPU acceleration for OpenGL and Vulkan as of #1771. Please try the 1.14.0 beta. :)

**Comment by Forza-tng** [comment]
This is great news 👍

Anything particular we should do to enable GPU acceleration? I'm using the Gentoo package and I think it works correct automatically:

### glxinfo
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.57, 6.8.11-gentoo-e350) (0x1638)
    Version: 24.0.9
    Accelerated: yes
    Video memory: 512MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 381 MB, largest block: 381 MB
    VBO free aux. memory - total: 15667 MB, largest block: 15667 MB
    Texture free memory - total: 381 MB, largest block: 381 MB
    Texture free aux. memory - total: 15667 MB, largest block: 15667 MB
    Renderbuffer free memory - total: 381 MB, largest block: 381 MB
    Renderbuffer free aux. memory - total: 15667 MB, largest block: 15667 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 512 MB
    Total available memory: 16243 MB
    Currently available dedicated video memory: 381 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Graphics (radeonsi, renoir, LLVM 17.0.6, DRM 3.57, 6.8.11-gentoo-e350)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.9
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
```

**Comment by CendioOssman** [comment]
It does indeed looks to be working fine for you. :)

It's usually easiest to look at the "OpenGL renderer string" to see if you are using the GPU or not. Software rendering will say "llvmpipe".
