### ISSUE TITLE
Remote screen occupies only a quarter of window in vncviewer for Mac

### ISSUE THREAD

**Issue by steve8988** [TigerVNC/tigervnc#1628]
Hello,

I remotely connect to my linux box that runs x0vncserver using the following command

`x0vncserver -Geometry 3840x1080+0+0 -display :0 -rfbauth ~/.vnc/passwd -rfbport 5901 -AcceptSetDesktopSize=0`

Connecting to this server using vncviewer on Fedora 38 is fine and remote desktop fills up the window
![linux](https://user-images.githubusercontent.com/17192859/236391590-7b4b192a-bb46-4829-b4e1-0a3d79b7c900.png)

However, when I try using vncviewer on my Macbook Air M2, I get the following where it only occupies the lower quadrant
![mac](https://user-images.githubusercontent.com/17192859/236391711-0ebc5741-c8bc-4879-b399-f3e7eba4b8e2.jpg)

I've tried using turbovnc viewer on Mac and it doesn't have this problem.

**Comment by CendioOssman** [comment]
This issue only appears when in incorrect builds of the viewer. Please use the build from our release page and the issue should go away.
