### ISSUE TITLE
Error while compiling on ubuntu 22.04

### ISSUE THREAD

**Issue by Galex88** [TigerVNC/tigervnc#1629]
**Describe the bug**
I'm getting an error while trying to compile on ubuntu 22.04. I installed all dependencies required in the BUILDING.txt file.

**To Reproduce**
Just launch 'make' on ubuntu 22.04.

**Screenshots**
![Capture d’écran 2023-05-15 105527](https://github.com/TigerVNC/tigervnc/assets/24251141/9f0a9cca-310e-4cda-b724-2cdb96ad8b6e)

**Client (please complete the following information):**
 - OS: Ubuntu 22.04
 - VNC client: TigerVNC
 - Client downloaded from: GitHub

**EDIT**
In fact, I don't need that server part but as I encountered the issue, I prefer to show it to you :)
I personally just want to have the client part.

**Comment by CendioOssman** [comment]
Thanks for reporting. It looks like we missed the corner case of when Xtest development files are missing.
