### ISSUE TITLE
format string different from variable

### ISSUE THREAD

**Issue by maddin200** [TigerVNC/tigervnc#1632]
/vncviewer/parameters.cxx line 436
Code:
```c++
  size_t index = 0;
  assert(SERVER_HISTORY_SIZE < 100);
  char indexString[3];

  try {
    while(index < serverHistory.size() && index <= SERVER_HISTORY_SIZE) {
      snprintf(indexString, 3, "%d", index); // <-- check format vs size_t
```

**Comment by maddin200** [comment]
same procedure line 525

**Comment by CendioOssman** [comment]
Hmm... That's odd. We are supposed to have checks for that. Will need to investigate how they missed this.

Thanks for bringing it to our attention!

**Comment by CendioOssman** [comment]
The lack of warnings is apparently because of gettext. I've filed an issue with them:

https://savannah.gnu.org/bugs/index.php?64384
