### ISSUE TITLE
Localhost option ignored TigerVNC 1.12 "x0vncserver" on Ubuntu 22.04

### ISSUE THREAD

**Issue by atcapollo** [TigerVNC/tigervnc#1633]
Running:

`x0vncserver -localhost=0 -passwordfile ~/.vnc/passwd -interface=192.168.3.100 -verbose -display=:0`

Results in:

`Starting /usr/bin/X0tigervnc -display :0 -interface 192.168.3.100 -localhost=**1** -desktop MachineName:0 (username) -rfbport 5900 -PasswordFile /home/username/.vnc/passwd -SecurityTypes VncAuth`

Tired the following... none seem to work
-localhost=no
-localhost no
-localhost=0
-localhost 0

**Comment by atcapollo** [comment]
Had to manually specify -SecurityTypes VncAuth,TLSVnc

Man states:

```
-SecurityTypes sec-types
              Specify which security scheme to use for incoming connections. Valid values are a  comma  separated
              list  of None, VncAuth, Plain, TLSNone, TLSVnc, TLSPlain, X509None, X509Vnc, and X509Plain. Default
              is VncAuth if -localhost is not given and VncAuth,TLSVnc if -localhost no is given.

```
The default when -localhost no is given, does not seem to be automatically adding TLSVnc. I had to manually specify this, either the manual needs updating or the implementation based on my experience.

**Comment by CendioOssman** [comment]
I'm afraid that that startup script is not part of TigerVNC, but is rather something that Debian/Ubuntu adds. That means that we unfortunately cannot help you with it. Please file an issue with your distribution and hopefully, they can help you out.
