### ISSUE TITLE
Error building in Win10

### ISSUE THREAD

**Issue by X-Vaskys** [TigerVNC/tigervnc#1637]
**Describe the bug**
Trying to compile TigerVNC in Win10 results in a cmake error

**To Reproduce**
1. Follow the steps to build TigerVNC on Windows up to the Installer Part
2. Set the Path through "Export"
3. Run "mingw32-make.exe installer"
4. Process fails

**Expected behavior**
MingW is meant to build the Installer

**Screenshots**
![image](https://github.com/TigerVNC/tigervnc/assets/20264383/9f757413-afee-4fb0-a869-ed696a023619)

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC
 - VNC client version: 1.13.1
 - Client downloaded from: GitHub Source Code (git)

**Server (please complete the following information):**
 - Clientside Issue, nothing Serverside yet. -

**Additional context**
I even tried making a "temp" folder and adding all files to it, yet cmake still believes the files do not exist.

**Comment by QF1987** [comment]
> 关闭，因为我决定使用另一个选项并放弃 TigerVNC。

我遇到同样的问题，你怎么解决的？
