### ISSUE TITLE
/usr/sbin/vncsession: cannot execute: required file not found

### ISSUE THREAD

**Issue by dausruddin** [TigerVNC/tigervnc#1638]
**Describe the bug**
I have installed tigervnc on my Debian 12 by extracting the binaries into my system.
When I am trying to start tigervnc using systemctl, it fails with this error

`/usr/libexec/vncsession-start: line 43: /usr/sbin/vncsession: cannot execute: required file not found`

**To Reproduce**
1. Extract binaries, `$ sudo tar xvfk tigervnc-1.13.1.i386.tar.gz --strip-components=1 -C /`
2. Edit `vncserver.users` and add a user
3. Start tigervnc

**Expected behavior**
TigerVNC should be running

**Screenshots**
![Screenshot_20230629-180603_Termux](https://github.com/TigerVNC/tigervnc/assets/5763466/e3057b06-7183-4093-a51b-b1f19c971060)

**Server (please complete the following information):**
 - OS: Debian 12
 - VNC server: TigerVNC
 - VNC server version: 1.13.1
 - Server downloaded from: Sourceforge
 - Server was started using: systemctl

**Additional context**
N/A

**Comment by CendioOssman** [comment]
Huh. That's an unfamiliar error message. I would guess there is some library missing, though.

What doesn `ldd /usr/sbin/vncsession` say?

**Comment by CendioMartin** [comment]
@dausruddin Is the i386 package correct for your platform architecture? 
There's also a x64 package available, tigervnc-1.13.1.x86_64.tar.gz
