### ISSUE TITLE
Certificate for Windows binaries appear to be expired ; on 6/1/2023.

### ISSUE THREAD

**Issue by trogdorrr** [TigerVNC/tigervnc#1639]
**Describe the bug**

Certificate for Windows binaries appear to be expired ; on 6/1/2023.

**To Reproduce**
1. Right click exe
2. Click on: Properties, Digital Signatures, Brian Patrick Hinz, Details, View Certificate
3. Scroll down to bottom
4. See error: Valid from 5/27/2020 to 6/1/2023

** (please complete the following information):**
 - OS: Windows 11
 - VNC client: vncviewer-1.13.1.exe, tigervnc64-1.13.1.exe
 - VNC client version: vncviewer-1.13.1
 - Client downloaded from: SourceForge

**Comment by CendioOssman** [comment]
That should not be an issue for 1.13.1 since it was released back in March. But it will be a problem for future releases.

@bphinz, have you got an eye on this?

**Comment by bphinz** [comment]
Ugh, code signing cert renewal time.  I should have renewed it on July 1 just to align with Bobby Bonilla day...  Thanks, I missed the reminder email the issuer sent me.

**Comment by dmigowski** [comment]
Please note that code signing alone is not enought, but you should also timestamp the code signing. The latter is required to make executables trustworthy even when the code signing certificate has expired. 

I didn't check how singing is performed here but you might have a look at signtool.exe's /tr option.

**Comment by bphinz** [comment]
The new signing cert is in place and the current nightly builds have the updated signatures, including timestamps (thanks for pointing that out @dmigowski)
