### ISSUE TITLE
No local cursor is being shown when connecting to a PiKVM v4

### ISSUE THREAD

**Issue by darkbasic** [TigerVNC/tigervnc#1642]
**Describe the bug**
When connecting to my PiKVM v4 using [these settings](https://docs.pikvm.org/vnc/#enabling-vnc-on-the-pikvm-side) no local cursor is being shown, instead it shows the remote cursor (which lags too much to be usable).
The PiKVM web UI shows both the local cursor (a circle) and the remote cursor. Ideally the remote cursor should be hidden, not sure how but maybe by faking the input events as touch inputs so that the remote cursor won't even move until you click.
If the remove cursor can indeed be hidden then maybe the local one should be changed to something more visible than the thin circle in the web UI.
Worse case scenario it's better to have both the remote cursor and the local cursor than just the remote one which is completely unusable.

**To Reproduce**
1. Connect to a PiKVM v4 using [these settings](https://docs.pikvm.org/vnc/#enabling-vnc-on-the-pikvm-side)
2. Remote cursor is being shown (laggy, gets clipped when you reach the border of the window). Local cursor is not being shown.

**Expected behavior**
The local cursor should be rendered (like the small circle shown in the PiKVM web UI).
Ideally the remote cursor should not be shown at all.

**Screenshots**
![image](https://github.com/TigerVNC/tigervnc/assets/1047358/816d96e5-9a44-4537-bc2b-bd56bb51cf2f)

**Client (please complete the following information):**
 - OS: Gentoo Linux ppc64le
 - VNC client: TigerVNC
 - VNC client version: 1.13.1-r3
 - Client downloaded from: Gentoo ebuild

**Server (please complete the following information):**
 - OS: PiKVM v4 Mini
 - VNC server: 
 - VNC server version: 
 - Server downloaded from: 
 - Server was started using: 

**Additional context**

**Comment by CendioOssman** [comment]
That is what the "Show dot when no cursor" setting is for. Have you tried enabling that? It is disabled by default as we want to avoid double cursors.

**Comment by darkbasic** [comment]
@CendioOssman it looks like "Show dot when no cursor" does indeed work but only when activating it **before** connecting. I was enabling it via the F8 menu, where it has no effect at all.
Also, it there any way to change the dot to something more visible?

**Comment by darkbasic** [comment]
Ok so I'm closing this one as duplicate.
