### ISSUE TITLE
Session password cannot be entered

### ISSUE THREAD

**Issue by AymericDAT** [TigerVNC/tigervnc#1647]
**Describe the bug**
I have installed tigervnc on a Ubuntu desktop 22.04.2 LTS Linux machine. I then created a user for VNC. I can then connect first to the machine in vnc without having to enter the linux session password. However, if I logout from the session, it's impossible to enter the password, and I get the "Authentication failure" message several times.

**To Reproduce**
1. Fresh Install of Ubuntu 22.04.2 LTS Desktop (https://releases.ubuntu.com/jammy/ubuntu-22.04.2-desktop-amd64.iso)
2. force gdm display (uncomment line :  #WaylandEnable=false on /etc/gdm3/custom.conf)
3. Install  tigervnc-standalone-server (sudo apt install tigervnc-standalone-server)
4. Install dbus-x11 (sudo apt-get install dbus-x11)
5. Force localhost no in file vncserver-config-mandatory
6. Create specific user for vnc ( useradd -s /bin/bash -d /home/vncuser/ -m -G sudo testvnc)
7. Set password to specific user (sudo passwd testvnc)
8. set VNC password (su testvnc ; tigervncpasswd and exit)
9. Launch vnc session for user created (sudo tigervncsession testvnc :4)

**Expected behavior**
be able to insert the linux session password and enter the session

**Screenshots**
unable to select password field
![image](https://github.com/TigerVNC/tigervnc/assets/139887966/d9fd84cc-4fb9-43bb-b4f9-19d4385a007c)

**Client (please complete the following information):**
 - OS: Windows 11 (22H2) Build (22621.525)
 - VNC client: RealVNC Viewer
 - VNC client version: 
![image](https://github.com/TigerVNC/tigervnc/assets/139887966/7543544f-f515-4f57-b8ba-90937f7236eb)
 - Client downloaded from: Windows 
 
**Server (please complete the following information):**
 - OS: Ubuntu Desktop 22.04.2 LTS 
![image](https://github.com/TigerVNC/tigervnc/assets/139887966/a2671230-db8c-49bd-92a8-0205127286b4)
 - VNC server: TigerVNC
 - VNC server version:
![image](https://github.com/TigerVNC/tigervnc/assets/139887966/73617b51-41d2-4487-be87-4c1feb5ee798)
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: sudo tigervncsession USER :port 

**Additional context**

**Comment by huajian628** [comment]
if use xfce desktop environment    that is ok

**Comment by CendioOssman** [comment]
I'm afraid that Ubuntu has their own startup scripts for TigerVNC, so session problems are not something we can help you out with here. Please file a bug with Ubuntu, and hopefully, they can help you out.

**Comment by CendioOssman** [comment]
Oh, right. You could also try the Ubuntu packages from our release page. Those include our startup scripts instead of Ubuntu. If you are seeing an issue with our package as well, then we can have a look here.

**Comment by AymericDAT** [comment]
I've made some progress in diagnosing the problem. I don't have the problem with the first user that is created when ubuntu is installed. 
When I connect to the vnc with the user created during installation, it also connects the user created later for VNC..... I'm having trouble understanding the problem....
I've also tried with root, and I'm having the same problem as with the user created later for vnc....even stranger!

**Comment by huajian628** [comment]
关闭系统里面的锁屏就好了

**Comment by AymericDAT** [comment]
@huajian628 I think this is the best possible safety measure.

**Comment by huajian628** [comment]
ok

**Comment by Bibelo** [comment]
Impressive there's still no solution for this, as this issue been plaguing users for a 10 good years. Everyone refers the problem to someone else: Ubuntu, TigerVNC, Gnome...
