### ISSUE TITLE
F8 Menu has duplicate shortcuts ('c' = Disconnect and Ctrl)

### ISSUE THREAD

**Issue by roberestarkk** [TigerVNC/tigervnc#1650]
**Describe the bug**
The F8 Menu has the same character shortcut (hotkey/whatsit) for two separate entries. 
Disconnect and Ctrl. Both are 'mapped' to 'c'.

**To Reproduce**
1. Open a VNC Session somewhere
2. Press F8 once the remote session is active
3. Press 'c' expecting the 'Ctrl' portion to toggle
4. Experience VNC Session Disconnecting

**Expected behavior**
If there's a shortcut for an entry, pressing that shortcut should not immediately trigger a different entry.

I would suggest 'Disconnect' be remapped, since 'Ctrl' feels too 'c-ish' to be a different character.
Perhaps 'Disconnect' could be 'd' and 'Send Ctrl-Alt-Del' could be 's'
Perhaps Disconnect' could be 't' and 'About TigerVNC' could be 'v'
To retain all the existing ones as-is for backwards compatibility with muscle memory reasons, perhaps Disconnect could be 'n'
Or perhaps 'Disconnect' could be highlighted by default as the top entry, so 'Enter' would be that.
Perhaps pressing the shortcut should highlight the entry but not automatically select it, if multiple entries have the same key, and both retain 'c' as the shortcut...

I'm not sure what the best solution would be to be honest...

**Screenshots**
![](https://i.imgur.com/DnrYzaD.png)

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC Viewer
 - VNC client version: 1.13.1
 - Client downloaded from: https://sourceforge.net/projects/tigervnc/files/stable/1.13.1/

**Server (please complete the following information):**
 - OS: ArchLinux armv71
 - VNC server: kvmd-vnc
 - VNC server version: 3.238-1 (I think?)
 - Server downloaded from: https://pikvm.org/
 - Server was started using: kvmd-vnc --run (I think, it's actually running as a service)

**Additional context**
N/A

**Comment by CendioOssman** [comment]
Good catch, thanks. This was overlooked in 44b085a. It's a shame we don't have any automatic checks for conflicts here. :/

**Comment by CendioOssman** [comment]
Fixed in 8b6e43e8fc636cd94a8168a9761fe4d1ec0bd67e.
