### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by mmolaie** [TigerVNC/tigervnc#1652]
hi friends.
i'm new in tigervnc
i use tigervnc1.10 and actually have vncserver in tar archive.
no have any idea how should use 1.13 - doesn't have vncserver binary file.
could any one help to handle it.
i use tigervnc with Xfce sessions

**Comment by rajeshhazari** [comment]
Suggestions: may be this how to can be shared in readme doc, I can open pr for this is required.

**Comment by CendioOssman** [comment]
Sure. Please feel free to submit at PR with a suggestion and we can have a look.
