### ISSUE TITLE
Systemd service files do not work on Ubuntu 20. 

### ISSUE THREAD

**Issue by stayprivate** [TigerVNC/tigervnc#1653]
**Describe the bug**
Cannot start a vncsession through systemd with Ubuntu 20.   

Aug 08 17:57:31 u20 systemd[1]: vncserver@.service: Failed with result 'protocol'.
Aug 08 17:57:31 u20 systemd[1]: Failed to start Remote desktop service (VNC).

**To Reproduce**
Setup Ubuntu 20 server. Grab the install package from sourceforge at https://sourceforge.net/projects/tigervnc/files/stable/1.13.0/ubuntu-20.04LTS/amd64/

Configure /etc/tigervnc/vncservers.user and user's .vnc/config accordingly
sudo cp  /usr/lib/systemd/system/vncserver@.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable vncserver@.service
sudo systemctl start vncserver@.service
sudo systemctl status vncserver@.service

Status will show:
:  vncserver@.service: Failed with result 'protocol'.

**Expected behavior**

Successfull start 

**Screenshots**
N/A

**Client (please complete the following information):**
N/A

**Server (please complete the following information):**
Ubuntu 20 server, with xfce4 installed, but not configured to start automaticaly (head-less),

**Additional context**
In original file /usr/lib/systemd/system/vncserver@.service:
...
[Service]
Type=forking
ExecStart=/usr/lib/x86_64-linux-gnu/vncsession-start %i
...

1 - Type forking causes a systemd "protocol" error because vncsession-start does not fork at all. Changing the Type to simple gets a vncsession to start but it's not possible to stop it with systemd stop.

2 - %i should be :%i

**Comment by stayprivate** [comment]
If I installed tigervnc 1.10 from Ubunto repository there is a file called /usr/bin/tigervncserver that is mean to be called from systemd service, it does the forking systemd expect.  The work this file does, seems to have no equivalent in tigervnc 1.13

**Comment by CendioOssman** [comment]
This is a parameterised service, which means it needs to be started with an argument indicating which display to start for. E.g.

```console
$ sudo systemctl start vncserver@:2.service
```

I'm a bit surprised systemd didn't show a clear error message, given that the service has the `@` marker in it.
