### ISSUE TITLE
Incorrect VNC protocol implementation for PixelFormatChange ( -258 / fffffefe )

### ISSUE THREAD

**Issue by jollyjinx** [TigerVNC/tigervnc#1656]
**Describe the bug**
TigerVNC sends a PixelFormatChange without the PixelFormat.

**To Reproduce**
1. Start TigerVNCServer
2. Connect with a client that supports PixelFormatChange (e.g. JollysFastVNC)
3. When the server sends then a PixelFormatChange ( for example when the client request a different PixelLayout on connection ) without any Format just the Rectangle that there is a PixelFormatChange is sent.

**Expected behavior**
VNC Protocol should be adhered.
A pixelformat change requires to include the pixelformat.

**Client (please complete the following information):**
 - OS: macOS
 - VNC client: JollysFastVNC 
 - VNC client version: 1.64
 - Client downloaded from: www.jinx.de/JollysFastVNC.html

**Server (please complete the following information):**
 - OS: RH Linux 4.18.0-477.15.1.el8_8.x86_64  SMP Wed Jun 28 15:04:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - VNC server: TigerVNC 
 - VNC server version: 1.12
 - Server downloaded from: Linux distribution
 - Server was started using: systemctl enable vncserver@\:1

**Comment by CendioOssman** [comment]
I'm afraid -258 is already registered for the QEMU keyboard extension. So it unfortunately looks like it is JollysFastVNC that isn't following the official protocol.

I can't really find anything if I search for a VNC pixel format change extension. Is this something specific to JollysFastVNC?

**Comment by jollyjinx** [comment]
It's not something specific to jfvnc. It's described in the rfc https://datatracker.ietf.org/doc/html/rfc6143 section 7.5.1

**Comment by CendioOssman** [comment]
That section describes a client to server message, not an encoding. And there is no response from the server for that message. In fact, the value 258 or fffffefe don't appear anywhere in the base VNC specification. So I'm afraid I don't see the connection to what jfvnc expects.

**Comment by jollyjinx** [comment]
You are right I don't find the reference to -258 in there directly only the specification on the pixelformat change. I wonder which server or document added that back in 2007 which is how long that encoding is supported by JFVNC as it was needed back then when the Server switched it's screen resolution and depth.

You wrote "258 is already registered for the QEMU keyboard...." how can it be registered if it's not in RFC ?

**Comment by CendioOssman** [comment]
The RFC establishes a new registry with IANA where such things can be registered:

https://www.iana.org/assignments/rfb/rfb.xml

-258 is in the range registered by Anthony Liguori for the QEMU project.

In general, I would recommend looking at the community version of the VNC protocol here, as RealVNC isn't really concerned with an open VNC protocol any more:

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst

As for the matter at hand, if you can't recall which server you added this for, then I would suggest just removing it. There are multiple major clients supporting the QEMU keyboard extension, and we haven't encountered any server where this is a problem. So it must be something very obscure.
