### ISSUE TITLE
Change hardcoded config paths to use $HOME.

### ISSUE THREAD

**Issue by rokejulianlockhart** [TigerVNC/tigervnc#1657]
**Is your feature request related to a problem? Please describe.**

When the path of the user's home directory changes, this isn't updated in TigerVNC, because the path is hardcoded.

![image](https://github.com/TigerVNC/tigervnc/assets/42837531/85b22d8d-278e-4cb8-bb03-556d5a271248)

**Describe the solution you'd like**

Use the `$HOME` environment variable.

![image](https://github.com/TigerVNC/tigervnc/assets/42837531/bdd033ed-c5c5-45d6-b677-14452158632c)

**Describe alternatives you've considered**

What occurs currently could be considered an alternative, but any real alternative would involve needlessly re-engineering exactly this solution.

**Additional context**

This is only relevant to the default configuration. I don't instead mean that the scope of the path input forms should be changed to `$HOME` instead of `/`.

**Comment by CendioOssman** [comment]
That's true that it won't follow a change in a user's home directory path. But that should be something that is exceedingly rare.

What was the situation in your case that caused user home directories to move?

**Comment by rokejulianlockhart** [comment]
> What was the situation in your case that caused user home directories to move?

Nothing yet, @CendioOssman. I'm going to experiment with such things in future though, and this seemed like a change with no downsides.

**Comment by CendioOssman** [comment]
The big downside is that there needs to be a lot more complexity. Either we need a parser for some special syntax (e.g. `~`), or it needs some way of detecting a change in the home directory and adjust the settings appropriately.

So I'm a bit sceptical that this is worth fixing. I don't think this is a scenario that will happen very commonly for users.

**Comment by rokejulianlockhart** [comment]
@CendioOssman, I'm not sure what you mean. Environment variables aren't `bash`-specific syntax like `~` is. Perhaps because I'm primarily a .NET Core developer, I'm used to passing paths through the current shell (`chsh`) but surely env vars should be expanded by the system anyway?

**Comment by CendioOssman** [comment]
I'm afraid the `$` notation is also a shell specific syntax. I'm not aware of any software outside of shells that supports it. So it would be very non-standard to use it in TigerVNC.

So no, unfortunately, expansion of environment variables is not something that is applied generally by the system.

**Comment by rokejulianlockhart** [comment]
I'd still like this ability, think that following https://github.com/TigerVNC/tigervnc/issues/1657#issuecomment-1691606399 is probably the best idea, but I understand if you want to close this as unplanned.
