### ISSUE TITLE
'Send Clipboard to Server' toggle for F8 Menu

### ISSUE THREAD

**Issue by roberestarkk** [TigerVNC/tigervnc#1660]
**Is your feature request related to a problem? Please describe.**
Ideally this setting should be enabled all the time and the clipboard of client and server unobtrusively kept in sync, but for whatever reason when it's enabled, I get periodic pastes of the most recently copied text seemingly without any prompting or activation on my part (once immediately on re-focus after copying, and again every so often but I'm yet to spot a pattern with it due to leaving it mostly disabled).

**Describe the solution you'd like**
I would love to see an option in the F8 menu to quickly toggle this setting, like with Ctrl and Alt.

**Describe alternatives you've considered**
Leaving it disabled and going into F8 -> Options -> Input -> Toggle setting, does work, but is not very flowy.
I've also tried googling the problem but haven't really found any evidence that it happens to people other than me, with the keywords I've used anyway.

**Additional context**
I freely admit it might very well be a problem with my PiKVM and not TigerVNC, which I am looking into in the meantime.
However, if I use 'TurboVNC' with those same two clipboard settings enabled, it doesn't periodically paste the most recent clipboard content into the server, nor does it appear to have any impact on the server's clipboard, it instead provides a little 'Clipboard manager' window via F8, which keeps synced with the client clipboard and lets me manually trigger a send for one of them to the server. 

Which leads me to think it might either be a weird combination of my clipboard manager (ditto) and whatever mechanism TigerVNC is using to try to keep the clipboards synced in the background (though I've tested with ditto disabled and it still at the very least does the 'send paste to server on client copy'), or it's just a fact of life for how VNC works and mostly people just work around it.

**Comment by CendioOssman** [comment]
Cluttering up the context menu to work around a bug seems a bit excessive to me, so let's instead try to get to the bottom of the bug and get that resolved.

Could you open a new issue for the bug with as much detail as possible?

**Comment by roberestarkk** [comment]
Agreed! 
But I figured I'd tackle the 'If it's not a bug and that's actually how it works, how can I have a smoother workflow' scenario first, just in case.
I'll raise a bug report shortly!

**Comment by roberestarkk** [comment]
#1661
