### ISSUE TITLE
'Send Clipboard to Server' seems to be typing the client's clipboard into the server without being prompted

### ISSUE THREAD

**Issue by roberestarkk** [TigerVNC/tigervnc#1661]
**Describe the bug**
When 'Send clipboard to server' is checked, I find myself occasionally experiencing a 'paste' when I am not expecting one.
This most predictably and repeatably happens as soon as focus is regained in the VNCViewer window, after I've added something to the Client's clipboard, but I do believe it may have also happened while I've been actively using the VNCViewer _after_ having populated the client's clipboard.

**To Reproduce**
Steps to reproduce the behavior, for me at least:
1. Connect TigerVNCViewer to a PiKVM VNC session
2. Enable the two 'Clipboard' settings
3. Have your cursor somewhere that accepts text in the server session
4. Copy something to your clipboard in the client session
5. Re-focus the VNCViewer
6. Observe as the newly added text on your client clipboard is immediately typed into the server (sometimes incompletely, eg: `Issue: Bug report` became `Issug report` once, and if the clipped text is sufficiently long, it might stop printing unless/until you start 'activating' the window, at which point it'll print the rest and eventually catch up to you)

**Expected behavior**
I would (perhaps naively) expect the clipboard of my server machine to seamlessly sync with the clipboard of my client machine in the background without causing the clipped text to appear in my active window in the server view.

**Screenshots**
[Simple Example (unmute for Commentary)](https://imgur.com/diRVqu7)
[Longer Example (unmute for Commentary](https://imgur.com/FAyBVec)

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNCViewer
 - VNC client version: 1.13.1
 - Client downloaded from: Sourceforge I think?

**Server (please complete the following information):**
 - OS: ArchLinux armv71 (PiKVM providing indirect access to Windows 11)
 - VNC server: kvmd-vnc
 - VNC server version: 3.238-1 (I think?)
 - Server downloaded from: https://pikvm.org/
 - Server was started using: kvmd-vnc --run (I think, it's actually running as a service)

**Additional context**
I also don't see the clipboard being shared back the other direction either, and I am using '[Ditto](https://ditto-cp.sourceforge.io/)' to manage my clipboard history.
I have tested while Ditto was disconnected from the clipboard (on both Client and Server), but it still at the very least does the 'On Focus, paste' part.
I also tested leaving the setting enabled for an hour while I was afk focused on the Server with 'Get-date' copied and a Terminal window open, but it didn't auto-paste, so I suspect it is *something* I'm doing that triggers it in the not-regaining-focus context, but I'm not sure what.

I've also noticed that the server will occasionally replicate the heck out of my keypresses, so `accustomed` will just repeat the 'd' into `accustomedddddddddddddddddddddddddd` and I'll need to go back and sort it, but I assume that's a network thing and it's tolerably infrequent, so I mention it only in case it might be relevant as an accidental shortcut trigger perhaps.

I also freely admit it might be something to do with the PiKVM sitting in the middle. Transitioning from Windows 10 Clipboard to Linux Clipboard and back to Win11 again via VNC and KVM related shenanigans, is a level of complexity ripe for weird edge cases, but I googled around for PiKVM (and linux/vnc) pasting related issues and found nothing similar.

I also tested with TurboVNC Viewer to try to isolate where the fault is, and it didn't auto-paste on re-focus, and instead provided me with a pop-up Clipboard Manager built into the viewer. It did keep in sync with my client's clipboard, but it would only interact with the server if I hit the 'Send Paste' via the manager, via the F8 menu for TurboVNC. Which is one of the reasons I am not sure if it's realistic to expect a VNCViewer to seamlessly sync the clipboard of client and server invisibly in the background.

**Comment by CendioOssman** [comment]
Unfortunately, this sounds like a PiKVM bug. It sounds like it immediately dumps the clipboard as fake keyboard presses as soon as it gets it. Which is not how it is supposed to work. It is supposed to keep that clipboard and wait for the user to request it.

I'm afraid you'll need to report the issue to them. I'm surprised that this is not something they've noticed before. AFAIK, most VNC clients will automatically sync the clipboard. Perhaps there is some setting that has changed in your PiKVM setup?

> I also don't see the clipboard being shared back the other direction either, and I am using '[Ditto](https://ditto-cp.sourceforge.io/)' to manage my clipboard history.

I don't think PiKVM has real clipboard synchronisation, given that it is a hardware solution. It seems to fake keyboard input instead of actually sending the clipboard to the machine. So it has no access to the machine's clipboard to send back to the VNC client.

> I've also noticed that the server will occasionally replicate the heck out of my keypresses, so `accustomed` will just repeat the 'd' into `accustomedddddddddddddddddddddddddd` and I'll need to go back and sort it, but I assume that's a network thing and it's tolerably infrequent, so I mention it only in case it might be relevant as an accidental shortcut trigger perhaps.

Yes, that is common when accessing a full host and is often seen in VMs. What you need to do is disable keyboard autorepeat in the remote systems and let the client handle it. However, this means you lose the ability for applications to notice you are keeping a key pressed down, rather than pressing it repeatedly.

**Comment by mdevaev** [comment]
I got my hands on it. Alas, there is no technical way to fix this, this is a limitation of the fact that we don't have access to the clipboard.
