### ISSUE TITLE
systemd started session can need more dependencies

### ISSUE THREAD

**Issue by dad4x** [TigerVNC/tigervnc#1666]
When a systemd launched vncserver is created for a user, it assumes that the things needed have been made available and mounted.   With environment having automounting, the /home/user isn't present until something goes there, and some places using ldap or nis may not have a password file given the After dependencies present.

**Describe the solution you'd like**
Possibly the  /usr/lib/systemd/system/vncserver@\.service  should have an After dependency that makes sure the getent call works and the home is mounted.

**Describe alternatives you've considered**

1.   A manual hack that a user crafts to pull dependencies in with a manual addition to the vncserver@.service configuration.

2  A documented version of (2).

3.  If no passwd entry in vncsession-restore, trying /home/${USER}?

**Additional context**

Example from boot:
 vncserver@:7.service - Remote desktop service (VNC)
   Loaded: loaded (/usr/lib/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2023-09-04 17:44:05 PDT; 1min 29s ago
  Process: 1731 ExecStartPre=/usr/libexec/vncsession-restore :7 (code=exited, status=1/FAILURE)

Sep 04 17:44:05 phoenix92608 systemd[1]: Starting Remote desktop service (VNC)...
Sep 04 17:44:05 phoenix92608 vncsession-restore[1731]: Failed to get home directory for dbrower

>>>>> This indicates that `getent passwd ${USER} | cut -f6 -d:` in vncsession-restore didn't deliver.

Sep 04 17:44:05 phoenix92608 systemd[1]: vncserver@:7.service: Control process exited, code=exited status=1
Sep 04 17:44:05 phoenix92608 systemd[1]: vncserver@:7.service: Failed with result 'exit-code'.
Sep 04 17:44:05 phoenix92608 systemd[1]: Failed to start Remote desktop service (VNC).
bash-4.4# systemctl start   vncserver@:7

Subsequent manual start succeeds.

**Comment by CendioOssman** [comment]
This has already been fixed in TigerVNC 1.13.0 and later. So please update your TigerVNC and it should work fine.
