### ISSUE TITLE
Cannot connect to tigervnc in windows version using "guacamole" as client

### ISSUE THREAD

**Issue by liuyuhao520** [TigerVNC/tigervnc#1667]
**Describe the bug**
Cannot connect to tigervnc in windows version using "guacamole" as client

**To Reproduce**
1. Download the Windows 32-bit version of tigervnc version number is :1.13.1 and install successfully
2. guacad is installed on another linux server, and windows for tigervnc is installed via guacad connection using guaca-lient as the client. The guacamole version used is 1.4.0
3. When you install guacad, make sure that you downloaded the vnc dependency package, and guacad checks that vnc is supported
5. Then look at the guacad error log, as shown below,The screenshot shows.
![image](https://github.com/TigerVNC/tigervnc/assets/31134628/4fc25974-8c75-4bd8-a69e-9d99e334a7a9)
6. The following screenshot shows the tigervnc server configuration
![image](https://github.com/TigerVNC/tigervnc/assets/31134628/cababc97-7d07-471b-9294-1b8360cc2655)
7. But I was able to connect to tigervnc normally through the "MobaXterm" client

**Client (please complete the following information):**
 - OS: [linux]
 - VNC client: [guacamole]
 - VNC client version: [1.4.0]

**Server (please complete the following information):**
 - OS: [e.g. Windows7]
 - VNC server: [TigerVNC]
 - VNC server version: [1.13.1]

**Comment by CendioOssman** [comment]
I'm afraid it looks like an incompatibility in Guacamole that they'll have to fix. They don't seem to be prepared for standard authentication types when using VeNCrypt. This was discussed in the VNC community, and we ended up with the decision that those need to be supported to handle all scenarios properly. So Guacamole needs to make sure they follow that behaviour.

As there isn't anything we can do about this in our end, I'm afraid I'll go ahead and close this issue.
