### ISSUE TITLE
Can This VNC Run on a Android Device

### ISSUE THREAD

**Issue by srctar** [TigerVNC/tigervnc#1668]
I hava an android 11 (Xiaomi 11 Utral, with snapdragon 888 cpu, armv8)

now I want to make it to be a linux server, a suit vnc server may help me match。

it is root, and with nessery linux runtime.

can tigerVNC run on a android device?

if not, what should I do to make tigerVNC run on my device?

I dont need GUI on it`s screen。

**Comment by CendioOssman** [comment]
No, I'm afraid we don't have any server designed to run on Android. You might be able to force Xvnc to run if you can get all the necessary libs in place. But I'm not certain how helpful that would be as it would only support X11 applications, not Android applications.
