### ISSUE TITLE
[website] Consider changing the donation system

### ISSUE THREAD

**Issue by macias** [TigerVNC/tigervnc#1669]
Some time ago I reported donation website was down: https://github.com/TigerVNC/tigervnc/issues/1548

This year it is down for another reason:

```
Secure Connection Failed

An error occurred during a connection to app.bountysource.com. SSL peer has no certificate for the requested DNS name.

Error code: SSL_ERROR_UNRECOGNIZED_NAME_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

However particular reason is not that important. If the donation website is so brittle that is problem after problem, well, then it **is** a problem, a not a solution. So maybe change the donation system?

**Comment by CendioOssman** [comment]
I agree, Bountysource has been very flakey. Not just in this, but in all details.

Unfortunately, I can't find any alternatives. So the question is then if we want a buggy bounty system, or none at all. :/

**Comment by CendioOssman** [comment]
Bountysource seems to be completely dead. Wikipedia states they've filed for bankruptcy, and haven't paid out any bounties in a year. So it looks like we need to do a clean-up of tagged issues.

As for alternatives, are there any?

**Comment by CendioOssman** [comment]
I've removed the bounty section from the home page, and removed the issue label. There is also a note at the bottom of all issues, but that will have to be manually removed.
