### ISSUE TITLE
Segmentation fault at address 0x10

### ISSUE THREAD

**Issue by mperov** [TigerVNC/tigervnc#1673]
**Describe the bug**
VNC session is crashed.

**To Reproduce**
Steps are unknown. User worked with remote server and session was killed.

**Expected behavior**
VNC server should 

**Client (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - VNC client: VNC Viewer
 - VNC client version: 6.22.826 (r47988) x64 (Sep 15 2022 19:08:34)
 - Client downloaded from: https://www.realvnc.com/en/connect/download/viewer/

**Server (please complete the following information):**
 - OS: CentOS 7.9
 - VNC server: tigerVNC
 - VNC server version: 1.10.0
 - Server downloaded from: https://github.com/TigerVNC/tigervnc/releases
 - Server was started using: vncserver

**Additional context**
I have attached VNC server log file, bu short crash dump here:
```console
(EE)
(EE) Segmentation fault at address 0x10
(EE)
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE)
```

**Comment by CendioOssman** [comment]
I'm afraid that is a rather old version of TigerVNC, so it's not really something we want to start a big debugging investigation for.

Please upgrade to the latest version of TigerVNC. If the user is still seeing crashes, then we can investigate further.
