### ISSUE TITLE
Resolution stuck at 1280x800 on macbook pro 13" TigerVNC Viewer 1.13.1

### ISSUE THREAD

**Issue by bucovaina** [TigerVNC/tigervnc#1675]
**Describe the bug**
I'm running TigerVNC Server 1.12.0 on a Debian 12 Bookworm server. I connect to it with a Debian Client without problems. When I try to connect with TigerVNC Viewer 1.13.1 to it with a macOS Monterey 12.6.3 the resolution is stuck at 1280x800 at full screen. When I try to set the resolution higher in Mate-settings (desktop environment), I get scroll bars to scroll through the desktop. If I resize the TigerVNC viewer window on the macos client, it seems to pick it up and lowers the resolution automatically to whatever the window size. It seems to me the client on macos is scaling down somehow. 

**To Reproduce**
1. I SSH to the server and start the sever as follows: tigervncserver -xstartup /usr/bin/mate-session -geometry 2560x1600 -localhost no &  ##
2. Connect with TigerVNC Viewer 1.13.1 from a macOS and verify the resolution is not at the highest possible but the window itself is full screen
3. Connect to the same session but from my Debian host and notice the macos session gets closed automatically and notice that on my debian laptop the resolution is perfectly fine (2560x1600)
4. To double check retry on the macbook and the resolution is back at 1280x800. Same session

**Expected behavior**

**Client (please complete the following information):**
 - macOS Monterey 12.6.3: from this client I see the problem
 - Debian Bookworm up-to-date: from this client no complaints, the resolution matches the screen. Both clients btw are MacBook Pro A1502 machines. One has macOS installed (which shows the problem) and one macbook, I wiped and reinstalled with Debian 12.0. This one does not show the problem and works perfectly as expected. So same server, same session, same client hardware only different client software (well, one for Macos and one for Debian)

**Server (please complete the following information):**
 - OS: Debian bookworm (up to date)
 - VNC server: TigerVnc Server 1.12.0
 - Server downloaded from: apt repositories
 - Server was started using: see code above

**Comment by bucovaina** [comment]
Additional info, I wanted to try 1.12.0 on the macOS client to have the exact same version on the server and the client. No luck there but there's something else that caught my eye, the "VNC Viewer: Connection Details" dialog box to set up the connection also looks "blurred". The same way the VNC session looks.

See image attached. This is a screen shot from the macOS client while trying 1.12.0
<img width="490" alt="screenshot" src="https://github.com/TigerVNC/tigervnc/assets/42909233/bb4cd4fe-e3cd-4acd-9ed8-aaf02bb0deec">

**Comment by bucovaina** [comment]
I found and edited the Info.plist file but not much better. Screen resolution is fine now but the workable area in the VNC viewer is not right. Picture says more than a thousand words. The mouse only seems to work if I keep it in the upper left corner of the window in the dark gray area. Then I can click and activate the menu (which shows on the bottom half of the screen far under the mouse cursor). I cannot click on lower parts of the screen though.
<img width="1392" alt="screenshot2" src="https://github.com/TigerVNC/tigervnc/assets/42909233/f82da853-a302-46ef-a112-feb0eb31cf0d">

**Comment by bucovaina** [comment]
And I think this issue is closely related at issue  #369. Maybe not exactly the same because I don't have this on Linux, but do have it on 1.12.0 and 1.13.1 on the macOS client.

Meanwhile I tried the RealVNC client and that one seems to work as expected. It would be nice though if I could use TigerVNC both for client and the server.

**Comment by CendioOssman** [comment]
Yes, this is partly #369. But it seems you also want HiDPI support in the VNC session, which we don't currently have a tracker bug for. That is much more difficult, given the state of HiDPI support in Linux at the moment.

I'll still close this as a duplicate, though, as we already have the HiDPI discussion on the other bug.
