### ISSUE TITLE
Change path of .vnc directory 

### ISSUE THREAD

**Issue by puneet336** [TigerVNC/tigervnc#1677]
Hi,
We are in process of preparing a new set of CentOS 7 servers with updated patches, and we are upgrading tiger vnc as well.
 tigervnc-server-1.8.0-25.el7_9.x86_64 will be replaced with tigervnc-server-1.13.1-1.el7.x86_64
 
 Issue is that we have a NFS $HOME directory, which means that each user on our systems have common $HOME/.vnc directory . This makes the migration difficult as we plan to use the same NFS and and we do not want to impact the existing/running VNC sessions.  
 
 Is it possible to make the tigervnc1.13 to use a separate config directory like - $HOME/localvnc/.vnc so that running sessions do not get any impact?
 If the  1.13 binaries do not have that option then   I can attempt to build the tigervnc rpm by tweaking the source code to change .vnc to .vnc113 using instructions mentioned at 
 https://github.com/TigerVNC/tigervnc/blob/master/BUILDING.txt
 
But changing .vnc to .vnc113 in the following files will be enough ?
```
 ./common/os/os.cxx:  snprintf(dir, sizeof(dir), "%s/.vnc", homedir);
./vncviewer/vncviewer.cxx:  // Create .vnc in the user's home directory if it doesn't already exist
./java/com/tigervnc/vncviewer/FileUtils.java:    return getHomeDir()+".vnc"+getFileSeparator();
./unix/vncserver/vncsession.c:    snprintf(logfile, sizeof(logfile), "%s/.vnc", homedir);
./unix/vncserver/vncsession.c:    snprintf(logfile, sizeof(logfile), "%s/.vnc/%s%s.log",
./unix/vncserver/vncserver.in:$vncUserDir = "$ENV{HOME}/.vnc";
```

 
 Please advice.

**Comment by CendioOssman** [comment]
Changing the path is not configurable, no. We do give unique file names to some files to avoid this specific problem, though.

Those files look like a good start if you want to make your own custom version. It's not something we keep a close track on, as it wasn't really meant to be changed.
