### ISSUE TITLE
TigerVNC black screen on RockyLinux9

### ISSUE THREAD

**Issue by yaoqianhao** [TigerVNC/tigervnc#1678]
I am using RockyLinux as OS for my development. For peer works, I’d like to use tigervnc to login in the system.

      When I use  the command “systemctl start vncserver@:2” to  start a vncserver on the port 5902.

      I have made it access to the port 5902 through the firewall.

      I have edited the config file "/etc/systemd/system/vncserver@\:2.service"

 
![image](https://github.com/TigerVNC/tigervnc/assets/29427550/6dc36a73-3432-4a2a-86f1-a31fdf39e4da)

      The server could not be created.

      The log content is that:

    
![image](https://github.com/TigerVNC/tigervnc/assets/29427550/7d6d31f7-255f-4bcc-80aa-b2dd89404d8c)

     

 And also, I tried to use the command “vncserver :2” to create a vncserver. The client can connect to the server. But there is a black screen and could not do anything to the server.

      The config file ~/.vnc/xstartup is like that.

      
![image](https://github.com/TigerVNC/tigervnc/assets/29427550/16025bbe-3b8c-44bd-9c2d-33ba1c226fe9)

      Here is the snapshot of the screen.

    
![image](https://github.com/TigerVNC/tigervnc/assets/29427550/0621ea00-6dfc-49d4-817f-3bab45e1560f)

 

 

 

     But when I use “sudo vncsever :2” to create vncserver , I can use vnc viewer to login in as the root account, and the GUI could be work.       

 

     My RockyLinux version is 9.2,and my tigerVNC version is 1.12.0.

**Client (please complete the following information):**
 - OS: Window 10
 - VNC client: VNC Viewer
 - VNC client version: 6.21
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: RockyLinux 9
 - VNC server: TigerVNC
 - VNC server version: 1.12.0.
 - Server downloaded from:use “yum” to install
 - Server was started using: vncserver

**Additional context**

**Comment by CendioOssman** [comment]
I see you've also written to the tigervnc-users discussion group. Let's avoid duplicate discussions, so I'll go ahead and close this entry here and the discussion can continue in the group.
