### ISSUE TITLE
x0vncserver on nvidia

### ISSUE THREAD

**Issue by axet** [TigerVNC/tigervnc#1680]
**Describe the bug**

x0vncserver -SecurityTypes None -localhost :0

works differently on amd and nvidia (nouveau) video cards. When started on AMD video card it only showing :0.0 display. When started on nvidia GPU it showing booth :0.0 and :0.1 workspaces.

Is here an option to prevent that? Bug? Feature?

**To Reproduce**

1. x0vncserver -SecurityTypes None -localhost :0
2. connect using remmina

repeat with amd / nvidia card

**Screenshots**

![Screenshot from 2023-10-04 12-50-44](https://github.com/TigerVNC/tigervnc/assets/298672/8eb7980b-1f1d-4a49-8940-dd3e1ac87139)

**Client/server**

 - OS: Debian 12 (bookworm booth machines)
 - TigerVNC Server version 1.12.0, built 2023-01-06 16:01
 - VNC client:  remmina                                       1.4.29+dfsg-1

**Comment by CendioOssman** [comment]
`x0vncserver` can only connect to a single screen at a time, so it cannot show two completely independent screens. It is more likely that your system is configured with a single screen with multiple monitors. It sounds like the AMD setup is configured in Zaphod mode, but the nvidia setup is not.

If you wish to only show part of the screen, then you can use the `-geometry` setting for `x0vncserver`. The default behaviour is to show everything.

**Comment by CendioOssman** [comment]
It has managed to find something there to send over to the client. What does `xrandr` say when run on those two machines?

**Comment by axet** [comment]
nvidia https://paste.debian.net/1293994/

amd https://paste.debian.net/1293995/

**Comment by CendioOssman** [comment]
Unfortunately, those logs show exactly what `x0vncserver` is showing you, that there are indeed two monitors connected.

However, it is showing that both monitors are "LVDS", which usually means the built-in monitor. Perhaps this is a optimus system where it's showing two GPUs connected to the laptops monitor?

**Comment by axet** [comment]
NVidia laptop is Apple Macbook Pro 6,2.

Thanks for helping figuring it out. I guess I should disable it somehow, since this internal LVDS monitor it is not physically available.
