### ISSUE TITLE
x0vncserver pipe mode

### ISSUE THREAD

**Issue by axet** [TigerVNC/tigervnc#1681]
**Is your feature request related to a problem? Please describe.**

Here a few ways to connect to vncserver using tcp port / unixsocket. Booth ways depend on default authontication protocol. But here one option is missing for more secure simple setup connection: using pipe.

**Describe the solution you'd like**
start vnc server without port / localhost / unixpath / security by typing: 'x0vncserver -'

Connect to vncserver using: ssh host 'x0vncserver -'

Which has benefits: no locahost port, which open to all localhost users, no security protocol authentication weaknesses.

**Describe alternatives you've considered**

```bash
x0vncserver -rfbport 0 -rfbunixpath $HOME/vnc :0
socat - UNIX-CONNECT:$HOME/vnc
x0vncserver --kill
```

**Comment by CendioOssman** [comment]
A unix socket is not available for all other users unless you want it to. The defaults only allow access to the user that started the server.

Do you have a use case where that is insufficient?

**Comment by CendioOssman** [comment]
The extra commands would only be needed if you need the client to use pipes. Why can't you let the client use the unix socket directly?

**Comment by axet** [comment]
Not sure I understand you. You have to run additional commands to make unix socket available remotely. The only one benefit having pipe would be give you more flexibility then having unix socket.

However using socat installed you can convert anything to anything. Like having pipe (system command) available via unix socket / tcp / udp / additional connection encryption (https / ssl) / password, etc..

Maybe one disadvantage here having unix socket would be requirement running vncserver in background, and socat in foreground and then killing vncserver. Not much flexibility here.

**Comment by axet** [comment]
I guess having pipe option would make 'socat' call even shorter:

`socat -d tcp-l:80,reuseaddr,keepalive,fork system:"x0vncserver - :0"`

That would conclude, pipe feature better than unix socket, since it makes all calls shorter with or wihout socat.

**Comment by CendioOssman** [comment]
I'm afraid I'm still not seeing what problem is being solved here. We already support TCP, so we don't need a detour via socat for that. And if you want to use a Unix socket but still expose that remotely, then ssh supports that.

I'm closing this for now until we have something more tangible that we cannot achieve with the current mechanisms.
