### ISSUE TITLE
Scaling options: 100%, 200%, fullscreen with scaling

### ISSUE THREAD

**Issue by hubertmeier** [TigerVNC/tigervnc#1684]
tigervnc is now recommended for the raspian bookworm VNC connection ... but it has its issues. On a 4k screen which is normally scaled to 150% on windows, the VNC is windows is scaled too to 150%, which results in unsharp pictures. Another option does not exist. 100% would be sharp, but not readable, 200% would be ideal, or perfect if it would resize the screen with the windows, just to fullscreen with 200% on a 4k screen.

I used the last stable vncviewer64-1.13.1.

Thank you

**Comment by CendioOssman** [comment]
Please see #274 for the discussion on adding client side scaling support to TigerVNC.
