### ISSUE TITLE
Make Option (F8) available too at the window title bar

### ISSUE THREAD

**Issue by hubertmeier** [TigerVNC/tigervnc#1685]
I had a bit to search how to access the option, i found "F8" in the docs. Is it possible to see an option menu in the title bar, perhaps a submenu or a call of the option-windows, perhaps direct commands like "fullscreen" and "restore windowsize to server resolution"

Thank you

**Comment by CendioOssman** [comment]
I'm afraid I don't think that is possible, at least not on all of our platforms.

The client is supposed to inform you about the F8 button every time you connect. Does that message pop up for you?

**Comment by CendioOssman** [comment]
No response. Closing.
