### ISSUE TITLE
Remember credentials when reconnecting

### ISSUE THREAD

**Issue by JohnFarl** [TigerVNC/tigervnc#1688]
Often the VNC connection is lost and it is really annoying to confirm reconnection and log in again every time this happens. 
It should be added a configurable option that allows you to configure automatically reconnection on lost connection and relative max connection attempts.

**Comment by CendioOssman** [comment]
As you say, you will likely need to log in again as part of the reconnect. So triggering it automatically might not be a good idea, as the user might not be present or notice the reconnect, so they can enter the login details before the connection times out.

**Comment by CendioOssman** [comment]
I'm afraid it's up to the operating system to decide when to give up on a TCP connection, so it's not something we can control from TigerVNC. At least not making it *less* sensitive. :/

Just to make sure we are talking about the same thing; you are saying that not having to press "yes" on the reconnect dialog, even if you still have to specify the login details again, is a substantial improvement for you?

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by JohnFarl** [comment]
Sorry. I have missed your reply. I'm talking about storing session credentials, so that in case connection is lost when you see something as "connection lost, try to reconnect?"... on confirm, without need to re-type username and password on every re-connection attempt, if connection is available, you are connected again. Having to press "yes" on the reconnect dialog is not a problem, be forced to re-input the credentials every time in case of shaky connection is the deal breaker.

**Comment by CendioOssman** [comment]
Good news, this has been implemented now: 633e75b5263cbde04a16a0f2c04165807db1bd91
