### ISSUE TITLE
OpenGL applications draw with semi-transparent background

### ISSUE THREAD

**Issue by pberto** [TigerVNC/tigervnc#1689]
**Describe the bug**

OpenGL applications draw with semi-transparent background

**To Reproduce**

- fresh debian system with kde, tigervnc, nvidia drivers and mesa-utils
- connect over ssh to the host, start `vncserver`, then run vncviewer on the client and connect to the host 
- open a terminal and run glxgears and produce screenshot below

**Expected behavior**
the background should not be transparent.
this extends to any opengl application btw.

**Screenshots**

![image](https://github.com/TigerVNC/tigervnc/assets/254052/7fa50405-abf5-40b2-8add-ee42c48bf72e)

**Client (please complete the following information):**
 - OS: macOS
 - VNC client: realvnc
 - VNC client version: 7.5.1
 - Client downloaded from: realvnc website

**Server (please complete the following information):**
 - OS: debian 12
 - VNC server: TigerVNC's `vncserver`
  - VNC server version: 1.12.0
 - Server downloaded from: my Linux distribution
 - Server was started using: `vncserver`

**Comment by CendioOssman** [comment]
Well that's a new one.

It looks a bit too neat and clean to be a bug. Are you sure this isn't some effect from the compositor?

Still, it unfortunately cannot be a bug in TigerVNC as we are not involved in the rendering. We just transfer what's rendered. So the issue should be in either Xorg or mesa.

Could you try using our generic build? You can find it via our release page.

**Comment by pberto** [comment]
I confirm it has nothing to do with TigerVNC version, it happens with another version and also with other VNC or even with no machine. So it has to be the compositor I just don't know how to get this fixed.

**Comment by CendioOssman** [comment]
Thanks for digging further. Unfortunately, it is a bit outside our expertise at this point. I would suggest reporting the issue to Debian, or the desktop environment/window manager that you are using. They should hopefully be able to get to the bottom of this.

**Comment by dholstei** [comment]
I have exactly the same issue!
![gears](https://github.com/TigerVNC/tigervnc/assets/60890386/6a614378-3826-46f7-abdd-eec37b4d0745)
The clients (_all using Mesa OpenGL_) and the server are the same machine, namely a CentOS8 Hyper-V guest on Windows 10

**Comment by dholstei** [comment]
Additional info:
```shell
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa (0xffffffff)
    Device: llvmpipe (LLVM 16.0.6, 256 bits) (0xffffffff)
    Version: 23.1.4
    Accelerated: no
    Video memory: 15758MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.0
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 11008 MB, largest block: 11008 MB
    VBO free aux. memory - total: 10931 MB, largest block: 10931 MB
    Texture free memory - total: 11008 MB, largest block: 11008 MB
    Texture free aux. memory - total: 10931 MB, largest block: 10931 MB
    Renderbuffer free memory - total: 11008 MB, largest block: 11008 MB
    Renderbuffer free aux. memory - total: 10931 MB, largest block: 10931 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8128 MB
    Total available memory: 23886 MB
    Currently available dedicated video memory: 11008 MB
OpenGL vendor string: Mesa
OpenGL renderer string: llvmpipe (LLVM 16.0.6, 256 bits)
OpenGL version string: 3.0 Mesa 23.1.4
OpenGL shading language version string: 4.50
```
