### ISSUE TITLE
TigerVNC Viewer for Windows: improve saving/loading/using profiles

### ISSUE THREAD

**Issue by bits01** [TigerVNC/tigervnc#169]
TigerVNC Viewer for Windows: please add a way to save a full profile, all settings, including host to connect to. Also associate a .tigervnc extension or similar to the viewer on Windows so that one can easily double click on a saved profile and start a connection to the server using the saved profile.

It seems saving/loading profiles is very weak/buggy on Windows.

**Comment by CendioOssman** [comment]
Associating .tigervnc files is issue #38.

**Comment by CendioOssman** [comment]
And profiles ins #153.
