### ISSUE TITLE
vncviewer: invert colors to switch from lightmode to darkmode

### ISSUE THREAD

**Issue by milahu** [TigerVNC/tigervnc#1697]
it would be nice if i could call `vncviewer -InvertColor`
to invert colors from daymode to nightmode

http://ssb22.user.srcf.net/setup/vnc-invert.html

> People with certain eyesight conditions find bright backgrounds difficult to work with, but some applications cannot be configured otherwise. ​If you have to use one of those applications, it might help a little to use a program that intercepts the display at a low level and inverts all the colours.

<details>
<summary>
invert-vnc.diff
</summary>

```diff
--- t2/vnc-3.3.3r2/vncviewer/desktop.c	Mon Jun 14 12:24:29 2004
+++ vnc-3.3.3r2/vncviewer/desktop.c	Sat Jun 12 19:42:18 2004
@@ -363,6 +363,7 @@
 		 + x * myFormat.bitsPerPixel / 8);
 
     for (h = 0; h < height; h++) {
+      int i; for(i=0; i<widthInBytes; i++) buf[i]=~buf[i]; /* ssb hack */
       memcpy(scr, buf, widthInBytes);
       buf += widthInBytes;
       scr += scrWidthInBytes;
@@ -422,7 +423,7 @@
   case 8:
     for (q = 0; q < height; q++) {
       for (p = 0; p < width; p++) {
-	*(scr8++) = BGR233ToPixel[*(buf++)];
+        *(scr8++) = ~ BGR233ToPixel[*(buf++)]; /* ssb: added ~ */
       }
       scr8 += si.framebufferWidth - width;
     }
@@ -431,7 +432,7 @@
   case 16:
     for (q = 0; q < height; q++) {
       for (p = 0; p < width; p++) {
-	*(scr16++) = BGR233ToPixel[*(buf++)];
+	*(scr16++) = ~ BGR233ToPixel[*(buf++)]; /* ssb: added ~ */
       }
       scr16 += si.framebufferWidth - width;
     }
@@ -440,7 +441,7 @@
   case 32:
     for (q = 0; q < height; q++) {
       for (p = 0; p < width; p++) {
-	*(scr32++) = BGR233ToPixel[*(buf++)];
+	*(scr32++) = ~ BGR233ToPixel[*(buf++)]; /* ssb: added ~ */
       }
       scr32 += si.framebufferWidth - width;
     }
```

</details>

not working: invert colors on the xorg-server with `xcalib -i -a` or `xrandr-invert-colors`
this has no effect in vncviewer

workaround: [Invert colors of the active window](https://unix.stackexchange.com/questions/20565/invert-colors-of-the-active-window)

example: invert colors of one window on Xvnc with [picom](https://github.com/yshui/picom)

```sh
Xvnc -SecurityTypes none -localhost :2 &
sleep 2
DISPLAY=:2 picom --invert-color-include 'class_g="Chromium-browser"' &
sleep 2
DISPLAY=:2 chromium --user-data-dir=/tmp/chromium &
sleep 2
vncviewer :2
```

related issue: https://github.com/iiordanov/remote-desktop-clients/issues/130

**Comment by CendioOssman** [comment]
I'm afraid this likely falls outside what we want to take responsibility for in TigerVNC. This sounds like something that should be handled by your desktop environment, locally or remotely.

The fact that `xrandr-invert-colors` doesn't work could be an TigerVNC issue. But that functionality is for colour correction, so it's not really meant for this use case. Colour correction is monitor specific, so it's something that should ideally be handled by the client system.

So please check what features your desktop environment provides. I think I noticed that KDE offers something for this at least.

**Comment by milahu** [comment]
> This sounds like something that should be handled by your desktop environment, locally or remotely.

this requires a "compositing" window manager, which is not always available

in my workaround, im using picom on the server side

i would prefer a solution on the client side
because some clients may prefer lightmode

[wikipedia: Compositing window manager](https://en.wikipedia.org/wiki/Compositing_window_manager)

> A compositing manager, or compositor, is software that provides applications with an off-screen buffer for each window. The compositing manager composites the window buffers into an image representing the screen and writes the result into the display memory.

similar: the mpv video player [allows](https://github.com/mpv-player/mpv/issues/955) me to invert colors with `mpv --vf=sub,lavfi=negate video.mp4`

judging from `invert-vnc.diff` an implementation in vncviewer would be trivial
i just would require unswitching the "render frame" loop for better performance
