### ISSUE TITLE
UseLocalCursor option is not working

### ISSUE THREAD

**Issue by giridhar08** [TigerVNC/tigervnc#170]
Hi,

UseLocalCursor option is not working with vncviewer. 

vncviewer UseLocalCursor=1 192.xxx.xx.x:5900

This is very important for us as our requirement is to deliver VNC connection over citrix ICA, and ICA doesn't seems to work well with remote cursor as there seems lot be lot of lag. 

Thank you

**Comment by CendioOssman** [comment]
There is no setting for it since it is always turned on. You are either using a TigerVNC viewer together with an FLTK that doesn't support setting cursors, or there is some issue with the VNC server you are using.
