### ISSUE TITLE
copy paste / drag and drop between server and client not working at all

### ISSUE THREAD

**Issue by jackokapucin** [TigerVNC/tigervnc#1708]
**Describe the bug**
when connection is establish with remote computer, going to specific folder, can't copy file, can not see in my clipboard after copy was made. Even drag and drop not functioning at all

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [macOS Ventura 13.6.1.]
 - VNC client: [TigerVNC Viewer]
 - VNC client version: [1.13.1]
 - Client downloaded from: [https://sourceforge.net/projects/tigervnc/files/stable/1.13.1]

**Server (please complete the following information):**
 - OS: [macOS Sonoma]
 - VNC server: [MacOS]
 - VNC server version: [Sonoma latest]
 - Server downloaded from: []
 - Server was started using: []

**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid you cannot copy files via the VNC clipboard. And we don't have any drag-and-drop support at all.

Does this work with any VNC client? I don't think macOS's VNC server has any such functionality.

**Comment by CendioOssman** [comment]
No response. Closing.
