### ISSUE TITLE
Unusable with MacOSX Screen Sharing

### ISSUE THREAD

**Issue by kaihendry** [TigerVNC/tigervnc#171]
https://youtu.be/gAEsz5am2A8

Has MacOSX broken this feature? It's incredibly slow on a Wifi connection.
##

**Comment by CendioOssman** [comment]
Who knows. Apple's remote desktop is not really very VNC compatible and I don't know any effort to try and figure out their changes.

**Comment by kaihendry** [comment]
Is there a sane workaround you know of? Running tigervnc server on MacOSX?

**Comment by CendioOssman** [comment]
Not that I know of I'm afraid. A more proper VNC server would be desirable, but I'm not aware of any.

**Comment by kaihendry** [comment]
I think there is a tigervnc port on MacOSX via brew. Just hoping someone could chime in with what is known to work.

**Comment by CendioOssman** [comment]
It seems to work somewhat better in current versions of macOS. Still though, we can't improve things without a clear indication of what is needed. So I'll go ahead and close this issue.
