### ISSUE TITLE
Using TigerVNC Viewer on Win10 works but not Ubuntu

### ISSUE THREAD

**Issue by jmizv** [TigerVNC/tigervnc#1719]
**Describe the bug**
I have a Raspberry P 5 with a freshly installed Raspberry Pi OS and activated VNC.

Trying to connect via VNC with the `VncViewer-1.13.1.jar` (e.g. `java -jar VncViewer-1.13.1.jar`) fails after entering username and password with
```
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
com.tigervnc.rfb.AuthFailureException: Authentication failure: Invalid username or password
	at com.tigervnc.rfb.CConnection.processSecurityResultMsg(CConnection.java:328)
	at com.tigervnc.rfb.CConnection.processMsg(CConnection.java:147)
	at com.tigervnc.vncviewer.VncViewer.run(VncViewer.java:440)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Though I can perfectly connect via `vncviewer64-1.13.1.exe` from Windows 10. Why is that?

**To Reproduce**
Connect from Ubuntu via TigerVNCViewer to a Raspberry Pi OS with username/password

**Expected behavior**
I expect to connect via VNC on Ubuntu to the same machine like I can from Win10.

**Client**
 - OS: Ubuntu 22.04.3 LTS 64bit

**Server**
 - OS: 
 > PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian

**Comment by samhed** [comment]
It seems you're using the Java viewer on your raspberry and the regular viewer on Windows?

I think the Java viewer has different capabilities. Did you try with the regular Linux viewer?

**Comment by jmizv** [comment]
> It seems you're using the Java viewer on your raspberry and the regular viewer on Windows?
I use the Java Viewer on Ubuntu for accessing the Raspberry Pi, the regular viewer (*.exe) is used on Windows to acces the Raspberry Pi likewise. Okay, so these are not the same viewer? They differ in code and implementation?

> I think the Java viewer has different capabilities. Did you try with the regular Linux viewer?
Okay, I can try this, thanks.

**Comment by bphinz** [comment]
The RealVNC authentication protocol was only recently added to both viewers
and maybe there is a flaw with the java viewer.  I can take a look

**Comment by jmizv** [comment]
I've used the nightly build but looks like it raises the same problem:

```
~/Downloads$ java -jar VncViewer-1.13.80.jar 

TigerVNC Java Viewer v1.13.80 (20240206)
Built on 2024-02-06 at 03:45:23
Copyright (C) 1999-2024 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
DecodeManager: Detected 8 CPU core(s)
DecodeManager: Creating 4 decoder thread(s)
CConn: connected to host 192.168.1.238 port 5900
CConnection: Server supports RFB protocol version 3.8
CConnection: Using RFB protocol version 3.8
com.tigervnc.rfb.AuthFailureException: Authentication failure: Invalid username or password
	at com.tigervnc.rfb.CConnection.processSecurityResultMsg(CConnection.java:328)
	at com.tigervnc.rfb.CConnection.processMsg(CConnection.java:147)
	at com.tigervnc.vncviewer.VncViewer.run(VncViewer.java:440)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

I literally triple checked that the username and password are correct.

So for me it is okay if you don't look any further as I was just curious about using VNC from Ubuntu to Windows. I did not intend to use it on a regular base. Thanks.

**Comment by bphinz** [comment]
I was finally able to get my hands on a Raspberry Pi 5.  I tried both the default wayvnc and the RealVNC server and was able to connect to both just fine from Ubuntu 22.04.4.  I think what might be happening is that the "Send Local Username" option in the client (on the Security tab, under Authentication) is turned on by default so if the remote username is different then you would get that error.  Based on the screenshots (thanks for those) it looks like it is sending "pi" as the username, is that what you have as the username on the remote pi?

**Comment by CendioOssman** [comment]
No response. Closing.
