### ISSUE TITLE
xstartup not killed when server dies

### ISSUE THREAD

**Issue by feklee** [TigerVNC/tigervnc#172]
Sample `~/.vnc/xstartup`:

```
#!/bin/sh
while true; do sleep 1; done
```

I start `vncserver`, then kill it:

```
$ pkill X
```

And `xstartup` is still running:

```
$ ps a | grep xstartup
22475 pts/1    S      0:00 /bin/sh /home/felix/.vnc/xstartup
22512 pts/1    S+     0:00 grep xstartup
```
##

**Comment by CendioOssman** [comment]
It's not meant to do that either. Graphical programs will generally terminate when the X server disappears. Anything else will be left alone.

**Comment by feklee** [comment]
Well, Xorg does kill `~.xinitrc`. The problem is that I've loops in `xstartup` that respawn programs. No idea how to terminate them when shutting down `vncserver`.

**Comment by CendioOssman** [comment]
It's actually xinit that plays around with that file. You should be able to use xinit with Xvnc as well. But you probably won't be able to use the vncserver script at that point.

**Comment by feklee** [comment]
Using `xinit` to start `Xvnc` could be interesting. Here's how `vncserver` runs `xstartup`:

    system("$vncUserDir/xstartup >> " . &quotedString($desktopLog) . " 2>&1");

Anyhow, I solved the problem by letting the loop stop once the connection to X is lost:

    while xset q &>/dev/null
    do
        sleep 1 # actually respawn some program here
    done

Seems to work AFAICT.

**Comment by CendioOssman** [comment]
We now use xinit so this should be fixed.
