### ISSUE TITLE
Unrecognized option X509Cert when starting /usr/bin/Xtigervnc

### ISSUE THREAD

**Issue by robigan** [TigerVNC/tigervnc#1720]
**Describe the bug**
When starting the Xvnc server, a fatal error is produced with the error line:
```
Unrecognized option: −-X509Cert=/root/.vnc/desktop_vnc.pem

...help output...

Fatal server error:
(EE) Unrecognized option: −-X509Cert=/root/.vnc/desktop_vnc.pem
(EE)
```

**To Reproduce**
Run Xvnc executable with X509Cert parameter

**Expected behavior**
To be able to use tigervnc server using x509-encoded asymmetric keys

**Client (please complete the following information):**
 - OS: Linux Mint
 - VNC client: RealVNC
 - VNC client version: 7.9.0
 - Client downloaded from: Linux Mint software repository

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC server: [e.g. TigerVNC, or UltraVNC]
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from (Output of apt-cache):
```
tigervnc-standalone-server:
  Installed: 1.12.0+dfsg-4
  Candidate: 1.12.0+dfsg-4
  Version table:
 *** 1.12.0+dfsg-4 500
        500 https://mirror.init7.net/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```
 - Server was started using: LightDM VNCServer configuration

**Additional context**
<details>
<summary>This is my lightdm configuration block for anything VNC:</summary>

```
#
# VNC Server configuration
#
# enabled = True if VNC connections should be allowed
# command = Command to run Xvnc server with
# port = TCP/IP port to listen for connections on
# listen-address = Host/address to listen for VNC connections (use all addresses if not present)
# width = Width of display to use
# height = Height of display to use
# depth = Color depth of display to use
#
[VNCServer]
enabled=true
command=/usr/bin/Xvnc -rfbauth /root/.vnc/passwd -SecurityTypes X509Vnc −X509Cert /root/.vnc/desktop_vnc.pem -X509Key /root/.vnc/desktop_vnc.pem
port=5900
listen-address=0.0.0.0
user-session=cinnamon
width=1920
height=1080
depth=24

#[XDMCPServer]
#enabled=true
#port=177
#listen-address=localhost
```
</details>
<details>
<summary>Output from lightdm.log:</summary>

```
[+34.16s] DEBUG: Got VNC connection from 192.168.50.2:50006
[+34.16s] DEBUG: Seat vnc0: Loading properties from config section Seat:*
[+34.16s] DEBUG: Seat vnc0: Starting
[+34.16s] DEBUG: Seat vnc0: Creating greeter session
[+34.16s] DEBUG: Seat vnc0: Creating display server of type x
[+34.16s] DEBUG: XServer 1: Logging to /var/log/lightdm/x-1.log
[+34.16s] DEBUG: XServer 1: Writing X server authority to /var/run/lightdm/root/:1
[+34.16s] DEBUG: XServer 1: Launching X Server
[+34.16s] DEBUG: Launching process 87775: /usr/bin/Xvnc -rfbauth /root/.vnc/passwd -SecurityTypes X509Vnc −X509Cert /root/.vnc/desktop_vnc.pem -X509Key /root/.vnc/desktop_vnc.pem :1 -auth /var/run/lightdm/root/:1 -nolisten tcp -inetd -geometry 1920x1080 -depth 24
[+34.16s] DEBUG: XServer 1: Waiting for ready signal from X server :1
[+34.16s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat1
[+34.17s] DEBUG: Process 87775 exited with return value 1
[+34.17s] DEBUG: XServer 1: X server stopped
[+34.17s] DEBUG: XServer 1: Removing X server authority /var/run/lightdm/root/:1
[+34.17s] DEBUG: Seat vnc0: Display server stopped
[+34.17s] CRITICAL: x_server_local_get_authority_file_path: assertion 'server != NULL' failed
[+34.17s] CRITICAL: x_server_get_address: assertion 'server != NULL' failed
[+34.17s] DEBUG: Launching process 87776: /sbin/prime-switch
[+34.32s] DEBUG: Process 87776 terminated with signal 11
[+34.32s] DEBUG: Seat vnc0: Stopping session
[+34.32s] DEBUG: Seat vnc0: Session stopped
[+34.32s] DEBUG: Seat vnc0: Stopping display server, no sessions require it
[+34.32s] DEBUG: Seat vnc0: Stopping; greeter display server failed to start
[+34.32s] DEBUG: Seat vnc0: Stopping
[+34.32s] DEBUG: Seat vnc0: Stopped
```
</details>

Additionally, what do the various types of SecurityTypes mean? What's the difference between X509None, X509Vnc, and X509Plain and what about its TLS counterpart?

**Comment by CendioOssman** [comment]
> This is my lightdm configuration block for anything VNC:

It seems the dash (`-`) got replaced with a minus (`−`), so that's why it fails to parse that argument.

> Additionally, what do the various types of SecurityTypes mean? What's the difference between X509None, X509Vnc, and X509Plain and what about its TLS counterpart?

The different X509 types have different user authentication. None lets everyone in, Vnc uses classical VNC authentication, and Plain uses a user/password authentication. The latter requires PAM configuration, though, and often requires running Xvnc as root.

The TLS versions don't use certificates, so you get encryption but no protection against man-in-the-middle attacks. It's generally best to use the X509 versions.

> VNC client: RealVNC

I'm afraid RealVNC's client does not support the X509 types. You'll need to use our client, or another client that supports VeNCrypt.

**Comment by robigan** [comment]
> > This is my lightdm configuration block for anything VNC:
> 
> It seems the dash (`-`) got replaced with a minus (`−`), so that's why it fails to parse that argument.
> 
> > Additionally, what do the various types of SecurityTypes mean? What's the difference between X509None, X509Vnc, and X509Plain and what about its TLS counterpart?
> 
> The different X509 types have different user authentication. None lets everyone in, Vnc uses classical VNC authentication, and Plain uses a user/password authentication. The latter requires PAM configuration, though, and often requires running Xvnc as root.
> 
> The TLS versions don't use certificates, so you get encryption but no protection against man-in-the-middle attacks. It's generally best to use the X509 versions.
> 
> > VNC client: RealVNC
> 
> I'm afraid RealVNC's client does not support the X509 types. You'll need to use our client, or another client that supports VeNCrypt.

So what is VeNCrypt? How does that differ from X509 encryption types? Cus I've seen from other articles that it's a separate SecurityType.

As for the dash getting replaced by a minus, I already checked that using the command sans `--` and `=`, so yeah the option isn't getting recognized nonetheless.

**Comment by robigan** [comment]
Oh now that I reread my issue, I see that I gave the output from Xvnc when I was testing if it was the arg parse failing by being more specific with double dashes and equals sign. But I am using `-argument value` in my configs.

**Comment by robigan** [comment]
@CendioOssman

**Comment by CendioOssman** [comment]
> So what is VeNCrypt? How does that differ from X509 encryption types? Cus I've seen from other articles that it's a separate SecurityType.

VeNCrypt is an extension framework that allows using those X509 encryption types. Yes, it is technically also a security type, but it is required for all the X509 types to work.

> Oh now that I reread my issue, I see that I gave the output from Xvnc when I was testing if it was the arg parse failing by being more specific with double dashes and equals sign. But I am using `-argument value` in my configs.

The minus I quoted was from the config you included, not from the error output. So please double-check your configuration again and check that it is truly a dash for the `X509Cert` argument.

**Comment by robigan** [comment]
Right, seems that you were right, and I got it to work in the end. I figured out that it got in there because I copied the parameters from the man pages.
