### ISSUE TITLE
The variable name is incorrect

### ISSUE THREAD

**Issue by Jathon-yang** [TigerVNC/tigervnc#1721]
Tigervnc/common/rfb/Logger_ File.cxx
The variable name on line 103 of the file is incorrect.
`if (strlen(filename) >= sizeof(filename))`
Should be changed to
`if (strlen(filename) >= sizeof(m_filename))`

**Comment by CendioOssman** [comment]
Quite right. Thanks for finding the problem!

**Comment by CendioOssman** [comment]
Fixed in 238028d97ac3a9ab660b247cf1d9881ff40b6168.
