### ISSUE TITLE
Menu bar and desktop applications not appearing. 

### ISSUE THREAD

**Issue by KrystalSimmonds1** [TigerVNC/tigervnc#1723]
**Describe the bug**
As mentioned in the title, whenever I connect to TigerVNC (vncviewer64-1.13.1) all I can see is my desktop background. I can't see the menu or the shortcuts that are on my desktop usually. 

**To Reproduce**
1. Connect to TigerVNC

**Expected behavior**
I expect to be able to use the desktop as normal and see the applications I have available. 

**Screenshots**
![image](https://github.com/TigerVNC/tigervnc/assets/79720815/199727a3-b944-4c95-ba11-621e4e812dc9)

**Client (please complete the following information):**
 - OS: Windows Server 2016 Datacenter
 - VNC client: -
 - VNC client version: -
 - Client downloaded from: -

**Server (please complete the following information):**
 - OS: Amazon Linux 2
 - VNC server: TigerVNC
 - VNC server version: 1.13.1
 - Server downloaded from: Downloaded using 'sudo yum install tigervnc-server'
 - Server was started using: sudo systemctl start vncserver@:1

**Additional context**
I apologise if I've filled this out incorrectly. I'm not familiar with GUIs. I have searched for an answer but have been unable to find anything online. Some background info is that my hardware is a macbook and I'm using windows via AWS Workspaces.

**Comment by CendioOssman** [comment]
Those symptoms usually mean that there was some issue starting the desktop environment for the session.

One common reason is that you are already logged in with the same user on the local console of the system. Could that be the case here?

**Comment by KrystalSimmonds1** [comment]
> Those symptoms usually mean that there was some issue starting the desktop environment for the session.
> 
> One common reason is that you are already logged in with the same user on the local console of the system. Could that be the case here?

This is unfortunately not the case. I normally have an SSH tunnel on VS code to connect to my EC2 and I have the GUI running so that I can run puppeteer tests in headless mode. It's never really been an issue before. I was connect as normal earlier today and when I went to use my GUI after spending maybe a couple of hours away from it I've seen this issue. Would uninstalling/removing and re-installing help? I have no issue doing the above but I would rather this be a last resort.

**Comment by CendioOssman** [comment]
I don't think reinstalling TigerVNC would help, no.

Have you tried a restart of the system? It's cliché, but it can sometimes help if there is some service that has managed to lock up.

**Comment by KrystalSimmonds1** [comment]
Thanks for your help @CendioOssman. Good old 'sudo reboot' on my ec2 did the trick. I'd logged out/exited a number of times but didn't think to reboot. Enjoy the rest of your day
