### ISSUE TITLE
x0vncserver doc "AcceptPointerEvents" missleading

### ISSUE THREAD

**Issue by iot-rocket** [TigerVNC/tigervnc#1724]
**Describe the bug**
According to: https://tigervnc.org/doc/x0vncserver.html the argument for `AcceptPointerEvents` says:
```
−AcceptPointerEvents
Accept pointer press and release events from clients. Default is on.
```
From the description I would expect that the mouse-pointer would still be movable and just the click events are disabled.

**To Reproduce**
Start x0vncserver by:
```sh
x0vncserver -AcceptPointerEvents=0 -passwordfile ~/.vnc/passwd -display :0
```
and connect to the VNC Session.

**Expected behavior**
From the description I would expect that the mouse would still be controllable and just the click events are disabled. But the mouse-pointer does not move anymore.

**Client (please complete the following information):**
 - OS: Debian 11
 - VNC client: TigerVNC
 - VNC client version: 1.13.1
 - Client downloaded from: https://sourceforge.net/projects/tigervnc/files/stable/1.13.1/

**Server (please complete the following information):**
 - OS: Debian 11
 - VNC server: TigerVNC
 - VNC server version: 1.13.1
 - Server downloaded from: https://sourceforge.net/projects/tigervnc/files/stable/1.13.1/
 - Server was started using: `x0vncserver -AcceptPointerEvents=0 -passwordfile ~/.vnc/passwd -display :0`

**Additional context**
Either the documentation needs to get updated("Bug") or the functionality should get extended by this very usefull feature

**Comment by CendioOssman** [comment]
I agree, that is a bit misleading. It looks like someone simply copied the description from `AcceptKeyEvents`.

I've updated the documentation in e9d78517c90f393a5f5c420d6543b958d2b31032. Thanks for reporting the issue.
