### ISSUE TITLE
TigerVNC extension for auto-login

### ISSUE THREAD

**Issue by evan0greenup** [TigerVNC/tigervnc#1725]
**Is your feature request related to a problem? Please describe.**
When both client-side and server-side use TigerVNC. Is it possible to let client-side be able to send username and password or other credential to server-side via secure tunnel. So the end-user does not need to manually input the username and password.

**Describe the solution you'd like**
It would be nice to add some TigerVNC specific protocol to pass credential from client to server. And the login related information can be saved inside `*.tigervnc` file.

**Describe alternatives you've considered**

It would be also good to provide an alternative authenticate based on asymmetric encryption/signature. That client submit a pubkey to server. And client use its private key to sign session token and send back to server. (Just like how SSH do for security)

**Additional context**
If the user can automatically login without manually input login credential. It will be a great advantage for tigervnc.

**Comment by CendioOssman** [comment]
Yes, it is possible to automate these things.

If you need both the username and password, then the only current method is using the environment variables `VNC_USERNAME` and `VNC_PASSWORD`.

If you only require the password, then you can set the setting `PasswordFile` to point to a file generated by `vncpasswd`.

I'm afraid that it is not currently possible to specify these fields in a `.tigervnc` file. Hopefully, these alternatives are sufficient for your use case.

**Comment by LorenAmelang** [comment]
`If you need both the username and password, then the only current method is using the environment variables VNC_USERNAME and VNC_PASSWORD.`

I have used 
```
[loren@Gazp9 ~]$ export VNC_USERNAME=xx
[loren@Gazp9 ~]$ export VNC_PASSWORD=xyzzy
[loren@Gazp9 ~]$ printenv
SHELL=/bin/bash
...
VNC_PASSWORD=xyzzy
...
VNC_USERNAME=pi
...
_=/usr/bin/printenv
[loren@Gazp9 ~]$ 
```
Logged out, logged in...  Yes, those are (masked here versions of) the same entries that work when manually typed. 

But the Tiger client still asks for User and Password like before. 

I see tons of places in Arch Linux where you can supposedly add environment variables, but that seems to be the simplest. Do I need to put them somewhere else? Perform some other ritual?

**Comment by CendioOssman** [comment]
Did you start vncviewer in that same terminal? Setting environment variables that way will not affect applications started in another way (e.g. by clicking the TigerVNC icon).
