### ISSUE TITLE
Error: Could not read the line(28)

### ISSUE THREAD

**Issue by michaelobe** [TigerVNC/tigervnc#173]
On Max OS X TigerVNC 1.4.3.
If I try to load a tigervnc file I get the following error on the console:
Parameters:  Could not read the line(28) in the configuration file,the
              buffersize is to small.

It does not load any settings from the file.

Interestingly there are only 27 lines in the configuration file. It used to work but I forget which version it was (1-2 versions ago).

**Comment by CendioOssman** [comment]
This is a bug that we've fortunately already fixed on master (3b865f1). We'll try to make a 1.5 release with it shortly.

Normally I'd point you at the nightly builds. But sourceforge has apparently killed of our storage for those. :/
