### ISSUE TITLE
Digital signature issues

### ISSUE THREAD

**Issue by Saxomania** [TigerVNC/tigervnc#1730]
Similar but not same as https://github.com/TigerVNC/tigervnc/issues/1503

**Describe the bug**
Invalid digital signature because of missing timestamp

**To Reproduce**
check screenshot, i did an overview of version 12.8 (good), 13.1 (bad) and 13.8 (bad)

**Expected behavior**
get it done right :)

**Screenshots**
![WKvKUHrZPt](https://github.com/TigerVNC/tigervnc/assets/11755505/bbb0012d-0037-4562-a908-f0de21b94d3e)

**Client (please complete the following information):**
 - OS: Windows 10

**Additional context**
dont miss timestamps because if any other cert in your trust chain is expired it will break yours too

**Comment by CendioOssman** [comment]
@bphinz, could you have a look? Seems like you need a renewed certificate.

**Comment by CendioOssman** [comment]
Ping @bphinz.

Can you give us a status update? This is a bit problematic if we'd like to make a new release.

**Comment by bphinz** [comment]
The new signing cert is in place and the current nightly builds have the updated signatures
