### ISSUE TITLE
Can't enter password on macOS

### ISSUE THREAD

**Issue by catap** [TigerVNC/tigervnc#1731]
**Describe the bug**

When I connect to macOS 13 host, and after enter VNC password I see a login screen where I should enter user password. I can move mouse but I can't enter anything which inclued password.

So, I can't login into machine.

**To Reproduce**
1. Connect't to macOS host which doesn't loged in
2. Unable to enter password.

**Expected behavior**
Be able to enter password

**Screenshots**

![screenshot-2024-02-20_22-58-58](https://github.com/TigerVNC/tigervnc/assets/37775/28d9cb61-e5f6-45df-ae16-327feaed8bf6)

**Client (please complete the following information):**
 - OS: OpenBSD 7.5-beta
 - VNC client: TigerVNC Viewer
 - VNC client version: 1.13.1
 - Client downloaded from: installed from OpenBSD ports

**Server (please complete the following information):**
 - OS: macOS 13
 - VNC server: embeded into macOS
 - VNC server version: no idea
 - Server downloaded from: no idea
 - Server was started using: no idea

**Comment by CendioOssman** [comment]
Could you test with a different VNC client so we can rule out any issues with the server?

Any reason you are still on macOS 13 rather than 14? With some luck, it could be any issue resolved in macOS 14.

**Comment by catap** [comment]
> Could you test with a different VNC client so we can rule out any issues with the server?

Yes, I can login via another clients :(

> Any reason you are still on macOS 13 rather than 14? With some luck, it could be any issue resolved in macOS 14.

I need VNC to update that machine :)

**Comment by CendioOssman** [comment]
Well, that complicates things. :)

Which other clients have you tested?

Could you enable debug logging and let us know what it says:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs#os-x

It will tell us what key events the client is trying to send.

**Comment by macmacy** [comment]
I have same issue when trying to access mac OS 14. 
Except, that in this case, other VNC clients do not work as well (tried tight and ultra). And I use Windows version of the client.

The important thing is (maybe) that this is old iMac with Sonoma installed using OpenCore Legacy Patcher (https://dortania.github.io/OpenCore-Legacy-Patcher/).  I see no other networking-related issues after this update: mac has Internet access. And -  VNC client DOES connect and displays log-on screen - I "just" cannot enter any keyboard input.

**Comment by CendioOssman** [comment]
No response. Closing.
