### ISSUE TITLE
VNC It takes up a lot of network.

### ISSUE THREAD

**Issue by dnslin** [TigerVNC/tigervnc#1732]
**Describe the bug**

**To Reproduce**
1. Shake the window

**Expected behavior**
The desktop used to connect the intranet archlinux tigervnc through realvnc viewer on the windows11 is KDE, which takes up a lot of network after shaking the window.

My intranet is gigabit. When shaking the window, the network occupies up to `400mbps/s`

```bash
session=plasma
geometry=2560x1440
alwaysshared
```

**Screenshots**
![a](https://github.com/TigerVNC/tigervnc/assets/49158572/179641ce-f949-4022-a1c6-51169510d391)

**Client (please complete the following information):**
 - OS: win 11
 - VNC client: realvnc vnc viewer
 - VNC client version: [e.g. 1.8.0]

**Server (please complete the following information):**
 - OS: archlinux
 - VNC server: TigerVNC
 - VNC server version: latest
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver`]

**Comment by CendioOssman** [comment]
TigerVNC will try to provide a good user experience, so it will use any bandwidth available if that means it can push more updates. So I'm afraid I don't see anything abnormal here.

That said, I don't think RealVNC supports the necessary extensions to make TigerVNC a bit more efficient for the network. So I would suggest trying our client instead and see if that uses less bandwidth.
