### ISSUE TITLE
Output Corrupts When Resolution Is Very Short

### ISSUE THREAD

**Issue by BaconB0T** [TigerVNC/tigervnc#1736]
**Describe the bug**
Output becomes corrupted/garbled when making the server's resolution's height too short through a client.

**To Reproduce**
1. Start vncviewer through the systemd service.
2. Connect using noVNC or TigerVNC clients.
3. Resize the client window by dragging up from the bottom until very close to the top.
4. The output becomes corrupted and will not reset until the vncserver is restarted.

**Expected behavior**
The display should be clear and not produce artifacts.

**Screenshots**
What I mean by corrupted/garbled output:
![image](https://github.com/TigerVNC/tigervnc/assets/63115990/dc8a8fac-e8d8-4f0c-abb5-b05a59b90c81)

**Client (please complete the following information):**
 - OS: WSL 2 - Ubuntu 22.04
 - VNC client: TigerVNC (also tested with noVNC)
 - VNC client version: 1.12.0 (noVNC version 1.4.0)
 - Client downloaded from: my Linux distribution

**Server (please complete the following information):**
 - OS: RHEL 8
 - VNC server: TigerVNC
 - VNC server version: 1.31.1
 - Server downloaded from: yum repo: `rhel-8-appstream-rhui-rpms`
 - Server was started using: `vncserver` through the systemd unit.

**Additional context**
Resizing the client causes the following logs on the server. After making the resolution too small, `0 pixels in / 0 pixels out` and `(1:-nan ratio)` are always present no matter the size I change it to afterwards. 
```
Thu Mar 14 21:59:33 2024
 ComparingUpdateTracker: 944.194 kpixels in / 234.1 kpixels out
 ComparingUpdateTracker: (1:4.03329 ratio)

Thu Mar 14 21:59:34 2024
 ComparingUpdateTracker: 112.8 kpixels in / 112.8 kpixels out
 ComparingUpdateTracker: (1:1 ratio)

Thu Mar 14 21:59:38 2024
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)
```

Checking the resolution with xrandr, it seems to break when resizing and the height goes below 150. I could not get the output to corrupt when resizing just the width.

**Comment by CendioOssman** [comment]
Thanks for your report.

Historically, that bug has often been the desktop environment crashing/misbehaving.

I assume it is GNOME that's being used? Could you try a different desktop environment and see if the issue still appears?

**Comment by BaconB0T** [comment]
Thanks for the quick response.

Yes, GNOME 3.28 is the only desktop environment available on RHEL8 (see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/using_the_desktop_environment_in_rhel_8/index). 

I'll try getting KDE on RHEL 7 just to confirm it's GNOME

**Comment by BaconB0T** [comment]
Yup, it's a GNOME problem. Neither KDE nor XFCE have the same problem.

Closing this out since it's evidently not a TigerVNC problem. Thank you for the help!
