### ISSUE TITLE
Show a list of recent connections/server names

### ISSUE THREAD

**Issue by jonhp** [TigerVNC/tigervnc#174]
Enhancement Request (v1.4.3 -- in my case running on win7 64bit)
If this is a duplicate, I apologize; I looked but didn't find anything I thought the same. On the "VNC Viewer: Connection Details" dialog box, there is a field called "VNC server:" It would be nice if this was a drop down list of servers which have been successfully connected to. Then the user could simply pick one and click "Connect". An "X" symbol at the right hand end, if clicked on, would be a request to remove that server from the drop down list. New systems would be automatically added as successful connections are made. Thanks for considering.
##

**Comment by jvillar2** [comment]
I would like a dropdown too; i am use to using TightVNC so this seems odd not to have drop-down.  I have 3+ vnc sessions for different projects and designs so would be nice to have ease-of-usage here.

**Comment by jwildstr** [comment]
Is this likely to be implemented? I like TigerVNC far better than UltraVNC (my other go-to) but the lack of history is really hampering me.

**Comment by CendioOssman** [comment]
PR #656 was an attempt at this, but I haven't gotten any response to my feedback. :/

**Comment by pauledd** [comment]
+1 on a history list in 2019!

**Comment by CendioOssman** [comment]
Fixed now by #1176. :)
