### ISSUE TITLE
TigerVNC Client: no window appears on connection (becomes Task Manager "Background Process")

### ISSUE THREAD

**Issue by SterlingButters** [TigerVNC/tigervnc#1743]
**Describe the bug**
TigerVNC Client becomes a (Task Manager) "Background Process" so no GUI is rendered after specifying connection details. Prior to step 2) below, the client is running as a (Task Manager) App. I can see from the server side `Connections: accepted: <ip address>::<port>` so I don't think the issue is with the server. 

**To Reproduce**
1) Type in VNC Server name in Connection Details window
2) Hit "Connect"
3) Observe "TigerVNC Client" becoming a "Background Process"

**Expected behavior**
I expected to see the screen of the remote machine as I have in the past. 

**Client (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC client: [e.g. TigerVNC, or UltraVNC]
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: RHEL Server 7.9
 - VNC server: Xvnc TigerVNC 
 - VNC server version: 1.8.0
 - Server downloaded from: Shipped w/ distro
 - Server was started using: `DISPLAY=:1 gnome-session & Xvnc -verbose -listen tcp -rfbport 5900 :1 -PasswordFile <path/to/file>

**Additional context**
What is the possibility of there being a group policy that prevents programs from running as a (Task Manager) App?

**Comment by gfoam** [comment]
If you're using a portable version, move it to ie Desktop location. It appears that the software doesn't like special characters on the directory it is located. Regards

**Comment by vrutantthakore** [comment]
Facing the same issue, it still is running in the background. 
It attaches to the dock once we "connect" to the server but we don't see any GUI

**Comment by SterlingButters** [comment]
> If you're using a portable version, move it to ie Desktop location. It appears that the software doesn't like special characters on the directory it is located. Regards

Not using a portable version AFAIK - installed to Program Files. Funny enough I can get it working if I ssh port forward to localhost:5900 (with PuTTy) and call the TigerVNC Client on localhost:5900.

**Comment by CendioOssman** [comment]
TigerVNC hides the connection window as soon as it *starts* the connection process, but it won't show the session window until everything is fully connected. So if there is some problem connecting, there can unfortunately be a long period with no UI.

Have you tried waiting it out and see if it eventually shows some form of error?

It would also be helpful if you could provide a debug log for the client:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs

**Comment by SterlingButters** [comment]
I think I let it run for several hours at one point. Unfortunately, I don't think I will be able to share a log report since it is on a corporate system.

**Comment by vrutantthakore** [comment]
> TigerVNC hides the connection window as soon as it _starts_ the connection process, but it won't show the session window until everything is fully connected. So if there is some problem connecting, there can unfortunately be a long period with no UI.
> 
> Have you tried waiting it out and see if it eventually shows some form of error?
> 
> It would also be helpful if you could provide a debug log for the client:
> 
> https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs

yes, it was a connection issue and got resolved once I restored my connection
