### ISSUE TITLE
BUG?There is a problem with some errors.

### ISSUE THREAD

**Issue by e-tw** [TigerVNC/tigervnc#1746]
**Describe the bug**
What version of the "VC Redistributable Package" must be installed in order to run correctly?

**To Reproduce**

**Expected behavior**

**Screenshots**
![擷取](https://github.com/TigerVNC/tigervnc/assets/138014001/2076d88e-3058-47b3-aa7b-af38cc353a72)
![擷取0](https://github.com/TigerVNC/tigervnc/assets/138014001/e709074a-3580-472f-8e3f-ec57bc8f6922)

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client:tigervnc
 - VNC client version: 1.13.80
 - Client downloaded from: nightly

**Server (please complete the following information):**
 - OS: Windows 10
 - VNC server: tigervnc64-winvnc
 - VNC server version:1.13.80
 - Server downloaded from:nightly
 - Server was started using:tigervnc64-winvnc

**Additional context**
@cendio @CendioOssman

**Comment by CendioOssman** [comment]
I'm afraid it looks like you are hitting some bug, rather than an issue with the runtime libraries.
Could you include the steps you take to produce these error messages?

**Comment by e-tw** [comment]
Hi,
To Reproduce
The main problem is that the authentication part of the program will fail no matter if you enter a password.

**Comment by CendioOssman** [comment]
Your screenshot seems to show vncconfig, so I guess this is when you try to *configure* the password? Not when trying to authenticate using a VNC client?

Your report also has two error messages. Do they both happen from the same action? Or are there separate steps for the two?

**Comment by e-tw** [comment]
> Your screenshot seems to show vncconfig, so I guess this is when you try to _configure_ the password? Not when trying to authenticate using a VNC client?
> 
> Your report also has two error messages. Do they both happen from the same action? Or are there separate steps for the two?

The part with the line "130" is the error that occurs when I reopen "winvnc4.exe".

**Comment by CendioOssman** [comment]
This should hopefully be fixed in 763cf8b27cb79e97bb2e5edefbc5bdce9bd6b6f7. Please try tomorrow's nightly build and see if the crashes are gone.
