### ISSUE TITLE
I suddenly stopped Tigervnc Pointer in settings but now how to activate the mouse!

### ISSUE THREAD

**Issue by EragGoshiH** [TigerVNC/tigervnc#1749]
Please help me to activate the mouse.
![Uploading Screenshot_2024-04-23-22-17-21-080_com.offsec.nethunter.kex.jpg…]()

**Comment by CendioOssman** [comment]
Please fill out the issue template so we can understand your setup. It also seems that screenshot did not upload properly.

**Comment by EragGoshiH** [comment]
The bug Fixed!

ZazakaLLah Khairan.
