### ISSUE TITLE
AltGR not working with Ubuntu and Win11 RealVncViewer

### ISSUE THREAD

**Issue by mpovel** [TigerVNC/tigervnc#1751]
When trying to write |,@ or any other key requireing AltGRr on german keyboard, key is not accepted.

Connect from WIN11 RealVNCClient to sytem running tigervnc x0 server I try to type any symbol using AltGr in terminal, so key is seen.
Works perfect with Raspberry PI and the default VNC (RealVNCServer, that is the reason I need this client)

**Expected behavior**
The keys should work as with raspbian even if using tigervnc x0 server.

**Client (please complete the following information):**
 - OS: Win11
 - VNC client: RealVnc
 - VNC client version: 7.6.0

**Server (please complete the following information):**
 - OS: ubuntu 22.04.04
 - VNC server: tigervnc
 - VNC server version: 1.12.0
 - Server was started using:  x0tigervncserver

**Additional context**
Issue does not occure with raspberry, only with the tigervnc 

Works with tigervnc client OK, but my expectation would be portability between different clients...

**Comment by CendioOssman** [comment]
Please see #528. x0vncserver doesn't have fancy enough keyboard handling yet.

Assuming RealVNC sends proper keyboard events, you should be able to work around the issue by having the same keyboard layout on both the client and server. If that still doesn't work, then I would assume that RealVNC is sending bad keyboard events and more magic would be needed in our end to compensate for that fact.
