### ISSUE TITLE
Brave starts in display 2 but opens prompts in display 0

### ISSUE THREAD

**Issue by bitcoinmeetups** [TigerVNC/tigervnc#1756]
**Describe the bug**
Brave starts in display 2 but opens prompts in display 0
**To Reproduce**
brave-browser
right click image
prompt opens in display 0 instead of display 2 which I'm currently working in
**Expected behavior**
I expect every window that opens in display 2 to open every prompt in display 2 as well.
**Screenshots**

**Client (please complete the following information):**
Android bVNC

**Server (please complete the following information):**
Debian 12
TigerVNC latest

**Additional context**

**Comment by CendioOssman** [comment]
I'm afraid that is some issue with Brave. TigerVNC does not control such things. Please report the issue to them or Debian.

Are you also logged in locally on the server? Many systems do not support multiple graphical sessions as the same user.
