### ISSUE TITLE
'*' character in password

### ISSUE THREAD

**Issue by eu4you** [TigerVNC/tigervnc#1758]
Hello.
I launch vncserver 1.13.1+dfsg-2build2 installed by apt-get in ubuntu 22.04,
`vncserver :1 -localhost no -securitytypes vncauth`

And '*' character is in password,
`phrase1*phrase2`

Then, after the character '*' are ignored. Any characters can accept by password,
ex) phrase1* / phrase1*121314sdafd / phrase1**&(&^ .... etc.

This happenned not to limit specific vnc client(noVNC, tigervnc viewer, ultravnc viewer)

**Comment by CendioOssman** [comment]
How long are the phrases? Could this just be #370?

**Comment by eu4you** [comment]
My password is combined 8 characters containd 1 special character, 1 capital letter, 2 small letters, and 4 numbers, before * character. And 4 characters contained 1 capital letter, and 3 special characters, after * character. So totally 13 characters.

**Comment by CendioOssman** [comment]
That sounds exactly like #370. There are eight characters before *, so it's expected that it will ignore everything after that. Please see the other issue for future improvements to this.
