### ISSUE TITLE
Nightly debian builds

### ISSUE THREAD

**Issue by chrism2671** [TigerVNC/tigervnc#176]
Do these still exist? They're referred to at the bottom of BUILDING.txt but the SVN repo seems to have gone in favour of Github, and I'm not quite sure how to use the contents of /contrib/packages with dpkg.

Thanks!

**Comment by bphinz** [comment]
On Fri, Jun 19, 2015 at 4:28 AM, chrism2671 wrote:

> Do these still exist? They're referred to at the bottom of BUILDING.txt
> but the SVN repo seems to have gone in favour of Github, and I'm not quite
> sure how to use the contents of /contrib/packages with dpkg.
>
> Thanks!
>
Yes, there is a link to the nightly builds on the tigervnc.org home page.
Unfortunately, sourceforge recently turned off access to the project
completely so I can't even put a redirect page into the old nightly build
location...

-brian

**Comment by CendioOssman** [comment]
@bphinz, will you have a look at updating BUILDING.txt? Perhaps it's best to leave contrib stuff out of that file completely?

**Comment by chrism2671** [comment]
It probably makes sense to have some kind of official build if there is one. I spent a good hour trying to compile tigervnc from source on Ubuntu 14.04 LTS and gave up; if it's easy provide a package, it will really help.

**Comment by Alexqw** [comment]
@chrism2671 In case this helps, here's the [mailing list] (https://lists.alioth.debian.org/pipermail/pkg-tigervnc-devel/) for those who maintain TigerVNC for Debian. There's been some effort recently to get the latest beta building, but I believe it's currently blocking on [this bug] (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23791346).

**Comment by bphinz** [comment]
On Fri, Jun 26, 2015 at 3:52 AM, chrism2671 <notifications@github.com>
wrote:

> It probably makes sense to have some kind of official build if there is
> one. I spent a good hour trying to compile tigervnc from source on Ubuntu
> 14.04 LTS and gave up; if it's easy provide a package, it will really help.
>
Our official .debs are available on bintray (
https://bintray.com/tigervnc/stable/tigervnc/1.4.3/view#files
<https://bintray.com/tigervnc/stable/tigervnc/1.4.3#files> for stable, and
https://bintray.com/tigervnc/beta/tigervnc/1.5beta/view#files for the 1.5
beta).

-brian

**Comment by CendioOssman** [comment]
So can we close this?
