### ISSUE TITLE
ctrl+shift+"." and ctrl+shift+"," ctrl-+shift+"+" are not correctly sent to server. Kitty not fully usable.

### ISSUE THREAD

**Issue by michaeltraxler** [TigerVNC/tigervnc#1776]
When connected via tigervncviewer (v1.13.1) to a tigervncserver (1.13.1) the 
following keys are not transported correctly:
ctrl+shift+"." and ctrl+shift+"," ctrl-+shift+"+"

Curiously, ctrl-+shift+"-" is transported correctly.
This can be seen, when using kitty, which for example should increase the font size with 
ctrl-+shift+"+", but there is no reaction when these keys are pressed.
But decreasing the font size with ctrl-+shift+"-" works.

Do you have any idea, what is wrong here?

The same behavior when using remmina as a vnc-client.

**Comment by CendioOssman** [comment]
Please fill out the full issue template, so we better understand your setup.

Also, could you please provide some debug logs from the client and server. You can find details on how to produce those here:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs

**Comment by michaeltraxler** [comment]
**Describe the bug**

The key-combinations 
ctrl+shift+"."   ,  "ctrl+shift+","  and " ctrl-+shift+"+"
are not transported correctly to the tigervnc-server

**To Reproduce**
Steps to reproduce the behavior:

1. Connect via tigervncviewer to a tigervncserver
2. Open an application, which reacts on the key-combinations ctrl+shift+"."   ,  "ctrl+shift+","  and " ctrl-+shift+"+"
3. e.g. in the application kitty, the key combination ctrl+shift+"+" is increasing the font-size, but this doesn't work. But a simple ctrl + '+' works, so it arrives at the application kitty as if I had pressed ctrl + shift + '+'.


**Expected behavior**
I expect that the key combinations increase the font size.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Client (please complete the following information):**
 - OS: openSUSE Tumbleweed 20240701
 - VNC client: tigervnc and remmina
 - VNC client version: v1.13.1

**Server (please complete the following information):**
 - OS:   openSUSE Tumbleweed 20240701
 - VNC server: tigervnc
 - VNC server version: 1.13.1
 - Server was started using: [e.g. `vncserver`]

**Additional context**

When looking to the logfiles I see in the vncviewer 4 times the keypress for 
shift + ctrl + ',' (german keyboard!):

```
Fri Jul  5 10:58:34 2024
 Viewport:    Key pressed: 0x001d => XK_Control_L (0xffe3)
 Viewport:    Key pressed: 0x002a => XK_Shift_L (0xffe1)

Fri Jul  5 10:58:35 2024
 Viewport:    Key pressed: 0x0033 => XK_semicolon (0x003b)
 Viewport:    Key released: 0x0033 => XK_semicolon (0x003b)
 Viewport:    Key pressed: 0x0033 => XK_semicolon (0x003b)
 Viewport:    Key released: 0x0033 => XK_semicolon (0x003b)

```

In the server I see:

```
Fri Jul  5 10:58:34 2024
 VNCSConnST:  Key pressed: 0xffe3 / 0x1d
 Input:       keycode 37 down
 VNCSConnST:  Key pressed: 0xffe1 / 0x2a
 Input:       keycode 50 down

Fri Jul  5 10:58:35 2024
 VNCSConnST:  Key pressed: 0x3b / 0x33
 Input:       temp shift 50 up
 Input:       keycode 47 down
 Input:       temp shift 50 down
 VNCSConnST:  Key released: 0x3b / 0x33
 Input:       keycode 47 up
 VNCSConnST:  Key pressed: 0x3b / 0x33
 Input:       temp shift 50 up
 Input:       keycode 47 down
 Input:       temp shift 50 down
 VNCSConnST:  Key released: 0x3b / 0x33
 Input:       keycode 47 up

```



If I use the ctrl + shift + '+' key I get the following:

```
Fri Jul  5 11:05:44 2024
 Viewport:    Key pressed: 0x001d => XK_Control_L (0xffe3)
 Viewport:    Key pressed: 0x002a => XK_Shift_L (0xffe1)
 Viewport:    Key pressed: 0x001b => XK_asterisk (0x002a)

Fri Jul  5 11:05:45 2024
 Viewport:    Key released: 0x001b => XK_asterisk (0x002a)
 Viewport:    Key pressed: 0x001b => XK_asterisk (0x002a)

Fri Jul  5 11:05:46 2024
 Viewport:    Key released: 0x001b => XK_asterisk (0x002a)
 Viewport:    Key pressed: 0x001b => XK_asterisk (0x002a)
 Viewport:    Key released: 0x001b => XK_asterisk (0x002a)

Fri Jul  5 11:05:47 2024
 Viewport:    Key pressed: 0x001b => XK_asterisk (0x002a)
 Viewport:    Key released: 0x001b => XK_asterisk (0x002a)

Fri Jul  5 11:05:48 2024
 Viewport:    Key released: 0x002a => XK_Shift_L (0xffe1)
 Viewport:    Key released: 0x001d => XK_Control_L (0xffe3)


```
the server tells:

```
Fri Jul  5 11:05:44 2024
 VNCSConnST:  Key pressed: 0xffe3 / 0x1d
 Input:       keycode 37 down
 VNCSConnST:  Key pressed: 0xffe1 / 0x2a
 Input:       keycode 50 down
 VNCSConnST:  Key pressed: 0x2a / 0x1b
 Input:       keycode 17 down

Fri Jul  5 11:05:45 2024
 VNCSConnST:  Key released: 0x2a / 0x1b
 Input:       keycode 17 up
 VNCSConnST:  Key pressed: 0x2a / 0x1b
 Input:       keycode 17 down

Fri Jul  5 11:05:46 2024
 VNCSConnST:  Key released: 0x2a / 0x1b
 Input:       keycode 17 up
 VNCSConnST:  Key pressed: 0x2a / 0x1b
 Input:       keycode 17 down
 VNCSConnST:  Key released: 0x2a / 0x1b
 Input:       keycode 17 up

Fri Jul  5 11:05:47 2024
 VNCSConnST:  Key pressed: 0x2a / 0x1b
 Input:       keycode 17 down
 VNCSConnST:  Key released: 0x2a / 0x1b
 Input:       keycode 17 up

Fri Jul  5 11:05:48 2024
 VNCSConnST:  Key released: 0xffe1 / 0x2a
 Input:       keycode 50 up
 VNCSConnST:  Key released: 0xffe3 / 0x1d
 Input:       keycode 37 up
```

If I press ctrl + '+' (no shift key!), which increases the font size in kitty, so a shift + ctrl + '+' is sent to kitty.
The logs show:

```
Fri Jul  5 11:08:54 2024
 Viewport:    Key pressed: 0x001d => XK_Control_L (0xffe3)

Fri Jul  5 11:08:55 2024
 Viewport:    Key pressed: 0x001b => XK_plus (0x002b)
 Viewport:    Key released: 0x001b => XK_plus (0x002b)
 Viewport:    Key released: 0x001d => XK_Control_L (0xffe3)

```
and in the server:

```
Fri Jul  5 11:08:54 2024
 VNCSConnST:  Key pressed: 0xffe3 / 0x1d
 Input:       keycode 37 down

Fri Jul  5 11:08:55 2024
 VNCSConnST:  Key pressed: 0x2b / 0x1b
 Input:       temp shift 50 down
 Input:       keycode 21 down
 Input:       temp shift 50 up
 VNCSConnST:  Key released: 0x2b / 0x1b
 Input:       keycode 21 up
 VNCSConnST:  Key released: 0xffe3 / 0x1d
 Input:       keycode 37 up
```

**Comment by michaeltraxler** [comment]
Additional information:
The key combination to decrease the font size, which is ctrl + shift + '-' , is transported correctly to the kitty application!

And, very important,  I just see, if I change the keyboard layout on the client (the X11 display I'm sitting at and start the vncviewer) to 'us' ("setxkbmap us"), then all mentioned keypresses are transported correctly!
So, it is a keyboard-mapping issue...

**Comment by CendioOssman** [comment]
I'm afraid this is how VNC works, so it is expected. VNC focuses on symbols, not keys. So it does not preserve the exact key combination and will map to some other set of keys if that is necessary to get the same symbol.

The usual workaround for this is to set the same keyboard layout on the client and server.

You can also use the RawKeyboard setting on the server, which will switch to a key centric system instead. It requires a compatible client, though, so will not work with all VNC clients.
