### ISSUE TITLE
`BUILD_STATIC=ON` but win-installer doesn't contain necessary DLLs

### ISSUE THREAD

**Issue by a90091343** [TigerVNC/tigervnc#1778]
**Describe the bug**
When I build a TigerVNC viewer installer for Windows and install it on another Windows computer, it reports errors such as "The code execution cannot proceed because libffi-8.dll was not found."

**To Reproduce**
Compile Env:
 - OS: Windows 11
- Msys2-ucrt64
Compile Cmds:
```
export PATH="/c/Program Files (x86)/Inno Setup 6":$PATH
git clone https://github.com/TigerVNC/tigervnc.git
cd tigervnc
mkdir build
cd build
cmake -G "MinGW Makefiles" -DBUILD_STATIC=ON ../
mingw32-make.exe
mingw32-make.exe installer
```

**Screenshots**
![image](https://github.com/TigerVNC/tigervnc/assets/78312508/11e0a3da-c511-45ae-860b-021132e21239)

**Probably Solution**
```
Source: "C:\msys64\ucrt64\bin\libffi-8.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
Source: "C:\msys64\ucrt64\bin\libp11-kit-0.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
Source: "C:\msys64\ucrt64\bin\libunistring-5.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
Source: "C:\msys64\ucrt64\bin\libintl-8.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
Source: "C:\msys64\ucrt64\bin\libiconv-2.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace;
```
I added the above lines to the `[Setup]` section in the `tigervnc\release\tigervnc.iss.in` file to ensure Inno Setup packages these necessary DLLs. After rebuilding, I can install and use the application normally.

**Comment by CendioOssman** [comment]
I'm afraid the static build option is only a best effort one. If the build environment doesn't contain static libraries, then it cannot produce distributable binaries. In most cases, you'll need to build all dependencies yourself to get static versions of everything.
