### ISSUE TITLE
Missing option for resizing the remote session in options

### ISSUE THREAD

**Issue by Blackclaws** [TigerVNC/tigervnc#1780]
**Describe the bug**
The remote resizing feature cannot be disabled. I have a user who wishes to use the session on a different screen but have scrollbars instead of the window auto resizing. The option seems to not exist anymore. The option in the F8 menu is also not a checkbox and also does nothing when clicked. The resolution always resizes to fit the window size.
**To Reproduce**
1. Start TigerVnc
2. Connect
3. Press F8
4. Press Resize Remote
5. Nothing happens

**Expected behavior**
Toggles Remote Resizing behavior

**Client (please complete the following information):**
 - OS: Windows 11/Arch Linux
 - VNC client: TigerVNC
 - VNC client version: v1.13.1
 - Client downloaded from: Sourceforge/Arch Distro

**Server (please complete the following information):**
 - OS: CentOS
 - VNC server: TigerVNC

**Additional context**
It seems this option existed before under a screen tab but I cannot find this anymore in the recent versions. I understand that autoscaling is usually the preferred behavior but there are cases where you want to maintain the original resolution (because windows within should not resize) when switching temporarily (like for a presentation) to a smaller resolution screen.

**Comment by Blackclaws** [comment]
Possibly same issue? https://github.com/TigerVNC/tigervnc/issues/1527

**Comment by CendioOssman** [comment]
Yes, that option was indeed removed from the UI because it was deemed too niche to be worth the clutter.

Could you describe your use case a bit more? The example you state, switching monitors, would behave the same for local applications, so I'm afraid I don't see it as unreasonable that a remote session behaves the same.

**Comment by CendioOssman** [comment]
And to be clear, the setting is still available from the command line. It's just the UI that was removed.

**Comment by hporter3** [comment]
Yet one more vote to add the "Screen" tab back in to the UI. I have been using an older version and so I didn't realize this option had been removed.
The problem I have is that I'm using some CAD software that tends to freak out when the size of the vnc window is resized. The fonts get all messed up and it becomes unusable. The fixed screen size prevents that from happening.
Please consider adding it back.
Thank you

**Comment by CendioOssman** [comment]
I'm afraid that also sounds a bit niche. From our point of view, that would be a workaround for a buggy application that deals poorly with changing monitor resolution. That does not seem like a very TigerVNC specific issue.

Again, the functionality is still available from the command line (or config file/registry), as well as in the server configuration. I don't think what's been mentioned so far motivates moving it to a more prominent location.

So for now, I'm going to go ahead and close this issue.
