### ISSUE TITLE
The Linux server panel is not fully shown and the Windows client's taskbar never disappears.

### ISSUE THREAD

**Issue by dongwon-you** [TigerVNC/tigervnc#1781]
**Describe the bug**
I'm not sure if this is a setting issue or a bug, 
The Linux server panel is not fully shown and the Windows client's taskbar never disappears.

**Screenshots**
![image](https://github.com/TigerVNC/tigervnc/assets/57248072/1d1c221f-72c3-4fbd-92b4-d7aa39cfff7a)

**Expected behavior**
Taskbar shouldn't show up and Linux panels should show correctly.
The image is what it should be.
![image](https://github.com/TigerVNC/tigervnc/assets/57248072/3c3f5277-6075-43af-9c6d-6f36247703f8)

**Client**
 - OS: Windows 10 Enterprise
 - VNC client: TigerVNC
 - VNC client version: TigerVNC 1.13.90
 - Client downloaded from: https://sourceforge.net/projects/tigervnc/

**Server**
 - OS: Rocky Linux 8.9
 - VNC server: TigerVNC
 - VNC server version: TigerVNC 1.13.1
 - Server downloaded from: dnf install tigervnc-server
 - Server was started using: vncserver

**Comment by CendioOssman** [comment]
I'm afraid that is not a known problem. Please share the exact steps required to reproduce the problem.

**Comment by CendioOssman** [comment]
I'm afraid that is not a supported way to start a TigerVNC server. It is not something included with TigerVNC, but rather something Red Hat has added. You'll need to file a bug report with them, or try our supported method:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

That should only be relevant to issue 1, though.

For issue 2, it's not something we see here. So we need to know how you've configured the client and how you are starting it. Have you made any modifications to the Windows task bar? E.g. turning on auto hide?

**Comment by CendioOssman** [comment]
No response. Closing.
