### ISSUE TITLE
"Timer: gettimeofday is broken" error in x0vncserver output

### ISSUE THREAD

**Issue by poppcicle** [TigerVNC/tigervnc#1782]
After the latest commits, I am seeing a lot of messages like this in the output of x0vncserver:
```
Thu Jul 11 04:36:28 2024
 Timer:       gettimeofday is broken...

Thu Jul 11 04:37:00 2024
  Timer:       gettimeofday is broken...

Thu Jul 11 04:37:04 2024
 Timer:       gettimeofday is broken...
 Timer:       gettimeofday is broken...

Thu Jul 11 04:38:10 2024
 Timer:       gettimeofday is broken...
 Timer:       gettimeofday is broken...
 Timer:       gettimeofday is broken...
```
Reverting both https://github.com/TigerVNC/tigervnc/commit/c831c9084afffdf10fa5dda865a6df5d643d83dd and https://github.com/TigerVNC/tigervnc/commit/80ce950887824a120c8de07dac9191e7fff72de4 seems to fix it. Reverting either of the two commits alone did not stop the error; only reverting both did.

**Comment by CendioHalim** [comment]
For me, reverting only https://github.com/TigerVNC/tigervnc/commit/c831c9084afffdf10fa5dda865a6df5d643d83dd was enough to fix it.

Every time the branch that prints the error is reached, the difference between `toWait` and `timeoutMs` is 1:

```
Fri Jul 12 10:25:46 2024
 Timer:       toWait=51, timeoutMs=50
 Timer:       gettimeofday is broken...
 Timer:       toWait=51, timeoutMs=50
 Timer:       gettimeofday is broken...
 Timer:       toWait=51, timeoutMs=50
 Timer:       gettimeofday is broken...
 Timer:       toWait=9, timeoutMs=8
 Timer:       gettimeofday is broken...

Fri Jul 12 10:25:47 2024
 Timer:       toWait=51, timeoutMs=50
 Timer:       gettimeofday is broken...
 Timer:       toWait=51, timeoutMs=50
 Timer:       gettimeofday is broken...
 Timer:       toWait=51, timeoutMs=50
 Timer:       gettimeofday is broken...
 Timer:       toWait=9, timeoutMs=8
 Timer:       gettimeofday is broken...

```

**Comment by poppcicle** [comment]
I compiled again and wasn't able to reproduce with only https://github.com/TigerVNC/tigervnc/commit/c831c9084afffdf10fa5dda865a6df5d643d83dd reverted. Not sure why, but it was probably a mistake I made on my end.

**Comment by CendioOssman** [comment]
The rounding misbehaves when the `tv_usec` calculation is overflowing. I think this should fix it:

```diff
diff --git a/common/rfb/Timer.cxx b/common/rfb/Timer.cxx
index 4654d50c8..4d2231d3f 100644
--- a/common/rfb/Timer.cxx
+++ b/common/rfb/Timer.cxx
@@ -54,7 +54,10 @@ inline static timeval addMillis(timeval inTime, int millis) {
 }
 
 inline static int diffTimeMillis(timeval later, timeval earlier) {
-  return ((later.tv_sec - earlier.tv_sec) * 1000) + ((later.tv_usec - earlier.tv_usec + 999) / 1000);
+  long udiff;
+  udiff = ((later.tv_sec - earlier.tv_sec) * 1000000) +
+          (later.tv_usec - earlier.tv_usec);
+  return (udiff + 999) / 1000;
 }
 
 std::list<Timer*> Timer::pending;
```

**Comment by samhed** [comment]
Indeed, your fix worked well.

Tested with x0vncserver on RHEL 9. Without the patch, I get the same errors seen above when opening Nautilus, for example. With the patch, I don't get any errors.

Committed to master in 422444a.
