### ISSUE TITLE
Is the default reverse connection feasible when booting up?

### ISSUE THREAD

**Issue by worm001** [TigerVNC/tigervnc#1788]
My machine A is running CentOS 7 core without GUI. I have installed the latest version of TigerVNC Server. How can I modify the configuration so that it can connect to my machine B's internal IP address, such as 192.168.0.200 on port 5500, in reverse at startup?

**Comment by CendioOssman** [comment]
Probably. How depends on how you've set up things.

I would suggest starting a discussion in the tigervnc-users group. The issue tracker is better suited for specific bugs or features, rather than usage questions.
