### ISSUE TITLE
Missing comma in the default value of SecurityTypes parameter of vncviewer 1.14.0

### ISSUE THREAD

**Issue by papavlos** [TigerVNC/tigervnc#1789]
The default value for the `SecurityTypes` misses a comma almost at the end, just before `VncAth` type.
This small typo was introduced with the last release when adding new security type `MSLogonII`, the programmer has apparently forgotten to add comma after it.

current `default=X509Plain,TLSPlain,X509Vnc,TLSVnc,X509None,TLSNone,RA2,RA2_256,RA2ne,RA2ne_256,DH,MSLogonIIVncAuth,None`
expected `default=X509Plain,TLSPlain,X509Vnc,TLSVnc,X509None,TLSNone,RA2,RA2_256,RA2ne,RA2ne_256,DH,MSLogonII,VncAuth,None`

This hits everyone wanting to connect to a VNC server configured to use VncAuth with the error _'No matching security types'_.
As the workaround you have to add explicit `-SecurityTypes=VncAuth` when running vncviewer.

**Comment by CendioOssman** [comment]
Oops. Thanks for noticing. Fix in 4f6a3521874da5a67fd746389cfa9b6199eb3582.

**Comment by CendioOssman** [comment]
No definite plans for a bug fix release at the moment, but it is something to consider.

If you open the GUI and change the security settings, it should fix the problem permanently.
