### ISSUE TITLE
Empty config settings for vncserver/vncsession can break service

### ISSUE THREAD

**Issue by CendioOssman** [TigerVNC/tigervnc#1791]
**Describe the bug**
If you specify a setting in one of the vncserver config files, but leave a blank value, then this can for some variables cause the server to fail to start.

**To Reproduce**
1. Enter `rendernode=` in `/etc/tigervnc/vncserver-config-defaults`
2. Start the `vncserver@:#.service`

**Expected behavior**
Server is running with DRI3 disabled.

**Client (please complete the following information):**
N/A

**Server (please complete the following information):**
 - OS: RHEL 9
 - VNC server: TigerVNC
 - VNC server version: 1.14.0
 - Server downloaded from: Sourceforge
 - Server was started using: `sudo systemctl start vncserver@:2.service`

**Additional context**
What happens is that `rendernode=` gets translated to the argument `-rendernode=`, but it should be translated to `-rendernode ""`. The reason this works for some variables is that the `=` form is valid for TigerVNC parameters, but not for Xorg arguments (which `-rendernode` is).

A workaround in this case it to specify some bogus value instead, as that will also disable DRI3.

**Comment by CendioOssman** [comment]
The issue seems to be the regexp in `vncserver`:

```perl
        if (my ($k, $v) = /^\s*(\w+)\s*=\s*(.+)$/) {
```

It requires a non-zero number of characters in the value.

**Comment by LMattsson** [comment]
This should now be fixed.

It was tested by checking the scenario in the issue report, as well as testing that config variables with regular values (e.g. `securitytypes=vncauth`) as well as boolean variables (e.g. `alwaysshared`) still were passed correctly to Xvnc.
