### ISSUE TITLE
How can I build a single executable file for Windows?

### ISSUE THREAD

**Issue by lurenJBD** [TigerVNC/tigervnc#1798]
**Describe the bug**
I tried using MSYS2 to compile a static build, but the resulting executable always prompts for missing DLL files.

I followed the wiki to compile. [Compiling TigerVNC for Windows · TigerVNC/tigervnc Wiki (github.com)](https://github.com/TigerVNC/tigervnc/wiki/Compiling-TigerVNC-for-Windows)

How can I create an installer package like the ones you release on sourceforge.net, Without additional DLL files and a single executable file can run normally?

**To Reproduce**
1. Install [MSYS2](https://www.msys2.org/docs/installer/) and [Inno Setup](https://jrsoftware.org/isdl.php#stable).

> The version of MSYS2 I installed is [`msys2-x86_64-20240507.exe`](https://github.com/msys2/msys2-installer/releases/download/2024-05-07/msys2-x86_64-20240507.exe)
> The version of Inno Setup I installed is [`innosetup-6.3.3.exe`](https://files.jrsoftware.org/is/6/innosetup-6.3.3.exe)

2. Run MSYS2-MinGW64 and set up the build environment.
```
pacman -S mingw-w64-x86_64-toolchain \
    mingw-w64-x86_64-cmake \
    mingw-w64-x86_64-make \
    mingw-w64-x86_64-fltk \
    mingw-w64-x86_64-gnutls \
    mingw-w64-x86_64-libjpeg-turbo \
    mingw-w64-x86_64-zlib \
    mingw-w64-x86_64-pixman \
    git
```
3. Clone the source code using `git clone`.
```
git clone https://github.com/TigerVNC/tigervnc.git && cd tigervnc

# For now, I am using the latest commit. 
# If anyone needs to replicate it, run this code
git reset --hard 4f6a3521874da5a67fd746389cfa9b6199eb3582
```
4. Prepare a build folder
```
mkdir build && cd build
```
5. Run CMake to configure the build.
```
cmake -G "MinGW Makefiles" -DBUILD_STATIC=1 ../ 
```
6. Set the PATH variable. Once set, you can check it using the `env` command, or directly execute `iscc` to see if it produces any errors.
```
export PATH="/C/Program Files (x86)/Inno Setup 6":$PATH
```
7.  Compile the project. You can't just run `mingw32-make.exe installer` alone, you need to run `mingw32-make.exe translations` first, otherwise, you might encounter missing *.mo file errors.
```
mingw32-make.exe translations installer
```
8. Go to the `build/release` directory and copy the `tigervnc64-1.14.80.exe` file from there.

**Expected behavior**
Run `tigervnc64-1.14.80.exe` to install,  after that run `vncviewer.exe` in `C:\Program Files\TigerVNC`

Encounter several errors:
"Unable to continue execution due to the missing `libp11-kit-0.dll`. Reinstalling the program may resolve this issue."
"Unable to continue execution due to the missing `libunistuing-5.dll`. Reinstalling the program may resolve this issue."

**Screenshots**
![ERROR](https://github.com/user-attachments/assets/a901e566-adbc-46c6-aea0-f37945b9c120)

**Client Environment:**
 - OS: Windows 11 23H2
 - VNC client: Not related
 - VNC client version: 1.14.80
 - Client downloaded from: Not related

**Additional context**
Actually, I found a solution. Simply copy the missing DLL files from `C:\msys64\mingw64\bin\`.
I also made modifications to the source code to ensure that these DLL files are included in the installer package.
https://github.com/TigerVNC/tigervnc/commit/478aeb522ed8ba03bd8593a154dfba7eae1169d6

**Comment by CendioOssman** [comment]
Building self contained exe files requires that all required libraries are provided in a static version. I'm afraid general repositories like MSYS2 do not do so.

So to build an exe like we do, you'll need to build all libraries yourself and make sure static versions are included. Or get MSYS2 to include everything that's needed.

Providing build environments is unfortunately out of the scope for this project. So I don't see anything we can fix on our end here.

**Comment by lurenJBD** [comment]
> Building self contained exe files requires that all required libraries are provided in a static version. I'm afraid general repositories like MSYS2 do not do so.
> 
> 
> 
> So to build an exe like we do, you'll need to build all libraries yourself and make sure static versions are included. Or get MSYS2 to include everything that's needed.
> 
> 
> 
> Providing build environments is unfortunately out of the scope for this project. So I don't see anything we can fix on our end here.

Ok, any tips or help to set up an environments building a truly static version.

**Comment by bphinz** [comment]
We use mxe for the windows builds.
