### ISSUE TITLE
runtime option to swap the ctrl and alt modifier keys to better support mac servers

### ISSUE THREAD

**Issue by Osndok** [TigerVNC/tigervnc#18]
I've recently moved my keyboard & mouse from my mac to my linux box, thinking that I could easily control the mac from vnc. Thankfully, I've managed to maintain most keyboard shortcuts because my keyboard has an option to swap the Ctrl & Alt keys (mac mode & pc mode).

One of very few exceptions is when I try and use the mac over vnc, which (unfortunately) changes every keyboard shortcut when looking through the tigervnc portal; and, as you can imagine, it's a bit arduous to overcome years of muscle memory.

The best source of technical information that I could find on the subject is here:
https://www.realvnc.com/products/vnc/documentation/5.0/misc/keyboard-mapping/

I understand that the root cause of this is probably an ancient choice by Apple to be different (or else my keyboard would not try and support them both), and is not any fault, misfeature, or even responsibility of tigervnc. Nonetheless, I have run into this swap option many times from the Apple side, but cannot locate it from the Linux side.

Using Fedora 20, the current version reads:
tigervnc-1.3.0-14.fc20.x86_64
TigerVNC Viewer 64-bit v1.3.0 (20140319)

In this (or any newer) version, are you aware of a way to easily transpose the Ctrl & Alt keys?
##

**Comment by Osndok** [comment]
I've actually tried it with both the "official" Apple VNC server and the only other one I could get to work ("Vine Server"). I also tried RealVNC, but it's server just crashes on startup, and has little to go on in terms of documentation and diagnostic output (not time-effective for me). If you know of any other vnc server for os x, I'm all ears... but since apple has integrated their own I think it has both killed the motivation for it, and/or is "google-washing" any smaller projects.

Anyway... the real reason for this comment was that I find that the above patch is rather hopeless in 1.6.90 ... can you suggest a new/better place to perform this hackish modifier key swap (in the unix-vncviewer code path)?

**Comment by CendioOssman** [comment]
Have a look at `Viewport::handleKeyPress()`. It already has some magic for OS X. You should be able to do something similar.

**Comment by CendioOssman** [comment]
Given #770 it seems a lot of this is bad behaviour in Apple's server. Closing this for now.
