### ISSUE TITLE
3rd party windows server build seems to contain malware.

### ISSUE THREAD

**Issue by Keeper-of-the-Keys** [TigerVNC/tigervnc#1802]
Hey, the windows build linked to from the [documentation](https://github.com/TigerVNC/tigervnc/wiki/Setup-TigerVNC-server-(Windows))  (which I realize fully is unofficial) is marked as containing malware by multiple scanners on virustotal.

While not supported the windows build by a 3rd party should probably not be linked to.

![afbeelding](https://github.com/user-attachments/assets/4f3c843e-ac61-4ccd-a4df-4771fde93501)

**Comment by CendioOssman** [comment]
I'm afraid it is indeed malware. Wikis on GitHub are constantly getting spammed with such links, and GitHub does not seem to care in the slightest.

We remove them as we notice them, but we can only do so much. :/
