### ISSUE TITLE
ubuntu24.04LTS tigervnc 

### ISSUE THREAD

**Issue by MYS0529** [TigerVNC/tigervnc#1803]
1. I saw 1.14.0 had released，but still is 1.13.1 via apt installed
2. Remote desktop is gray or black screen(windows 10 remote ubuntu 24.04 via VNC viewer)
3. There is no detail documents to guide how to configure vnc
thanks

**Comment by MYS0529** [comment]
the OS ubuntu24.04 is new installed, after consulting the information, I learned that OS should use X11 rather wayland window manager.
Should I install gnome-panel or others?

**Comment by MYS0529** [comment]
![Capture](https://github.com/user-attachments/assets/75c1d1f7-8aa5-4640-9803-8a9e8ed1e015)

**Comment by CendioOssman** [comment]
Please fill out the bug report template so we can better understand your issue.

**Comment by MYS0529** [comment]
Client:
    windows10 VNC viewer

Server:
    OS:ubuntu 24.040LTS
    username:mys
    server:TigerVnc 1.13.1

Server  config:
    1. /etc/tigervnc/vncserver-config-defaults
            $session='ubuntu';
             $geometry='1920x1080';
            $localhost='no';
    2. /etc/tigervnc/vncserver-config-mandatory
            $AlwaysShared='yes';
    3. /etc/tigervnc/vncserver.users
            :1=mys
    4. sudo systemctl daemon-reload
    5. sudo systemctl enable tigervncserver@:1.service

**Comment by MYS0529** [comment]
Hi, the issue is remote desktop is gray or black screen, show as picture.

**Comment by MYS0529** [comment]
[honor2.log](https://github.com/user-attachments/files/16508694/honor2.log)
[honor 2.log](https://github.com/user-attachments/files/16508695/honor.2.log)

**Comment by CendioOssman** [comment]
I'm afraid that is Ubuntu's packaging of TigerVNC, and they don't use our implementation of starting session. That means we don't have the expertise to help you.

Please try our Ubuntu packages instead. Or file a bug with Ubuntu and see if they can help you out.

**Comment by MYS0529** [comment]
ok, I'll try download from Official release.
My demand is win10 remote ubuntu 24.04 desktop( sharing windows,)
I wan't know there is a detail document to configure tigerVNC

**Comment by CendioOssman** [comment]
We have a HOWTO to get started as part of the packaging:

https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md

**Comment by MYS0529** [comment]
I can use x0vncserver to emote and interact with real X displays (i.e. a display corresponding to a physical monitor, keyboard, and mouse)
But I can't copy/paste between server and client, does x0vncserver support this feature?
If yes, how to configure?
thanks

**Comment by CendioOssman** [comment]
No, I'm afraid it does not. Please see #529.

**Comment by MYS0529** [comment]
OK, maybe look up a feature
