### ISSUE TITLE
vnc viewer keeps black until moving or dragging the viewer window

### ISSUE THREAD

**Issue by chiefliu** [TigerVNC/tigervnc#1805]
**Describe the bug**

**TigerVnc version :** 
![image](https://github.com/user-attachments/assets/d523c013-8c7a-4837-9772-77219961604a)
![image](https://github.com/user-attachments/assets/81d55980-0a1d-46a1-9c35-2184b6e6470f)

I tried two versions fo TigerVnc. When i use tigervnc  on **windows10 LTSC** to connect an Linux based on ubuntu and try to start an app  
when the desktop is started . An **turbovnc server （v3.0.3）** is running on the  linux，when connected the command line is on the linux :

/opt/TurboVNC/bin/Xvnc :1 -desktop TurboVNC: appbox:1 (root) -auth /root/.Xauthority -geometry 1240x900 -depth 24 -rfbwait 120000 -x509cert /root/.vnc/x509_cert.pem -x509key /root/.vn/x509_private.pem -securitytypes none -rfbport 30009 -fp catalogue:/etc/X11/fontpath.d -deferupdate 1 -dridir /usr/lib64/dri -registrydir /usr/lib64/xorg -nocursor -noclipboardrecv -noclipboardsend

**It seems that the connection is successfully built,but the tigervnc windows keeps black:**

![image](https://github.com/user-attachments/assets/5f9839d2-27da-4e22-8a8f-dfe51ddafce9)

**if i move the tigervnc windows(such as drag the window，min size the max size)，it displays normally:**

![image](https://github.com/user-attachments/assets/834f76fb-38be-4f3e-9f87-8cced0cc1bc7)

I'm not sure if this is an tigervnc bug or just some compatibility problems.  Can you provide some solutions for troubleshooting this issue?  

Client:
tigernvc  1.14.80
windows10 LTSC
windows dpi  1920*1080

server:
TurboVnc 3.0.3

Thank you ~

**Comment by chiefliu** [comment]
I use RealVNC 7.10, it works well

**Comment by CendioOssman** [comment]
To clarify, is it sufficient to just move the client window? Or do you need to resize it?

**Comment by chiefliu** [comment]
> To clarify, is it sufficient to just move the client window? Or do you need to resize it?

I just make a test, i just moved the window, but the window size is changed. and  if i minimize the window and then restore it. It comes to work normally either.

so I  think i does not rely on resize?

**Comment by chiefliu** [comment]
I also found that  the vnc viewer has a lot of  white areas around the black area  before i move it :
![image](https://github.com/user-attachments/assets/43da7071-6ebc-413c-8975-d1afb579081d)

After i move the window, the white areas are disappeared:
![image](https://github.com/user-attachments/assets/e8147626-58e6-42d4-ab04-61d895711c34)

**Comment by CendioOssman** [comment]
Did you use our builds for TigerVNC 1.14.80 and 1.3.1? Or did you build them yourself?

**Comment by chiefliu** [comment]
I use your builds, i didn't build it .

**Comment by chiefliu** [comment]
It works well in most cases except on  windows10  LTSC

**Comment by CendioOssman** [comment]
I'm afraid that makes it almost impossible for us to debug and fix. :/

Does it work from that client to a TigerVNC server?

**Comment by chiefliu** [comment]
I did not do that test, I consider if this is a  compatibility problem : when the vnc viewer is launched, the window size is not adjust correctly and may stuck  the vnc viewer's  display ? (As my previous screenshots, the vnc viewer window seems  abnormal: there is a lot of white blank area)

**Comment by CendioOssman** [comment]
At this point it is difficult to state if that area comes from the client or the server. Hence why it would be very helpful if you can test with a different server.

**Comment by noarche** [comment]
Mine stays black the whole session.

**Comment by CendioOssman** [comment]
@noarche, if you are not using Windows 10 LTSC then I don't think you have the same issue.

@chiefliu, please set up a test with TigerVNC as the server. That's the best way forward I can see.

**Comment by CendioOssman** [comment]
No response. Closing.
