### ISSUE TITLE
Exception on worker thread: ZRLE decode error

### ISSUE THREAD

**Issue by stevefalco** [TigerVNC/tigervnc#1809]
**Describe the bug**
tigervnc 1.14.0 on Fedora 40 won't connect to an RPi running bookworm.  It gets an error:

Exception on worker thread: ZRLE decode error

I downgraded to 1.13.1 and the problem went away. I tried setting the encoding to raw (I also tried hextile) but I still got a ZRLE error:

```
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Exception on worker thread: ZRLE decode error
 DecodeManager:     raw: 37 rects, 4.14806 Mpixels
 DecodeManager:          15.824 MiB (1:1 ratio)
 DecodeManager:     ZRLE: 1 rects, 315 pixels
 DecodeManager:           707 B (1:1.79915 ratio)
 DecodeManager:   Total: 38 rects, 4.14838 Mpixels
 DecodeManager:          15.8247 MiB (1:1.00003 ratio)
```

**To Reproduce**
1. Attempt to connect to an RPi running bookworm using tigervnc-1.14.0
2. Observe error

**Expected behavior**
No error

**Screenshots**
![Screenshot_20240816_110851](https://github.com/user-attachments/assets/98d87942-0fe2-45a0-a085-2d7a31c22767)

**Client (please complete the following information):**
 - OS: Fedora 40 x86_64
 - VNC client: tigervnc 
 - VNC client version: 1.14.0
 - Client downloaded from: github tigervnc releases

**Server (please complete the following information):**
 - OS: Raspberry Pi Bookworm
 - VNC server: RealVNC
 - VNC server version: 7.11.0 (r18) ARMv8-A (Apr 22 2024 15.20.33)
 - Server downloaded from: part of RPI bookworm standard packages
 - Server was started using: /usr/bin/vncserver-x11-serviced -fg

**Additional context**
I tried both the official package for Fedora as well as building from the tar file and the behavior is consistent: 1.14.0 throws the ZRLE error while 1.13.1 works fine.

**Comment by CendioOssman** [comment]
Thanks. Would you mind trying a `git bisect` to help us pinpoint where this broke? I would suspect baca73d03217a1c219d9c4f024ffcd39f85fd322.

**Comment by stevefalco** [comment]
I ran a bisect and indeed baca73d0321 is the bad commit.

Please let me know if you have a proposed fix that you'd like me to test.

**Comment by CendioOssman** [comment]
I'm not seeing the issue when using the TigerVNC server, so I need to set up a RealVNC server to test with.

If you'd like, you could try adding more debug lines to the ZRLE decoder and pinpoint where things go amiss.

**Comment by stevefalco** [comment]
Ok, I see that there are three places where the ZRLEDecoder.cxx code can emit that error so I added some code.

The error is coming from the "palette RLE" path, where I see that "end - ptr" is 34 and len is 244, so I guess that the available data are less than the expected size, or perhaps something is being parsed incorrectly leading up to this.

I don't know what else I might be able to dump, as I am not at all familiar with this code.

**Comment by CendioOssman** [comment]
Do you think you could get a tcpdump .pcap file of the error? That could allow us to do a deeper analysis.

**Comment by stevefalco** [comment]
I ran a wireshark capture - please let me know if this is what you need:

[fault.zip](https://github.com/user-attachments/files/16730164/fault.zip)

**Comment by stevefalco** [comment]
I should add that 192.168.0.12 is my Linux desktop and 192.168.0.125 is the Raspberry Pi RealVNC server.

**Comment by CendioOssman** [comment]
Thanks. I'll try to have a look at it next week.

**Comment by CendioOssman** [comment]
I think I have an idea of what might be wrong. Could you test this patch:

```diff
diff --git a/common/rfb/ZRLEDecoder.cxx b/common/rfb/ZRLEDecoder.cxx
index 474fd6ca1..e274a697a 100644
--- a/common/rfb/ZRLEDecoder.cxx
+++ b/common/rfb/ZRLEDecoder.cxx
@@ -125,10 +125,10 @@ void ZRLEDecoder::zrleDecode(const Rect& r, rdr::InStream* is,
   Pixel maxPixel = pf.pixelFromRGB((uint16_t)-1, (uint16_t)-1, (uint16_t)-1);
   bool fitsInLS3Bytes = maxPixel < (1<<24);
   bool fitsInMS3Bytes = (maxPixel & 0xff) == 0;
-  bool isLowCPixel = (sizeof(T) == 4) &&
+  bool isLowCPixel = (sizeof(T) == 4) && (pf.depth <= 24) &&
                      ((fitsInLS3Bytes && pf.isLittleEndian()) ||
                       (fitsInMS3Bytes && pf.isBigEndian()));
-  bool isHighCPixel = (sizeof(T) == 4) &&
+  bool isHighCPixel = (sizeof(T) == 4) && (pf.depth <= 24) &&
                       ((fitsInLS3Bytes && pf.isBigEndian()) ||
                        (fitsInMS3Bytes && pf.isLittleEndian()));
 
```

**Comment by kwhite-uottawa** [comment]
Thanks! This fixes the problem for me.  It also fixes the problem of the cursor of the remote Raspberry Pi RealVNC server not being displayed.

**Comment by stevefalco** [comment]
Your patch fixes the problem for me.  I can now connect to my Raspberry Pi.

I'll mention this on the Fedora bug report too.

Thanks!

**Comment by grulja** [comment]
> I'll mention this on the Fedora bug report too.
 
I've been watching the issue here, but thanks for mirroring this to Fedora. I'll backport the fix once I'm back from vacation.

**Comment by CendioOssman** [comment]
Thanks for testing! Applied as 6d9017eeb364491cf2acdf1c7e61aee8dd198527.
