### ISSUE TITLE
When running in a winpe environment, there is a high probability that the following error will occur: Exception processing message 0xc0000005-unexpected parameters

### ISSUE THREAD

**Issue by duddy-j** [TigerVNC/tigervnc#1812]
TigerVNC is the coolest VNC server software I've ever seen, it can be very friendly and supports IPv6, thank you very much to the author.I recently had a very tricky problem,when running in a winpe environment, there is a high probability that the following error will occur: Exception processing message 0xc0000005-unexpected parameters. If you kill winvnc4.exe process in Task Manager, it is likely that it will not open normally, but it will only show that there are processes in Task Manager, but no interface will appear.

**Comment by CendioOssman** [comment]
Thank you for your report. But please fill out the bug template you got when opening this issue, as it helps us better understand your setup.

**Comment by duddy-j** [comment]
Thank you for your reply, sorry, I'm not sure what information to provide to help locate the issue. I add the following information:
1, The kernel version of Winpe is 10.0.19045.3803 and the TigerVNC version is 1.13.90
2. After I installed Tigernvc, I did a portable process, only kept the three files of winvnc4.exe, vncconfig.exe, and wm_hooks.dll, and set the boot winvnc.exe to use as a VNC server.
3. The key export information of the registry is as follows:
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\TigerVNC\WinVNC4]
"Password"=hex:39,4b,fb,6f,4d,f7,57,c5
"SecurityTypes"="VeNCrypt,TLSVnc,VncAuth"
"QueryConnect"=dword:00000000
"QueryOnlyIfLoggedOn"=dword:00000000
"PortNumber"=dword:0000170d
"IdleTimeout"=dword:00000000
"HTTPPortNumber"=dword:00000000
"LocalHost"=dword:00000000
"Hosts"="+,"
"AcceptKeyEvents"=dword:00000001
"AcceptPointerEvents"=dword:00000001
"AcceptCutText"=dword:00000001
"SendCutText"=dword:00000001
"DisableLocalInputs"=dword:00000000
"DisconnectClients"=dword:00000001
"AlwaysShared"=dword:00000000
"NeverShared"=dword:00000000
"DisconnectAction"="None"
"RemoveWallpaper"=dword:00000000
"RemovePattern"=dword:00000000
"DisableEffects"=dword:00000000
"PollConsoleWindows"=dword:00000001
"UseCaptureBlt"=dword:00000000
"UseHooks"=dword:00000000
"Protocol3.3"=dword:00000000

**Comment by duddy-j** [comment]
> Thank you for your report. But please fill out the bug template you got when opening this issue, as it helps us better understand your setup.

Thank you for your reply, sorry, I'm not sure what information to provide to help locate the issue. I add the following information:
1, The kernel version of Winpe is 10.0.19045.3803 and the TigerVNC version is 1.13.90
2. After I installed Tigernvc, I did a portable process, only kept the three files of winvnc4.exe, vncconfig.exe, and wm_hooks.dll, and set the boot winvnc.exe to use as a VNC server.
3. The key export information of the registry is as follows:
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\TigerVNC\WinVNC4]
"Password"=hex:39,4b,fb,6f,4d,f7,57,c5
"SecurityTypes"="VeNCrypt,TLSVnc,VncAuth"
"QueryConnect"=dword:00000000
"QueryOnlyIfLoggedOn"=dword:00000000
"PortNumber"=dword:0000170d
"IdleTimeout"=dword:00000000
"HTTPPortNumber"=dword:00000000
"LocalHost"=dword:00000000
"Hosts"="+,"
"AcceptKeyEvents"=dword:00000001
"AcceptPointerEvents"=dword:00000001
"AcceptCutText"=dword:00000001
"SendCutText"=dword:00000001
"DisableLocalInputs"=dword:00000000
"DisconnectClients"=dword:00000001
"AlwaysShared"=dword:00000000
"NeverShared"=dword:00000000
"DisconnectAction"="None"
"RemoveWallpaper"=dword:00000000
"RemovePattern"=dword:00000000
"DisableEffects"=dword:00000000
"PollConsoleWindows"=dword:00000001
"UseCaptureBlt"=dword:00000000
"UseHooks"=dword:00000000
"Protocol3.3"=dword:00000000

**Comment by CendioOssman** [comment]
There was a template in the description input field that you removed when you created this issue.

If you click new issue and then the bug report button, you'll get an input box with the template again. Please copy that over here and fill out the details.

Please also include a screenshot of the crash.

**Comment by CendioOssman** [comment]
No response. Closing.
