### ISSUE TITLE
Some valid server addresses are not accepted when using -via

### ISSUE THREAD

**Issue by LMattsson** [TigerVNC/tigervnc#1815]
**Describe the bug**
When doing a regular login (i.e. not using `-via`), the following server addresses are allowed in the **VNC server** input field:
```
<host>:<port>
<host>::<port>
<host>:<display>
```

When using `-via` with  `<host>::<port>` or `<host>:<display>`, I can log in without any issues. However, using `-via` with `<host>:<port>` is not possible and the error message below is shown:
```
The connection was dropped by the server before the session could be established.

Attempt to reconnect?
```

**To Reproduce**
1. Run `vncviewer -via <host>`
2. Input e.g. `localhost:5902` in the VNC server field (only one colon)
3. Click connect
4. Enter the password for SSH in the terminal
5. Instead of logging in to TigerVNC, the error message above is shown.

**Expected behavior**
The same server address should work for login regardless if `-via` is used or not.

**Client (please complete the following information):**
 - OS: Fedora 39
 - VNC client: TigerVNC
 - VNC client version: 1.13.1
 - Client downloaded from: my Linux distribution

**Server (please complete the following information):**
 - OS: RHEL 9
 - VNC server: TigerVNC
 - VNC server version: 1.13.1
 - Server downloaded from: my Linux distribution
 - Server was started using: `systemctl start vncserver@:2.service`

**Comment by CendioOssman** [comment]
Fixed in e6d4d3cbb4242d536474f4e8e2262bc5886200db.
