### ISSUE TITLE
The mouse cursor jumps to the upper left corner

### ISSUE THREAD

**Issue by mozo78** [TigerVNC/tigervnc#1816]
**Describe the bug**
The mouse cursor jumps to the upper left corner from time to time when x0vncserver is active and it's very frustrating. The problem does not occure on Wayland.

**To Reproduce**
Just start x0vncserver

**Expected behavior**
Mouse shouldn't move randomly to upper left corner.

**Client (please complete the following information):**
 - OS: Arch Linux
 - VNC client: TigerVNC
 - VNC client version: 1.14.0
 - Client downloaded from: Arch Linux official repositores

**Server (please complete the following information):**
 - VNC client: TigerVNC
 - VNC client version: 1.14.0
 - Client downloaded from: Arch Linux official repositores
 - Server was started using: `x0vncserver -rfbauth ~/.vnc/passwd -display :0`

**Additional context**
I tried to find what triggers it but without success. It seems it's random.

**Comment by CendioOssman** [comment]
Thanks for your report.

How is it you notice the cursor moving? Locally on the server machine? Or from the client?

**Comment by mozo78** [comment]
> Thanks for your report.
> 
> How is it you notice the cursor moving? Locally on the server machine? Or from the client?

Hello,
Thanks for your answer!
Locally. When I enter remotely to my machine, the problem doesn't exists. But when I working on the server (my home machine), the cursor jumps to the upper left corner from time to time. Sometimes very often and sometimes not so often. I can't find a pattern or a reason that triggers it. When I kill vnc and x0vncserver processes, the problem disappears completely.

**Comment by CendioOssman** [comment]
I guess there is no client connected to x0vncserver when these jumps happen?

**Comment by mozo78** [comment]
No, there's not a client connected. I'm using my PC remotely only when I'm not at home and x0vncserver is always on.

**Comment by CendioOssman** [comment]
Okay, I have a theory on when this happens. Did the issue start after upgrading to 1.14.0?

Could you try if this patch helps:

```diff
diff --git a/common/rfb/VNCSConnectionST.cxx b/common/rfb/VNCSConnectionST.cxx
index 88deff8cc..7dc2a0b8c 100644
--- a/common/rfb/VNCSConnectionST.cxx
+++ b/common/rfb/VNCSConnectionST.cxx
@@ -83,9 +83,6 @@ VNCSConnectionST::~VNCSConnectionST()
     vlog.info("closing %s: %s", peerEndpoint.c_str(),
               closeReason.c_str());
 
-  // Release any mouse buttons
-  server->pointerEvent(this, server->getCursorPos(), 0);
-
   // Release any keys the client still had pressed
   while (!pressedKeys.empty()) {
     uint32_t keysym, keycode;
diff --git a/common/rfb/VNCServerST.cxx b/common/rfb/VNCServerST.cxx
index 114ff3477..66b05fae5 100644
--- a/common/rfb/VNCServerST.cxx
+++ b/common/rfb/VNCServerST.cxx
@@ -176,8 +176,11 @@ void VNCServerST::removeSocket(network::Socket* sock) {
   for (ci = clients.begin(); ci != clients.end(); ci++) {
     if ((*ci)->getSock() == sock) {
       // - Remove any references to it
-      if (pointerClient == *ci)
+      if (pointerClient == *ci) {
+        // Release the mouse buttons the client have pressed
+        desktop->pointerEvent(cursorPos, 0);
         pointerClient = nullptr;
+      }
       if (clipboardClient == *ci)
         handleClipboardAnnounce(*ci, false);
       clipboardRequestors.remove(*ci);
```

**Comment by linuxrulezgames** [comment]
Thank you!
I downloaded the tigervnc-master, applied the patch, compiled it and installed it. Is this enough? Is a new version of x0vncserver installed now? If so, I'll need some time to test it.

**Comment by mozo78** [comment]
Thank you!
I downloaded the tigervnc-master, applied the patch, compiled it and installed it. Is this enough? Is a new version of x0vncserver installed now? If so, I'll need some time to test it.

**Comment by CendioOssman** [comment]
Great! Thanks for testing! Committed in 704f9724d8af58314c4fafc8930666bb2be46722.

**Comment by mozo78** [comment]
Thanks for the fix!
