### ISSUE TITLE
        fprintf(stderr, "Could not create VNC config directory: %s\n", strerror(errno));

### ISSUE THREAD

**Issue by kgoldman** [TigerVNC/tigervnc#1819]
**Is your feature request related to a problem? Please describe.**

vncpasswd recently changed. Entering 'vncpasswd' yields 
Could not create VNC config directory: File exists

**Describe the solution you'd like**
The fprintf should output the directory that could not be created and/or the file that exists. This helps the user debug the new file structure.

**Additional context**
Perhaps add %s, configDir.

**Comment by MichaelRiss** [comment]
Stumbling over the same problem. I get this error message if the directory `~/.config/tigervnc` already exists, in this case `vncpasswd` throws the error message and does not create `~/.config/tigervnc/passwd`.
I have to delete the config directory every time.

**Comment by kgoldman** [comment]
That fix did not work for me.  My workaround was to specify the password file name on the command line.

**Comment by CendioOssman** [comment]
Thank you for report. Unfortunately, this is a bug in `vncpasswd` without an obvious workaround. We've already fixed it in 445e0230cf4e939dcc59caf5d5f001c2f7b04da6, but we probably need to also do a bug fix release.

**Comment by kgoldman** [comment]
Separate from the fix, I suggest improving the error message. Printing 'Could not create VNC config directory' without saying what directory was failing inhibits debug.  It could be that protections are wrong, etc. Simply adding %s configDir will help the end user.

**Comment by CendioOssman** [comment]
Sounds reasonable. Added in 9df4f39c77aa66da992c7632d4ad5847e63d9f16.
