### ISSUE TITLE
TigerVNC don't capture modifier keys set on Logitech Options + 

### ISSUE THREAD

**Issue by rudironsonijr** [TigerVNC/tigervnc#1827]
**Describe the bug**
TigerVNC don't capture modifier keys set on Logitech Options + 

**To Reproduce**
1. Set keyboard shortcuts to my MX Master 2S thumb button gestures on Logitech Option+;
2. Open TigerVNC in full screen and configured to pass shortcuts to the remote machine;
3. Try to use the mouse gestures, no modifier key is sent, only the last key is received.

**Expected behavior**
Remote host should receive the modifiers.

**Screenshots**

![CleanShot 2024-09-03 at 17 11 52@2x](https://github.com/user-attachments/assets/f6692322-4a11-4950-80f6-176eb9192783)

![CleanShot 2024-09-03 at 17 16 08@2x](https://github.com/user-attachments/assets/9b519cae-76ff-49e5-9de9-de09f0368baa)

![CleanShot 2024-09-03 at 17 13 58@2x](https://github.com/user-attachments/assets/85bcb170-c011-41d1-b7a2-ea017de7ffa7)

**Client (please complete the following information):**
 - OS: MacOS 15
 - VNC client: TigerVNC
 - VNC client version: 1.14.80
 - Client downloaded from: Happens both on client downloaded form TigerVNC and built on my machine

**Server (please complete the following information):**
 - OS: Arch
 - VNC server: PiKVM
 - VNC server version: 
 - Server downloaded from: 
 - Server was started using: 

**Additional context**

**Comment by rudironsonijr** [comment]
More info:

**CGSSetGlobalHotKeyOperatingMode**

https://stackoverflow.com/a/58012972/16563876

https://github.com/NUIKit/CGSInternal/tree/master

https://forum.qt.io/topic/49253/capturing-alt-tab-event/5

https://fossies.org/linux/SDL2/src/video/cocoa/SDL_cocoakeyboard.m

https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Frontends/VirtualBox/src/platform/darwin/DarwinKeyboard.cpp

http://git.ithinksw.org/~jspiros/WindowBlur.git/blob/HEAD:/CGSInternal/CGSHotKeys.h

**Comment by rudironsonijr** [comment]
https://discourse.libsdl.org/t/sdl-cocoa-add-keyboard-grab-support/32323

**Comment by rudironsonijr** [comment]
https://github.com/libsdl-org/SDL/blob/main/src/video/cocoa/SDL_cocoakeyboard.m

**Comment by CendioOssman** [comment]
We only respond to keyboard events, so if Logitech is doing something magical, then it might not be compatible.

Could you try enabling debug logging and see if you get any log lines when you use the gestures:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs#os-x

It would also be interesting to see how other applications behave. Please try the following page in a browser and use the gestures with the input box focused:

https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html

**Comment by CendioOssman** [comment]
No response. Closing.
