### ISSUE TITLE
TigerVNC Authentication 

### ISSUE THREAD

**Issue by AdyaAgarwal** [TigerVNC/tigervnc#1832]
Bugs/Questions 

1. How do I disable sudo authentication for TigerVNC on my server (Red Hat Enterprise Linux 9.4 (Plow))?
2. How do I gain access to my account after changing the default_rules settings in Polkit-1? 

**Context**:

Sudo authentication is required when starting a session with VNC. Lab members cannot start a session, since they do not have sudo privileges. I was able to create service files for all users with definite display numbers. I added the following code 

"SecurityTypes = None;" and then I also added display numbers to the service file. 

I was expecting to disable sudo authentication, but that did not happen. I was prompted to enter authenticate using my account information. Initially, I was able to authenticate. However, I ran into an error on my second try. 

![AlternativeAuthenticationforVNC](https://github.com/user-attachments/assets/ce8384f3-f899-4a67-a318-3e3dbc103eea)
 
I keep receiving this error:  **polkit-agent-helper-1: pam_authenticate failed: Authentication failure** 

![TigerVNCAuthenticationError](https://github.com/user-attachments/assets/1d34fb86-a4dc-406b-a9fb-0792f957876c)

As you can see, I received the **polkit-agent-helper-1: pam_authenticate failed: Authentication failure** error here as well.

To combat this, I made the following changes to the Default_Rules file in the following path: /etc/polkit-1/rules.d/default_rules

polkit.addRule(function(action, subject) {
    if (subject.isInGroup("users")) {
        return polkit.Result.YES;
    }
});

However, I am unable to access my default rules file after this. 

<img width="534" alt="Polkit-1_Authentication_Error" src="https://github.com/user-attachments/assets/c16d825b-c734-4dfe-a70c-c754b101847a">

**How can I regain my access?**

**Comment by CendioOssman** [comment]
I'm afraid this is more a question about your distribution, than TigerVNC, so we are not the experts here. But I would suggest looking if you can configure very specific sudo rules, possibly with a helper script that enforces the right policy. Or exploring what can be done with PolKit more.

Creating user sessions is a privileged operation, so some system will unfortunately need to be in place to give normal users that access.

I'm afraid we can't help you with your second question. I don't know polkit in enough detail for that. I would suggest using normal sudo and restore the configuration file you modified.
