### ISSUE TITLE
Indication text in windows task bar

### ISSUE THREAD

**Issue by Benjamin-agrikomp** [TigerVNC/tigervnc#1834]
When I have many Tiger-VNC windows open I cannot see which one belongs to which customer.

In the windows task bar instead of "nobody's X11 desktop (akPlant:2) - TigerVNC" or "X11 - TigerVNC" I would like to see the IP address + port as the first left part.

**Comment by CendioOssman** [comment]
That description is usually controllable in the server. E.g. TigerVNC's Xvnc can change it using vncconfig. We even default to include the hostname and port, so users rarely have to change it.

What server are you using? And how are you starting it? There is a form to fill out for new issues that you seem to have removed.

**Comment by Benjamin-agrikomp** [comment]
I use the Xorg-x11-Xvnc on a SUSE Linux Enterprise Server 11 (x86_64) and TigerVNC Viewer 64-bit v1.9.80.
The computers which host the server all have the same local IP address (192.168.222.3) but I access them via VPN. So the information about IP / Port is in the TigerVNC viewer's configuration file, for example ServerName=10.32.45.3:5903

**Comment by CendioOssman** [comment]
It sounds like you should be able to specify `-desktop` on those servers to give you a different identifier for each system.
