### ISSUE TITLE
Low FPS with KDE6/X11

### ISSUE THREAD

**Issue by MauroOrlic** [TigerVNC/tigervnc#1836]
**Describe the bug**
After a recent update from KDE5 to KDE6 the system has been extremely laggy (low FPS, bad responsiveness) when logging in via TigerVNC.

**To Reproduce**
1. Install Arch linux with full KDE6 suite
2. Install TigerVNC server with ~/.config/tigervnc/config having session=plasmax11
3. enable vncserver@:1.service, disable sddm.service, reboot
4. login to machine via TigerVNC client

**Expected behavior**
Non-laggy user experience as it was in KDE5 (much better FPS and responsiveness).

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: Windows 10
 - VNC client: TigerVNC
 - VNC client version: 1.14.0
 - Client downloaded from: Sourceforge

**Server (please complete the following information):**
 - OS: Arch linux
 - VNC server:TigerVNC
 - VNC server version: 1.14.0
 - Server downloaded from: my Linux distribution
 - Server was started using: systemctl enable vncserver@:1.service

**Additional context**
Also created another fresh install of Arch linux with KDE6/X11 and TigerVNC on another machine, exact same issue. When using ThinLinc instead, no issues is present. Same goes when disabling vncserver service and logging in to the machine directly via SDDM. I am only 99% sure this is related to KDE6 since the issue appeared when I first upgraded from KDE 5 to 6.

**Comment by CendioOssman** [comment]
Could you test with TigerVNC 1.13.1 on the server? KDE 6 might not be working well with the new GPU acceleration we have in TigerVNC 1.14.0.

**Comment by CendioOssman** [comment]
Great. You can disable the new GPU stuff in 1.14.0 by adding `rendernode=foobar` to your vncserver config. Could you check if that also solves the issue?

**Comment by MauroOrlic** [comment]
I have `rendernode=foobar` to `~/.vnc/config` on my optiplex machine, as well as to `~/.vnc/config` and `~/.config/tigervnc/config` on my laptop. After a reboot the issue is fixed on both machines.

**Comment by MauroOrlic** [comment]
Looks like this also fixed another, separate issue where my Slack application specifically had inverted colors (yellow likes became cyan for example), other applications are fine.

**Comment by CendioOssman** [comment]
> I have added `rendernode=foobar` to `~/.vnc/config` on my optiplex machine, as well as to `~/.vnc/config` and `~/.config/tigervnc/config` on my laptop. After a reboot the issue is fixed on both machines.

Great. Thanks for testing!

> Looks like this also fixed another, separate issue where my Slack application specifically had inverted colors (yellow likes became cyan for example), other applications are fine.

That is more concerning as it sounds like a GPU driver bug somewhere. But, this is for somewhat old hardware. So I'm not sure how interested the driver developers are. :/
