### ISSUE TITLE
Temporarily stop capturing keyboard input in full screen mode

### ISSUE THREAD

**Issue by fxzxmicah** [TigerVNC/tigervnc#1837]
**Is your feature request related to a problem? Please describe.**
none.

**Describe the solution you'd like**
If the menu key is pressed, the menu will pop up, at which time the keyboard input is released (stop capturing keyboard input so that the user can use the keyboard to operate the host). When the menu exits, the capture of keyboard input resumes.

**Describe alternatives you've considered**
none.

**Additional context**
On gnome wayland, if the menu is open, the menu will appear in all workspaces, which is not expected.

**Comment by CendioOssman** [comment]
Thank you for your suggestion. We have #2 for easier way to toggle the keyboard grab, so let's keep the discussion there.

> On gnome wayland, if the menu is open, the menu will appear in all workspaces, which is not expected.

I'm afraid this is a bug in GNOME. Please report the issue to GNOME, or to your distribution.

**Comment by fxzxmicah** [comment]
10 years ago? It seems that you really don't like this suggestion.
