### ISSUE TITLE
No matching security types

### ISSUE THREAD

**Issue by tshepardd** [TigerVNC/tigervnc#184]
Hello, 
I am attempting to connect from windows 7 to a VNC server running on scientific linux 7.1 through tigerVNC, and after having the rest of the set up going well, I am receiving an issue on all computers I am attempting to connect from. All computers have tigerVNC installed on them. Thanks in advanced for your help! Side note, I should also mention that the VNC server has been started through the terminal command.

**Comment by CendioOssman** [comment]
The error message means that the client and server couldn't agree on a way to authenticate the client.

How have you set up and configured the VNC server?

**Comment by CendioOssman** [comment]
No response. Closing.
