### ISSUE TITLE
TigerVNC Securitytype doesnot support

### ISSUE THREAD

**Issue by lasag-2511** [TigerVNC/tigervnc#1841]
Hi,

Configured tigervnc users under /etc/tigervnc/tigervnc.users
/etc/tigervnc/tigervnc-config-mandatory
SecurityTypes=TLSPlain 
PlainUsers=%u

With TLSPlain, I get authentication error if I pass none or TLSvnc it works.

``
 SConnection: AuthFailureException: Authentication failure: invalid password or
              username
 VNCSConnST:  closing 10.149.171.125::54821: Authentication failure: invalid
              password or username
``

**Comment by CendioOssman** [comment]
You already have a discussion in the discussion group. Please don't create duplicate issues here.

**Comment by lasag-2511** [comment]
@CendioOssman : Unfortunately, I am not getting any solution or replies there in the discussion group.
