### ISSUE TITLE
Fractional scaling does not work in VNC remote desktop

### ISSUE THREAD

**Issue by Heng-Zhou** [TigerVNC/tigervnc#1848]
**Describe the bug**
In VNC remote desktop, if I set scaling to a fractional scale (say 125%), the resulting scale is always an integer scale (say 200%). Fractional scaling works fine if l operate locally, so I consider it a bug of tigervnc and request a fix.

**To Reproduce**
1. Start VNC remote desktop according to directions in tigervnc's official [HOWTO](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md) document (so I did not do anything special). Connect it to show the Ubuntu desktop.
2. Display Settings -> Enable 'Fractional Scaling' -> Select a non-integer scale, say 125% -> Apply.

**Expected behavior**
Can change to the specified fractional scale in VNC remote desktop as when I operate locally.

**Screenshots**
![image](https://github.com/user-attachments/assets/1c320cfc-e95f-41de-a588-c1564c48d138)

**Client (please complete the following information):**
 - OS: Windows 10 64-bit
 - VNC client: MobaXterm
 - VNC client version: v24.2 Build 5220 (the most latest stable version)
 - Client downloaded from: MobaXterm official website

**Server (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS (the most latest stable version)
 - VNC server: TigerVNC
 - VNC server version: 1.14.0 (the most latest stable version)
 - Server downloaded from: SourceForge
 - Server was started using: `sudo systemctl start vncserver@:x` and `systemctl enable vncserver@:x` according to tigervnc's official [HOWTO](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md) document.

**Additional context**
Contents of `/etc/tigervnc/vncserver-config-defaults`:

> session=ubuntu 
> geometry=3840x2160
> localhost=false
> alwaysshared=true

The fractional scaling works fine if l operate locally. The problem only occurs in VNC remote desktop. Also, the same problem occurs in previous versions of tigervnc like 1.13.0 on Ubuntu 22.04. So the issue has nothing to do with new OS or GNOME and I consider it a long-hidden bug of tigervnc and thus request a fix.

**Comment by CendioOssman** [comment]
I'm afraid that's a limitation in GNOME, not TigerVNC. They don't allow fractional scaling on X11 for some reason. There seems to be some suggestion for workaround here:

https://wiki.archlinux.org/title/HiDPI#Xorg

Please report the issue to GNOME as only they can resolve this.

**Comment by Heng-Zhou** [comment]
@CendioOssman: Disagree. I have said clearly that there is no such a problem when I set fraction scale locally. If GNOME does not allow fractional scaling on X11, then I should not be able to do that both locally and remotely on the same machine. How do you explain I can set fraction scale locally on the same GNOME desktop? The only reasonable explanation is that the bug is in tigervnc, not in GNOME or something else. So, don't push your duty to somewhere else.

**Comment by CendioOssman** [comment]
You are likely using Wayland locally. If I start GNOME with X11 locally here, I can only choose integer scale factors. You can also find numerous links about this is for local sessions, so it is not a TigerVNC specific issue.

**Comment by Heng-Zhou** [comment]
@CendioOssman: Disagree. I have double checked that I am using X11. Below is the screenshot. The information of Windowing System remains the same both locally or remotely -- X11. I can choose fractional scale without problem if I operate locally. The second screenshot below shows that I have successfully applied 125% fractional scale. Again, it's a bug of tigervnc. Don't push your duty to somewhere else; that's rude, unprofessional and cowardly.

The screenshot below shows that I am using X11, not Wayland:
![image](https://github.com/user-attachments/assets/284aced2-515f-4e4a-b707-d0a0b815761e)

The screenshot below shows that I can successfully set fractional scale locally:
![image](https://github.com/user-attachments/assets/b41f0fdd-c542-481c-b49c-fe35010c1086)

**Comment by bphinz** [comment]
> Don't push your duty to somewhere else; that's rude, unprofessional and cowardly.

"Duty"??  You have a grave misunderstanding of how open source software development works.  And you lecturing anyone else on being rude is rich to say the least.  Please don't reply or file any further bug tickets.

**Comment by Heng-Zhou** [comment]
@bphinz: Maybe I don't understanding open source, but it is obvious that you and some other people in this thread don't understand what "shame" is for a software developer Leave a bug for so long and refuse to admit it even if it is spot out, not to mention fix it. Shame on you!
