### ISSUE TITLE
Fractional scaling does not work in VNC remote desktop - Reopen

### ISSUE THREAD

**Issue by Heng-Zhou** [TigerVNC/tigervnc#1849]
**Describe the bug**
In VNC remote desktop, if I set scaling to a fractional scale (say 125%), the resulting scale is always an integer scale (say 200%). Fractional scaling works fine if l operate locally, so I consider it a bug of tigervnc and request a fix.

**To Reproduce**
1. Start VNC remote desktop according to directions in tigervnc's official [HOWTO](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md) document (so I did not do anything special). Connect it to show the Ubuntu desktop.
2. Display Settings -> Enable 'Fractional Scaling' -> Select a non-integer scale, say 125% -> Apply.

**Expected behavior**
Can change to the specified fractional scale in VNC remote desktop as when I operate locally.

**Screenshots**
![image](https://github.com/user-attachments/assets/1c320cfc-e95f-41de-a588-c1564c48d138)

**Client (please complete the following information):**
 - OS: Windows 10 64-bit
 - VNC client: MobaXterm
 - VNC client version: v24.2 Build 5220 (the most latest stable version)
 - Client downloaded from: MobaXterm official website

**Server (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS (the most latest stable version)
 - VNC server: TigerVNC
 - VNC server version: 1.14.0 (the most latest stable version)
 - Server downloaded from: SourceForge
 - Server was started using: `sudo systemctl start vncserver@:x` and `systemctl enable vncserver@:x` according to tigervnc's official [HOWTO](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md) document.

**Additional context**
To those who can't help to push aside your own duties to other people: I have said clearly that there is no such a problem when I set fraction scale locally. If GNOME does not allow fractional scaling on X11, then I should not be able to do that both locally and remotely on the same machine. How do you explain I can set fraction scale locally on the same GNOME desktop? The only reasonable explanation is that the bug is in tigervnc, not in GNOME or something else. So, don't push your duty to somewhere else.

**Comment by CendioOssman** [comment]
Please don't open duplicate issues just because you disagree with the result. That's a quick way to earn a ban.
