### ISSUE TITLE
Can not run program on virtual desktop

### ISSUE THREAD

**Issue by dkandrov** [TigerVNC/tigervnc#186]
I launch vncserver with command:
```
vncserver -geometry 1024x768 -depth 16 :2
```

When I start `xterm` with exporting `DISPLAY=:2`, all working. But when I exporting `DISPLAY=127.0.0.1:2` or when set real ip I am getting error:
```
$ export DISPLAY=127.0.0.1:2
$ xterm 
xterm: Xt error: Can't open display: 127.0.0.1:2
```
There are no any messages in `.vnc/localhost:2.log` file.
My OS is ArchLinux. Version of TigerVNC is 1.5. Also I don't have firewall.
Server is working:
```
$ netstat -an | grep tcp | grep 590
tcp        0      0 0.0.0.0:5902            0.0.0.0:*               LISTEN     
tcp6       0      0 :::5901                 :::*                    LISTEN     
```
Through vncviever I can connect to my vncserver, but I need launch remote application that show its gui on this virtual display.
Has any ideas what's wrong?

**Comment by hildred** [comment]
It is common practice To minimize exposure by disallowing network access to the X protocol (which has had much criticism for lax security) by adding `-nolisten tcp` to the options passed from vncserver to Xvnc. Your package may have done so. This is normally not a problem as unix sockets work just fine for almost all local and ssh forwarded connections. This is only an issue if you want to display clients from multiple hosts without ssh or for some old clients without support for unix sockets (I have not seen any such client In at least fifteen years but they are rumored to exist).

Your test using netstat does not check for X connectivity which uses 600X ports. the line you wanted to use is `netstat -an | grep tcp | grep -e 590[0-9] -e 600[0-9]` which will list both vnc and X11 tcp sockets (but not unix sockets). It does highlight another oddity in that you seem to be running two vnc servers one of which is only listening on ipv6 and one of which is only listening on ipv4. You can track this down by adding the -p flag to the netstat command (which requires superuser permissions it list tasks run by other users).

**Comment by dkandrov** [comment]
Ok, but how can I use old variant of using VNCserver?
I will try to explain my problem:
We have build server where VNCServer not working properly.
Also we have other server with TigerVNC, that localy working good.
And we automatically perform testing of our GUI application on the build server with using number of vnc servers.
But now this not working :(

How can I launch application on one server but to show it on the other server with VNC and without using SSH?

**Comment by CendioOssman** [comment]
If you want to allow remote X11 connections then you have to add the arguments `-listen tcp`. Note that you'll also have to set up xauth on the other system for it to be allowed to connect. SSH is a much better solution as it does this for you, and securely.

**Comment by chemacc** [comment]
no tenies ni idea
