### ISSUE TITLE
Error in Makefile to compile tigervnc 14.1 on linux

### ISSUE THREAD

**Issue by mhtvnc** [TigerVNC/tigervnc#1860]
tigervnc 14.1:

The compilation of tigervnc doesn't work for me.

The Steps:

cmake
make clean
make
make Xvnc

don't work.

The step 'make clean' delets  at least one file which make doesn't regenerate.
After 'make clean' I miss 'common/network/libnetwork.la'.
This file is generated by cmake!

the build of the Xvnc need this file.

--> compile / build fails

**Comment by CendioOssman** [comment]
Yeah, that the `.la` files aren't regenerated seems to be a bug. But `make clean` should not be a necessary step to build TigerVNC. Can't you just leave that out?

**Comment by CendioOssman** [comment]
Should be fixed in 9f51fcf8a07b53bb0726a988c91ded7799eeb496. Thanks for reporting.
