### ISSUE TITLE
No scale?

### ISSUE THREAD

**Issue by fxzxmicah** [TigerVNC/tigervnc#1862]
**Describe the bug**
`GDK_SCALE` does not enable program scaling.

**To Reproduce**
1. Set `GDK_SCALE=2` and launch the program.

**Expected behavior**
Scaled.

**Screenshots**
![截图 2024-11-03 00-25-26](https://github.com/user-attachments/assets/ec25e2ed-c873-499d-86b6-1604e15302a8)

**Client (please complete the following information):**
 - OS: Fedora 41
 - VNC client: TigerVNC
 - VNC client version: 1.14.1
 - Client downloaded from: my Linux distribution

**Server (please complete the following information):**
 - OS: OpenSUSE
 - VNC server: Wayvnc
 - VNC server version: 0.8.0
 - Server downloaded from: my Linux distribution
 - Server was started using: wayvnc -g

**Additional context**
Wayland-based native vncviewer becoming more and more urgent.

**Comment by CendioOssman** [comment]
Please see #369.

**Comment by fxzxmicah** [comment]
Well, it looks like it's going to be another half-century of unsolvable problems.
