### ISSUE TITLE
tigervnc cursor "cropped" with gnome

### ISSUE THREAD

**Issue by ozbenh** [TigerVNC/tigervnc#1863]
You can reproduce this with Fedora 41. Run the Xvnc server with a gnome session in it, connect with tigervnc client,
and the mouse cursor is often "Cropped" vertically. It depends on the cursor, but for example the "I" cursor used when hovering above text tends to only show the top half.

I did  a bunch of printf'ing around the server. It appears that the bitmap (RGBA mode) is fine all the way. Here's an example
```
 DisplayCursor: NON-NULL w=24 h=24 ARGB=0x55cacbc0f830

 vncext:      vncSetCursorSprite(w=24 h=24)
 XserverDesktop: setCursor(w=24 h=24)
 XserverDesktop: 
 Cursor:      CROP 24/24 hs=11/12
 Cursor:       before -> tl.x=11 tl.y=12 br.x=12 br.y=13
 Cursor:        after-> tl.x=4 tl.y=1 br.x=17 br.y=24
 Cursor:      Cursor crop 13/23
 VNCSConnST:  CNX setCursor()
 VNCSConnST:  CNX client setting cursor
 SMsgWriter:  calling writeSetCursorWithAlphaRect
 SMsgWriter:  Cursor write 13/23
 SMsgWriter:  00010203030202020303020100
 SMsgWriter:  0107fffffcd776d8fcffff0701
 SMsgWriter:  0216fffffffffaffffffff1602
 SMsgWriter:  031afffffdfafffafdffff1a03
 SMsgWriter:  0216485969fdfffd6959481602
 SMsgWriter:  0107161e32ffffff321e160701
 SMsgWriter:  000102071fffffff1f07020100
 SMsgWriter:  000000031cffffff1c03000000
 SMsgWriter:  000000031bffffff1b03000000
 SMsgWriter:  000000031bffffff1b03000000
 SMsgWriter:  000000031bffffff1b03000000
 SMsgWriter:  000000031bffffff1b03000000
 SMsgWriter:  000000031bffffff1b03000000
 SMsgWriter:  000000031bffffff1b03000000
 SMsgWriter:  000000031bffffff1b03000000
 SMsgWriter:  000000031bffffff1b03000000
 SMsgWriter:  000000031cffffff1c03000000
 SMsgWriter:  000102072cfdfffd2c07020100
 SMsgWriter:  0107fffffdfafffafdffff0701
 SMsgWriter:  0216fffffffffbffffffff1602
 SMsgWriter:  031afffffde4a5e5fdffff1a03
 SMsgWriter:  02164858564a3f4a5658481602
 SMsgWriter:  0107161a19161216191a160701
```
This displays the alpha channel.

However, what's ... surprising, is that if I disable cropping by commenting out this line:
```
void Cursor::crop()
{
  Rect busy = Rect(0, 0, width_, height_);
  //busy = busy.intersect(Rect(hotspot_.x, hotspot_.y,
  //                          hotspot_.x+1, hotspot_.y+1));
```
then the cursor on the client is complete.

I haven't yet had a chance to try to debug the situation client-side. I'm open to advice, otherwise I'll spend time later and update this issue.

**Comment by ozbenh** [comment]
Update: it works fine if I use vncviewer unmodified on Fedora 41, in the above failing case, the client was running Ubuntu 24.04. It's starting to look like an fltk problem

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by ozbenh** [comment]
That was a quick close :-) I was away for a few days ... i'll try to test other clients

**Comment by ozbenh** [comment]
Ouch, I didn't see your reply (I think the github notification got spam filtered). I'll try to do more testing.

**Comment by ozbenh** [comment]
I can see the problem with vinagre, remmina but not xtightvncviewer interestingly

**Comment by ozbenh** [comment]
I re-did the tests. With a Fedora 41 client, either X11 or Wayland gnome env, it works fine. With Ubuntu 24.04 LTS (X11) I see the problem with the above clients. Same server in all cases.

**Comment by CendioOssman** [comment]
Is the TigerVNC client installed from Ubuntu's repositories? Could you try the version from our release page? So we can rule out any build issues.

**Comment by ozbenh** [comment]
I'll give that a spin tomorrow

**Comment by ozbenh** [comment]
Same problem, the cursors are cut off using your client. I will try to spend some time during the next few days (or the holidays) to track this down further client-side, maybe through fltk.. it could be something in one of the underlying X libs...

**Comment by CendioOssman** [comment]
Any new insights, @ozbenh?

**Comment by ozbenh** [comment]
Not yet. It's our big  summer holiday here in Australia and I was away the last few weeks. I'm travelling (for work this time) for another couple of weeks, hopefully I'll get back to this early feb.

**Comment by CendioOssman** [comment]
What's the status here?
