### ISSUE TITLE
vncviewer: make width of bump scrolling region customizable

### ISSUE THREAD

**Issue by spectrallypure** [TigerVNC/tigervnc#1877]
**Is your feature request related to a problem? Please describe.**
When the remote session and the local display have very different sizes, bump scrolling in vncviewer prevents proper usage due to the width of the bump regions being too large w.r.t. the size of the local display. As a result, the effective area left for the user to work without unwillingly activating the scrolling is too small, as shown in the snapshot below (inner area of blue rectangle).

**Describe the solution you'd like**
This problem would be solved if vncviewer had an option to change the value of the "EDGE_SCROLL_SIZE" parameter, which currently is a constant hardcoded to 1/16 of the viewport.

**Describe alternatives you've considered**
Changing the "EDGE_SCROLL_SIZE" constant in the vncviewer source code and recompiling. Didn't try it as it goes way beyond my skills.

**Additional context**
My colleagues and I work remotely on servers through VNC connections. Usually we connect from desktops with many large displays, and all our remote applications are tiled and sized nicely for that setup. However, we also need to work sometimes from our laptops, using the same VNC sessions, so we run into the issue described above. Note that we don't want to resize the remote session to the tiny laptop displays, because then the tiling and sizing of the windows of all the applications is messed and we waste precious time restoring them when we reconnect from our desktops (and even if we would resize, the laptop display is just too small for the remote applications interfaces to have any usable sizes). 

![Q6GbyS9](https://github.com/user-attachments/assets/cd22b307-7668-40a1-a3cf-561c8808343f)

**Comment by CendioOssman** [comment]
Thank you for your report.

I'm trying to understand the issue better here, and if it's a bug or a design issue. Are you saying that the example image is representative of your experience? Because that looks like a lot more than 1/16th.

**Comment by spectrallypure** [comment]
Hi Pierre! I believe the problem is that the bump-scroll region is being defined as 1/16th of the remote session display, not the local display. In the example of the snapshot, the remote session is 3 monitors of 27'' each, while the local session is a 14'' laptop. I think that is why the bump scroll regions are ridiculously wide w.r.t. the usable area in the middle.

**Comment by CendioOssman** [comment]
Fixed in 24a89098ffa13b33bc5bb712530e1e19ee948823. Thanks for reporting!

**Comment by spectrallypure** [comment]
Thanks for the update! Could you please tell me around when will binaries including this bugfix be available for download at sourceforge?
