### ISSUE TITLE
Security: restrict who can edit the wiki

### ISSUE THREAD

**Issue by Octogonapus** [TigerVNC/tigervnc#1880]
A malicious user added a crypto miner download to the wiki: https://github.com/TigerVNC/tigervnc/wiki/Home/_compare/316055964ad3c98e471758aff91f344357fd747f

I have removed this, but anyone can edit those pages. Please restrict who can edit the wiki.

**Comment by CendioOssman** [comment]
I thought we had already done that, but apparently not. Thanks for the reminder.

It's locked down now, and I've purged the junk from the history.
