### ISSUE TITLE
VNCViewer: The screen did not resize to full screen when the client has set the scaling and text size in Windows 11 23H2

### ISSUE THREAD

**Issue by w93163red** [TigerVNC/tigervnc#1883]
**Describe the bug**
When launching the application in fullscreen mode, the content does not properly resize to fit the entire screen. Instead, part of the screen remains black, and the displayed content appears cropped or offset. Additionally, the mouse pointer's actual interaction position does not align with the displayed UI elements, leading to mismatches between clicks and their intended targets.

The client version I built is from commit 9da4f05748c1ec084ee28982c3d1299a5f775664
The server version is built from commit (b5225e9790fe49c63e5baa2c223d0949d68a9524) 

**To Reproduce**
1. Set windows resolution to 2560x1600 (I have tested two resolutions 2560x1600, 3840x2160, they both have the same issue). The scale set to 150%.
2. In the Windows `accessibility` tab, set the `Text Size` to 112%
![image](https://github.com/user-attachments/assets/21370b6b-d10a-4ba7-9d0e-a900d11c23b3)

**Expected behavior**
It should display the content as full screen  

**Screenshots**
![image](https://github.com/user-attachments/assets/80151ed2-2bf5-4cee-ac86-79edf78f7348)

**Client (please complete the following information):**
 - OS: Windows 11 23H2
 - VNC client: TigerVNC
 - VNC client version: 9da4f05748c1ec084ee28982c3d1299a5f775664
 - Client downloaded from: self build 

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC server: TigerVNC
 - VNC server version: b5225e9790fe49c63e5baa2c223d0949d68a9524
 - Server downloaded from: self-build
 - Server was started using: Xvnc

**Additional context**
I have tested the novnc with the mouse back commit (https://github.com/novnc/noVNC/pull/1919) , it works correctly

**Comment by CendioOssman** [comment]
There might be different issues at play at once here. Neither the TigerVNC client, nor the server supports scaling. But at least the client should work correctly in the backwards compatible mode.

To rule out build issues, what problems are you seeing if using the official builds on our release page?

**Comment by w93163red** [comment]
The official build is correct. It might be related to the process when I built the binary. The step I used is to follow the command in the https://github.com/TigerVNC/tigervnc/blob/master/.github/workflows/build.yml

**Comment by w93163red** [comment]
Downgrade to 1.3.9-1 works, but there is no mouse back/front button function

**Comment by CendioOssman** [comment]
I'm afraid FLTK 1.4 is not backwards compatible, so you need to use FLTK 1.3 when building TigerVNC.

I've filed an issue with MSYS2 that they need to provide both: https://github.com/msys2/MINGW-packages/issues/22769

**Comment by felixaszx** [comment]
@w93163red The problem is in fact related to FLTK1.4 instead of TigerVNC itself. An update will be made in MSYS2 very soon to address this issue.
