### ISSUE TITLE
Does not display text

### ISSUE THREAD

**Issue by DJs3000** [TigerVNC/tigervnc#1886]
I'm building TigerVNC 1.14.1 from source. I use the custom linux OS. Tell me what the problem is, where to look first.

![image](https://github.com/user-attachments/assets/85e9fc5b-a1f2-43a1-9e74-05c7ff9c64c1)

**Comment by DJs3000** [comment]
If run as "LC_MESSAGES=C vncviewer" is displayed in English. For some reason, the localized interface is not displayed.

**Comment by CendioOssman** [comment]
Looks like a font issue. I don't think FLTK supports fallback fonts for individual glyphs, so your primary font likely needs to be a good one with all needed symbols. It looks like all the cyrillics are missing.

What does the command `fc-match sans` say?

**Comment by DJs3000** [comment]
# fc-match sans
DejaVuSans.ttf: "DejaVu Sans" "Book"

**Comment by CendioOssman** [comment]
That seems reasonable enough. DejaVu is what I have here as well, and I don't see the issue.

Do you get the same issue with our builds?

**Comment by DJs3000** [comment]
I can't use ready-made builds, I use an exotic processor architecture. I'm cutting out the definition of systemd because elogind is defined as libsystemd. Okay, I'll try to figure it out on my own.

**Comment by CendioOssman** [comment]
Fonts also look very aliased. My next guess would be that FLTK was built without all the font libraries available, so it needs to fall back to some older system.

**Comment by DJs3000** [comment]
You're right. I have updated fltk to version 1.3.10 and now everything is fine. If you use the newest fltk 1.4.0-1, then there is an error when compiling TigerVNC 1.14.1.

![image](https://github.com/user-attachments/assets/b2d8a3f0-63ef-4431-9202-33c084d551db)

**Comment by bphinz** [comment]
Fltk 1.4.0 is not backwards compatible

**Comment by CendioOssman** [comment]
Great! Glad to hear the issue got resolved.
