### ISSUE TITLE
Command Line on ms windows

### ISSUE THREAD

**Issue by Joffrey** [TigerVNC/tigervnc#189]
I'm writing a script for windows which launch winvnc4.exe (from tigervnc 1.5.0) with the following content:

(user mode only)
.\winvnc4.exe -SecurityTypes=None -RemoveWallpaper
.\winvnc4.exe -connect 192.168.0.150::5500

Sometimes, the application doesn't start in the systray and it doesn't work
This script works well on tigervnc 1.4.0

**Comment by hildred** [comment]
You do realize that you are starting two copies of the server with different parameters?

**Comment by Joffrey** [comment]
It's weird, I know. But in previous version, these commands launched only one instance (and configuration worked well).

**Comment by CendioOssman** [comment]
So exactly what are you trying to achieve? Why not use all the arguments at once with a single winvnc?

**Comment by Joffrey** [comment]
```
winvnc4.exe -SecurityTypes=None -RemoveWallpaper'
```
^ This command launches Tigervnc in the systray (user mode)
At this point, there is only One instance (of winvnc4.exe)
```
winvnc4.exe -connect 192.168.0.150::443
```
^ This command uses the current opened instance and connect to a distant computer in reverse mode.
There is still only One instance (of winvnc4.exe)

The software needs two commands separately because it is not able to work when I gather all arguments in one call. I made tests, and it achieves what I am looking for in TigerVNC 1.4.x not in TigerVNC 1.5.0.

**Comment by CendioOssman** [comment]
Alright. I'm still not entirely clear on exactly what goes wrong though. Does the initial command fail to start a server? Have you checked in task manager if winvnc4.exe is running?

**Comment by bphinz** [comment]
On Thu, Aug 20, 2015 at 11:01 AM, Joffrey <notifications@github.com> wrote:

> winvnc4.exe -SecurityTypes=None -RemoveWallpaper'
>
> ^ This command launches Tigervnc in the systray (user mode)
> At this point, there is only One instance (of winvnc4.exe)
>
> winvnc4.exe -connect 192.168.0.150::443
>
> ^ This command uses the current opened instance and connect to a distant
> computer in reverse mode.
> There is still only One instance (of winvnc4.exe)
>
> The software needs two commands separately because it is not able to work
> when I gather all arguments in one call. I made tests, and it achieves what
> I am looking for in TigerVNC 1.4.x not in TigerVNC 1.5.0.
>
So the unix analogy would be starting up the server and then issuing
vncconnect?  Are you sure that the server has had enough time to startup?
I think if you're using the Windows "start" command to spawn a process, it
doesn't actually wait for the process to return, correct?

-brian

**Comment by Joffrey** [comment]
> Alright. I'm still not entirely clear on exactly what goes wrong though. Does the initial command fail to start a server? Have you checked in task manager if winvnc4.exe is running?

The first command seems to fail, the screen "flickers" though.
Like I said, however, sometimes it works.
I checked the Task Manager, yes : sometimes it starts, sometimes it doesn't start (checked on Windows XP, Seven and 8.1).

> So the unix analogy would be starting up the server and then issuing vncconnect? Are you sure that the server has had enough time to startup? I think if you're using the Windows "start" command to spawn a process, it doesn't actually wait for the process to return, correct?

Sure, I need to wait for 2 seconds before calling the "connect" command. And for TigerVNC 1.4.x, it works every time. For TigerVNC 1.5, sometimes, the instance just never starts.



Sorry for my approximate english.

**Comment by rzippert** [comment]
I'm running into the same issue. I have a Java application that calls winvnc4.exe with the arguments -SecurityTypes=TLSNone, -RemoveWallpaper and -ShowTrayIcon, then waits a few seconds and calls winvnc4.exe again with the -Connect address argument. For some reason I cannot define, it will always start the process, but often without the tray icon. When that happens (there's no tray icon but running process), the second call will create the tray icon but won't start the reverse connection.
I'll try a few more tests and post here if I find a different behavior.
Will also test with the aforementioned 1.4.3 version.

**Comment by rzippert** [comment]
Updating the part I said:

>  When that happens (there's no tray icon but running process), the second call will create the tray icon but won't start the reverse connection (does it replace the old running instance?).

I am running it pretty reliably with a 5 second delay. The icon still only shows when the second instance launches, but the reverse connection is always being started. Can't say for sure if the first behavior didn't start the reverse connections.

I didn't yet test the 1.4.x versions. Will do so tomorrow probably.

**Comment by CendioOssman** [comment]
There were some crash bugs that we've fixed since this issue was opened. Could you test with the latest release and see if the problem remains?

**Comment by Joffrey** [comment]
Problem solved with tigervnc 1.6.0,
Thanks for all ! :)

**Comment by CendioOssman** [comment]
Great. Thanks for testing.

**Comment by niterain** [comment]
So did he mean he doesn't have to wait 2 seconds anymore?
