### ISSUE TITLE
TigerVNC 1.5.0 issues on Win 8.1 x64

### ISSUE THREAD

**Issue by worstdevil** [TigerVNC/tigervnc#191]
I had a problem with x64 version of this release on two different computers that it keeps flashing the "hourglass" by the mouse cursor every 1-2 secs even if nothing is being done on the computer. Killing TigerVNC service stops that. Plus the systray icon never showed up. On x86 version this problem doesn't appear, instead I didn't see the IP address of the machine when hovering over TigerVNC icon in the systray.

**Comment by alexeykv** [comment]
I have same issue on Windows 7 x64

**Comment by Dambuster88** [comment]
I have Win7 x64 and the same issue.
Sometimes (just a few times) the service managed to start and be useful.

**Comment by b-user** [comment]
os: windows 8.1 x64
winvnc4 x64 1.5.0.0 - APPCRASH
winvnc4 x86 1.5.0.0 - work fine

**Comment by CendioOssman** [comment]
This sounds very much like #187 which was fixed with f7aa3f9bd315ba52d6ee1e7236a580102c8d20b8. Can you test a nightly build and see if that works?

**Comment by genpfault** [comment]
The `tigervnc64-1.5.80.exe`/`2015-11-09 01:47:07`/`2c4de08e59f4f98e8abe5b2239aef357` [nightly](http://tigervnc.bphinz.com/nightly/) seems to fix the hourglass issue on my Windows 7 machine.
