### ISSUE TITLE
NullPointerException when attempting to use X509 security types with unspecified CA certificate in Java viewer

### ISSUE THREAD

**Issue by dcommander** [TigerVNC/tigervnc#193]
Steps:

* Create X.509 certificate on the server using a fake certificate authority:
  ```bash
  openssl genrsa -out ca_server.key 1024
  openssl req -new -newkey rsa:1024 -nodes -out ca_server.csr -keyout ca_server.key -subj "/C=US/ST=Texas/L=Austin/O=The VirtualGL Project/OU=Software Development/CN=VeNCryptServer/CN=VeNCryptFakeServerCA"
  openssl x509 -req -days 3650 -in ca_server.csr -signkey ca_server.key -out ca_server.crt
  openssl genrsa -out server.key 1024
  openssl req -new -newkey rsa:1024 -nodes -out server.csr -keyout server.key -subj "/C=US/ST=Texas/L=Austin/O=The VirtualGL Project/OU=Software Development/CN=VeNCryptServer"
  openssl x509 -req -days 3650 -CA ca_server.crt -CAkey ca_server.key -CAcreateserial -in server.csr -out server.crt
  ```

* Start the server using the self-signed cert
  ```bash
  vncserver -securitytypes x509none -x509key `pwd`/server.key -x509cert `pwd`/server.crt
  ```

* Log in using FLTK viewer
  ```bash
  vncviewer bullwinkle:1
  ```
  * Dialog:
    "Hostname (bullwinkle) does not match any certificate, do you want to continue?"  Yes.
  * Dialog:
    "This certificate has been signed by an unknown authority: blah blah blah ... Do you want to save it and continue?"  Yes.
  * Connection completes successfully.

* Log in using Java viewer
  ```bash
  java -jar VncViewer.jar bullwinkle:1
  ```
  produces the following exception:
  ```
  TigerVNC Java Viewer v1.5.80 (20150912)
  Built on Sep 12 2015 at 14:19:36
  Copyright (C) 1999-2015 TigerVNC Team and many others (see README.txt)
  See http://www.tigervnc.org for information on TigerVNC.
  CConn: connected to host bullwinkle port 5901
  CConnection: Server supports RFB protocol version 3.8
  CConnection: Using RFB protocol version 3.8
  com.tigervnc.rfb.Exception: java.lang.RuntimeException: java.lang.NullPointerException
  	at com.tigervnc.rfb.CSecurityTLS.processMsg(CSecurityTLS.java:132)
  	at com.tigervnc.rfb.CSecurityStack.processMsg(CSecurityStack.java:41)
  	at com.tigervnc.rfb.CSecurityVeNCrypt.processMsg(CSecurityVeNCrypt.java:177)
  	at com.tigervnc.rfb.CConnection.processSecurityMsg(CConnection.java:193)
  	at com.tigervnc.rfb.CConnection.processMsg(CConnection.java:64)
  	at com.tigervnc.vncviewer.VncViewer.run(VncViewer.java:466)
  	at java.lang.Thread.run(Thread.java:695)
  ```
  However, it works fine if I load ```ca_server.crt``` into the viewer using the "Load CA certificate" button under Options-->Security.

**Comment by bphinz** [comment]
Thanks for the heads up.  After looking at it, I think it would have done the same thing even if the server certificate was signed by a valid authority.  I've extended the functionality of the X509TrustManager to pull in all of the trusted CA certificates known to the JRE, in addition to any CA certificate(s) specified by the client or read in from ~/.vnc/x509_savedcerts.pem.  In the case of a certificate whose issuer cannot be verified, a dialog similar to the FLTK viewer is shown and the certificate will be appended to ~/.vnc/x509_savedcerts.pem if the user approves it.  I should have that all checked in sometime tomorrow, I just need to test it on a couple more platforms first (looks good on linux/osx with Java 7/8).

I think the X509TrustManager needs to be extended to perform better CRL checking and hostname verification, but those can be added independent of this.

**Comment by bphinz** [comment]
Sorry, didn't realize that 'fixes' in the commit message would close the issue when the original commit was to a fork.  In either case, I believe that it is fixed but if you find otherwise then go ahead and re-open the issue.

**Comment by dcommander** [comment]
Thanks for the quick fix.  I'll take a look at it in detail this week.

**Comment by dcommander** [comment]
On my Mac using Apple Java 6, this patch fails with:

"invalid DER-encoded certificate data"

Seems to work on other versions of Java (including Java 6 on Linux.)  Any ideas?

This represents a regression, because now it fails even if I specify the CA certificate (whereas previously it didn't.)

**Comment by bphinz** [comment]
Please take a look at 395a934, it fixes the Apple Java 6 issue for me and a couple of other things that I found along the way.

**Comment by dcommander** [comment]
Works for me.  I've integrated these into the TurboVNC Viewer.  You should also check out

https://github.com/TurboVNC/turbovnc/commit/587aea9a8861bf2277801b00bf94f44af637f461

If you have multiple viewer instances running within the same invocation of VncViewer, this prevents all of the instances from exiting if the user clicks "No" in the trust dialog.

**Comment by bphinz** [comment]
Thanks!
