### ISSUE TITLE
Shortcut to windows taskbar in fullscreen tigervnc session

### ISSUE THREAD

**Issue by cookacounty** [TigerVNC/tigervnc#197]
I frequently find myself wanting to swap between a fullscreen thinlinc session
and my windows desktop, for example when I want to take a screenshot of the
thinlinc session and paste it in a word doc.

It would be nice if there was a option in the F8 menu to make thinlinc still
fullscreen but show the windows taskbar "show taskbar". If I un-fullscreen
thinlinc It sometimes causes my windows to shift around which is not desirable.

I'm also creating a duplicate of this bug on github for tigervnc.

Thanks!

**Comment by cookacounty** [comment]
Normal thinlinc session (Ubuntu XFCE desktop)
![image](https://cloud.githubusercontent.com/assets/3683155/9945619/4ebdd262-5d5c-11e5-9296-7a69be1c611b.png)


Shortcut would reveal a view like this:
![image](https://cloud.githubusercontent.com/assets/3683155/9945597/3a96fc64-5d5c-11e5-8ac7-91d9f225df39.png)

**Comment by CendioOssman** [comment]
Issue #90 was recently fixed. Is that sufficient? Because showing the task bar without leaving full screen is not that easy. And probably impossible in a portable manner.

**Comment by cookacounty** [comment]
Yes, I think that is suffient. I also forgot about the ability to disable sending of system keys to the session.
One thought, would it be reasonable to have a config file where we could set which system keys get sent, perhaps even change the mapping?

**Comment by CendioOssman** [comment]
The override is usually all-or-nothing, so I don't think such a configuration would be possible. :/
