### ISSUE TITLE
Add -- (double dash vs single dash) argument option to Xvnc

### ISSUE THREAD

**Issue by durack1** [TigerVNC/tigervnc#203]
I've tripped over myself a couple of times trying to query arguments of `Xvnc` and think it'd be useful if `--help` (double leading dash, rather than single leading dash) also worked for arguments rather than leading to an error - this is the default for many other `linux` system binaries..

```
[user@ocean ~]$ Xvnc --help
Unrecognized option: --help
use: X [:<display>] [option]
-a #                   default pointer acceleration (factor)
-ac                    disable access control restrictions
-audit int             set audit trail level
-auth file             select authorization file
...
```

**Comment by CendioOssman** [comment]
I'm afraid this is an historical difference in the X11 world. We are not the ones parsing that `-help`, but rather the Xorg base used to build Xvnc. So you'd have to direct that request to the Xorg people. If they make that change then Xvnc will also be changed as it uses the same source.
