### ISSUE TITLE
Xfwm4 shade window: Black windows displayed as there is no window redraw 

### ISSUE THREAD

**Issue by vrishab** [TigerVNC/tigervnc#204]
1. Before issue:
   ![before](https://cloud.githubusercontent.com/assets/8469504/10158222/28df77ca-66ae-11e5-8786-dd2d7c75c384.png)
2. Click Shade button ( arrow mark )
3. Issue appears

![after](https://cloud.githubusercontent.com/assets/8469504/10158223/28e59f9c-66ae-11e5-9515-9942c188f626.png)
## Server machine:

Debian Jessie 32 bit
TigerVNC 1.5.0 server ( 32 - bit )

[server] $ xfwm4 --version
    This is xfwm4 version 4.10.1 (revision 3918e6b) for Xfce 4.10
    Released under the terms of the GNU General Public License.
    Compiled against GTK+-2.24.25, using GTK+-2.24.25.

```
Build configuration and supported features:
- Startup notification support:                 Yes
- XSync support:                                Yes
- Render support:                               Yes
- Xrandr support:                               Yes
- Embedded compositor:                          Yes
- KDE systray proxy (deprecated):               No
```
## Client machine:

Debian Jessie 64 bit
TigerVNC 1.5.0 client ( Linux 64 - bit )
##

**Comment by CendioOssman** [comment]
I wonder if this is another case of bug #196. Could you try a nightly build on the server and see if anything changes?

**Comment by vrishab** [comment]
This issue exists in the latest nightly ( logs below )

Xvnc TigerVNC 1.5.80 - built Sep 28 2015 02:22:22
Copyright (C) 1999-2015 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11202000, The X.Org Foundation

**Comment by vrishab** [comment]
Interestingly this issue happens only within the windows of "Document Viewer".  Note that in the picture attachment above, there is a window actions [ - [] x ] from the window manager and "Document Viewer" has its own actions [ - [] x ]. Document Viewer as such works fine on the machine which hosts the TigerVNC server - but on a gnome session. The TigerVNC session uses xfwm4 as the window manager.

**Comment by vrishab** [comment]
As mentioned in the previous comment, the issue happens within "Document Viewer" instances - or - more precisely within instances which have 2 set of window actions [ - [] x ] one from the window manager, and one within the app itself. Below are the attachments where this behavior is observed between nautilus and "Document Viewer".

![before3](https://cloud.githubusercontent.com/assets/8469504/10185843/bdbb3dc8-6769-11e5-8107-0dbf64ff5d6f.png)
![after3](https://cloud.githubusercontent.com/assets/8469504/10185844/bdc066ae-6769-11e5-9e27-8f706829931e.png)

This also happens between 2 instances of nautilus windows too.

**Comment by CendioOssman** [comment]
I'm unable to reproduce this for the simple fact that my GTK3 windows are well behaved and don't have double set of buttons.

Can you reproduce this with any non-GTK3 applications?

**Comment by vrishab** [comment]
Hi, this is not an issue with vanilla gtk app on vanilla gtk environment. This issue is only seen when we use xfwm4 as the window manager ( meaning a non default window manager ). Below are the contents of the xstartup file that I use for my vnc session.

xsetroot -solid '#1b5994'
/usr/bin/xfwm4 &
/usr/bin/xfce4-panel &

Add nautilus to xfce panel, and launch the apps ( document-viewer or nautilus windows ).

**Comment by CendioOssman** [comment]
Something is broken with your GTK applications, so I'm not realistically going to be able to reproduce your issue with those. Hence why I'm asking you if you can see this bug in any other applications?

**Comment by vrishab** [comment]
Here are the steps I use to reproduce this issue:

1. Install package "xfwm4"
2. Install package "xfce4-panel"
3. Copy the following to ~/.vnc/xstartup

if [ -f ~/.Xresources ]; then
    xrdb -merge ~/.Xresources
fi

xsetroot -solid '#1b5994'
rm -rf ~/.config/xfce4/

/usr/bin/xfwm4 &
/usr/bin/xfce4-panel &
/usr/bin/nautilus &
/usr/bin/nautilus &

4. Start TigerVNC server ( no arguments ) using above xstartup file.
5. Connect using vncviewer. Select "One Empty Panel" when panel dialog box appears.
6. Keep nautilus windows overlapped. 
7. Use the "upward arrow" button from one of the windows. The bug should appear.

The "upward arrow" is the key to reproduce this bug. The upward arrow option is available from xfwm4. Not sure about other window managers. I tried this on standard Debian Jessie 32 / 64 bit. With all remaining the same, I switched the vncserver from TigerVNC to TightVNC and the issue is not seen. The only difference is TightVNC is installed from Debian APT, where as TigerVNC is started from a directory ( not installed in the system ) as shown below:

[ user @host : ~/Downloads/TigerVnc/64-bit/stable-1.5.0/usr/bin$ ./vncserver

I've to do it this way, since TigerVNC is not in Debian repositories yet. This bug shows up only in applications which use CSD ( Client Side Decorations ). I've seen this issue with evince / nautilus / gnome-calculator - all of them are gnome native apps which use CSD. So, any gnome app with CSD would qualify for this bug. As stated ( in - Refer 4th paragraph in https://blogs.gnome.org/mclasen/2014/01/13/client-side-decorations-continued/ ), there are problems between apps which use CSD and xfwm4 . But, this combination was working perfectly for months in TightVNC. 

In both my test systems ( 32 / 64 bit ), a gnome session will be always active ( if that is useful information ), in addition to the vnc sessions.

**Comment by CendioOssman** [comment]
Hmm... That link has some interesting bug reports. They indicate that Xfwm4 never did anything to accommodate CSD. Yet it works just fine when I'm testing here.

**Comment by CendioOssman** [comment]
Okay, the key seems to be Gnome version, not Xfwm4. I'm able to get the double captions with Gnome 3.8, but not Gnome 3.16. Still, the screen updates just fine when I roll up the nautilus windows.

**Comment by vrishab** [comment]
I just installed a brand new ISO of debian Jessie ( debian-8.1.0-i386-DVD-1.iso ) in VirtualBox, and followed the exact steps as above, and I was able to reproduce this issue. Gnome version is as below:

[...]$ gnome-shell --version
GNOME Shell 3.14.4

Online debian package reference: https://packages.debian.org/jessie/gnome

**Comment by vrishab** [comment]
Reproduced on the latest debian ( 8.2 ) iso too ( http://cdimage.debian.org/debian-cd/8.2.0/i386/iso-cd/debian-8.2.0-i386-CD-1.iso ).

debian@debian-8:~$ uname -a
Linux debian-8 3.16.0-4-586 #1 Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) i686 GNU/Linux

debian@debian-8:~$ gnome-shell --version
GNOME Shell 3.14.4

Entire command history of normal user:

    1  cd Downloads/
    2  ls
    3  ls -l
    4  tar zxf tigervnc-Linux-i686-1.5.0.tar.gz 
    5  ls
    6  cd usr/
    7  ls
    8  cd bin/
    9  ls
   10  gnome-shell --version
   11  ls
   12  mkdir ~/.vnc && touch ~/.vnc/xstartup && chmod +x ~/.vnc/xstartup
   13  vi ~/.vnc/xstartup ( paste from issue #204 )
   14  sudo apt-get install xfwm4 xfce4-panel
   15  ls
   16  ./vncserver 
   17  ./vncviewer :1

**Comment by CendioOssman** [comment]
Is this still an issue with updated versions of everything?

**Comment by CendioOssman** [comment]
No response. Closing.
