### ISSUE TITLE
No window redraw after maximize and restore neighbouring window

### ISSUE THREAD

**Issue by vrishab** [TigerVNC/tigervnc#205]
Step1:  I have 2 pdfs opened in Document Viewer

![before2](https://cloud.githubusercontent.com/assets/8469504/10158472/f818df08-66af-11e5-9f75-bcae2fbe1873.png)

Step 2: The document on the left is on top. The document on the right is at bottom. Maximize and restore left document.

Step 3: Result is show in this image

![after2](https://cloud.githubusercontent.com/assets/8469504/10158473/f820b282-66af-11e5-96f5-833a248ffb96.png)

Server machine:

Debian Jessie 32 bit
TigerVNC 1.5.0 server ( 32 - bit )

[server] $ xfwm4 --version
This is xfwm4 version 4.10.1 (revision 3918e6b) for Xfce 4.10
Released under the terms of the GNU General Public License.
Compiled against GTK+-2.24.25, using GTK+-2.24.25.

Build configuration and supported features:
- Startup notification support:                 Yes
- XSync support:                                Yes
- Render support:                               Yes
- Xrandr support:                               Yes
- Embedded compositor:                          Yes
- KDE systray proxy (deprecated):               No

Client machine:

Debian Jessie 64 bit
TigerVNC 1.5.0 client ( Linux 64 - bit )
##

**Comment by vrishab** [comment]
This issue exists in the latest nightly ( logs below )

Xvnc TigerVNC 1.5.80 - built Sep 28 2015 02:22:22
Copyright (C) 1999-2015 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11202000, The X.Org Foundation

**Comment by CendioOssman** [comment]
Same question as on #204, can you reproduce this in any non-GTK3 applications?

**Comment by vrishab** [comment]
Hi, this is not an issue with vanilla gtk app on vanilla gtk environment. This issue is only seen when we use xfwm4 as the window manager ( meaning a non default window manager ). Below are the contents of the xstartup file that I use for my vnc session.

xsetroot -solid '#1b5994'
/usr/bin/xfwm4 &
/usr/bin/xfce4-panel &

Add nautilus to xfce panel, and launch the apps ( document-viewer or nautilus windows ).

**Comment by CendioOssman** [comment]
Is this still an issue with updated versions of everything?

**Comment by CendioOssman** [comment]
No response. Closing.
