### ISSUE TITLE
TigerVNC 1.5.0 client hangs due to firewall block ( Minor )

### ISSUE THREAD

**Issue by vrishab** [TigerVNC/tigervnc#206]
This is the backtrace from gdb:

#0  0x00007f0e15eec293 in __select_nocancel () at ../sysdeps/unix/syscall-template.S:81
#1  0x00000000005881d8 in rdr::FdOutStream::writeWithTimeout(void const*, int, int) ()
#2  0x0000000000588453 in rdr::FdOutStream::flush() ()
#3  0x00000000005896ef in rdr::TLSOutStream::push(void*, void const*, unsigned long) ()
#4  0x00000000005b0cca in _gnutls_writev_emu ()
#5  0x00000000005b2835 in _gnutls_io_write_flush ()
#6  0x00000000005aea4d in _gnutls_send_tlen_int ()
#7  0x00000000005af01a in gnutls_record_send ()
#8  0x000000000058940a in rdr::TLSOutStream::writeTLS(unsigned char const*, int) ()
#9  0x00000000005894bd in rdr::TLSOutStream::flush() ()
#10 0x000000000047f9db in Viewport::handlePointerEvent(rfb::Point const&, int) ()
#11 0x000000000047fd38 in Viewport::handle(int) ()
#12 0x00000000004a30b8 in Fl_Group::handle(int) ()
#13 0x00000000004a30b8 in Fl_Group::handle(int) ()
#14 0x0000000000498904 in send(int, Fl_Widget*, Fl_Window*) ()
#15 0x0000000000499fa4 in Fl::handle_(int, Fl_Window*) ()
#16 0x00000000004790fd in DesktopWindow::fltkHandle(int, Fl_Window*) ()
#17 0x00000000004c2f8b in do_queued_events() ()
#18 0x00000000004c33c3 in fl_wait(double) ()
#19 0x000000000049a829 in Fl::wait(double) ()
#20 0x0000000000483873 in main ()

Even after the vnc server was stopped, the vncviewer was still in frozen mode for quite a while displaying all windows ( with just no keyboard and mouse response ), after which the entire vncviewer window became blank ( grey )

Server machine:

Debian Jessie 32 bit
TigerVNC 1.5.0 server ( 32 - bit )

[server] $ xfwm4 --version
This is xfwm4 version 4.10.1 (revision 3918e6b) for Xfce 4.10
Released under the terms of the GNU General Public License.
Compiled against GTK+-2.24.25, using GTK+-2.24.25.

Build configuration and supported features:
- Startup notification support:                 Yes
- XSync support:                                Yes
- Render support:                               Yes
- Xrandr support:                               Yes
- Embedded compositor:                          Yes
- KDE systray proxy (deprecated):               No

Client machine:

Debian Jessie 64 bit
TigerVNC 1.5.0 client ( Linux 64 - bit )

**Comment by vrishab** [comment]
This might not be an issue. Just a behavior.

This was due to a firewall block. The port on which the vnc server was listening was blocked prior to "vncserver -kill :<display>". Hence the client was clueless about the kill. I waited for more than 10 minutes after the port block, and vncviewer had nothing to say ( terminating the connection with an error message ). This could be handled better.

**Comment by CendioOssman** [comment]
Commit 1db732494b625df465797faaec3d76d535e69d43 makes sure you can terminate the client even when the network has managed to lock up.
