### ISSUE TITLE
Building gets killed

### ISSUE THREAD

**Issue by IotaSpencer** [TigerVNC/tigervnc#208]
[ 87%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o
/home/ken/Downloads/tigervnc-1.5.0/vncviewer/DesktopWindow.cxx: In member function ‘void DesktopWindow::fullscreen_on()’:
/home/ken/Downloads/tigervnc-1.5.0/vncviewer/DesktopWindow.cxx:437:38: error: ‘fullscreen_screens’ was not declared in this scope
     fullscreen_screens(-1, -1, -1, -1);
                                      ^
/home/ken/Downloads/tigervnc-1.5.0/vncviewer/DesktopWindow.cxx:472:48: error: ‘fullscreen_screens’ was not declared in this scope
     fullscreen_screens(top, bottom, left, right);
                                                ^
vncviewer/CMakeFiles/vncviewer.dir/build.make:100: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o' failed
make[2]: *** [vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o] Error 1
CMakeFiles/Makefile2:775: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/all' failed
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

I'm just trying to build the vncviewer part of tiger, and this happens

I'm using ubuntu 15.04

**Comment by CendioOssman** [comment]
You are using a too old version of FLTK. TigerVNC requires 1.3.3 or newer.
