### ISSUE TITLE
Windows service registration

### ISSUE THREAD

**Issue by fmgppt** [TigerVNC/tigervnc#209]
Let me just say ahead I believe this is a minor issue, however I also believe it should be fixed.

The windows service name and description appear to be registered wrong.

My lab setup: Windows 7 Ultimate x64 fully updated. (literally a lab, no other tools)

When browsing the service list I couldn't find any TigerVNC service, although I knew I had it registered.
By resorting to task manager, msconfig and the alike tools I noticed winvnc4 executable was associated to a service named "Provides remote access..." which I believe it's meant as the description.

**Comment by CendioOssman** [comment]
The internal API labels that as the name and description, but that's not what the Windows API uses it for. So yes, we need to put some better strings in here.

**Comment by CendioOssman** [comment]
Fixed in 018c67e6e1cdfb5e0494ad987093738b7fe7e60d.
