### ISSUE TITLE
xterm scrolling issue

### ISSUE THREAD

**Issue by richash** [TigerVNC/tigervnc#211]
Opening scrolling xterm session in gnome-terminal window affects the other overlapping segments.

Steps to reproduce:

Example Case 1
a) Open gnome-terminal in tigervnc. Run xterm.
b) In xterm window, run "ping google.com"
c) Open Activities and you can see the background getting distorted.

Example Case 2
a) Open gnome-terminal in tigervnc. Run xterm.
b) In xterm window, run "ping google.com"
c) Open one more xterm in another workspace.
d) The overlapping segment in second xterm will scroll with the first xterm

**Comment by wbentley0** [comment]
Similar issue reported from users on TigerVNC Win 1.4.3 viewer, connecting to TigerVNC Linux 1.4.3 server.  Scrolling term window (test results) partially overlapped by another (test control) window; redraws on the underneath window during scroll pulls the overlapping window contents upward, then the overlapping window gets redrawn after.  Creates a continuously flickering effect on-screen for users during frequent/constant scrolling of content in the partially-overlapped window.

**Comment by CendioOssman** [comment]
Fixed in 9986dce. We didn't account for the fact that compositing means that windows might not be at their apparent coordinates.
