### ISSUE TITLE
Set the keyboard repeat and delay

### ISSUE THREAD

**Issue by mercmobily** [TigerVNC/tigervnc#213]
I am trying to change the keyboard delay for repeats. I am using: TigerVNC Viewer 64-bit v1.5.0 Built on: 2015-07-12 15:29

I tried:

* Setting it from xfce interface: no joy
* `sudo kbdrate -d 100` : no joy
* `xset r rate 100` and `xset r rate 100 30`: no joy

Thing is, I am _sure_ I daw somewhere in the command line help an option to set the kbd repeat and delay... in fact, that WAS one of the main reason why I installed tigervnc in the first place! (Then I discovered that it's _actually_ maintained, and it's actually built against xorg which is fantastic...)

A a side note, I really need this.. It's for a devel machine I built (I am an active free software development) and the keyboard delay is driving me bananas. I spent hours trying to hammer this one... but here I am, I give up... thanks for listening :D

**Comment by CendioOssman** [comment]
Keyboard repeat is entirely controlled by the client. So just change it locally using the system settings. It cannot be sensibly done server side because of the extra latency introduced by the network.

**Comment by mercmobily** [comment]
Hi,

So it was my X's fault. Sorry.

Merc.
