### ISSUE TITLE
configuration files for /usr/bin/vncserver

### ISSUE THREAD

**Issue by graysky2** [TigerVNC/tigervnc#216]
I am writing a systemd service for vncserver (https://github.com/TigerVNC/tigervnc/pull/217) and would like to make it as general as possible (minimal number of switched in the ExecStart line.  My question is: does /usr/bin/vncserver source some config file where various options reside and are called by vncserver upon startup?  For example, I want to avoid passing the `-alwaysshared -localhost -geometry 2000x1200` flags to /usr/bin/vncserver but I do want them capture in a user config file like $HOME/.vnc/config or the like.  Thanks.

**Comment by CendioOssman** [comment]
No there is no such configuration right now.

**Comment by graysky2** [comment]
Would you be opposed to depending on a module to parse a config file?  For example: Config::General

**Comment by hildred** [comment]
@graysky2, you do realize that library is written in perl and that Xvnc is written in C and C++. I don't think that would be the best place for embedding a perl interpreter unless we had additional plans for using it.

**Comment by bphinz** [comment]
I think he's suggesting adding a dependency on Config::General from within
the vncserver perl script.

**Comment by CendioOssman** [comment]
That doesn't seem to be installed by default on at least Fedora, so I'm a bit cautious about depending on it.

It there some simpler module that is included with Perl itself? Or how difficult would it be to include a small parser in the vncserver script?

**Comment by graysky2** [comment]
@pbhinz - Yes, you are indeed correct: only needed for the vncserver perl script.
@CendioOssman - Yes, I am making ready a PR that will have this parsing built into the script without any extra dependencies.  The code works well in my test cases and will allow for easy incorporation of the systemd user service from https://github.com/TigerVNC/tigervnc/pull/217

**Comment by graysky2** [comment]
Ready for review: https://github.com/TigerVNC/tigervnc/pull/221
