### ISSUE TITLE
Bad error message "No useful address for host"

### ISSUE THREAD

**Issue by bswartz** [TigerVNC/tigervnc#225]
If you attempt to connect to a system that is up but not running a VNC server you get a weird and misleading error message:

>$ ping -c1 10.97.21.160
>PING 10.97.21.160 (10.97.21.160) 56(84) bytes of data.
>64 bytes from 10.97.21.160: icmp_seq=1 ttl=118 time=26.1 ms
>
>--- 10.97.21.160 ping statistics ---
>1 packets transmitted, 1 received, 0% packet loss, time 0ms
>rtt min/avg/max/mdev = 26.195/26.195/26.195/0.000 ms
>$ telnet 10.97.21.160 5901
>Trying 10.97.21.160...
>telnet: connect to address 10.97.21.160: Connection refused
>$ vncviewer 10.97.21.160:1
>
>TigerVNC Viewer 64-bit v1.5.0
>Built on: 2015-08-21 09:59
>Copyright (C) 1999-2015 TigerVNC Team and many others (see README.txt)
>See http://www.tigervnc.org for information on TigerVNC.
>
>Wed Oct 21 10:51:38 2015
> CConn:       __No useful address for host__
>$ 

I would have expected an error message indicating that the connection was refused.

**Comment by CendioOssman** [comment]
This got fixed in 5a126667a3e375df227be69689a150fec0d75a28. It will be in the next release. You can try a nightly build if you wish to test it out right away.
