### ISSUE TITLE
Linux viewer negotiates a different encryption scheme than expected.

### ISSUE THREAD

**Issue by ryanjaeb** [TigerVNC/tigervnc#230]
I've tested the viewer on:

```
  CentOS 7

Name        : tigervnc
Arch        : x86_64
Version     : 1.2.80
Release     : 0.30.20130314svn5065.el7
```

```
  Fedora 22

Name        : tigervnc
Arch        : x86_64
Epoch       : 0
Version     : 1.5.0
Release     : 2.fc22
```

```
  Windows 10 (from bintray)

TigerVNC Viewer 64-bit v1.5.0
Built on: 2015-07-12 15:35
```

I'm running a server on:
```
  CentOS 7

Name        : tigervnc-server
Arch        : x86_64
Version     : 1.2.80
Release     : 0.30.20130314svn5065.el7
```

For the purpose of testing, I set the following on the server (don't use this in production):

```
-SecurityTypes=VeNCrypt,X509Plain,TLSPlain,X509Vnc,TLSVnc,X509None,TLSNone,VncAuth,None
```

The Windows viewer behaves as I expected, but the Linux viewers don't.  Using the GUI, I attempt a connection with the following security options **selected**:

* Encryption
 * None
 * TLS with anonymous certificates
* Authentication
 * Standard VNC (insecure without encryption)

When I connect with the Windows viewer I get a `TLSVnc` connection.  When I connect with the Linux viewer I get a `VncAuth` connection.

Using the GUI, I attempt another connection with the following security options **selected**:

* Encryption
 * TLS with anonymous certificates
* Authentication
 * Standard VNC (insecure without encryption)

When I connect with the Windows viewer I get a `TLSVnc` connection.  When I connect with the Linux viewer I get an error:

```
No matching security types.
```

I can connect as expected with the Linux viewer if I use the command line:

```bash
vncviewer -SecurityTypes=VeNCrypt,TLSVnc
```

Entering the `host:port` and clicking `Connect` will get me a `TLSVnc` connection.  However, if I navigate to the `Security` tab first and click `OK`, the connection will fail with the error `No matching security types`.

Based on [an old mailing list](http://www.mail-archive.com/tigervnc-devel%40lists.sourceforge.net/msg02418.html) comment, I'm guessing the Linux viewer isn't including the `VeNCrypt` security type and, because of that, the server ignores all the `VeNCrypt` options.

**Comment by CendioOssman** [comment]
This is a Red Hat bug. They screw up the VeNCrypt handling with this patch:

http://pkgs.fedoraproject.org/cgit/tigervnc.git/tree/tigervnc11-rh692048.patch

So I suggest filing a bug with them. Or getting @twaugh attention.

Until then you can use our builds, or build the client yourself.
