### ISSUE TITLE
Consider support for Intel KVM AMT (porotocol version 4.0)

### ISSUE THREAD

**Issue by bits01** [TigerVNC/tigervnc#232]
[This issue was filed against TurboVNC too: https://github.com/TurboVNC/turbovnc/issues/14]

Trying to connect to a server that supports Intel KVM AMT I noticed that Turbo VNC does not work, it authenticates and then the connection is closed with a read error. The RealVNC client works. Apparently it has to do with RFB protocol version 4.0 which is not documented anywhere.

More from here:
http://sourceforge.net/p/turbovnc/bugs/45/

This seems to be a known issue
https://software.intel.com/en-us/forums/intel-business-client-software-development/topic/280246
related to the KVM's use of RFB 4.0, which seems to be a proprietary extension to the RFB protocol. If someone can find an actual specification for this extension, then it's probably something that would be easy to support, but even RealVNC's own specification (https://www.realvnc.com/docs/rfbproto.pdf)) only seems to address versions 3.8, and the community specification that TurboVNC and TigerVNC maintain (https://github.com/rfbproto/rfbproto) also only goes to 3.8. The thread on Intel's web site above seems to indicate that dropping down to 8-bit might allow it to work with an RFB 3.8 viewer. You can try that by passing "-colors 256" to the TurboVNC Java Viewer.

**Comment by bits01** [comment]
I can confirm that setting the colors to 256 works, which is a reasonable workaround for now, for just console access.

**Comment by bits01** [comment]
Just one more note, in case you want to support it some day for one of your clients:
The Open MDTK project (used to manage Intel AMT) can configure one of 3 clients for VNC access: RealVNC, UltraVNC, TightVNC. I assume they all 3 implement the same protocol.

The same Open MDTK tool can act as a local proxy to do some VNC signaling (which I don't understand) to connect to an alternate Intel AMT port 16994.
https://software.intel.com/en-us/blogs/2013/01/09/opendtk-commander-with-vnc-kvm-to-redirection-port

And some more info:
https://scivision.co/intel-amt-vpro-full-remote-kvm-control-without-proprietary-realvnc-viewer-plus/

**Comment by CendioOssman** [comment]
Sorry, this is basically a different protocol. Without documentation then there isn't anything we can do.
