### ISSUE TITLE
Flickering Desktop with version 1.5.0, Fedora 23 (server), Windows 7 (viewer)

### ISSUE THREAD

**Issue by leslie-leder** [TigerVNC/tigervnc#235]
Hello,
When using tigervnc 1.5.0 server on fedora 23 workstation (gnome3) with tigervnc 1.5.0 viewer on windows 7 (both 64bit) I can see the desktop. But it quickly flickers between the following view fragments in undeterministic order:
* full login screen
* Background image
* black screen 
* just buttons, 
* just password text input

I can login somehow. But after login it happens the same only additionally the desktop is among the flickering fragments. It seems to work in general. I can open programs but it still flickers heavily.
It makes no difference whether I use it in window or full screen mode (2 monitors in my case). 

Tigervnc 1.4.3 (server & viewer) fedora 22 (kde) worked very well in my setup. So it seems not to by client side issue.
--Leslie

**Comment by CendioOssman** [comment]
Is this with Fedora's build or ours? If it's Fedora's then could you test with our version?

**Comment by leslie-leder** [comment]
I'm not sure which package I shall use for fedora 23:
* [rpm](https://bintray.com/artifact/download/tigervnc/stable/el6/RPMS/x86_64/tigervnc-server-1.5.0-21.el6.x86_64.rpm)
* [tar.gz](https://bintray.com/artifact/download/tigervnc/stable/tigervnc-Linux-x86_64-1.5.0.tar.gz)

the rpm installation completed but doesn't run, maybe it will be configured differently. 

for the tar.gz I'm not sure how to install/config it.

**Comment by leslie-leder** [comment]
This was not quite right. the rpm based installation runs if started with:

    systemctl start vncserver@:2 

The same as for this [tigervnc-server-1.5.0-3.fc24.x86_64.rpm](ftp://rpmfind.net/linux/fedora/linux/development/rawhide/x86_64/os/Packages/t/tigervnc-server-1.5.0-3.fc24.x86_64.rpm) package.

But it stops instantly if I try to connect to it.

**Comment by CendioOssman** [comment]
> I'm not sure which package I shall use for fedora 23:

Use the .tar.gz. The RPMs are for RHEL 6 and will probably not be compatible for Fedora. You could try the RHEL 5 RPMs as those contain the same build as the .tar.gz. Not sure if there is any issues with dependency naming though.

For the .tar.gz you just unpack it. In `/` if you want a "normal" install, but you can unpack it in a temporary directory if you just want to test it.

Does it work with any other desktop environment?

**Comment by lantw44** [comment]
I also see the same problem with Fedora's build. I downloaded your .tar.gz build, but GNOME failed to start with it:

```
gnome-session[6423]: gnome-session-is-accelerated: No hardware 3D support.
gnome-session[6423]: gnome-session-check-accelerated: Helper exited with code 256
gnome-session[6423]: gnome-session-is-accelerated: No hardware 3D support.
gnome-session[6423]: gnome-session-check-accelerated: Helper exited with code 256
gnome-session[6423]: gnome-session-binary[6423]: WARNING: software acceleration check failed: Child process exited with code 1
gnome-session-binary[6423]: WARNING: software acceleration check failed: Child process exited with code 1
```

glxinfo also doesn't work
```
$ DISPLAY=:0 glxinfo
name of display: :0
Error: couldn't find RGB GLX visual or fbconfig
```

**Comment by lantw44** [comment]
Rebuilding Fedora SRPM fixes the problem for me.

Binary RPM provided by Fedora 23 shows this message in the log:
Underlying X server release 11799901, The X.Org Foundation

Rebuilt RPM shows this message in the log:
Underlying X server release 11800000, The X.Org Foundation

**Comment by CendioOssman** [comment]
Thanks for testing. I'll assume this is a Fedora issue then and it will be resolved once they do a fresh build.

**Comment by petemcdonnell** [comment]
Added notes to Fedora bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1279146
Posting here to add that reference.
