### ISSUE TITLE
vncviewer shows no server side mouse cursor

### ISSUE THREAD

**Issue by russkiontheloose** [TigerVNC/tigervnc#238]
Here's my setup:

$xrandr --addmode VIRTUAL1 1920x1080 --addmode VIRTUAL2 1920x1080
$xrandr --output LVDS1 --mode 1440x900 --rate 60.00 --pos 2160x1080 --output VGA1 --mode 1920x1080 --pos 3840x0 --output VIRTUAL1 --mode 1920x1080 --pos 0x0 --output VIRTUAL2 --mode 1920x1080 --pos 1920x0
$x11vnc -display :0 -cursor_drag -cursor arrow -xkb -noipv6 -shared -forever -nopw -norc -noclipboard -noncache -xrandr -noxdamage -rfbport 22220 -desktop left -clip 1920x1080+0+0
$x11vnc -display :0 -cursor_drag -cursor arrow -xkb -noipv6 -shared -forever -nopw -norc -noclipboard -noncache -xrandr -noxdamage -rfbport 22221 -desktop center -clip 1920x1080+1920+0

remote displays:
$vncviewer -viewonly -DotWhenNoCursor=1 -QualityLevel=9 -NoJPEG -PreferredEncoding=Raw -CompressLevel=0 -geometry 1920x1080+0+0 -AutoSelect=0 -Fullscreen=1 -FullscreenSystemKeys=0 [HOSTNAME]::2222[0-1]

The above extends my desktop to 2 screens on different machines and everything works great, except it is not possible to see mouse cursor in the viewers.

All experimentation with vncviewer and x11vnc options pertaining to cursor produced no results.

running:
TigerVNC Viewer 64-bit v1.5.0
Built on: 2015-07-13 13:21

Any and all help would be much appreciated!

**Comment by CendioOssman** [comment]
If I understand you correctly you'd like the server to render the cursor? But you say that the server is x11vnc, not TigerVNC, so I'm not sure what it is you'd like us to do?

**Comment by russkiontheloose** [comment]
I think the problem is with the vncviewer, since every other viewer shows the cursor movements accurately, it's just the viewer from tigervnc that doesn't, even tried it with a few android viewers.

**Comment by CendioOssman** [comment]
I tried TurboVNC and it has the same effect. I also tried hacking out local cursor support in our viewer and that makes x11vnc start rendering the cursor server side. So sorry, I'm going to consider this an x11vnc bug. It is not handling clients with local cursor support properly.

**Comment by jakoprd** [comment]
Hi, i had this issue too. Try `x11vnc -forever -nocursorshape` When i connect to x11vnc server via tiger vncviewer first time, i see two cursors overlapped. When logout and login to x11vnc again, overlapping is gone. If someone move mouse on server, tiger viewer client show it, but if client move mouse too, cursor on server fast jumps to clients position. But this is small cosmetic issue.
