### ISSUE TITLE
add option to not overwrite primary selection

### ISSUE THREAD

**Issue by hackonteur** [TigerVNC/tigervnc#240]
I connect to a Linux VNC server with a Windows viewer. When I copy something in Windows it gets sent to both the X primary selection buffer and the X clipboard on Linux. I don't want it to overwrite the primary selection buffer.

I also don't like that the Linux X primary selection gets sent to Windows as the clipboard.

I have tried all combinations in the VNC config on the server and the Preference in the viewer and can't get the selection to not be sent or modified when the clipboard is.

I am running the Windows 64-bit 1.4.3 viewer on Windows 7, because all the more recent versions crash. I have seen this problem on most versions of the server and can confirm it with the 1.6beta (1.5.90).

**Comment by CendioOssman** [comment]
This is controlled by the `SendPrimary` setting which is available in `vncconfig` as both a command line setting, and in the UI.

**Comment by hackonteur** [comment]
Using the 1.6beta server on RHEL6 with the Windows 64-bit viewer v1.4.3; disabling SendPrimary is not working for me. So file this as a bug then.

**Comment by CendioOssman** [comment]
I'm afraid I cannot reproduce this. I tried:

 a) Stopping the `vncconfig` started by `vncserver` and starting my own, where I unchecked sending primary.

 b) Modifying `vncserver` to include `-SendPrimary=0`.

This is with the x86_64 beta RPMs on RHEL 6.

**Comment by hackonteur** [comment]
I just reproduced the issue using the cross-compatible build server on RHEL6:
tigervnc-Linux-x86_64-1.6.80-20151206gitdb821a23.tar.gz
With viewer on Windows 7:
tigervnc64-1.6.80.exe 2015-12-06 11:29:08 655c8ce30571de20380aa05badc4b678

Viewer settings:
• Accept clipboard from server
Server settings:
• Send clipboard to viewers

I copy some text in Emacs (Meta-w) and confirm that is my clipboard. I select text with the mouse and confirm that this is my primary selection. When I go to paste in Windows I get the primary selection.

I can't try the RHEL6 RPMs right now because I don't have root on this machine.

**Comment by CendioOssman** [comment]
> When I copy text in Windows and then go back to Linux, the clipboard from Windows has over-written both the Linux clipboard (good) and primary selection (bad).

Ah, right. I didn't check that, sorry. And unfortunately neither the client nor the server currently has an option to disable this.

> Aside: The options on both sides seem a bit wrong to me. Currently the Windows viewer has the option I didn't select "Send primary selection and cut buffer as clipboard". That option doesn't make sense to me on Windows, which only has a clipboard.

Indeed. That should only be shown on X11 systems.

> I would suggest "Accept primary selection from server (as clipboard)".

Not possible I'm afraid. The protocol only has a single clipboard so the receiving end has no idea what selection generated it.
