### ISSUE TITLE
Error when attempting to modify ACL in WinVNC

### ISSUE THREAD

**Issue by bphinz** [TigerVNC/tigervnc#248]
When attempting to specify a subnet as an allowed Host IP Address Pattern as per the example ("e.g. 192.168.0.0/16"), the following error is generated:  "unable to resolve host by name: Either the host has not called WSAStartup, or WSAStartup failed.".  Possibly related to 14e214f or cd87317(?)

**Comment by CendioOssman** [comment]
Very odd. I tested cd87317 which worked fine. But I'm not sure how that's possible. Anyway, I have a fix lined up.

**Comment by CendioOssman** [comment]
Fixed in 398a6f4.
