### ISSUE TITLE
el7 packages

### ISSUE THREAD

**Issue by loganmc10** [TigerVNC/tigervnc#249]
Just a feature request.

It'd be nice to have released include el7 rpms, the el6 ones seem to work, but I assume that Xvnc isn't built with the X server bundled with EL7, so there are potential compatibility issues.

**Comment by bphinz** [comment]
Working on it actually.  I setup an EL7 build host last week and hope to have RPMs later this week.

**Comment by CendioOssman** [comment]
Fixed I assume?
