### ISSUE TITLE
vncserver connect to vncviewer?

### ISSUE THREAD

**Issue by SHOTbyGUN** [TigerVNC/tigervnc#251]
Is it possible to make vncserver to connect to vncviewer ?

vncviewer seems to have -listen parameter, but I cannot find information about "vncserver connect" from any documentation available.

**Comment by CendioOssman** [comment]
You use the `vncconfig` command for this. E.g. `vncconfig -connect myclient:5902`. Documentation is available here:

http://tigervnc.org/doc/vncconfig.html
