### ISSUE TITLE
maximizing a window with multiple monitors

### ISSUE THREAD

**Issue by jerrykt** [TigerVNC/tigervnc#253]
Under 1.5.80 (nightly built) and with multiple monitors, maximizing a window expands only on the current monitor. It is a desired update, IMHO.

But under 1.5.90, it revert backs to the previous version, expending to all monitors.

Regards,
Jerry

**Comment by CendioOssman** [comment]
Is this your own build or ours? Which platform?

**Comment by jerrykt** [comment]
Both VNC server and client are binary downloaded last night.

server:
tigervnc-Linux-x86_64-1.5.90.tar.gz
running on CentOS 6.2

client:
vncviewer64-1.5.90.exe
on Windows 7 64bit Professional

**Comment by jerrykt** [comment]
Sorry. Just found that sever side was not installed properly.
