### ISSUE TITLE
include .desktop file(s) in all X11 packaging

### ISSUE THREAD

**Issue by paul1149** [TigerVNC/tigervnc#255]
Sorry for what must be a super-basic question. I have installed the .deb package for Linux Lite 2.6 x64, which is based on ubuntu "trusty" 14.04. I see it installed in the package manager. But it is nowhere to be found in the system menu. Must this be accessed by terminal only?

The Server install on a windows machine went flawlessly.

Thanks.

**Comment by CendioOssman** [comment]
It seems like we only have `.desktop` files in the RPM packaging. That should really be included everywhere. The deb packaging also has some `.menu` file, but I'm not sure what that's about.

**Comment by bphinz** [comment]
On Fri, Dec 18, 2015 at 5:22 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> It seems like we only have .desktop files in the RPM packaging. That
> should really be included everywhere. The deb packaging also has some
> .menu file, but I'm not sure what that's about.
>
I'll have to look into it.  I based the debs off existing TightVNC packages
and haven't changed them much since.

**Comment by CendioOssman** [comment]
It should probably be moved all the way out of `contrib`. A simple `make install` should also include them. IMO.

**Comment by paul1149** [comment]
Appreciate the response, guys. I perceive this is a dev forum rather than for end users. I think I found the viewer executable at /usr/bin, but see no way to set it to Listen rather than speccing a server. Is there a user forum where I can ask the questions I have? Thanks.

**Comment by CendioOssman** [comment]
> I think I found the viewer executable at /usr/bin, but see no way to set it to Listen rather than speccing a server.

There's a `-listen` argument, but there's nothing from the GUI.

> Is there a user forum where I can ask the questions I have? Thanks.

We have tigervnc-users for that. It's both a mailing list and web forum (via Google groups). Links are at tigervnc.org.

**Comment by paul1149** [comment]
Thanks. I will check that out.

**Comment by CendioOssman** [comment]
Fixed in 3544999.
