### ISSUE TITLE
`error adding symbols` / `recompile with -fPIC` error

### ISSUE THREAD

**Issue by lucabelmondo** [TigerVNC/tigervnc#257]
I am a huge fan of TigerVNC, it is incredibly useful and valuable at both work and home.
I managed to build it with [this script][tiger-build] on trusty amd64, jessie amd64 and jessie armhf (Raspberry Pi).  

However, I can't get the build working on trusty armhf (crouton chroot on Chrome OS, Rockchip processor).
The output of the script is [here][build-output], but in summary it seems that the problem is the "recompile with -fPIC" bit. I've tried to add the CFLAGS=-fPIC to the configure step, to no avail.

I would greatly appreciate any help or pointers, thank you!

[tiger-build]: https://github.com/lucabelmondo/dotfiles/blob/eaa8c1990fccf723d3bc6f64a7e31a80cdf0cf02/scripts/tigervnc/package
[build-output]: https://gist.github.com/lucabelmondo/8b48506a686b830871bd

**Comment by CendioOssman** [comment]
Yeah, that's a bug. We only turn on `-fPIC` for x86_64. Need to have a look at that.

For now you can indeed specify `-fPIC`, but you need to give that to `cmake`, not `configure`. It has other arguments though, but `-DCMAKE_CXX_FLAGS="-O2 -fPIC"` should work.

**Comment by CendioOssman** [comment]
Should be fixed in 7b8ebff.

**Comment by lucabelmondo** [comment]
I just wanted to confirm that the change fixes the problem on the Rockchip processor of the Asus Chromebook Flip, where I was able to successfully build and package. 
Thank you @CendioOssman !
