### ISSUE TITLE
Provide portable Linux binaries for the armhf architecture

### ISSUE THREAD

**Issue by not-a-user** [TigerVNC/tigervnc#258]
It would be great to have portable binaries not only for i686 and x86_64, but also for armhf. armhf is in wide use (everybody has a Raspberry Pi, right?) and has support from Debian, Fedora, Arch, openSUSE and other Linux distributions.

TigerVNC is hard to build from the plain source tarball, because of all the manual handling of the xorg sources. I tried but failed on Ubuntu 14.04/armhf. So I assume TigerVNC is currently out of reach for the average Linux/armhf user.
##

**Comment by CendioOssman** [comment]
Probably a good idea, but it would be nice if we could have usable instructions on how to build Xvnc and libvnc.so. Unfortunately it's a bit distribution specific. But perhaps something to put in the wiki? We could have separate pages for each distribution that way.

(And Raspberry Pi would probably not be supported in such binaries. The distributions tend to target armv7hl and the Pi is armv6hl. The Pi2 might be fine though.)

**Comment by not-a-user** [comment]
I managed to build on Ubuntu 14.04/armhf using

	dget -d https://bintray.com/artifact/download/tigervnc/stable/ubuntu-14.04LTS/source/tigervnc_1.6.0-3ubuntu1.dsc
	dpkg-source -x tigervnc_1.6.0-3ubuntu1.dsc
	cd tigervnc-1.6.0/
	dpkg-checkbuilddeps
	# install reported missing dependencies, and then additionally:
	sudo apt-get install libcairo2-dev x11proto-dri3-dev libgcrypt20-dev x11proto-xcmisc-dev x11proto-present-dev
	patch -p0 << 'END_OF_PATCH'
	--- debian/rules.orig   2015-12-24 20:18:02.000000000 +0000
	+++ debian/rules        2016-01-05 06:13:49.386028397 +0000
	@@ -3,9 +3,9 @@
	 # GNU copyright 1997 by Joey Hess.
	 export DEB_BUILD_MAINT_OPTIONS=hardening=+all
	 
	-CFLAGS   := $(shell dpkg-buildflags --get CFLAGS)
	+CFLAGS   := $(shell dpkg-buildflags --get CFLAGS) -fPIC
	 CPPFLAGS := $(shell dpkg-buildflags --get CPPFLAGS)
	-CXXFLAGS := $(shell dpkg-buildflags --get CXXFLAGS)
	+CXXFLAGS := $(shell dpkg-buildflags --get CXXFLAGS) -fPIC
	 LDFLAGS  := $(shell dpkg-buildflags --get LDFLAGS)
	 
	 export CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
	END_OF_PATCH
	debuild -us -uc

The `-fPIC` is a dirty workarround, but otherwise I get linker errors. Sorry, I'm new to Debian packaging.

The problem is, this generates only `../tigervnc-java_1.6.0-3ubuntu1_armhf.deb`, but no other installable packages. However the binaries are there:

    $ file debian/tigervncserver/usr/bin/*
    debian/tigervncserver/usr/bin/tigervncconfig:   ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=26ea2c699c90f528df7523ba6fc31c047cd2aa53, not stripped
    debian/tigervncserver/usr/bin/tigervncpasswd:   ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=cd4e8c0edcaa196992b83c4da6d0181c20d257eb, not stripped
    debian/tigervncserver/usr/bin/tigervncserver:   Perl script, ASCII text executable
    debian/tigervncserver/usr/bin/x0tigervncserver: ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=eea282fd76607d3f1b642b19d2efa80bfa05d50c, not stripped
    debian/tigervncserver/usr/bin/Xtigervnc:        ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=792534cac0c130e9afc2020c26afad8a01354e20, not stripped

Any ideas why the server is not packaged? This is the build log: [tigervnc_1.6.0-3ubuntu1_armhf.build.zip](https://github.com/TigerVNC/tigervnc/files/78327/tigervnc_1.6.0-3ubuntu1_armhf.build.zip) Again, I'm sorry, but I'm new to Debian packaging.

**Comment by CendioOssman** [comment]
I'm afraid I don't know Debian packaging either. @bphinz?

**Comment by not-a-user** [comment]
I can build the Debian package on Ubuntu 14.04/armhf using:

	dget -d https://bintray.com/artifact/download/tigervnc/stable/ubuntu-14.04LTS/source/tigervnc_1.6.0-3ubuntu1.dsc
	dpkg-source -x tigervnc_1.6.0-3ubuntu1.dsc
	cd tigervnc-1.6.0/
	dpkg-checkbuilddeps
	# install reported missing dependencies, and then additionally:
	sudo apt-get install libcairo2-dev x11proto-dri3-dev libgcrypt20-dev x11proto-xcmisc-dev x11proto-present-dev
	patch -p0 << 'END_OF_PATCH'
	--- debian/rules.orig   2015-12-24 20:18:02.000000000 +0000
	+++ debian/rules        2016-01-05 06:13:49.386028397 +0000
	@@ -3,9 +3,9 @@
	 # GNU copyright 1997 by Joey Hess.
	 export DEB_BUILD_MAINT_OPTIONS=hardening=+all
	 
	-CFLAGS   := $(shell dpkg-buildflags --get CFLAGS)
	+CFLAGS   := $(shell dpkg-buildflags --get CFLAGS) -fPIC
	 CPPFLAGS := $(shell dpkg-buildflags --get CPPFLAGS)
	-CXXFLAGS := $(shell dpkg-buildflags --get CXXFLAGS)
	+CXXFLAGS := $(shell dpkg-buildflags --get CXXFLAGS) -fPIC
	 LDFLAGS  := $(shell dpkg-buildflags --get LDFLAGS)
	 
	 export CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
	--- debian/control.orig 2016-01-05 12:03:41.849480427 +0000
	+++ debian/control      2016-01-05 12:05:39.169169749 +0000
	@@ -7,7 +7,7 @@
	 Homepage: http://www.tigervnc.com
	 
	 Package: tigervncserver
	-Architecture: amd64 i386
	+Architecture: any
	 Provides: xserver, vnc-server
	 Depends: x11-common | xserver-common, x11-utils, xauth, libbz2-1.0, libc6, libfontenc1, libfreetype6, libgcc1, libgl1-mesa-dri, libgnutls28, libjpeg-turbo8, libp11-kit0, libpam0g, libpixman-1-0, libstdc++6, libtasn1-3-bin, libx11-6, libxau6, libxcb1, libxdmcp6, libxext6, libxfont1, libxtst6, zlib1g, libglu1-mesa, libxcursor1, libxinerama1, libxfixes3
	 Recommends: xfonts-base, x11-xserver-utils
	@@ -28,7 +28,7 @@
	  JPEG codec.
	 
	 Package: xtigervncviewer
	-Architecture: amd64 i386
	+Architecture: any
	 Provides: vncviewer, vnc-viewer
	 Depends: libc6, libexpat1, libfontconfig1, libfreetype6, libgcc1, libgnutls28, libjpeg-turbo8, libp11-kit0, libpng12-0, libstdc++6, libtasn1-3-bin, libx11-6, libxau6, libxcb1, libxdmcp6, libxext6, libxft2, libxrender1, zlib1g, libglu1-mesa, libxcursor1, libxinerama1, libxfixes3
	 Recommends: xfonts-base
	END_OF_PATCH
	debuild -us -uc

### Oservations:

There are some build-dependencies missing, but this should not be armhf specific.

`debian/control`: I had to set `Architecture: any` to actually get out the binary packages on armhf.

`debian/rules`: I had to add `-fPIC` in order to work arround linker errors. This is a dirty hack.

The resulting packages work for me.

**Comment by not-a-user** [comment]
There is a tigervnc 1.6.0 package in archlinuxarm which works fine.

**Comment by bphinz** [comment]
You're probably right about those build reps not being ARM-specific.  My build hosts probably just have those packages installed and so the build errors you covered were never exposed.  I'll take a look tonight and update the control/rules file.  I have no opposition to the other changes either.

**Comment by bphinz** [comment]
@not-a-user, I'm kicking off a new nightly build right now.  Can you try rebuilding the resulting source package and let me know if it works?  I updated the build-deps and architecture field in the control file, but did not add the '-fPIC' changes because I want to see if they're unnecessary after 7b8ebff.

**Comment by not-a-user** [comment]
@bphinz, builds on Ubuntu 14.04/armhf without modifications (using http://tigervnc.bphinz.com/nightly/ubuntu-14.04LTS/source/tigervnc_1.6.80+20160105git45a5a7b6-3ubuntu1.dsc). Resulting packages install and run smoothly for me. Great!

I suggest modifying the Ubuntu 12.04 control file as well (adding Architecture: any). I had a precise/armhf box running until recently.

**Comment by bphinz** [comment]
I just pushed that change, but I have no means of verifying that the Precise packages will build on any arm-based hardware.

**Comment by not-a-user** [comment]
@CendioOssman 

> And Raspberry Pi would probably not be supported in such binaries. The distributions tend to target armv7hl and the Pi is armv6hl. The Pi2 might be fine though.

And yet it should! A portable Linux/arm binary should probably be armv5te, hard-float EABI, little endian. I suggest using Archlinuxarm as the platform to build such a portable binary, because it is the only one that comes to my mind which has a readily available armv5 port.

The drawback might be the cutting-edge nature of Arch. If that introduces incompatibilities, raspbian might be a better candidate (but it is armv6 only).

What are the instructions used to build the nightly "Cross-compatible builds"? I will give it a try.

**Comment by bphinz** [comment]
The "cross-compatible" binaries are really nothing more than the contents of the el5 rpm packages extracted to a tar ball.  They are pretty much a bastard to create as it requires building a complete Xorg tree, along with many other pre-reqs, and statically linking them all.  You should be able to use the el5 spec file as a templates for you wish to go down this path, but to be honest I would avoid it like the plague...  I did some digging to see whether or not there is an mxe toolchain for arm similar to what I use to cross-compile the win32 and win64 binaries.  There was a ticket filed requesting arm support but it was closed for reasons similar to what Pierre suggested.

**Comment by not-a-user** [comment]
I see. But what about "Building the TigerVNC Server on Legacy Unix/Linux Systems" as described in `BUILDING.txt`? Does it work?

**Comment by not-a-user** [comment]
I just completed building of the Debian packages on raspbian-jessie/armhf (which is armv6). I used the trusty source packages with a few dependency corrections: 
[howto_build_jessie_packages.zip](https://github.com/TigerVNC/tigervnc/files/79707/howto_build_jessie_packages.zip)

This should work also for x86 builds on jessie. Can you provide a jessie source package? The differences from trusty are few, as you can see.

This solves the problem for me - a recent tigervnc is running on my trusty, raspbian-jessy, and archlinux ARMs.

Why is tigervnc not in the official Debian and Ubuntu repositories?

**Comment by bphinz** [comment]
On Wed, Jan 6, 2016 at 9:46 AM, not-a-user <notifications@github.com> wrote:

> I just completed building of the Debian packages on raspbian-jessie/armhf
> (which is armv6). I used the trusty source packages with a few dependency
> corrections:
> howto_build_jessie_packages.zip
> <https://github.com/TigerVNC/tigervnc/files/79707/howto_build_jessie_packages.zip>
>
> This should work also for x86 builds on jessie. Can you provide a jessie
> source package? The differences from trusty are few, as you can see.
>
Probably not packages at this point.  I'm basically at capacity in terms of
hardware for binary builds and more importantly, monthly AWS uploads.  In
fact, I had to scale back the build schedule from "nightly + SCM triggered"
to  "weekly + SCM triggered" in order to stay under the limit of 2000
PUTs/month.  The package specs could probably be kept under the
contrib/packages/deb directory alongside trusty & precise, but maintenance
of those is likely to be inconsistent without regular builds.

> This solves the problem for me - a recent tigervnc is running on my
> trusty, raspbian-jessy, and archlinux ARMs.
>
> Why is tigervnc not in the official Debian and Ubuntu repositories?
>
Not sure.  I had always hoped that providing an upstream package source
would encourage packagers from those distros to start including it, but so
far that hasn't happened.  The dependency on Fltk 1.3.3 is likely part of
the problem though, especially for the LTS flavors where they're locked
into a particular version.  On the other hand, if the Fltk packager is
willing to apply the patches that Pierre originally created (and were
subsequently merged into Fltk beginning with 1.3.3), then a fully
functional TigerVNC could be built against the native libraries even for
those distros where Fltk < 1.3.3 is supplied.  Adam Tkac worked with the
Fedora Fltk packagers to accomplish this, but we've never had an "inside
man" at any of the debian-based distros...

**Comment by not-a-user** [comment]
@bphinz 
> I just pushed that change, but I have no means of verifying that the Precise packages will build on any arm-based hardware.

I just finished building http://tigervnc.bphinz.com/nightly/ubuntu-12.04LTS/source/tigervnc_1.6.80+20160106git0260a9f9-3ubuntu1.dsc on a freshly debootstrapped precise/armhf. There are a few issues, but none of them seems armhf specific:

- `libgnutls28-dev` and `x11proto-xf86misc-dev` are actually in precise-updates and not in precise, so that repository must be activated.
- The build dependency `libgcrypt11-dev` is missing.
- I had to use `LC_ALL=C.UTF-8 debuild -us -uc` for building, becase in the `POSIX` locale the java build fails because of unicode characters in a source file:

	/home/muth/tigervnc_testing/tigervnc-1.6.80+20160106git0260a9f9/java/com/tigervnc/rfb/UnicodeToKeysym.java:38: error: unmappable character for encoding ASCII
		new codepair(0x01a1, 0x0104), /*                     Aogonek ?? LATIN CAPITAL LETTER A WITH OGONEK */

- Finally, there is a runtime dependency on `x11-xkb-utils`. Without it, `vncserver` fails with

	sh: 1: /usr/bin/xkbcomp: not found
	(EE) Error compiling keymap (server-2)
	(EE) XKB: Couldn't compile keymap
	XKB: Failed to compile keymap
	Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.

I tried the server, but not the client or java-client.

**Comment by bphinz** [comment]
On Fri, Jan 8, 2016 at 8:42 AM, not-a-user <notifications@github.com> wrote:

> @bphinz <https://github.com/bphinz>
>
> I just pushed that change, but I have no means of verifying that the
> Precise packages will build on any arm-based hardware.
>
> I just finished building
> http://tigervnc.bphinz.com/nightly/ubuntu-12.04LTS/source/tigervnc_1.6.80+20160106git0260a9f9-3ubuntu1.dsc
> on a freshly debootstrapped precise/armhf. There are a few issues, but none
> of them seems armhf specific:
>
>    - libgnutls28-dev and x11proto-xf86misc-dev are actually in
>    precise-updates and not in precise, so that repository must be activated.
>    - The build dependency libgcrypt11-dev is missing.
>    -
>
>    I had to use LC_ALL=C.UTF-8 debuild -us -uc for building, becase in
>    the POSIX locale the java build fails because of unicode characters in
>    a source file:
>
>    /home/muth/tigervnc_testing/tigervnc-1.6.80+20160106git0260a9f9/java/com/tigervnc/rfb/UnicodeToKeysym.java:38:
>    error: unmappable character for encoding ASCII
>    new codepair(0x01a1, 0x0104), /* Aogonek ?? LATIN CAPITAL LETTER A
>    WITH OGONEK */
>    -
>
>    Finally, there is a runtime dependency on x11-xkb-utils. Without it,
>    vncserver fails with
>
>    sh: 1: /usr/bin/xkbcomp: not found
>    (EE) Error compiling keymap (server-2)
>    (EE) XKB: Couldn't compile keymap
>    XKB: Failed to compile keymap
>    Keyboard initialization failed. This could be a missing or incorrect
>    setup of xkeyboard-config.
>
> I tried the server, but not the client or java-client.
>

Awesome, thanks for testing that out.  I'll make corrections tonight.

**Comment by not-a-user** [comment]
@bphinz 
> The dependency on Fltk 1.3.3 is likely part of the problem though, especially for the LTS flavors where they're locked into a particular version.

xenial will come with Fltk 1.3.3.

**Comment by bphinz** [comment]
The rest of those changes have been committed, with the exception of the libgcrypt-dev build dependency for trusty.  Trusty has libgcrypt11-dev and libgcrypt20-dev available and either one can satisfy the dependency, however the two are mutually exclusive and I haven't figured out how to specify that either one can be used (there appears to be a libgcrypt-dev meta package, but it seems as though it just resolves to libgcrypt11-dev).

**Comment by bphinz** [comment]
Oh, and the errors regarding non-ASCII characters in the comments should be cleared up.  I'm going to take a look and see if this can be corrected the "right way" in cmake, but for now this should be a workaround.

**Comment by tristan-k** [comment]
So is there a recommened way to build tigervnc for armhf. Would like to install it on my odroid-c1.

**Comment by tristan-k** [comment]
I found at build script [here](https://github.com/lucabelmondo/dotfiles/blob/master/scripts/tigervnc/package) from this [tweet](https://twitter.com/BlmLcu/status/681919945333161984). Trying it out right now. Will report back.

**Comment by tristan-k** [comment]
Building fails with the error: `recipe for target 'libvnc.la' failed`. I opened a issue at https://github.com/lucabelmondo/dotfiles/issues/2 but I'm not sure if this is related to the build script or tigervnc. I would be glad if someone could give proper instruction on how to build tigervnc on armhf devices.

**Comment by CendioOssman** [comment]
TigerVNC isn't really arch specific, so BUILDING.TXT is relevant for all Linux systems. ARM does hit that bug though, but it's already fixed in 7b8ebff2f8bdc8218fa8dcd066e8c53fe5ea0822. Could you try `master` instead of 1.6.0?

**Comment by rcarmo** [comment]
Guys, while you're at it, and even though bintray "works", is there any plan for having a PPA/debian repo we can apt-get from? Should I open another issue?

**Comment by bphinz** [comment]
There are plans for a Debian repo at this time. I can look into whether or
not it's possible with bintray, but last time I checked it was not (not for
multiple arch + multiple distro vers + multiple release versions anyway...).

-brian

**Comment by rcarmo** [comment]
"Are" or "are no"? Apologies, seemed a bit ambiguous.

**Comment by polrus** [comment]
any successes on building 1.8 on 16.04 arm?

**Comment by CendioOssman** [comment]
I'm sorry guys, but I'm going to close this. It doesn't look like we'll be expanding our builds anytime soon.

If you have issues building stuff then please discuss those on the mailing list, or open a new issue for the specific bug you are encountering.
