### ISSUE TITLE
vnctiger-server + Fedora23 & gdk critical error

### ISSUE THREAD

**Issue by FoLkjF** [TigerVNC/tigervnc#259]
#------------------------------------------------------------------------------------------------------------------------
** (polkit-gnome-authentication-agent-1:8560): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
Cannot register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
Xlib:  extension "VMWARE_CTRL" missing on display ":3.0".

(nm-applet:8599): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(nm-applet:8599): nm-applet-WARNING **: Failed to register as an agent: (32) An agent with this ID is already registered for this user.
#------------------------------------------------------------------------------------------------------------------------

just installed Fedora 23 Security spin. installed "vnctiger-server", when i execute vncserver the above is returned to the vnc log file. looks like some "gdk" error? is this a bug or is there a lib or something i need to isntall?

tia

**Comment by FoLkjF** [comment]
ok, i try gtk3-3.19.6-1.fc24.  thanks "BG" for the tip

**Comment by CendioOssman** [comment]
These errors come from the programs started with TigerVNC, and not from TigerVNC itself. So it's not really an issue from our end. You should report them to their respective projects (various Gnome components in this case).
