### ISSUE TITLE
Alt Shift causes keybindings to change

### ISSUE THREAD

**Issue by cookacounty** [TigerVNC/tigervnc#263]
For some reason, when Alt+shift is pressed and released, it is causing the "minus" and several other keys to rebind to some other random key. This behavior is repeatable.

Here is what I know:
* Same server is running VNC, my laptop does NOT have the issue, someone else does.
* Same version of VNCclient (we tried 1.6)
* tried vncserver 1.4x and 1.6, both have the issue.
* XFCE 4.12 desktop, ubuntu 14.04

Here is the log from xev when the problem happens:

![image](https://cloud.githubusercontent.com/assets/3683155/12594429/1a27462e-c444-11e5-961e-f2ae2abc8a6e.png)

Pressing ALT+SHIFT and releasing reverses the problem and the minus key once again works as usual!

**Comment by CendioOssman** [comment]
Not something I've ever heard of before. Could you run the client with full debug log so that we can see the key events sent? Add `-Log *:stderr:100` to the command line and save the output.

**Comment by cookacounty** [comment]
Is there a different command for windows? I tried this and didn't see any log.

![image](https://cloud.githubusercontent.com/assets/3683155/12949920/7b82bcec-cfd8-11e5-8514-23e65ecee4b1.png)

**Comment by CendioOssman** [comment]
Ah, right. Windows doesn't get a console so you need to use file logging.

Make sure `c:\temp` exists and that your user can write to it. Then you can start vncviewer with `-Log *:file:100` instead. At that point you should get a file in that directory.

**Comment by hildred** [comment]
That does make logging on a system without a c: drive difficult. Also
problematic is a system with the cdrom on c:. I have seen both.

On Wed, Feb 10, 2016 at 7:41 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Ah, right. Windows doesn't get a console so you need to use file logging.
>
> Make sure c:\temp exists and that your user can write to it. Then you can
> start vncviewer with -Log *:file:100 instead. At that point you should
> get a file in that directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TigerVNC/tigervnc/issues/263#issuecomment-182401629>.
>



-- 
--
Ben Hildred
Automation Support Services
303 815 6721

**Comment by CendioOssman** [comment]
Were you able to produce a log file?

**Comment by hildred** [comment]
> Were you able to produce a log file?

no, but I was not trying to as everything worked fine. But hardcoded paths have real drawbacks.

**Comment by CendioOssman** [comment]
Sorry, I meant that @cookacounty who was seeing the problem. :)

**Comment by DasCrane** [comment]
@cookacounty had filed this bug on my behalf, so he was waiting for my reply. I apologize for the delayed response. I'm fairly new to Git, so my formatting may be slightly off.

I followed @CendioOssman 's recommendation and the log file was produced successfully in Temp. My keystrokes (dashes included) were:--ALT+SHIFT--

The log reported the following:
"Mon Mar 14 10:23:19 2016
 Viewport:    Key pressed: 0x000c => 0x002d
 Viewport:    Key released: 0x000c => 0x002d
 Viewport:    Key pressed: 0x000c => 0x002d

Mon Mar 14 10:23:20 2016
 Viewport:    Key released: 0x000c => 0x002d
 Viewport:    Key pressed: 0x0038 => 0xffe9
 Viewport:    Key pressed: 0x002a => 0xffe1
 Viewport:    Key released: 0x0038 => 0xffe9
 Viewport:    Key released: 0x002a => 0xffe1

Mon Mar 14 10:23:21 2016
 Viewport:    Key pressed: 0x000c => 0x00df
 Viewport:    Key released: 0x000c => 0x00df
 Viewport:    Key pressed: 0x000c => 0x00df
 Viewport:    Key released: 0x000c => 0x00df"

I did this several times. One anomaly that did show up during several of the ALT+SHIFT presses, but doesn't seem to be the direct cause of the key binding change. The anomaly is bolded:

 "Viewport:    Key pressed: 0x0038 => 0xffe9
 Viewport:    Key pressed: 0x002a => 0xffe1
 Viewport:    Key released: 0x0038 => 0xffe9
** Viewport:    Unexpected release of key code 29**
 Viewport:    Key released: 0x002a => 0xffe1"

**Comment by CendioOssman** [comment]
It looks like it is switching from an American keyboard layout to a German one. Perhaps you have configured Alt+Shift to be the shortcut for switching layouts? You should be able to see the current active layout if you enable the language bar.

**Comment by DasCrane** [comment]
Looks like that was cause of the key binding switch. ALT+SHIFT was changing the keyboard layout in Windows, which ultimately changed the keys in my TigerVNC session. This bug should probably be closed as "invalid".
