### ISSUE TITLE
tigervnc Xvnc server will not listen only on 127.0.0.1

### ISSUE THREAD

**Issue by thestick613** [TigerVNC/tigervnc#264]
when i run
`./tigervnc/usr/bin/Xvnc -interface 127.0.0.1 -httpPort 0 -depth 24 -geometry 1024x768 -rfbport 5900 PasswordFile=./vnc_secret_password :1`

`netstat -nalp | grep vnc` will show me:
`tcp        0      0 127.0.0.1:5900          0.0.0.0:*               LISTEN      15336/Xvnc`
`tcp        0      0 0.0.0.0:6001            0.0.0.0:*               LISTEN      15336/Xvnc`

I'm trying really hard to get Xvnc to bind only to 127.0.0.1 (actually, to bind on my private vpn ip), but it seems it won't listen. I've tried adding the localhost switch, and binding on different ips, but it's not working.

**Comment by hildred** [comment]
You probably want to add `-nolisten tcp` to your command.

Here is what is going on: Xvnc is two servers in one, it is both a vnc and X server. The -interface option only applies to the vnc side of things. The X11 side of things has no direct equivalent (to the best of my knowledge), but can disable tcp transport, which works well with both local applications and ssh's x forwarding. The only times you need tcp X11 transport is when you are using xdmcp or you are running applications on hosts other than your display server and cannot use ssh (both cases are known to have security vulnerabilities and not recommended outside closed lans). the X11 options all come from Xorg (see the Xserver(1) man page for additional details) so if you need to tunnel x applications over your VPN and cannot use ssh you should file a bug report with Xorg first. once it is implemented upstream it will naturally become part of Xvnc.

**Comment by thestick613** [comment]
Thank you for your response. I've been suspecting X server as well, but i wasn't sure.

**Comment by hildred** [comment]
The giveaway was the port number 6001 corresponds to :1.

**Comment by jak3kaj** [comment]
Thanks, helped me out too!  Not the most obvious flag.
