### ISSUE TITLE
errors in miinitext.c

### ISSUE THREAD

**Issue by l29ah** [TigerVNC/tigervnc#265]
can't compile master with clang
```
../../mi/miinitext.c:118:30: error: a parameter list without types is only allowed in a function definition
extern void vncExtensionInit(INITARGS);
                             ^
../../mi/miinitext.c:331:41: error: invalid application of 'sizeof' to an incomplete type 'const ExtensionModule []'
    LoadExtensionList(staticExtensions, ARRAY_SIZE(staticExtensions), TRUE);
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../include/dix.h:67:31: note: expanded from macro 'ARRAY_SIZE'
#define ARRAY_SIZE(a)  (sizeof((a)) / sizeof((a)[0]))
                              ^~~~~
2 errors generated.
make: *** [Xvnc-miinitext.o] Error 1
```

**Comment by CendioOssman** [comment]
That file comes from Xorg and not TigerVNC, so I'm afraid it's not a bug we can do anything about. You need to file the bug with them.

(or try a different Xorg version and see if that works better)

**Comment by l29ah** [comment]
I don't see such a problem when i compile xorg in gentoo, and it seems the problem is that the required cpp macro is not provided to the source, so it might be a tigervnc build system's fault.

**Comment by CendioOssman** [comment]
The build system also comes from the Xorg sources, I'm afraid.
