### ISSUE TITLE
Chrome/ChromeOS/Chromebook viewer

### ISSUE THREAD

**Issue by bits01** [TigerVNC/tigervnc#275]
RealVNC has one, I think TigerVNC should have one too that's optimized to work with TigerVNC servers, can do screen resizing and other features that may be specific to TigerVNC.
https://chrome.google.com/webstore/detail/vnc%C2%AE-viewer-for-google-ch/iabmpiboiopbgfabjmgeedhcmjenhbla?hl=en

**Comment by CendioOssman** [comment]
That's the beauty of an open protocol like VNC, any VNC client can implement these features and be fully compatible with TigerVNC servers. We don't have the resources to take on another client implementation, so this is better handled by getting these features in to some existing Chrome VNC extension.
