### ISSUE TITLE
Linux Mint 17.3: starting 2 servers via init.d results in dconf spamming ~/.xession-errors for the 2nd user

### ISSUE THREAD

**Issue by bits01** [TigerVNC/tigervnc#276]
Linux Mint 17.3 x64 MATE (based on Ubuntu 14 LTS): tried to configure 2 VNC servers for 2 different users, to start automatically at boot via `/etc/init.d/vncserver` by configuring them in `/etc/default/vncservers`

The servers started, but for the 2nd user I noticed that `dconf` started spamming `~/.xsession-errors` with permission errors. The file grew to 100s of MB within minutes. It seems `dconf` is trying to access some file/directory that belongs to the 1st user, IIRC the path was something along the lines of `/var/run/user/<1st_uid>/dconf/...` which is not readable by the 2nd user.

Note that starting the 2 servers manually via a ssh session for each user seems to work without issues, it's only when started via the `/etc/init.d/vncserver` script.

**Comment by CendioOssman** [comment]
Odd. It should be changing to the relevant user before starting things. Can you check in `ps` that all processes are in fact running as the correct user?

**Comment by bits01** [comment]
Yes they are running as the correct user.

**Comment by CendioOssman** [comment]
Then I think you'll have to report this bug to dconf for now. If they have more specific needs than running as the correct user, then they'll have to specify those first.
