### ISSUE TITLE
How to install Tiger VNC 1.6 on CentOS 6 (hopefully using yum?)

### ISSUE THREAD

**Issue by eric-tvnc** [TigerVNC/tigervnc#285]
Having difficulties with Tiger VNC Viewer that I described in another post a few minutes ago.  Figuring that if I upgrade the problem might go away, I tried to upgrade from version 1.1 to version 1.6 and was not able.

Using CentOS's package manager, yum, the latest I am able to install is version 1.1.0 build 10/30/14.

If I download the 1.6.0 RPM and say "rpm -i tigervnc-1.6.0-1.el6.x86_64.rpm" I get:

error: Failed dependencies:
        tigervnc-icons is needed by tigervnc-1.6.0-1.el6.x86_64
        tigervnc-license is needed by tigervnc-1.6.0-1.el6.x86_64

So far I have not been able to find tigervnc-icons or tigervnc-license that are advertised as compatible with CentOS 6.  Anyway, I though RPM was supposed to manage all that stuff in the background (I know yum is supposed to handle it).

Anybody know a way to install version 1.6 via yum, i.e. is there a yum repository that has that version?

Thanks...

Eric

**Comment by bphinz** [comment]
RPMs for the latest stable release can be downloaded from bintray:

https://bintray.com/tigervnc/stable/tigervnc/1.6.0#files/el6/RPMS

RPMs for the current development tree can be downloaded from our nightly builds page:

http://tigervnc.bphinz.com/nightly/

We do not have a yum repository, but you can certainly install rpms via yum using 'yum localinstall …'.

HTH,
-brian

**Comment by eric-tvnc** [comment]
Thanks, Brian, I tried that earlier, and yum localinstall still fails on dependencies for tigervnc-license and tigervnc-icons.  The only versions of those files I can find for CentOS (and those are for Centos-7, not -6) are version 1.3.1.  I suppose I could try downloading and installing the -license and -icons files for Fedora 23 from rpmfind, and hope nothing else breaks...

**Comment by bphinz** [comment]
The license and icons packages are in the noarch directory:

https://bintray.com/tigervnc/stable/tigervnc/1.6.0#files/el6/RPMS/noarch

**Comment by eric-tvnc** [comment]
Thank you Brian.  That did it.

Eric
