### ISSUE TITLE
Installing TigerVNC Server on Centos 5.6 fails

### ISSUE THREAD

**Issue by eric-tvnc** [TigerVNC/tigervnc#286]
One of my servers, which I can not change or upgrade, is running the ancient CentOS 5.6 OS with RealVNC Server version 4.1.2.  I would like to replace that with TigerVNC server, latest version (1.6).

I removed the old version with "yum remove vnc" and "yum remove vnc-server".  Then, since I could not find any TigerVNC repositories that work with CentOS 5, I downloaded tigervnc-server-1.6.0-1.el5.i686.rpm and said "yum localinstall tigervnc-server-1.6.0-1.el5.i686.rpm".  It complained about missing dependency on tigervnc-server-minimal, so I downloaded and "yum localinstall'ed" tigervnc-server-minimal-1.6.0-1.el5.i686.rpm.

Now it complains about a missing dependency on tigervnc-license so I downloaded tigervnc-license-1.6.0-1.el5.i686.rpm.  When I go to install that with "yum localinstall tigervnc-license-1.6.0-1.el5.i686.rpm", yum looks like it's doing things correctly and then errors out with the following messages:

warning: rpmts_HdrFromFdno: Header V3 RSA/SHA1 signature: NOKEY, key ID 4582a460

Public key for tigervnc-license-1.6.0-1.el5.i686.rpm is not installed

Google was no help in finding a solution for this.

What else do I need to make this work?

Is there an earlier version of TigerVNC Server I should try?

Thanks...

Eric

**Comment by bphinz** [comment]
I don't know what the deal with that is either.  I started seeing it a few weeks ago, and like you have not been able to find out the cause of it.  There are tons of hits on google for that error message on el6, but the cause (a change to libnss) doesn't seem applicable.  Forcing the installation will cause subsequent rpm/yum operations to spew that message and potentially fail.  The only workaround that I have found is to remove the gpg signature with 'rpmsign --delsign ...' and then install the packages.

Note that we've really only been dragging the el5 RPMs along for the purpose of having a source of statically linked binaries to distribute as "cross compatible".  However they've become so impossible to maintain that Pierre has picked up generation of the cross compatible binaries (using Cendio's build system) and we're not going to provide el5 packages anymore.  You can get the tarball for the latest snapshot of those builds from the nightly builds page, under the "Cross-compatible builds" section:

http://tigervnc.bphinz.com/nightly/

**Comment by eric-tvnc** [comment]
Good morning, Brian.

"rpmsign --delsign" just makes yum complain about the package not being signed.

So I dug a little deeper and ended up using the yum --nogpgcheck to install license, then minimal, then vnc-server.  That seems to have worked, in that the TigerVNC server is up and running, sort of.

I say "sort of" because I still can't log into the server, which is the problem that prompted me to start this report to begin with.  But... that's a topic for another report.

Thanks...

Eric

**Comment by bphinz** [comment]
Correct, without a signature you need --nogpgcheck.  That's a yum-ism though.

Please try the Cendio cross-compatible build form the nightly builds page and see if that works.

Thanks,
-brian
