### ISSUE TITLE
vncserver sets vncClasses path wrongly in SanityCheck

### ISSUE THREAD

**Issue by ercanal** [TigerVNC/tigervnc#295]
There is a problem with SanityCheck function in vncserver. java classes are under ../share/vnc/classes but this function sets this path to 
$vncClasses = "$_/../vnc/classes";
##

**Comment by CendioOssman** [comment]
Quite right. Although later code will try the standard `/usr/share/vnc/classes`, so in many cases it will work anyway.

**Comment by CendioOssman** [comment]
Hmmm... actually it's a bit undefined at this point where they end up as the Java build system never defines `${DATA_DIR}`. The sane option is somewhere under /usr/share though. @bphinz, could you have a look at adjusting it? `${CMAKE_INSTALL_PREFIX}` should probably be respected.

**Comment by bphinz** [comment]
Will do.  Thanks.

**Comment by ercanal** [comment]
I am using from my home directory and don't have permision to write /usr/share/vnc.
I fixed my script's vncClasses lines as below and able to connect with java client. 
$vncClasses = "$_/../vnc/share/classes";

If I understand correctly, please don't set fixed path for vncClasses directory.

**Comment by bphinz** [comment]
On Fri, Apr 22, 2016 at 10:12 AM, ercanal <notifications@github.com> wrote:

> If I understand correctly, please don't set fixed path for vncClasses
> directory.
>
Yeah, I agree that it should probably look for the class path relative to
the Xvnc binary that was invoked, rather than relative to the system root.
