### ISSUE TITLE
server configuration is ignored when server is started from command line spawned by SSHD

### ISSUE THREAD

**Issue by oldunixguy** [TigerVNC/tigervnc#297]
host is win 7 pro 64 bit. host runs freesshd. client computer runs putty to host with a tunnel for port 5900.
Installed tigervnc using the host desktop. did not run as service since I want to manually run and shutdown this server via cmd line. using the sys tray configurer I disabled the port 5800 java connection and set the VNC server password.
If I manually start the server from the host desktop this works. TCP port 5900 has a listen and there is NO listen on 5800 as expected.
If I started it from the desktop I CANNOT stop it from the client SSHD cmd line. It complains about permission. I can only use the systray interface to stop it.
If I instead start the server thru the remote cmd line it does NOT apply any of the configuration settings done thru the sys tray interface in the step earlier. I can tell this simply because the password set doesnt work AND it posts TCP listens on both 5900 and 5800.
I need to be able to configure, start and shutdown this server running in application mode from this SSHD cmd line.
I don't need to be able to start from the desktop and shutdown from the cmd line and vice versa (but it would be nice if this worked).
How can I make this work all from the cmd line (config, start and shutdown in appl mode)?
thanks
oldunixguy

**Comment by CendioOssman** [comment]
WinVNC reads configuration from HKEY_CURRENT_USER when run in user mode (i.e. not service mode). Could it be that you configured the service mode in your first step?

It might also be that freesshd runs your session as a different user than when you log on locally.

**Comment by oldunixguy** [comment]
not possible. I also did a complete uninstall and reinstalled making sure I did not use the service mode.

what IS possible is that there is some user difference between what the cmd line shell spawned by freesshd and what happens when I sign in to the host win 7 desktop.

Regardless.... one MUST be able to create a configuration that when the server .exe is started manually it is used.

How does one do this?
Why does a configuration exist and can be seen and edited using the desktop startup and configuration tool and NOT when the server .exe is started from the cmd line?
Stated differently, how does one create and edit a configuration for solely using the cmd line interfaces?
I can find ZERO information on this.
thanks
oldunixguy

**Comment by CendioOssman** [comment]
> Why does a configuration exist and can be seen and edited using the desktop startup and configuration tool and NOT when the server .exe is started from the cmd line?

Have you actually tested this? Because that works fine when I'm testing here. Starting it through freesshd is not the same thing. If it works when starting it from the command line locally, but not in freesshd, then I'm afraid the problem is with freesshd.

> Stated differently, how does one create and edit a configuration for solely using the cmd line interfaces?
> I can find ZERO information on this.

You can't really. Hence no documentation. WinVNC expects a GUI for configuration.

**Comment by oldunixguy** [comment]
yes i have tested this. it is fully repeatable. i have it this way (in this
dysfunctional state) on my win 7 pro still.

So you are implying that 1) one must use the GUI to configure it and 2)
that config is supposed to be automatically used when the cmd line server
invocation is used?

My demonstration shows this is not true. My proof is that when started from
the win desktop and configured then that config is NOT used when the server
is manually started from the cmd line. The specific element for proof is
that I disable the port 5800 java listener in the GUI. I start the server
from windows by double clicking on the server exe. I use the process
explorer to see that the server process has only tcp port 5900 with a
listener. I close down and restart windows. I confirm no server process is
running (shouldn't be because I dont want it automatically started from
windows services) by using process explorer. I then use the cmd line
produced from freesshd to start the server. Then look at the process
explorer. this shows that the server process has 2 tcp ports: 5800 and
5900. This should bot be. I conclude that starting from the freesshd cmd
line htat none of the "configuration" set by the windows GUI is being used.

How else can this be?

What other diagnostic info can I provide? I really need this to work
without windows auto starting this server but rather done on manually from
the freesshd cmd line.

thanks
rich

On Mon, May 2, 2016 at 3:14 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Why does a configuration exist and can be seen and edited using the
> desktop startup and configuration tool and NOT when the server .exe is
> started from the cmd line?
>
> Have you actually tested this? Because that works fine when I'm testing
> here. Starting it through freesshd is not the same thing. If it works when
> starting it from the command line locally, but not in freesshd, then I'm
> afraid the problem is with freesshd.
>
> Stated differently, how does one create and edit a configuration for
> solely using the cmd line interfaces?
> I can find ZERO information on this.
>
> You can't really. Hence no documentation. WinVNC expects a GUI for
> configuration.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TigerVNC/tigervnc/issues/297#issuecomment-216165408>
>



-- 
Richard A. Painter, P.E.

Homeless from the Black Forest Colorado Forest Fire

AMERICA- Designed by geniuses, Run by idiots, fools and criminals!

**Comment by CendioOssman** [comment]
Given your description it is apparent that this only happens when started from freesshd. So it is either a) running things as a different user, or b) starting things with insufficient privileges to read the configuration from the registry. Neither of which are TigerVNC issues. So I'm afraid I'll have to direct you to file a bug with freesshd.
