### ISSUE TITLE
tigervnc-license RPM not available

### ISSUE THREAD

**Issue by jblaine** [TigerVNC/tigervnc#301]
Properly installing tigervnc-server (from Bintray) via `yum` is not possible since there is no tigervnc-license RPM available there.

Likewise, installing tigervnc (ergo viewer) via `yum` fails because there's no tigervnc-icons RPM available there either.

**Comment by jblaine** [comment]
Doesn't work via straight `rpm` either, unless you work around the tigervnc-license requirement with `rpm -i --nodeps`

**Comment by bphinz** [comment]
You didn't say which version, but I just checked v1.6.0 and both the license and icons packages are there for both el5 and el6.  On el6 they are in the 'noarch' folder because they are architecture independent.

-brian

**Comment by jblaine** [comment]
Ohhh! Thanks Brian.
