### ISSUE TITLE
Version 1.6.0 incorrectly registers service

### ISSUE THREAD

**Issue by thelonelyprogrammer** [TigerVNC/tigervnc#306]
When creating the "TigerVNC Server" service, what intends to be the service description ("Provides remote access to this machine via the VNC/RFB protocol.") is actually set as the service display name. This creates a few problems, for example the service is not show up in the "Services" application.

This problem is due to win\winvnc\winvnc.cxx, line 172, passing the service description as the 2nd parameter instead of passing the service name.

I am unsure what the service name intends to be, I suspect it is the same as the service key name, "TigerVNC Server". The (optional) service description would need to be set with ChangeServiceConfig2(), although it is often easier to simply set the description directly in the registry (I usually do that).

I'm happy to check in a fix, including code which sets the service description.

The only issue is that my build environment is strictly VS, it would take me some time to setup a build environment and properly test it.

**Comment by CendioOssman** [comment]
This was fixed in 018c67e6e1cdfb5e0494ad987093738b7fe7e60d, so it will be included in the next release.
