### ISSUE TITLE
CTRL-ALT-DEL does not work [$50]

### ISSUE THREAD

**Issue by thelonelyprogrammer** [TigerVNC/tigervnc#308]
I'm installing TigerVNC on a Windows 2008 server (32-bit), and sending CTRL-ALT-DEL does not work when sent from the F8 context menu. Nothing happens.

I do not understand how to enable logging (nothing shows up in C:\Temp which appears to be the hard-coded path) so I'm limited to what I can do myself since I'm fairly new to the software/project.

I've previously used 1.4.3 with 64-bit machines, where this works without issue.

**Comment by CendioOssman** [comment]
Which versions have you tried on the 32-bit machine? Have you tried the same 1.4.3?

**Comment by thelonelyprogrammer** [comment]
I tried 1.43, 1.5 and 1.6

**Comment by thelonelyprogrammer** [comment]
Is there something I can do on my end to troubleshoot this? Happy to help. Is there a way to enable logging? I also just noticed the "bounty", will look at that.

**Comment by PlasmaPower** [comment]
I'm not an expert, but this may be due to the fact that Ctrl+Alt+Del handling is handled my the Windows kernel itself, not in userspace IIRC.

**Comment by thelonelyprogrammer** [comment]
@PlasmaPower That's not the issue, it works fine with the 64-bit client, and other software is able to do it as well (e.g. VMWare, etc.).

**Comment by PlasmaPower** [comment]
@thelonelyprogrammer I'm not saying that it's the only problem or that it's insurmountable, it just probably has something to do with it.

**Comment by thelonelyprogrammer** [comment]
I just increased the bounty, it would be great to get a fix for this issue soon. Thank you.

**Comment by camgaertner** [comment]
i am giving this a go. thelonelyprogrammer, can u elaborate on if the bug is with sending a ctrl alt delete from win2008 via the viewer, or if it is receiving one via the server?

**Comment by thelonelyprogrammer** [comment]
The viewer was running on Win 8.1, 2008 is running on the server on which the CTRL-ALT-DEL should have been executed. However, it appears to affect not just 2008, seem to affect 2012 (incl. R2) as well. It should be easy to reproduce.

**Comment by camgaertner** [comment]
Okay thanks. I'm having some issue running tigervnc-1.6.0. I double checked, and I downloaded the 32 bit binary [here](https://bintray.com/tigervnc/stable/tigervnc/1.6.0), but it's simply not opening. Any thing else to reproduce this on 1.6?

**Comment by thelonelyprogrammer** [comment]
Not really, I didn't have to do anything unusual to reproduce it - just installed it. Like I mentioned earlier, it happens with 1.43, 1.5 and 1.6. Maybe try 1.5? I know there is a bug with the service installation in 1.6 that has been fixed in the repository, not sure if an updated installer is available yet.

**Comment by camgaertner** [comment]
Thanks, I'll try that out.

**Comment by bphinz** [comment]
The current nightly builds should have the fix for the installer.

-brian

**Comment by niterain** [comment]
I believe it is a registry setting you have to set in order for this to work.

You can either go via your Group Policy Editor, or use your registry editor to change:

HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System to 3

Then test.

**Comment by thelonelyprogrammer** [comment]
Thank you. It looks like a new beta was released, I'm currently trying to see if that will work ok due to the other issues I ran into with earlier releases. Unfortunately it's completely unusable on Windows in its current state, I will report back.

**Comment by thelonelyprogrammer** [comment]
I decided to move to the UltraVNC project, I've just run into too many issues with TigerVNC and Windows (which apparently is never tested by the developers). It's difficult when there is not even an installer that actually works - 2 versions in a row. Thank you.

**Comment by seselunalo** [comment]
F8 on your keyboard will open a context menu. In there you will find "send ctl-alt-del"

**Comment by Mamooshi** [comment]
i just do this:
fn conrtol command delete in mac and works
