### ISSUE TITLE
unable to load libvnc.so after installing 1.6.0

### ISSUE THREAD

**Issue by jhnelson** [TigerVNC/tigervnc#311]
Current build will not load because of version mismatch:

from Xorg.0.log:
[    29.077] (II) LoadModule: "vnc"
[    29.077] (II) Loading /usr/lib/xorg/modules/extensions/libvnc.so
[    29.612] (II) Module vnc: vendor="TigerVNC Project"
[    29.612]    compiled for 1.11.3, module version = 1.0.0
[    29.612]    Module class: X.Org Server Extension
[    29.612]    ABI class: X.Org Server Extension, version 6.0
[    29.612] (EE) module ABI major version (6) doesn't match the server's version (8)
[    29.612] (II) UnloadModule: "vnc"
[    29.612] (II) Unloading vnc

testing with tigervncserver_1.6.80+20160516git044e2b87-3ubuntu1_amd64.deb from:http://tigervnc.bphinz.com/nightly/

Please advise,

**Comment by CendioOssman** [comment]
Did you download the correct one? Looks like you used the 12.04 version on 14.04.

@bphinz, would it be wrong to add some suffix to the packages? It's a bit confusing to have the same name (even though Ubuntu and Debian seem to use that model themselves).

**Comment by jhnelson** [comment]
Sorry. It works when you can read....

**Comment by CendioOssman** [comment]
No problem. It happens to the best of us. :)

**Comment by jhnelson** [comment]
updated my xorg.conf file as well. removed superfluous x4vnc config
