### ISSUE TITLE
[question] is there a way to hide vncviewer window?

### ISSUE THREAD

**Issue by goog** [TigerVNC/tigervnc#312]
after logined in vncserver,  i did not need to keep vncviewer live,  then could record the vnc video at background. but i don't have some idea about how to hide **the vncviewer window**, so need you give some guide

**Comment by CendioOssman** [comment]
In most cases no. It's really up to your window manager to offer such a feature. And I don't see it appropriate to add such a feature to vncviewer directly. If you want to record your session then there are other tools available.
