### ISSUE TITLE
Support system-wide UNIX/Linux Xvnc forced options

### ISSUE THREAD

**Issue by jblaine** [TigerVNC/tigervnc#317]
I'm proposing pretty simply edits to the `vncserver` perl script which will allow administrators a sane way to configure system-wide Xvnc options which override user defaults found in `$HOME/.vnc/config`

After the block https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver#L276-290 , system-wide options will be read from < taking-suggestions-for-filename-and-path > which then override only those options that were already set in `$config`

If the system-wide options file (yet to be named) does not exist, `vncserver` will function exactly as it always has.

Likewise, I will update the `vncserver` man page.

This will provide a way to at least **attempt** to enforce some default policy, such as TLS, through the most commonly used means of starting UNIX/Linux Xvnc sessions. It is fully understood that this system-wide preferred policy could be subverted by someone constructing their own `vncserver` script, running `Xvnc` by hand, etc.

Before I start on the code, are there objections? I intend to start work on the code + doc June 2.

**Comment by CendioOssman** [comment]
As mentioned on the mailing list, I think we need both defaults and overrides. And also careful wording since it is indeed easy to override so we shouldn't give anyone a false sense of security. Other than that, go for it. :)

Also, I think we should avoid adding more generic "VNC" naming. `/etc/tigervnc` or similar is better. We aren't the only VNC implementation. :)

**Comment by jblaine** [comment]
I want to make sure we've agreed on the same thing before I start:

1. Various defaults will remain set in vncserver, hardcoded as they are now[1]
2. A user config file, if it exists, will be loaded[2]
3. To be written: A system-wide config file, if it exists (and it won't by default) will be loaded and **its settings will override any configured by the user config file**

Footnotes:

1.
```
$default_opts{desktop} = &quotedString($desktopName);
$default_opts{httpd} = $vncJavaFiles if ($vncJavaFiles);
$default_opts{auth} = $xauthorityFile;
$default_opts{geometry} = $geometry if ($geometry);
$default_opts{depth} = $depth if ($depth);
$default_opts{pixelformat} = $pixelformat if ($pixelformat);
$default_opts{rfbwait} = 30000;
$default_opts{rfbauth} = "$vncUserDir/passwd";
$default_opts{rfbport} = $vncPort;
$default_opts{fp} = $fontPath if ($fontPath);
$default_opts{pn} = "";
```

2.
```
# if a user configuration file already exists
if(stat("$vncUserDir/config")) {

  # loads and parses configuration file
  if(open(IN, "$vncUserDir/config")) {
    while(<IN>) {
      next if /^#/;
      if(my ($k, $v) = /^\s*(\w+)\s*=\s*(.+)$/) {
        $config{$k} = $v;
      } elsif ($_ =~ m/^\s*(\S+)/) {
        $config{$1} = $k;
      }
    }
    close(IN);
  }
}
```

**Comment by CendioOssman** [comment]
Sounds good.
