### ISSUE TITLE
Application interface font

### ISSUE THREAD

**Issue by neilunderwood** [TigerVNC/tigervnc#318]
Not really an functionality issue so much so a personal preference issue.  I've been holding out upgrading from v1.40 simply because everything newer introduces a horribly ugly font in the tigervnc interface.  Where exactly is the config file to change this font?  Or is it even possible to do so?

I notice that v1.60 has a fontconfig folder with a bunch of binary cache files in it, which was not present in v1.40.

**EDIT**
I should add that I'm running the 64-bit Linux v1.60

**Comment by CendioOssman** [comment]
We haven't changed anything font related since the new viewer was introduced (1.2.0 I think). So it is most likely something in the build environment that has changed. Which builds are you comparing? Ours?

Could you attach screenshots?

**Comment by CendioOssman** [comment]
No response. Closing.
