### ISSUE TITLE
Multiple keystrokes registered on vnc server

### ISSUE THREAD

**Issue by flyingrhinonz** [TigerVNC/tigervnc#320]
Using latest tiger vnc server on linux mint 17.3 xfce and latest tigervnc viewer on win 8.1

Starting the vnc this way:
x0vncserver -display :0 -rfbport 5900  -passwordfile ~/.vnc/passwd -Log *:stderr:30 -BlacklistThreshold 10 -BlacklistTimeout 5 -MaxProcessorUsage 70 -DeferUpdate 1

When typing alphanum or even contols (such as space, backspace, del) , sometimes many keystrokes are registered on the remote machine.

Easily seen in the "start menu" of xfce, or in thunderbird client.

If any further debugging or logs are required please contact me.
Thanks

**Comment by CendioOssman** [comment]
This could just be over eager keyboard repeat in your X server. Could you try disabling keyboard repeat in Xfce and see if that gets rid of the problem?

**Comment by flyingrhinonz** [comment]
> Could you try disabling keyboard repeat in Xfce and see if that gets rid of the problem?

Thanks for the tip, I'll make this change tomorrow and advise. If you are correct, we could add this as an item in the FAQ

**Comment by flyingrhinonz** [comment]
Hi,

I confirm it is working properly with REPEAT DELAY = 700 , REPEAT SPEED = 20
At least from 2-3 different remote sites I could try.

Thanks
