### ISSUE TITLE
windows service doubled (i.e. also running twice), unable to clean up

### ISSUE THREAD

**Issue by calestyo** [TigerVNC/tigervnc#324]
Hi.

At some point, the Windows service definition name and display name apparently changed from
name=WinVNC4
display name=VNC Server Version 4
to
name=TigerVNC Server
display name=Provides remote access to this machine via the VNC/RFB protocol

1) The new display name is IMHO a bit unfortunate, as it's rather that what MS understands as the "service's description"... this new display name makes it pretty hard to find the service in the list.

2) Apparently when the name was changed the old one wasn't cleaned up properly. So now I have two of them, and yes both actually run, and I see actually two icons for it in the system tray (interestingly with different icons).
-unregister only cleans up the new one, but not the old.
So please add code to clean up the legacy cruft.

Cheers,
Chris.

**Comment by CendioOssman** [comment]
Good point. We've fixed the whole description mess, but there is no cleanup.

**Comment by CendioOssman** [comment]
Fixed in ed92079.

**Comment by calestyo** [comment]
> Good point. We've fixed the whole description mess, but there is no cleanup.

Well as I've said, what you now set as "description" is AFAIU rather used as display name and should therefore be something like "TigerVNC VNC/RFP protocol server" or so.

The actual "description" field in Windows seems to be empty.

Cheers,
Chris.

**Comment by CendioOssman** [comment]
In 1.6.0, yes. But master has a proper fix with both display name and description.

**Comment by calestyo** [comment]
+1 Thanks :)
