### ISSUE TITLE
default xstartup and xclient config files

### ISSUE THREAD

**Issue by durack1** [TigerVNC/tigervnc#325]
Are there `xstartup` and `xclient` default config files located somewhere in the tigerVNC repo?

I'm interested in reconfiguring my vnc environment on a new RHEL 7.2 installation, however am a little uncertain of how best to initialize the KDE or GNOME environments using the available config files.

I think it'd be best that I start from scratch with `tigerVNC 1.6.0` default files if they exist. Alternatively, is there a good website that outlines the configuration options for RHEL 7.2?

**Comment by CendioOssman** [comment]
Well, it depends. There are two "normal" ways to start TigerVNC; either via `vncserver`, or via XDMCP. `vncserver` uses `~/.vnc/xstartup` and the default contents is hard coded in to `vncserver`. XDMCP is controlled by your display manager (commonly GDM or LightDM) and will most likely use your global system configuration.

**Comment by durack1** [comment]
@CendioOssman thanks for pointing that out, I've now found the defaults for [xstartup and config files](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver#L58-L93) and these seem similar to what I've seen before.

With particular focus on RHEL 7.2, this OS no longer ships with `twm` and I'm fairly sure that it's also not a default inclusion in RHEL 6.x. For that reason I'm wondering whether `gnome-session` or `startkde` should be a better default window manager to be specified in `vncserver`? I also do wonder whether the `/opt/gnome/bin` path for `SuSE-release` is also still valid for the modern OSes?

**Comment by CendioOssman** [comment]
That thing probably needs a revamp, yes. We may want to consider executing the distro scripts rather than our own.
