### ISSUE TITLE
tigervnc-1.4.2 -> 1.6.0 upgrade causes vinagre, remmina not be able to authenticate

### ISSUE THREAD

**Issue by lkraav** [TigerVNC/tigervnc#326]
I finally managed to connect with Remmina by using "Disable encryption" checkbox in the connection profile's Advanced tab.

For failed connections, this is what I see in server log

```
Sun Jul  3 00:10:35 2016
 Connections: accepted: 192.168.1.2::41706

Sun Jul  3 00:10:36 2016
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VeNCrypt(19)
 Connections: closed: 192.168.1.2::41706 (Clean disconnection)
```

Is there something I need to explicitly specify for `vncserver` now?

**Comment by CendioOssman** [comment]
Looks like vinagre might be one of those implementations that has some sub-optimal handling of VeNCrypt. Could you try a nightly build? We added some compatibility hacks not too long ago.

**Comment by lkraav** [comment]
Gentoo doesn't seem to have a git ebuild in the tree. Might delay this operation. I could easily apply individual patches on top of 1.6.0 though, if a few relevant hashes would be presented.

**Comment by lkraav** [comment]
I just noticed `1.6.90` is released and tested it. Vinagre's connection problems have been solved.
