### ISSUE TITLE
Error! VNC connection failed! null after about 2 seconds of connection

### ISSUE THREAD

**Issue by merinleona** [TigerVNC/tigervnc#330]
i can't get VNC to work, it connects I can type things etc. for about 2 seconds and then I get the Error. Does someone have an idea why? I am using AndroidVNC on Android. I also tried the RealVNC app, it just said connection closed unexpectectly.

**Comment by CendioOssman** [comment]
Does it work when you connect from a regular PC?

**Comment by merinleona** [comment]
I did not test that, I tried another VNC client for my PC and it worked.

**Comment by CendioOssman** [comment]
In that case it sounds like a problem in those clients. Please file a bug report with them.
