### ISSUE TITLE
missing libsystemd-daemon

### ISSUE THREAD

**Issue by mpkh** [TigerVNC/tigervnc#331]
libsystemd-daemon is now merged into libsystemd

**Comment by CendioOssman** [comment]
We do not use libsystemd anywhere. What is the issue you are seeing?

**Comment by mpkh** [comment]
@CendioOssman right, not sure where does it came from, for now I can't reproduce it but it was somewhere there https://github.com/TigerVNC/tigervnc/tree/master/unix/xserver/hw/vnc maybe flags came from an external library/project

**Comment by CendioOssman** [comment]
Probably. libtool can have a tendency to drag in extra dependencies, so a rebuild can be required if you swap out local libraries.

**Comment by mpkh** [comment]
@CendioOssman well... currently tigervnc package with systemd support use flag is completely broken in gentoo and it's not about rebuild since there it's using clean sandbox, something is pulling outdated linking flags for systemd and I was unable to discover what exactly.
