### ISSUE TITLE
dridir option not working in vncserver 1.6.90

### ISSUE THREAD

**Issue by gmgo** [TigerVNC/tigervnc#333]
Hello,

I was using tigervnc 1.6.0 successfully with the option

-dridir <install_path>/usr/lib64/tigervnc/dri/

as path to the  swrast_dri.so  library.

This way,  the session was managing OpenGL applications duly.

With new 1.6.90 ,  the -dridir option seems not supported as I get an error when using it.

This is same issue occurrence as in the past,  see former post for reference

https://groups.google.com/forum/#!topic/tigervnc-users/CCcbTUqWQ10

Thanks

Regards

**Comment by bphinz** [comment]
Which build are you using?

-brian

**Comment by gmgo** [comment]
I downloaded and tried 
tigervnc-1.6.90.x86_64.tar.gz

**Comment by CendioOssman** [comment]
None of our builds include that extra patch anymore, but rather use a plain Xorg source.
