### ISSUE TITLE
/VERYSILENT install not allowing connection

### ISSUE THREAD

**Issue by adamreed90** [TigerVNC/tigervnc#335]
I have created a windows service that runs the /VERYSILENT install of TigerVNC on Windows, then starts the service. When attempting to connect to the service once it's running, I get.

**No password configured for VNC Auth**

What can I do to set the password via MSI. I have tried to run the config program after, but the winvnc4.exe is running via SYSTEM user, which seems to not have any Registry settings I can edit.

**Comment by CendioOssman** [comment]
In service mode it reads the configuration from HKLM rather than HKCU, so you should be able to store the configuration you need there.
