### ISSUE TITLE
default options interfere with text selection in other apps

### ISSUE THREAD

**Issue by Osndok** [TigerVNC/tigervnc#337]
I'm currently running Fedora 24 with a functional mix of Qt & GTK stuff.

I've noticed that whenever tigervnc is running (1.6.90) and I start to select text using either the mouse (dragging) or the keyboard (shift+arrow keys) in a *GTK* application (such as gedit) the selection will quickly be reset. This makes a rather fun and interesting 'worm' effect as the small selection moves, but is undesirable because it makes it nearly impossible to actually select text.

Qt/KDE applications (such a kwrite) do not seem to be effected.

An easy workaround is to add "-SendPrimary=off" to the vncviewer command line arguments, so I perceive this to be a rather minor bug.

Perhaps the default option should be to use only the secondary (more deliberate) clipboard? Perhaps there is an official gtk-way to passively get the selected text? I don't know what the best solution would be.

**Comment by CendioOssman** [comment]
The text is already grabbed passively. And this scenario normally works just fine. Most likely you have some program grabbing the clipboard inside your VNC session (e.g. a clipboard manager). This causes the clipboard to bounce back to the client.

**Comment by Osndok** [comment]
Ok... I think I understand... so the real issue, then, is that the remote side is continuously requesting the keyboard. I think it must be some unknown kludge in Vine Server, then, that intends to adapt the vnc/unix clipboard paradigm to the Apple APIs... sorry for the noise.
