### ISSUE TITLE
Mouse is trapped in first screen. Multiscreen.

### ISSUE THREAD

**Issue by juaningan** [TigerVNC/tigervnc#338]
Hi, I'm running TigerVNC (both stable and beta version) with:
/usr/bin/Xvnc :0 -screen 0 1280x1024x24 -screen 1 1024x768x24 -screen 2 1024x768x24

Then the mouse is trapped in first screen (:0.0). If I move local mouse in 2nd vncviewer (against screen :0.1) the movement happens but just in first screen.

My use case is a legacy multi monitor application that is hardcoded to :0.0, :0.1 and :0.2.
Running Xorg with dummy driver and x11vnc over it is working correctly.

Thanks in advance.

**Comment by CendioOssman** [comment]
Turned out there was a whole bunch of broken things. It should be fixed on `master` now though.
