### ISSUE TITLE
win10 vnc connection always timeout

### ISSUE THREAD

**Issue by richardweiu** [TigerVNC/tigervnc#342]
Why I use vncviewer always timeout 10060 at win10

I use ubuntu 16.04.It can work,so not vnc server's problem

**Comment by CendioOssman** [comment]
That could be caused by a firewall blocking access to the VNC server. Have you opened up the relevant port(s) on your Ubuntu server and any firewall between the server and client?

**Comment by richardweiu** [comment]
I have close the windows and ubuntu firewall

**Comment by CendioOssman** [comment]
Then you should check any other network equipment between the machines. Error code 10060 is caused by network issues and not by TigerVNC.
