### ISSUE TITLE
Sticky Alt key

### ISSUE THREAD

**Issue by hans109h** [TigerVNC/tigervnc#343]
I use TigerVNC 1.6.9 as my VNC server, however due lack of permissions I have to use the TightVNC 2.8.2 java viewer.  

When I use Alt-Tab to switch between the java view and other local windows, and then switch back to the java viewer I find that the Alt key is stuck on.  

The TightVNC website reports this about beta version 2:  "New viewer will reset keyboard modifiers to their actual state on restoring keyboard focus. That was a long-term problem of the viewer. After leaving the viewer window with Alt+Tab and returning to the viewer again, Alt could get "stuck" and one would need to press Alt once again to restore correct keyboard handling. We've eliminated that problem at last."

It is unclear to me if it's completely a viewer problem, or if there was a server side issue as well.  If this is not related to the Server side, please delete this thread.

**Comment by CendioOssman** [comment]
Should be a client problem. @bphinz , does the Java viewer release all keys on loss of focus?

**Comment by bphinz** [comment]
On Thu, Sep 1, 2016 at 6:11 AM, Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Should be a client problem. @bphinz <https://github.com/bphinz> , does
> the Java viewer release all keys on loss of focus?
>
Yes, it does.

**Comment by hans109h** [comment]
Thanks, I'll take the discussion over to the TightVNC mailing list....
