### ISSUE TITLE
Port for android

### ISSUE THREAD

**Issue by joaopa00** [TigerVNC/tigervnc#346]
Hello,

is there a port for android foreseen in a short or middle term?
Thanks in advance

**Comment by CendioOssman** [comment]
Not really, unless @bphinz is planning to port the Java client?

**Comment by bphinz** [comment]
No, currently I have no plans to port the java viewer over to Android.  However, I am currently working on a very large changeset that might make doing so more feasible in the future.

**Comment by CendioOssman** [comment]
In that case I'm closing this. I don't think we should have large feature requests like this just sitting there if no-one has any intention of implementing them (and maintaining them).
