### ISSUE TITLE
copy clipboard and multiple viewers

### ISSUE THREAD

**Issue by luisgutz** [TigerVNC/tigervnc#348]
Hi,

I I have 2 VNC viewers, and I copy something on one of them, I can see that on windows, but not on the second VNC viewer.
To do so, I have to paste into windows and copy again., which seems odd, since other VNC viewers can do this.

Steps to reproduce.
1) Start a VNC session on any host.
1.a) use tiger vnc viewer to connect to this session
1.b) start vncconfig
2) Start a second VNC sessions
2.a) use tiger vnc viewer to connect to this session
2.b) start vncconfig
3) select text from session 1.
4) try to paste into session: it will fail (ie either it won't paste anything, or it will paste the wrong thing
5) select text from session 1.
6) paste into windows (ie, notepad)
7) copy recently pasted text from windows
8) paste into second VNC. It should work this time.
##

**Comment by CendioOssman** [comment]
I'm afraid I cannot reproduce this issue. Which build are you using? Do you have some clipboard tool running on the Windows machine that might interfere? Microsoft Office has been known to screw with the clipboard in odd ways.

**Comment by luisgutz** [comment]
Hi Pierre,

I'm using v1.6.0 (v)


I do have MS office installed, but no other clipboard SW.

Oddly, it's working now. But only in one direction.




Luis

**Comment by CendioOssman** [comment]
Is it possible for you to test uninstalling Office? Or testing on another machine?

**Comment by CendioOssman** [comment]
No response.
