### ISSUE TITLE
TigerVNC offers encryption methods while it is disabled

### ISSUE THREAD

**Issue by joukio** [TigerVNC/tigervnc#350]
I run TigerVNC version 1.6.0, compiled without TLS (long story) and I try to connect with x11vnc to reflect (for instance) vnc port 5920 to port 5910. TigerVNC is running with securitytypes=none.

However, when I try to connect with x11vnc to TigerVNC it breaks. When I run both programs in debug mode I see that TigerVNC is offering securitytypes 19 and 1. Due to a bug in x11vnc it picks 19 and the process dies. But I really don't know why TigerVNC is still offering securitytype 19 (vencrypt) while I explicitly configured securitytypes to be none.

regards
Jouk

**Comment by CendioOssman** [comment]
We used to always offer VeNCrypt as it was backwards compatible with the non-VeNCrypt security types. Unfortunately some other implementations don't handle this properly, so we added a workaround for them. The latest version should be more kind to things like x11vnc.
