### ISSUE TITLE
Build failure with clang on Linux

### ISSUE THREAD

**Issue by elkrejzi** [TigerVNC/tigervnc#352]
CC       Xvnc-miinitext.o
../../mi/miinitext.c:118:30: error: a parameter list without types is only allowed in a function definition
extern void vncExtensionInit(INITARGS);
                             ^
../../mi/miinitext.c:331:41: error: invalid application of 'sizeof' to an incomplete type 'const ExtensionModule []'
    LoadExtensionList(staticExtensions, ARRAY_SIZE(staticExtensions), TRUE);
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../include/dix.h:67:31: note: expanded from macro 'ARRAY_SIZE'
#define ARRAY_SIZE(a)  (sizeof((a)) / sizeof((a)[0]))
                              ^~~~~
2 errors generated.

**Comment by elkrejzi** [comment]
llvm/clang 3.9.0, tigervnc 1.7.0

**Comment by CendioOssman** [comment]
That file comes from Xorg, not TigerVNC, so I'm afraid it looks like a bug for them rather than us. Which version of Xorg did you use for the build?

**Comment by elkrejzi** [comment]
Stock xorg server builds just fine with clang. The line being highlighted is added by patch in TigerVNC tree:

https://github.com/TigerVNC/tigervnc/blob/master/unix/xserver118.patch#L60

I'm using xorg-server-1.18.4

**Comment by CendioOssman** [comment]
Ah, I see. Does it compile if you change `INITARGS` to `void`?

**Comment by elkrejzi** [comment]
Changing INITARGS to void fixes the compilation issue. I now get link issue:

/usr/bin/ld: ../../../../common/network/.libs/libnetwork.a(TcpSocket.cxx.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC

This too isn't present with gcc, which uses the same linker ... Which makes me wonder if PIC/PIE detection is compiler dependent.

**Comment by CendioOssman** [comment]
Yup, we have a gcc check for that part. I think it was originally since Visual Studio has very different arguments. But Windows doesn't need PIC anyway. I'll get it fixed.

**Comment by CendioOssman** [comment]
Both issues should now be fixed on `master`. Please test and see if there is anything else.
