### ISSUE TITLE
pam_service

### ISSUE THREAD

**Issue by ryanlraines** [TigerVNC/tigervnc#355]
CentOS 7
tigervnc-server.x86_64 1.3.1
TigerVNC Client WIN64 

Attempting to authenticate against LDAP, via pam_service Xvnc parameter.
(http://tigervnc.org/doc/Xvnc.html)

Issued command: _vncserver :1 -PlainUsers=$USER -pam_service=login_

Attempting to connect from WIN7 tiger vncviewer client.   Client  only connects if vncpasswd is given.  I'm expecting to authenticate with LDAP password.

**Comment by CendioOssman** [comment]
As mentioned on the mailing list, Plain is not enabled by default. You need to specify `-SecurityTypes=TLSPlain`. Doing this makes it work just fine on CentOS 7 (I just tested).

(Also note that PAM authentication requires running vncserver as root)

**Comment by brilong** [comment]
I have not seen the running vncserver as root to be a hard requirement for PAM auth, but I've just started playing with it.  I was able to set up TLSPlain / PAM on RHEL 6 and CentOS 7 with my personal account (authenticated via Red Hat IdM / FreeIPA).

**Comment by CendioOssman** [comment]
I can depend a bit on the environment, but most PAM modules assume a privileged environment.
