### ISSUE TITLE
cmake error when preparing for vncviewer

### ISSUE THREAD

**Issue by octavsly** [TigerVNC/tigervnc#357]
`cmake -G "Unix Makefiles" ../vncviewer/`

```
...
CMake Error at CMakeLists.txt:55 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "vncviewer".
```

**Comment by CendioOssman** [comment]
Not something we've seen before. Which version of CMake is this?

**Comment by CendioOssman** [comment]
Ah, wait. You can't run cmake on just the vncviewer directory. You have to do it on the top directory.
