### ISSUE TITLE
vncviewer doesn't handle CAPS LOCK and key modifiers correctly

### ISSUE THREAD

**Issue by tajayi** [TigerVNC/tigervnc#358]
When I use the vncviewer.exe from windows to a linux machine (also running tigervnc), with CAPS LOCK on on my windows machine, a Ctrl+d combination on the keyboard, creates a Ctrl+Shift+d. 

My understanding from is that tigervnc does not synchronize CAPS LOCK, but rather sends a Shift+<key> for alphabetic characters. I believe the correct behaviour when CAPS LOCK is on, is to not send the shift modifier. Other vnc clients have tried do this.

**Comment by CendioOssman** [comment]
It's actually the server that does this, not the client. And it has to do this to get the correct symbol. Lock keys are not yet supported (see #156).

**Comment by tajayi** [comment]
Thanks for your response.

There seems to be some inconsistencies between different viewers  connecting to the server has Xvnc TigerVNC 1.3.1 server. 
Using a TightVNC  viewer, the behavior is as expected (IMO): CAPSon + Ctrl + d (client side) -> Ctrl + d (server side)
On TigerVnc or RealVNC viewer, the behavior is different: CAPSon + Ctrl + d (client side) -> Ctrl + *Shift* + d (server side)

**Comment by tajayi** [comment]
@CendioOssman Any chance of re-opening this issue? I don't believe it was ever addressed and is still persistent.
TightVNC client appears to behave correctly and TigerVNC client doesn't (connecting to the same server instance)
