### ISSUE TITLE
Trusty Tahr deb missing dependency

### ISSUE THREAD

**Issue by ErikHarmon** [TigerVNC/tigervnc#360]
Fresh install on Ubuntu Server 14.04, Xvnc failed with "Xvnc: error while loading shared libraries: libgcrypt.so.20: cannot open shared object file: No such file or directory"

"workaround": apt-get install libgcrypt20
##

**Comment by CendioOssman** [comment]
We don't use libgcrypt directly, so this sounds like an Ubuntu bug. @bphinz?

**Comment by oskarpolski** [comment]
Had the same problem on Ubuntu Server 14.04 with both Ubuntu and Kubuntu. Solved with the solution proposed by @ErikHarmon. Thanks!
