### ISSUE TITLE
System wide settings for vncserver

### ISSUE THREAD

**Issue by rahuls1071** [TigerVNC/tigervnc#363]
Is there a way to enforce configuration settings by admin and block overwrite by users who run vncserver on the machine. LIke, some settings file in /etc and the parameters mentioned in that file cannot be overwritten by any user
This will help enforce security settings and various auth methods.

--RAhul

**Comment by CendioOssman** [comment]
Partially, yes. There is a global configuration system for `vncserver` in the nightly builds. But enforcement relies on the users not being able to run `Xvnc` some other way.
