### ISSUE TITLE
Sharing VNC session with others

### ISSUE THREAD

**Issue by rahuls1071** [TigerVNC/tigervnc#364]
I'm currently using securityTypes & pam service for login instead of VNCAuth. In this case I'm unable to share my session with others after starting the session. I can give list of users to share only at the time of creating the session, but if I want to share with anyone after initiating the session, it is not possible.

Also i should be able to have view-only sharing . Please help

--RAhul

**Comment by CendioOssman** [comment]
You can change the PlainUsers setting for a running session using vncconfig and the new AllowOverride system. There is however no mechanism to enforce view-only this way. Only the simple VNCAuth has that.
