### ISSUE TITLE
crypt32.dll entry point error [$100]

### ISSUE THREAD

**Issue by niterain** [TigerVNC/tigervnc#365]
Using Mingw64 with MSYS2.

After compiling everything, and attempting to run vncviewer.exe, I get this error:

**The procedure entry point CertCloseStore@8 could not be located in the dynamic link library crypt32.dll.**

I suspect it is an issue with the gnutls library.

**Comment by CendioOssman** [comment]
That sounds like a GnuTLS issue, yes. We never call that function so it is not a TigerVNC issue. So I'm afraid I'll have to direct you to file a bug report with them.
