### ISSUE TITLE
init script run levels wrong in the packaged deb?

### ISSUE THREAD

**Issue by sandeep048** [TigerVNC/tigervnc#367]
Changing run levels in the init script (/etc/init.d/vncserver) from

```
# Default-Start:
# Default-Stop: 0 1 2 3 4 5 6
```

to

```
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
```

seems to work. This change followed by these commands ensure that tigervncserver starts at boot.

```
update-rc.d vncserver defaults
update-rc.d vncserver enable

```

Assuming /etc/default/vncservers is updated as needed. Should these instructions be documented some where?
##

**Comment by CendioOssman** [comment]
I think it needs configuration before it can be used as a service anyway. @bphinz?

**Comment by bphinz** [comment]
The reason that the service levels default to off is that we're not assuming that everyone wants it running.  This is the same default that VNC services have always had in most distros.  Besides, as Pierre noted, the per-user configuration needs to be adjusted before there is anything to start.
