### ISSUE TITLE
MacOS - vncviewer: High CPU load due to writing the image to the screen 

### ISSUE THREAD

**Issue by fredowski** [TigerVNC/tigervnc#372]
Hi, 

i looked at XCode Instruments to see where the CPU cycles are consumed in the vncviewer process. I wanted to check if I can see a difference in the jpeg vs. jpeg-turbo build. I see roughly 20% of the load going to jpeg decoding, while 80% is spend more or less in writing the image to the screen. So on Mac the jpeg decoding seems to be a minor problem compared to image writing. I run this on a MacBook Pro with HighResolution Display - so maybe something is converted there...

Here is a screenshot showing the Main Thread vs. one of the worker threads with jpeg decoding:
![inst-overview](https://cloud.githubusercontent.com/assets/1280457/19698671/867525ac-9af0-11e6-9a84-d2899d74ba0c.JPG)

Here is the first part of the main thread:

![inst1](https://cloud.githubusercontent.com/assets/1280457/19698724/be8bf0ba-9af0-11e6-9a6b-1139e8bac434.JPG)

and here is the remaining part.

![inst2](https://cloud.githubusercontent.com/assets/1280457/19698770/ed0ecbb0-9af0-11e6-9ff9-c58fca7de58d.JPG)

60% of the total CPU power for vncviewer  is spend in the OS routine: argb32_image_mark_RGB24. 

Googling seems to show more problems with this: http://stackoverflow.com/questions/21665473/coregraphics-argb32-image-mark-rgb24-is-slow

Friedrich
##

**Comment by CendioOssman** [comment]
Yes, I'm afraid this is a somewhat known issue. Unfortunately none of the suggested fixes we've found so far have worked.

**Comment by CendioOssman** [comment]
It also happens on all Macs, not just high resolution displays.

**Comment by CendioOssman** [comment]
This should be fixed in 41a0c151c554a37fbffece8ef36848ed47fd17d3.
