### ISSUE TITLE
Server started as a service, can't accept connections (Win7 x64) v1.7.0_x64

### ISSUE THREAD

**Issue by Dambuster88** [TigerVNC/tigervnc#373]
Hello,
I am using v1.7.0_x64 server (as service) on a Windows 7 x64.
When trying to connect with the viewer (v1.7.0_x64), the viewer crashes instant with no prompt.
When trying to connect with the RealVNC viewer, instantly I receive a prompt "The connection closed unexpectedly."

This problem appears only when the server is started as a service. When started as a user program, the connection can be made between server and client.
##

**Comment by CendioOssman** [comment]
Could you modify the service and add the arguments `-Log *:EventLog:100`. You should then see log entries in the Windows event log.

**Comment by Dambuster88** [comment]
I am not using antivirus and the firewall is disabled!
I have activated the log entries and at the start of the service I can see this (downwards):
Config     set immutable Log
Service   Service
Service   entering dispatcher
Service   entering TigerVNC serviceProc
Service   registering handler...
Service   registered handler (0000000001605D40)
Service   set status to 2(1)
Service   entering TigerVNC serviceMain
Service   set status to 4(2)

Trying to connect to the server (service) from both, Windows 7 and Fedora 24. Both clients (v1.7.0) are instant crashing without a message, and in the server logs doesn't appear any other entries until service stop.

Trying to connect with other VNC viewer (Real VNC) I am receiving the message: "The connection closed unexpectedly."

**Comment by CendioOssman** [comment]
Hmm... Perhaps there is something else messing with the connection.

Could you start the client with the argument `-Log *:file:100`? You'll get a log in `C:\temp`.

**Comment by Dambuster88** [comment]
Hello. Running the Viewer from Fedora and Windows 7 will result in the same log file:
Sat Nov 19 01:19:05 2016
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to 10.7.3.4 [10.7.3.4] port 5900
 CConn:       connected to host 10.7.3.4 port 5900
 CConnection: reading protocol version
 CConn:       End of stream

**Comment by Dambuster88** [comment]
I have found the problem. Was the Access Control, was empty.
Is it possible to be a remaining setting from an old version, like older than v1.6.x ?
Another setting that is different is the "Serve Java viewer ..."; was disabled (only in service mode).
I suspect that those different (than default) settings are leftovers from an update, because I am running the server in a local network and I do not need to change those settings. And I do not remember to have changed those settings in the past.

Sorry for this wrong report.

Additionally, I can report that: In service mode, the "About..." is not working from Tray Icon.

**Comment by CendioOssman** [comment]
Strange. You should have seen log reports from the server when it kicks out clients like that. Glad you found the problem though.
