### ISSUE TITLE
Run TigerVNCserver 1.7.0/1.6.0 on debian "Jessie"

### ISSUE THREAD

**Issue by matangk** [TigerVNC/tigervnc#375]
Hi, Sorry for the noob question,
I want to run TigerVNCserver 1.7.0 on Debian 8.6 "Jessie". However the ".deb" installer contains Ubuntu specific packages, and I can't follow the "build from source" instructions as it requires fltk>=1.3.3.
Is there any way round that?
I'm sure I'm missing something but I was looking everywhere for instructions how to install the latest TigerVNCserver and couldn't find any.

Any help will be welcome!
-Matan
##

**Comment by hildred** [comment]
A quick search for "dpkg backport instructions" will find you several sets of instructions for backporting packages from unstable or testing. this can be used to build a newer ftlk from testing which is new enough. At this point you can repeat those instructions for tigervnc 1.6 (the version in testing) or you can follow the source build instructions for the most recent version.

**Comment by matangk** [comment]
Awesome, Thanks.
I followed:
https://wiki.debian.org/SimpleBackportCreation
And managed to backport fltk1.3-1.3.3, and tigervnc1.6.0. It seems to have built and installed fine.
I verified that vncviewer works as intended.
However when I try to start a vncserver, It immediately dies, with the follwoing log:
--this fails:--
# vncserver :2
--log:--
Tue Nov  1 23:29:55 2016
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5902
 vncext:      created VNC server for screen 0
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":2"
      after 139 requests (139 known processed) with 0 events remaining.
Killing Xtigervnc process ID 1123... success!
--end log--

I did verify that the port is open in the firewall, but it didn't change anything.
Any help will be appreciated!
Matan

**Comment by matangk** [comment]
OK, one more problem solved. Upon installing, TigerVNC has created a config file at "/etc/vnc.conf".
This file points to the vncStartup variable, which is defined as:
$vncStartup = "/etc/X11/Xvnc-session";
by changing it to:
$vncStartup = "$ENV{HOME}/.vnc/xstartup";
I point the server to start normally. I can also verify by:
# vncserver -list :*
That my vnc server is up and running.
However, I still cannot connect to it remotely. I suspect it's a firewall issue.
Any inputs are still welcome.
Matan

**Comment by CendioOssman** [comment]
Have you tried simply disabling the firewall?

**Comment by matangk** [comment]
Mmm... that's strange...
After fumbling with firewall definitions for a short while I looked at netstat after starting the vncserver:
->vncserver :1
->netstat -tln
The output is:
tcp        0      0 127.0.0.1:5901          0.0.0.0:*               LISTEN
From what I read (noob, sorry) I figured out I can't connect since the port only listens on loopback.
I seem to have solved the problem by starting vnc as follows:
 ->vncserver :1 -localhost
->netstat -tln
The output is:
tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN
And I am able to connect to my vnc server (great success!).
What confuses me is that in all the posts I read online, using -localhost should force the port to listen on loopback. It seems that in my case it's the other way around.
Can you please explain why?

**Comment by CendioOssman** [comment]
That is not the expected behaviour. Do you perhaps have a ~/.vnc/config that is affecting things?

Could you check what arguments `Xvnc` is getting once running?

**Comment by matangk** [comment]
No.. no config files.
As far as I could see the only config file is at /etc/vnc.conf, but it doesn't define anything that has to do with localhost. I do have a default file at: ~/.vnc/default.tigervnc. its content is:
***
TigerVNC Configuration file Version 1.0
ServerName=131.215.136.177:1
X509CA=
X509CRL=
SecurityTypes=VeNCrypt,X509Plain,TLSPlain,X509Vnc,TLSVnc,X509None,TLSNone,VncAut
h,None
DotWhenNoCursor=0
AutoSelect=1
FullColor=1
LowColorLevel=2
PreferredEncoding=Tight
CustomCompressLevel=0
CompressLevel=2
NoJPEG=0
QualityLevel=8
FullScreen=0
FullScreenAllMonitors=1
DesktopSize=
geometry=
RemoteResize=1
ViewOnly=0
Shared=0
AcceptClipboard=1
SendClipboard=1
SendPrimary=1
MenuKey=F8
FullscreenSystemKeys=1
***
I tried to look for xorg arguments but couldn't find any other than /var/log/Xorg.0.log
Is there anywhere else i should look?

Thanks for all the help!
Matan

**Comment by CendioOssman** [comment]
> I tried to look for xorg arguments but couldn't find any other than /var/log/Xorg.0.log
> Is there anywhere else i should look?

Run `ps ax` and find Xvnc in the output.

**Comment by lifeboatpres** [comment]
"That is not the expected behaviour. Do you perhaps have a ~/.vnc/config that is affecting things?"

I had these problems with "vncserver -kill $DISPLAY" in ~/.vnc/xstartup so I commented that line out. I didn't type that line so it was a bear to discover.
