### ISSUE TITLE
Change description so you can find TigerVNC in github search

### ISSUE THREAD

**Issue by n1trux** [TigerVNC/tigervnc#376]
Hi guys,

I think it'd be beneficial if you changed the github repo description to something more meaningful to appear in the [github search results for "vnc"](https://github.com/search?o=desc&q=vnc&s=stars&type=Repositories&utf8=%E2%9C%93).

How about "_TigerVNC is a high-performance, platform-neutral implementation of VNC (Virtual Network Computing)_"?
(from the home page)

**Comment by CendioOssman** [comment]
I've put the same description as for the project. Thanks for pointing this out.
