### ISSUE TITLE
linux viewer in listen mode - how to?

### ISSUE THREAD

**Issue by markd89** [TigerVNC/tigervnc#379]
Hi,

I am trying to use the viewer in reverse VNC mode but I do not get a window opening on my machine with the remote screen. What am I missing?

Following is what I did (Debian Jessie):

mark@ux305:~/Downloads$ ./vncviewer -listen

TigerVNC Viewer 64-bit v1.7.0
Built on: 2016-09-08 10:37
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Mon Nov  7 13:03:18 2016
 main:        Listening on port 5500

Mon Nov  7 13:03:46 2016
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConnection: Server supports RFB protocol version 3.16
 CConnection: Using RFB protocol version 3.8

^C  **(I hit ctrl-C)**
Mon Nov  7 13:04:17 2016
 main:        Termination signal 2 has been received. TigerVNC Viewer will now
              exit.

So, a connection is made, but no window opens.

Thanks,
Mark

**Comment by CendioOssman** [comment]
3.16 is not a valid version number. What server are you using? Does it work with our server?

**Comment by markd89** [comment]
I am using UVNC's Single-Click Reverse VNC for the server for the users that I support. This is a single EXE that is pretty easy for a non-technical user to download/run. (http://www.uvnc.com/products/uvnc-sc.html)

Is there an alternative that I should look at for this kind of capability?

Thanks,
Mark

**Comment by CendioOssman** [comment]
I don't know if there is any such other packaging available. But it seems like that server has some incompatibility bug, so I suggest you file a bug report with UltraVNC.
