### ISSUE TITLE
jetson tx1 jetpack 2.3. ubuntu 16.04 lts

### ISSUE THREAD

**Issue by golovanevAA** [TigerVNC/tigervnc#380]
dpkg-shlibdeps: error: no dependency information found for /usr/lib/aarch64-linux-gnu/tegra/libGL.so.1 (used by debian/tigervncserver/usr/bin/Xtigervnc)
Hint: check if the library actually comes from a package.
ARM Cortex-A57. would like to specify there are chances to compile under him? if yes, as it to make that?

**Comment by CendioOssman** [comment]
This sounds like a bug in your system. Perhaps you have a proprietary driver installed that is screwing up the build?

**Comment by golovanevAA** [comment]
All drivers which are necessary for this system are installed. Perhaps the problem that costs Nvidia of the driver as is the built-in system with the powerful graphic chip (256 graphic kernels) what other drivers to establish there is no opportunity. And as is well-known Nvidia very much doesn't love OpenGL and supports in the main CUDA (8.0) and OpenCV (2.4.13) - on jetson TX1 they and are established. Possibly at you with TigerVNC specific OpenGL of function are used (from higher what supported 1.2 versions) and therefore there is such mistake :(

**Comment by bphinz** [comment]
Where does /usr/lib/aarch64-linux-gnu/tegra/libGL.so.1 actually come from?
ie: was it installed as part of a .deb package or via a tarball, etc?  I
think that dpkg-shlibdeps is looking for dependency info in the package db
but the file was likely installed manually (outside of apt).  There are
numerous reports that you can reference to try to bypass the check:

http://stackoverflow.com/questions/11238134/dpkg-shlibdeps-error-no-dependency-information-found-for

**Comment by golovanevAA** [comment]
Many thanks for council. I managed to compile the program, I set it but unfortunately that that all the same doesn't work. In file/.xsession-errors there are here such errors
`openConnection: connect: No such file or directory
cannot connect to brltty at :0
upstart: Failed to spawn window-stack-bridge main process: unable to execute: No such file or directory`

**Comment by CendioOssman** [comment]
`.xsession-errors` isn't normally used with VNC. How are you starting the server?

**Comment by hillct** [comment]
I'm not clear on whether this bug is still open because aarch64 builds are still a problem, or it was just abandoned. I wonder if I could get an update on the status of aarch64 builds, as I have a need to build for he Nvidia Jetson Nano hardware which runs Ubuntu 18.04 aarch64-linux-gnu

**Comment by CendioOssman** [comment]
I'd say this is abandoned. If you are still seeing issues then please file a new report with our new bug template and we'll go from there.
