### ISSUE TITLE
Enhancement: PPA for Ubuntu

### ISSUE THREAD

**Issue by bits01** [TigerVNC/tigervnc#381]
It would be useful to have an official and up to date PPA for various Ubuntu versions so that the update process for tigervnc can be automated.

There's something here, but it's not up to date:
https://launchpad.net/~ikuya-fruitsbasket/+archive/ubuntu/tigervnc

**Comment by CendioOssman** [comment]
That would probably be useful, yes. But it's not something we have resources for right now. Anyone else is free to set up a PPA though.

As this doesn't really affect the project here, I'll close this issue.
