### ISSUE TITLE
Building vncviewer 1.7 on Debian Jessie: ‘fullscreen_screens’ was not declared in this scope

### ISSUE THREAD

**Issue by markd89** [TigerVNC/tigervnc#383]
Hi,

I am trying to build the viewer, but running into an issue on make. 

Please tell me what I am missing. 

Much thanks!
Mark

Here's what I did:

1. root@debianvm:/mnt/hgfs/debian8vmtemp/tigervnc-1.7.0# cmake -G "Unix Makefiles"  -Wno-dev -DBUILD_STATIC=1  -DBIN_DIR=/bin vncviewer

2. root@debianvm:/mnt/hgfs/debian8vmtemp/tigervnc-1.7.0# make vncviewer

that results in:
...
[ 89%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o
/mnt/hgfs/debian8vmtemp/tigervnc-1.7.0/vncviewer/DesktopWindow.cxx: In member function ‘void DesktopWindow::fullscreen_on()’:
/mnt/hgfs/debian8vmtemp/tigervnc-1.7.0/vncviewer/DesktopWindow.cxx:431:38: error: ‘fullscreen_screens’ was not declared in this scope
     fullscreen_screens(-1, -1, -1, -1);
                                      ^
/mnt/hgfs/debian8vmtemp/tigervnc-1.7.0/vncviewer/DesktopWindow.cxx:466:48: error: ‘fullscreen_screens’ was not declared in this scope
     fullscreen_screens(top, bottom, left, right);
                                                ^
vncviewer/CMakeFiles/vncviewer.dir/build.make:100: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o' failed
make[3]: *** [vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o] Error 1
CMakeFiles/Makefile2:775: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/all' failed
make[2]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Error 2
CMakeFiles/Makefile2:787: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/rule' failed
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/rule] Error 2
Makefile:333: recipe for target 'vncviewer' failed
make: *** [vncviewer] Error 2

In-case, you're wondering...
Q: Why am I building rather than using the repository binary? 
A: I had posted this issue: https://github.com/TigerVNC/tigervnc/issues/379 After much searching, I found someone else had run into the same issue and posted the solution here: https://groups.google.com/forum/?_escaped_fragment_=topic/tigervnc-devel/pLdECYl6b5o#!topic/tigervnc-devel/pLdECYl6b5o

The solution involves a hack to CConnection.cxx so that if a server presents a higher version than 3.8, the viewer defaults back to 3.3. Once that's done, I'll be able to use UltraVNC Single Click (from Windows) as my server to connect to TigerVNC viewer on the Debian machine I use.

**Comment by bphinz** [comment]
Do you have the libfltk1.3-dev (and possibly libfltk1.3-compat-headers)
packages installed?

>

**Comment by markd89** [comment]
Thanks, Brian. I did not have the headers installed.

I installed those, but I think I may be missing something else. Now I get:

root@debianvm:/mnt/hgfs/debian8vmtemp/tigervnc-1.7.0# make vncviewer
[  0%] Built target Xregion
[  4%] Built target os
[ 19%] Built target rdr
[ 86%] Built target rfb
[ 86%] Built target network
vncviewer/CMakeFiles/vncviewer.dir/build.make:44: CMakeFiles/vncviewer.dir/depend.make: No such file or directory
vncviewer/CMakeFiles/vncviewer.dir/build.make:47: CMakeFiles/vncviewer.dir/progress.make: No such file or directory
vncviewer/CMakeFiles/vncviewer.dir/build.make:50: CMakeFiles/vncviewer.dir/flags.make: No such file or directory
make[3]: *** No rule to make target 'CMakeFiles/vncviewer.dir/flags.make'.  Stop.
CMakeFiles/Makefile2:775: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/all' failed
make[2]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Error 2
CMakeFiles/Makefile2:787: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/rule' failed
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/rule] Error 2
Makefile:333: recipe for target 'vncviewer' failed
make: *** [vncviewer] Error 2

**Comment by markd89** [comment]
I started over again from a fresh build directory. I do have the libfltk1.3-compat-headers and xorg-dev which I did not have the first time.

Unfortunately, I'm still seeing the original issue.

My steps:

1.  root@debianvm:/mnt/hgfs/debian8vmtemp/t# cmake -G "Unix Makefiles"  -Wno-dev -DBUILD_STATIC=1  -DBIN_DIR=/bin .
2.  root@debianvm:/mnt/hgfs/debian8vmtemp/t# make vncviewer

Scanning dependencies of target vncviewer
[ 87%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/menukey.cxx.o
[ 87%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/CConn.cxx.o
[ 89%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o
/mnt/hgfs/debian8vmtemp/t/vncviewer/DesktopWindow.cxx: In member function ‘void DesktopWindow::fullscreen_on()’:
/mnt/hgfs/debian8vmtemp/t/vncviewer/DesktopWindow.cxx:431:38: error: ‘fullscreen_screens’ was not declared in this scope
     fullscreen_screens(-1, -1, -1, -1);
                                      ^
/mnt/hgfs/debian8vmtemp/t/vncviewer/DesktopWindow.cxx:466:48: error: ‘fullscreen_screens’ was not declared in this scope
     fullscreen_screens(top, bottom, left, right);
                                                ^
vncviewer/CMakeFiles/vncviewer.dir/build.make:100: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o' failed
make[3]: *** [vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o] Error 1
CMakeFiles/Makefile2:775: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/all' failed
make[2]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Error 2
CMakeFiles/Makefile2:787: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/rule' failed
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/rule] Error 2
Makefile:333: recipe for target 'vncviewer' failed
make: *** [vncviewer] Error 2

**Comment by markd89** [comment]
https://github.com/TigerVNC/tigervnc/issues/177

has the same issue. I guess the FLTK in the Debian Jessie repository is too old. This resolved the error above.
