### ISSUE TITLE
unable to open display on CentOS 7

### ISSUE THREAD

**Issue by sobigworld** [TigerVNC/tigervnc#384]
Hi, i have a job task to test tigervnc(version 1.3.1) on CentOS7.2, and i meet a problem like this:  After succeed to create a vnc session (by typing command "vncserver") and setting variable DISPLAY=<IP>:<session id>,  I failed to call "xhost +"。
testing info:
```
[test@gv55 ~]$ ps -ef | grep Xvnc
test  9419     1  0 10:16 pts/1    00:00:00 /usr/bin/Xvnc :1 -desktop gv55:1 (test) -httpd /usr/share/vnc/classes -auth /home/test/.Xauthority -geometry 1280x1088 -rfbwait 30000 -rfbauth /home/test/.vnc/passwd -rfbport 5901 -fp catalogue:/etc/X11/fontpath.d -pn
[test@gv55 ~]$ export DISPLAY=10.0.35.55:1
[test@gv55 ~]$ xhost + 
xhost:  unable to open display "10.0.35.55:1"
[test@gv55 ~]$ netstat -lnp | grep 9419 
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:5801            0.0.0.0:*               LISTEN      9419/Xvnc           
tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN      9419/Xvnc           
tcp6       0      0 :::5801                 :::*                    LISTEN      9419/Xvnc           
tcp6       0      0 :::5901                 :::*                    LISTEN      9419/Xvnc           
unix  2      [ ACC ]     STREAM     LISTENING     1673236  9419/Xvnc            @/tmp/.X11-unix/X1
unix  2      [ ACC ]     STREAM     LISTENING     1673237  9419/Xvnc            /tmp/.X11-unix/X1
```
firewalld and SELinux have been stopped before testing this.
I guess the reason maybe like this: the Xvnc doesn't listened on X11 port(6001).
This phenomenon at CentOS7.2 is different with CetOS5.x/6.x (with lower version of tigervnc).
So, my question: how to make tigervnc server to listen on 600x on CentOS7.2 ?
Looking forward to your help, thanks!

**Comment by CendioOssman** [comment]
> So, my question: how to make tigervnc server to listen on 600x on CentOS7.2 ?

It's better if you use the Unix sockets (i.e. set DISPLAY to :1), but if you really want to then the arguments are `-listen tcp`.

**Comment by sobigworld** [comment]
It works,
Thank you very much, CendioOssman
