### ISSUE TITLE
questions about client/server combination (incremental)

### ISSUE THREAD

**Issue by 02015678** [TigerVNC/tigervnc#386]
I just want to know.
If use tigervnc as server, and will various clients benefiting from screen incremental update?
If use tigervnc as client, and will various servers benefiting from screen incremental update?

For example, if I use tigervnc server and realvnc client, 
the screen will update incremental or not?

This page talk about the question, but I don't get it.
https://github.com/TigerVNC/tigervnc/wiki/DesktopSize

I cannot figure out section Server means use of Tigervnc Server, or use of Tigervnc Client.

**Comment by CendioOssman** [comment]
Yes, pretty much all VNC clients and servers support incremental updates.
