### ISSUE TITLE
Significant performance different between Ubuntu Mate 14.04 and 16.04.

### ISSUE THREAD

**Issue by jmadams1** [TigerVNC/tigervnc#389]
After doing a fresh install of Ubuntu Mate 16.04 on my physical server, I found tigervnc access to it very slow in comparison to Ubuntu Mate 14.04.  My comparison test is simple, LAN, resolution around 1920x1130, open terminal window, resize it to about half the screen, run top, and then move the window around.  In 14.04, it's smooth, hardly notice it's a vnc session.  In 16.04, it is very slow to redraw.

To troubleshoot, I installed two VMs, one with Ubuntu Mate 14.04 and the other with 16.04 with all the updates for each.  Installed 1.7.0 server on each (adding the missing dependencies when needed.)  The cleanly installed VMs exhibit the same behaviour as the physical server - 14.04 fast, 16.04 slow.

As a datapoint, I tried x2go and vnc performance on 16.04 was great.

Any suggestions?

Thank you very much,
John

**Comment by CendioOssman** [comment]
It could be that compositing is enabled in MATE in 16.04. Here's one guide for how to toggle it:

https://wiki.archlinux.org/index.php/MATE#Enabling_compositing

**Comment by jmadams1** [comment]
Disabling compositing did make a huge positive difference in performance for 16.04.  It's now very workable.  

Just as a side note, I checked my 14.04 VM and it does have software compositing enabled and I'm able to see the effects.  Something has changed in 16.04 that's doesn't play well with tigervnc with compositing on.

Thank you,
John

**Comment by CendioOssman** [comment]
It would seem so. I don't think anyone has time to figure out what at this time though. :/
