### ISSUE TITLE
vncviewer does not honor the SendClipboard setting

### ISSUE THREAD

**Issue by meshpoint** [TigerVNC/tigervnc#392]
`sendClipboard` is not referenced at all in vncviewer/Viewport.cxx; it sends unconditionally.

This is a security issue, because a user who unsets this option would think that it works as expected and may copy some sensitive data, which will be sent to a possibly untrusted VNC server.

**Comment by CendioOssman** [comment]
Hmm... Seems to have been like that ever since the new client. I'll have a look.

**Comment by CendioOssman** [comment]
Fixed in a432b58232cbe576b7776b674eb8da368c47ce7a.
