### ISSUE TITLE
Does there exist a VNC solution with Audio ?

### ISSUE THREAD

**Issue by handsetvn** [TigerVNC/tigervnc#396]
Any solutions to these issues? Thanks.

**Comment by CendioOssman** [comment]
Some VNC implementations have added extensions for audio. But they are very basic from what I've seen.

We at Cendio solve this by bundling everything over an SSH connection and then using PulseAudio to transfer the audio.

Doing any changes to TigerVNC in this area is not something anyone is working on, as far as I know.

**Comment by anonymous2ch** [comment]
https://www.realvnc.com/en/connect/audio/ Yep

**Comment by samhed** [comment]
>  On Linux systems, the pulse audio sound system must be installed in order to use the remote audio feature. 

@anonymous2ch, it seems realvnc are using PulseAudio as well.

**Comment by lucasfcnunes** [comment]
> https://www.realvnc.com/en/connect/audio/ Yep

That's a payed and closed source solution...

[ref 1](https://www.raspberrypi.org/forums/viewtopic.php?p=1522451&sid=8a42238f35a74c809c07b33d3f31463e#p1522451)
[ref 2](https://help.realvnc.com/hc/en-us/articles/360002504358?flash_digest=827218d951a46191cd857ec47cbc99535a506cae&_ga=2.127759821.1998683537.1589248126-1034393487.1589248126#what-can-and-can%E2%80%99t-i-do-with-audio--0-1)
