### ISSUE TITLE
v1.7.1 d'nt build

### ISSUE THREAD

**Issue by SergeyDjam** [TigerVNC/tigervnc#403]
Hello.
cmake .
make
...
[ 89%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/Viewport.cxx.o
/home/admin/rpmbuild/BUILD/tigervnc-1.7.1/vncviewer/Viewport.cxx: In constructor «Viewport::Viewport(int, int, const rfb::PixelFormat&, CConn*)»:
/home/admin/rpmbuild/BUILD/tigervnc-1.7.1/vncviewer/Viewport.cxx:112:3: ошибка: «add_system_handler» не является элементом «Fl»
   Fl::add_system_handler(handleSystemEvent, this);
   ^
/home/admin/rpmbuild/BUILD/tigervnc-1.7.1/vncviewer/Viewport.cxx: In destructor «virtual Viewport::~Viewport()»:
/home/admin/rpmbuild/BUILD/tigervnc-1.7.1/vncviewer/Viewport.cxx:147:3: ошибка: «remove_system_handler» не является элементом «Fl»
   Fl::remove_system_handler(handleSystemEvent);
   ^
/home/admin/rpmbuild/BUILD/tigervnc-1.7.1/vncviewer/Viewport.cxx: В функции-члене «virtual int Viewport::handle(int)»:
/home/admin/rpmbuild/BUILD/tigervnc-1.7.1/vncviewer/Viewport.cxx:356:5: ошибка: «disable_im» не является элементом «Fl»
     Fl::disable_im();
     ^
/home/admin/rpmbuild/BUILD/tigervnc-1.7.1/vncviewer/Viewport.cxx:365:5: ошибка: «enable_im» не является элементом «Fl»
     Fl::enable_im();
     ^
vncviewer/CMakeFiles/vncviewer.dir/build.make:254: ошибка выполнения рецепта для цели «vncviewer/CMakeFiles/vncviewer.dir/Viewport.cxx.o»
make[2]: *** [vncviewer/CMakeFiles/vncviewer.dir/Viewport.cxx.o] Ошибка 1
CMakeFiles/Makefile2:845: ошибка выполнения рецепта для цели «vncviewer/CMakeFiles/vncviewer.dir/all»
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Ошибка 2
Makefile:127: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

uname -r
4.1.34-nrj-desktop-2rosa-x86_64

rpm -qa | grep cmake
cmake-3.5.2-1-rosa2014.1.x86_64
extra-cmake-modules-5.24.0-1-rosa2014.1.noarch

cat /etc/release 
ROSA Desktop Fresh R8 release 2014.1 for x86_64

**Comment by CendioOssman** [comment]
You are using a too old version of FLTK. Please upgrade to 1.3.3 or later.
