### ISSUE TITLE
Switch User - VNC Screen become blank

### ISSUE THREAD

**Issue by lokebl** [TigerVNC/tigervnc#404]
Hi,

We are using CentOS 6.8 and 7.2 , We have installed TigerVNC. 

VNC is configured properly and we are able to connect as well , But we tried switch users , but the screen goes blank and we have to kill the vnc session to connect back.

If we sign out , it works fine , only issues with switch user.

Please let me know if anyhow came across this issues and sovled.

Regards,
Lokesh

**Comment by CendioOssman** [comment]
Is this using the VNC module attached to the local X server?

Is it our build?

**Comment by lokebl** [comment]
Yes, We are using VNC Module attached to local X Server.

We have the configuration for CentOS 6.8 on /etc/X11/xorg.conf 

CentOS 7.2 on /etc/X11/xorg.conf.d/10-libvnc.conf

**Comment by CendioOssman** [comment]
Did you get TigerVNC from us or from CentOS?

**Comment by lokebl** [comment]
we got it from https://github.com/TigerVNC/tigervnc/releases 

Not from CentOS.

**Comment by CendioOssman** [comment]
Great. Could you dig out a log from the X server? Perhaps there is an interesting warning or error there.

**Comment by lokebl** [comment]
Please find the attached X Server Log.

[Xorg.0.txt](https://github.com/TigerVNC/tigervnc/files/726508/Xorg.0.txt)

**Comment by CendioOssman** [comment]
Hmmm... That didn't contain any VNC logging unfortunately. On the CentOS 7 system I think you should be able to get at it using:

```
journalctl /usr/libexec/gdm-x-session 
```

**Comment by MohammedAriff** [comment]
I couldn't find the file:

[root@ais-v1 xinit]# journalctl /usr/libexec/gdm-x-session
Couldn't stat file: No such file or directory
Failed to add filters: No such file or directory
[root@ais-v1 xinit]#

**Comment by MohammedAriff** [comment]
we tried to change xinitrc config file parameters but still the same issue.

**Comment by MohammedAriff** [comment]
I can see below error in /var/log/messages as soon as I switch user in VNC:

Jan 31 22:55:57 ais-v1 dbus[843]: [system] Successfully activated service 'org.freedesktop.realmd'
Jan 31 22:55:57 ais-v1 systemd: Started Realm and Domain Configuration.
Jan 31 22:55:57 ais-v1 dbus-daemon: dbus[843]: [system] Successfully activated service 'org.freedesktop.realmd'
Jan 31 22:55:58 ais-v1 gnome-session: (gnome-settings-daemon:7820): color-plugin-WARNING **: failed to get edid: unable to get EDID for output
Jan 31 22:55:58 ais-v1 gnome-session: (gnome-settings-daemon:7820): color-plugin-WARNING **: unable to get EDID for xrandr-Virtual1: unable to get EDID for output

**Comment by CendioOssman** [comment]
Does it work if you switch back to that session locally? The graphics driver might not work properly when the session isn't visible, screwing up VNC access as well.

**Comment by MohammedAriff** [comment]
It won't work, Just a blank screen. not able to view anything all blank.

It happens on all hardwares --> VMs, HP hardware etc..

**Comment by CendioOssman** [comment]
I spun up some test servers, and I'm afraid this seems to be a limitation in the X server. I cannot even get a simple screen shot unless the session is currently active. So I'm afraid we can't do anything until the X server gets the feature to stay active even when not visible.
