### ISSUE TITLE
"Xvnc -inetd" is silent

### ISSUE THREAD

**Issue by chlohr** [TigerVNC/tigervnc#405]
Dear all,
  I'm experimenting the "inetd" scenario with TigerVNC 1.7.0 - built Jan  5 2017 22:35:23
(debian tigervnc-standalone-server package 1.7.0+dfsg-2 (amd64))

I'm facing a strange issue regarding the -inetd option: after the client has sent "RFB 003.008", the server remains silent (instead of sending something like 0x02 0x13 0x02...).  As if the server were waiting something more from the client which never arrives. And everything is blocked.

For instance, let's use socat as a mini-inetd service with its dump feature:
   socat -v TCP-LISTEN:5905,reuseaddr EXEC:'Xvnc -inetd'
and in another terminal type:
  vncviewer localhost:5

Does anyone else got the issue?
Any advice?
Regards

**Comment by CendioOssman** [comment]
Works fine for me. Could you test the general build? And perhaps the nightly build?

**Comment by chlohr** [comment]
Hi,
  You're right. No problems with the last "Xvnc TigerVNC 1.7.80 - built Jan 26 2017 01:07:13".
This only occur with the current debian packet.
So, let's close this ticket.
Sorry for the inconvenience. 
Regards.
