### ISSUE TITLE
Linux build uses an old statically linked fontconfig library

### ISSUE THREAD

**Issue by LaurentBonnaud** [TigerVNC/tigervnc#406]
Hi,

when I run tigervnc 1.7.1 on my Ubuntu 16.10 system I see the following error messages:
```
TigerVNC Viewer 64-bit v1.7.1
Built on: 2017-01-18 12:46
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Thu Jan 26 22:49:01 2017
 DecodeManager: Detected 2 CPU core(s)
 DecodeManager: Creating 2 decoder thread(s)
 CConn:       connected to host xeeleel port 5900
 CConnection: Server supports RFB protocol version 3.7
 CConnection: Using RFB protocol version 3.7
 CConnection: Choosing security type None(1)
 X11PixelBuffer: Using default colormap and visual, TrueColor, depth 24.
 DesktopWindow: Adjusting window size to avoid accidental full screen request
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Using Tight encoding
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
```

It seems that those error messages are produced by an old fontconfig library that is statically linked to the tigervnc binary that you distribute.
Another undesirable side effect is that it creates a ~/.cache/fontconfig/ directory with many cache files instead of using the system wide /var/cache/fontconfig/ directory.

I see 2 solutions:
 - either link fontconfig dynamically (and use fontconfig from the system)
 - or build tigervnc with a more recent fontconfig

**Comment by bphinz** [comment]
You're talking about the generic tar ball, not the 16.04 .debs, right?

**Comment by LaurentBonnaud** [comment]
> You're talking about the generic tar ball, not the 16.04 .debs, right?

Yes.

**Comment by CendioOssman** [comment]
The generic tar balls are meant to be run everywhere, so I'm afraid we have to statically link fontconfig. Upgrading it might solve the issue for you, and cause the same issue for everyone on systems with an older version. So there is no real way to solve this.

I suggest you take the 16.04 packages and recompile them for 16.10. Then you'll get a build that's nicely integrated with your libraries.
