### ISSUE TITLE
gnome-terminal stops working after started VNC server

### ISSUE THREAD

**Issue by aaronlu** [TigerVNC/tigervnc#407]
Steps to reproduce:
1 boot up
2 login to gnome
3 launch gnome-terminal(everything works well now)
4 start vnc session by running cmd: vncserver (provided by tigervnc-server)
5 close gnome-terminal
6 launch gnome-terminal again, problem occurs.
7 run vncserver -kill :1 in this problematic gnome terminal, the terminal will go away with the VNC session as if the terminal belongs to the VNC session instead of the local session

When problem occurs, gnome-terminal's menu doesn't respond, e.g. if I click Help->about, nothing happens etc. And the copy/paster functionality is also lost.

I have filed a bug for gnome-terminal:
https://bugzilla.gnome.org/show_bug.cgi?id=777772
And the GNOME developer Christian Persch hinted me to check the environ file of the gnome-terminal-server process in step 3 and 6:
aaron@localhost:~$ diff -u 3 6
--- 3	2017-01-26 23:15:49.847835529 +0800
+++ 6	2017-01-26 23:15:49.847835529 +0800
@@ -1,5 +1,5 @@
 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
-DISPLAY=:0
+DISPLAY=:1
 GNOME_DESKTOP_SESSION_ID=this-is-deprecated
 HOME=/home/liveuser
 LANG=en_US.UTF-8

Quote Christian of his comment there:
"
So starting vncserver alters the dbus activation environment of the dbus session bus that belongs to :0 (gnome session, I guess). It has no business doing that.
"

So I'm submitting the issue here.

The problem starts to appear in Fedora 24, which ships with tigervnc 1.6 IIRC. The problem is still here with Fedora 25 tigervnc-server-1.7.1-1.fc25.x86_64.

**Comment by CendioOssman** [comment]
I'm afraid this is pretty much per design. Not ours though. The Linux desktop crowd decided some time ago that running multiple sessions as the same user is too much hassle. So I'm afraid you cannot have a local session and a VNC session running as the same user at the same time.

**Comment by aaronlu** [comment]
OK I see.

One more information, the following error message appeared every time when I killed the vnc session.

[ 1512.597704] gnome-session-f[8173]: segfault at 0 ip 00007fd9d5d00899 sp 00007ffd05a83940 error 4 in libgtk-3.so.0.2200.7[7fd9d5a22000+6f6000]

It appeared when I start the VNC session as another user, i.e. not the same user that is running a local GNOME session.

Any idea if this is a GNOME bug or a VNC one? Thanks.

**Comment by CendioOssman** [comment]
That would be a GNOME bug. We don't integrate with the applications on a level where we could cause crashes.
