### ISSUE TITLE
Ubuntu 16.04 package lacks a dependency

### ISSUE THREAD

**Issue by LaurentBonnaud** [TigerVNC/tigervnc#408]
Hi,

I installed the `xtigervncviewer_1.7.1-1ubuntu1_amd64.deb` package on my system, and got the following error:

```
$ xtigervncviewer 
xtigervncviewer: error while loading shared libraries: libfltk_images.so.1.3: cannot open shared object file: No such file or directory
```
Installing the `libfltk-images1.3` package fixed the problem.

**Comment by bphinz** [comment]
Thanks for the heads up, I'll add that to the dependency list.
