### ISSUE TITLE
x0vncserver: execute a user script when someone success to connect?

### ISSUE THREAD

**Issue by chlohr** [TigerVNC/tigervnc#410]
Dear all, 
  Just a short question: is there any way for x0vncserver to execute a user script/command when someone success to connect to the current session?
A special option? Or an X event? any trick?

Best regards.

**Comment by CendioOssman** [comment]
No, I'm afraid x0vncserver has no such hooks or events.

**Comment by chlohr** [comment]
Hi,
  So, may I propose a patch for this.
This adds two parameters "StartHook" and "StopHook" that are executed (in background) when a remote session starts and ends.

Best regards

Note: A use-case for lightdm users could be to have a StartHook with something like "killall light-locker; chvt $XDG_VTNR" ... ;-)

[x0vncserver_start_stop_hook.patch.txt](https://github.com/TigerVNC/tigervnc/files/753128/x0vncserver_start_stop_hook.patch.txt)
