### ISSUE TITLE
x0vncserver: unable to open display ":0"

### ISSUE THREAD

**Issue by qnxor** [TigerVNC/tigervnc#411]
I'm on Ubuntu 16.04.1 with the .deb version 1.7.1 installed and I'm trying to get x0vncserver to work. My Ubuntu runs LightDM (standard setup). The following fails:

```
# x0vncserver -display :0 -SecurityTypes None
No protocol specified
x0vncserver: unable to open display ":0"
```
I also tried without -SecurityTypes, and with other parameters. It always fails with the same error as above.

x11vnc works just fine. The following works fine and I can access it on port 5900:
```
x11vnc -xkb -noxrecord -noxdamage -repeat -rfbauth /etc/x11vnc.pass -rfbport 5900 -auth /var/run/lightdm/root/:0 -forever -bg -o /var/log/x11vnc.log
```

I'm a bit lost. What am I missing?

**Comment by CendioOssman** [comment]
You haven't specified the necessary authorization for x0vncserver to connect to your X server. In x11vnc's case this is the `-auth` argument. So try:

```
$ XAUTHORITY=/var/run/lightdm/root/:0 x0vncserver -display :0 -SecurityTypes None
```

**Comment by qnxor** [comment]
I had actually looked at --help and the man page for a way to tell it which auth to use but neither mention it, and alas, I forgot about the XAUTHORITY env var. It may be worth adding a note about the XAUTHORITY env var in the man page and --help of x0vncserver (if I were you, I'd add a separate command line option for it, like x11vnc).

Tested and working fine (and faster than x11vnc).
