### ISSUE TITLE
Sane installation / building process for Ubuntu 14.04

### ISSUE THREAD

**Issue by aashidham** [TigerVNC/tigervnc#415]
I want to install tigerVNC on my Ubuntu 14.04 LTS x86_64 instance with GLX support. [The instance is hosted on AWS EC2, which means it has NViDia drivers, I think?]

However, it is really fucking frustrating getting this to work. The binary doesn't seem to support glxgears or other OpenGL processes.

Maybe I'm an idiot and I'm missing a configuration flag somewhere when I build this. Regardless, I'm willing to pay somebody if they can provide a Docker image on Docker hub with tigerVNC installed on Ubuntu 14.04 that supports GLX / OpenGL along with a Dockerfile that describes each step of the installation / building process. 

PLEASE. I'm begging you. Somebody do this. I will send Bitcoin to a wallet of your choice if you can do this in 24 hours.

**Comment by CendioOssman** [comment]
I'm afraid Nvidia's drivers screw up OpenGL so that it stops working in Xvnc. So you either have to uninstall those drivers and restore Mesa, or use VirtualGL to avoid depending on OpenGL support in the X server.
