### ISSUE TITLE
Implement reconnect on network outage [$50]

### ISSUE THREAD

**Issue by stormy1777** [TigerVNC/tigervnc#416]
In 1.0.1 there was a prompt that asked to reconnect when network went out (can be even days out, like folded laptop), newer versions do not have it.  Important to prompt the user when to reattempt, and keep prompting until successful connection, OR the user selects NO (to not reconnect).

**Comment by johahauf** [comment]
See pull request #1196, this should be solution for this issue

**Comment by StormyOS** [comment]
Thanks @johahauf ; not sure how to verify, will wait until win7/10 binaries are available, Thanks for the mention!!

**Comment by samhed** [comment]
Should be fixed in master now that #1196 is merged.
