### ISSUE TITLE
minor hack to the vncserver script

### ISSUE THREAD

**Issue by abelew** [TigerVNC/tigervnc#420]
Greetings,
  I modified slightly the vncserver script so that it prints out what one must do to connect to the new vncserver via remmina, cotv, or a ssh tunnel; I think I might have set a few defaults too.

  I am attaching it here in the hopes that it proves useful.
[vncserver.txt](https://github.com/TigerVNC/tigervnc/files/797237/vncserver.txt)

**Comment by CendioOssman** [comment]
Thank you. Could you send this as a pull request instead? It's much easier to review and merge that way.
