### ISSUE TITLE
Implement "Fit to window" option

### ISSUE THREAD

**Issue by warmos** [TigerVNC/tigervnc#424]
This can be really useful, when connecting to a host with high resolution. Scrollbars are extremely inefficient.
Thanks

**Comment by warmos** [comment]
Apologies, found it here
https://github.com/TigerVNC/tigervnc/issues/274
But still, is it going to be implemented? It has been requested almost year ago.

**Comment by CendioOssman** [comment]
Probably at some point, but there isn't anyone working on it right now AFAIK.
