### ISSUE TITLE
build xserver error on 14.04 x86_64

### ISSUE THREAD

**Issue by songzhiqiangEx** [TigerVNC/tigervnc#429]
i run xserver configuration successful
when make xserver show error below:
events.c: In function ‘DetachFromMaster’:
events.c:1461:54: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     dixSetPrivate(&dev->devPrivates, GrabPrivateKey, (void *)id);
                                                      ^
events.c: In function ‘ReattachToOldMaster’:
events.c:1477:10: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
     id = (int)p; /* silence gcc warnings */

How to fix this error . thanks

**Comment by CendioOssman** [comment]
I'm afraid events.c is not a file from TigerVNC but from Xorg, so it's not something we can fix. Are you using the same version of Xorg as Ubuntu 14.04 uses? Have you checked how Ubuntu are building it? Special flags might be needed.

**Comment by songzhiqiangEx** [comment]
@CendioOssman thank you for our advice
    I run it successful on my ubuntu system.
    I have another question,why not use udp protocol on the server side and can i  replace by udp protocol in my application?

**Comment by songzhiqiangEx** [comment]
@CendioOssman thank you for your advice
I run it successful on my ubuntu system.
I have another question,why not use udp protocol on the server side and can i replace by udp protocol in my application?

**Comment by CendioOssman** [comment]
VNC requires a reliable transport so UDP would not work.
