### ISSUE TITLE
Where can i read more ? 

### ISSUE THREAD

**Issue by Adgreen** [TigerVNC/tigervnc#431]
Where can i read more ? 

Where can i read more about how to start a safe encrypted tunnel/ channel, for instance SSH  - and then run Tiger VNC in that ?

( Have I understood right ?  That method / work flow. : To open a safe encrypted tunnel/ channel, for instance SSH  - and then run Tiger VNC in that ?

I want to conect to my VPS, WinServer 2016 - from my Vista and Win10 machine. 

I connected with SSH through Putty before - that is the reference i have.  
And I have installed and run Tiger VNC - but with out the safety of a secure encrypted tunnel/ channel, for instance SSH  - and then run Tiger VNC in that

**Comment by bphinz** [comment]
The most recent version of the TigerVNC java client has an integrated SSH client that is configurable via the GUI.  If you bring up the Options dialog and click the "Tunnel VNC over SSH" checkbox on the "SSH" tab before connecting, it will automatically open up an SSH tunnel to the server host and forward the connection through it.

**Comment by Adgreen** [comment]
Hmmm ... 
I have searched these pages  ( below ) for the word java - regarding my Q :  "I want to conect to my VPS, WinServer 2016 - from my Vista and Win10 machine".
Only finding TigerVNC java client for OS Ubuntu ....
Do you mean that I can run those TigerVNC java client for OS Ubuntu - When I want to conect to my VPS, WinServer 2016 - from my Vista and Win10 machine. 

http://tigervnc.bphinz.com/nightly/
http://tigervnc.org/
https://bintray.com/tigervnc/stable/tigervnc

**Comment by bphinz** [comment]
The java client can run on any platform that has Java 6 or higher installed.  It looks and behaves as similar to the native (Fltk) client as possible.  You can download the standalone jar file directly from bintray:

https://bintray.com/tigervnc/stable/download_file?file_path=VncViewer-1.7.1.jar

**Comment by Adgreen** [comment]
( and yes I can connect with the Java viewer without the SSH tunnel - so the VNC Server - Java Viewer set up is working. )

But ... 

Do I need to install som SSH Server on the machine I want to conect to - my VPS, WinServer 2016.
Where can i read more about this ?
Yes - I have clicked the "Tunnel VNC over SSH" checkbox on the "SSH" tab.
I´v tried all variations ; Administrator, administrator, ADMINISTRATOR @ {  My IP number  } 
( and yes Administrator on my VPS. )
( and yes I can connect with the Java viewer without the SSH tunnel - so the VNC Server - Java Viewer set up is working. )
And/ But there are more alternatives ; Use ext SSh client and some embedded SSH Client config.
Where can i read more about this ?

But probably first 
Do I need to install som SSH Server on the machine I want to conect to my VPS, WinServer 2016.

**Comment by Adgreen** [comment]
I have pressed "F1" for help - nothing ...

I have read and searched all the Man files for SSH.  I have found the text ( below ). But I don't know if it applies when I want to connect to - a VPS, WinServer 2016.

Where can i read more about this ?  In a normal help format ? 

But probably first ...
Do I need to install some SSH Server on the machine I want to conect to, my VPS, WinServer 2016.

Then do i need to use this −via gateway ??

So perhaps ... Then this text, "assuming that SSH client binary can be accessed as /usr/bin/ssh"  I assume the Java viewer can that .. 

Should I then use this −via gateway and set host machine name to "localhost"

−via gateway
Automatically create encrypted TCP tunnel to the gateway machine before connection, connect to the host through that tunnel (TigerVNC−specific). By default, this option invokes SSH local port forwarding, assuming that SSH client binary can be accessed as /usr/bin/ssh. Note that when using the −via option, the host machine name should be specified as known to the gateway machine, e.g. "localhost" denotes the gateway, not the machine where vncviewer was launched. The environment variable VNC_VIA_CMD can override the default tunnel command of /usr/bin/ssh -f -L "$L":"$H":"$R" "$G" sleep 20. The tunnel command is executed with the environment variables L, H, R, and G taken the values of the local port number, the remote host, the port number on the remote host, and the gateway machine respectively.

**Comment by Adgreen** [comment]
Can i use vncconfig for my Tiger Java Viewer ?

C:\Users\administrator\Downloads>VncViewer-1.7.1.jar -help   This opens no Help

Where can i read more about this ? In a normal help format ?

**Comment by bphinz** [comment]
The simplest solution is to have an SSH running on your VNC server (I'm a Unix guy - that's outside my wheelhouse, so sorry but I can't help with that).  Then you should be able to just select that single checkbox and be done.  The other options are just there for more exotic situations.  For example, you could use an external SSH client and set a custom command line in order to set up additional port forwarding, etc.  It doesn't sound like you need anything like this though

**Comment by bphinz** [comment]
> Can i use vncconfig for my Tiger Java Viewer ?

No, vncconfig is used to control the server.

> C:\Users\administrator\Downloads>VncViewer-1.7.1.jar -help This opens no Help

Jar files don't execute by themselves, they're run by the java interpreter.  `java -jar VncViewer-1.7.1.jar -help` will print out help.

**Comment by bphinz** [comment]
> So perhaps ... Then this text, "assuming that SSH client binary can be accessed as /usr/bin/ssh" I assume the Java viewer can that ...

You do not need an external SSH client, the TigerVNC Java client includes an embedded SSH client.  The option to use an external SSH client is just there for advanced situations where users need more control over the SSH protocol, authentication methods, etc.  A binary SSH client might offer better performance, but in practice I've never seen a significant difference between the embedded SSH client and an external one.

**Comment by Adgreen** [comment]
Your last comment just disappeared ...

**Comment by Adgreen** [comment]
Oh no - it came back !!!

**Comment by Adgreen** [comment]
Click single checkbox ?  

Meaning Just "Tunnel VNC over SSH".  And not click anything or fill in anything below ... 

Not even putting in Username and hostname/ IP address ?

**Comment by Adgreen** [comment]
I love to have "an SSH running on your VNC server", e g my VPS, WinServer 2016.

I´v gone through all the man files now ;

Do I need an SSH server on my VPS, WinServer 2016.?
how do I see If I have that on my VPS, WinServer 2016 ?
If so - How do I install for instance some Open ssh server or something like that on my VPS, WinServer 2016.

Something that works with Tiger Java Viewer

**Comment by bphinz** [comment]
Yes.  Uncheck "Use SSH gateway" and it will create an SSH tunnel to the VNC server.  As part of the SSH protocol, you will be prompted for username/password (note that this is in addition to your VNC credentials).

**Comment by Adgreen** [comment]
If I try something like this - and Succeed - Should I post that here ? 

https://github.com/PowerShell/Win32-OpenSSH/releases/

Do you think something like that could ba a SSH server form my VPS, WinServer 2016

**Comment by Adgreen** [comment]
OK - I´m learning ....

And I believe i´ll take all this into my suggestion for the Wiki Entry.

My ref source for this General, Portal, Q :  See Quote below : https://en.wikipedia.org/wiki/Secure_Shell#Architecture

To allow for Collaboration, Teamwork, ( like for instance Teamviewer.com sometimes is used ). Does SSH have advantages over TLS. For instance the ability to multiplex many secondary sessions into a single SSH connection, 

++ Also related - What amazes me about MS Remote Desktop is that one can not connect more then one client before the first one id thrown out ( unless using shadow user- session etc etc - complicated, not User Friendly ).

So ... There is a lot I like about Tiger.  ? Do we loose the ability to have lets say 3 - 5 clients/ viewers connected to the same Server desktop - with TLS or SSH - or what are the Pros and Cons

"This open architecture provides considerable flexibility, allowing the use of SSH for a variety of purposes beyond a secure shell. The functionality of the transport layer alone is comparable to Transport Layer Security (TLS); the user-authentication layer is highly extensible with custom authentication methods; and the connection layer provides the ability to multiplex many secondary sessions into a single SSH connection, a feature comparable to BEEP and not available in TLS."

**Comment by CendioOssman** [comment]
> Q : Do we loose the ability to have let´s say 3 - 5 clients/ viewers connected to the same Server desktop - with TLS or SSH ?
> 

No, that's a VNC thing and it doesn't matter what the transport is.

> Or what are the Pros and Cons with SSH, TLS.

The big advantage of TLS is that everything is built in to TigerVNC, whilst SSH will always require extra components (at minimum a SSH server). SSH also has a lot of extra functionality you may not want.
The advantage of SSH is that if you already have a server with SSH then you don't need to open more ports in your firewall. It also means just opening a single port no matter how many VNC servers you have.

There should not be any significant difference when it comes to security or performance.

**Comment by Adgreen** [comment]
Don't we learn more if, I Test SSH on my Server, WinSer 2016.

And wider future use, e g ; just opening a single port no matter how many VNC servers you have.

More knowledge to our Wiki.

I see two choices - so that I/We dont spend time on the wrong thing here - My little Research so far ; 

A Github project "This is a pre-release (non-production ready)" ??  ( My 5 - 1 0 minute reading, it seem little unstable .. But I might be wrong ... )  Link below.

A more established with the CygWin open source project. Link below.

( Openssh.com  has nothing regarding Windows platform as far as I see - but they refer some what to the Github project, see below. )

https://github.com/PowerShell/Win32-OpenSSH/releases
"This is a pre-release (non-production ready)" ??

CygWin.com : ( Ref below )
https://cygwin.com/packages/package_list.html
https://cygwin.com/packages/x86_64/openssh/

Microsoft "Contribution",  OpenSSH for Windows Update
Most all other SSH tags on MS Developer Network goes to here.
https://blogs.msdn.microsoft.com/powershell/2015/10/19/openssh-for-windows-update/
And from here everything rtefers to the same Github Project ; https://github.com/PowerShell/Win32-OpenSSH/releases

..............................................

Ref, Cygwin :  It is free and open source software, 
Cygwin was originally developed by Cygnus Solutions, which was later acquired by Red Hat. It is free and open source software, released under the GNU Lesser General Public License version 3. Today it is maintained by employees of Red Hat, NetApp and many other volunteers. 
wikipedia.org/wiki/Cygwin

**Comment by Adgreen** [comment]
https://github.com/PowerShell/Win32-OpenSSH/releases´

Txt Txt 
Txt Txt 
Txt Txt

**Comment by Adgreen** [comment]
t ; https://github.com/PowerShell/Win32-OpenSSH/releases

..............................................

Ref, Cygwin : It is free and open source software,
Cygwin was originally developed by Cygnus Solutions, which was later acquired by Red Hat. It is free and open source software, released under the GNU Lesser General Public License version 3. Today it is maintained by employees of Red Hat, NetApp and many other volunteers.
wikipedia.org/wiki/Cygwin
