### ISSUE TITLE
A small contribution ...

### ISSUE THREAD

**Issue by Adgreen** [TigerVNC/tigervnc#432]
A small contribution ...

The text ( below ) on https://bintray.com/tigervnc/stable/tigervnc.  Should it not also say Windows ... 

"Pre-built packages for Red Hat/CentOS 5 & 6, Ubuntu 12.04LTS & 14.04LTS are available. Use the "Files" link to browse to them."

Like the text on http://tigervnc.org/   says . "installers for 64-bit and 32-bit Windows".

**Comment by bphinz** [comment]
The Windows installers and standalone client executables are directly visible on that page.  The point of the note was to alert people where to find the distribution-specific package files (a lot of people were having trouble finding them).  I guess the note could be clarified a bit though.

**Comment by CendioOssman** [comment]
Will you have a look at that @bphinz ?

**Comment by bphinz** [comment]
I updated the description field in the bintray stable, 1.7.0, and 1.7.1 releases to read:

_Installers for Microsoft Windows and Mac OS X, as well as stand alone viewers for Windows, Unix, and Java can be downloaded using the links below. Pre-built packages for Red Hat/CentOS 6 and 7, Ubuntu 12.04LTS, 14.04LTS, and 16.04LTS are available. Use the "Files" link to browse to them._
