### ISSUE TITLE
Leaking shared memory

### ISSUE THREAD

**Issue by morgangreen** [TigerVNC/tigervnc#434]
It looks like shared memory segments created by the tigervnc viewer don't go away until the viewer exits even if they are no longer in use. I just closed a tigervnc instance which had created 250 ~32MB shared memory segments according to 'ipcs -m'. All but one of those segments was marked for destruction, but they weren't destroyed because the X server was still attached to them. Those segments accounted for almost all of the 8GB of available System V shared memory and were causing other applications which tried to use shared memory to fail.

The problem appears to happen each time I resize the viewer window. From 'ipcs -m' output I see that each time I resize the old shared memory segment is marked for destruction, but not actually destroyed.

I briefly looked at the code. It looks like tigervnc code is both destroying the shared memory segment with shmctl with cmd=IPC_RMID and detaching from it with shmdt. However it asks the X server to attach to it with XShmAttach, but never calls XShmDetach. So I think the shared memory segments don't go away until the viewer exits because the X server is still attached to them. I think this could be fixed by adding an XShmDetach call to X11PixelBuffer::~X11PixelBuffer in the 1.7.0 branch and PlatformPixelBuffer::~PlatformPixelBuffer in master.

**Comment by CendioOssman** [comment]
Are you using `master`? Because this should have been fixed in 1d2556fb31a32604cebad3915531a9ddcb53ad89.

**Comment by morgangreen** [comment]
I'm currently using 1.7.1, but I don't see how that change would fix the problem.

That change fixed a different type of shared memory leak where if the viewer process was killed or crashed the shared memory segment it had created was not destroyed and would live on after the viewer process.

The leak I reported is cleaned up when the process is killed or crashes because at that point the X server detaches from shared memory segments that vncviewer asked it to attach to. Two things must happen before a shared memory segment is destroyed:

1) The segment must be marked for destruction with shmctl(shmid, IPC_RMID, 0)

2) All processes must detach from the shared memory segment

The fix you mentioned makes sure that the first requirement is met even if the process doesn't exit cleanly by always doing that as soon as it has attached to the segment. However currently the second requirement is not met until vncviewer exits or is killed because while it detaches from shared memory segments when it is done with them it never tells the X server to detach from them with XShmDetach.

It is easy to reproduce the problem and observe the leak:

1) vncviewer foo:1
2) In another terminal on the machine running vncviewr: ipcs -m
3) Note the number of shared memory segments
4) Resize the vncviewer window
5) ipcs -m
6) Notice that a new segment appeared, but all previous segments still exist. With 1.7.1 the status of a previous segment will also have changed to "dest", but with master due to the change you mentioned I think it would already have been "dest".
7) Repeat steps 4-6 as many times as you like and notice that shared memory segments keep being added and the old ones are not actually destroyed. Do it enough times and vncviewer will use all available System V shared memory and you will be unable to use other applications which depend on it.
8) close vncviewer
9) notice that all the segments were cleaned up.

**Comment by CendioOssman** [comment]
Ah, I see. I'll have a look and get it sorted out.

**Comment by CendioOssman** [comment]
Fixed in fbbd48b35e53fb156b91715dae4aab9008533565. Thanks for finding this.
