### ISSUE TITLE
LDAP + TigerVNC

### ISSUE THREAD

**Issue by caiosoutomaior1812** [TigerVNC/tigervnc#435]
Hi, is it possible to define groups of Active Directory accesses?

I would like to define which groups can have access to certain computers.

**Comment by CendioOssman** [comment]
Not directly, no. But if you use TigerVNC's PAM authentication system then you can usually control this via your PAM configuration. Note though that this requires you to use the `Plain` authentication types, and often only works if the VNC server runs as root.

**Comment by awarre** [comment]
@CendioOssman This would imply it is not possible at all when running a Windows TigerVNC server, correct?

**Comment by CendioOssman** [comment]
Correct. Windows does not have any central configuration with the same flexibility as PAM.

**Comment by hildred** [comment]
fyi: pam was ported to windows at least once https://www.usenix.org/publications/library/proceedings/usenix-nt98/full_papers/itoi/itoi.pdf
