### ISSUE TITLE
Double free in server caused by fences

### ISSUE THREAD

**Issue by michalsrb** [TigerVNC/tigervnc#437]
If client sends fence with some data, followed by a fence with no data (length 0), the `VNCSConnectionST::fence` will delete `VNCSConnectionST::fenceData`, but keep it pointing at the same memory:

      delete [] fenceData;
      if (len > 0) {
        fenceData = new char[len];
        memcpy(fenceData, data, len);
      }

      return;

If the client sends another fence or if it disconnects the `VNCSConnectionST::fenceData` is deleted for second time. It can crash the whole server or possibly cause some security issues.

It is not clear to me from the RFB protocol documentation if fences with zero length are ok. If not, then `SMsgReader` should reject it. If they are ok, then `VNCSConnectionST` needs to set the `fenceData` to null and `SMsgWriter::writeFence` must be able to write that kind of fence back to client.

**Comment by CendioOssman** [comment]
They should be ok, so we should fix the quoted code.
