### ISSUE TITLE
Debian Jessie support? - two dependencies not available

### ISSUE THREAD

**Issue by dkebler** [TigerVNC/tigervnc#446]
Trying to install 1.7.1 server  from the deb package on debian jessie   

I got most of the dependencies to install except these two.    Are you going to support Jessie without these?  (i.e. use alt/newer libraries?).  Looks like the` libgnutls28-dbg `is all that's available with jessie stable the other (`turbo8`) is not in any debian repository.

```
root@gateway:~# apt install libgnutls28
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgnutls28 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgnutls28' has no installation candidate
root@gateway:~# apt install libjpeg-turbo8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libjpeg-turbo8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libjpeg-turbo8' has no installation candidate

```

**Comment by bphinz** [comment]
Debian jessie is not one of the distros that we provide packages for.  Generally speaking, we can only support the "enterprise" or LTS distros.  Not enough bandwidth to handle the fast-moving distros...

**Comment by hildred** [comment]
Jessie also has its own package of tigervnc and it is not too old.
