### ISSUE TITLE
XServer crash with dummy driver and vnc module

### ISSUE THREAD

**Issue by grulja** [TigerVNC/tigervnc#448]
Using xorg 1.19 and dummy driver + vnc module makes Xserver to crash due to latest change in vncHooks.c. It's specifically this commit [1] as this issue is not reproducible with Tigervnc 1.7.1 or with 1.7.90 and reverted mentioned commit. I'm also attaching the backtrace, let me please now whether you need more information.

[1] - https://github.com/TigerVNC/tigervnc/commit/84c72feb3999339fc

[xorg_crash.txt](https://github.com/TigerVNC/tigervnc/files/963833/xorg_crash.txt)
6529b4b0abae9b50fee4245

**Comment by grulja** [comment]
Ok, I did some investigation and I think I spotted potential problem:
In previous code I see there was call:
**rp->rrCrtcSet = vncHooksScreen->RandRCrtcSet;**
which you replaced by:
**unwrap(vncHooksScreen, rp, rr##field);**
but if I'm not mistaken this will produce:
**rp->rrCrtSet = vncHooksScreen->rrCrtSet**
which is different from previous call

**Comment by grulja** [comment]
If that's true, then it applies also to the function above, but I was looking into the part mentioned in backtrace.

**Comment by CendioOssman** [comment]
That member was renamed in order to make the macros possible. It would not have compiled otherwise.

The backtrace shows that it hit an assert. Do you have the logs to see which assert?

And why are you using the dummy driver instead of Xvnc?

**Comment by grulja** [comment]
Aha, I see so I was wrong. The reason why we use the dummy driver is that some machines are without a graphic card, also the dummy driver works with GDM service.

Attached Xorg.log if you meant that.But I don't see anything relevant there. Also interesting is that this is reproducible only when you use "startx", running Xserver using "X", or "xinit" or "Xorg" seems to avoid the crash.
[xorg_log.txt](https://github.com/TigerVNC/tigervnc/files/964300/xorg_log.txt)

**Comment by CendioOssman** [comment]
> Aha, I see so I was wrong. The reason why we use the dummy driver is that some machines are without a graphic card, also the dummy driver works with GDM service.

Neither of these should be a problem with Xvnc.

> Attached Xorg.log

This is not the same crash as the first report, so please try again so that we get something consistent. It also looks like you have some problem with missing debug symbols.

**Comment by grulja** [comment]
It should be the same, I now managed to get the backtrace again and with corresponding log. I just don't know why in the xorg.log the backtrace is not complete, but the crash got catched by abrt and generated coredump which I opened in gdb. It also seems to be related to xinit as starting xserver with it makes it crash.

[xorg_crash.txt](https://github.com/TigerVNC/tigervnc/files/964827/xorg_crash.txt)
[xorg_log.txt](https://github.com/TigerVNC/tigervnc/files/964828/xorg_log.txt)

**Comment by grulja** [comment]
Already fixed by https://github.com/TigerVNC/tigervnc/pull/453.
