### ISSUE TITLE
Multiple viewer windows on OS X

### ISSUE THREAD

**Issue by LicoMonch** [TigerVNC/tigervnc#45]
I am using MacOS X (10.9.5) and TigerVNC Viewer 1.3.0.

After installing the viewer into the applications, one can simply start it from there or (if pinned to) from the dock - but only once.
But that way it is impossible to start a second or more sessions.

Workaround for me so far is to change to /Applications/TigerVNC Viewer 1.3.0.app/Contents/MacOS and start it manually (./TigerVNC\ Viewer). (But this also adds more "TigerEye"-icons to the dock.)

Does the "App" offer any way of starting another session, eg. via short cut?

Greetings,
Lico

**Comment by CendioOssman** [comment]
A menu has now been added for creating new viewers. Unfortunately the multiple dock entries is a misfeature of OS X and I don't see any clean way of solving that. You get the same effect if you start multiple instances of e.g. the calculator.

**Comment by LicoMonch** [comment]
Thank you for this new feature. Multiple dock icons are something easy to live with ;)

**Comment by selvamani-ramasamy** [comment]
Launching the viewer from terminal allows more then one instance.  Thanks.
