### ISSUE TITLE
Connection issues between VNC server and VNC viewer on same network but OK on separate networks

### ISSUE THREAD

**Issue by vikasg-tx** [TigerVNC/tigervnc#454]
Hi All,

I have a Linux box on which I am running the TigerVNC Server. The Linux box has been assigned a static IP (say StaticIP1). The Linux box is hardwired to the work router.

I am trying to connect to the Server through my Mac laptop which has TigerVNC viewer running. When I am on the same network as the Linux box, connected through a dynamically assigned IP (on WiFi) from the work router, I am unable to connect to the VNC server. When I ping the StaticIP1 from my Mac (using XQuartz), I see the pings go through without a problem. Please also note that my WiFi connection to the web is also working fine.

When I change the IP of my Mac to another static IP (say StaticIP2) at work, I am able to connect to the VNC server on the Linux box with no problem.

Further from home, I am able to connect my Mac to the VNC Server even though my home router dynamically assigns an IP to the Mac.

I am trying to understand why I am unable to connect to the VNC server through a dynamically assigned IP at work.

I have checked with my internet provider and they see no problems with the router or the static IPs that have been assigned to me. They think is a "software" problem.

I have also checked with RedHat and they think it is a network problem....

PLEASE HELP!! I am not an IT person. I work at a start-up and am trying to get my work done. I know enough about computer networks and protocols to get myself into trouble.

Thanks!

**Comment by CendioOssman** [comment]
Sounds like you have some misconfiguration of your network settings. Most likely with the subnetting.

What is the address and netmask in the static cases? And what are those in the dynamic cases?

**Comment by vikasg-tx** [comment]
Thank you very much for the pointer. Let me look at the settings and let you know.

**Comment by vikasg-tx** [comment]
Hi,

The subnet on the Linux box with static IP is 255.255.255.248.

The subnet on the mac for dynamically assigned IP is 255.255.255.0.
The subnet on the mac for manually assigned static IP is 255.255.255.0.

Could this be the problem? Please recall, when I manually assign a static IP to the mac, I am able to connect to the Linux box.

Thanks,

**Comment by CendioOssman** [comment]
On 08/05/17 23:13, vikasg-tx wrote:
> Hi,
> 
> The subnet on the Linux box with static IP is 255.255.255.248.
> 
> The subnet on the mac for dynamically assigned IP is 255.255.255.0.
> The subnet on the mac for manually assigned static IP is 255.255.255.0.
> 
> Could this be the problem? Please recall, when I manually assign a static IP to the mac, I am able to connect to the Linux box.
> 

Indeed. The mask must always be the same or you can end up with the 
machines on different networks. I would suggest changing the Linux box 
as 255.255.255.248 is a very tiny network.

Regards
-- 
Pierre Ossman           Software Development
Cendio AB		http://cendio.com
Teknikringen 8		http://twitter.com/ThinLinc
583 30 Linköping	http://facebook.com/ThinLinc
Phone: +46-13-214600	http://plus.google.com/+CendioThinLinc

A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by vikasg-tx** [comment]
Hi - changing the subnet of the Linux box from 255.255.255.248 to 255.255.255.0 disconnects the Linux box from the internet. When I ping the IP from my mac, the ping times out. The 255.255.255.248 subnet was the address provided by the ISP when assigning static IPs to my company.

**Comment by CendioOssman** [comment]
That's very odd and should not happen.

You're going to have to give us a more complete picture of your network system. A drawing would be nice. And include all information about addresses, netmasks and gateways. We can't help if we have to guess half the stuff.
