### ISSUE TITLE
Java viewer disregards SSH gateway address

### ISSUE THREAD

**Issue by gradinaruvasile** [TigerVNC/tigervnc#455]
In 1.8 beta (i think in older versions too) the Tigervnc Java viewer does not use the set ssh gateway address. Instead it wants to connect via ssh to the address specified in the server address.
Example:
I have xvnc running in a remote machine, lostening only on localhost and ssh running on the default 22 port. Thus i want to connect to the remote machine's ssh adress (1.1.1.1:22) and then connect to the server running only on localhost.
So i enter for example:
localhost:5900 as vnc server
1.1.1.1 as ssh gateway in the options

What happens is that the vnc viewer tries to connect to localhost:22 for ssh authentication (instead of connecting to 1.1.1.1:22). I tried using 127.0.0.1 instead of localhost, it does the same.

**Comment by bphinz** [comment]
Fixed in 8381fcc.  Thanks for pointing this out.

**Comment by bphinz** [comment]
Looks like there's still some corner cases where it's still not right.  Should have it fixed shortly.

**Comment by bphinz** [comment]
OK, should be fixed properly now.  Please test it out and confirm.  If you find any further problems please reopen the issue.  Thanks.
