### ISSUE TITLE
Getting "No password configured for VNC Auth" with Password Already Set

### ISSUE THREAD

**Issue by jmacera** [TigerVNC/tigervnc#457]
I am running RedHat Linux v7 on System z.  I am attempting to use VNC to support full screen applications.  I started it successfully and it is running as root.

[root@tvt6065 ~]# startx
xauth:  file /root/.serverauth.63746 does not exist

Xvnc TigerVNC 1.3.1 - built Sep 13 2016 10:03:38
Copyright (C) 1999-2011 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11702000, The X.Org Foundation

Thu May 11 11:26:53 2017
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5900
 vncext:      created VNC server for screen 0
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
gnome-session-is-accelerated: llvmpipe detected.

[root@tvt6065 ~]# ps -ef | grep X
root     64356 64337  0 11:45 pts/0    00:00:00 xinit /etc/X11/xinit/xinitrc -- /usr/bin/X :0 -auth /root/.serverauth.64337
root     64357 64356  0 11:45 pts/0    00:00:00 /usr/bin/X :0 -auth /root/.serverauth.64337
root     64497 64359  0 11:45 ?        00:00:00 /usr/bin/ssh-agent /etc/X11/xinit/Xclients

My objective is to run it without security, since I am working totally internally.  When I attempt to login using the VNC Client I get prompted for a password.  I enter the password I had set using vmcpasswd and get these errors:

On Linux:

Thu May 11 11:48:14 2017
 Connections: accepted: 9.85.140.138::50053
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Thu May 11 11:48:24 2017
 SVncAuth:    neither Password nor PasswordFile params set
 SConnection: AuthFailureException: No password configured for VNC Auth
 Connections: closed: 9.85.140.138::50053 (No password configured for VNC Auth)

On the Client:
No password configured for VNC Auth

The password file exists in the root directory for the root user:

[root@tvt6065 .vnc]# ls -la
total 8
drwxr-xr-x.  2 root root   19 May 10 16:29 .
dr-xr-x---. 24 root root 4096 May 11 11:45 ..
-rwxrwxrwx.  1 root root    8 May 10 17:21 passwd

Any ideas how to fix this?

Thank you for your assistance.

**Comment by CendioOssman** [comment]
The clue is in the log:

```
 SVncAuth: neither Password nor PasswordFile params set
```

One of those need to be configured for password authentication to function.

If you want to completely remove it then you need to change the `SecurityTypes` setting. Set it to `None` to let people straight in.

**Comment by jmacera** [comment]
Duh!  Thank you very much Pierre.  I was reading that message (and found other posts) to indicate the password hadn't been set using vncpasswd.  I started the server with -SecurityTypes=none and it works great!

**Comment by syed191** [comment]
-SecurityTypes=none helped me to resolve issue.

**Comment by Sivajida00** [comment]
In which file we need to modify?

**Comment by Sivajida00** [comment]
Whoever facing this issue, The file you need to modify is nano /root/.vnc/config - Uncomment the securitytypes and set to none.

**Comment by plmondor** [comment]
I am getting the same error. How do I fix it? I am running tightvnc on ubuntu. 

/root/.vnc/config does not exist. 

In the user directory under .vnc -- config also does not exist. 

How do I fix this to make every user enter a username and login when connecting vncviewer. 

Yes, I need each user to enter their individual usernames. Regardless of possible better options, this is what my management is requiring so it's what I need to set up if I want to keep getting a paycheck.

**Comment by bphinz** [comment]
If you want to require full user authentication then you probably don't want to be using either SecurityType none or VncAuth.  TigerVNC supports auth types Plain, TLSPlain, and X509Plain in conjunction with PAM, that can be used for user authentication (have a look at the Xvnc man page, specifically the -PlainUsers and -pam_service options).  I don't know what tightvnc supports.

**Comment by xiaoleihuang** [comment]
> I am getting the same error. How do I fix it? I am running tightvnc on ubuntu.
> 
> /root/.vnc/config does not exist.
> 
> In the user directory under .vnc -- config also does not exist.
> 
> How do I fix this to make every user enter a username and login when connecting vncviewer.
> 
> Yes, I need each user to enter their individual usernames. Regardless of possible better options, this is what my management is requiring so it's what I need to set up if I want to keep getting a paycheck.

Have you solved the issue. I have the same problem.

**Comment by zhulianhua** [comment]
> > I am getting the same error. How do I fix it? I am running tightvnc on ubuntu.
> > /root/.vnc/config does not exist.
> > In the user directory under .vnc -- config also does not exist.
> > How do I fix this to make every user enter a username and login when connecting vncviewer.
> > Yes, I need each user to enter their individual usernames. Regardless of possible better options, this is what my management is requiring so it's what I need to set up if I want to keep getting a paycheck.
> 
> Have you solved the issue. I have the same problem.

Have you solved the issue. I have the same problem.

**Comment by choppnz** [comment]
I thought I'd post this here for anyone else... This worked for me...

> -rfbauth is an option for Xvnc, a VNC server that displays a virtual desktop. It allows you to specify a password file that contains the password required for VNC clients to connect to the server. You can create a password file using the vncpasswd command. To use the -rfbauth option, you need to provide the full path to the password file as an argument. For example:



`Xvnc -rfbauth /home/user/.vnc/passwd
`
`Xtigervnc -rfbauth /home/user/.vnc/passwd
`



> This will start a VNC server that requires the password stored in /home/user/.vnc/passwd to connect. You can also use the -rfbport option to specify the port number for the VNC server. For more information, you can check the [Xvnc man page](https://unix.stackexchange.com/questions/23431/authenticating-with-x11vnc-whats-the-difference-between-auth-and-rfbauth) or the [vncpasswd man page](https://linux.die.net/man/1/x11vnc). I hope this helps. 😊

Just make sure the path after -rfbauth is where your passwd file is.
