### ISSUE TITLE
Intermittent failures "No matching security types" for -SecurityTypes None

### ISSUE THREAD

**Issue by yurivict** [TigerVNC/tigervnc#458]
Invocation command: ```vncviewer -SecurityTypes None localhost:0```
VNC server: x11vnc over ssh.

Sometimes this command works and immediately opens the window, but in other cases it fails with the "No matching security types" message.

I couldn't figure out the condition that triggers the failure.
tigervnc-1.7.1 on FreeBSD 11.

**Comment by hildred** [comment]
'The condition that triggers the failure' is that x11vnc requires authentication. Start it with -SecurityTypes None also.

**Comment by yurivict** [comment]
> 'The condition that triggers the failure' is that x11vnc requires authentication.

It certainly does work sometimes with the same command line: ```x11vnc -safer -localhost -nopw -once -display :0```. 

x11vnc doesn't know ```-SecurityTypes None```:
```
13/05/2017 02:03:54 *** unrecognized option(s) ***
13/05/2017 02:03:54 	[1]  -SecurityTypes
13/05/2017 02:03:54 	[2]  None
```
```-nopw``` is accepted though.

Another failure of vncviewer is ```Too many security failures```, even when the previous connection was successful. x11vnc is restarted every time so it doesn't keep connection failure info.

**Comment by CendioOssman** [comment]
Sounds like problems with `x11vnc` rather than TigerVNC.

You could try adding `-Log *:stderr:100` to the `vncviewer` command line. That will let you see the steps of the handshake, but I'm not sure it will tell you anything more.

**Comment by CendioOssman** [comment]
No response. Closing.
