### ISSUE TITLE
Xvnc memory leak

### ISSUE THREAD

**Issue by nikiwaibel** [TigerVNC/tigervnc#460]
i thought it may make sense to reference this
 https://bugs.centos.org/view.php?id=13257
here as well.

**Comment by CendioOssman** [comment]
I'm afraid this report is very vague, so we can't really do much with it. We would need steps on how to reproduce it.

Also, SZ isn't the beast measurement of memory usage. What are the numbers for virtual, resident and shared memory?

**Comment by CendioOssman** [comment]
No response. Closing.
