### ISSUE TITLE
Mouse pointer trapped in top left corner at (0,0)

### ISSUE THREAD

**Issue by khumarahn** [TigerVNC/tigervnc#461]
Hi,

I use tigervnc with the linux server and clients on linux and android (realvnc). I am happy with it, except one thing.

The android client is not usable, because the instant I lift the finger, the mouse pointer jumps to (0,0). I am not sure what the issue is, and I am not sure it is with the tigervnc, but also without android, on the tigervnc's linux client, I would sometimes see two pointers  - one where the mouse is, and one extra at (0,0).

I don't know how to debug this, but I would be happy to run any tests.

**Comment by CendioOssman** [comment]
Sounds like there is something in your session trying to move the mouse pointer. Is this with Xvnc? Could you try running a simpler session? E.g. just xterm.

**Comment by khumarahn** [comment]
Yes, this is Xvnc. I run lxde. My .vnc/xstartup has only
```
exec startlxde
```
I changed it to `exec xterm` and could reproduce the same issue.

**Comment by CendioOssman** [comment]
Hmm.. not sure what could be causing it in that case. Is this one of our builds?

**Comment by khumarahn** [comment]
No, I run Gentoo, so it is built on my machine. The building script is rather straightforward:
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-misc/tigervnc/tigervnc-1.7.1-r4.ebuild

**Comment by CendioOssman** [comment]
Could you try 1.8.0? If nothing else 1.7.1 doesn't really support Xorg 1.19.

**Comment by khumarahn** [comment]
I already running 1.8.0. It is not in Gentoo package tree, but a minor modification of the ebuild for 1.7.1 did the job.

With 1.8.0 it got better a bit: I do not see two pointers where I saw them before. But when I connect from the android phone, the pointer moves normal for a few seconds, and then sticks to the top left screen.

**Comment by CendioOssman** [comment]
Alright. Did you remove this line:

```
		eapply "${FILESDIR}/${PN}-1.7.1-xserver119-compat.patch"
```

And adjust this:

```
		eapply "${FILESDIR}/xserver119.patch"
```

Because those are not suitable for 1.8.0 and could cause issues.

**Comment by khumarahn** [comment]
I removed the first one, but I still apply the patch for xserver119.
My script:
https://pastebin.com/XdL0WaSJ

I created a video:
https://drive.google.com/file/d/0By9Hrz1qA8KDWXBkNHd4VDBrNzA/view?usp=sharing

**Comment by khumarahn** [comment]
To apply xserver119.patch, I do
```
cd unix/xserver || die
eapply "../xserver119.patch"
```

The patch in 1.7.1 is in the Gentoo tree, and it did not work for 1.8.0. But the one in the source archive worked fine.

**Comment by CendioOssman** [comment]
> To apply xserver119.patch, I do

That looks correct.

> I created a video:

Let's focus on our client for now. We can't really debug RealVNC's stuff as well. :)

Could you share the server VNC log file?

**Comment by khumarahn** [comment]
VNC log file:
https://pastebin.com/RLCKgzhz

Yes, it does not seem possible to debug realvnc, and I am not sure that the problem is not with them. But in 1.7.1 I saw the extra pointer at (0,0) with the tiger vnc's viewer.

**Comment by CendioOssman** [comment]
Nothing obvious in there. It did look like both clients were connected at the same time at one point, which could explain things. But it wouldn't explain if the cursor is buggy at other times.

Could you try a fresh session and only use the TigerVNC viewer? Just to make sure the Android client isn't triggering something.

**Comment by khumarahn** [comment]
Hi, I made a new video. This is with 1.7.1 and the tigervnc viewer. No other clients connected.

https://drive.google.com/file/d/0By9Hrz1qA8KDS2taSGM3TW5KNTQ/view?usp=sharing

(you can download the file to see it in the original quality)

You can see that at some point an extra pointer appears and stays at `(0,0)` for some time. I suspect that it is related.

**Comment by CendioOssman** [comment]
Hmm.. it seems like the issue appears when you use vglrun. Does it happen when starting glxgears directly?

**Comment by khumarahn** [comment]
yes, without virtualgl it is the same.
https://drive.google.com/file/d/0By9Hrz1qA8KDSEdUalBlOG9vSVU/view?usp=sharing

**Comment by khumarahn** [comment]
and actually it does not have to be glxgears. If I start another lxterminal, the same happens.

I can give you the address to connect, if you want to try.

**Comment by khumarahn** [comment]
I could not find how to send a private message here... I sent you a facebook message. If that is you.

**Comment by CendioOssman** [comment]
So it's some form of rendering bug. The cursor isn't actually in that coordinate. You can tell because highlights do not change, which they would if the cursor actually moved.

Can you try with our official 1.8.0 build?

**Comment by khumarahn** [comment]
I don't think it is just a rendering bug. I used to run a game, which would move a map depending on where the cursor is. And the map would be scrolling in the direction of the left top corner all the time.

I will try to figure out how to install the official build.

**Comment by khumarahn** [comment]
I installed the official builds for 1.7.1 and 1.8.0.

The problem with the extra pointer as on my two last videos comes only on gentoo's 1.7.1. It does not happen with the official 1.7.1, or gentoo's 1.8.0, or the official 1.8.0.

I could also use the RealVNC's android client with the official 1.7.1, at least for some short time. But it wasn't usable with the official 1.8.0.

**Comment by CendioOssman** [comment]
In that case it doesn't sound like a bug in TigerVNC, but rather something broken in Gentoo's build. So I'm going to go ahead and close this issue. Feel free to open a new issue if you are seeing other problems with our builds.

**Comment by khumarahn** [comment]
The main issue that affects me is with the realvnc viewer. It remains, even with the official builds. It may or may not be tigervnc's bug... I thought that maybe the extra pointer is something related, and is worth investigating, but the developers would probably know better.

I also see some other bugs, e.g. sometimes I would not be able to open new applications, because the screen cannot be connected. These also may be related... But they go away with a simple server restart, and I did not bother.
