### ISSUE TITLE
Windows TigerVNC server crashes with noVNC viewer (shared flag issue)

### ISSUE THREAD

**Issue by sebLopezCot** [TigerVNC/tigervnc#468]
I am trying to view TigerVNC for Windows via the noVNC client. The two are able to get through exchanging protocol versions, authenticating via the standard VNC method, but when it reaches ClientInitialisation, TigerVNC closes the socket connection after noVNC sends the shared-flag of 0 or 1. 

I'm running TigerVNC v 1.8. Any help with this?

**Comment by CendioOssman** [comment]
Are you getting a crash or a disconnect? I.e. is winvnc still running afterwards?

**Comment by CendioOssman** [comment]
No response. Closing.
