### ISSUE TITLE
Error while rebuilding tigervnc 1.7.1 src.rpm for rhel6

### ISSUE THREAD

**Issue by rahravee** [TigerVNC/tigervnc#469]
Hi,

I tried to rebuild tigervnc source RPM for RHEL6 to add some packages to Requires section.
I downloaded the source RPM form below link:
https://bintray.com/artifact/download/tigervnc/stable/el6/SRPMS/tigervnc-1.6.0-1.el6.src.rpm
I am facing below `issue:`.
`
patching file configure.ac
Hunk #1 succeeded at 65 with fuzz 2 (offset -9 lines).
Hunk #2 succeeded at 1516 (offset -280 lines).
Hunk #3 succeeded at 1558 with fuzz 2 (offset -277 lines).
Hunk #4 FAILED at 2066.
Hunk #5 succeeded at 2266 (offset -340 lines).
1 out of 5 hunks FAILED -- saving rejects to file configure.ac.rej
patching file hw/Makefile.am
Hunk #1 FAILED at 38.
1 out of 1 hunk FAILED -- saving rejects to file hw/Makefile.am.rej
patching file mi/miinitext.c
Hunk #1 succeeded at 264 with fuzz 2 (offset 153 lines).
Hunk #2 FAILED at 239.
1 out of 2 hunks FAILED -- saving rejects to file mi/miinitext.c.rej
patching file os/WaitFor.c
Hunk #1 succeeded at 126 with fuzz 2 (offset 1 line).
Hunk #2 succeeded at 154 (offset 1 line).
Hunk #3 FAILED at 216.
Hunk #4 FAILED at 227.
2 out of 4 hunks FAILED -- saving rejects to file os/WaitFor.c.rej
error: Bad exit status from /var/tmp/rpm-tmp.71SteI (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.71SteI (%prep)
`
 

Could you please help me on this.

**Comment by CendioOssman** [comment]
That is a very old version and most likely out of date. Please use the current 1.8.0 release.

**Comment by rahravee** [comment]
Hi,

Sorry that we are managing an environment for some users and we need that correct version for them.
Could you please help me to solve why the src RPM is not getting build

Regards,
Rahul

**Comment by rahravee** [comment]
Hi ,

While running vncserver command the session is not getting initialized.
This is due to some downgraded package.
We need to edit the spec with below package versions.
libXfont.x86_64 0:1.5.1-2.el6  pixman.i686 0:0.32.8-1.el6  pixman.x86_64 0:0.32.8-1.el6  pixman-devel.x86_64 0:0.32.8-1.el6  libfontenc.x86_64 0:1.1.2-3.el6

Regards,
Rahul

**Comment by CendioOssman** [comment]
We don't really have the resources to also support old versions of the code. That said, I would guess that RHEL updated the version of Xorg at some point so the wrong patch is being used. Check the build where it applies the xserver patch and make sure the number matches the version provided by the system.

**Comment by rahravee** [comment]
Hi,

Thanks for the update.
I will check on this and reply back.

Regards,
Rahul

**Comment by rahravee** [comment]
Hi,

One more help...

This is the xorg details of one of our system.
[root@euca-10-254-168-7 unix]# X -version

X.Org X Server 1.17.4
Release Date: 2015-10-28
X Protocol Version 11, Revision 0
Build Operating System: x86-032 2.6.18-412.el5
Current Operating System: Linux euca-10-254-168-7 2.6.32-220.el6.x86_64 #1 SMP Wed Nov 9 08:03:13 EST 2011 x86_64
Kernel command line: ro root=/dev/vda1 console=ttyS0 initrd=/boot/initramfs-2.6.32-220.el6.x86_64.img BOOT_IMAGE=/boot/vmlinuz-2.6.32-220.el6.x86_64
Build Date: 02 November 2016  01:02:04PM
Build ID: xorg-x11-server 1.17.4-16.el6
Current version of pixman: 0.32.8
        Before reporting problems, check https://www.redhat.com/apps/support/
        to make sure that you have the latest version.
[root@euca-10-254-168-7 unix]#

Could you please check which patch we need to apply for this.

Regards,
Rahul
