### ISSUE TITLE
Can't resize remote desktop

### ISSUE THREAD

**Issue by AGCYohann** [TigerVNC/tigervnc#471]
Hello

I'm using TigerVNC viewer v1.8.0 to remotely control the office computers. I'm having an issue with the parameter -RemoteResize. If i'm correct it should resize the remote desktop to fit in the client session. My resolution is bigger than the remote desktop. So when I use my client window full screen im having black borders around the displaying of the remote desktop.

Is there a parameter to zoom the remote desktop so that it fits my local client window ?

I know that the -RemoteResize parameter doesn't work with all the VNC servers. Does someone know what version is best for the parameter to work ?

Regards

**Comment by CendioOssman** [comment]
I'm not sure it's implemented in anything but our Xvnc/vncserver. Perhaps TurboVNC's server as well as he tends to keep an eye on what we're doing.

What server are you running?

And no, there is no zoom function right now.

**Comment by bphinz** [comment]
On Thu, Jun 8, 2017 at 9:39 AM, AGCYohann <notifications@github.com> wrote:

> Hello
>
> I'm using TigerVNC viewer v1.8.0 to remotely control the office computers.
> I'm having an issue with the parameter -RemoteResize. If i'm correct it
> should resize the remote desktop to fit in the client session. My
> resolution is bigger than the remote desktop. So when I use my client
> window full screen im having black borders around the displaying of the
> remote desktop.
>
> Is there a parameter to zoom the remote desktop so that it fits my local
> client window ?
>
The TigerVNC java client can scale without resizing the remote session.
You can scale by a fixed percentage, fixed aspect ratio, or auto scale to
the current window size.

**Comment by AGCYohann** [comment]
I have to use TightVNC server.

Are you planning or adding this feature in the future ?

**Comment by CendioOssman** [comment]
At some point. We have issue #274 to track this.
