### ISSUE TITLE
xvnc crashes as soon as text is in the selection and/or copy buffer

### ISSUE THREAD

**Issue by mhellwig** [TigerVNC/tigervnc#473]
I am using xrdp to connect to a Fedora Desktop VM. Xrdp apparently internally uses Xvnc to create the actual content and on Fedora, this Xvnc is provided by the tigervnc-server-minimal package.

Behaviour when tigervnc 1.7.0-3.fc25 is installed: I can select text and/or lock the screen, nothing bad happens.

Behaviour when tigervnc 1.8.0-1.fc25 is installed: as soon as text appears either in the selection or copy buffer (not sure which is the culprit or whether it's both), also when this doesn't happen by using the mouse to select something but e.g. using pwsafe (which places strings into both buffers), a disconnect happens. I can then reconnect to the same session again via xrdp, but it is kindof annoying to to be able to copy&paste ...
Also, the same thing happens when clicking the "lock screen" button offered by gnome inside the vnc connection. Also -> immediate disconnect, happens on 1.8, doesn't happen on 1.7

For now, I've downgraded to 1.7 and this solves the problem completely.

**Comment by CendioOssman** [comment]
Do you have some logs to share?

Does this happen if you connect a regular VNC client?

We need to determine if this is a bug in TigerVNC, or Xrdp.

**Comment by mhellwig** [comment]
sorry for the delay, was in bed sick. Will report back in a few days.

**Comment by fwelland** [comment]
Have same issue.    

Distro  is F24:  4.11.5-100.fc24.x86_64

I did a dnf downgrade on all tigervnc related packages, and the problem goes away.   Currently using: 
tigervnc-1.6.0-6.fc24.x86_64
tigervnc-icons-1.6.0-6.fc24.noarch
tigervnc-server-1.6.0-6.fc24.x86_64
tigervnc-license-1.6.0-6.fc24.noarch
tigervnc-server-minimal-1.6.0-6.fc24.x86_64

**Comment by shoemael** [comment]
Looks like there is a fix for this in xrdp:

https://github.com/neutrinolabs/xrdp/issues/755

**Comment by CendioOssman** [comment]
Great. I'll close this issue here then.
