### ISSUE TITLE
VNC service timeout

### ISSUE THREAD

**Issue by ssackett** [TigerVNC/tigervnc#476]
I am running TigerVNC on RHEL 7.3.  About once a day the VNC service quits and this results in my Gnome session exiting and leaving orphaned processes.  This occurs about the same time every day so it makes me think that in some way VNC or RHEL is setting a timeout.  After this occurs I find that the VNC service is no longer running.

The start of the VNC service is somewhat abnormal in that the service is enabled to start automatically when the system boots (systemctl enable vncserver@:1.service) and though this results in Xvnc starting on port 5901, none-the-less systemctl reports a failure to start the service (ie. "systemctl status vncserver@:1.service"  reports an error).

I suspect that if a timeout is occurring it is because of the abnormal startup of the VNC service and that RHEL is waiting for something to happen and eventually gives up.  

All theories aside if anyone knows what's causing this problem and how to fix it please let me know.

Thanks,
Steve

BTW: I have tried to configure VNC to do a normal startup but there is some sort of bug preventing it.  I have found mentions of this particular bug that go back years and yet in the intervening time it has not been fixed.  Basically it has to do with a port that "is not yet readable" or something of that sort and is traceable to a set of files located in the .vnc directory that contain port numbers organized by display number.   I can provide more info if necessary but the only way I have been able to get the VNC service to run is through relying on Xvnc to start on port 5901 even though the formal launch of the service is reported as having failed.

**Comment by CendioOssman** [comment]
There should be no such timeouts. What error are you getting?

Could you show us the output of `sudo journalctl -u vncserver@:1.service`?

**Comment by CendioOssman** [comment]
No response. Closing.
