### ISSUE TITLE
FullScreen doesn't work in 1.8.0

### ISSUE THREAD

**Issue by rpolasek** [TigerVNC/tigervnc#477]
hi, using vino-3.22 as a server in gentoo with 2 lcds (2944 x 1280) and fullscreen stopped working in version 1.8.0. i have only 1 lcd at home (1920x1200) and i can see only the 1st lcd from a remote. when i upgraded back to version tigervnc-1.7.1-r2 it is working again w/o any changes.

**Comment by CendioOssman** [comment]
In other words the bump scrolling doesn't work?

Could you run vncviewer with the arguments `-Log *:stderr:100` and paste the output here after seeing the issue?

**Comment by rpolasek** [comment]
- yes bump scrolling doesn't work
- i can test it today later (at about 19:00 cet) as i'm at work now

**Comment by rpolasek** [comment]
any news?

**Comment by CendioOssman** [comment]
I'm afraid I probably can't look at this until next week.

**Comment by rpolasek** [comment]
no problem i appreciate every your help

**Comment by CendioOssman** [comment]
Ah, right. This was already discovered and fixed in e8d25d83463805c0f6ef623dba2ac9a276df3587. Unfortunately that was after 1.8.0 was released. It will be in the next release though. Until then please use an older version, `master` or 1.8.0 with that fix applied manually.

**Comment by rpolasek** [comment]
thanks, i'm going to test your patch today in the evening

**Comment by rpolasek** [comment]
it works like a charm :-)

**Comment by CendioOssman** [comment]
Glad to hear it. :)
