### ISSUE TITLE
Please add a separate installer for VNC Server.

### ISSUE THREAD

**Issue by legionpheonix** [TigerVNC/tigervnc#478]
Please add a separate installer for VNC Server. Add a sample option when installing: VNC Server Desktop or VNC Server Service.
In the settings, add the option to hide the value from the system tray.

**Comment by CendioOssman** [comment]
The installer already has the option if you wish to install the system service or not. There is also the option `ShowTrayIcon` to hide the tray icon.

So I'm not sure what you are asking for that we don't already provide?

**Comment by legionpheonix** [comment]
Destination location:
      C:\Program Files\TigerVNC

Start Menu folder:
      TigerVNC 64-bit

Additional tasks:
      Server configuration:
         Register new TigerVNC Server as a system service
         Start or restart TigerVNC service

This is a standard type of installation, there is no option to remove the icon in the tray.
Also, the installer does not offer a choice of installation.

**Comment by CendioOssman** [comment]
Well, you just listed the choice there under "Additional tasks".

Removing the tray icon is done after installation in the server config.
