### ISSUE TITLE
crashes instantly with message "terminated"

### ISSUE THREAD

**Issue by tchey290** [TigerVNC/tigervnc#479]
I am running Centos 7 and have Xfce desktop installed.
When I run "vncserver" this is what happens:

`You will require a password to access your desktops.
Password:Terminated`

After that if i try to type something it will give me this error:

`getpassword error: Input/output error`

So it asks to set the password as normal but within 1 or 2 seconds before I can type anything it will say terminated. I've been able to get past this by quickly pasting a password in. But even then it will still say terminated right after runningr vncserver. The server appears to still be running but when connecting it's just a black screen.

Software version: tigervnc-server-1.3.1-9.el7.x86_64

**Comment by tchey290** [comment]
This is also the log after starting it:

_XSERVTransSocketOpenCOTSServer: Unable to open socket for inet6
_XSERVTransOpen: transport open failed for inet6/server:1
_XSERVTransMakeAllCOTSServerListeners: failed to open listener for inet6

Xvnc TigerVNC 1.3.1 - built Nov 16 2016 13:38:44
Copyright (C) 1999-2011 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11702000, The X.Org Foundation


Sat Jun 24 22:43:16 2017
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0

**Comment by CendioOssman** [comment]
It looks like something is screwy with your terminal. How are you starting `vncserver`? No `&` or other redirections?

You can also run `vncpasswd` manually first to bootstrap the password file.

That version is also very old. Please test the latest version of TigerVNC.

**Comment by CendioOssman** [comment]
No response. Closing.
