### ISSUE TITLE
Handling Windows 10 with TigerVNC

### ISSUE THREAD

**Issue by pedro7** [TigerVNC/tigervnc#480]
The documentation should have some tips regarding Windows 10 high DPI scaling borking the expected resolution client-side.

Example:
The client is running Windows 10 at 1920x1080 (build 15063, Creators Update).
The server is running Gentoo Linux/Gnome at 1920x1080.

I was expecting that when running the client full screen the remote desktop would fit on the screen.
However the remote screen would be too big for my local screen.

The solution was disabling, for the TigerVNC viewer, "high DPI scaling behaviour" setting it as "Scaling performed by: Application".

![system-enhanced-scaling-option-windows10](https://user-images.githubusercontent.com/220099/27515274-629a41e2-5997-11e7-9275-fd6acd8ecd49.jpg)
[Credits for the pic](https://www.windowscentral.com/how-improve-app-dpi-scaling-enabling-system-enhanced-feature-windows-10).

This fixed this issue which I was experiencing since my first tests with Windows 10. 

P.S.: for some reason I also had to add to the shortcut DotWhenNoCursor=1.

**Comment by CendioOssman** [comment]
Generally you want to have a scaled session as otherwise it would be difficult to see the screen elements. However we have issue #369 for more improvements.
