### ISSUE TITLE
TLSVnc Authentication with Shared Option

### ISSUE THREAD

**Issue by lokebl** [TigerVNC/tigervnc#482]
Hi,

We are using Security Option TLSVnc and we are able to connect only 1 session at a time , If we use VNCAuth we are able to connect morethan 3 connection at a time.

Shared access is working for VNCAuth Option but its not working for  TLSVnc Security Option.

Please help.

**Configuration**

Section "Screen"
        Identifier "Screen0"                                    
        DefaultDepth 16                                           
        Option "SecurityTypes" "TLSVnc"                     
        Option "UserPasswdVerifier" "VncAuth"                 
        Option "PasswordFile" "/etc/vnc-server-ext/vncpasswd"             
        Option "IdleTimeout" "900"                             
EndSection

Regards,
Lokesh K

**Comment by CendioOssman** [comment]
I'm afraid I'm unable to reproduce any issue. Have you made sure the clients are configured to share sessions?

What version are you using on the server? And on the client?

Could you share the log files from the server?

**Comment by CendioOssman** [comment]
No response. Closing.
