### ISSUE TITLE
Feat. request horizontal scrolling

### ISSUE THREAD

**Issue by absnc** [TigerVNC/tigervnc#483]
Hi, 

First of all, thanks for this beautiful software; by far fastest and most stable I found
out there.

I have some laptops equiped with Pointstick / Pointing stick navigation.
They allow me horizontal navigation, when page content is too wide, by pressing
middle button plus pointing left/right.

Does anyone know about the easiest way to make this work?
should I look somewhere in `unix/xserver/hw/vnc/Input.c` ?

Vertical scrolling do seem to work out of the box right now, though horizontal
gives several blinks, in place of a continuous signal, when in a terminal.

**Comment by CendioOssman** [comment]
That scrolling is usually handled by the application, not the operating system. Are you sure the applications in you session have this feature?

**Comment by absnc** [comment]
Both host and target are running Ubuntu.
The apps I'm using inside TigerVNC are mostly common, chromium-browser, terminator.

Ok, I got more informations going on now,
Here is the output I'm getting from a standard Unix session using xev; these are the events I'm
getting for Left and Right pointstick scrolling:

```
ButtonRelease event, serial 37, synthetic NO, window 0x7400001,
    root 0x2ca, subw 0x0, time 111046733, (79,141), root:(1251,861),
    state 0x10, button 6, same_screen YES

ButtonPress event, serial 37, synthetic NO, window 0x7400001,
    root 0x2ca, subw 0x0, time 111047277, (79,141), root:(1251,861),
    state 0x10, button 7, same_screen YES
```

as opposed to getting this one right here in my VNC sessions:

```
ButtonRelease event, serial 33, synthetic NO, window 0x3600001,
    root 0x4f, subw 0x0, time 902031557, (109,77), root:(734,435),
    state 0x100, button 1, same_screen YES
```

**Comment by CendioOssman** [comment]
Alright, if you are getting button events locally then they should be sent to the server as well.

What version of TigerVNC are you running on the server and client? Where did you get the builds?

**Comment by absnc** [comment]
Both were taken under Github latest release

* Client side is running under Ubuntu 16.04.2 LTS :
```
VncViewer-1.8.0.jar
```

* Server side, I have 14.04.5
```
Xvnc TigerVNC 1.8.0 - built May 16 2017 14:01:59
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11400000, The X.Org Foundation
```

Thanks for acknowledging. Hope I could be of any help if needed

**Comment by CendioOssman** [comment]
Could you test the native viewer?

@bphinz, does the Java viewer support horizontal scroll wheels?

**Comment by absnc** [comment]
Sure I'll do that.
I guess I missed the download link for the binary version at first.

**Comment by absnc** [comment]
Ok, it's working perfectly while using the ```vncviewer``` executable from the server/client bundle

Looks like there is a slight gain in terms of fluidity, as well.

Then, I was probably looking after a client only archive.

Thanks for you help, now my environment is flawless.
