### ISSUE TITLE
Client difference between Linux and Windows?

### ISSUE THREAD

**Issue by jmadams1** [TigerVNC/tigervnc#487]
I have tigervnc server (1.7 or 1.8) on various Ubuntu Mate 16.04 servers.
When using tigervnc viewer (1.7 or 1.8) on Ubuntu Mate 16.04 connecting to any of the Ubuntu Mate 16.04 servers, the mouse pointer doesn't change based on the context - primarily, when going to the lower right hand corner of a window to resize (it should change to the resize pointer.)  When connecting with the tigervnc windows client (only tried 1.7) the pointer icon does change based on context and works like expected.

I've been able to reproduce with a clean and updated version of Ubuntu Mate 16.04.

Is this pointer context change just not supported in Linux based clients?

Thank you!

**Comment by CendioOssman** [comment]
It is supported on all platforms. Historically this problem has been the result of a broken build where FLTK doesn't handle cursors properly. Where did you get your build?

**Comment by jmadams1** [comment]
I've been following this link from the release page:

Binaries are available from bintray:

https://bintray.com/tigervnc/stable/tigervnc/1.8.0

And specifically for the 1.8 release:

https://bintray.com/tigervnc/stable/tigervnc/1.8.0#files/ubuntu-16.04LTS%2Famd64

Thank you for your response.
John

**Comment by CendioOssman** [comment]
I had a look and I'm afraid FLTK in Ubuntu 16.04 is built without cursor support, so I'm afraid I'm going to have to ask you to file a bug with them.
