### ISSUE TITLE
tigervnc on armboard linux eg armbian, raspbian or dietpi

### ISSUE THREAD

**Issue by blub4747** [TigerVNC/tigervnc#492]
Hi guys,

I would like to run tigervnc on my raspberry and don't really know which package to pick.
Do I need to compile the server from scratch ?
like with ./configure make etc?

Thx, for the help in advance.

blub4747

**Comment by CendioOssman** [comment]
I'm afraid we do not have any builds for that platform, so you'll have to do it yourself. Please look at `BUILDING.txt` for details.
