### ISSUE TITLE
Unable to select text to cut or copy in vncclinent running on Centos 7

### ISSUE THREAD

**Issue by dseltz** [TigerVNC/tigervnc#495]
Hi,
  I'm unable to select text in the vncclient so that I can cut or copy.  I'm running Centos 7.  I'm using TigerVNC Client 1.3.1.
In the title bar of the screen I'm able to right click and bring up the menu (maximize, minimize, move, resize, etc.)
But in the main part of the window the mouse does not seem to do anything.  Cannot highlight text.  right clicking or left clicking does not seem to do anything.

Any suggestions?

**Comment by dseltz** [comment]
A bit more information.  Here is the information on the screen when I start vncviewer:

dseltz@localhost ~]$ vncviewer :5900

TigerVNC Viewer 64-bit v1.3.1 (20161116)
Built on Nov 16 2016 at 13:37:43
Copyright (C) 1999-2011 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Sun Aug 13 23:47:58 2017
 CConn:       connected to host localhost port 5900
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 PlatformPixelBuffer: Using default colormap and visual, TrueColor, depth 24.
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Using hextile encoding
 DesktopWindow: Failure grabbing keyboard
 DesktopWindow: Failure grabbing mouse

**Comment by CendioOssman** [comment]
That's a very old version of TigerVNC. Could you try something more recent?

Does it work with other clients?

**Comment by dseltz** [comment]
I updated to version 1.8 and have the same problem.

**Comment by CendioOssman** [comment]
Are you still getting the errors about grabbing keyboard and mouse?

What VNC server are you using?

**Comment by CendioOssman** [comment]
No response. Closing.
