### ISSUE TITLE
Please make PointerEventInterval for Mac client something other than 0

### ISSUE THREAD

**Issue by jperschb** [TigerVNC/tigervnc#498]
When PointerEventInterval on Mac client is set to 0 there is a huge lag between the client mouse pointer and the application cursor that one of our CAD tools creates.  

When set to anything other than 0 the lag is imperceptible.

As this option seems to have been deprecated (was only command line, and now is not even command line), could the default behavior be 17ms?  

Thanks!
jgp

**Comment by jperschb** [comment]
This is resolved and bounty is waiting for denim2x to claim.

Thanks,
jgp

**Comment by denim2x** [comment]
@jperschb Thanks; I'll be able to claim as soon as this issue is closed.

**Comment by jperschb** [comment]
Thanks.  Closing issues.
