### ISSUE TITLE
Scale local view of remote session to the local window size

### ISSUE THREAD

**Issue by fnJeff** [TigerVNC/tigervnc#501]
I've done my best to find an existing answer to this and came up empty so far.

I'm sure the feature that auto scales the remote session to the size of the local window is useful for some, but unfortunately it doesn't work well for what I need to do.

Essentially I setup my desktops in a session in a very particular arrangement that facilitates the way I work.  The issue is when I do that at work (where I have a 2560x1440 monitor) and then try and open the session when working from home (where I have a 1600x1200 monitor).  Previously we used ETX and that was able to scale the remote session locally (not on the server) to fit it whatever window size I had, with the option to lock the aspect ratio.  We have now switched to using TigerVNC.

This is essentially a local viewer scaling of the remote session.  I'm hoping there is some way to do this with TigerVNC viewer that I haven't yet found.

Your help is greatly appreciated.

**Comment by CendioOssman** [comment]
Scaling is not supported unfortunately. We track this feature request under #274.

**Comment by fnJeff** [comment]
Apologies if I'm incorrect, but wouldn't this be considered a different feature than what is described in #274?  As I understood it that issue was with scaling the remote session size to match the local window size.   My issue was with local scaling of the client, without changing the remote session size.

Do you still considerate it a duplicate issue?  Or maybe I'm missing something in the other thread.

Thanks.

**Comment by CendioOssman** [comment]
There were some confusion in the start of the other thread, but in the end it is about scaling in the client. Scaling the actual session size is already implemented in TigerVNC. :)

**Comment by fnJeff** [comment]
Ah yes, I was confused as well.  Re-re-reading it again, I do see what you meant.  Thanks for your patience, and sorry for the duplicate!
