### ISSUE TITLE
AddNewClient not working from the command line

### ISSUE THREAD

**Issue by niterain** [TigerVNC/tigervnc#502]
version 1.8.0
On Windows 10

Connecting to the reflector works if you use the AddNewClientDialog, but trying to connect using

winvnc4.exe -connect
winvnc4.exe -connect 127.0.0.1::5510:ID:reflectorid234234234234

It doesn't look like the server even receives the message.

**Comment by niterain** [comment]
I think it might be a problem with Finding the Tray.  I just ran winvnc4.exe -connect from a different terminal window, and the AddNewClient dialog now appears.  However, still not seeing an indication it has reached the server, but now the two version opens up a console and one opens up a dialog, since the AddNewClient Dialog works when clicking the option from the tray.

**Comment by CendioOssman** [comment]
I think this is an authorization thing. The tray runs as SYSTEM, the same as winvnc4.exe. If you start it by hand then you'll run it as your user.

We need to re-design things so that the server and the user interfaces are able to run as separate users.
