### ISSUE TITLE
No screen updates

### ISSUE THREAD

**Issue by frispete** [TigerVNC/tigervnc#503]
Hi,

I'm having a hard time to setup Xvnc 1.8.0 on certain openSUSE Leap 42.3 systems.
The problems appear on systems with different GPUs, and with Xvnc 1.6.0, as well as with 1.8.0. 
When accessing those systems with vncviewer or krdc during sddm login, the vnc display keeps black, but keystrokes are working (e.g. I can enter the password, but cannot see the screen). When I push enter, I can see the login screen correctly for a second, then parts of the initial view are shown, including a progress display. Before the desktop appears, the vnc display stops updating again, and shows a little distortion (parts of the screen are repeated with a horizontal and vertical offset):
![grafik](https://user-images.githubusercontent.com/1009685/29947728-749cf5e4-8eab-11e7-850f-51b11d34e490.png)

I've tried many combinations of options in the vnc module:
```
Section "Module"
    Load "vnc"
EndSection

Section "Screen"
    Identifier "Screen0"
    Option "SecurityTypes" "TLSVnc"
    Option "PasswordFile" "/root/.vnc/passwd"
    #Option "DeferUpdate" "0"
    #Option "Protocol3.3" "on"
    #Option "CompareFB" "off"
    #Option "ImprovedHextile" "off"
    #Option "Log" "*:syslog:100"
EndSection
```
but the problem persists. Syslog and Xorg.0.log are sane (no problems are logged).

The problem doesn't appear in a VirtualBox installation, nor on an older system with 1.8.0, and doesn't depend on a certain kernel (42.3 uses a heavily patched 4.4.79 kernel), but I've tried a 4.11.11 with the same result.

VNC with x11vnc is not affected (but has its own share of problems of course...).

XOrg is 7.6, Xserver is 1.18.3. 

Affected systems:
- HP 250 G5 SP X0N34EA Business Notebook
- Lenovo Thinkpad E555 20DH (AMD Kaveri A8-7100, AMD Radeon R5 (Kaveri), 15.6")

It looks like VNC doesn't track any changes on the X11 screen, neither initially nor after start up. 

Any idea, what's going wrong here?

**Comment by CendioOssman** [comment]
There seems to be some confusion here. Xvnc is the stand-alone VNC server that runs independently of your local login. It is configured entirely through command line. The VNC module attaches to your normal Xorg and is configured through xorg.conf. How are you starting your VNC server?

Do you have some proprietary graphics drivers installed? What desktop environment are you using?

**Comment by frispete** [comment]
Hi Cendio,

you're right - I've been very tired last night. Hopefully I'm doing a little better now.

VNC is started by Xorg, and is configured by `/etc/X11/xorg.conf.d/10-libvnc.conf` here, as shown above.

This happened on two systems, that where using different GPUs (AMD Radeon R5 and Intel i915), but no proprietary drivers, with the KDE Plasma 5 DE.

After installing (and suffering) from this issue on another system (AMD Phenom(tm) II X4 955, NVidia GeForce 9800 GT, nouveau driver), I managed to get to the bottom of this! It depends on the compositor rendering method. Those systems allow the choice of OpenGL 3.1, OpenGL 2.0 and XRender. Anything but the latter results in the described problems. 

Hence, this boils down to: either switch of the compositor completely or avoid using any OpenGL rendering in the compositor at least. I can imagine, that this is a pesky problem for VNC.

**Comment by CendioOssman** [comment]
That scenario should work fine, so there must be some bug somewhere. Since both radeon and nouveau are affected it is most likely the bug is in Xorg or TigerVNC.

Could you test if x0vncserver works better?

When in XRender mode, do other OpenGL applications work well over VNC?

**Comment by CendioOssman** [comment]
No response.

**Comment by BenBrock** [comment]
I have the same issue running on Ubuntu 18.04.4 LTS with Nvidia proprietary drivers version 440.33.01.

Here's what my 10-vnc.conf looks like:

`Section "Module"
    Load "vnc"
EndSection

Section "Screen"
    Identifier "Screen0"
    Option "UserPasswdVerifier" "VncAuth"
    Option "PasswordFile" "/home/brock/.vnc/passwd"
EndSection`

When I log into the VNC session, the display never changes, but the clicks seem to be reflected if I log out and back in to the VNC session.  I'm using stock GDM as the login manager.  "Regular" VNC sessions created with `vncserver` (i.e. not attached to an X display) work fine.

Any recommendations on what to try?

**Comment by BenBrock** [comment]
I was able to work around this.  It seems to be caused by a bad interaction between the proprietary Nvidia drivers and GDM.  Switching to another login manager (in my case SLiM) eliminated the issue.  Graphical applications work and are hardware accelerated.

I do have another issue, which is that the VNC session goes black and becomes unresponsive if an application goes full screen.  The VNC session becomes responsive again if I kill the full screen app.  Windows applications run fine.

**Comment by CendioOssman** [comment]
Sounds like the same issue then, in that certain OpenGL applications fail to notify about updates properly. As suggested earlier, could you test x0vncserver and see if that works better? You can use both at the same time.

**Comment by BenBrock** [comment]
Weirdly, x0vncserver doesn't seem to be installed with the default Ubuntu package on 18.04.  Is there another package I need to install?

**Comment by CendioOssman** [comment]
Maybe. I'm afraid I don't know Ubuntu's packaging by heart. Note that they (and Debian) also tend to rename things to avoid conflict. So it's likely called `x0tigervncserver`.

**Comment by yankyo** [comment]
I encountered an issue that seems to be the same -- with Xorg module and Gnome shell (which uses an OpenGL composition), there are no updates (besides the copy of a portion of the buffer when e.g. a window is moved).

I've checked with `x0vncserver` and it seems to work correctly. Would it however be possible to use the Xorg module as well? Thanks!

**Comment by warrenc5** [comment]
I believe I am experiencing the same issue.. standalone tigervncserver (scraping) works 
xorg extension module vnc looks like the below - however mouse & keyboard & clipboard are working.

I am using nvidia and primus
nvidia-kernel-dkms 470.129.06-6 amd64
bumblebee      3.2.1-28
primus-nvidia  0~20150328-14

![Screenshot from 2022-08-10 08-13-33](https://user-images.githubusercontent.com/3395365/183771251-ca309b9f-c699-4731-9394-7ce0e3047aef.png)

**Comment by warrenc5** [comment]
I should also add that I am running enlightenment  0.25.3-1

I tried fiddling all the enlightenment opengl settings such as vsync/grab all/buffer swapping but nothing worked.

So I disabled the opengl composite renderer and use the software renderer and now it works.

Btw, If I run glxgears I can see that on the client.

**Comment by frispete** [comment]
FTR: with openSUSE Tumbleweed, KDE and X11 (all pretty current) I've given up on TigerVNC: 
KDE has abandoned the Xrender option, and even disabling the compositor didn't cut it. 
`x11vnc` does the job quite well for now, but the (handy) integration with the Xserver is lost...
