### ISSUE TITLE
Cut & paste only works from the VNC environment to the computer with viewer (not both ways...)

### ISSUE THREAD

**Issue by PeteKey** [TigerVNC/tigervnc#508]
Hi folks.

I have switched to tigervnc 1.8 from 1.5 and now, I cannot copy & paste from my windows machine any more ... I use it with VNC viewer (tried older and new version) ... seems not working. I wonder why copy & paste is always such a mess with VNC servers 7 clients.

Cheers,
Peter

**Comment by PeteKey** [comment]
In general, I have noticed only the tiger vincviewer 1.8 seems to be able to work okay with copy & paste. However, I use old windows xp for client so I can only launch the java vnc tiger viewer 1.8. The windows versions do not work on XP. Any suggestions (apart from update of all)?

Perhaps viewer 1.8 can be compiled on XP somehow?

**Comment by PeteKey** [comment]
Another version is downgrade to Tiger VNC server 1.7. Would that resolve copy & paste with other existing VNC viewer clients?

**Comment by PeteKey** [comment]
Actually, the copy & paste does not work even with the tiger vnc viewer 8.0 half of the time ....

**Comment by PeteKey** [comment]
Oh, I think I discovered the issue. There was this piece of program called klipper running in the background. I think it was messing up exchange between the server and client.

**Comment by CendioOssman** [comment]
Yes, klipper can unfortunately wreak havoc with the clipboard. Since you found the issue I'll close this entry.

**Comment by Pascal666** [comment]
The workaround found at https://github.com/TigerVNC/tigervnc/issues/520#issuecomment-335381310 was to disable Klipper's "Prevent empty clipboard" option.
