### ISSUE TITLE
Can't connect to MacOS Yosemite (No matching security types)

### ISSUE THREAD

**Issue by smilix** [TigerVNC/tigervnc#51]
Any ideas what Apple have done to their vnc server?

```
TigerVNC Viewer 64-bit v1.3.80
Built on: 2014-10-21 01:46
Copyright (C) 1999-2014 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Mon Oct 27 15:04:30 2014
 CConn:       connected to host 10.1.200.229 port 5900
 CConnection: Server supports RFB protocol version 3.889
 CConnection: Using RFB protocol version 3.8
 CConnection: No matching security types
 CConn:       No matching security types
```
##

**Comment by orthecreedence** [comment]
I was getting this too (windows 7 x64, tigervnc 1.4.2, osx yosemite), doing the following helped:

1. Disable "Remote Management" (if enabled)
2. Enable "Screen Sharing"
3. Set "Allow access for:" to `All users`
3. Go into "Computer Settings..."
4. _Enable_ both "Anyone may request permission..." and "VNC viewers may control screen w/ password" (set a password)

Also, connecting via IP vs hostname *may* matter (but don't quote me on that) so try using the exact hostname listed under "Other users can access your computer's screen at vnc://[hostname]/" (even if it requires a local hosts entry mapping).

Hope this helps.

**Comment by kaihendry** [comment]
Confirming the issue on MacOSX. Workaround is to set a password. https://youtu.be/gAEsz5am2A8

**Comment by yan12125** [comment]
Thanks @kaihendry setting a password works. (tested on ElCapitan with Linux clients)
