### ISSUE TITLE
Create option for enabling SNI for TLS connections

### ISSUE THREAD

**Issue by dhaavi** [TigerVNC/tigervnc#510]
It would be great to have an option to enable SNI for TLS connections.
This would enable us to build a (TLS terminating) reverse proxy for VNC, selecting the internal endpoint based on the supplied server name.
This would save us and anyone with a similar use case the hassle of opening and mapping ports all the time in a fast changing infrastructure.

I would also like to open-source this reverse proxy once it's built, but will have to check on that with my employer first.

**Comment by CendioOssman** [comment]
Should be easy enough. Does this patch work for you?

```diff
diff --git a/common/rfb/CSecurityTLS.cxx b/common/rfb/CSecurityTLS.cxx
index 8a053e3..3f13e6e 100644
--- a/common/rfb/CSecurityTLS.cxx
+++ b/common/rfb/CSecurityTLS.cxx
@@ -254,6 +254,11 @@ void CSecurityTLS::setParam()
     if (gnutls_credentials_set(session, GNUTLS_CRD_CERTIFICATE, cert_cred) != GNUTLS_E_SUCCESS)
       throw AuthFailureException("gnutls_credentials_set failed");
 
+    if (gnutls_server_name_set(session, GNUTLS_NAME_DNS,
+                               client->getServerName(),
+                               strlen(client->getServerName()) + 1) != GNUTLS_E_SUCCESS)
+      vlog.error("Failed to configure the server name for TLS handshake");
+
     vlog.debug("X509 session has been set");
   }
 }
```

**Comment by bphinz** [comment]
Interesting idea.  A few years back, I registered a pseudo encoding called ClientRedirect, which our Java viewer supports, for much the same reason.  You might be able to use that in conjunction with a new SecurityType which triggers a redirect based on SNI.  My application, for example, is a daemon that runs on each node of a cluster and listens on port 5900 and supports only a security type that requests the username.  The name is used to find the port number of that user's existing session (starting a new one if there isn't already a session) and then sends a ClientRedirect message which causes the client to reconnect seamlessly on that port (starting the RFB handshake all over again).

**Comment by dhaavi** [comment]
@CendioOssman thanks for the fast reply.
That patch worked, though I had to remove the " + 1", otherwise it failed.
I am not sure if that broke something security-wise.

@bphinz that's an interesting way to handle this, especially as it does not introduce another possible bottle-neck, because you can have a firewall do port redirection and do not have to handle this on the application layer.
For what we are doing we will just build a small reverse proxy to directly forward the traffic to its final destination. Also, we only want to expose one single service for all VNC access.

**Comment by bphinz** [comment]
@dhaavi would you mind testing this with the current TigerVNC Java client?  It looks like the server name is already being set in the SSL context similar to Pierre's patch above so it should just work.

**Comment by CendioOssman** [comment]
Great. So I've commited the change to `master`.
