### ISSUE TITLE
Make error for RPI 3B on Raspbian Jessie

### ISSUE THREAD

**Issue by Pavel-Sayekat** [TigerVNC/tigervnc#518]
After patching xserver117.patch as the matched server version
I just did
  cd tigervnc
  cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr
  make
and it gets stuck here ->
Scanning dependencies of target vncviewer
[ 82%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/menukey.cxx.o
[ 82%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/CConn.cxx.o
[ 83%] Building CXX object vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o
/../tigervnc/vncviewer/DesktopWindow.cxx: In member function ���void DesktopWindow::fullscreen_on()���:
/../tigervnc/vncviewer/DesktopWindow.cxx:725:38: error: ���fullscreen_screens��� was not declared in this scope
     fullscreen_screens(-1, -1, -1, -1);
                                      ^
/../tigervnc/vncviewer/DesktopWindow.cxx:760:48: error: ���fullscreen_screens��� was not declared in this scope
     fullscreen_screens(top, bottom, left, right);
                                                ^
vncviewer/CMakeFiles/vncviewer.dir/build.make:110: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o' failed
make[2]: *** [vncviewer/CMakeFiles/vncviewer.dir/DesktopWindow.cxx.o] Error 1
CMakeFiles/Makefile2:884: recipe for target 'vncviewer/CMakeFiles/vncviewer.dir/all' failed
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CendioOssman** [comment]
That looks like your version of FLTK is simply too old. What version are you using?

**Comment by Pavel-Sayekat** [comment]
$ sudo dpkg -l libfltk1.3-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                Version                Architecture           Description
+++-===================================-======================-======================-============================================================================
ii  libfltk1.3-dev                      1.3.2-6                armhf                  Fast Light Toolkit - development files

**Comment by CendioOssman** [comment]
I'm afraid that is too old. 1.3.3 is the minimum required version.
