### ISSUE TITLE
Mouse/Keyboard trapped after opening a single full-screen vnc window in multi-monitor setting

### ISSUE THREAD

**Issue by dchneric** [TigerVNC/tigervnc#519]
This happens on my DebianJessie. Just manually built VNCViewer from master today.

The setting is similar to #447. #447 is fixed in master but this one can still be reproduced by the following steps:

1) I have two monitors. Start vncviewer full-screen in Monitor1
2) In Monitor2, type something in chrome browser, or a konsole window. It works.
3) In Monitor2, minimize and then restore the chrome window (or konsole window, without touching the vnc window). Typing on the keyboard doesn't work any more. Right-clicking on some of the application (or desktop) doesn't work. I.e. the existence of a full-screen vnc window on one monitor interferes with other applications on other monitor.
4) Click on full-screened vncviewer window in Monitor1, and go back to Monitor2. This issue is gone.

I can also verify that if vncviewer is not in full-screen mode, this issue won't happen.

**Comment by CendioOssman** [comment]
I can reproduce the issue here. I'll have a look.

**Comment by CendioOssman** [comment]
Fixed in 841e9f32d5952d6f16f67294c2da8bf395066a9b.
