### ISSUE TITLE
Compile on Windows10?

### ISSUE THREAD

**Issue by howknows** [TigerVNC/tigervnc#524]
It has lots of problems when I compiling this project on windows10 & MingW. What is the right way to compiling on windows10?

**Comment by CendioOssman** [comment]
Hopefully the instructions in `BUILDING.txt` should be correct. We however build with mingw on Linux, so we rarely test things on Windows.

What problems are you seeing?

**Comment by niterain** [comment]
Yeah, let us know the exact error messages you are getting.  I am compiling fine on Windows 10 x64 without a problem.

**Comment by howknows** [comment]
When execute make ,it's output like this:

`Scanning dependencies of target os
[  1%] Building CXX object common/os/CMakeFiles/os.dir/Mutex.cxx.obj
[  1%] Building CXX object common/os/CMakeFiles/os.dir/Thread.cxx.obj
[  2%] Building C object common/os/CMakeFiles/os.dir/w32tiger.c.obj
[  2%] Building CXX object common/os/CMakeFiles/os.dir/os.cxx.obj
c:/Users/TuringSec002/Desktop/horse/tigervnc/common/os/os.cxx: In function 'int getvnchomedir(char**)':
c:/Users/TuringSec002/Desktop/horse/tigervnc/common/os/os.cxx:77:62: error: 'SHGetSpecialFolderPath' was not declared in this scope
  ret = SHGetSpecialFolderPath(NULL, dir, CSIDL_APPDATA, FALSE);
                                                              ^
common/os/CMakeFiles/os.dir/build.make:138: recipe for target 'common/os/CMakeFiles/os.dir/os.cxx.obj' failed
mingw32-make[2]: *** [common/os/CMakeFiles/os.dir/os.cxx.obj] Error 1
CMakeFiles/Makefile2:182: recipe for target 'common/os/CMakeFiles/os.dir/all' failed
mingw32-make[1]: *** [common/os/CMakeFiles/os.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
mingw32-make: *** [all] Error 2`

**Comment by CendioOssman** [comment]
Looks like something is missing from your mingw headers.

Could it be an old version?

Are you using "normal" mingw or mingw-w64?

**Comment by howknows** [comment]
And when I compiling on Ubuntu 16.04, also has some problems.
And I install MingW used this command : `apt install mingw-w64-i686-dev gcc-mingw-w64-i686 g++-mingw-w64-i686`
`
root@hh:~/vnc/tigervnc/build# CC=/usr/bin/i686-w64-mingw32-gcc CXX=/usr/bin/i686-w64-mingw32-g++ RC=/usr/bin/i686-w64-mingw32-windres cmake -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_AR=/usr/bin/i686-w64-mingw32-ar -DCMAKE_RANLIB=/usr/bin/i686-w64-mingw32-ranlib .. 
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/i686-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/i686-w64-mingw32-g++
-- Check for working CXX compiler: /usr/bin/i686-w64-mingw32-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE = Release
-- VERSION = 1.8.80
-- BUILD_TIMESTAMP = 2017-10-17 15:54
-- 32-bit build
-- Performing Test HAVE_ACTIVE_DESKTOP_H
-- Performing Test HAVE_ACTIVE_DESKTOP_H - Success
-- Performing Test HAVE_ACTIVE_DESKTOP_L
-- Performing Test HAVE_ACTIVE_DESKTOP_L - Success
-- Found ZLIB: /usr/local/lib/libz.a (found version "1.2.11") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.7") 
CMake Warning at CMakeLists.txt:173 (message):
  Gettext NOT found.  Native Language Support disabled.


-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Performing Test FOUND_LIBJPEG_TURBO
-- Performing Test FOUND_LIBJPEG_TURBO - Failed
-- WARNING: You are not using libjpeg-turbo. Performance will suffer.
-- Found FLTK: fltk_images;fltk  
-- Found GnuTLS: /usr/lib/x86_64-linux-gnu/libgnutls.so.30  
-- Looking for include file security/pam_appl.h
-- Looking for include file security/pam_appl.h - not found
-- Looking for pam_start
-- Looking for pam_start - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /root/vnc/tigervnc/build

`
It seems good ,but when I execute make ,I looks like 

`
root@hh:~/vnc/tigervnc/build# make
Scanning dependencies of target os
[  1%] Building CXX object common/os/CMakeFiles/os.dir/Mutex.cxx.obj
In file included from /usr/include/sys/select.h:45:0,
                 from /usr/include/sys/types.h:219,
                 from /usr/include/stdlib.h:314,
                 from /usr/share/mingw-w64/include/combaseapi.h:129,
                 from /usr/share/mingw-w64/include/objbase.h:14,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /root/vnc/tigervnc/common/os/Mutex.cxx:20:
/usr/include/bits/time.h:30:8: error: redefinition of ‘struct timeval’
 struct timeval
        ^
In file included from /usr/share/mingw-w64/include/winsock.h:32:0,
                 from /usr/share/mingw-w64/include/windows.h:92,
                 from /root/vnc/tigervnc/common/os/Mutex.cxx:20:
/usr/share/mingw-w64/include/_timeval.h:10:8: error: previous definition of ‘struct timeval’
 struct timeval
        ^
In file included from /usr/include/sys/types.h:219:0,
                 from /usr/include/stdlib.h:314,
                 from /usr/share/mingw-w64/include/combaseapi.h:129,
                 from /usr/share/mingw-w64/include/objbase.h:14,
                 from /usr/share/mingw-w64/include/ole2.h:17,
                 from /usr/share/mingw-w64/include/wtypes.h:12,
                 from /usr/share/mingw-w64/include/winscard.h:10,
                 from /usr/share/mingw-w64/include/windows.h:97,
                 from /root/vnc/tigervnc/common/os/Mutex.cxx:20:
/usr/include/sys/select.h:75:5: error: conflicting declaration ‘typedef struct fd_set fd_set’
   } fd_set;
     ^
In file included from /usr/share/mingw-w64/include/winsock.h:36:0,
                 from /usr/share/mingw-w64/include/windows.h:92,
                 from /root/vnc/tigervnc/common/os/Mutex.cxx:20:
/usr/share/mingw-w64/include/psdk_inc/_fd_types.h:25:3: note: previous declaration as ‘typedef struct fd_set fd_set’
 } fd_set;
   ^
In file included from /usr/share/mingw-w64/include/windows.h:114:0,
                 from /root/vnc/tigervnc/common/os/Mutex.cxx:20:
/usr/share/mingw-w64/include/stralign.h: In function ‘WCHAR* ua_wcscpy(PUWSTR, PCUWSTR)’:
/usr/share/mingw-w64/include/stralign.h:37:102: error: ‘wcscpy’ was not declared in this scope
   __CRT_INLINE PUWSTR ua_wcscpy(PUWSTR Destination,PCUWSTR Source) { return wcscpy(Destination,Source); }
                                                                                                      ^
common/os/CMakeFiles/os.dir/build.make:63: recipe for target 'common/os/CMakeFiles/os.dir/Mutex.cxx.obj' failed
make[2]: *** [common/os/CMakeFiles/os.dir/Mutex.cxx.obj] Error 1
CMakeFiles/Makefile2:182: recipe for target 'common/os/CMakeFiles/os.dir/all' failed
make[1]: *** [common/os/CMakeFiles/os.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

`

**Comment by howknows** [comment]
@CendioOssman I use "MinGW Installation Manager" installed mingw32-gcc mingw32-g++ etc. And the download link is https://sourceforge.net/projects/mingw/files/latest/download?source=files 
It should be the newest MinGW .

**Comment by CendioOssman** [comment]
The Ubuntu error is a different one. You aren't setting up your environment correctly.

Unfortunately it is  a bit complex to set up cross compilation with CMake, but they seem to have a guide here:

https://www.vtk.org/Wiki/CmakeMingw#How_to_use_MinGW_to_cross_compile_software_for_Windows

Give that a try and see how it goes.

**Comment by CendioOssman** [comment]
Assuming it got resolved. Closing.

**Comment by FlySkyBear** [comment]
add #define _WIN32_IE 0x1100   in the build/config.h
