### ISSUE TITLE
A VNC server is already running as :1   New '... :2' desktop is ... :2

### ISSUE THREAD

**Issue by mastermark007** [TigerVNC/tigervnc#531]
A VNC server is already running! What can I do to prevent switching to the next free display number?
If I assign different users a fixed display, then the unique assignment no longer works. By the way, it would be better to force the desired displays. Is there a solution?

**Comment by CendioOssman** [comment]
How are you starting the server? The standard behaviour is to stop if an explicit display is specified and it is already used.

**Comment by mastermark007** [comment]
Well, for me alone it would work. However, if the server is used for multi-user operation and each user is assigned to a specific display, then the automatic switch can lead to confusion: one does not reach the screen anymore because the number has changed and the other one can No longer use his display number etc. 
As an administrator, a lot of maintenance is required for proper operation. In previous versions, this automatic change was not given – as far as I can remember.

**Comment by CendioOssman** [comment]
My point is that there shouldn't be an automatic switch. So we need to figure out what is going wrong on your system.

**Comment by mastermark007** [comment]
Hello,
The OS is the current CentOS 7.4. 
For me, it looks like a response from the VNC server.
See:
# vncserver :1
A VNC server is already running as :1
New 'xyz:2 (master)' desktop is xyz:2
Starting applications specified in /home/master/.vnc/xstartup
Log file is /home/master/.vnc/xyz:2.log

**Comment by mastermark007** [comment]
Found the reason in file "vncserver":
By commenting out the line 168 "$displayNumber = &GetDisplayNumber();", the expected behavior was shown.
Best wishes!

**Comment by CendioOssman** [comment]
Ah. This is a Red Hat modification and not how things should behave. So I'm afraid you'll have to file a bug with them.
