### ISSUE TITLE
vncviewer does not support -display argument, even though man page says so

### ISSUE THREAD

**Issue by astrand** [TigerVNC/tigervnc#535]
The man page for vncviewer says:

 -display Xdisplay
              Specifies the X display on which the VNC viewer window should appear.

However, there's actually no such option. Either the man page needs to be updated, or we need to add support for that option (probably by calling Fl::display).

**Comment by CendioOssman** [comment]
This was actually a regression. Fixed in 727a70f03868b1734e73853f2f75a4e9e4aa9b61.
