### ISSUE TITLE
(tech support) Can I run vncviewer in a window?

### ISSUE THREAD

**Issue by shentino** [TigerVNC/tigervnc#536]
I'm having trouble running vncviewer as a windowed app instead of fullscreen.  I already asked my distro (gentoo)'s support channel and didn't get a good answer.

What I'm seeking:

Being able to run vncviewer as a window, probably with scroll bars that will let me change what part of the remote desktop I see.

**Comment by CendioOssman** [comment]
Of course. There is a setting for fullscreen in the options dialog, and you can also enter and leave fullscreen by using the context menu (opened using F8 by default).
