### ISSUE TITLE
Java client - hitting and releasing Alt alone causes focus to return to the window manager

### ISSUE THREAD

**Issue by fnJeff** [TigerVNC/tigervnc#538]
So I've been using the fixed Java client and just noticed another strange thing.  I accidentally hit the Alt key without any other key.  Then I hit the down arrow (editing in xemacs) and something similar to the previous F10 problem happened.  The keyboard was focused to the window dressing and the drop down menu from the upper left of the window's title bar appeared.

This is basically exactly what hitting F10 before the fix did.  If Alt is combined with another key, I don't see the issue.

Hopefully it's an easy one to find and fix.

**Comment by bphinz** [comment]
Ah, yes I see that too.  I actually wondered if there were others like F10 and tried to write up something to list all of the keys with listeners bound to them and see what their actions were.  Unfortunately, all that I was able to get was a reference to an actionListener and no way (that I could find) to show what the handler does when it gets an event.  Annoying but easily fixed...

**Comment by fnJeff** [comment]
Fortunately, that's the only one I've seen so far.  Glad to hear it's an
easy one.  Lame that there is no easy way to detect all keys that do that.

I will continue to let you know.  Since the Java client is the only one
support scaling, I have a vested interest in helping you make it better.  :)


fnJeff

**Comment by fnJeff** [comment]
Let me know when you have a new .jar file to test.


fnJeff

**Comment by bphinz** [comment]
This should be fixed in d8809e3.  A new jar file has been posted to the the [nightly builds](http://tigervnc.bphinz.com/nightly/) page.  Please test it out and confirm.

**Comment by fnJeff** [comment]
Definitely fixed!

Thanks!


fnJeff
