### ISSUE TITLE
TigerVNC 1.8 issue with CentOS 7.4

### ISSUE THREAD

**Issue by briansrls** [TigerVNC/tigervnc#539]
I'm on a freshly installed version of CentOS 7.4, tigervnc-server package: tigervnc-server-1.8.0-1.el7.x86_64.  This bug seems to be reproducible by installing fresh 7.4 then following the basic instructions from the vncserver.service file:

1. Copy this file to /etc/systemd/system/vncserver@.service
2. Replace <user> with username
3. run `systemctl daemon-reload`
4. run `systemctl enable vncserver@:<display>.service`

Here is a centos forum discussion for more information: [tigervnc - behavior weird](https://www.centos.org/forums/viewtopic.php?f=47&t=64982&p=273538#p273538)

The basic gist of the issue is something like this image:
![image](https://user-images.githubusercontent.com/11205878/32799121-c20dcfa0-c944-11e7-95b1-6eeebf4ccec3.png)

There are no menu bars at all, including minimization, maximization, and close buttons on each process.  I'm able to open a terminal by right clicking on the desktop and hitting "open terminal".  When I try to check my display settings it shows "Could not get screen information".  When I select windows they do not come to the foreground.

What helped a little was adding the line `exec mutter --replace &` to my `~/.vnc/xstartup`.  With this addition, I see something like this:

![image](https://user-images.githubusercontent.com/11205878/32799829-c716ce50-c946-11e7-92e1-cc011ff1db8e.png)

I see a background image and I can interact with windows more normally.  The close buttons work, although I still don't have a minimize button or top menu bar.  When I click on windows they come to the background.

I am not very familiar with how vnc works, so I was hoping someone here may get a hunch based off of the images of what the issue could be.  Thanks!

**Comment by CendioOssman** [comment]
The images (and workaround) suggest that your window manager isn't starting up properly. Since this is CentOS that would mean some issue with gnome-shell. You also seem to be using Red Hat's modified version of TigerVNC, which has some different behaviour compared to ours.

Unfortunately they both mean you'll have to turn to Red Hat or CentOS for assistance. This does not look like a general TigerVNC issue at this point.

**Comment by TianhuaJu** [comment]
I have suffered the same issue like you

**Comment by TianhuaJu** [comment]
![Uploading 捕获.JPG…]()

**Comment by briansrls** [comment]
@TianhuaJu I recommend installing xrdp in the meantime, follow this guide: http://www.itzgeek.com/how-tos/linux/centos-how-tos/install-xrdp-on-centos-7-rhel-7.html

**Comment by TianhuaJu** [comment]
@briansrls Yes, your recommended method is very nice, but the similar problem occurred when I restart the   PC

**Comment by briansrls** [comment]
@TianhuaJu do you mean you're having the same problem with XRDP as you had with vanilla tigervnc?  I actually didn't have that issue on restart using XRDP
