### ISSUE TITLE
broken display in centos 7

### ISSUE THREAD

**Issue by leoliu** [TigerVNC/tigervnc#54]
I am using the stock tighervnc-server from centos 7 and my display often ends up like this http://i.imgur.com/rKEi28o.png, i.e. after quick movement or scrolling of a window, the display is out of date containing pixels from past etc.

I have also verified this doesn't happen when using a physical screen attached to the server.

Is this a known bug?

Thanks,
Leo

**Comment by dungla2011** [comment]
Centos 7 and VNC seem BAD, sometime can not interact

I run Centos 6 + VNC is very stable
