### ISSUE TITLE
Feature request: vncviewer 3-button mouse emulation

### ISSUE THREAD

**Issue by markeby** [TigerVNC/tigervnc#540]
I am currently using the "real" product which has this feature in the viewer.  I would prefer to use TigerVNC but it lacks this feature, which I require.  Please add this to emulate the wheel-button push.

**Comment by CendioOssman** [comment]
For reference, here's how Xorg's evdev driver does it:

https://cgit.freedesktop.org/xorg/driver/xf86-input-evdev/tree/src/emuMB.c

**Comment by CendioOssman** [comment]
And the old TigerVNC viewer:

https://github.com/TigerVNC/tigervnc/blob/1.0-branch/win/rfb_win32/CPointer.cxx

**Comment by CendioOssman** [comment]
Resolved via #942.
