### ISSUE TITLE
libtasn1-3-bin dependency quirck on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by qnxor** [TigerVNC/tigervnc#546]
I'm on a fresh install of Ubuntu 16.04.3 x64 and trying to install the .deb for v1.8.0

```
# dpkg -i tigervncserver_1.8.0-1ubuntu1_amd64.deb
Selecting previously unselected package tigervncserver.
(Reading database ... 270583 files and directories currently installed.)
Preparing to unpack tigervncserver_1.8.0-1ubuntu1_amd64.deb ...
Unpacking tigervncserver (1.8.0-1ubuntu1) ...
dpkg: dependency problems prevent configuration of tigervncserver:
 tigervncserver depends on libtasn1-3-bin; however:
  Package libtasn1-3-bin is not installed.
```

Trying to install `libtasn1-3-bin` I get:
```
# apt-get install libtasn1-3-bin
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libtasn1-3-bin : Depends: libtasn1-bin (>= 4.7-3ubuntu0.16.04.2)
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

I had to do a `apt-get -f install` in order to get those installed and then another `dpkg -i tigervncserver_1.8.0-1ubuntu1_amd64.deb` to have tigervnc installed ... this looks like a .deb definitions problem which should have installed those deps automatically and cleanly.

Leaving it here for the devs to consider.

**Comment by CendioOssman** [comment]
I'm afraid I don't see any TigerVNC issue here. Somehow your installation of `libtasn1-3-bin` got screwed up, but that's an issue that Canonical would need to resolve.

**Comment by qnxor** [comment]
I was afraid you'd say that :) but there has always been an issue installing the tigervncserver .deb on Ubuntu for as long as I remember you guys releasing .deb's ... sometimes those are solved by adjusting the defs in the .deb in order to trigger a proper install of all dependencies, which right now just doesn't happen.

**Comment by CendioOssman** [comment]
We don't want to carry workarounds for distribution bugs in our stuff. So I would recommend you to report this issue to Canonical and they will hopefully fix it. After that you shouldn't have any issue installing our debs.

**Comment by qnxor** [comment]
What I was saying was that the you could double-check the dep defs as the issue might just be in there, before reporting anythign to canonical.

**Comment by CendioOssman** [comment]
There is nothing in your bug report suggestion that they are incorrect. So I'm afraid there is nothing for us to adjust. Packages should only include their immediate dependencies. Secondary dependencies (which you are having problems with) should be handled by the package adding the extra dependencies. In your case that means libtasn1-3-bin.

**Comment by bphinz** [comment]
It looks like libtasn1-3 was superseded by libtasn1-6 in July and this
might be part of the issue. I’ll take a look when I get back from vacation
tomorrow.

-brian

**Comment by qnxor** [comment]
@bphinz, a sensible reply, thanks for actually checking! Enjoy the rest of your vacation.

**Comment by bphinz** [comment]
I just pushed commit abdb07b which fixes the reported issue.
