### ISSUE TITLE
Is Ubuntu 16.04 deb Debian 9 compatible with?

### ISSUE THREAD

**Issue by whao** [TigerVNC/tigervnc#548]
Hello everyone,

I am currently using Debian 9. It has its own tigervnc package but version is 1.7. Also it needs to work with vnc4server. I tested it and image quality is poor and copy/paste doesn't work. In official release [webpage](https://bintray.com/tigervnc/stable/tigervnc/1.8.0), I didn't find the Debian build binary. I tried linux.tar.gz. I copied call binaries in to /usr. It works but would be pain if I need to uninstall. I just wonder if the lasted Ubuntu build is compatible with Debian?

Thank you

**Comment by CendioOssman** [comment]
Not explicitly, no. They are not that strongly related. If you're lucky it might still match though, so I would suggest you try and see.

I would strongly suggest you poke Debian about upgrading though. We cannot provide packages for every possible distribution, so it's important that users tell their distributions they want TigerVNC included and updated.

**Comment by pm-pm** [comment]
> I am currently using Debian 9. It has its own tigervnc package but version is 1.7. 

> ... and copy/paste doesn't work. 

Just for documentation:
Copy&Paste works with tigervnc 1.7, but you have to run "vncconfig" programm. Once "vncconfig" is startet copy&paste works well. It is a feature of tigervnc 1.8 that vncconfig is not needed anymore. [See release notes tigervnc 1.8.](https://github.com/TigerVNC/tigervnc/releases/tag/v1.8.0)
