### ISSUE TITLE
Clipboard do not work correctly with KDE Klipper

### ISSUE THREAD

**Issue by kmatveyonok** [TigerVNC/tigervnc#549]
I have two linux boxes (slackware current) with kde.
Local client is krdc, remote is TigerVNC started from inetd in the second form(as from man).
It seems
  remote -> local works fine
  local -> remote not works at all
then, I close Klipper on remote and got local -> remote working.

As I see, vncconfig settings do not affect on this at all.

**Comment by CendioOssman** [comment]
We did a workaround for Qt bugs some time ago. Could you try a nightly build on the server to see if that helps?

**Comment by kmatveyonok** [comment]
I tried latest master.
local -> remote works with latin charactes, but something wrong with cyrillic. Seems something wrong with codepage. See image attached.

**Comment by CendioOssman** [comment]
The standard protocol doesn't support anything but latin-1 unfortunately. #20 is about improving this.
