### ISSUE TITLE
Cyrillic symbol do not work in typing

### ISSUE THREAD

**Issue by kmatveyonok** [TigerVNC/tigervnc#558]
I use KRDC as client and Xvnc/Linux server.
When I type Cyrillic_che, it do not pass to server. xev on server do not see keyPress/keyRelease.

Here is xev output from client side:
KeyPress event, serial 40, synthetic NO, window 0x6a00001,
    root 0x288, subw 0x0, time 636922892, (790,834), root:(790,857),
    state 0x2000, keycode 53 (keysym 0x6de, Cyrillic_che), same_screen YES,
    XLookupString gives 2 bytes: (d1 87) "ч"
    XmbLookupString gives 2 bytes: (d1 87) "ч"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x6a00001,
    root 0x288, subw 0x0, time 636922949, (790,834), root:(790,857),
    state 0x2000, keycode 53 (keysym 0x6de, Cyrillic_che), same_screen YES,
    XLookupString gives 2 bytes: (d1 87) "ч"
    XFilterEvent returns: False

**Comment by CendioOssman** [comment]
I cannot reproduce this issue here so I'm going to need some more details from you:

- What version of TigerVNC?
- How is the server started?
- What does the server log say?

**Comment by kmatveyonok** [comment]
1. master brach at 19 nov 2017
2. 5901   stream   tcp wait   km     /usr/bin/Xvnc Xvnc -inetd -query localhost -once passwordFile=/home/km/.vnc/passwd

Ups. I restarted the server with -Log *:syslog:100
And it works.

**Comment by CendioOssman** [comment]
I would guess you're getting bitten by #93. Please set a russian keymap in the session and you should be fine.
