### ISSUE TITLE
How to share the local logined display 0 on tigervnc.

### ISSUE THREAD

**Issue by iamybj** [TigerVNC/tigervnc#560]
After some config ,I can now connect my office computer at home by xrdp/tigervnc.
But the connection is a new session, not the local display 0 in office.
After some research, I find that x11vnc can do this:
x11vnc.x86_64 : VNC server for the current X11 session

Does tigervnc can provide the same function ?

**Comment by iamybj** [comment]
For Unix, the traditional VNC implementation includes a "virtual" X11 server Xvnc (usually launched via the vncserver command) that is not associated with a physical display, but provides a "fake" one X11 clients (xterm, firefox, etc.) can attach to. A remote user then connects to Xvnc via the VNC client vncviewer from anywhere on the network to view and interact with the whole virtual X11 desktop.

**Comment by hildred** [comment]
In addition to Xvnc the tigervnc project also provides two other servers x0vncserver (which is roughly equivlent to x11vnc) and vnc.so which is a loadable module for x.org, both of which will probably do what you want.

**Comment by iamybj** [comment]
How to set x0vncserver and vnc.so ?

I strongly recommend write a hand-by-hand guide to describe how to configure tigervnc.
Man files are not satisfied  with end users, just satisfied with developers.

**Comment by iamybj** [comment]
x0vncserver - an **inefficient** VNC server which continuously polls any X display

inefficient ? that's too bad. And I found tigervnc is writern by c++, but x11vnc is writern by c. C is more  efficient than c++.

**Comment by CendioOssman** [comment]
x0vncserver has actually gotten better and will now only use polling as a fallback. But it is still a fairly simple server so x11vnc might be better as something standalone. The GNOME project also has their vino for screen sharing.
