### ISSUE TITLE
Need "verbose" log level, between default and debug

### ISSUE THREAD

**Issue by astrand** [TigerVNC/tigervnc#561]
Currently, we have this log levels:
    static const int LEVEL_ERROR  = 0;
    static const int LEVEL_STATUS = 10;
    static const int LEVEL_INFO   = 30;
    static const int LEVEL_DEBUG  = 100;

The default for vncviewer is -Log=*:stderr:30. This means that you cannot select to run in a "verbose" mode or similar. All you have is the default level, and the highest debugging level. 

This affects the very nice statistics graph: It is only enabled on loglevel 100. This does not make sense: It could be useful to have the graph, even for an end user, without having to resort to the highest debug level.  

We could consider defining a LEVEL_VERBOSE=50, or similar.

**Comment by CendioOssman** [comment]
Sounds like it's just about the graph and not that we have a need for more levels for log messages?

If so, then I think it is better to give that its own switch. E.g. creating a new log class so you can turn on just the graph.
