### ISSUE TITLE
Qucik question: Why does tiger VNC use Java, for what parts ?

### ISSUE THREAD

**Issue by GuacheSuede** [TigerVNC/tigervnc#562]

**Comment by bphinz** [comment]
We have a full featured viewer written in Java (in addition to our native/c++ client).  The java viewer can be deployed as an applet or JNLP, or used as a stand-alone application.

**Comment by GuacheSuede** [comment]
Hypothetically, could one replace Java Swing with QT for memory savings or would it be not worth ?

**Comment by bphinz** [comment]
I can't imagine a scenario where that would be more beneficial than just using the native client (which uses Fltk for the user interface).  The memory footprint of the Java viewer is quite small anyway, and for any reasonably sized screen most of that is attributable to the framebuffer not Swing.

**Comment by GuacheSuede** [comment]
I see, understand it now, Thanks for the help :)
