### ISSUE TITLE
How to use tigervnc viewer to VNC server that require MSlogon

### ISSUE THREAD

**Issue by reubinoff** [TigerVNC/tigervnc#564]
Hi,
I have one PC with UltraVNC server that has MSLogn Cred requires.
How can I use the tigerVNC viewer from linux command line to connect to this server?

Thanks!

**Comment by CendioOssman** [comment]
I'm afraid TigerVNC does not support that authentication type. So you'll have to configure your server with some other method. Perhaps they support "Plain" which is similar?

**Comment by reubinoff** [comment]
Thanks!
