### ISSUE TITLE
Quick Question: Is there a headless api to send events such as clicks or keyDown ?

### ISSUE THREAD

**Issue by GuacheSuede** [TigerVNC/tigervnc#565]

**Comment by CendioOssman** [comment]
For the viewer? I'm afraid it does not have any API at all. However other products should be able to send fake events to the viewer window.

**Comment by GuacheSuede** [comment]
Theoretically if one were to write such a product, how would he or she hook onto the headless api, via command line or if through code do you know what file to look at ?

**Comment by CendioOssman** [comment]
The fake events would be sent through the operating system methods. E.g. X11 on Unix or using the Win32 API on Windows. So it isn't directly connected with TigerVNC.

**Comment by bphinz** [comment]
You might also want to look at [LibVNCServer/LibVNCClient](https://libvnc.github.io/), it's an API for interacting with VNC servers/clients.

**Comment by GuacheSuede** [comment]
@bphinz Thanks for the link Brian, scanning through i found this [GTKVNCVIEWER](https://github.com/LibVNC/libvncserver/blob/master/client_examples/gtkvncviewer.c), do you happen to mean something like this ?

Another option would be that the individual directily edits [vncviwer.cxx](
https://github.com/TigerVNC/tigervnc/blob/master/vncviewer/vncviewer.cxx) from tigervnc, would that be right ?

**Comment by bphinz** [comment]
> @bphinz Thanks for the link Brian, scanning through i found this GTKVNCVIEWER, do you happen to mean something like this ?

LibVNC provides both client & server APIs so you could use to send events without ever opening up a client.  If, on the other hand, you want to send fake events in addition to real ones generated by a user interacting with a viewer, then like Pierre said there's lots of ways to do that through the OS.  Utilities like Xdotool can send fake events to a specific window.

> Another option would be that the individual directily edits vncviwer.cxx from tigervnc, would that be right ?

It's really hard to say without knowing what you're trying to accomplish.

**Comment by GuacheSuede** [comment]
@bphinz Thanks for the reply Brian. Mainly to send keystrokes and pointer events to a headless tigervnc server mostly to do testing of applications.

**Comment by GuacheSuede** [comment]
@CendioOssman would you happen to mean something like [this](https://www.acmesystems.it/x11lib) ?

**Comment by CendioOssman** [comment]
No, that's just a very basic template for a X11 application.

As @bphinz said, I would suggest looking at libvncclient if you need a way to write an automated vnc client. They've put more effort in to being usable as a lib. If you want to use TigerVNC you'll have to start digging around in the code and get familiar with things as we do not have any API documentation.
