### ISSUE TITLE
Stripes are present in 1.8.0 on macOS 10.13.1

### ISSUE THREAD

**Issue by jsoref** [TigerVNC/tigervnc#570]
![image](https://user-images.githubusercontent.com/2119212/34570336-6bd9188e-f139-11e7-98b1-6cc558f3a463.png)

macOS 10.13.1
TigerVNC 1.8.0

The look and feel here appears to be the 10.0 .. 10.5 (?) look and feel, as of 10.6, an unstriped appearance became standard.

**Comment by CendioOssman** [comment]
I agree. I'll have a look what can be done.

**Comment by CendioOssman** [comment]
Oddly enough I'm not getting these stripes with my builds, so there is something different with the version of FLTK used by @bphinz for the official builds.

Still though, we probably want to get rid of the shiny buttons anyway so I changed things in 490b3198f7d806ce29e2908ffc03fbea80948b8f.
