### ISSUE TITLE
Bug: TigerVNC fully closes after automatic rejection timeout

### ISSUE THREAD

**Issue by kingio** [TigerVNC/tigervnc#572]
O.S: Windows 10 64b - Falls creator update

Everytime a request is not accepted, the entire server closes. 
Is this the expected behaviour? If yes, can it be disabled? I don't see any related option.

This issue may be related https://github.com/TigerVNC/tigervnc/issues/573

**Comment by CendioOssman** [comment]
Are you seeing a similar crash as for #573?

**Comment by kingio** [comment]
In this case, i see how TigerVNC icon disappears from tray, but it doesn't show me the usual "Has stopped working" window that in #573 does.

Example:
![https://images.scdn8.secure.raxcdn.com/wp-content/uploads/2016/12/img_585753d6e1329.jpg](https://images.scdn8.secure.raxcdn.com/wp-content/uploads/2016/12/img_585753d6e1329.jpg)

**Comment by CendioOssman** [comment]
Hopefully this is fixed now. Please have another try.
