### ISSUE TITLE
Bug: TigerVNC Server closes after a session

### ISSUE THREAD

**Issue by kingio** [TigerVNC/tigervnc#573]
O.S: Windows 10 64b - Falls creator update

After every session TigerVNC Server is closed.
If i don't interact with the client, (i just look),  TigerVNC Server is not closed when VNCViewer is closed :S

  
Edit: Ups, looks like it's a bug:
`Uncontrolled exception 0x00000000004B6310 on winvnc4.exe: 0xC0000005: Access violation when writing to the location 0x0000000003998EB8.`

**Comment by CendioOssman** [comment]
Hopefully this is fixed now. Please have another try.
