### ISSUE TITLE
TLS performance is bursty at times

### ISSUE THREAD

**Issue by sortel64** [TigerVNC/tigervnc#574]
I am using TigerVNC 1.8 on CentOS 6.9 using the TLS encryption security type.  Generally the performance is very good.  The encryption overhead is not perceivable.

However, I notice that if I am in a terminal window and type something like 'ls -l', I get all of the results except the very last few bits.  It may be an entire line of just a few characters.  If you move the mouse or type something like backspace.  The rest shows up.  It is almost like something is being buffered in then encryption module and is waiting to send an entire packet.  I have the encryption settings set to the highest performance.  We have no known network issues.

This does not occur if TLS is not used.

Is this a known issue?  Are there any settings that I can tweak?

This is an awesome tool.  Thanks to everyone who helps make it possible.

**Comment by CendioOssman** [comment]
That is not an issue I recognize, and it does sound like there is something in the network that is buffering things.

Are both client and server on the same network?

**Comment by sortel64** [comment]
Thanks for the comment.  They are not on the same network.  However, the problem seems to disappear when encryption is disabled.

**Comment by CendioOssman** [comment]
Do you think you could test with a client on the same network?

Are you using our builds for both client and server? If not, could you test with those?

**Comment by sortel64** [comment]
I am using your build for both the client and the server.  I will try to find a way to test on the same network.  Thanks!

**Comment by CendioOssman** [comment]
Any luck figuring out the issue?

**Comment by sortel64** [comment]
Thanks for the follow up.  My company moved us to thin clients and now I don't notice the issue.  So, it could have been in the old windows machine or the local network.  I think that we can close this for now since this does not seem to be a know issue that other are having.  I can submit another ticket or re-open this one if notice it again or I have anything more material to offer to help troubleshoot.  Again, I appreciate the support, and thanks for making TigerVNC!
