### ISSUE TITLE
map option key to alt in tigervnc-viewer of mac os x

### ISSUE THREAD

**Issue by faicker** [TigerVNC/tigervnc#576]
I am using tigervnc-viewer under mac os x(10.13.2) to connect to a centos 7 tigervnc server. viewer is full-screened. The option key is not mapped to alt key. The command key is mapped to alt key. But when I type command + tab, it takes effect in mac os x.
Turbovnc-viewer is OK.

**Comment by CendioOssman** [comment]
We have this shuffle of modifiers on macOS because of the way the Alt button works there (and to some extent the command key), so that is expected.

However the issue of locally grabbed keys is independent of this. You need to be in full screen for such keys to be sent over to the server rather than intercepted locally.

**Comment by episodeyang** [comment]
Thanks for this great tool. It would be really good if this design can be customized.

**Comment by ipstone** [comment]
I was looking for a way to remap mac option key to alt key to be used for vnc on a centOS machine: glad to discover this behavior - using the cmd for Alt on the vnc server!

**Comment by dims12** [comment]
Mapping command to alt makes impossible to switch windows within vnc. Very poor design.

**Comment by dims12** [comment]
> I was looking for a way to remap mac option key to alt key to be used for vnc on a centOS machine: glad to discover this behavior - using the cmd for Alt on the vnc server!
> 
> -- one update/comment: this tweak seems **only working for the internal keyboard** on my macbook, but not the external keyboard that I am using.

Which tool are you talikng about?

**Comment by didibus** [comment]
It be nice if this was customizable. I use Karabiner to swap command and alt everywhere on my mac, but then in Cendio its swaps the already swapped which is terribly annoying.

**Comment by prasskaly** [comment]
+1
I'm interested in having key mappings for modifier keys customized in TigerVNC settings.
