### ISSUE TITLE
No title bar, borders, minimize, maximize on some windows

### ISSUE THREAD

**Issue by sosul** [TigerVNC/tigervnc#577]
VNC Server:
CentOS7, tigervnc-server-1.8.0-2, gnome-session-2.22.3-4
VNC Client:
TightVNC Viewer for Windows 2.7.10

1. Some windows do not have title bar, borders, minimize, maximize, and close buttons, so that I cannot resize them.
2. I cannot move one of those if it does not have the menu bar.
3. Those windows do not come on top when I click them.
4. Main desktop itself does not have its title bar, which prevents access to main menu.

![image](https://user-images.githubusercontent.com/8186982/34659421-d44ce298-f47b-11e7-9ab3-6932f261e8c5.png)

Server configurations
- vncserver@:1.service has minimal modification (replacing \<USER\> to an account)
- xstartup is not modified
- config has geometry and rfbport settings

I'm not sure whether the problem comes from server or client.

**Comment by CendioOssman** [comment]
I'm afraid this is a Red Hat bug:

https://bugzilla.redhat.com/show_bug.cgi?id=896648

They've rolled out a fix for Fedora, but you may have to nag them to do the same for RHEL.

**Comment by mzechmeister** [comment]
I have the same problem with twm on kde.
.
And the problem also seems to occur also for gnome + ubuntu (https://askubuntu.com/questions/1259891/xfce-vnc-environment-no-longer-has-control-bar-menus-for-screens-no-close-or-m).
