### ISSUE TITLE
KDE asks to adjust monitor for :0

### ISSUE THREAD

**Issue by kmatveyonok** [TigerVNC/tigervnc#578]
I tried setup to use vnc module for X. For some reason KDE periodically asks to adjust monitor.
The :0 screen connected to TV via HDMI (original resulution for TV was 1920x1080, TV now is off power), but connected client VNC client is 1600x900 and I change resolution after login with script like:

#!/bin/sh
OUTPUT=`xrandr |grep " connected"|cut -d " " -f 1`
echo $OUTPUT
xrandr --newmode "1600x900_60.00"  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync
xrandr --addmode $OUTPUT 1600x900_60.00
xrandr --output $OUTPUT --mode 1600x900_60.00

Is there way to prevent KDE asking readjust screen?

I have another screen :1 started from initd, it works ok after screen adjusted with this script.

**Comment by CendioOssman** [comment]
I'm afraid I don't know KDE well enough for that. You'll have to check with them on how to disable this behaviour.

**Comment by kmatveyonok** [comment]
I disconnected HDMI cable from TV and KDE stops asking for screen adjustment
