### ISSUE TITLE
Xtigervnc reports incorrect lock file name

### ISSUE THREAD

**Issue by scaleoutsean** [TigerVNC/tigervnc#580]
```
/usr/bin/Xtigervnc 
(EE) 
Fatal server error:
(EE) Server is already active for display 0
	If this server is no longer running, remove /tmp/.X0-lock
	and start again.
(EE) 


```
I couldn't find this file to figure out what's going on. After a while I found on my system it's `/tmp/.X11-unix/X0`

* Ubuntu Xenial 16.04
* Xvnc TigerVNC 1.8.0 - built May 17 2017 20:53:25

**Comment by CendioOssman** [comment]
That is the correct path. `/tmp/.X11-unix/X0` is the socket, not the lock file, so it's not quite the same thing.

Either way though it seems like you already have a server running on that display, so I would suggest starting it on a different display number.
