### ISSUE TITLE
On Xfce on trusty, text under icon is not properly rendered

### ISSUE THREAD

**Issue by dev-ddoe** [TigerVNC/tigervnc#582]
I have some graphic glitches on text displayed under icon on the desktop of xfce.
![glitch](https://user-images.githubusercontent.com/20719822/34946171-182dc600-fa06-11e7-8486-e6a86c67ad3e.png)
This issue exists from tigervnc 1.4.1 to tigervnc 1.8.0.
It also exists using the nightly (tigervnc-1.8.80-20180112git1d29683.x86_64.tar.gz)

### To reproduce this  issue
* Deploy an ubuntu 14.04
* install xfce on it using the command: apt-get install xfce4
* Install tigervnc using the following command
`cd /tmp`
`wget https://bintray.com/tigervnc/stable/download_file\?file_path\=tigervnc-1.8.0.x86_64.tar.gz -O tigervnc.tar.gz`
`tar xzvf tigervnc.tar.gz`
`cp tigervnc-1.8.0.x86_64/* / -fr`
* Create a vnc server session using the following commands
`export DISPLAY=:10.0`
`Xvnc :10 -SecurityTypes None &`
`startxfce4`

* Access the vnc session using the vnc client and the address IP:5910
* Create a some icon on the desktop.
* icons looks like the following:
![glitch](https://user-images.githubusercontent.com/20719822/34946171-182dc600-fa06-11e7-8486-e6a86c67ad3e.png)

### Workaround:
* start tigervnc using the option -render

### Notes:
* This issue does not exist on tigervnc 1.4.0
* The issue occurs also on xenial if the compositor is disabled.(https://wiki.archlinux.org/index.php/Xfwm)

**Comment by CendioOssman** [comment]
I've seen this as well now and then, but I've yet to pinpoint what's causing it.

**Comment by CendioOssman** [comment]
Identified and fixed in 2922e749706297dba661e569b55c5252da5daecc.
