### ISSUE TITLE
geometry not working on linux

### ISSUE THREAD

**Issue by ganeshjkale** [TigerVNC/tigervnc#584]
Xvnc :10 -geometry 1920x1080 -depth 24 -rfbauth /home/test/.vnc/sesman_test_passwd -bs -ac -nolisten tcp -NeverShared

above command not resizing vnc session as per geometry

server:-xubuntu 16.04 x64

**Comment by CendioOssman** [comment]
That works absolutely fine for me. Are you sure it's not just your viewer that resizes things back when you connect?

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by torvim** [comment]
Same issue! When I specify window geometry I get:

`Geometry:    Desktop geometry is set to 1280x1024+0+0`

When I have specified `geometry=1920x1080`

**Comment by torvim** [comment]
Upon further inspection it seems to cap out geometry at 1280x1024, which seems odd to me. Am I being an idiot here?

**Comment by CendioOssman** [comment]
That should not be an issue. What is your exact Xvnc command line? And what version/build are you using?

**Comment by torvim** [comment]
`x0vncserver display=:0 SecurityTypes=none Geometry=1920x1080`

Is the exact command and

` Geometry:    Desktop geometry is set to 1280x1024+0+0`

Is the output

**Comment by torvim** [comment]
I cloned and compiled it myself yesterday evening.

**Comment by CendioOssman** [comment]
I'm afraid that is not quite the same thing. You are using x0vncserver but the original report was about Xvnc.

That command line works just fine here though:

```
$ x0vncserver display=:0 SecurityTypes=none Geometry=1920x1080

Fri Jun  5 13:54:53 2020
 Geometry:    Desktop geometry is set to 1920x1080+0+0
 XDesktop:    Using evdev codemap
 XDesktop:    
 XDesktop:    XTest extension present - version 2.2
 Main:        Listening on port 5900
```

What is the resolution of your local display? What does `xrandr -display :0` say?

**Comment by CendioOssman** [comment]
No response. Closing.
