### ISSUE TITLE
Connection shows ESTABLISHED even when the client is down.

### ISSUE THREAD

**Issue by dhanjit** [TigerVNC/tigervnc#586]
I don't think currently the server uses Keep Alive TCP sockets. Hence if the wire is pulled at a client, it takes 15 minutes (this is probably the retries time in proc/sys/net/tcp_retries2) to disconnect the client. It is too long a time for my use case where I need to get it disconnected quickly enough if network is down.

Maybe SO_KEEPALIVE can help? Or some way to set TCP_USER_TIMEOUT socket option?
Is there any way to figure out quickly enough if the remote is connected? 

IdleTimeout is also not an option, because it can be validly connected and the user can be simply watching but not "touching" with mouse/keyboard.

**Comment by CendioOssman** [comment]
An option for turning on TCP keep alive is pretty rare (since few need it), but there is a library called [http://libkeepalive.sourceforge.net/](libkeepalive) that allows you to enable it anywhere you like. So I would advise you to have a look at that.

**Comment by caio-vinicius** [comment]
Thanks for the recommendation, @CendioOssman
