### ISSUE TITLE
Stretch remote desktop to fill the view

### ISSUE THREAD

**Issue by physiii** [TigerVNC/tigervnc#587]
How do I get the remote desktop to fill the entire window no matter the server resolution. This needs to on the client since I can't change the server resolution.

Any ideas?

**Comment by CendioOssman** [comment]
I'm afraid we do not support that yet. Please see #274.

**Comment by bphinz** [comment]
As was mentioned in #274, the TigerVNC Java client supports scaling the client display to fill the window without altering the server-side resolution.
