### ISSUE TITLE
when using arm-linux-gcc to compile the source code of tigervnc-1.8，it's trouble that the file “./configure” not found!

### ISSUE THREAD

**Issue by zehrry** [TigerVNC/tigervnc#589]
**topic :**when using arm-linux-gcc to compile the source code of tigervnc-1.8，it's trouble that the file “./configure” not found!
**detail:**
$tar zxvf tigervnc-1.8.tar.gz 
$cd tigervnc-1.8/unix 
$CC=arm-linux-gcc 
$CXX=arm-linux-g++ 
**$./configure** --host=arm-linux --x-libraries=/usr/arm/lib --x-includes=/usr/arm/include

**Comment by CendioOssman** [comment]
We don't have a configure script, so that's not really surprising. You should use CMake for TigerVNC. Please see BUILDING.txt for details.
