### ISSUE TITLE
Add .desktop strings from "Name" and "GenericName" to translations

### ISSUE THREAD

**Issue by scootergrisen** [TigerVNC/tigervnc#591]
I suggest adding all strings (currently 3 strings) from the .desktop file to the translations POT/PO files so they can be translated.

```
Name=TigerVNC Viewer
GenericName=Remote Desktop Viewer
Comment=Connect to VNC server and display remote desktop
```

Currently it seems only the last string "Connect to VNC server and display remote desktop" is in the POT/PO files.

**Comment by CendioOssman** [comment]
Translations are updated as part of the release work, so this will be handled once we start preparing for 1.9.0.
