### ISSUE TITLE
Does the vncserver allow different session in progressions of 100?

### ISSUE THREAD

**Issue by joynexa** [TigerVNC/tigervnc#593]
I executed the following command in my linux machine: **vncserver :11**
I get the vncserver starting on display port 11. 
However when I try **vncserver :111**, **it says the vncserver is already running on 111**, even though I had not started one on 111..
I tried **vncserver :211** after this and it throws up a similar message, **vncserver is already running on 211**
Is the launch of vncserver on port 11, locking up the display ports in progression of 100?

Thanks ..

**Comment by CendioOssman** [comment]
No, I'm afraid `vncserver` does not support that at the moment. The reason being that the default VNC and X11 ports start overlapping at display :100 and `vncserver` does not have sufficient support for custom ports.

**Comment by joynexa** [comment]
Thank you for the clarification !!
