### ISSUE TITLE
There is no menu bar on the screen

### ISSUE THREAD

**Issue by singletone16** [TigerVNC/tigervnc#600]
Server: Oracle Linux 7.4 with KDE. TigerVNC 1.8.0-2.el7_4 from the repository.
Client: Win8.1, TigerVNC Viewer 1.8.0
![1](https://user-images.githubusercontent.com/36726810/36527800-178d20a2-17c4-11e8-87c0-7f74dbe56972.PNG)
The menu and background are not loaded. The other functions are working.
On the same server with Oracle Linux 7.4 with KDE. TigerVNC 1.3, the client is the same-everything works fine.
Tell me what to do in this situation.

**Comment by CendioOssman** [comment]
This is unfortunately a bug in Red Hat's packaging of TigerVNC. Please file a bug with Oracle or Red Hat or use our packages.
