### ISSUE TITLE
Interface feedback for maximum password length

### ISSUE THREAD

**Issue by a-raccoon** [TigerVNC/tigervnc#602]
There is currently no feedback being provided to the user when setting a VNC password, alerting them to the fact that a password may not exceed 8 characters in length.  In fact, it will quietly accept an infinitely long password as Good even though only the first 8 characters are retained and used.

This includes everywhere that a password is set, entered and validated:  It's almost as if TigerVNC purposefully deceives users to conclude that long passwords are useful, when they are not useful.  Users must be warned and prohibited from accidentally entering passwords that exceed 8 characters in length, so they may be informed users and not tricked into a false sense of security.

![tigervnc-8-char-password](https://user-images.githubusercontent.com/1052090/36562213-8bf978dc-17d3-11e8-96dc-1d59f7e9ff67.png)

**Comment by CendioOssman** [comment]
As I mentioned on #601, we already have an issue about warning about the password length in #370.
