### ISSUE TITLE
Can the vncserver log files be redirected?

### ISSUE THREAD

**Issue by joynexa** [TigerVNC/tigervnc#603]
Currently when I launch a vncserver, it creates the .pid and .log files in my $HOME/.vnc directory. This over a period of time, fills my home space.

Is there any way that the .pid file/ or the .log file more importantly(which is large) can be redirected elsewhere?

Thanks ..

**Comment by CendioOssman** [comment]
No, I'm afraid `vncserver` does not support changing the location of the log file. However you can replace `~/.vnc` with a symlink to some other part of your filesystem.

**Comment by joynexa** [comment]
Thanks!
