### ISSUE TITLE
Low colour depth (8-bit) image palette looks wrong

### ISSUE THREAD

**Issue by romanrm** [TigerVNC/tigervnc#605]
I suppose because the support for color maps was removed in [1]?

For instance at https://www.lowendtalk.com/ the left and right side green bars are turned into a blueish tint instead. And on great many of other websites and apps there's a noticeable loss of either correctness or visual fidelity in general. In all of those the original VNC server [2] manages to stay close enough (much closer than TigerVNC) to how things look in full color.

Is there any workaround now?

[1] https://github.com/TigerVNC/tigervnc/commit/b6b4dc6487690e891ec2487c6cf765d36821fe3a
[2] https://packages.debian.org/jessie/vnc4server

**Comment by CendioOssman** [comment]
> I suppose because the support for color maps was removed in [1]?

No, that commit means the server won't start if colour maps are required. So if it's running then you're seeing some other issue.

Could you take a screenshot of the problem?

And have you checked your client setting that you aren't using a reduced color mode?

**Comment by romanrm** [comment]
> And have you checked your client setting that you aren't using a reduced color mode?

Yes, in both cases the server is launched with -depth 24, but in the client I set "Color level: Medium (256 colors)". Does not seem to matter which client, same with TigerVNC, SSVNC or the original one. I'll try to make screenshots in a bit.

**Comment by romanrm** [comment]
Full color (for reference): https://romanrm.hk/2018-03-01T084949Z-letfc.png

Original VNC server 256 colors: https://romanrm.hk/2018-03-01T085318Z-letorig.png
TigerVNC server 256 colors: https://romanrm.hk/2018-03-01T085222Z-lettiger.png
Client settings in both cases: https://romanrm.hk/2018-03-01T085558Z-client.png

As you can see not only many colors are wrong compared to the original, also horizontal lines in the main topic list were "clamped" to white, and as such are missing.

Also including a 64 color mode screenshot for reference, to verify that it was not using the 64 color mode by mistake in the example above: https://romanrm.hk/2018-03-01T090341Z-let64color.png

**Comment by CendioOssman** [comment]
Some colors will always be wrong, that's just the nature of reducing the number of available colors. But your example seems to show some rounding error. I'll see if I can figure out what's going on.

**Comment by CendioOssman** [comment]
Should be fixed in 816baa35ae5374f350ee4031ac54d7d1e90af183.
