### ISSUE TITLE
SELinux prevents systemd from reading vncserver pid file

### ISSUE THREAD

**Issue by graywolf2** [TigerVNC/tigervnc#606]
Please read this: https://forums.fedoraforum.org/showthread.php?317411-VNC-server-systemd-SELinux-problem

I think you must implement the possibility to change the pid file location.
The default location $HOME/.vnc/host:display#.pid is inconvenient when vnc server is configured as systemd service.
In Fedora the SELinux blocks the access to such location for systemd by default.

The user must have the ability to configure the vnc server so that the pid file will be created in separate directory with var_run_t label.

**Comment by CendioOssman** [comment]
There are many ways to resolve this, and having a fully customizable pid file location isn't necessarily the best way.

Has this been reported to Fedora? Their SELinux guys might have some input.
Where are PID files for user services normally located? $XDG_RUNTIME_DIR might be something, but I'm finding some mixed information on it being suitable for PID files or not. And it would still need a fallback since it might not be set.

**Comment by graywolf2** [comment]
I try to report this to Fedora as a bug.
-------------------------------------------------------
vovk@dell:~$ echo $XDG_RUNTIME_DIR
/run/user/1000
vovk@dell:~$ ls -Zld /run/user/1000
drwx------. 8 vovk vovk system_u:object_r:user_tmp_t:s0 180 Mar  6 11:18 /run/user/1000
vovk@dell:~$ ls -ld /var/run
lrwxrwxrwx. 1 root root 6 Jun 16  2017 /var/run -> ../run

I think the pid file may be placed somewhere in /run/user/{uid}.
But I'm not sure that the /run/user/{uid} directory will be created always at the server.
Later I will check the SELinux access to that directory for systemd.

**Comment by graywolf2** [comment]
I confirm that the /run/user/{uid} directory is not created always.
```
[fedora@test-server ~]$ ls -nld /home/simple_user
drwx------. 18 1001 1001 4096 Mar  5 18:40 /home/simple_user
[fedora@test-server ~]$ ls /run/user/1001
ls: cannot access '/run/user/1001': No such file or directory
```
I executed that commands after successful start the vnc server as systemd service for simple_user (without PIDFile=).

**Comment by CendioOssman** [comment]
So that directory is probably not a good idea then. I'd say we need more feedback from the SELinux people and/or systemd people.

**Comment by graywolf2** [comment]
One of the solution may be to use the following template for systemd vnc service.
```
[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking

User=USER
Group=USER

PIDFile=/var/run/vncserver/%H:%i.pid
WorkingDirectory=/home/USER
Restart=always

# Execute pre and post scripts as root
PermissionsStartOnly=true

ExecStartPre=/bin/rm -f /tmp/.X11-unix/X%i
ExecStartPre=/bin/bash -c '[ -d /var/run/vncserver ] || { mkdir /var/run/vncserver && chown USER:USER /var/run/vncserver ;}'

ExecStart=/usr/bin/vncserver :%i -geometry 1366x768 --pid-file=/var/run/vncserver/%H:%i.pid
ExecStop=/usr/bin/vncserver -kill :%i

[Install]
WantedBy=multi-user.target
```
But you have to implement the --pid-file= option.

**Comment by CendioOssman** [comment]
This is a user service, meaning many different users can be running it at the same time. So things need to be in user specific directories.

Why not just remove `PIDFile` from the service definition if that seems to work well? systemd obviously doesn't handle this use case very well.

**Comment by graywolf2** [comment]
> Why not just remove PIDFile from the service definition if that seems to work well? systemd obviously doesn't handle this use case very well.
I did so. :) It works fine without PIDFile.
Honestly, I don't understand how PIDFile can be useful for systemd in such service.

**Comment by okapia** [comment]
For anyone who is regarding this as purely an SELinux problem, can I just point out that I'm running into the same issue because home directories are mounted from a server using NFS and the .vnc directory is created by default without world read/execute permissions. And as we don't use root_squash on our filesystems, systemd can't read the PID file or change the permissions on the directory. Even without the permission issues, I'd be far happier with the PID file being on tmpfs than NFS.

**Comment by CendioOssman** [comment]
We now have a different approach to starting the server which shouldn't have this issue. Closing.

**Comment by apmattil** [comment]
'We now have a different approach to starting the server which shouldn't have this issue. Closing.'
what is this different approach ?

**Comment by CendioOssman** [comment]
There is an updated `vncserver@` systemd service. Please have a look in the unit file for it from the latest release on how to get it up and running.
