### ISSUE TITLE
Using the clipboard to copy & paste Chinese has garbled between Windows and Ubuntu

### ISSUE THREAD

**Issue by fcying** [TigerVNC/tigervnc#609]
copy from windows chrome 
![1](https://user-images.githubusercontent.com/106934/37238084-721292a4-2459-11e8-84ea-679c7840d578.jpg)

paste to ubuntu file manager
![2](https://user-images.githubusercontent.com/106934/37238087-91e2beba-2459-11e8-992b-d1924db5b95a.jpg)

Copy & paste English  can be displayed normally

Is there any settting that can be fix it?

**Comment by CendioOssman** [comment]
I'm afraid this is not supported in TigerVNC right now. Please see #20.
