### ISSUE TITLE
Scrolling backgorund windows corrupt foreground ones

### ISSUE THREAD

**Issue by stefanot73** [TigerVNC/tigervnc#610]
Dear support,

I am experiencing a problem which looks to be difficult to be fixed.
The basic issue is that when two windows overlap and the one in the background scrolls, then the one in foreground (and in general part of the screen) is corrupted, making it impossible to work with it.
This behavior happens also when the scrolling window in minimized or in another workspace.

This issue appeared when the O.S. was updated to Linux RH 7.3 (uname -r -> 3.10.0-514.el7.x86_64).
I am using Xvnc TigerVNC 1.3.1 - built Sep 13 2016 10:00:38.
I have tried different machines (with the same OS version), different version of the viewer and different network connections, but the issue is always there.
The way I have started the VNC server is vncserver -geometry 1920x1080 -dpi 75.

Any feedback would be greatly appreciated.
In case you need more data from me or you want me to run any experiment, please just let me know.
Thanks a lot in advance.
Best regards,
Stefano

**Comment by CendioOssman** [comment]
This was fixed some time ago, so you need to upgrade your TigerVNC. RHEL 7.4 includes TigerVNC 1.8.0, which does not have this problem.

**Comment by stefanot73** [comment]
Hi, thanks a lot for you prompt feedback.

**Comment by stefanot73** [comment]
Hi, I understand this ticket is closed, but I hope I can ask a further question.
Is there specific condition why this issue appears? The reason for this question is that most of my colleagues (sharing the same machines and systems) do not have such a problem.
Thanks a lot for any feedback you'd like to provide.
Best regards,
Stefano

**Comment by CendioOssman** [comment]
I think it was 9986dce0ae20b0821a5e189f58e86a764079048b that fixed this, so I would guess that you have compositing enabled in your desktop environment and your colleagues do not.
