### ISSUE TITLE
Problem: with password

### ISSUE THREAD

**Issue by jaifar530** [TigerVNC/tigervnc#611]
This is critical issue 
after the installation, I have input the password to be 

> vncpasswd 
P@ssw0rd@2016@XYZ

 then and by using the chrome VNC client, if I test to access using "P@ssw0rd@" the system accept me,
in other words i can access using at least 8 characters of above main password ""P@ssw0rd@2016@XYZ" !!

try to use my case above and let me know if this is a my proplem or general problem.

**Comment by CendioOssman** [comment]
I'm afraid VNC authentication is limited to just 8 characters. We have issue #370 for better informing users of this limit.
