### ISSUE TITLE
Cursor lag when using TigerVNC behind Citrix ICA

### ISSUE THREAD

**Issue by Adonai** [TigerVNC/tigervnc#612]
Hi. Thanks for wonderful VNC implementation.

TigerVNC versions:
vncserver: Linux RHEL 7.3, TigerVNC 1.8.0
vncviewer: Windows 7, TigerVNC 1.8.0

I have quite a strange issue. When I was using bare metal hardware desktop all worked perfectly, when I was moving cursor to the vncviewer window the local windows cursor took shape of remote one and was rendered locally, without any lag.

Now I am working mostly remotely and here's where issues arise:

1. When I connect through Citrix ICA to my desktop and start vncviewer the following happens:
* Local windows cursor doesn't disappear
* Remote cursor is visible too but it has visual lag (due to network latency, I guess)

2. When I connect through DELL Wyse Thin Client and start vncviewer the following happens:
* Local cursor disappears as expected
* Remote cursor is visible but it has same visual lag

Here's a screencast from Citrix ICA:
https://i.imgur.com/CUtIkVe.mp4

**Comment by CendioOssman** [comment]
That is indeed odd. But if it works fine without Citrix, then I'm afraid there isn't very much we can do. It sounds like Citrix has some form of bug or limitation when it comes to cursors. So I think you'll have to report the issue to them and see if they can sort it out. :/

**Comment by Adonai** [comment]
@CendioOssman thanks for a quick answer

**Comment by Adonai** [comment]
@CendioOssman , I have a small question then, is it possible to completely disable server-side cursor?
I mean, the one that's shaped like Adwaita and lags behind?

**Comment by CendioOssman** [comment]
That cursor is local as far as TigerVNC is concerned. There is no way to completely hide cursors in TigerVNC.

For Citrix, I have no idea if it has such an option.
