### ISSUE TITLE
Cannot transfer clipboard from Windows 10 to TigerVNC client

### ISSUE THREAD

**Issue by kingaj12** [TigerVNC/tigervnc#613]
Hi

I used to have a wonderful working vnc environment, but as of yesterday it stopped accepting entries from the clipboard.  In addition, in the server log I am getting the following messages (which I think are new)

    No VNC extension on display :2
    Xlib:  extension "RANDR" missing on display ":2".
    Window manager warning: Log level 32: could not find XKB extension.

The server is running on Ubuntu 14.04, the client is running on Windows 10.  Here is the xstartup file:

    #!/bin/sh

    export XKL_XMODMAP_DISABLE=1
    unset SESSION_MANAGER
    unset DBUS_SESSION_BUS_ADDRESS

    [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
    [ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
    xsetroot -solid grey
    #vncconfig -iconic &

    gnome-panel &
    #gnome-settings-daemon &
    metacity &
    nautilus &
    gnome-terminal &
    vncconfig -nowin -poll 250&

**Comment by CendioOssman** [comment]
Looks like you've started something other than TigerVNC as it has all three of those extensions.

Have you checked that something hasn't replaced your TigerVNC installation?

Are you starting things through `vncserver`?

**Comment by kingaj12** [comment]
Yes, you found the answer.  I reinstalled TigerVNC from

    https://bintray.com/tigervnc/stable/tigervnc/1.8.0#files/ubuntu-14.04LTS%2Famd64

and it works now.  Thanks for the quick response!
