### ISSUE TITLE
vncviewer display is lost when date/time changes on server's host

### ISSUE THREAD

**Issue by powellss** [TigerVNC/tigervnc#614]
The vncviewer stops updating its display, though keyboard and mouse input communication are still active, when the host's date-time is changed (one to many times) on the host running tigervnc-server (x0vncserver in this case).

Steps to reproduce:
1. Run x0vncserver on [host1]
2. Run vncviewer connected to x0vncserver from [host2].
3. Change the date repeatedly on [host1] using 'sudo date [MMDDhhmmCCYY]', for example by changing the year (CCYY) with each command.

Once the issue occurs and the display becomes 'stale', if you continue to change the date repeatedly, VNC will connect once again, and work successfully once more. Note that mouse and keyboard input work while the display is stale.

I have verified that this is not a connection issue across hosts by performing the same steps, but running viewer and server on [host1] and executing ssh -X 'vncviewer ...' from [host2]. In this case again, mouse and keyboard input are still working across SSH. However, the viewer (now X11 forwarded) still displays a stale image though its connection is now local to the x0vncserver / [host1].

I have also tested by connecting a RealVNC Viewer on Windows 7 to the very same x0vncserver on [host1] and the RealVNC Viewer does not exhibit the same issue.

Server version on RHEL 6.9 x86_64: 1.1.0-24
Viewer version(s) on RHEL 6.9 x86_64: 1.1.0-24 and 1.8.80-5

**Comment by feichashao** [comment]
See if debug log can give us more information?
`# vncviewer -Log *:file:100`
(client side)

Try only keeping the log of the problem moment.

**Comment by CendioOssman** [comment]
That server is absolutely ancient. I'm afraid I'm going to have to ask you to test on either 1.8.0 or the latest nightly build first. This issue might already be fixed.

**Comment by powellss** [comment]
Thanks guys. Updating to 1.8.0 el6 RPMs resolved this issue. Surprisingly though RedHat Customer Portal has 1.1 as "latest" for RHEL 6.9.
