### ISSUE TITLE
Menu key options seem to have been corrupted

### ISSUE THREAD

**Issue by fnJeff** [TigerVNC/tigervnc#615]
So I've been happily using version 1.8.80 of the java client for many months now after the fixes made for key mappings.  Unfortunately, I just stumbled on another one and subsequently noticed something else that seems wrong.  Just to make sure, this is the last version that Brian sent to me directly after fixing several of the key issues.  I have not downloaded anything since that version.

I was using a layout tool that required hitting F1 to perfom some function.  The TigerVNC menu popped up instead.  Ok, that's weird, because I had set my menu key to Pause/Break.  So I clicked on "Options..." to open that window and selected the Input tab.  The menu key says "Semicolon".  Hmmmm, that can't be right.  I remember specifically setting it to Pause/Break back when I was getting it up and running.

![image](https://user-images.githubusercontent.com/31246517/37605607-da5c1150-2b93-11e8-9ae4-043ae8c3fd71.png)

Clicking on the dropdown box, I see a bunch of rather strange keys listed as options that were definitely not there when I last looked, and can't be correct.  Something is clearly awry here...

![image](https://user-images.githubusercontent.com/31246517/37605684-05e81fda-2b94-11e8-93d5-710a3d52625c.png)

![image](https://user-images.githubusercontent.com/31246517/37605710-10736cf2-2b94-11e8-87d0-5c2c027c859d.png)

![image](https://user-images.githubusercontent.com/31246517/37605742-22d6464e-2b94-11e8-8475-a960c51de53e.png)

**Comment by bphinz** [comment]
Check the latest nightly, I'm pretty sure that I already fixed that

**Comment by fnJeff** [comment]
My apologies, you did. 20180308 doesn't have this issue.

Thanks, and sorry for the false alarm.

**Comment by bphinz** [comment]
No worries, your comments have always been helpful.
