### ISSUE TITLE
Java client login doesn't receive focus after clicking or hitting enter to connect

### ISSUE THREAD

**Issue by fnJeff** [TigerVNC/tigervnc#616]
I will admit, this is a minor nitpicky usage thing, so feel free to de-prioritize and grain-of-salt it if you want.

With the 20180308 nightly build, after clicking on Connect, the keyboard focus is somewhere other than in the text box where you would type your password or username.  Previously after clicking on Connect, you would immediately be able to type username and/or password without having to grab the mouse first.  Eg. click to open client, hit enter to connect, and start typing password.

As I said, it is just a usage annoyance and not a functional flaw.  Hoping it's a super easy thing to fix and just got missed while focus was on the secure/insecure stuff.

As always, appreciate the efforts you guys make!

**Comment by bphinz** [comment]
Fixed in b023b3c

**Comment by fnJeff** [comment]
Awesome, works perfectly, thanks!
