### ISSUE TITLE
How to resolve “Xtigervnc did not start up” error message?

### ISSUE THREAD

**Issue by redscience** [TigerVNC/tigervnc#623]
When I start vncserver, I see this error message: 
First:

`vncserver -kill :1
`
Second:

`vncserver :1 -geometry 1366x768 -depth 24
`
Output is:

```
vncserver: /usr/bin/Xtigervnc did not start up, please look into '/root/.vnc/win.localdomain:1.log' to determine the reason! -1
Killing Xtigervnc process ID 451... success!

```
And

`root@win:~# tail -l /root/.vnc/win.localdomain:1.log
`
Output is:

```
Xvnc TigerVNC 1.7.0 - built Dec  4 2017 09:39:19
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11905000, The X.Org Foundation


Mon Apr  2 04:40:32 2018
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5901
 vncext:      created VNC server for screen 0
```

Any suggestions?

**Comment by CendioOssman** [comment]
No response.

**Comment by raldone01** [comment]
I got the same message. :( How can I check where I got the package from? (Running debian 9)

**Comment by CendioOssman** [comment]
I would assume you just installed it using `apt` then. So it would be Debians package then, and not ours. I'm afraid you'll have to report the issue to Debian in that case since it is their modified script that is having problems.
