### ISSUE TITLE
[Windows] Any command line gives no output for “winvnc4.exe”, but works if there is a redirect

### ISSUE THREAD

**Issue by Kdmeizk** [TigerVNC/tigervnc#624]
Any command line gives no output for “winvnc4.exe”.
I tried with “vncviewer.exe -help” for example, it works by opening a console.

**EDIT:**
I just saw the output is written in the redirection, for example:
`winvnc4.exe -help > test.txt`
→ it works with the redirection

**Comment by CendioOssman** [comment]
Please see #319.
