### ISSUE TITLE
“-connect [<host[::port]>” in the file “winvnc.cxx”

### ISSUE THREAD

**Issue by Kdmeizk** [TigerVNC/tigervnc#626]
> “-connect [<host[::port]>” in the file “winvnc.cxx”

Is `::port` normal? It works with this syntax, `:port` works too.

**Comment by CendioOssman** [comment]
This is a syntax that is specific to VNC. A single `:` generally indicates which display, rather than port. However it only works that way for displays up to 100, so `:port` often works just as well as `::port`.
