### ISSUE TITLE
How to change IdleTimeout parameter for TigerVncServer?

### ISSUE THREAD

**Issue by Karan-nayyar** [TigerVNC/tigervnc#628]
The command Xvnc -Idletimeout 0 not working.Receiving Fatal Server Error.

I don't want the vnc session to get disconnected after some idle time.So want to set the parameter to value 0.

**Comment by CendioOssman** [comment]
Are you trying to change the setting of a running instance? If so you need to use `vncconfig`. You also need to configure `AllowOverride` on your Xvnc startup to allow changing that setting.

**Comment by Karan-nayyar** [comment]
When i am trying to configure AllowOverride ,I am receiving a unrecognized option.

**Comment by Karan-nayyar** [comment]
How can i configure AllowOverride,I am running this command -

Xvnc -AllowOverride IdleTimeout
 
Receiving an error:-
(EE) Server is already active for display 0
        If this server is no longer running, remove /tmp/.X0-lock
        and start again.
(EE)
