### ISSUE TITLE
How to change the setting of a running instance of TigerVnc Server?

### ISSUE THREAD

**Issue by Karan-nayyar** [TigerVNC/tigervnc#629]
#628 

How can i configure AllowOverride,I am running this command -

Xvnc -AllowOverride=IdleTimeout

Receiving an error:-
(EE) Server is already active for display 0
If this server is no longer running, remove /tmp/.X0-lock
and start again.
(EE)

**Comment by CendioOssman** [comment]
That command starts a new server instance. What you need to do is modify your existing startup. E.g. adding that argument to your call to `vncserver`, or add it to one of its configuration files. Please see the man page for details.
