### ISSUE TITLE
after so many years requesting, does tigervnc viewer support socks proxy?

### ISSUE THREAD

**Issue by moralrebuild** [TigerVNC/tigervnc#630]

**Comment by moralrebuild** [comment]
I switched to realvnc viewer and very glad to enjoy its feature rich experience. It's a shame to see as key tool, open source project has so huge gap to a commercial one.

**Comment by CendioOssman** [comment]
No, as you probably noticed we do not have any proxy support at the moment. TigerVNC may be a key tool for many, but that in itself doesn't mean we get more development resources.

**Comment by Joe-Kaze** [comment]
Can this be reopened as an enhancement request?

**Comment by CendioOssman** [comment]
We have a new template for feature requests. Please file a new issue so we can get a clean request.
