### ISSUE TITLE
Receiving a black screen after some Idle time on VncViewer

### ISSUE THREAD

**Issue by Karan-nayyar** [TigerVNC/tigervnc#631]
I have an issue regarding the black screen i am receiving on Vnc Viewer after making connection to the TigerVnc Server which is installed on the Debian OS. After some idle time of 30 minutes or  more,I am receiving a black screen.Is there any way of resolving this idle time issue?

**Comment by CendioOssman** [comment]
TigerVNC does not have any such blanking functionality. Isn't it just your screen saver?

**Comment by Karan-nayyar** [comment]
No I am sure it's not a screen saver.

**Comment by quanmltya** [comment]
Sometimes I get the same issue on my Fedora and Fedora server. On both KDE, Cinnamon and XFCE.

**Comment by CendioOssman** [comment]
Do you have a reliable way of reproducing it? Otherwise I'm afraid there isn't much we can do. :/

**Comment by MarkMielke** [comment]
Also check your log file. Blank screen can mean lots of things - including that your session manager exited (completely separate from VNC, which is apparently still up...).

**Comment by CendioOssman** [comment]
No response. Closing.
