### ISSUE TITLE
Connection info suggested is wrong when using interface=whatever

### ISSUE THREAD

**Issue by jblaine** [TigerVNC/tigervnc#633]
TigerVNC 1.8.0

`vncserver -interface=10.10.1.230` will output something like "New 'the-local-os-hostname:1 (root)' desktop is the-local-os-hostname:1" instead of _looking up_ the hostname of 10.10.1.230 and displaying that in the info.

**Comment by CendioOssman** [comment]
We might not want to do a reverse lookup because that would mean we assume some symmetry, but we should probably show the value specified for `interface` if given.

**Comment by ferdnyc** [comment]
I think there are three potential difficulties there:

1. `vncserver` doesn't ever see the `-interface` argument, currently it's passed to `Xvnc` unexamined.
1. In the case of unroutable addresses (like, in fact, `10.x.y.z`), they generally don't have hostnames that can be looked up. Some networks might serve reverse DNS for their unroutable subnets, but most won't.
1. If the interface address doesn't correspond to the value of `uname -n` (which is where vncserver gets the value of `$host`), seems like there would be bigger problems. The `$host` value is also what vncserver uses in the `Xauthority` file for the server (at line 295):

```perl
open(XAUTH, "|xauth -f $xauthorityFile source -");
print XAUTH "add $host:$displayNumber . $cookie\n";
print XAUTH "add $host/unix:$displayNumber . $cookie\n";
close(XAUTH);
```

**Comment by CendioOssman** [comment]
We no longer have the ability to show output like this since things are now running as a service. So there is nothing we can do here.
