### ISSUE TITLE
Windows and Icons go black

### ISSUE THREAD

**Issue by rmd6502** [TigerVNC/tigervnc#634]
Centos 7 server, MacOs High Sierra client, both running the latest tigervnc 1.8.0.

To reproduce, start vncserver as my login user on centos, run vncserver &lt;server&gt;:1 on macos. Open my home directory by double-clicking the Home icon.

Result: all my icons and windows go completely black, though the background stays the default blue.
![screen shot 2018-04-27 at 1 09 29 pm](https://user-images.githubusercontent.com/419223/39382979-649bf532-4a1c-11e8-9b0c-8495698ad49c.png)
![screen shot 2018-04-27 at 1 09 38 pm](https://user-images.githubusercontent.com/419223/39382981-64b45c80-4a1c-11e8-9480-3220aadcd756.png)

**Comment by rmd6502** [comment]
Note that once this happens, disconnecting and reconnecting from the mac doesn't help - I have to kill Xvnc and restart vncserver.

**Comment by CendioOssman** [comment]
Looks more like a bug in Xorg or Xfce at first glance.

What build are you using? Ours or CentOS'?

What happens if you continue using the session? E.g. dragging that window around, or opening another window.

**Comment by CendioOssman** [comment]
No response. Closing.
