### ISSUE TITLE
Huge cursor offset

### ISSUE THREAD

**Issue by RudyFiero** [TigerVNC/tigervnc#635]
I have a tablet Windows 10 tablet that I use for music, connected to my stereo. On the tablet the browser I am using is Microsoft Edge. I have installed the 32 bit EXE of Tiger VNC. The tablet screen is something like 1280x800.

 I am trying to control the tablet with my Windows 10 desktop machine. I run TigerVNC client 64 bit for Windows. 

I am getting a huge offset of the cursor position.  It seems the client's cursor position has to be up 200-300 pixels from the desired point on the server screen image. 

Is there an easy way to fix this? I'm not a programmer, not a computer guy. I'm somewhat technical (microcontroller programming) but just not in this area.

![tigervncoffset](https://user-images.githubusercontent.com/10385754/39401463-66f317b2-4b0b-11e8-867e-4a353597d533.png)

**Comment by Botts85** [comment]
See Ramcq's solution here at issue #480 

After doing that and a couple reboots it worked great for me.

The app you need to change permissions on is:

C:/Program Files/TigerVNC/winvnc4.exe  You'll want to apply it to all users if you're running as a service.

**Comment by RudyFiero** [comment]
I figured out what caused this. My tablet has a **Scale and layout** setting of 125%. When I change it to 100% then the client cursor position matches the tablet. Unfortunately the tablet is not usable at 100%.

@Botts85 
I tried the solution in #480 but it didn't make a difference. I don't understand it so I didn't try anything different that what was done there.

![scaling](https://user-images.githubusercontent.com/10385754/39409677-0fe774da-4bb1-11e8-9de2-7ab3dfaad724.png)

**Comment by Botts85** [comment]
Select Application in the drop box at the bottom of the window you screenshot.   Then change for all users. 

You should be able to keep scaling on.

**Comment by RudyFiero** [comment]
That did it. Thanks.

**Comment by calestyo** [comment]
Just for the records, if someone has this problem with the TigerVNC server running on a scaling Windows, one can also change the compatibility settings for `winvnc4.exe`. If one runs it as a service, it must probably be changed for "all users".
Compatibiltiy / Change settings for all users / High DPI Settings / DPI Scaling = Application

(Sorry if the translations are wrong, but I only have German Windows here)
