### ISSUE TITLE
Vncpasswd viewonly password using stdin

### ISSUE THREAD

**Issue by Waishon** [TigerVNC/tigervnc#640]
I'm trying to set a VNC password and a second viewonly password using the `vncpasswd` tool.
Using this command with the TigerVNC vncpasswd tool, the passwd file only contains the first password:
`echo -ne "12345678\n87654321" | vncpasswd -f > /root/.vnc/passwd`
```
od -x passwd 
0000000 e4f0 6431 c2f6 73e3
0000010
```

When I use the same command with the vncpasswd tool of TightVNC the result looks like that:
```
0000000 e4f0 6431 c2f6 73e3 1036 ba0a 9c4c 8b55
0000020
```
This file contains both passwords as expected. When I use the TigerVNC one using the interactive one everything works fine, but not when I use the stdin one.

It seems that vncpasswd is only reading the first line of stdin and ignoring the other one:
https://github.com/TigerVNC/tigervnc/blob/master/unix/vncpasswd/vncpasswd.cxx#L72

**Comment by CendioOssman** [comment]
Fixed in e58fcb99
