### ISSUE TITLE
Are there any plans to emulate RealVNC's "virtuald" utility?

### ISSUE THREAD

**Issue by jrop** [TigerVNC/tigervnc#646]
First of all, thanks for the amazing software!

My question relates to [this feature, included with RealVNC](https://www.realvnc.com/en/connect/docs/man/vncserver-virtuald.html).  In short, VirtualD listens on 5999 for incoming connections and, after authentication, automatically starts/stops vncserver instances.

My question is: is any feature like this planned for TigerVNC?

Thanks again!

**Comment by CendioOssman** [comment]
We're glad you like it. :)

Unfortunately nothing like that is currently in the plans. It would be a major new protocol and service, and we have our hands full maintaining what we have.
