### ISSUE TITLE
PlatformPixelBuffer.h build fails

### ISSUE THREAD

**Issue by gitcnd** [TigerVNC/tigervnc#651]
No such file Xrender.h

In file included from /root/tigervnc-1.8.0/vncviewer/PlatformPixelBuffer.h:36,
                 from /root/tigervnc-1.8.0/vncviewer/CConn.cxx:49:
/root/tigervnc-1.8.0/vncviewer/Surface.h:28:36: error: X11/extensions/Xrender.h: No such file or directory
In file included from /root/tigervnc-1.8.0/vncviewer/PlatformPixelBuffer.h:36,
                 from /root/tigervnc-1.8.0/vncviewer/CConn.cxx:49:
/root/tigervnc-1.8.0/vncviewer/Surface.h:65: error: ‘Picture’ does not name a type
/root/tigervnc-1.8.0/vncviewer/Surface.h:66: error: ISO C++ forbids declaration of ‘XRenderPictFormat’ with no type
/root/tigervnc-1.8.0/vncviewer/Surface.h:66: error: expected ‘;’ before ‘*’ token
make[2]: *** [vncviewer/CMakeFiles/vncviewer.dir/CConn.cxx.o] Error 1
make[1]: *** [vncviewer/CMakeFiles/vncviewer.dir/all] Error 2
make: *** [all] Error 2
[root@localhost tigervnc-1.8.0]# 
[root@localhost tigervnc-1.8.0]# locate X11/extensions 
/usr/include/X11/extensions
/usr/include/X11/extensions/EVI.h
/usr/include/X11/extensions/EVIproto.h
/usr/include/X11/extensions/MITMisc.h
/usr/include/X11/extensions/XEVI.h
/usr/include/X11/extensions/XI.h
/usr/include/X11/extensions/XI2.h
/usr/include/X11/extensions/XI2proto.h
/usr/include/X11/extensions/XIproto.h
/usr/include/X11/extensions/XKB.h
/usr/include/X11/extensions/XKBgeom.h
/usr/include/X11/extensions/XKBproto.h
/usr/include/X11/extensions/XKBsrv.h
/usr/include/X11/extensions/XKBstr.h
/usr/include/X11/extensions/XLbx.h
/usr/include/X11/extensions/XResproto.h
/usr/include/X11/extensions/XShm.h
/usr/include/X11/extensions/Xag.h
/usr/include/X11/extensions/Xcup.h
/usr/include/X11/extensions/Xdamage.h
/usr/include/X11/extensions/Xdbe.h
/usr/include/X11/extensions/Xeviestr.h
/usr/include/X11/extensions/Xext.h
/usr/include/X11/extensions/Xfixes.h
/usr/include/X11/extensions/Xge.h
/usr/include/X11/extensions/Xv.h
/usr/include/X11/extensions/XvMC.h
/usr/include/X11/extensions/XvMCproto.h
/usr/include/X11/extensions/Xvproto.h
/usr/include/X11/extensions/ag.h
/usr/include/X11/extensions/agproto.h
/usr/include/X11/extensions/bigreqsproto.h
/usr/include/X11/extensions/bigreqstr.h
/usr/include/X11/extensions/composite.h
/usr/include/X11/extensions/compositeproto.h
/usr/include/X11/extensions/cup.h
/usr/include/X11/extensions/cupproto.h
/usr/include/X11/extensions/damageproto.h
/usr/include/X11/extensions/damagewire.h
/usr/include/X11/extensions/dbe.h
/usr/include/X11/extensions/dbeproto.h
/usr/include/X11/extensions/dmx.h
/usr/include/X11/extensions/dmxproto.h
/usr/include/X11/extensions/dpms.h
/usr/include/X11/extensions/dpmsconst.h
/usr/include/X11/extensions/dpmsproto.h
/usr/include/X11/extensions/dri2proto.h
/usr/include/X11/extensions/dri2tokens.h
/usr/include/X11/extensions/dri3proto.h
/usr/include/X11/extensions/evieproto.h
/usr/include/X11/extensions/extutil.h
/usr/include/X11/extensions/ge.h
/usr/include/X11/extensions/geproto.h
/usr/include/X11/extensions/lbx.h
/usr/include/X11/extensions/lbxproto.h
/usr/include/X11/extensions/mitmiscconst.h
/usr/include/X11/extensions/mitmiscproto.h
/usr/include/X11/extensions/multibuf.h
/usr/include/X11/extensions/multibufconst.h
/usr/include/X11/extensions/multibufproto.h
/usr/include/X11/extensions/panoramiXproto.h
/usr/include/X11/extensions/presentproto.h
/usr/include/X11/extensions/presenttokens.h
/usr/include/X11/extensions/randr.h
/usr/include/X11/extensions/randrproto.h
/usr/include/X11/extensions/recordconst.h
/usr/include/X11/extensions/recordproto.h
/usr/include/X11/extensions/recordstr.h
/usr/include/X11/extensions/render.h
/usr/include/X11/extensions/renderproto.h
/usr/include/X11/extensions/saver.h
/usr/include/X11/extensions/saverproto.h
/usr/include/X11/extensions/secur.h
/usr/include/X11/extensions/security.h
/usr/include/X11/extensions/securproto.h
/usr/include/X11/extensions/shape.h
/usr/include/X11/extensions/shapeconst.h
/usr/include/X11/extensions/shapeproto.h
/usr/include/X11/extensions/shapestr.h
/usr/include/X11/extensions/shm.h
/usr/include/X11/extensions/shmproto.h
/usr/include/X11/extensions/shmstr.h
/usr/include/X11/extensions/sync.h
/usr/include/X11/extensions/syncconst.h
/usr/include/X11/extensions/syncproto.h
/usr/include/X11/extensions/syncstr.h
/usr/include/X11/extensions/vldXvMC.h
/usr/include/X11/extensions/xcmiscproto.h
/usr/include/X11/extensions/xcmiscstr.h
/usr/include/X11/extensions/xf86bigfont.h
/usr/include/X11/extensions/xf86bigfproto.h
/usr/include/X11/extensions/xf86bigfstr.h
/usr/include/X11/extensions/xf86dga.h
/usr/include/X11/extensions/xf86dga1const.h
/usr/include/X11/extensions/xf86dga1proto.h
/usr/include/X11/extensions/xf86dga1str.h
/usr/include/X11/extensions/xf86dgaconst.h
/usr/include/X11/extensions/xf86dgaproto.h
/usr/include/X11/extensions/xf86dgastr.h
/usr/include/X11/extensions/xf86misc.h
/usr/include/X11/extensions/xf86mscstr.h
/usr/include/X11/extensions/xf86vm.h
/usr/include/X11/extensions/xf86vmode.h
/usr/include/X11/extensions/xf86vmproto.h
/usr/include/X11/extensions/xf86vmstr.h
/usr/include/X11/extensions/xfixesproto.h
/usr/include/X11/extensions/xfixeswire.h
/usr/include/X11/extensions/xtestconst.h
/usr/include/X11/extensions/xtestext1.h
/usr/include/X11/extensions/xtestext1const.h
/usr/include/X11/extensions/xtestext1proto.h
/usr/include/X11/extensions/xtestproto.h
[root@localhost tigervnc-1.8.0]# cat /etc/issue
CentOS release 6.9 (Final)
Kernel \r on an \m

**Comment by CendioOssman** [comment]
I'm afraid Xrender is required, so please install libXrender-devel.
