### ISSUE TITLE
Crash in Congestion.cxx after position wrap around

### ISSUE THREAD

**Issue by astrand** [TigerVNC/tigervnc#652]
Originally reported at: https://github.com/x11clone/x11clone/issues/10

The new congestion code per https://github.com/TigerVNC/tigervnc/pull/442 does not handle the case when the bytestream position wraps around. In some cases, this gives an assert of type:

Congestion.cxx:280: int rfb::Congestion::getUncongestedETA(): Assertion `iter != pings.end()' failed.
Aborted (core dumped)

**Comment by lprylli** [comment]
I believe the fix in https://github.com/TigerVNC/tigervnc/commit/c05fba745ee42661b54bb4454b270e43232c1b is partly incorrect, I still get a crash like the original on tigervnc compiled on FreeBSD with clang.

Looking at coredump and disassembly of crash, it seems clang occasionally compiles the isAfter() statement:
 ` (int)a - (int)b > 0`
like if it was:
 ` (int)a > (int)b`

which means the wrapping case is still not handled correctly. I think clang is allowed to do that as per C standard, the result of overflow on signed integers is undefined and in the absence of overflow,` (int)a - (int)b > 0`  is equivalent to ` (int)a > (int)b `

So I would suggest isAfter to be changed instead to something with well-defined C behavior:
`(int)(a - b) > 0 `

Here is a snippet of code showing the problem with current definition for isAfter, on both freebsd/linux C or C++, the result of compiling/executing that snippet with "clang -O2 -fno-inline t.c":
```
0
1
1
```
(while gcc gives `1 1 1`).

```
// clang -O2 -fno-inline t.c
#include <stdbool.h>
#include <stdio.h>

bool
is_greater(unsigned x, unsigned y)
{
  return (int)x - (int)y > 0;
}

void
foo(unsigned x, unsigned y)
{
  printf("%d\n", is_greater(x,y));
  printf("%d\n", (int)x - (int)y > 0);
  printf("%d\n", (int)(x - y) > 0);
}

int
main()
{
  foo(0x80000001, 0x7fff0000);
}
```
