### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by Waishon** [TigerVNC/tigervnc#657]
Hi,

do you've a kind of release schedule for TigerVNC? The last release is already one year old and I'd like to use the newest features and bugfixes of TigerVNC. Of course I'm able to compile it myself, but it would be easier for most admins to just use the binarys. 

Do you've any build system that builds the binarys every night or when do you plan to publish the next release?

**Comment by CendioOssman** [comment]
> do you've a kind of release schedule for TigerVNC? The last release is already one year old and I'd like to use the newest features and bugfixes of TigerVNC. Of course I'm able to compile it myself, but it would be easier for most admins to just use the binarys.
> 

Not really. It is more ad-hoc when there's been enough work and someone has time to do a release. That said, I was hoping to get a beta out next week.

> Do you've any build system that builds the binarys every night or when do you plan to publish the next release?

There is a link to nightly builds on the main page. Please have a look there.
