### ISSUE TITLE
Server does not create ~/.vnc/xstartup config file

### ISSUE THREAD

**Issue by fenarinarsa** [TigerVNC/tigervnc#659]
On Debian 9.4 and Ubuntu 18.04, tigervnc server does not create ~/.vnc/xstartup on the first launch, resulting in a non-functional server.

Another server must be installed before for this file to exist.

Tested with tigervnc 1.17 (the version avalaible on debian repos)

**Comment by CendioOssman** [comment]
How are you starting the server? And what do you mean when you say another server must be installed? What other server?

**Comment by CendioOssman** [comment]
Alright, so the original issue is then some bug in Ubuntu's packaging and should be resolved once they update.

If you have more problems then please open separate issues for those. Note though that first make sure you aren't logged in locally when you start vncserver. Most systems don't support multiple graphical sessions for the same user.

**Comment by Eccenux** [comment]
Workaround is to create `xstartup` file yourself.

Side note: You also need a separate user for vnc! And as you cannot be logged into X-session you also should have `ssh` (and connect remotely when configuring the server). None of this is obvious as you need none of that on e.g. Windows. For me it seems like TrigerVnc is not communicating problems properly and it is not really Ubuntu issue. Just saying (don't mean to be rude).

So... Assuming you have Xfce4 the file (`~/.vnc/xstartup`) can be as simple as this:
```bash
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec startxfce4
```

After creating the file you might want to reboot (mainly to make sure nobody is logged in i.e. no X-session are active).

Then you login via ssh with your vnc user. And as vnc user you run something like:
`vncserver -localhost no -geometry 800x600 -depth 24`

And then you should be able to connect via TigerVNC viewer from remote computers.

PS: I know this is old issue, but I'm here from Google ;-).

**Comment by CendioOssman** [comment]
> Side note: You also need a separate user for vnc! And as you cannot be logged into X-session you also should have `ssh` (and connect remotely when configuring the server). None of this is obvious as you need none of that on e.g. Windows. For me it seems like TrigerVnc is not communicating problems properly and it is not really Ubuntu issue. Just saying (don't mean to be rude).

I'm afraid those are limitations of Ubuntu, not TigerVNC. You have to remember that we are pretty much just a display server and most of the session comes from the OS.

They are fairly common limitations though, and it would be nice to have some good guides here. But our time is limited so it's not something we've been able to keep fully track of.
