### ISSUE TITLE
Keys do not autorepeat with x11vnc server

### ISSUE THREAD

**Issue by nsinik** [TigerVNC/tigervnc#66]
Keys do not autorepeat when using tigervnc viewer 1.3.1-6.3.1(opensuse 13.2) with x11vnc 0.9.13-7.1.2.  
Tightvnc works OK.
The issue is reproducible. 
Regards
Nick Sinik

**Comment by yingshaoxo** [comment]
But they still keep that bug alive.

Can you guys fix it?

**Comment by CendioOssman** [comment]
Sorry, no. It would break things for other servers.

**Comment by Martii** [comment]
For posterity here... `x11vnc -repeat` may help... does here so far on multiple remotes.

**Comment by StefanHoutzager** [comment]
Indeed command=x11vnc -repeat -forever -display :1  proved to be the solution, one of your engineers helped me out before. See https://github.com/StefanHoutzager/elixir-dev-anywhere-docker/commit/4305e1a9d62dba53ef0a699209d4ef213a8a481e#diff-8466346a9df6610ab4098566eeb71681

**Comment by cavernico** [comment]
> For posterity here... `x11vnc -repeat` may help... does here so far on multiple remotes.

works fine here

**Comment by Kamilake** [comment]
I can't believe that option isn't the default

**Comment by JustRedTTG** [comment]
Is there a way to configure this or set it in the GUI?

**Comment by tux2bsd** [comment]
> I can't believe that option isn't the default

Mind-blowing isn't it...
