### ISSUE TITLE
vncviewer fullscreen mode freezes tigervnc on xorg-server-1.20.0

### ISSUE THREAD

**Issue by apocalyptech** [TigerVNC/tigervnc#660]
Hello - I'm having problems with tigervnc-1.8.0's vncviewer, when connecting to an x11vnc instance on another machine.  It works fine until I go into fullscreen mode, at which time I just get a blank grey screen which seems impervious to input.  At that point I have to hop out to a text console or SSH in remotely to kill the vncviewer process, which gives me control of the X session again.  This has been working fine for many years now, so *some* recentish update on my system (within the last three months or so) triggered this.  Unfortunately I don't use vncviewer too often, so I don't have a tighter timeline than that, or what update in particular might have caused the issue.

I *have* verified that two other VNC clients can connect to the x11vnc instance just fine, so I don't *think* that the problem is on x11vnc's side.  I'm running Arch linux on both machines.  The machine running vncviewer is running xorg-server 1.20.0 and Mesa 18.1.1 (Intel graphics); I'm not sure what other bits of software version info might help.

The initial connection, prior to entering fullscreen mode (in the simplest case here, doing away with SSH tunnelling and the like for the sake of simplicity) is:

```
$ vncviewer -Log '*:stderr:100' arrakis

TigerVNC Viewer 64-bit v1.8.0
Built on: 2018-01-25 12:23
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Sun Jun 10 22:09:41 2018
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to arrakis [10.42.0.2] port 5900
 CConn:       connected to host arrakis port 5900
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: Server offers security type None(1)
 CConnection: Choosing security type None(1)
 CConnection: processing security message
 CConnection: processing security result message
 CConnection: processing security result message
 CConnection: Authentication success!
 CConnection: reading server initialisation
 CConnection: initialisation done
 PlatformPixelBuffer: Using shared memory XImage
 DesktopWindow: Adjusting window size to avoid accidental full screen request
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Using Tight encoding
```

Then when I kill the process after trying to go into fullscreen mode, this is the rest of the output:

```
Sun Jun 10 22:09:49 2018
 Config:      set FullScreen(Bool) to 1

Sun Jun 10 22:09:53 2018
 Viewport:    Key pressed: 0x0040 => XK_Alt_L (0xffe9)
 Viewport:    Key released: 0x0040 => XK_Alt_L (0xffe9)
 Viewport:    Key pressed: 0x0025 => XK_Control_L (0xffe3)
 Viewport:    Key released: 0x0025 => XK_Control_L (0xffe3)

Sun Jun 10 22:09:54 2018
 Viewport:    Unexpected release of key code 37
 Viewport:    Unexpected release of key code 64
 Viewport:    Unexpected release of key code 68

Sun Jun 10 22:09:55 2018
 main:        Termination signal 15 has been received. TigerVNC Viewer will now
              exit.
```

Definitely let me know if I'm leaving out important information here!

**Comment by Gusar321** [comment]
It's xorg-server 1.20. The fltk viewer doesn't like it. Any other viewer will work, and downgrading xorg-server to 1.19 will make the fltk viewer work again.

**Comment by apocalyptech** [comment]
Ohhhh, okay.  I see the most recent github commits are even about that very thing.  Awesome, thanks for the info!  I'll close this out myself.

**Comment by Gusar321** [comment]
The latest github commit adds xorg-server-1.20 support to the server, it does not affect the viewer. The viewer is still broken. The question is, is the problem in X, in fltk or in the viewer? I don't really know how to find out.

**Comment by CendioOssman** [comment]
I can reproduce this using a virtual Fedora 29 machine, so this seems to be something generic.

**Comment by CendioOssman** [comment]
Which desktop environment are you using? I'm seeing the issue with GNOME here, but not with Xfce.

**Comment by CendioOssman** [comment]
The issue has something to do with keyboard grab. It gets in to an infinite loop with focus and grab being constantly toggled. I suspect this commit has something to do with it:

https://cgit.freedesktop.org/xorg/xserver/commit/?id=c67f2eac56518163981af59f5accb7c79bc00f6a

**Comment by CendioOssman** [comment]
Filed a bug with Xorg:

https://bugs.freedesktop.org/show_bug.cgi?id=106895
