### ISSUE TITLE
Start TigerVNC server with spesific resolution

### ISSUE THREAD

**Issue by mervekaya** [TigerVNC/tigervnc#666]
Hello,
I want to start tigervnc server with specific resolution in Windows Server 2012. Something like that : `.\winvnc.exe -geometry 1024x768` . I make a lot of research on google but i couldn't find it. Is there a such command / parameter or there is another way ?

**Comment by CendioOssman** [comment]
I'm afraid WinVNC does not have such options, and I don't think it is something that really should be part of it. WinVNC shows a regular Windows desktop, so it is up to the system's tools to change such things. Perhaps there is some way to do it via PowerShell?
