### ISSUE TITLE
copy paste garbage

### ISSUE THREAD

**Issue by deepakguptahp** [TigerVNC/tigervnc#667]
When I do a copy paste in tigervnc either in same terminal or between two terminals I get some garbage values along with data.

For e.g. if i am copying "TEXT"
when I paste it becomes "0~TEXT1~"

I am using TigerVNC version 1.8 on mac

please help. It's very irritating.

**Comment by CendioOssman** [comment]
That's not something we've seen before.

Is this between two terminals inside the VNC session?

What server are you using?

**Comment by CendioOssman** [comment]
No response.
