### ISSUE TITLE
Variable JPEG Quality

### ISSUE THREAD

**Issue by mmcclaskey** [TigerVNC/tigervnc#672]
I know it is outside the specifications, however, I would like to know if it is possible to have a variable JPEG quality based on the rate of change. When change rate slows back down the a high quality block will be sent. It would have to be on a block by block basis, otherwise an ad on a web page would result in the entire screen looking bad. I'm looking for ways to increase efficiency in order to provide scalability in an a large deployment. Any ideas would be greatly appreciated. I'm willing to pay a bounty for ideas that can work towards more scalability from a network load point of view (bandwidth usage). I know a lot of work in the community has already gone into this issue, however, I believe more efficiency may be possible.

**Comment by clbr** [comment]
I'm currently investigating, but I believe dynamic jpeg quality is relatively easy to implement, and would work in all existing VNC viewers that support jpeg (tight). It should have nice b/w savings indeed.

If targeting various existing viewers, it would probably be best as a server option, something like "-dynamicJpeg min,max", which would enable it for all clients that request the tight encoding.

If you have cpu to burn, and can also modify the viewers, there's a few things possible (in order of efficiency and cpu usage):
- dropbox lepton can recompress jpeg losslessly, saving about 22%
- webp about halves the size at the same quality
- av1's image format beats webp at about 20%, meaning 60% over jpeg

These all tend to be cpu-heavy though, especially av1 as it hasn't been optimized yet. You should try each of them on your target server, encode a full-screen image, measure how much cpu it took, and multiply by the number of clients you expect. That'd be a reasonable approximation of the maximum cpu load.

**Comment by mmcclaskey** [comment]
Personally, I am interested in noVNC for the client. Unfortunately that limits what can be done on the client side. I have tested JPEG2000 using a javascript decoder and writing to a canvas, the performance was horrible. JPEG2000 is natively supported in Safari only. Webp is supported natively in Chrome base browsers, so performance might be good there. JPEG XR is supported in IE and Edge and is similar to JPEG2000. AV1 might be an option, I haven't previously considered that, however, I did read this article which seems to indicate that using video encoding for vnc has its downfalls as well...

https://turbovnc.org/About/H264

All that being said, probably the easy kill would be dynamic jpeg quality for round 1. I'm not sure if the tigerVNC community would desire supporting JPEG2000, Webp, and JPEG-XR to support all the native browser implementations. However, if the desire was there I post a separate bounty for that.

**Comment by mmcclaskey** [comment]
This might be a good long term option (browser support coming in the next few years across all major browsers), but I'm hoping the dynamic jpeg quality is an easier short-term kill. 

This is a nice tool for comparing the options.
https://wyohknott.github.io/image-formats-comparison/#bath-from-alexandra-park&webm=s&webm=m

**Comment by clbr** [comment]
I have a prototype implementation running. Giving it the full quality range, and running a web browser in the VNC server with a sample page with two animated banners, the JPEG numbers were improved by 12%. Shouldn't take more than a couple days to clean it up and run various benchmarks.

**Comment by CendioOssman** [comment]
Automatic encoding selection is something we've talked about for some time. Unfortunately it is not trivial to do. However we are slowly working towards it. One piece that was recently added is the "repair" of overly compressed parts of the screen. That takes care of the cleanup part. But we still need to figure out a good logic for the compression step.
