### ISSUE TITLE
Disable "press F8" message at launch?

### ISSUE THREAD

**Issue by ferdnyc** [TigerVNC/tigervnc#678]
Is there any way to turn off the "Press F8 to exit fullscreen" message that now appears over the start of every tigervnc session? I _know_ this by now, and that message showing up every time gets in the way of me seeing what I need to on the remote screen. I checked the man page, but there didn't seem to be any information. A web search was also fruitless.

I did find this [RHEL bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1491608) from last year asking the same thing, but it never got any response over there.

**Comment by ferdnyc** [comment]
Yeah, I'd say something like "Maybe show it the first 4 times", or whatever, but then you end up with all sorts of questions about where to keep that state, whether it should be 4x for each different remote host/display, whether the 4x counter should reset if the menu key is changed, etc...?

How about this: What if the popup was only shown when TigerVNC is fullscreened, at the time it enters fullscreen? If that's at the start of the session, great, it works the same as now. If the switch to fullscreen occurs later in the session, hold off and only show the message then. So, more like the "Press Esc to exit fullscreen" type popups that Chrome and Firefox show, whenever the browser switches into fullscreen mode.

If I launch TigerVNC in window mode and I never go to fullscreen, it's not really critical to show me the F8 message at all. I don't have to worry about the menu. It's not like I'm going to end up "trapped" in the session, all I need to do to exit is just close the window.

**Comment by CendioOssman** [comment]
Being trapped is one aspect. But we also want people to find this menu even if they start out in windowed mode. So I don't think that is a good option.

Perhaps we can just make it less intrusive. The browsers seem to have similar timeouts (3s in Firefox, 4s in Chrome). Chrome has fairly small popup though. Perhaps just reducing the size of it is enough:

```diff
diff --git a/vncviewer/DesktopWindow.cxx b/vncviewer/DesktopWindow.cxx
index e8750b4e..d5edfb87 100644
--- a/vncviewer/DesktopWindow.cxx
+++ b/vncviewer/DesktopWindow.cxx
@@ -498,6 +498,9 @@ void DesktopWindow::menuOverlay(void* data)
 
 void DesktopWindow::setOverlay(const char* text, ...)
 {
+  const Fl_Fontsize fontsize = 16;
+  const int margin = 10;
+
   va_list ap;
   char textbuf[1024];
 
@@ -528,22 +531,22 @@ void DesktopWindow::setOverlay(const char* text, ...)
     fl_gc = XDefaultGC(fl_display, 0);
 #endif
 
-  fl_font(FL_HELVETICA, FL_NORMAL_SIZE * 2);
+  fl_font(FL_HELVETICA, fontsize);
   w = 0;
   fl_measure(textbuf, w, h);
 
   // Margins
-  w += 80;
-  h += 40;
+  w += margin * 2 * 2;
+  h += margin * 2;
 
   surface = new Fl_Image_Surface(w, h);
   surface->set_current();
 
   fl_rectf(0, 0, w, h, 0, 0, 0);
 
-  fl_font(FL_HELVETICA, FL_NORMAL_SIZE * 2);
+  fl_font(FL_HELVETICA, fontsize);
   fl_color(FL_WHITE);
-  fl_draw(textbuf, 40, 20 + fl_height() - fl_descent());
+  fl_draw(textbuf, 0, 0, w, h, FL_ALIGN_CENTER);
 
   imageText = surface->image();
   delete surface;
```

**Comment by ferdnyc** [comment]
The smaller message is a lot more unobtrusive, and actually wouldn't obscure the bits of the remote display that I need to see, unlike the current (enormous) one.

However, since I already had the code in front of me to apply that patch, I couldn't resist and... well, see PR #683. (BTW, can I just compliment everyone involved in TigerVNC on your code? It is clean, organized, and a joy to read, which made adding that parameter child's play.)

Entirely your call — if you feel like that option is the wrong direction and decide not to merge, I won't be insulted. And I do think the smaller message is a good change, either way.

**Comment by CendioOssman** [comment]
Adjusted in 9fbf94db8b85eeee1d233089243a0da71f5b544f.

**Comment by jbenc** [comment]
Sorry for the late follow up and thanks for decreasing the message size.

The problem is also the placement of the message. When using tigervnc to connect to a VM with a typical Linux installation, it covers exactly the grub boot menu. And with grub menu having a timeout similar to the timeout of the F8 message, it's very annoying when one needs to select a kernel often, which is exactly what I do when using kvm+tigervnc for the kernel development. It's slightly better with the smaller message but it still covers 3 menu items.

I'd really like to see an option to remove the message completely. I start tigervnc several times a day, I *know* what F8 does. By all means, let the message be on by default for the occasional users, but an option for hiding it for daily users would be very welcome. Failing that, could the message at least be shifted down to not cover the grub boot menu?

Thanks!

**Comment by CendioOssman** [comment]
I'd really like to avoid more options, but I'm open to suggestions. E.g. only show it every x days. Not sure how we would implement it though.

Could you include a screen shot of how the placement ends up right now?

**Comment by jbenc** [comment]
![screenshot](https://user-images.githubusercontent.com/5006725/51272353-31bbf300-19ca-11e9-90cb-e5b2b354b480.png)
![screenshot2](https://user-images.githubusercontent.com/5006725/51272354-32548980-19ca-11e9-8184-489dbf2bcdf4.png)

**Comment by ferdnyc** [comment]
Ouch, wow. That... is extremely unfortunate. It wasn't nearly as big an issue for me, I just found the message distracting. But that's kind of a real problem.

**Comment by ferdnyc** [comment]
@sterbeN27 With the caveat that you _won't be able_ to press <kbd>F8</kbd> to open the context menu, of course... (IOW, actual functionality is lost by disabling the menu key. It doesn't _just_ disable the message. It disables the feature the message is reminding you of.)

Still, a clever workaround for those who are sure they'll never need the <kbd>F8</kbd> menu.
