### ISSUE TITLE
tigervnc-1.9.0/common/rfb/VNCSConnectionST.cxx:904: poor error checking

### ISSUE THREAD

**Issue by dcb314** [TigerVNC/tigervnc#680]
tigervnc-1.9.0/common/rfb/VNCSConnectionST.cxx:904]: (style) Unsigned variable 'eta' can't be negative so it is unnecessary to test it.

Source code is

  eta = congestion.getUncongestedETA();
  if (eta >= 0)
    congestionTimer.start(eta);

but getUncongestedETA returns int and eta is unsigned. Suggest sanity
check return value before putting it into an int.

**Comment by CendioOssman** [comment]
Ah. Quite right. That's a bug. Have you seen any practical effects from this?

It's fixed in ce261817682a9d3e842d497a1a0507fdda0f1b5f at least.
