### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Neofox13** [TigerVNC/tigervnc#682]
Finally created a Github account just to say thanks for this and I'll be providing a linkback (from my website) soon. :) I'm a vet going to college for Business Management now and decided a part of it will require me to go from shared hosting to what I'm doing now which is a cloud-based solution. Previously I didn't have anyway to interface with Ubuntu (that I knew of?)

This solution has helped me so much. Not sure if "Issues" is the right place for a thank-you if not, feel free to move the message. Thanks again.

EDIT: Apparently my account is flagged now. :( I'm not a shpammer! Lol.

**Comment by CendioOssman** [comment]
Thank you, we're glad you like TigerVNC. :)

(and no, Issues is probably not the best place. In the future we have the tigervnc-users discussion list for such things)
