### ISSUE TITLE
Unable to save server x509 certificates

### ISSUE THREAD

**Issue by kim0** [TigerVNC/tigervnc#686]
After hitting untrusted letsencrypt root CA bug (#685). The warning message asks me to "save" this certificate. I click yes to save it. However, every time I reconnect, I still get asked. I have found the log message saying `Saved server certificates don't match`, while seemingly the file `~/.vnc/x509_savedcerts.pem` contains repeated copies of the same certificate saved multiple times.

I'm guessing this x509 code path isn't well excercised :)

**Comment by CendioOssman** [comment]
Hmm... Seems to work fine here. Could you share the entire log output?

**Comment by CendioOssman** [comment]
No response. Closing.
