### ISSUE TITLE
Shift-tab not working

### ISSUE THREAD

**Issue by RetroSven** [TigerVNC/tigervnc#687]
Windows 10 x64 tiger vncviewer, Linux Ubuntu 14.05 x64 tiger x0vncserver

Shift-tab (which apparently maps to ISO_Left_Tab) is being swallowed somehow by x0vncserver

en_US keyboards on both sides

Please let me know if you need any additional information
Thanks!

Oh, v1.9.0 on both sides also

**Comment by CendioOssman** [comment]
Indeed. Shift+Tab is handled a bit special in the RFB protocol, and we are not properly compensating for this in x0vncserver. :/

**Comment by CendioOssman** [comment]
Should be fixed in 9ee59ecb78d47513ce5e2a365e57a931449998e2.

**Comment by RetroSven** [comment]
Thanks very much!
