### ISSUE TITLE
Prefer intltool-merge over msgfmt for generating Desktop Entry files

### ISSUE THREAD

**Issue by awilfox** [TigerVNC/tigervnc#688]
Hi there.

I'm the project lead of Adélie Linux, a newer Linux distribution focused on speed, stability, and minimal resource usage.  We use [gettext-tiny](https://github.com/sabotage-linux/gettext-tiny) instead of GNU gettext, and right now gettext-tiny [does not support generating Desktop Entry files](https://github.com/sabotage-linux/gettext-tiny/issues/36).  I was therefore wondering if a patch would be accepted to change the CMake code to check `IF(INTLTOOL_MERGE_EXECUTABLE)` _before_ using `msgfmt` would be acceptable?

The patch would look something like [what we're shipping right now in Adélie](https://code.foxkit.us/adelie/packages/blob/master/user/tigervnc/use-intltool.patch) and I would be more than happy to open a PR if that is acceptable.

Thank you.

**Comment by CendioOssman** [comment]
The intltool method is a bit hacky, so I don't think it will be a good idea to have that as the preferred one.

But gettext-tiny seems to be on version 0.2.0 right now. So it shouldn't be be going down the gettext path. Have you debugged why this is happening?

**Comment by awilfox** [comment]
As [the linked issue explains](https://github.com/sabotage-linux/gettext-tiny/issues/36), there is no intention of supporting templating upstream beyond a stub.  They feel this is something maintainers should be doing in release tarballs, not something that should be done during the build on every machine/distro.

**Comment by CendioOssman** [comment]
That has its own problems, so that's not really a good option.

But my point was that it shouldn't be trying to use gettext in this case since 0.2.0 is older than the 0.89 requirement. So something must be going wrong there.

**Comment by awilfox** [comment]
```
awilcox on gwyn /usr/src/packages/user $ msgmerge --version
msgmerge (GNU gettext-tools compatible) 99.9999.9999
```

This is necessary because all KDE packages will fail to build if gettext is below 0.18.

**Comment by CendioOssman** [comment]
Ah, I see. That's probably not a very good approach by gettext-tiny if they want to be able to add more stuff in the future. How are build systems supposed to test for features in that case?

I'm afraid we don't want to change the order of things here. If you can come up with a better test case that can detect that msgmerge doesn't support the necessary flags then that would be welcome. Otherwise I don't think there is much we can do here.
