### ISSUE TITLE
tigervnc 1.9.0: Regression pasting into VNC window

### ISSUE THREAD

**Issue by github-cygwin** [TigerVNC/tigervnc#689]
vncviewer from tigervnc-1.9.0 introduces the following regression:

  So far it was possible to paste the primary selection from any client
  window into the VNC window by just pressing the middle mouse button.
  Pasting and focussing the VNC window was a single click.

  With 1.9.0, this doesn't work anymore.  The first press of the
  middle mouse button does not copy the current primary selection
  over to the VNC server.  Instead, the *previous* selection on
  the server side is pasted.  If there's nothing in the server-side
  primary selection buffer, nothing is pasted.

  Only the *second* press of the middle mouse button copies over
  the primary selection and pastes the desired text.

  This is very destructive behaviour for the workflow.

  Steps to Reproduce:

  1. Open a VNC window to some host
  2. Create a primary selection in any non-VNC client window (double-click
     left mouse button)
  3. Try to paste this selection into the VNC window by pressing the
     middle mouse button.
  4. Observe how the selection is not pasted.
  5. Press the middle mouse button again.
  6. Observe that the selection is now pasted, belatedly.

  Thanks for any help,
  Corinna

**Comment by github-cygwin** [comment]
On Jul 30 10:28, Pierre Ossman (Work account) wrote:
> I'm afraid I'm unable to reproduce this issue. What applications are
> you using? I tested with a gnome-terminal on either end.

I'm copying from the client side under F28, typically from
mate-terminal-1.20.1 or firefox-61.0.1

The server side is running F27: tigervnc-1.8.0, mate-terminal-1.20.1,
xfce4-terminal-0.8.7.4.

Note that, under otherwise identical circumstances, I reverted the
clinet side vncviewer to tigervnc-1.8.0 and copy/paste works as
expected again.  I also tried two versions of realvnc and the problem
didn't occur.  So I'm reasonably sure this is somehow connected to
tigervnc-1.9.0.


Thanks,
Corinna

**Comment by CendioOssman** [comment]
Are you using Wayland or X11 on the client?

**Comment by github-cygwin** [comment]
On Jul 30 10:55, Pierre Ossman (Work account) wrote:
> Are you using Wayland or X11 on the client?

I'm using X11, FWIW.

(I just tried again:  RealVNC and tigervnc 1.8.0 vncviewer copy/paste
works fine, tigervnc 1.9.0, doesn't)


Thanks,
Corinna

**Comment by CendioOssman** [comment]
Odd. My setup is pretty much the same. What desktop environment are you using on the client?
And which build of the viewer?

**Comment by github-cygwin** [comment]
On Jul 30 04:59, Pierre Ossman (Work account) wrote:
> Odd. My setup is pretty much the same. What desktop environment are you using on the client?

KDE

> And which build of the viewer?

The client side is Fedora 28 and I'm using the stock Fedora packages.
So the working viewer is tigervnc-1.8.0-10.fc28.x86_64.rpm, the failing
viewer is tigervnc-1.9.0-1.fc28.x86_64.rpm.


Thanks,
Corinna

**Comment by CendioOssman** [comment]
Alright, I'm seeing the same thing with KDE. It seems to be doing something odd with the focus as it isn't raising the window until the second click. Will have to investigate.

**Comment by CendioOssman** [comment]
Should be fixed in be88293952175258992c1ed2f5a1b7d8f78fe7cc. Thanks for your bug report.

**Comment by github-cygwin** [comment]
Thanks a lot!

Corinna
