### ISSUE TITLE
TigerVNC 1.9.0 macOS app unsigned

### ISSUE THREAD

**Issue by snmishra** [TigerVNC/tigervnc#690]
macOS refuses to run TigerVNC 1.9.0. I checked with codesign tool:
```
> codesign -dv --verbose=4 /Applications/TigerVNC\ Viewer\ 1.9.0.app
/Applications/TigerVNC Viewer 1.9.0.app: code object is not signed at all
```
1.8.0 works fine:
```
> codesign -dv --verbose=4 /Applications/TigerVNC\ Viewer\ 1.8.0.app
Executable=/Applications/TigerVNC Viewer 1.8.0.app/Contents/MacOS/TigerVNC Viewer
Identifier=com.tigervnc.tigervnc
Format=app bundle with Mach-O thin (i386)
CodeDirectory v=20200 size=20065 flags=0x0(none) hashes=996+3 location=embedded
Library validation warning=OS X SDK version before 10.9 does not support Library Validation
VersionPlatform=1
VersionMin=656896
VersionSDK=656896
Hash type=sha1 size=20
CandidateCDHash sha1=a085dba410b933317828c140d59c9475f604de16
Hash choices=sha1
Page size=4096
CDHash=a085dba410b933317828c140d59c9475f604de16
Signature size=8519
Authority=Developer ID Application: Brian Hinz (S5LX88A9BW)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=May 22, 2017 at 10:21:27 PM
Info.plist entries=14
TeamIdentifier=S5LX88A9BW
Sealed Resources version=2 rules=12 files=1
Internal requirements count=1 size=184
```

**Comment by bphinz** [comment]
Thanks for the heads up.  I recently upgraded the OSX build host to
HighSierra and I guess during that process something broke.  I'll try to
get this re-published correctly today.

-brian

**Comment by bphinz** [comment]
The problem has been fixed and a signed package uploaded to bintray.
Thanks again for pointing this out.

-brian

**Comment by snmishra** [comment]
Thanks a lot for the fast fix on a Sunday. I can verify that it works now.

**Comment by Spongman** [comment]
1.9.0 is the latest release, is there a new release that contains this fix?

**Comment by bphinz** [comment]
This was a build issue, so the 1.9.0 dmg was simply republished to bintray:

https://bintray.com/tigervnc/stable/download_file?file_path=TigerVNC-1.9.0.dmg

**Comment by Spongman** [comment]
ah, ok, thanks. i thought that was why it's crashing on launch. maybe something else...
