### ISSUE TITLE
Changes to option "Pass system keys directly..." does not always take effect immediately

### ISSUE THREAD

**Issue by MarkMielke** [TigerVNC/tigervnc#691]
I think the ungrab keyboard is not being reliable performed as a result of the Options being saved.

I often end up in a situation where I am in fullscreen mode, and I need to switch back to Windows by pushing the Windows key and I try it and this fails. I push F8, Options, uncheck "Pass system keys directly...", "Ok",  and then try Windows key again and it often continues to fail. If I push F8 again, Options, and then click "Ok" (without making any other changes), and then try Windows key again it works.

I can toggle this back and forth and seeing the grab/ungrab often not taking effect until the *next* time I save the options.

This is not 100% reproducible. While writing this issue text, I tried one more time and the "Ok" took effect immediately as expected. But, I tried again and it is still easily reproducible.

I have noticed this behaviour on a variety of configurations, but some of these include:

1) Windows 7 client with TigerVNC 1.8.0 or 1.9.0.
2) Windows 10 client with TigerVNC 1.8.0 or 1.9.0

I can't recall if it also happened on 1.7.1 as well or not.

The server is normally always Linux. Definitely it has happened with 1.8.0 and 1.9.0, and again not sure about 1.7.1. The Linux server OS has also been different, including at least RHEL 7, Fedora 27, and Fedora 28.

**Comment by MarkMielke** [comment]
While looking closer, I found spells of being unable to reproduce, and then being able to easily reproduce.

If I understand the code correctly... it all looks correct to me on the surface. I'm left wondering about scenarios such as the win32 keyboard thread not receiving the WM_QUIT message, but this doesn't entirely make sense as I think I can reproduce both enable and disable not taking immediate effect. The other scenario in there that I'm confused about is how FLTK interferes with focus, and whether it might have something to do with the dialog window having focus at the time of "OK"...

**Comment by MarkMielke** [comment]
I am going to follow up here on the mailing list for best direction. This change broke some of my code that relies on BasicCookieStore being Serializable, but this change breaks this contract by introducing a transient "lock" variable (without qualifying it as transient), doesn't provide readObject()/writeObject() methods to deal with the transient variable, and doesn't update the serialVersionUID so it continues to try and read the objects already written that have the same serialVersionUID. I think this change should probably be reverted?

**Comment by CendioOssman** [comment]
I'm afraid this one will be difficult to fix without more information, or a reliable way to reproduce it. I tried several times on a Windows 10 machine here without success.

You could try creating `C:\temp` and starting the client with `-Log *:file:100`, which will get you a log file in `C:\temp`. Please check it for errors when you are able to reproduce the issue.

**Comment by MarkMielke** [comment]
Can you confirm if you tried on Windows 7? I think I mistakenly included Windows 10 in my summary above. I just realized I may have overlapped analysis and symptoms between two different issues and got myself confused. I almost never use "Full Screen" on my Windows 10 desktop, and I was unable to reproduce trying with Windows 10 desktop. My symptoms may only be on Windows 7.

**Comment by CendioOssman** [comment]
I have tried both Windows 10 and Windows 7 without being able to see the issue.

**Comment by CendioOssman** [comment]
Alright, please continue testing this. But I'll close this issue until we have something more substantial.
