### ISSUE TITLE
Cannot type underscore on v1.9 viewer

### ISSUE THREAD

**Issue by s-masashi** [TigerVNC/tigervnc#692]
Hi.
I'm enjoying TigerVNC with Linux(Ubuntu) server and macOS client.
But from v1.9, I can no longer type underscore character ('_').
When I switch back to v1.8 viewer, I can type underscore with the identical v1.9 linux vncserver.
I'm using Japanese keyboard.

Is something around keyboard operation changed at v1.9 update?

**Comment by CendioOssman** [comment]
Yes, there was a lot of work to enable support of the extended, raw, keyboard mode.

Could you run the client from a terminal and include `-Log *:stderr:100` and see what it says when you press underscore.

**Comment by CendioOssman** [comment]
No response, closing.
