### ISSUE TITLE
HAVE_XTEST should be defined for x0vncserver

### ISSUE THREAD

**Issue by marcriehm** [TigerVNC/tigervnc#693]
Hi. I installed tigervnc 1.9.0 from binaries. x0vncserver launches in read-only mode - the primary X display is shown on the remote vnc client session, but the keyboard and mouse do not work. x0vncserver prints the following error messages:
 XDesktop:    XTest extension not present
 XDesktop:    Unable to inject events or display while server is grabbed

These come from file unix/x0vncserver/XDesktop.cxx. There is a preprocessor variable HAVE_XTEST which is undefined. The error message is only printed when the binary is compiled without HAVE_XTEST. I beileve it should be recompiled with HAVE_XTEST=1.

Note that I can only comment on x0vncserver, not any other modules.

Regards, --Marc Riehm.

**Comment by astrand** [comment]
Where are the binaries from? I just downloaded and tested 	tigervnc-1.9.0.x86_64.tar.gz and 	tigervnc-1.9.0.i386.tar.gz from https://bintray.com/tigervnc/stable/tigervnc/1.9.0, and they work fine:


$ ./x0vncserver 

Mon Aug 13 12:51:46 2018
 Geometry:    Desktop geometry is set to 3200x1200+0+0
 XDesktop:    Using evdev codemap

 XDesktop:    XTest extension present - version 2.2
 Main:        Listening on port 5900

**Comment by CendioOssman** [comment]
No response. Closing.
