### ISSUE TITLE
"-RemoteResize=0" does not work on the Viewer command line

### ISSUE THREAD

**Issue by mrprintcu** [TigerVNC/tigervnc#696]
TigerVNC Viewer 1.9.0 for macOS

I now have to create a .tigervnc file with the "Resize remote session on connect" un-checked and specify the file in the command. For example:

'/Applications/TigerVNC Viewer 1.4.2.app/Contents/MacOS/TigerVNC Viewer' /Users/justme/bin/large.tigervnc

**Comment by CendioOssman** [comment]
The corresponding setting for that is `-DesktopSize`, not `-RemoteResize`. Please try specifying `-DesktopSize=""` and things should hopefully work better.
