### ISSUE TITLE
Accessing VNC Server inside of firewall.

### ISSUE THREAD

**Issue by alaskanrogue** [TigerVNC/tigervnc#698]
What ports/protocols do I need to forward thru a firewall to use TigerVNC to access a VNC server?

**Comment by Magissia** [comment]
Depends on your VNC server configuration.

**Comment by alaskanrogue** [comment]
Which configuration settings are involved? I am trying to access a Apple Mac system which I am using to compile code.

**Comment by CendioOssman** [comment]
The default port of VNC is 5900, so start by testing that. Otherwise try opening a larger range, e.g. 5900-6000.
