### ISSUE TITLE
vnc1.8.0 time out(10060) error

### ISSUE THREAD

**Issue by luoyanghero** [TigerVNC/tigervnc#705]
I use CentOS7.5 x64 server, installed tigervnc 1.8.0.
On CentOS7.5, I test vncviewer connect itself, it is ok. But I use another PC(windows 7 OS) to connect my CentOS7.5, show me 'time out 10060' error.
On windows7, I tried to use xshell(22 port) connect CentOS7.5, it is OK.

I checked the follow things on server:
1.selinux has closed.
2.firewall has closed.

The question is how can I get more infomation to debug where has a mistake? 

This is the log:
#################
[luoy@localhost t]$ getenforce 
Permissive
###################
[luoy@localhost t]$ systemctl status firewalld.service 
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

Aug 30 13:13:25 localhost.localdomain firewalld[2982]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -w --table filter --delete FORWARD --in-interface virbr0 --out-interface virbr0 --jump ACCE...that chain?).
Aug 30 13:13:25 localhost.localdomain firewalld[2982]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -w --table filter --delete FORWARD --out-interface virbr0 --jump REJECT' failed: iptables: ...by that name.
Aug 30 13:13:25 localhost.localdomain firewalld[2982]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -w --table filter --delete FORWARD --in-interface virbr0 --jump REJECT' failed: iptables: N...by that name.
Aug 30 13:13:25 localhost.localdomain firewalld[2982]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -w --table filter --delete INPUT --in-interface virbr0 --protocol udp --destination-port 53...that chain?).
Aug 30 13:13:25 localhost.localdomain firewalld[2982]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -w --table filter --delete INPUT --in-interface virbr0 --protocol tcp --destination-port 53...that chain?).
Aug 30 13:13:25 localhost.localdomain firewalld[2982]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -w --table filter --delete OUTPUT --out-interface virbr0 --protocol udp --destination-port ...that chain?).
Aug 30 13:13:25 localhost.localdomain firewalld[2982]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -w --table filter --delete INPUT --in-interface virbr0 --protocol udp --destination-port 67...that chain?).
Aug 30 13:13:25 localhost.localdomain firewalld[2982]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -w --table filter --delete INPUT --in-interface virbr0 --protocol tcp --destination-port 67...that chain?).
Aug 30 13:13:56 localhost.localdomain systemd[1]: Stopping firewalld - dynamic firewall daemon...
Aug 30 13:13:57 localhost.localdomain systemd[1]: Stopped firewalld - dynamic firewall daemon.
Hint: Some lines were ellipsized, use -l to show in full.

###################
[luoy@localhost t]$ vncserver -version
xauth:  timeout in locking authority file /run/gdm/auth-for-luoy-DYipcE/database

WARNING: The first attempt to start Xvnc failed, possibly because the font
catalog is not properly configured.  Attempting to determine an appropriate
font path for this system and restart Xvnc using that font path ...
Could not start Xvnc.

Xvnc TigerVNC 1.8.0 - built Apr 11 2018 06:06:57
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11903000, The X.Org Foundation

Xvnc TigerVNC 1.8.0 - built Apr 11 2018 06:06:57
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11903000, The X.Org Foundation

###################
[luoy@localhost t]$ vnc
vncconfig  vncpasswd  vncserver  vncviewer  
[luoy@localhost t]$ vncviewer -help

TigerVNC Viewer 64-bit v1.8.0
Built on: 2018-04-11 06:05
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

**Comment by hdatma** [comment]
Try this.

On the server:

```
sudo yum -y install tigervnc tigervnc-server tigervnc-server-mimimal tigervnc-server-module;
sudo systemctl enable vncserver@:1.service;
sudo vim /etc/systemd/system/vncserver\@.service;
sudo firewall-cmd --permanent --zone=public --add-service vnc-server;
sudo firewall-cmd --reload;
sudo systemctl daemon-reload;
sudo systemctl start vncserver@:1.service;
sudo systemctl status vncserver@:1.service
```

On the client:

```
xterm ssh -v -C -L 5901:127.0.0.1:5901 <ip-of-vnc-server-here> &
```

Then point the vnc viewer to <vnc://127.0.0.1:5901>.

**Comment by luoyanghero** [comment]
My server IP is 192.168.0.31.
On my win7, I tried xmanager client, xshell client. Log in my server, and run 'ssh -v -C -L 5901:127.0.0.1:5901 192.168.0.31 &' 
Show me some debug info, but no relative with my vnc.
And I open vncviewer.exe, try to input 'vnc://127.0.0.1:5901' or '192.168.0.31://127.0.0.1:5901', show me some address error.
I still don't know how to use this for debug.

Fortunity, when run over the server command, and try to use vncviewer connect server. success...^_^
