### ISSUE TITLE
Mysterious screen freezes after closing windows and menus

### ISSUE THREAD

**Issue by darkphoenix** [TigerVNC/tigervnc#706]
I've been using TigerVNC for a while now (desktop is GNOME Shell), and one issue keeps coming back: while most interactions are very fast and have almost no noticeable lag, whenever a window closes (or a dropdown menu disappears), the entire screen freezes for somewhere between 3 and 30 seconds. I can interact normally in that time (the cursor changes when I move over things, I can even click normally and it has an immediate effect, e.g. videos stop as evidenced by the sound ending, a menu opens and can be seen after the screen redraws etc), but the screen is just completely frozen. Is this a known issue, or is it more likely it's caused by the window manager and not TigerVNC? It occurs reproducably in just about every application I tried.

**Comment by darkphoenix** [comment]
> Which version of TigerVNC and which build are you using?
Xtigervnc -version

Xvnc TigerVNC 1.9.0 - built Jul 29 2018 13:31:03
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12000000, The X.Org Foundation

> How are you starting the server?
I am using the vncserver script, without any specific flags except -localhost no.
.vnc/xstartup just sets some variables and runs gnome-session.

> Do you have a proprietary graphics driver on this system?
I don't think so, this was a stock Ubuntu 18.04 and I never knowingly installed any.

**Comment by CendioOssman** [comment]
Very odd. I have no real idea what might cause it. I'll see if I can get a Ubuntu machine up and running here and see if I get the same effect.

**Comment by CendioOssman** [comment]
Hmmm... Ubuntu 18.04 only includes TigerVNC 1.7.0. And we don't have builds for 18.04. Did you do these builds yourself?

**Comment by darkphoenix** [comment]
Yes, I built it myself in hopes of fixing it - the issue occurred with the 1.7.0 that is shipped by Ubuntu, too.

**Comment by CendioOssman** [comment]
I'm having trouble getting a session running using Ubuntu's own scripts. Could you describe the steps you took to start a server using the version included with Ubuntu?

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by darkphoenix** [comment]
Sorry, completely forgot about this. No idea what the reason was, it somehow resolved itself a while ago.
