### ISSUE TITLE
why standard user login need admin authorization?

### ISSUE THREAD

**Issue by luoyanghero** [TigerVNC/tigervnc#711]
Envrionment: CentOS7.5 vnc1.8.0

I am a standard user, when server reboot, I first login through vnc-viewer.
It needs admin authorization.
Each time reboot, I need call my administrator to help me input the password. So bad.
How can I avoid this?

The following is my vnc-server config:
gvim /etc/systemd/system/vncserver@\:2.service
############################

> [Unit]
> Description=Remote desktop service (VNC)
> After=syslog.target network.target
> 
> [Service]
> Type=forking
> 
> ##Clean any existing files in /tmp/.X11-unix environment
> ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
> ExecStart=/usr/sbin/runuser -l linjiang -c "/usr/bin/vncserver %i"
> PIDFile=/home/linjiang/.vnc/%H%i.pid
> ExecStop=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
> 
> [Install]
> WantedBy=multi-user.target
> ##WantedBy=graphical.target
> 

#########################

**Comment by CendioOssman** [comment]
The password should only need to be set once, and can be done by the user. Could you describe exactly what it is your admin has to do each time? We might be talking about different things here.

**Comment by luoyanghero** [comment]
Ohh, I forgot it, I am a sudoer.
When I change to a standard account. No Authenticaition let me input.
