### ISSUE TITLE
Mouse not including geometry offset with x0vncserver

### ISSUE THREAD

**Issue by achea** [TigerVNC/tigervnc#712]
Using TigerVNC 1.9.0 with xorg-server 1.20

I set up a virtual screen to use as a second monitor on my tablet (like explained [here](https://bbs.archlinux.org/viewtopic.php?id=191555)) and start `x0vncserver` like:

```
x0vncserver -display :0 -Geometry 1920x1200+1920+0 -PasswordFile ~/.vnc/passwd
```
The mouse renders with 1.9.0 (didn't with 1.8) on the vnc screen, but it doesn't factor in the offset, so when the mouse is on the main screen, the cursor renders on both screens at the same time, and when I move the mouse from the main to the vnc screen, the mouse doesn't render on either screen (but I can still see the effects of actions on the vnc screen like clicking and hovering).

Is this a bug or am I missing a setting somewhere?  Thanks.

**Comment by CendioOssman** [comment]
Yeah, I think the geometry thing was overlook. Could you try this patch?
```diff
diff --git a/unix/x0vncserver/XDesktop.cxx b/unix/x0vncserver/XDesktop.cxx
index 110b79eb..d83e538a 100644
--- a/unix/x0vncserver/XDesktop.cxx
+++ b/unix/x0vncserver/XDesktop.cxx
@@ -204,6 +204,8 @@ void XDesktop::poll() {
     unsigned int mask;
     XQueryPointer(dpy, DefaultRootWindow(dpy), &root, &child,
                   &x, &y, &wx, &wy, &mask);
+    x += geometry->offsetLeft();
+    y += geometry->offsetTop();
     server->setCursorPos(rfb::Point(x, y));
   }
 }
```

**Comment by achea** [comment]
I thought something like this would fix it but no dice ... HOWEVER, on a whim I changed the patch to:

```
index 110b79eb..d83e538a 100644
--- a/unix/x0vncserver/XDesktop.cxx
+++ b/unix/x0vncserver/XDesktop.cxx
@@ -204,6 +204,8 @@ void XDesktop::poll() {
     unsigned int mask;
     XQueryPointer(dpy, DefaultRootWindow(dpy), &root, &child,
                   &x, &y, &wx, &wy, &mask);
+    x -= geometry->offsetLeft();
+    y -= geometry->offsetTop();
     server->setCursorPos(rfb::Point(x, y));
   }
 }
```

and it works!  I don't know why it does though - maybe since the vnc screen has its own state of the main cursor's position?  Pre-patch the vnc screen thinks it's the main screen, so we need to shift the main screen relative to the vnc screen?  Just a thought.

**Comment by CendioOssman** [comment]
The internals only know of the cropped dimensions, so everything needs to be adjusted. Thanks for testing. I've committed this as c86ce3eeef5521134e8d30e6009dafc6b7c1759f and it will be in the next release.
