### ISSUE TITLE
how to make vncviewer real full screen

### ISSUE THREAD

**Issue by luoyanghero** [TigerVNC/tigervnc#713]
Environment: CentOS7.5  VNC1.8.0-server
client: vncviewer1.8.0
I open vncviewer connect to my vnc_server,
but cannot full sceen, I maxmize vncviewer window, have up border and bottom border。
Can I set client to make it full screen?
Or Is there another client can do this?

**Comment by CendioOssman** [comment]
Full screen is available from the context menu, which by default is opened when pressing F8. You can also enable it from the options before you connect.

Does that work better for you?

**Comment by luoyanghero** [comment]
f8  is a good option.
