### ISSUE TITLE
Trying to connect Tiger to vino fails

### ISSUE THREAD

**Issue by Apromixately** [TigerVNC/tigervnc#716]
It seems there is an issue with TLS encryption. At least all of the internet recommends running
`$ gsettings set org.gnome.Vino require-encryption false`
which I obviously don't want to do. The website says TigerVNC supports TLS. What might be the issue here?

**Comment by CendioOssman** [comment]
Vino unfortunately uses a different extension for TLS which isn't implemented in TigerVNC. Please see #307.
