### ISSUE TITLE
Does xp 32bit operation system support for vnc viewer1.8.0 ?

### ISSUE THREAD

**Issue by luoyanghero** [TigerVNC/tigervnc#717]
I try to open vnc viewer in a xp OS, show me the error 'cannot find the input InitailizeConditionVariable from KERNEL32.DLL'

**Comment by CendioOssman** [comment]
No, I'm afraid you'll need Windows Vista at least.

**Comment by luoyanghero** [comment]
Does there some other vnc client support for xp?

**Comment by luoyanghero** [comment]
Even the oldest version not support for xp?

**Comment by bphinz** [comment]
1.6.0 was the last version to support Windows XP.
