### ISSUE TITLE
macOS homebrew tiger-vnc incompatible library jpeg-turbo/lib/libjpeg.8.dylib

### ISSUE THREAD

**Issue by weakunix** [TigerVNC/tigervnc#718]
installed tiger-vnc 1.9.0 via `brew install tiger-vnc` on macOS 10.12.6 without issue. but when trying to launch vncviewer, encountered the following error:

dyld: Library not loaded: /usr/local/opt/jpeg-turbo/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/vncviewer
  Reason: Incompatible library version: vncviewer requires version 10.0.0 or later, but libjpeg.8.dylib provides version 8.0.0
Abort trap: 6

**update 1**: clean reinstall of homebrew/tiger-vnc doesn't fix the issue either. is there anyway to install 1.8.0 brew formula?

**update 2**: a high sierra machine that was running tiger-vnc 1.8.0 w/o problems now gives the same error after `brew upgrade tiger-vnc`, and worse yet, even using `brew switch tiger-vnc 1.8.0` to switch back to the older version doesn't fix the issue. it appears that jpeg-turbo is among the updated formulae when upgrading tiger-vnc (not sure if it's the issue though).

**update 3**: problem found - this is indeed due to the dependency keg jpeg-turbo being updated from 1.5.3 to 2.0.0. reinstalling/switching to jpeg-turbo 1.5.3 fixes the launch issue (tiger-vnc 1.8.0 & 1.9.0 both work).

**Comment by CendioOssman** [comment]
I'm afraid we don't have any control over how homebrew does their builds. So I'm going to have to ask you to file a bug with them if there is something wrong with their build.
