### ISSUE TITLE
Any Support for Ubuntu 18.04?

### ISSUE THREAD

**Issue by whao** [TigerVNC/tigervnc#719]
Hello

I am wondering if there is any support for Ubuntu 18.04 in the future? Because 18.04 switched back to gnome. I assume the TigerVNC would be working perfectly in default.

**Comment by luoyanghero** [comment]
what does 'switched back to gnome'

**Comment by CendioOssman** [comment]
We don't explicitly support (or not support) specific distributions. Are you seeing some issue on Ubuntu 18.04?

**Comment by CendioOssman** [comment]
That should be harmless. What happens if you run `make` after this?

**Comment by whao** [comment]
@CendioOssman Thank you for your reply, nothing wrong comes out. I am figuring out the configuration options when building. According to the `BUILDING.txt`:
```
> ./configure --with-pic --without-dtrace --disable-static --disable-dri \
      --disable-xinerama --disable-xvfb --disable-xnest --disable-xorg \
      --disable-dmx --disable-xwin --disable-xephyr --disable-kdrive \
      --disable-config-dbus --disable-config-hal --disable-config-udev \
      --disable-dri2 --enable-install-libxf86config --enable-glx \
      --with-default-font-path="catalogue:/etc/X11/fontpath.d,built-ins" \
      --with-fontdir=/usr/share/X11/fonts \
      --with-xkb-path=/usr/share/X11/xkb \
      --with-xkb-output=/var/lib/xkb \
      --with-xkb-bin-directory=/usr/bin \
      --with-serverconfig-path=/usr/lib[64]/xorg \
      --with-dri-driver-path=/usr/lib[64]/dri \
      {additional configure options}
    (NOTE: This is merely an example that works with Red Hat Enterprise/CentOS
    6 and recent Fedora releases.  You should customize it for your particular
    system.  In particular, it will be necessary to customize the font, XKB,
    and DRI directories.)
```
I am wondering where I can find all these available options? Because I didn't find list on X.org website. I am sorry if I asked the stupid quesion.

**Comment by CendioOssman** [comment]
Not sure. I would suspect they do not document them as they tend to change. Your can run `./configure --help` and you should get a list of all of them and some descriptions.

In most cases it's easiest to see how Xorg is built by your distribution and copy what they do. Building Xorg (and Xvnc) is unfortunately at a point where most users can easily sort it out. :/

Hope this helps. If you have more questions I would suggest using our mailing list. The issue tracker is better suited for specific problems that need to be resolved.
