### ISSUE TITLE
Lock screen terminates RDP connection 

### ISSUE THREAD

**Issue by wpj2** [TigerVNC/tigervnc#726]
Ubuntu 16.04.05 amd64 fresh install xrdp Version 0.6.1.  Lock screen terminates Windows 7 rdp connection when using tigervnc versions 1.8.0 and 1.9.0. Using tigervnc version 1.7.1 and lock screen (manual and autolock) works as expected.  Please ask if you require any additional information.
Regards,
 Pete

**Comment by CendioOssman** [comment]
Does this work if you use our client and not xrdp? If the RDP connection is terminated then it sounds like an issue with xrdp rather than TigerVNC.

**Comment by wpj2** [comment]
Hi Pierre,

I think not because lock screen (both auto and manual) work without terminating RDP if
tigervncserver_1.7.1-1ubuntu1_amd64.deb is used with the same xrdp version release with Xenial.

Regards,
Pete

**Comment by CendioOssman** [comment]
Newer features in TigerVNC might be provoking missing parts of xrdp. We've seen that happen before. 

So again, could you please try with our VNC client so we can narrow down when this occurs?

Have you checked the log files for xrdp and Xvnc when this happens?

**Comment by wpj2** [comment]
Hi Pierre,

Apologies for not answering sooner.

I have used your VNC client and lock screen works as expected.

You are correct in that it is an issue with xrdp on Ubuntu 16.04.

Thank you for your help with this issue.

Regards,
Pete Juhas

**Comment by CendioOssman** [comment]
Alright. I'll go ahead and close this issue then. If you file a report with xrdp then feel free to add a reference here in case other people run in to the same issue.
