### ISSUE TITLE
VNCServerST::checkTimeouts calls exit(0) - does not clean up

### ISSUE THREAD

**Issue by astrand** [TigerVNC/tigervnc#727]
VNCServerST::checkTimeouts handles MaxDisconnectionTime, MaxConnectionTime, and MaxIdleTime. If these are reached, the server simply does exit(0). This means that destructors are not executed. For example, when using -rfbunixpath, the UNIX socket is left behind.

**Comment by CendioOssman** [comment]
Bah. This was messy. These timeouts aren't handled like other timers, so that needs to be cleaned up first. But that in turn exposes a rather unhealthy lack of encapsulation between `VNCServerST` and `VNCSConnectionST'. So some cleanup is needed to get this in place.
