### ISSUE TITLE
First 2 lines in vncviewer .tigervnc config files uses Windows line breaks

### ISSUE THREAD

**Issue by astrand** [TigerVNC/tigervnc#733]
Line 1 and 2 in .tigervnc configuration files uses Windows line breaks, while the rest are using UNIX line breaks. From vncviewer/parameters.cxx:

  fprintf(f, "%s\r\n", IDENTIFIER_STRING);
  fprintf(f, "\r\n");

  if (encodeValue(servername, encodingBuffer, buffersize))  
    fprintf(f, "ServerName=%s\n", encodingBuffer)
...

**Comment by johahauf** [comment]
This can be closed, it is fixed since commit 3fe718c14

**Comment by CendioOssman** [comment]
Indeed. Thanks for noticing.
