### ISSUE TITLE
Opening .tigervnc files on windows fails when path+file name is too long

### ISSUE THREAD

**Issue by nhosko** [TigerVNC/tigervnc#735]
When a .tigervnc has a very long path + file name, then it will fail to open on Windows with the error "No such file or directory)".

For example when I download a .tigervnc from Internet Explorer from a website dedicated to create .tigervnc files for connecting to several computer, and click "Open", IE will temporarily save it to..
C:\Users\MYUSERNAME\AppData\Local\Microsoft\Windows\INetCache\IE\SOMEOTHERFOLDERS_blabla_WINDOWS_STUFF\filename.tigervnc
TigerVNC is set as my standard app for opening those files, then TigerVNC will fail to open as follows:

![image](https://user-images.githubusercontent.com/23018070/46592216-e3d94a00-cac0-11e8-9e72-53dbcea6bd83.png)

If instead of "opening" it, I save it to 
C:\Users\MYUSERNAME\Downloads\filename.tigervnc and then open, it will work. Unless MYUSERNAME and filename are too long..

For example..
![image](https://user-images.githubusercontent.com/23018070/46592366-5c8cd600-cac2-11e8-86ce-259cf9683f7c.png)
The first "ThisIsAFileWithAShortName.tigervnc" will open successfully, but the second one "..AVeryLongName" will fail with the error on photo above..

I'm using TigerVNC: vncviewer64-1.9.0.exe
In our company we recently changed from RealVNC to VNCTiger, and this issue was reproducible on all users (13 computers, all using the same 1.9.0 Version of Tiger VNC [32 and 64 bit] and Windows 10).

Is there a fix to solve this?

**Comment by CendioOssman** [comment]
Ah. We forgot to update the maximum length when we started supporting `.tigervnc` files as an argument, so the path cannot be longer than 64 characters. However the length got adjusted for other reasons in 67901996804e4e446c6ba2f36ea3ce26e0080fbb.

This fix has yet to be released though, but you can try a nightly build. You'll find the link for those on the homepage.
