### ISSUE TITLE
OpenSSL support in TigerVNC

### ISSUE THREAD

**Issue by shawnahall71** [TigerVNC/tigervnc#737]
Hi,

We are transitioning to using TLS encrypted TigerVNC sessions within our company, but during user testing we've found that our users who have the lower powered corporate-standard devices such as Surface Pro 4s and Dell e7470s are noticing a significant reduction in performance in encrypted sessions (vs. current unencrypted sessions).  In side-by-side testing with one user, I saw 3% CPU usage on Windows during an unencrypted session and 30% during an encrypted, both while an identical 2D visualization was running.

I understand encryption is going to incur a penalty, but I'm wondering if that penalty can be made so minimal that it's imperceptible.  My understanding is that OpenSSL is often the fastest SSL/TLS implementation, so I wanted to inquire about the possibility of adding OpenSSL support to TigerVNC.  Pending management approval, our company might be willing to develop and provide the code to the TigerVNC project.  I assume this isn't possible due to the conflicting GPL and OpenSSL licenses, but I wanted to ask here before completely ruling that out since I understand there are sometimes ways around that.

Alternatively, I would be open to other encryption libraries or optimizations to GnuTLS as long as they reduced the encryption penalty.  We've looked into TurboVNC, but since the native TurboVNC client doesn't support encryption, we'd be forced to use the Java TurboVNC client, which we really don't want to support (supporting Java applications on a locked-down corporate Windows build is a pain).  We've also considered SSH tunneling, but the added complexity for our end users over the long term seems more frustrating than putting in the up front effort to improve the TLS encryption within TigerVNC.

What are your thoughts?  Thanks in advance for your time.

**Comment by bphinz** [comment]
On Tue, Oct 9, 2018 at 8:32 AM Shawn Hall <notifications@github.com> wrote:

> We've also considered SSH tunneling, but the added complexity for our end
> users over the long term seems more frustrating than putting in the up
> front effort to improve the TLS encryption within TigerVNC.


Just thinking aloud here, but have you verified whether or not SSH
tunneling incurs a similar overhead penalty?  I added an SSH panel to the
options dialog of the TigerVNC Java client a while back.  Perhaps porting
that over to the native client would simplify things enough to make SSH
acceptable for end users?  Combined with the recent addition of Unix domain
sockets, it might be feasible to have VNC sessions completely initiated
client side by issuing the command to start Xvnc via SSH and then connect
to the socket (eliminating the hassle of assigning/managing RFB ports).

-brian

**Comment by CendioOssman** [comment]
To be honest, having two separate TLS implementations isn't terribly appealing. And as you say, there has been some discussion about licensing issues. So porting to OpenSSL is not something that I see as appealing.

That said, GnuTLS should have performance close to OpenSSL these days. It was back in the stone age when it was still using gcrypt that it had issues. So I wonder if there is something else going wrong on your machine.

For a comparison I tested quickly with my development build here, and I get a CPU usage change from 10% to 15% when I enable encryption for a simple test case.

Are you using the official 1.9.0 release binaries for this test? And have you made sure you picked the 64-bit versions?

**Comment by CendioOssman** [comment]
You said you saw the CPU usage increase on the client, so it's the build there I'm interested in.

Have you checked CPU usage on the server as well though?

**Comment by CendioOssman** [comment]
Oh, and was the client CPU usage just vncviewer.exe? Or was it an aggregate of the entire machine? Perhaps you have some security scanner running that is trying to analyse things.

**Comment by shawnahall71** [comment]
Sorry, for the delayed response.  Github update emails filter to a different inbox that doesn't get looked at very often.

CPU usage on the server isn't noticeably different.  Many people are working just fine with the new encryption, so the variable is the clients since everyone's using the same set of servers.

The client CPU usage is specific to the vncviewer.exe process.  There's certainly other security things on these systems that increases the overall CPU usage, but the vncviewer.exe process itself consumes much more CPU % with encryption enabled on slower machines.

The compromise we've come to at the moment is to "whitelist" the users who experience a noticeable slowdown.  Since we control the tool used to launch our VNC sessions, we made it so that whitelisted users stick with the unencrypted session, and the rest are encrypted.

We'd still like for the encryption to be a lower penalty so we can avoid this kludge, so if there's a way to make that happen I'm still interested in it.

**Comment by shawnahall71** [comment]
The trend seems to follow the "speed" of their computer.  It's a corporate environment, so most everyone has the same Windows 10 build, and everyone's using the same 1.8.0 client.  The difference is that the faster machines like a Dell Precision 5520 keep up just fine, but slower machines like a Surface Pro 4 struggle.

**Comment by CendioOssman** [comment]
I had a look at profiling things on a slow Atom machine here, and unfortunately it looks like the overhead is in very basic stuff such as allocating memory and shuffling buffers. As such it will be very difficult to optimize things further. :/

You could talk to the GnuTLS people and see if they have any optimizations planned for slower systems.

**Comment by dankegel** [comment]
Which CPU did the affected machines have?  
Both Surface Pro 4 and Dell e7470 are offered with a range of CPU types.

(There are openssl benchmark results for a range of cpus at https://openbenchmarking.org/showdown/pts/openssl but they might not measure what you need to measure.)

**Comment by shawnahall71** [comment]
The Surface Pro 4 systems deployed in the company have the Intel Core i5-6300U 2.4 GHz processors.  I'll have to look up what's in our e7470 systems - the current model 7490 systems we're deploying have the Intel Core i5-8350U quad-core 1.7GHz processors.

**Comment by dankegel** [comment]
What does "gnutls-cli --benchmark-tls-ciphers" output on the affected machines?

**Comment by shawnahall71** [comment]
Here's what I'm seeing on a "fast" system - a Dell Precision 5530 w/ a Intel Core i7-8850H @ 2.6 GHz.

```
$ gnutls-cli --benchmark-tls-ciphers
Testing throughput in cipher/MAC combinations (payload: 1400 bytes)
                  RSA_ARCFOUR_128_SHA1  150.87 MB/sec
                   RSA_ARCFOUR_128_MD5  158.68 MB/sec
                RSA_AES_128_GCM_SHA256  163.22 MB/sec
                       RSA_AES_128_CCM  161.38 MB/sec
           ECDHE_RSA_CHACHA20_POLY1305  0.22 GB/sec
                  RSA_AES_128_CBC_SHA1  143.80 MB/sec
             RSA_CAMELLIA_128_CBC_SHA1  64.41 MB/sec

Testing throughput in cipher/MAC combinations (payload: 15360 bytes)
                  RSA_ARCFOUR_128_SHA1  179.46 MB/sec
                   RSA_ARCFOUR_128_MD5  186.44 MB/sec
                RSA_AES_128_GCM_SHA256  188.41 MB/sec
                       RSA_AES_128_CCM  185.50 MB/sec
           ECDHE_RSA_CHACHA20_POLY1305  0.27 GB/sec
                  RSA_AES_128_CBC_SHA1  176.94 MB/sec
             RSA_CAMELLIA_128_CBC_SHA1  69.13 MB/sec
```

I'm working to get this same data from a Surface Pro 4.

**Comment by shawnahall71** [comment]
@dankegel Here's what I got from a colleague's Surface Pro 4:

![surface_pro_screenshot](https://user-images.githubusercontent.com/7996517/54542629-8d770e00-4972-11e9-9c28-53675a291bea.png)

**Comment by dankegel** [comment]
Looks like on the 'slow' machine, performance is half what it is on a 'fast' machine.
That doesn't seem to be enough to account for the 3% vs. 30% cpu time you mentioned.

Next step might be to profile TigerVNC on the slow vs. fast machine to see if there are any surprises.

**Comment by shawnahall71** [comment]
@CendioOssman can you share how you ran the profiling TigerVNC in your earlier comment?  I'm a Linux guy, so profiling an application on Windows is new to me.  You had mentioned your profiling results showed the majority of time being spent in fundamental things like memory management.

**Comment by CendioOssman** [comment]
I don't normally do profiling on Windows either, but I found this software which was able to profile vncviewer:

http://www.codersnotes.com/sleepy/
