### ISSUE TITLE
Wrong colours shown on big endian host

### ISSUE THREAD

**Issue by ernsteiswuerfel** [TigerVNC/tigervnc#738]
I am running a TigerVNC-client on my Talos II Secure Workstation, to access a TigerVNC-server running on my Opteron.. Works pretty normal, but I get strange colours in the TigerVNC-window (see screenshot). I suspect this being an endianness issue.

  Talos II: Gentoo Linux (Big Endian), tigervnc-1.9.0, xorg-server-1.20.1
Opteron: Gentoo Linux (Little Endian), tigervnc-1.8.0, xorg-server-1.19.5

![bildschirmfoto zu 2018-10-11 11-50-12](https://user-images.githubusercontent.com/13378641/46814630-7441b400-cd79-11e8-96bb-0aef6f1e3001.png)

**Comment by CendioOssman** [comment]
That does indeed look like some pixel conversion problem. And I thought we had tests to catch those... :/

First off, could you try upgrading to 1.9.0 on the server?

Secondly, please try to play around with the encoding settings to see if we can pinpoint which encoder or decoder is buggy. Try enabling and disabling JPEG, and try different encodings (with JPEG off if not using Tight).

Please also test another client so we can determine if this is a server or client problem.

**Comment by ernsteiswuerfel** [comment]
Ok, did as you suggested. Setup is now:

Viewer: Gentoo Linux (Big Endian), tigervnc-1.9.0, xorg-server-1.20.1
Server: Gentoo Linux (Little Endian), tigervnc-1.9.0, xorg-server-1.20.1

Encodings:
Tight + JPEG: funky colours
Tight - JPEG: funky colours
ZRLE - JPEG: funky colours
Hextile - JPEG: funky colours
RAW - JPEG: funky colours

So no change on the client side with the different options.

As another client I tried remmina-1.2.31.3, This one works showing the correct colours! But it's slooow compared to TigerVNC. ;)

Screenshot tigervnc-1.9.0 on server + client, with some server info:

![bildschirmfoto zu 2018-10-12 22-27-51](https://user-images.githubusercontent.com/13378641/46893031-d1b82c80-ce6f-11e8-8357-a5e82708e0ce.png)

**Comment by awilfox** [comment]
I'll note this bug also affects the TigerVNC client connecting to the Qemu built-in VNC server, and also the x11vnc VNC server.  Both work fine in the KRDC client on big endian.

**Comment by awilfox** [comment]
This is qemu-system-ppc64 running on the BE computer which is also running TigerVNC (localhost); you can see the white text is yellow:

![VNC connection information and example of Qemu VNC](https://user-images.githubusercontent.com/303838/46895872-ebda1680-ce3f-11e8-9281-2a5e9f589feb.png)

**Comment by ernsteiswuerfel** [comment]
Yep, I can verify that 1.7.1 shows the colours correctly!

However I can't apply the patch to 1.9.0. Looking at the source, in vncviewer/PlatformPixelBuffer.cxx I can't find a line
`-                                        ImageByteOrder(fl_display) == MSBFirst`
to be replaced.

**Comment by CendioOssman** [comment]
Hmm... it seems we've already had some fixes on this theme after 1.9.0...

Try changing `PixelFormat(32, 24, false, ...` to `PixelFormat(32, 24, true, ...` in that file.

**Comment by ernsteiswuerfel** [comment]
That did the trick, thanks! Changing this single parameter made the colours looking normal on my Big Endian viewers.

**Comment by CendioOssman** [comment]
Alright, I'll try to get a commit in place for something permanent. Thank you for testing.

**Comment by CendioOssman** [comment]
Could you test changing that `true` back to `false` and the applying this diff:

```diff
diff --git a/vncviewer/Surface_X11.cxx b/vncviewer/Surface_X11.cxx
index 3523da3d..6562634d 100644
--- a/vncviewer/Surface_X11.cxx
+++ b/vncviewer/Surface_X11.cxx
@@ -109,6 +109,7 @@ void Surface::blend(Surface* dst, int src_x, int src_y, int x, int y, int w, int
 
 void Surface::alloc()
 {
+  XRenderPictFormat templ;
   XRenderPictFormat* format;
 
   // Might not be open at this point
@@ -117,7 +118,37 @@ void Surface::alloc()
   pixmap = XCreatePixmap(fl_display, XDefaultRootWindow(fl_display),
                          width(), height(), 32);
 
-  format = XRenderFindStandardFormat(fl_display, PictStandardARGB32);
+  // Our code assumes a BGRA byte order, regardless of what the endian
+  // of the machine is or the native byte order of XImage, so make sure
+  // we find such a format
+  templ.type = PictTypeDirect;
+  templ.depth = 32;
+#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
+  templ.direct.alpha = 0;
+  templ.direct.red   = 8;
+  templ.direct.green = 16;
+  templ.direct.blue  = 24;
+#else
+  templ.direct.alpha = 24;
+  templ.direct.red   = 16;
+  templ.direct.green = 8;
+  templ.direct.blue  = 0;
+#endif
+  templ.direct.alphaMask = 0xff;
+  templ.direct.redMask = 0xff;
+  templ.direct.greenMask = 0xff;
+  templ.direct.blueMask = 0xff;
+
+  format = XRenderFindFormat(fl_display, PictFormatType | PictFormatDepth |
+                             PictFormatRed | PictFormatRedMask |
+                             PictFormatGreen | PictFormatGreenMask |
+                             PictFormatBlue | PictFormatBlueMask |
+                             PictFormatAlpha | PictFormatAlphaMask,
+                             &templ, 0);
+
+  if (!format)
+    throw rdr::Exception("XRenderFindFormat");
+
   picture = XRenderCreatePicture(fl_display, pixmap, format, 0, NULL);
 
   visFormat = XRenderFindVisualFormat(fl_display, fl_visual->visual);
```

It should work on your machine, but I don't have a big-endian machine here to verify with. :)

**Comment by awilfox** [comment]
Looks beautiful, thank you!  We've applied this to [our tree](https://code.foxkit.us/adelie/packages/commit/348791237928aa54acc58bfc9e52a419dcec328d) so that our users can use TigerVNC properly until a release is made.

Proof it works - VNC from my BE PPC64 to a LE box:
![It works](https://user-images.githubusercontent.com/303838/47385556-04fc8600-d6d0-11e8-8c7f-ad8815118acf.png)

**Comment by ernsteiswuerfel** [comment]
Yep, I can also confirm that your patch works perfectly. Thanks!

**Comment by CendioOssman** [comment]
Great. Thanks for testing. Committed as cc647dbd40398e5d56a5b5d649f3bb20d90608e6.

**Comment by gearnau** [comment]
Hello,

I recently moved to TigerVNC1.10 and I am afraid that a regression was introduced, when compared to 1.7
