### ISSUE TITLE
`/usr/lib/xorg/protocol.txt` installed

### ISSUE THREAD

**Issue by paulmenzel** [TigerVNC/tigervnc#739]
TigerVNC 1.8.0 seems to install `/usr/lib/xorg/protocol.txt`, which is already part of the X.Org X Server already.

**Comment by CendioOssman** [comment]
This is part of the standard Xorg installation, which you'll get if you just run `make install` in the xserver tree. I would suggest just installing `Xvnc` and `libvnc.so` as those are the only additions from TigerVNC.
