### ISSUE TITLE
Building server `libnetwork.la` not found as it is searched in source directory

### ISSUE THREAD

**Issue by paulmenzel** [TigerVNC/tigervnc#742]
TigerVNC 1.9.0 fails to build with the error below.

```
$ make -j100 TIGERVNC_SRCDIR=/dev/shm/bee-root/tigervnc/tigervnc-1.9.0-0/source
[…]
make[2]: Entering directory '/dev/shm/bee-root/tigervnc/tigervnc-1.9.0-0/build/unix/xserver/hw/vnc'
  CC       libvnc_la-vncModule.lo
  CC       libvnccommon_la-vncExt.lo
  CXX      libvnccommon_la-vncExtInit.lo
  CC       libvnccommon_la-vncSelection.lo
  CC       libvnccommon_la-vncHooks.lo
make[2]: *** No rule to make target '/dev/shm/bee-root/tigervnc/tigervnc-1.9.0-0/source/common/network/libnetwork.la', needed by 'libvnc.la'.  Stop.
```

The problem is, that TigerVNC was built outside the source directory in `/dev/shm/bee-root/tigervnc/tigervnc-1.9.0-0/build`, and that is where the static library is.

    /dev/shm/bee-root/tigervnc/tigervnc-1.9.0-0/build/common/network/libnetwork.la

How can the build system be told about that?

**Comment by paulmenzel** [comment]
By the way, this seems to be a regression in TigerVNC 1.9.0 (or X.Org X Server 1.20.x). The same build script worked with TigerVNC 1.8.0 (and X.Org X Server 1.19.x).

**Comment by CendioOssman** [comment]
It shouldn't be a regression as you always need to specify an extra variable for an out-of-tree build. However the variable was changed from `LIB_DIR` to `TIGERVNC_BUILDDIR` in 1.9.0. Please try specifying that and see if that helps.
