### ISSUE TITLE
Use HTTPS URLs

### ISSUE THREAD

**Issue by paulmenzel** [TigerVNC/tigervnc#743]
As the TigerVNC Web site is available over HTTPS, it’d be great if the more secure URL would be used.

For example, in the version output on the terminal.

```
$ vncviewer

TigerVNC Viewer 64-bit v1.8.0
Built on: 2018-04-19 10:51
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

[…]
```

**Comment by CendioOssman** [comment]
Good idea. Updated in 32b96ffec16273340e61a848e389b76d01c2986f.
