### ISSUE TITLE
vncserver script creates xstartup files in home directory

### ISSUE THREAD

**Issue by kmarius** [TigerVNC/tigervnc#744]
When I start vncserver with `vncserver -xstartup firefox`, the server will start with only firefox as expected. However I will find an executable file with name `firefox` in my home directory. 
What happens is vncserver will look for the xstartup file `firefox` in the current directory and since it won't find it, it will copy the default xstartup file. When it tries to execute `firefox` it will obviously find it somewhere in `PATH`. 

A temporary fix is just giving an absolute path, but I still think this inconsistency should be addressed.

**Comment by CendioOssman** [comment]
Yeah, that is just confusing. Thank you for reporting this.

**Comment by CendioOssman** [comment]
Since xstartup files are gone this is no longer an issue.
