### ISSUE TITLE
Add vncserver feature to not send screen output and allow control.

### ISSUE THREAD

**Issue by johnebgood** [TigerVNC/tigervnc#746]
Please add a feature to allow disabling sending screen output from the remote server, vncserver would then work much like Synergy, when running a program that has full motion video remote computer control it is very laggy and frustrating, it would be nice to have this feature just for control. Maybe an option where you would still use the geometry but no display, ie: -geometry 1920x1080 -nodisplay, it might be nice to have the option from the client side so control would be fluid when connecting to a computer with video or frequent screen updates.

Thanks,
John

**Comment by CendioOssman** [comment]
Sorry, but such usage is not the goal of this project. We want to provide a full interactive session.
