### ISSUE TITLE
cannot see the running apps with vnc

### ISSUE THREAD

**Issue by potant** [TigerVNC/tigervnc#747]
Hello,
vncserver's startup file: 
#!/bin/bash
startxfce4 &

The connection is successful but when i open a gui app e.g firefox with vnc client, i cannot see it in the physical machine and vice versa: when i have opened a gui in the physical machice, i cannot see it with vncviewer....

Any idea?

**Comment by CendioOssman** [comment]
I'm afraid `vncserver` is the wrong tool if you want to see your local screen. It starts an entirely new session that is independent from your local login.

Have a look at `x0vncserver` instead. That gives you a VNC server for an existing session. It is not our primary focus though, so it doesn't have as many features as `vncserver`.
