### ISSUE TITLE
Windows client encryption 

### ISSUE THREAD

**Issue by chrisplusplus** [TigerVNC/tigervnc#753]
No matter what I do I cannot get any windows clients to negotiate encrypted session (without ssh tunnel)  Can someone point me in the right direction?  I have security types set as such

`-SecurityTypes=VeNCrypt,Plain,TLSNone,TLSVnc,TLSPlain,X509None,X509Vnc,X509Plain`

**Comment by CendioOssman** [comment]
Are those the parameters given to the server or the client? Either way you should drop `VeNCrypt` and `Plain` from that list. The first is implicit, and the second is without encryption. Which might be the issue.

**Comment by chrisplusplus** [comment]
Removing VeNCrypt and Plain as @CendioOssman suggests unfortunately doesn't do anything for me.  Have you tried using a windows VNC client?

**Comment by CendioOssman** [comment]
Alright, let's see if we can get a log file then. Please create `c:\temp` and then start the viewer with the arguments `-Log *:file:100`. Then attach the output of `c:\temp\vncviewer.log` here.

**Comment by CendioOssman** [comment]
Ah. That's most likely because they implement other encryption standards. There are unfortunately several.

RealVNC will never work because they only implement their own, secret system. What other have you tried? I think gtk-vnc should work.

**Comment by chrisplusplus** [comment]
I'm open for any suggestions for windows clients that can allow for encryption without SSH

**Comment by chrisplusplus** [comment]
Freedom of choice and some of our clients are just stubborn and don't want to switch.  Also, unless I'm missing something, the tigervnc client doesn't scale up resolution so it can only be as large as the host resolution.

**Comment by CendioOssman** [comment]
Fair enough. But then we need to have more specifics as to what clients/extensions are needed.

And you could always request support for VeNCrypt in those other clients as well.

**Comment by chrisplusplus** [comment]
I have no requirement from our clients for specific types of encryption, just an encrypted connection.  Thanks for helping me out
