### ISSUE TITLE
have a single key to minimize from fullscreen

### ISSUE THREAD

**Issue by allefeld** [TigerVNC/tigervnc#756]
Dear developers,

the following would be very useful to me.

I run vncviewer (as packaged by Debian, xtigervncviewer) fullscreen because the remote screen has the same size as the local one. I often do work in parallel locally and remotely, so I very often switch between the remote screen and the local one. Getting into the remote screen is simple, e.g. by using Alt-Tab to minimized vncviewer, but getting out of it is more complicated: press F8, select minimize by mouse (switch of input) or press multiple keys to select "minimize".

Would it be possible to have a single key to put vncviewer into minimize?

Thank you!

**Comment by CendioOssman** [comment]
I'm hesitant to add new keyboard shortcuts in the current system as we don't want to get issues with shortcuts blocking normal input.

However I'm experimenting with gathering all viewer shortcuts under a single system, e.g. Ctrl+Shift+<key>. There might be room for this option there. But even there we will try to keep things short and simple. Would a shortcut for fullscreen be sufficient? E.g. Ctrl+Shift+Enter, and then Alt+Tab to switch away.

**Comment by allefeld** [comment]
@CendioOssman, yes, a shortcut to toggle fullscreen would be sufficient, thanks!

I understand the reluctance to add shortcuts. A way to avoid that which I know from vinagre (which for other reasons doesn't work for me anymore) is to have a region on screen such that if the mouse pointer is there, keyboard input does not get sent to the remote system but processed locally (like when the mouse leaves the window in windowed mode). This means switching is: move mouse to region, Alt+Tab. This region can be tiny, e.g. the uppermost line of pixels, or only its central part.

Another possibility would be to have shortcuts only within the popup menu, e.g. after F8 opens the menu: f toggles fullscreen, m minimizes, q or e exits etc. Two keystrokes but easily and quickly done using only the keyboard, no need to navigate the menu.

**Comment by CendioOssman** [comment]
> Another possibility would be to have shortcuts only within the popup menu, e.g. after F8 opens the menu: f toggles fullscreen, m minimizes, q or e exits etc. Two keystrokes but easily and quickly done using only the keyboard, no need to navigate the menu.

We already have that. The shortcut for minimize is `z`. So `F8`, `z` should minimize the client on an English system.

**Comment by allefeld** [comment]
Sorry, didn't notice that. Great!

Then my suggestion would be to show  the respective keys in the menu.

**Comment by allefeld** [comment]
Deleted my previous comments because they are stupid. Sorry!

This solves my problem. Thanks!
