### ISSUE TITLE
VNC Config lost for X11 Display

### ISSUE THREAD

**Issue by vncuser91** [TigerVNC/tigervnc#757]
Hi Guys, 

So I am using TigerVNC for an application that runs on Linux, I need it to open its configuration via X11 Display using VNC, the problem is that by mistake, I exited the VNC Config options and I have no idea how to recover it, I am attaching screenshots of how it might look, and how it looks now, if someone can let me know how to recover it, I would appreciate it a lot! 

![screen1](https://user-images.githubusercontent.com/44585705/47673187-87c28c80-db79-11e8-83be-efc95a8da9c2.JPG)
![screen2](https://user-images.githubusercontent.com/44585705/47673188-87c28c80-db79-11e8-8dd3-6b1e3d536650.JPG)

**Comment by CendioOssman** [comment]
That menu is actually from your window manager, twm. So that's what you exited, and hence why you lost all the window decorations.

I'm afraid there is no clear way to recover. You need to start up twm in your session again. If you have a terminal open then you could try starting it there.
