### ISSUE TITLE
vncviewer-1.9.0 and X server consumption

### ISSUE THREAD

**Issue by whiteForgot** [TigerVNC/tigervnc#759]
I don't know why but vncviewer-1.9.0 takes 3-4 times more X server resource then previous version 1.7.1

Will it be stay forever?

**Comment by CendioOssman** [comment]
Hard do say without first figuring out what is causing it. We did do some tweaks to the new automatic repair function after release though. Could you test a nightly build and see if that helps? There is a link to them on the home page.

**Comment by whiteForgot** [comment]
Sorry, I didn't find the link to the nightly build on the home page -)
So I build vncviewer from the latest source code from github in the same manner as I build stable version 1.9.0
Well.. I get absolutely the same X server consumption (about 3 times higher then than branch 1.7.xx)

**Comment by CendioOssman** [comment]
It's the X server that needs to be updated in this case, not the viewer. Could you try that?

Or are you saying that it's the X server on the client that is using more resources?

**Comment by whiteForgot** [comment]
Ok, I have notebook with Linux and X Server 1.20.1
I run vncviewer on this notebook.
If I run vncviewer-1.9.0 than X server show too high  load.
About 3 times higher than I use vncviewer-1.7.1 on the same video sample.

**Comment by CendioOssman** [comment]
No response, closing.
