### ISSUE TITLE
Unable to type chars with AltGr on Windows 10 touch keyboard

### ISSUE THREAD

**Issue by accetto** [TigerVNC/tigervnc#760]
Hello,

I've found, that it is not possible to type characters that require **AltGr** (right ALT) when using touch keyboards on Windows 10.

Unfortunatelly, the AltGr key must be used for typing characters like '@' or '€' (or a pipe) on keyboards with German, English (UK) and similar layouts.

An external Bluetooth keyboard works just fine.

It's not necessarily a TigerVNC's issue, but at the moment it seems like that.

I've found it while using the following configuration:

-  **TigerVNC Viewer 64-bit v1.9.0** on **Windows 10 Pro 64-bit** (English as the UI language)
- accessing a container created from [accetto/ubuntu-vnc-xfce-firefox-plus](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-firefox-plus/) based on [accetto/ubuntu-vnc-xfce](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce/~/dockerfile/) (Ubuntu 18.04, Xfce, TigerVNC 1.8.0)
- tested with touch keyboards with **German (Germany)** and **English (UK)** layouts

Regards
accetto

**Comment by CendioOssman** [comment]
I can reproduce this here, and it seems like the touch keyboard is not properly emulating a physical one. AltGr is supposed to send Ctrl_L+Alt_R on Windows, but instead it sends Ctrl_L+Alt_L.

So I'd say this is a bug in Windows, not in TigerVNC. I can reproduce the problem in Firefox as well. But I doubt they'll fix this anytime soon, so we probably need to find a workaround... :disappointed:

**Comment by CendioOssman** [comment]
Could you try the 1.8.0 client? I think the older workaround we had for AltGr on Windows might avoid this issue.

**Comment by accetto** [comment]
Thanks a lot for the prompt response. I've just tested the 1.8.0 client (viewer, x64) and it's unfortunatelly the same. I've suspected something like you've described above. :(
What was the older workaround?

**Comment by CendioOssman** [comment]
It did a fake release of Ctrl and Alt before sending other keys. But I guess it also expected a right Alt.

I've looked deeper in to this and I've made a fix in 0f1c63060cc000ddb8b15391b1349ab6653184ba. If you try the next nightly build then that should solve this problem.

**Comment by CendioOssman** [comment]
Also, to clarify. This fixes the issue where the touch keyboard is actually showing the AltGr key. The standard mode is unfortunately less well behaved and I'm not sure if that can be fixed.

**Comment by accetto** [comment]
Sorry for asking, but where can I find the nightly build for Windows? I've looked [here](http://tigervnc.bphinz.com/nightly/) and I didn't find anything new for Windows. The best would be the stand-alone viewer 64-bit.

**Comment by bphinz** [comment]
A recent commit broke the nightly builds and I haven't had time to fix it
yet.
