### ISSUE TITLE
mojave (10.14.1): gray on authentication

### ISSUE THREAD

**Issue by gnawhleinad** [TigerVNC/tigervnc#767]
I'm running into an issue where all the TigerVNC dialogs / UI is gray'd:

<img width="1198" alt="screen shot 2018-11-21 at 8 06 30 pm" src="https://user-images.githubusercontent.com/674134/48881312-95aaac80-edc9-11e8-909c-d06ca202b084.png">

Is there anything I can do to help debug this issue...?

**Comment by CendioOssman** [comment]
Ehmm... Odd. Is this using our official 1.9.0 build?

**Comment by gnawhleinad** [comment]
> Ehmm... Odd. Is this using our official 1.9.0 build?

Yes, installed via `brew`. I’ve reproduced this on two machines (running Mojave).

**Comment by bphinz** [comment]
Installed via brew?  That would imply that it’s not our build but yours...
There is an open Fltk build describing this behavior:

http://www.fltk.org/str.php?L3496

The bug says that it happens when the binay is linked on Mojave, so can you
try installing from our dmg and see if that works?

-brian

**Comment by gnawhleinad** [comment]
> Installed via brew? That would imply that it’s not our build but yours...

@bphinz, ah, I mistakenly thought the `brew` was a `cask`. My apologies for the misunderstanding.  

> The bug says that it happens when the binay is linked on Mojave, so can you try installing from our dmg and see if that works?

:+1:, I can try and report back!

Jumping a couple steps, _if that works_, is the preferred long term solution to (either):

- apply / add the `patch`es mentioned in http://www.fltk.org/str.php?L3496 to [`contrib/fltk`](https://github.com/TigerVNC/tigervnc/tree/master/contrib/fltk)
- apply / add the `patch`es directly to `brew` in [`Formula/tiger-vnc.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tiger-vnc.rb)

?

**Comment by gnawhleinad** [comment]
> The bug says that it happens when the binay is linked on Mojave, so can you try installing from our dmg and see if that works?

@bphinz, unfortunately, installing from the `dmg` did not work.

**Comment by CendioOssman** [comment]
> Jumping a couple steps, _if that works_, is the preferred long term solution to (either):
> 
>   * apply / add the `patch`es mentioned in http://www.fltk.org/str.php?L3496 to [`contrib/fltk`](https://github.com/TigerVNC/tigervnc/tree/master/contrib/fltk)
> 
>   * apply / add the `patch`es directly to `brew` in [`Formula/tiger-vnc.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tiger-vnc.rb)

The latter I'd say. This is an FLTK issue, not a TigerVNC specfic one.

@bphinz, that `contrib/fltk` directory isn't really relevant these days as people should be running a current version of FLTK. I see that some of the builds aren't though. Something you could have a look at?

**Comment by bphinz** [comment]
I'm OK with applying those patches to the Fltk libraries that we use to build the dmg but I agree with Pierre that we shouldn't be carrying around patches to Fltk.

> @bphinz, that contrib/fltk directory isn't really relevant these days as people should be running a current version of FLTK. I see that some of the builds aren't though. Something you could have a look at?

Which builds are you referring to?  I updated them all recently.  The Ubuntu trusty package should be the only one that's a little bit questionable since it's using the distro's native libfltk-1.3 (Fltk 1.3.2).  We should probably remove the el5 and ubuntu-precise directories under contrib/packages altogether since we're no longer supporting those...

**Comment by gnawhleinad** [comment]
> The latter I'd say. This is an FLTK issue, not a TigerVNC specfic one.

FWIW, I'm testing the following:

>```
> $ diff fltk.rb ~/Homebrew/homebrew-core/Formula/fltk.rb
> 9,24d8
> <   stable do
> <     url "http://www.fltk.org/software.php?VERSION=1.3.4&FILE=fltk/1.3.4/fltk-1.3.4-2-source.tar.gz"
> <     sha256 "5a14360b0aede39555be6b8e6baf506db2fa383f7a1ac2c863245c61e6c9384b"
> < 
> <     # http://www.fltk.org/str.php?L3496
> <     patch do
> <       url "http://www.fltk.org/strfiles/3496/mojave.diff"
> <       sha256 "77ad325aa3089f4055975d9ec241a11ddedf7ec11d736249cc38267f4516a96b"
> <     end
> < 
> <     patch do
> <       url "http://www.fltk.org/strfiles/3496/mojave_clang.diff"
> <       sha256 "6b4051b06673d9aabaae3ae2419aa83b6bafb8c456553f383083445cbb358028"
> <     end
> <   end
> < 
>```

>```
> $ diff tiger-vnc.rb ~/Homebrew/homebrew-core/Formula/tiger-vnc.rb 
> 16c16
> <   depends_on "fltk" => :build
> ---
> >   depends_on "fltk"
>```

**Comment by gnawhleinad** [comment]
> < depends_on "fltk" => :build

:point_up: was my mistake. There is no edits needed to `tiger-vnc.rb`.

> $ diff fltk.rb ~/Homebrew/homebrew-core/Formula/fltk.rb

Unfortunately, I ran into issues applying these patches to `fltk-1.3.4-2-source.tar.gz`. I ran a `tiger-vnc` build against http://fltk.org/pub/fltk/snapshots/fltk-1.4.x-r13130.tar.gz (on Mojave) and did not run into the gray'd window.

**Comment by bphinz** [comment]
I'm definitely not keen on building against the fltk development branch, so we'll need to see if those patches can be backported to the stable release.

**Comment by gnawhleinad** [comment]
> I'm definitely not keen on building against the fltk development branch, so we'll need to see if those patches can be backported to the stable release.

@bphinz, agreed, it was only to quickly test whether the patches would address the gray'd issues.

I've been trying to manually backport the changes to 1.3.x but thus far haven't had too much luck. I'll continue to work and report back if I can get a successful build!

**Comment by CendioOssman** [comment]
> Which builds are you referring to? I updated them all recently. The Ubuntu trusty package should be the only one that's a little bit questionable since it's using the distro's native libfltk-1.3 (Fltk 1.3.2). We should probably remove the el5 and ubuntu-precise directories under contrib/packages altogether since we're no longer supporting those...

Yeah, both trusty and precise are referring to 1.3.2. And both el5 and el6 still have a bunch of patches in their SOURCES directory. I would prefer if we can remove all patches to avoid any confusion.

**Comment by CendioOssman** [comment]
> I'm definitely not keen on building against the fltk development branch, so we'll need to see if those patches can be backported to the stable release.

Is your build system using the new SDK so you have to include these changes for our official builds?

**Comment by bphinz** [comment]
On Fri, Nov 30, 2018 at 8:36 AM Pierre Ossman (Work account) <
notifications@github.com> wrote:

> Is your build system using the new SDK so you have to include these
> changes for our official builds?
>
No, I'm building on High Sierra using the 10.7 SDK, so based on what's said
in STR 3496, this should not even be happening with our DMG.  I don't have
a machine running Mojave to verify this though

**Comment by gnawhleinad** [comment]
> I've been trying to manually backport the changes to 1.3.x but thus far haven't had too much luck. I'll continue to work and report back if I can get a successful build!

I tried using [`branch-1.3`](https://github.com/fltk/fltk/tree/branch-1.3) but I'm getting a different issue:

<img width="1432" alt="screen shot 2018-12-05 at 1 08 16 am" src="https://user-images.githubusercontent.com/674134/49495995-5b5df800-f82a-11e8-8f3c-3772bcd2fc11.png">

where the remote desktop only occupies the bottom left-hand corner...

I'll report more as I investigate...

**Comment by gnawhleinad** [comment]
> I tried using [`branch-1.3`](https://github.com/fltk/fltk/tree/branch-1.3) but I'm getting a different issue:

same issue using `master`.

**Comment by CendioOssman** [comment]
This is when doing your own builds? And it works fine when using our builds?

**Comment by gnawhleinad** [comment]
> This is when doing your own builds?

Yes. To be explicit, the issue I'm seeing in https://github.com/TigerVNC/tigervnc/issues/767#issuecomment-444382381 was **only** from my own builds.

> And it works fine when using our builds?

:+1:!

**Comment by CendioOssman** [comment]
So I'm afraid there isn't much we can do in TigerVNC in that case. I suggest continuing the discussion with the FLTK folks. Feel free to add more notes here though if something interesting happens. But I'll go ahead and close this issue as we cannot really have issues open for things we cannot control.
