### ISSUE TITLE
"-AcceptSetDesktopSize" option for x0vncserver

### ISSUE THREAD

**Issue by mauzi** [TigerVNC/tigervnc#769]
Please add "-AcceptSetDesktopSize" option for x0vncserver.
We are using VNC to access our billboard/digital signage system. A misconfigured vnc viewer can f*ck off the display layout. Thanks so much.

**Comment by CendioOssman** [comment]
Sorry about that. We disabled it in 0a0e582597be681488b91eb818c8a1963d13adbf but forgot to re-enable it in 242c5b2c8af6d89a34ff83089e9e724e32dcb279. Should be fixed in 946a5e9ca171a3999e99e19e6e6defac13547251.

**Comment by mauzi** [comment]
Great!
Please mention it in the manpage as well.
Thanks,
--
Gergely EGERVARY

> Should be fixed in 946a5e9 
> <https://github.com/TigerVNC/tigervnc/commit/946a5e9ca171a3999e99e19e6e6defac13547251>.

**Comment by CendioOssman** [comment]
Good point. man page fixed in 7af4449036b877727b63a79ec95b9927bdef1566.
