### ISSUE TITLE
Xtigervnc fails to start VNC extension with -localhost ; assumes IPv6 is present

### ISSUE THREAD

**Issue by osd1000** [TigerVNC/tigervnc#77]
Ubuntu 14.04.1 LTS
Package version 1.3.90+20141120git59c5a55c-3ubuntu1

When I start Xvnc with the -localhost argument, I get the error:

vncext:      vncExtInit: unable to bind listening socket: Cannot assign
              requested address (99)

Using strace I see:
bind(6, {sa_family=AF_INET6, sin6_port=htons(5903), inet_pton(AF_INET6, ":
:1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EADDRNOTAVAIL (Can
not assign requested address)

...which will not work on this system because IPv6 is disabled on all network interfaces.

Thanks,

Owen

**Comment by CendioOssman** [comment]
I've added parameters to disable IPv6 now. Should probably still implement the dual socket approach, but this provides a workaround.

**Comment by twaugh** [comment]
I have work in progress on this, but have been pressed for time this month due to other issues.

**Comment by twaugh** [comment]
I've been working on this today. Here's where I'm up to:
https://github.com/twaugh/tigervnc/commits/multisocket

The TcpFilter class still needs some work, but what do you think about the general approach?

**Comment by CendioOssman** [comment]
A whole bunch of comments added on the commits. :)

**Comment by twaugh** [comment]
I've updated (forced update) the branch, addressing your comments. See what you think.

**Comment by CendioOssman** [comment]
Some minor comments, but in general it looks very good.

**Comment by CendioOssman** [comment]
Closing this now as we've merged the proper fix.
