### ISSUE TITLE
Alt key not passed to OSX VNC server

### ISSUE THREAD

**Issue by teras** [TigerVNC/tigervnc#770]
Hello people and thank you for this software.

I have an issue with Linux (TigerVNC) client and default OSX Server.
Keyboard is a Microsoft keyboard and I am using the "us" layout under Linux (host).

I know that there are some discussion on whether/how the Alt / Windows(Command) / Control keys should be mapped and some were reversed.

But for a strange reason, although Control & Windows produce the "correct" code ("Control" and "Command"), the Alt key still produced the "Command" code.

I was expecting either the "Alt" key to be reversed with the "Windows" key, or to actually produce the "Alt" keycode. Now I am practically missing an importand modifier.

Is there any way to overcome this problem? What should I do?

**Comment by CendioOssman** [comment]
Unfortunately the macOS server has been known to be incompatible with standard VNC in many ways, so there might not be a fix for this. But let's check that there isn't anything wrong with your client.

Please start the client with `-Log *:stderr:100` and see what it says when you press and release the left and right Alt keys.

**Comment by teras** [comment]
I've got this result

```
Tue Nov 27 11:03:26 2018
 Viewport:    Key pressed: 0x0038 => XK_Alt_L (0xffe9)

Tue Nov 27 11:03:27 2018
 Viewport:    Key released: 0x0038 => XK_Alt_L (0xffe9)

Tue Nov 27 11:03:28 2018
 Viewport:    Key pressed: 0x00b8 => XK_Alt_R (0xffea)

Tue Nov 27 11:03:29 2018
 Viewport:    Key released: 0x00b8 => XK_Alt_R (0xffea)
```

To my unspecialized eyes it seems that everything should be OK, but it isn't.
Any hints on how to proceed with debugging?

**Comment by CendioOssman** [comment]
Not really, I'm afraid. At this point we can rule out the client, so there is something wrong with the macOS server and how it uses those key events. And I don't know how to debug their server, or where to report issues to them. :/

I don't see much we can do here and I'm afraid I'll have to direct you to talk to Apple.
