### ISSUE TITLE
defaultXStartup includes "vncserver -kill \$DISPLAY\n"

### ISSUE THREAD

**Issue by YLCFQ** [TigerVNC/tigervnc#773]
OS: CentOS 7

After upgrading tigervnc-server.x86_64 from 1.8.0-5.el7 to 1.8.0.13.el7. "vncserver -kill \$DISPLAY\n" is added to default xstartup script. Is this expected?

1.8.0-5.el7
$defaultXStartup
    = ("#!/bin/sh\n\n".
       "unset SESSION_MANAGER\n".
       "unset DBUS_SESSION_BUS_ADDRESS\n".
       "exec /etc/X11/xinit/xinitrc\n");

1.8.0.13.el7
$defaultXStartup
    = ("#!/bin/sh\n\n".
       "unset SESSION_MANAGER\n".
       "unset DBUS_SESSION_BUS_ADDRESS\n".
       "/etc/X11/xinit/xinitrc\n".
       "vncserver -kill \$DISPLAY\n");

**Comment by CendioOssman** [comment]
I'm afraid that is Red Hat's packaging and not ours. So you'll have to report the issue to them. We can't do anything about it.
