### ISSUE TITLE
TigerVNC-1.8.0-13.el7 GUI unresponsive

### ISSUE THREAD

**Issue by aaronvh** [TigerVNC/tigervnc#777]
Hi,

We patched our server yesterday (12/12/2018) and some of the patches were:
- Updated     tigervnc-license-1.8.0-5.el7.noarch                                              @prd-rhel-7
  Update                       1.8.0-13.el7.noarch                                             @prd-rhel-7
- Updated     tigervnc-server-1.8.0-5.el7.x86_64                                               @prd-rhel-7
Update                      1.8.0-13.el7.x86_64                                              @prd-rhel-7
- Updated     tigervnc-server-minimal-1.8.0-5.el7.x86_64                                       @prd-rhel-7
Update                              1.8.0-13.el7.x86_64                                      @prd-rhel-7
This morning our end users experienced unresponsiveness while for example typing in the terminal.  It seemed that the keyboard and mouse were workingly properly but not the refresh of the graphical part because drag the terminal causing it to redraw allways made visible what was typed.

**Solution:**
We downgraded to 1.8.0-5.el7 for all three packages and this solved the unresponsive GUI issue.

We would like to avoid this issue in our next patching.  Can you investigate, please?

**Comment by CendioOssman** [comment]
Those are red hat packages, and not from us. So I'm afraid you'll have to file a bug report with them. There is nothing we can do about their packaging.

**Comment by aaronvh** [comment]
Okido, thx for the info!
