### ISSUE TITLE
Password Dialog not show when connecting from MacOS vncviewer

### ISSUE THREAD

**Issue by gsshiva** [TigerVNC/tigervnc#779]
Client OS : **MacOS 10.13.6 (High Sirerra)**
Tiger VNC Viewer version : **1.7.0 and 1.9.0**

Server OS : **Ubuntu 18.04.1 (Linux version 4.15.0-38-generic)**
Tiger VNC Server version
```
Xvnc TigerVNC 1.7.0 - built Dec  5 2017 09:25:01
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
```

I have been running a vncserver on :1 display for the last 6 days.

Everytime I try to connect from the viewer, it will not show the password screen the first time, it would always take a couple of tries before I get the dialog. Today it got really worse and the dialog never appeared at all.

I just see the following line in the server log file when I connect from the viewer.
```
Sun Dec 16 19:23:35 2018
 Connections: accepted: X.X.X.X::49429
```

and the client logs shows (_from /tmp/vncviewer.log_)
```
Sun Dec 16 18:49:58 2018
 DecodeManager: Detected 4 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 TcpSocket:   Connecting to xxx [X.X.X.X] port 5901
 CConn:       connected to host xxx port 5901
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
```

When there is a succssful session, I see the following additional lines on the client side
```
CConnection: processing security types message
 CConnection: Server offers security type VeNCrypt(19)
 CConnection: Server offers security type VncAuth(2)
 CConnection: Choosing security type VeNCrypt(19)
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CConnection: processing security message
 CVeNCrypt:   Server offers security type VncAuth (2)
 CConnection: processing security message
 CVeNCrypt:   Server offers security type TLSVnc (258)
 CVeNCrypt:   Choosing security type VncAuth (2)
```

At this point I am not clear as to whether it is a client or a server issue that is preventing the protocol to proceed.

Any help or advice for debugging this further would be appreciated. Thanks

**Comment by CendioOssman** [comment]
If it just stops like that, then it does sound like some kind of network issue. Perhaps a firewall that gets upset and blocks the traffic?

1.7.0 is rather old though. Could you try 1.9.0 on the server?

**Comment by CendioOssman** [comment]
No response. Closing.
