### ISSUE TITLE
Quits on macOS 10.14.1 Mojave

### ISSUE THREAD

**Issue by rubenerd** [TigerVNC/tigervnc#784]
Hey guys, I've reproduced this on two separate 10.14.1 Mojave machines.

Opening the latest stable binary in Finder from [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/tigervnc-viewer.rb) (1.9.0) or the latest [nightly build](http://tigervnc.bphinz.com/nightly/) (1.9.80 at time of writing) bounces in the Dock once, then quits.

Running the binary directly works from the shell:

    $ /Applications/TigerVNC\ Viewer\ 1.9.80.app/Contents/MacOS/TigerVNC\ Viewer
 
In the latest stable release I get these errors in the shell, presumably because it's 32-bit:

    TigerVNC Viewer 32-bit v1.9.0
    Built on: 2018-08-05 14:36
    Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
    See http://www.tigervnc.org for information on TigerVNC.
    /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8 [..]

But the latest nightly builds only show this expected output:

    TigerVNC Viewer 64-bit v1.9.80
    Built on: 2019-01-01 03:44
    Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
    See https://www.tigervnc.org for information on TigerVNC.

So it only fails when launched from the Finder. Anyone else seeing a similar issue?

Cheers.

**Comment by CendioOssman** [comment]
I'm afraid I cannot reproduce this issue with the macOS 10.14.1 machine I have here. Could you check if you have some very restrictive GateKeeper settings enabled?

@bphinz, can you reproduce this issue?

**Comment by rubenerd** [comment]
Thanks @CendioOssman. On a hunch I created a new user account on one of the Macs I tested before, and both the stable and latest nightly builds launch!

IIRC I haven't messed with any GateKeeper settings, but I'll chalk it up to config unique to my macOS installs.

Appreciate your quick response, feel free to close.

**Comment by CendioOssman** [comment]
It could still be interesting to figure out why things don't work for you. Could you try moving your `~/.vnc` directory and see if that has any effect?

**Comment by h3adache** [comment]
Had the same issue and moving the ~/.vnc and reopening seemed to fix it for me @CendioOssman

**Comment by rubenerd** [comment]
That did the trick! Thanks @CendioOssman.

If its useful, I had RealVNC'c VNC Viewer.app on both these machines as well. It could be TigerVNC launched on a new user account because VNC Viewer.app had never been used in it and initialised that folder. Not sure if was a similar circumstance to @h3adache .

**Comment by CendioOssman** [comment]
Could you guys share you broken `.vnc` directories with us? We don't really want any situation where the viewer completely refuses to start.
