### ISSUE TITLE
Close the graphics desktop and start only one graphics application  is grey  desktop  and black mouse icon

### ISSUE THREAD

**Issue by xjspace** [TigerVNC/tigervnc#785]
Close the graphics desktop and start only one graphics application  is grey  desktop  and black mouse icon
bug：   grey X desktop and  black mouse icon. it'nt  worked

1. ubuntu 18.04 
sudo systemctl set-default multi-user.target
go to text mode.
2. vncserver （Premise:Installation is complete and running normally.
3. novnc （Premise:Installation is complete and running normally.）
4. xinit /usr/bin/paraview -- /usr/bin/Xorg   （Premise:paraview Installation is complete and running normally.）

**Expected behavior**

**Screenshots**
screenshots1
https://github.com/xjspace/tigervnc/blob/master/18.png
screenshots2
https://github.com/xjspace/tigervnc/blob/master/20190102151715.png
screenshots3

**Client (please complete the following information):**
 - OS: [e.g. ubuntu18.04]
 - noVNC client: [e.g. novnc]
 - noVNC client version: [e.g. 1.8.0]

**Server (please complete the following information):**
 - OS: [e.g. ubuntu 18.04]
 - VNC server: [e.g. TigerVNC]
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver:1`]

**Additional context**

**Comment by CendioOssman** [comment]
This seems to be the exact same issue as you specified in #782. As I mentioned there, please do not use `xinit`. Instead put the commands you want in `.vnc/xstartup` and it should work fine.

**Comment by xjspace** [comment]
but  not use xinit  paraview  Software does not work

$: /usr/bin/paraview --/usr/bin/Xorg 
paraview：cannot  connect  to X server。

**Comment by xjspace** [comment]
https://github.com/xjspace/tigervnc/blob/master/novnc.png
please Can you help write a sample configuration of xstartup to make it work? with paraview？
