### ISSUE TITLE
write  a  xstartup config file sample  for  Text mode  +Gui(paraview) 

### ISSUE THREAD

**Issue by xjspace** [TigerVNC/tigervnc#786]
ubuntu 18.04    text mode  tigervnc    runing  paraview    +novnc  brower 

Text mode  +Gui(paraview) 

write  a  xstartup config file sample。please help me，thanks

**Comment by CendioOssman** [comment]
Please don't open new requests with the same issue. You've already asked about this in #782 and #785.
