### ISSUE TITLE
Monitor size not propagated properly

### ISSUE THREAD

**Issue by hofmandl1** [TigerVNC/tigervnc#789]
Inside vnc session in a gnome-terminal:

> xrandr 
Screen 0: minimum 32 x 32, current 3600 x 1080, maximum 32768 x 32768
VNC-0 connected primary 1680x1050+1920+0 0mm x 0mm
   1680x1050     60.00*+
   [..]
VNC-1 connected 1920x1080+0+0 0mm x 0mm
   1920x1080     60.00*+
   [..]

Outside:
> xrandr 
Screen 0: minimum 320 x 200, current 3600 x 1080, maximum 8192 x 8192
DisplayPort-0 connected primary 1680x1050+1920+0 (normal left inverted right x axis y axis) 473mm x 296mm
   1680x1050     59.95*+
   [..]
DVI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 598mm x 336mm
   1920x1080     60.00*+

So it seems, montior width and size are not propagated or propagated as 0mm which leads to problems with some client applications.

**Client (please complete the following information):**
 - OS: ubuntu1804 64bit
 - VNC client: tigervnc
 - VNC client version: 1.9.0 64 bit
 - Client downloaded from: bintray

**Server (please complete the following information):**
 - OS: debian buster/sid 64bit
 - VNC server: tigervnc
 - VNC server version: 1.9.0
 - Server downloaded from: bintray
 - Server was started using: vncserver

The broken client application actually was an Eclipse Plugin because of SWT reporting a very high DPI due
to a floating division by zero when calculating DPI for image scaling.

**Comment by hofmandl1** [comment]
The java-wrapper function that returned 0 btw. was:
int widthMM = GDK.gdk_monitor_get_width_mm(pMonitor);
(I didn't debug this any further, the relation between the xrandr-output and the return-value of the function is just me guessing)

**Comment by CendioOssman** [comment]
Right, this is not something we transfer right now. If the client breaks, then it is a bug in that application though as not all monitors will reveal their physical dimensions. They are also very often wrong, so it's generally a very bad idea to calculate the DPI based on that information. Most systems today use an integer scaling value that you configure instead for high DPI handling.

I'm afraid it is not something we plan on adding at this point.
