### ISSUE TITLE
unable to build on Windows

### ISSUE THREAD

**Issue by jdtsillas** [TigerVNC/tigervnc#791]
Hi folks,

I'm trying to build on Windows 10 using mingw.

It's getting pretty far but fails in the linking phase:
```
[ 90%] Linking CXX executable vncviewer.exe
CMakeFiles/vncviewer.dir/objects.a(CConn.cxx.obj):CConn.cxx:(.text+0x36): undefined reference to `Fl::remove_timeout(void (*)(void*), void*)'
CMakeFiles/vncviewer.dir/objects.a(CConn.cxx.obj):CConn.cxx:(.text+0x71): undefined reference to `Fl::remove_fd(int)'
CMakeFiles/vncviewer.dir/objects.a(CConn.cxx.obj):CConn.cxx:(.text+0x26e): undefined reference to `Fl::remove_timeout(void (*)(void*), void*)'
CMakeFiles/vncviewer.dir/objects.a(CConn.cxx.obj):CConn.cxx:(.text+0x2a0): undefined reference to `Fl::remove_fd(int)'
. . .
```

My guess is the fltk lib was not located or added.

But I did install it:
```
==> Finished making: mingw-w64-fltk 1.3.4.2-1 (Wed, Jan 30, 2019  3:30:28 PM)
==> Installing package mingw-w64-i686-fltk with pacman -U...
```
And cmake seemed fine with it:
```
-- Found FLTK: C:/msys64/mingw32/lib/libfltk_images.dll.a;C:/msys64/mingw32/lib/libfltk.dll.a
```
So not sure what's going on there.

I'm trying to add a feature to disable vertical autoscroll for servers which use "offscreen" bitmap copies for backing store. x11vnc allows you to do that.

thanks!!!
-Jim.

**Comment by jdtsillas** [comment]
Please see attached.

[build_output.txt](https://github.com/TigerVNC/tigervnc/files/2837348/build_output.txt)

**Comment by samhed** [comment]
That log doesn't look complete. Did you try to build again after a broken build? Could you try building from scratch and send a new build log?

**Comment by samhed** [comment]
No response.
