### ISSUE TITLE
Compiling fails on windows  ( 'WTSGetActiveConsoleSessionId' was not declared )

### ISSUE THREAD

**Issue by ckox** [TigerVNC/tigervnc#792]
Hello,
I am getting the following error while trying to build under windows 
```
c:/tiger/tigervnc/win/rfb_win32/TsSessions.cxx:43:39: error: 'WTSGetActiveConsoleSessionId' was not declared in this scope
```
I can see that the function is defined in winbase.h as
```
#if _WIN32_WINNT >= 0x0501

WINBASEAPI
DWORD
WINAPI
WTSGetActiveConsoleSessionId(
    VOID
    );

#endif // (_WIN32_WINNT >= 0x0501)
```
also I can see "_WIN32_WINNT=0x0600" in the cmake files generated so I think that part is ok 

Do you have any ideas about this ? I can provide any other information if needed

Thanks in advance

**Comment by CendioOssman** [comment]
No idea. What does your build environment look like? We're mostly building with mingw on Linux here, so anything else might expose problems.

**Comment by ckox** [comment]
Thanks  a lot for the reply 

I have fixed the issue by using MSYS2 and mingw64

Now it builds and runs fine
