### ISSUE TITLE
Image compression by gpu

### ISSUE THREAD

**Issue by kahvis** [TigerVNC/tigervnc#793]
Is there anyway to replace legacy libjpeg-turbo with something that supports GPU accelrated compression. In case where the server has many users connected with vnc you could reduce CPU ( OpenCL ) load with that.

I am sorry if I have misunderstood something fundamental.

**Comment by CendioOssman** [comment]
You can replace libjpeg with anything you like that follows the same API. I'm not aware of anything like that that uses the GPU though.

It's also not an obvious improvement as you'll spend a lot of resources shuffling data back and forth from the GPU. You'll have to test and see if it helps.

**Comment by kahvis** [comment]
I was just browsing when I hit this, https://github.com/ianhuang-777/guetzli-cuda-opencl
