### ISSUE TITLE
Best way to get latest tigervncserver on Ubuntu 18.04

### ISSUE THREAD

**Issue by HowardLander** [TigerVNC/tigervnc#794]
Hi all

I am using TigerVNC with guacamole on some Ubuntu 18.04 amazon EC2 instances. Occasionally I'll get a reconnect message and the vncserver log will have some entries like:
```
 Connections: closed: 127.0.0.1::37124 (Clean disconnection)
 EncodeManager: Framebuffer updates: 15
 EncodeManager:   ZRLE:
 EncodeManager:     Indexed RLE: 14 rects, 15.5 kpixels
 EncodeManager:                  854 B (1:72.7963 ratio)
 EncodeManager:     Full Colour: 33 rects, 2.0272 Mpixels
 EncodeManager:                  2.97235 MiB (1:2.60182 ratio)
 EncodeManager:   Total: 47 rects, 2.0427 Mpixels
 EncodeManager:          2.97317 MiB (1:2.62105 ratio)
 TLS:         TLS session wasn't terminated gracefully
```
Interestingly this seems to be happening mostly if not exclusively using Safari as the browser rather than Chrome or Firefox.  Not quite sure why that should matter.  But I also noticed that the version of tiger on these machines that you get from apt-get is 1.7.0.  So rather than trying to spend a bunch of time tracing this down, I thought maybe the best choice would be to install 1.9.  What's the easiest way to do this? I did download tigervnc-1.9.0.x86_64.tar.gz from bintray, but there doesn't seem to be an install script.  I'm guessing I'm missing something obvious, but I'm not sure what!

Thanks much for any help
Howard

**Comment by CendioOssman** [comment]
To start with I think you should poke Ubuntu a bit. If they get enough interest they will hopefully make sure to always ship the latest version.

The .tar.gz file is meant to be unpacked in `/` to get a "normal" installation. But you could also try the 16.04 packages. They might work on 18.04 as well. You could also try rebuilding the source deb package on 18.04.

And if all else fails, you could do a build and install by hand by following BUILDING.txt.

Hope this helps. :)

**Comment by jcrben** [comment]
Note that these days there is a Debian package - check out https://salsa.debian.org/debian-remote-team/tigervnc - I ran `sudo apt install tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer` as suggested at https://www.cyberciti.biz/faq/install-and-configure-tigervnc-server-on-ubuntu-18-04/
