### ISSUE TITLE
Apparent Memory leak in 1.9.0

### ISSUE THREAD

**Issue by holderl5** [TigerVNC/tigervnc#797]
**Describe the bug**

XTigerVNC quickly becomes largest user of memory on a relatively quiet system.  After 6 days, memory usage is about 1.5GB.  Previously in Kubuntu 18.04, I could leave the VNC server running for months without issue.

This is in Kubuntu 18.10:
dpkg -l | grep tige
ii  tigervnc-common                               1.9.0+dfsg-1                                amd64        Virtual network computing; Common software needed by servers
ii  tigervnc-standalone-server                    1.9.0+dfsg-1                                amd64        Standalone virtual network computing server

**To Reproduce**
1.  Starting server with:
vncserver -geometry 1600x900

**Expected behavior**
Normal memory usage

I just restarted the VNC desktop a few minutes ago, so I will look at the previous memory bug reports to see what debugging information I can provide.  I would be happy to run any commands or data dumps you need to help find the problem.  I am also thinking of installing the binaries provided on github to see if it is specific to ubuntu package.

**Comment by holderl5** [comment]
I am trying memleax now and will report back if it finds anything

**Comment by CendioOssman** [comment]
What does it look like in `top`? We had a report that turned out to be a bug in mesa where it would tell the server to keep allocating shared memory.

**Comment by holderl5** [comment]
Thanks for getting back to me.  So far memleax is not reporting anything.  I had a VM HOST reboot due to an update last night and elected to restart my tigervnc since all my SSH sessions would probably die anyway.  Here is what top is reporting now.  I will come back in a few days once it has grown.


top - 9:16:28 up 18 days, 17:25,  1 user,  load average: 0.01, 0.07, 0.11
Tasks: 204 total,   1 running, 203 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.8 us,  0.3 sy,  0.0 ni, 94.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   3147.3 total,    703.4 free,    919.9 used,   1524.0 buff/cache
MiB Swap:   2048.0 total,   1862.5 free,    185.5 used.   1685.6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                              
  985 sddm      20   0  980624  45296  11976 S   7.3   1.4   1973:57 sddm-greeter                                                                                                                                         
24718 knop      20   0  671032 369060 297772 S   1.0  11.5   3:13.25 Xtigervnc

**Comment by holderl5** [comment]
ok, it is just about time for me to reboot.  Here is the current output of top:

top - 13:33:25 up 22 days, 21:42,  1 user,  load average: 0.01, 0.26, 0.32
Tasks: 205 total,   1 running, 204 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.9 us,  0.4 sy,  0.0 ni, 94.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   3147.3 total,    236.8 free,    889.2 used,   2021.3 buff/cache
MiB Swap:   2048.0 total,   1052.0 free,    996.0 used.    433.1 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                             
24718 knop      20   0 2398240   1.7g   1.5g S   0.9  54.3  44:35.49 Xtigervnc

memleax has told me nothing, I am going to try one of the other libs that get loaded in with LD_PRELOAD

**Comment by bhairav13** [comment]
Hi.
I can confirm seeing the same issue on my end.  In 1 hour after starting the VNC session, the memory usage has grown to 5Gig.  In a few hours, it will top out at about 13Gig.

**Comment by ferkulat** [comment]
Hi,
this memory leak and other commits which fixed memory leaks by adding a few "delete", make me curious if you would like to get rid of this by using the tools C++11 and above give us.
Namely std::unique_ptr and std::shared_ptr.
I would like to try it. Unless you have strong opinions against it.
What do you think?

**Comment by CendioOssman** [comment]
I'm afraid this looks like that mesa bug I mentioned. Unfortunately that means that we cannot fix anything as it is pretty much working as intended from our end. You can find the bug report here:

https://bugs.freedesktop.org/show_bug.cgi?id=109641

Ubuntu doesn't seem to have a new enough version of Mesa, so I think you'll have to report this issue to Ubuntu so they can apply the fix.

**Comment by holderl5** [comment]
Thank you for providing the link to the actual problem.  I appreciate it, and I am sure it will help others as well.
