### ISSUE TITLE
Unable to use special key combinations as keyboard shortcuts

### ISSUE THREAD

**Issue by vrkorda** [TigerVNC/tigervnc#8]
I am not able to use certain special key combinations like 'Ctrl+Alt+Any printable character' or 'Shit + Alt + Any printable character' as keyboard shortcuts.

I observed that in Eclipse, similar combinations are used as shortcuts and they are working fine. However there is a key combination 'Shift + Ctrl+Alt+Right' used for quick context view under navigation and I am not able to fire this key combination to invoke the menu item.

I realized that this is an issue with FLTK library and I am not sure whether this is the right place to log the bug request.

Regards,
Venkat

**Comment by manfredg** [comment]
I just upgraded my TigerVNC client from 1.3.1 to 1.4.1 in openSuse and I am seeing the same issue. Emacs has become unusable because it makes extensive use of multikey shortcuts. As the previous poster has already mentioned, <C-S-_> which is bound to "undo" results in a non-functional C-7 being received by Emacs.
For the time being I have downgraded to version 1.3.1 again.

**Comment by headbank** [comment]
Just upgraded a client box (Gentoo) to 1.3.1, which the server (also Gentoo) has been on for some time, and this is hitting me too. ^TAB works, but ^C, ^X, ^V, ^T, ^S, ^W, ^L, ^K (all pretty crucial shortcuts especially in Firefox) are no longer working.

I remembered (too late!) that this problem emerged before, when upgrading from 1.2.0 and was fixed by downgrading the client back to 1.2.0. As that's no longer available (in Gentoo), tigervnc is no longer usable here. I now wish I'd made more noise about it at the time :(

**Comment by LicoMonch** [comment]
@headbank 
I'm using net-misc/tigervnc-1.3.1-r2 on my server and the clients v1.3.0 on Windows 7 and v1.3.1 on OS X (10.9 and 10.10) and all shortcuts you mentioned are working very well (in Firefox too).
You should re-check your setup.

**Comment by CendioOssman** [comment]
This problem occurs when you are using an old and unpatched FLTK. The fallback keyboard handling unfortunately cannot tell the difference between certain Ctrl combinations.

Are you seeing this with our latest official builds? If so we can have a look at it, otherwise you'll have to poke whoever did your builds.

**Comment by manfredg** [comment]
This is FLTK version 1.3.2 from the openSuse repos:

# zypper info libfltk1
Loading repository data...
Reading installed packages...


Information for package libfltk1:
---------------------------------
Repository: repo-oss
Name: libfltk1
Version: 1.3.2-10.1
Arch: x86_64
Vendor: openSUSE
Installed: Yes
Status: up-to-date
Installed Size: 1.6 MiB
Summary: FLTK Library
Description: [...]

**Comment by CendioOssman** [comment]
An unmodified FLTK 1.3.2 is insufficient to get full keyboard function in TigerVNC. SUSE needs to either update to 1.3.3, or apply the keyboard patches that are included with TigerVNC (assuming they haven't).

**Comment by manfredg** [comment]
FLTK 1.3.3 was submitted to the Factory build 15 hours ago but hasn't yet come through to the repositories. I'll try and install it as soon as I find the time.

**Comment by headbank** [comment]
I have x11-libs/fltk-1.3.3-r2 installed on the client and server here, with net-misc/tigervnc-1.3.1-r2 built against it. Both were built on the same day in both cases, but the client builds were when trouble began.

I will, as you suggest, pursue this downstream. I do note that the Gentoo ebuild no longer has a USE="internal-fltk" flag as it used to; AFAICT right now, this flag was dropped post-1.2.0 and later versions all simply use stock FLTK (that tallies with when they started pulling in FLTK as a dependency).

What I can conclude is that Gentoo's fltk-1.3.3 does not solve the problem as your internal version/patches did, for whatever reason.

**Comment by tken3** [comment]
On Fri, 2015-01-23 at 01:37 -0800, Pierre Ossman (Work account) wrote:
> Are you seeing this with our latest official builds?

The issue I saw was with your official, generic, binary builds.
(tigervnc-Linux-x86_64-1.4.*.tar.gz)

**Comment by tken3** [comment]
On Fri, 2015-01-23 at 10:06 -0700, Thomas Kennedy wrote:
> On Fri, 2015-01-23 at 01:37 -0800, Pierre Ossman (Work account) wrote:
> > Are you seeing this with our latest official builds?
> 
> The issue I saw was with your official, generic, binary builds.
> (tigervnc-Linux-x86_64-1.4.*.tar.gz)

Correction: I saw the problem with tigervnc-Linux-x86_64-1.4.0.tar.gz

I cannot get tigervnc-Linux-x86_64-1.4.1.tar.gz binaries to run at all.

**Comment by bphinz** [comment]
There was a build issue with the generic binaries for 1.4.1.  Can you
please try the binaries posted here: http://tigervnc.sourceforge.net/1.4.1/

I will be releasing a new set of official binaries to address today or
tomorrow.

Thanks,
-brian

**Comment by tken3** [comment]
On Fri, 2015-01-23 at 10:41 -0800, Brian Hinz wrote:
> There was a build issue with the generic binaries for 1.4.1. Can you 
> please try the binaries posted here:
> http://tigervnc.sourceforge.net/1.4.1/ 

Using the client and server from:
http://tigervnc.sourceforge.net/1.4.1/xc/x86_64/tigervnc-Linux-x86_64-1.4.1.tar.gz
everything works great!

C-Space and C-S-_ both work as expected.

Thanks!

**Comment by manfredg** [comment]
Still the same problem here unfortunately. 

Presumably the binary with fltk compiled in, that tken3 used works fine, but the problem with C-S-_ in emacs persists when using the newest FLTK in the openSUSE reositories.

Tigervnc 1.4.1 with FLTK 1.3.3:

> zypper info tigervnc libfltk1
Loading repository data...
Reading installed packages...


Information for package tigervnc:
---------------------------------
Repository: repo-oss
Name: tigervnc
Version: 1.4.1-1.1
Arch: x86_64
Vendor: openSUSE
Installed: Yes
Status: up-to-date
Installed Size: 487.2 KiB
Summary: A high-performance, platform-neutral implementation of VNC
[...]

Information for package libfltk1:
---------------------------------
Repository: repo-oss
Name: libfltk1
Version: 1.3.3-1.1
Arch: x86_64
Vendor: openSUSE
Installed: Yes
Status: up-to-date
Installed Size: 1.2 MiB
Summary: FLTK Library
[...]

**Comment by CendioOssman** [comment]
Unfortunately the new FLTK has to be available when TigerVNC is built, not simply installed afterwards. Which I suspect is not the case given the low revision number of TigerVNC? So SUSE needs to trigger a rebuild of the TigerVNC package now that they've upgraded FLTK.

**Comment by manfredg** [comment]
Just tried the latest build tigervnc-1.4.1-58.3 (9h ago) from
http://download.opensuse.org/repositories/X11:/XOrg/openSUSE_Factory/

This one works as expected, ie C-S-_ in emacs finally binds to "undo" again rather than producing C-7.

Great, thanks.

**Comment by CendioOssman** [comment]
Great. I'll consider this issue closed then, even if it'll be some time before updated versions of FLTK and TigerVNC trickle down to all distributions.

**Comment by skoehler** [comment]
When using tigervnc 1.3.1 on Gentoo (built with fltk 1.3.1) I'm not able Ctrl+F in my editors (should bring up the search). Using the menu key and setting Ctrl manually works. Is this the issue discussed here? What's the resolution for people like me that are stuck with tigervnc 1.3.1 on Gentoo? Does upgrading fltk and rebuilding tigervnc help? Or is it a problem with the tigervnc sources? If so, what's the patch so I can tell the Gentoo maintainers to incorporate it in their package?

**Comment by CendioOssman** [comment]
The best solution is to upgrade both FLTK and TigerVNC to the latest versions. If you're stuck on 1.3.1 then you are going to have to use an older FLTK with the patches that were included with TigerVNC 1.3.1.

**Comment by skoehler** [comment]
Where would I find those patches? I'm looking at the tigervnc 1.3.1 tarball right now. Could you be a little bit more specific?

**Comment by CendioOssman** [comment]
It's described in BUILDING.txt. For 1.3.1 they are downloaded from FLTK's issue tracker.

**Comment by ahmadalli** [comment]
I'm experiencing the same issue with tightvnc as client and x11vnc as server. I can't send Shift + F5 to the server.

**Comment by ahmadalli** [comment]
This was x11vnc issue
