### ISSUE TITLE
Vncserver not working for me on CentOS 7.5

### ISSUE THREAD

**Issue by jagga13** [TigerVNC/tigervnc#808]
**Describe the bug**
Running vncserver on my CentOS 7.5 workstation gives me a black screen.  In the logs it looks like every time I startup vncserver I get these messages:

Mar 15 15:46:58 woodacre org.a11y.Bus: Activating service name='org.a11y.atspi.Registry'
Mar 15 15:46:58 woodacre org.a11y.Bus: Successfully activated service 'org.a11y.atspi.Registry'
Mar 15 15:46:58 woodacre org.a11y.atspi.Registry: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Mar 15 15:46:58 woodacre gnome-session-binary[4931]: ERROR: Failed to connect to system bus: Exhausted all available authentication mechanisms (tried: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS) (available: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS)#012aborting...
Mar 15 15:46:58 woodacre gnome-session: gnome-session-binary[4931]: ERROR: Failed to connect to system bus: Exhausted all available authentication mechanisms (tried: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS) (available: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS)
Mar 15 15:46:58 woodacre gnome-session: aborting...
Mar 15 15:46:58 woodacre kernel: traps: gnome-session-b[4931] trap int3 ip:7f9ffe4213f1 sp:7ffe8ef32d90 error:0
Mar 15 15:46:58 woodacre abrt-hook-ccpp: Process 4931 (gnome-session-binary) of user 17229 killed by SIGTRAP - dumping core
Mar 15 15:46:58 woodacre abrt-server: Duplicate: core backtrace
Mar 15 15:46:58 woodacre abrt-server: DUP_OF_DIR: /var/spool/abrt/ccpp-2018-12-20-12:45:18-9250
Mar 15 15:46:58 woodacre abrt-server: Deleting problem directory ccpp-2019-03-15-15:46:58-4931 (dup of ccpp-2018-12-20-12:45:18-9250)
Mar 15 15:46:58 woodacre abrt-server: Email address of sender was not specified. Would you like to do so now? If not, 'user@localhost' is to be used [y/N] 
Mar 15 15:46:58 woodacre abrt-server: Email address of receiver was not specified. Would you like to do so now? If not, 'root@localhost' is to be used [y/N] 
Mar 15 15:46:58 woodacre abrt-server: Sending an email...
Mar 15 15:46:58 woodacre abrt-server: Sending a notification email to: root@localhost
Mar 15 15:46:58 woodacre abrt-server: Email was sent to: root@localhost
Mar 15 15:47:28 woodacre dbus[965]: [system] Connection has not authenticated soon enough, closing it (auth_timeout=30000ms, elapsed: 30018ms)

**To Reproduce**
vncserver :3 -geometry 1680x1050 -depth 24
check /var/log/messages and connect to vncviewer

**Expected behavior**
GNOME desktop shows up when I connect to vnc

**Client (please complete the following information):**
 - OS: Mac OSX 10.11.6
 - VNC client: RealVNC
 - VNC client version: 6.17.731
 - Client downloaded from: RealVNC site

**Server (please complete the following information):**
 - OS: CentOS Linux release 7.5.1804 (Core) 
 - VNC server: tigervnc
 - VNC server version:tigervnc-server-1.8.0-5.el7.x86_64
 - Server downloaded from: Linux distribution
 - Server was started using: vncserver :3 -geometry 1680x1050 -depth 24

Thanks in advance for your assistance.

**Comment by CendioOssman** [comment]
I'm afraid it looks like GNOME is crashing for you. We don't really have the resources to debug other software, so I'm afraid I'll have to redirect you to Red Hat. Please file a bug in their bugzilla and hopefully they can provide a fix for the crash.
