### ISSUE TITLE
tigervnc-server No download address found

### ISSUE THREAD

**Issue by zhangxianweihebei** [TigerVNC/tigervnc#809]
Sorry, I didn't find the download address of server.

https://bintray.com/tigervnc/stable/tigervnc/1.9.0
This address downloads like a client

**Comment by samhed** [comment]
The server is available on the link you posted, for example:

https://bintray.com/tigervnc/stable/download_file?file_path=tigervnc-1.9.0.x86_64.tar.gz

**Comment by zhangxianweihebei** [comment]
3 q
