### ISSUE TITLE
Enhancing the TigerVNC UI for the MAC

### ISSUE THREAD

**Issue by bhairav13** [TigerVNC/tigervnc#818]
Using TigerVNC on MAC.  A "VNC Viewer: Connection Details" window pops up on executing "File -> New Connection".  It has options to "Save As" the connection details so we can load them in the future.  The method to load seems a bit cumbersome.  Requires multiple steps to load.  Typing out the name directly is much faster.

Wondering if the Loading could be made easier.  For example, in Chicken VNC, the application comes up with 2 panes in the window.  On the left pane, all the saved connections and on the right, some basic connection details if wanting to change any.  It also saves the password so it need not be typed in every time.

Would it be possible to do something like that?  It would make selecting saved VNC connections and opening them up much easier and faster.

To see a screenshot of it, please visit https://techsparx.com/blog/2017/06/remote-vnc-linux-sbc.html.  The section on "Testing the VNC server locally" shows how it looks.

Thanks.

**Comment by CendioOssman** [comment]
That looks more like a full fledged profile manager. I'm afraid that is not something we have yet. Issue #153 already exists asking for such a thing.

We've also had some discussion about having a history for just the server field, which would at least avoid having to type out the full server name each time. However no one has yet had time to write the code for it.
