### ISSUE TITLE
Shared Memory Leak

### ISSUE THREAD

**Issue by mneilly** [TigerVNC/tigervnc#819]
First, thank you for your work on Tiger VNC and all the effort that has gone into it.

We have about 80 VNC sessions running on our CentOS 7.5 and 7.6 servers and we are seeing that the maximum number of shared memory segments is reached rather quickly as a result of a shared memory leak in TigerVNC 1.8.0 (or associated libs/code). 

I installed the patch referred to in #797, installed the resulting */usr/lib64/dri/swrast_dri.so* library, and verified that Xvnc used that version of the library but the issue did not go away. I am assuming that any patch to the Mesa software rasterizer is only relevant if we are actually running 3D apps however.

I also pulled the v1.9.0.tar.gz from releases and compiled it from source but did not see the problem go away.

The problem can be clearly demonstrated by running `ipcs -m | grep -oP '^0\S+\s+\S+\s+\K\S+' | sort | uniq -c` in a terminal then starting a VNC server with `vncserver`. [Resizing a window and watching the ipcs output clearly shows an increase in segment use](https://youtu.be/r_8cfiZbwmU) and greping for *deleted* in */proc/\<Xvnc pid\>/maps* matches the segment counts exactly.

For example:

```
[root@machine ~]# ipcs -m | grep -oP '^0\S+\s+\S+\s+\K\S+' | sort | uniq -c
    108 user1
   *2153 user2*
     27 user3
      2 user4
[root@machine ~]# ps -ef | grep -P 'user2.*Xvnc'
user2     6588     1  0 Feb12 ?        07:52:01 /usr/bin/Xvnc :1 -auth /home/user2/.Xauthority -desktop sc-sw01:1 (user2) -fp catalogue:/etc/X11/fontpath.d -geometry 1024x768 -pn -rfbauth /home/user2/.vnc/passwd -rfbport 5901 -rfbwait 30000

[root@machine ~]# grep -i deleted /proc/6588/maps | wc -l
*2153*
[root@machine ~]# 
```

Running `perf record -g -e 'syscalls:sys_exit_shm*' -e 'syscalls:sys_exit_memfd*' -p \<Xvnc pid\>` and resizing a window several times shows a mismatch in the number of shmat and shmdt calls. 

![image](https://user-images.githubusercontent.com/5897087/55982608-20435980-5c4e-11e9-8f4d-558a5ce505f4.png)

Running Xvnc under callgrind shows a similar mismatch. I'm not familiar with the code so it may mean nothing but it seems like the number of shmat calls from the X server dispatcher might correlate to the vncHooksCopyArea calls. I have no idea what calls should end up with the dispatcher calling shmdt to balance things out... I've attached the callgrind output log.

[callgrind.out.32087.log](https://github.com/TigerVNC/tigervnc/files/3070182/callgrind.out.32087.log)

![image](https://user-images.githubusercontent.com/5897087/55984484-6c909880-5c52-11e9-9419-d18897d8d0ac.png)

![image](https://user-images.githubusercontent.com/5897087/55984517-8205c280-5c52-11e9-8a17-f7cb704206e7.png)

At this point, the solution we are using is to pass '-extension MIT-SHM' to Xvnc to disable the use of shared memory. Since the vncserver wrapper passes options along to Xvnc it can be passed on the command line. This has eliminated the leak but it is unclear at what performance cost.

```
$ vncserver -extension MIT-SHM
```

**Comment by CendioOssman** [comment]
The fact that disabling MIT-SHM helps unfortunatly indicates that this is a bug on the same theme as #797. If it is not Mesa then it must be some other application that is misbehaving and requesting lots of shared memory.

Unfortunately there isn't really anything we can do from our end. You'll have to identify the offending application and try to have it fixed. Killing the application will free the memory, so it should be possible to figure out which one. Unfortunately the offender might be the desktop environment itself, which can be difficult to kill.

**Comment by mneilly** [comment]
Thanks for the response. 

>Unfortunately the offender might be the desktop environment itself

Just for reference for anybody else that runs across this... on CentOS 7.5/7.6 changing ~/.Xclients to call startkde or mwm instead of the default of gnome also seems to resolve the issue for us.
