### ISSUE TITLE
Exit without killing JVM

### ISSUE THREAD

**Issue by simhem** [TigerVNC/tigervnc#820]
Hello,

Would it be possible to get an exit() function on the java VncViewer that does not kill the JVM, but gracefully kills the running Thread ?

**Comment by bphinz** [comment]
It's already supposed to do that.  Can you tell me more about the issue or use case?

**Comment by simhem** [comment]
I'm using the java solution (**VncViewe**r class) as a third-party library, so i juste use the same mechanism as it is done in the main(String[] args) 

`VncViewer viewer = new VncViewer(args);'

'VncViewer.setLookAndFeel();'

'vnc = new Thread(viewer, "VncViewer Thread") ;'

'vnc.start();`

When i want to close the VncViewer, the only function that is available is the exit(int n) function, but it calls the System.exit() that kills the JVM 

I am searching for a way to juste close the viewer without my JVM exiting.

**Comment by bphinz** [comment]
Hmmm, you might just be able to call newViewer() instead of "new Thread" and treat it in much the same way as additional viewers launched from the F8 context menu?

**Comment by simhem** [comment]
I found a workaround that looks like the newViewer() function, basically you start a whole new process with the VncViewer inside, works fine but not optimal for a thrid party library kind of usage, thanks.
