### ISSUE TITLE
Heavy distortions, when connecting with krdc to TigerVNC in medium quality

### ISSUE THREAD

**Issue by frispete** [TigerVNC/tigervnc#825]
**Describe the bug**
When connecting with krdc via TigerVNC from one openSUSE TW system to another, I harvest display distortions in medium quality, and a saturated GBit ethernet connection with high quality. Only low quality behaves, but suffers from quality  perspective (as expected)

**To Reproduce**
1. use krdc 19.03.90 and below using VNC from TW 20190403 to TW 20190403, 
2. choose medium quality, no forced resolution, no scaling
3. connect
4. krdc displays screen okay on the first draw, then more and more distortions appear

**Expected behavior**
proper display

**Screenshots**
![krdc-distorted](https://user-images.githubusercontent.com/1009685/56421744-52833580-62a4-11e9-98ba-74cb1d54f483.jpg)

**Client (please complete the following information):**
 - OS: openSUSE Tumbleweed 20190411
 - VNC client: krdc
 - VNC client version: 19.03.90 and any below from the Qt5 based series
 - Client downloaded from: distribution

**Server (please complete the following information):**
 - OS: openSUSE Tumbleweed 20190411
 - VNC server: TigerVNC
 - VNC server version: 1.9.0
 - Server downloaded from: distribution
 - Server was started using: libvnc.so from /etc/X11/xorg.conf.d/10-libvnc.conf

**Additional context**
Falsely reported to: https://bugs.kde.org/show_bug.cgi?id=406316, but this is not a krdc issue, but rather an unlucky parameterization. 

I built test versions of TigerVNC with HEAD applied here:
https://build.opensuse.org/package/show/home:frispete:RemoteDesktop/tigervnc
that fixes the problem. 

Given that tigervnc HEAD fixes the issue, it is most likely the culprit. Unfortunately, the diff of 1.9.0 and HEAD is rather big... Studying it doesn't reveal a singular place, where this is fixed. The distortions imply, that wrong coordinates/resolutions are sent to the client in medium quality. 

Rather than bisecting, it might be easier to wait for the next release. 

Is there any rough estimation available already?

**Comment by CendioOssman** [comment]
Whoa. I don't think I've ever seen something like that outside of hardware errors.

Have you tested with other clients? If this is indeed a server issue then you should be seeing it with more than just krdc.

Could you try a custom rebuild of 1.9.0 the same way? You are using libvnc.so, and if openSUSE updated Xorg but did not rebuild TigerVNC then you might get all kinds of weird issues.

A new release is mostly waiting on some free time to do the work. Hopefully not too far off...

**Comment by joakim-tjernlund** [comment]
Any chance this is the same as
https://github.com/LibVNC/libvncserver/pull/340 ?

**Comment by CendioOssman** [comment]
Could be. No response from @frispete though, so I'm going to go ahead and close this issue.

**Comment by frispete** [comment]
Sorry, @CendioOssman, my bad!

> Have you tested with other clients? If this is indeed a server issue then you should be seeing it with more than just krdc.

Never saw something similar elsewhere, but my nr. of clients is rather limited (Android bVNC, tigervnc and krdc). 

> Could you try a custom rebuild of 1.9.0 the same way? You are using libvnc.so, and if openSUSE  updated Xorg but did not rebuild TigerVNC then you might get all kinds of weird issues.

That's still to be done. Hrmpf. Not sure, if that is really of big value or rather necrophilism. With proper dependencies in the spec (which is the case here), the OBS makes sure, that dependent packages are built.

> A new release is mostly waiting on some free time to do the work. Hopefully not too far off...

Well, on the positive side, that git release was accepted to Factory, hence anybody using tigervnc with Tumbleweed is using the git version as of Apr. 20.

I just submitted git master as of now. Apart from a funny effect of bVNC (Android), that it doesn't take any input a few seconds after a connection is made, all is well here. And I'm exercising VNC about every day! Hard.
