### ISSUE TITLE
can you compile the vncserver in qtcreator？

### ISSUE THREAD

**Issue by HelloJango** [TigerVNC/tigervnc#830]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC client: [e.g. TigerVNC, or UltraVNC]
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC server: [e.g. TigerVNC, or UltraVNC]
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver`]

**Additional context**

**Comment by CendioOssman** [comment]
Possibly. But we don't have any configuration files for it, so you are pretty much on your own. The only build system we support is CMake.
