### ISSUE TITLE
Create RPi / Allwinner Linux Binarys or Update Debian *stable* Repositorys

### ISSUE THREAD

**Issue by pm-pm** [TigerVNC/tigervnc#831]
**Is your feature request related to a problem? Please describe.**
Missing Binarys for small Linux Platforms

**Describe the solution you'd like**
Create addition Binarys or keep debian reposittories up to date.

I would be wonderful to have new the currect release as binarys for _all main operating systems_.
From [your download page](https://bintray.com/tigervnc/stable/tigervnc/1.9.0) you can not download any armhf binarys.
The binaries on the debian repositories are more than old:
Debian stretch **stable**: 1.7.0 (and no backports)

After some tries i was not able to compile the tigervnc server for cubieboards by myself.

Thanks for your support. :-)

**Comment by CendioOssman** [comment]
I'm afraid we don't have build systems (or time) to support every possible packaging. This is really the responsibility of the distributions and we only provide packages as a workaround.

So I suggest you poke Debian about getting their packages up to date.
