### ISSUE TITLE
What version of TLS?

### ISSUE THREAD

**Issue by theyhavelanded** [TigerVNC/tigervnc#836]
What version of TLS is being used? We require 1.2 as per PCI. Can anyone confirm the version?

**Comment by bphinz** [comment]
TigerVNC supports TLSv1.2.  By default, the client will use the highest version offered by the server.  You can use the GnuTLSPriority parameter to restrict the versions that the server offers.  This parameter accepts standard GnuTLS priority strings.  For example, to force the server to offer TLSv1.2 you can pass

-GnuTLSPriority NORMAL:-VERS-ALL:+VERS-TLS1.2

Note that older versions don't necessarily support TLSv1.2 if the GnuTLS library they are linked against doesn't.
