### ISSUE TITLE
TigerVNC ECCN

### ISSUE THREAD

**Issue by EGChevron** [TigerVNC/tigervnc#840]
Greetings:
 
I am an Export Compliance Officer for Chevron.  Would you please provide the ECCN (Export Control Classification Number) for the TigerVNC application?

If one is not available, would you please assist me by answering the following:
1.	What is the function of the software?
2.	Does the software have any encryption capabilities? Y/N
a.	If yes, does the encryption (Y/N): 
i.	_______ Encrypt the data in files (scramble data for illegibility)
ii.	 _______ Does the software utilize encryption capabilities of other programs (i.e. “crypto with a hole” or “open cryptographic interface”)
iii.	 _______ Encrypt only the password to ensure user authenticity

**Comment by CendioOssman** [comment]
No, we do not know of the proper ECCN number for TigerVNC. But the answer to your questions are:



> * What is the function of the software?
> 

To provide remote access to a graphical desktop environment.

> * Does the software have any encryption capabilities? Y/N

Yes.

>   a.	If yes, does the encryption (Y/N):
>   i.	_______ Encrypt the data in files (scramble data for illegibility)

Sort of. The password file uses DES for obfuscation. There is no general support for encrypting files.

>   ii.	 _______ Does the software utilize encryption capabilities of other programs (i.e. “crypto with a hole” or “open cryptographic interface”)

Not sure what that means. We have a DES implementation in the source tree, but the TLS crypto comes from GnuTLS (which generally uses nettle).

>   iii.	 _______ Encrypt only the password to ensure user authenticity

No. Encryption is also used for transport security.

Hope this helps.
