### ISSUE TITLE
Portable Windows binaries?

### ISSUE THREAD

**Issue by acicovic** [TigerVNC/tigervnc#841]
Would it be easy to provide a portable version for Windows binaries?

This could be done as standalone binaries or even as part of a portable project like portableapps.com. I haven't found any VNC client which is portable and easy to download, and I think it could be a possibility for TigerVNC to differentiate itself from the rest.

Regarding portableapps.com, it could be a good thing for TigerVNC as the platform doesn't offer any other VNC client (I'm not counting TeamViewer which is not VNC, proprietary and imposes limits).

Have you thought about it? would it be feasible?

**Comment by CendioOssman** [comment]
Portable in what sense? Our viewer is already just a single file. What is missing?

**Comment by acicovic** [comment]
Sorry for the delayed response.

I saw that TigerVNC is provided in an installer so I assumed it wasn't portable.

When I say portable I mean that it doesn't write to registry and that all files (program files, settings etc) stay within the program's folder, so copying to a USB stick and running it on another machine would produce the exact same results.

If that's the case my assumption is wrong and nothing is missing.

**Comment by CendioOssman** [comment]
The installer is for convenience as most users will want the files in "Program Files" and a short cut on the start menu.

We do store our setting in the registry though, and I don't see that we want to change that anytime soon. You can always include a `.tigervnc` file on your stick if you want to keep the configuration as a file.
