### ISSUE TITLE
Command Multiple computers at once

### ISSUE THREAD

**Issue by kintaro1981** [TigerVNC/tigervnc#848]
Is it possible to command multiple computers at once?

I have some identical clients I need to maintain. I would like to know if I can connect to them and then command them all at the same time to do some maintenance.

**Comment by CendioOssman** [comment]
No, automation isn't really something we're targeting with TigerVNC. I'm afraid you'll have to look at some other software to do what you want to do.

**Comment by samhed** [comment]
Have a look at pssh for example. It let's you connect with ssh and run commands on multiple machines at once.
