### ISSUE TITLE
keyboard shortcuts on the 'F8' popup menu are missing

### ISSUE THREAD

**Issue by vrkorada** [TigerVNC/tigervnc#85]
It seems keyboard shortcuts on the 'F8' popup menu are missing.
I made the following code changes to add the shortcuts to menu items in-line with previous versions.

```diff
************************
@@ -901,7 +875,7 @@
   contextMenu->add(_("Exit viewer"), 0, NULL, (void*)ID_EXIT, FL_MENU_DIVIDER);
 
 #ifdef HAVE_FLTK_FULLSCREEN
-  contextMenu->add(_("&Full screen"), 0, NULL, (void*)ID_FULLSCREEN, 
+  contextMenu->add(_("Full screen"), 0, NULL, (void*)ID_FULLSCREEN, 
 		   FL_MENU_TOGGLE | (window()->fullscreen_active()?FL_MENU_VALUE:0));
 #endif
   contextMenu->add(_("Resize window to session"), 0, NULL, (void*)ID_RESIZE, 
@@ -910,25 +884,25 @@
 #endif
 		   FL_MENU_DIVIDER);
 
-  contextMenu->add(_("Ctr&l"), 0, NULL, (void*)ID_CTRL, 
+  contextMenu->add(_("Ctrl"), 0, NULL, (void*)ID_CTRL, 
 		   FL_MENU_TOGGLE | (menuCtrlKey?FL_MENU_VALUE:0));
-  contextMenu->add(_("Al&t"), 0, NULL, (void*)ID_ALT,
+  contextMenu->add(_("Alt"), 0, NULL, (void*)ID_ALT,
 		   FL_MENU_TOGGLE | (menuAltKey?FL_MENU_VALUE:0));
 
   if (menuKeyCode) {
     char sendMenuKey[64];
-    snprintf(sendMenuKey, 64, _("S&end %s"), (const char *)menuKey);
+    snprintf(sendMenuKey, 64, _("Send %s"), (const char *)menuKey);
     contextMenu->add(sendMenuKey, 0, NULL, (void*)ID_MENUKEY, 0);
     contextMenu->add("Secret shortcut menu key", menuKeyCode, NULL, (void*)ID_MENUKEY, FL_MENU_INVISIBLE);
   }
 
-  contextMenu->add(_("Send Ctrl-Alt-&Del"), 0, NULL, (void*)ID_CTRLALTDEL, FL_MENU_DIVIDER);
+  contextMenu->add(_("Send Ctrl-Alt-Del"), 0, NULL, (void*)ID_CTRLALTDEL, FL_MENU_DIVIDER);
 
-  contextMenu->add(_("Refres&h screen"), 0, NULL, (void*)ID_REFRESH, FL_MENU_DIVIDER);
+  contextMenu->add(_("Refresh screen"), 0, NULL, (void*)ID_REFRESH, FL_MENU_DIVIDER);
 
-  contextMenu->add(_("&Options..."), 0, NULL, (void*)ID_OPTIONS, 0);
-  contextMenu->add(_("Connection &Info..."), 0, NULL, (void*)ID_INFO, 0);
-  contextMenu->add(_("&About TigerVNC viewer..."), 0, NULL, (void*)ID_ABOUT, FL_MENU_DIVIDER);
+  contextMenu->add(_("Options..."), 0, NULL, (void*)ID_OPTIONS, 0);
+  contextMenu->add(_("Connection info..."), 0, NULL, (void*)ID_INFO, 0);
+  contextMenu->add(_("About TigerVNC viewer..."), 0, NULL, (void*)ID_ABOUT, FL_MENU_DIVIDER);
 
   contextMenu->add(_("Dismiss menu"), 0, NULL, (void*)ID_DISMISS, 0);
 }
**********************
```

**Comment by Dmole** [comment]
This should be a bug (regression) not an enhancement because you can't exit full screen (on OS X at least) without it working.

**Comment by Dmole** [comment]
And killing the pid for "TigerVNC Viewer 1.4.0.app" fails to kill related, so
```
sudo killall -u otheruser -9 && sudo kill -9 $(ps ax | grep -iP "loginwindow$" | perl -pe 's/ .*//g')
```
is how to exit the app short of pulling the plug and forcing a logout over ssh is just not an acceptable way to close an app.

**Comment by CendioOssman** [comment]
I'm afraid I don't see how this is preventing you from exiting full screen? You should be able to navigate using the arrow keys on the keyboard, or clicking using the mouse.

**Comment by Dmole** [comment]
CendioOssman can you be more specific?  [command]+[Q] and [command]+[tab] both fail.
For virtual box it lets you know what key is used to toggle whether commands are captured by guest or client OS and whether its on or off. Due to the lack of a bar in tigervnc there is nothing to "arrow key", or click on with the mouse except the remote(client) OS.

**Comment by CendioOssman** [comment]
This bug is not about adding any shortcuts that are always active. Rather it is about quickly selecting items in the menu once it is already open.

To get out of full screen you need to open the menu (F8 by default, but can be changed) and then navigate that menu using either they keyboard or the mouse.

**Comment by Dmole** [comment]
maybe I need to file another bug for F8 not working or check if my f8 key is broken (I checked and tigervnc is set to F8)
