### ISSUE TITLE
Xvnc server crashed by tk-based application.

### ISSUE THREAD

**Issue by pawelsopensource** [TigerVNC/tigervnc#853]
**Describe the bug**
https://bugzilla.redhat.com/show_bug.cgi?id=1732512

**Client (please complete the following information):**
 - OS: fedora-30
 - VNC client: remmina
 - VNC client version: 1.3.4
 - Client downloaded from: fedora-30

**Server (please complete the following information):**
 - OS: fedora-30
 - VNC server: tigervnc
 - VNC server version: 1.9.0-4
 - Server downloaded from: fedora-30
 - Server was started using: vncserver

**Comment by CendioOssman** [comment]
I'm afraid that crash includes no code from us. So it is something that needs to be fixed in Xorg, and then Fedora needs to do a new build of Xvnc.
