### ISSUE TITLE
 Incomplete Desktop: no task bar, only black Desktop and two icons

### ISSUE THREAD

**Issue by siyux** [TigerVNC/tigervnc#854]
I used the same configuration in three centos7.5 servers. The only difference is gpu(one RTX 2080ti two tesla P100) But when I connected their desktops, one of them is normal and the other two are unnormal. 
The normal steps: 
1.input ip and port
2.input the vnc password 
3.then you enter into the login interface 
4.input your user password and you will enter into the Desktop

But the other two not like this! It skips step3.  Don't need to input your user password and access the Desktop directly
Then, the background is black, no taskbar, no topbar(include applycations and status, I don't Kown the name)
The Desktop only have two icons(folder and trash), right click and open a terminal, the terminal don't have close icon.
This is the full screenshot:
![image](https://user-images.githubusercontent.com/40952612/61800443-98c9d100-ae5f-11e9-8170-ce5d63e7bb58.png)

Why does this happen? How to solve this?

**Comment by CendioOssman** [comment]
It looks like gnome-shell has failed to start (or crashed). Have you checked your logs on the server?

Do you have the NVIDIA driver installed? It tends to mess with the OpenGL libraries, which could be the cause of a crash.

**Comment by chao-1986** [comment]
I ran into this problem also, but on the same server with different user accounts. Even I assign a new port to the account that has this problem, he still have this incomplete desktop. I checked his account on the server instead of using vnc, it is ok.

**Comment by CendioOssman** [comment]
No response with log files. Closing.
