### ISSUE TITLE
Is there a way to flip screen on client side?

### ISSUE THREAD

**Issue by linfan68** [TigerVNC/tigervnc#855]
I wonder if there is a way to flip the screen vertically on the client side.
If not, can I have some pointers to which file to modify to achieve this?

**Comment by CendioOssman** [comment]
No, that's not really a feature we've considered. :)

It's probably easiest to flip it on output somehow. I'd look in the different `vncviewer/Surface*.cxx` and see what can be done. No idea how though. :)
