### ISSUE TITLE
"Authentication error" on GNOME Ubuntu 18.04 after screen lock

### ISSUE THREAD

**Issue by jcrben** [TigerVNC/tigervnc#856]
**Describe the bug**
UPDATE: I've now found I have to do this after taking a screenshot on mac when the TigerVNC screen is active, which I do with CTRL+CMD+SHIFT+4... incidentally, I started a wiki page on shortcuts https://github.com/TigerVNC/tigervnc/wiki/Keyboard-shortcuts

ORIGINAL: I see "Authentication error", and the keyboard does not work.

I may add a screenshot here later of the error, but at the moment I've disabled the default behavior of screen locking.

This has been reported for a long time over at https://bugzilla.redhat.com/show_bug.cgi?id=960149 - they kept trying to close it and people kept saying it was still happening. I think it wasn't ever fixed, but someone finally stopped showing up to reopen it.

The workaround fix is to run from an SSH session `loginctl unlock-session <session number>` after discovering sessions with `loginctl list-sessions`

**To Reproduce**

Run `tigervncserver` with `xstartup` like this:
![image](https://user-images.githubusercontent.com/5614134/62097584-1add3f80-b23c-11e9-944f-56c5aa0b4d0a.png)

My `/etc/vnc.conf` looks like this:
![image](https://user-images.githubusercontent.com/5614134/62097619-4102df80-b23c-11e9-8ede-097f6a648e26.png)

Version is: 1.7.0+dfsg-8ubuntu2
![image](https://user-images.githubusercontent.com/5614134/62097789-e8801200-b23c-11e9-812e-dcf9d652eafa.png)

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: macOS 10.14.5
 - VNC client: TigerVNC
 - VNC client version: 1.9.0
 - Client downloaded from: `brew cask install tigervnc-viewer`

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - VNC server: TigerVNC
 - VNC server version: 1.7.0+dfsg-8ubuntu2
 - Server downloaded from: I ran `sudo apt install tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer`
 - Server was started using: `tigervncserver`

**Comment by CendioOssman** [comment]
Unfortunately we still consider this to be a bug in GNOME somewhere, and not in TigerVNC. I would suggest reporting it to GNOME (and possibly Ubuntu) and they'll hopefully give it more attention than Red Hat has done.

**Comment by brechtm** [comment]
For reference: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2196
