### ISSUE TITLE
Wayland epoch is come?

### ISSUE THREAD

**Issue by AAAPops** [TigerVNC/tigervnc#857]
Last time more and more Linux distributes have preinstalled Wayland as Xorg alternative.

Maybe it's time to make vncviewer with Wayland support? I think picture quality has to become better even than now.

**Comment by CendioOssman** [comment]
It is not something we are looking at, no. The toolkit we are using (FLTK) does not have support for it, so we would have to wait for that first.

The viewer should work fine under Wayland right now via Xwayland though. What issue are you seeing?

**Comment by q2dg** [comment]
Duplicated (https://github.com/TigerVNC/tigervnc/issues/158)

**Comment by CendioOssman** [comment]
Right. Thanks.
