### ISSUE TITLE
I can't use "vncconfig −connect host[:port]" reverse connection with Apache Guacamole

### ISSUE THREAD

**Issue by xxyjskx1987** [TigerVNC/tigervnc#859]
I can't use "vncconfig −connect host[:port]" reverse connection with Apache Guacamole.
but ultravnc can do this with Apache Guacamole.

**Comment by CendioOssman** [comment]
What does the log files from Xvnc and Guacamole say?

**Comment by xxyjskx1987** [comment]
I can't get any log for the moment.
now, I use x11vnc replace tigervnc, but I can reverse connection between two tigervnc.

**Comment by CendioOssman** [comment]
Alright. I'll close this issue for now then and we can reopen it once there has been an opportunity to get some log files.
