### ISSUE TITLE
TigerVNC does not work on macOS Catalina

### ISSUE THREAD

**Issue by bofeiw** [TigerVNC/tigervnc#861]
**Is your feature request related to a problem? Please describe.**
TigerVNC does not work on macOS Catalina (10.15 Beta (19A526h)).
<img width="783" alt="Screen Shot 2019-08-23 at 2 45 49 pm" src="https://user-images.githubusercontent.com/34177142/63567434-f6635180-c5b4-11e9-8238-a87039b26fc5.png">

**Describe the solution you'd like**
Update TigerVNC for macOS Catalina.

**Describe alternatives you've considered**
An alternative is to downgrade macOS Catalina to Mojave so that TigerVNC can run.

**Comment by samhed** [comment]
Is it the same with TigerVNC 1.9.0?

**Comment by bofeiw** [comment]
> Is it the same with TigerVNC 1.9.0?

Yes. @samhed 
<img width="778" alt="Screen Shot 2019-08-24 at 1 36 27 am" src="https://user-images.githubusercontent.com/34177142/63604643-a82f6c00-c60f-11e9-8047-8c62dc3ac308.png">

**Comment by unikitty37** [comment]
The nightly build at http://tigervnc.bphinz.com/nightly/ appears to have been built with 64-bit support — I'm still on Mojave, but it doesn't throw the warning on launch, and shows as 64-bit in System Information > Applications.

Might be worth a try if you need to get up and running now on Catalina.

**Comment by nirvana1122** [comment]
Is nightly build the only solution? I do not know how to use it to install tigerVNC.

**Comment by bphinz** [comment]
It's just a .dmg installer - download it, double click, and follow the
prompts

**Comment by nirvana1122** [comment]
Got it ! thank you

**Comment by jma256** [comment]
The 64 bit nightly build crashes on launch on MacOS Catalina 10.15

However the java client works on Catalina.

**Comment by CendioOssman** [comment]
So the original issue seems to be resolved by a switch to a 64-bit build. So I'll go ahead and close this issue.

@jma256, please open a new issue for the crash. Please try to include any details of the crash is possible.
