### ISSUE TITLE
Improve vncserver script

### ISSUE THREAD

**Issue by darkdragon-001** [TigerVNC/tigervnc#862]
Ubuntu's vncserver script is a lot more powerful than the one provided from the project itself. It allows specifying (almost?) all options as parameters (e.g. `-localhost` is available), has a lot more comprehensive `-help` and `vncserver -list` also displays the bound port. As a downside, it is way less tolerant e.g. when run within a docker environment.

Maybe you could backup some of the additional features to the project itself?

**Comment by CendioOssman** [comment]
We're looking at a revamp of the vncserver feature in #838. So I'm afraid right now we're not looking at doing any more improvements to the current system.
