### ISSUE TITLE
Locally built vncviewer session size messed up

### ISSUE THREAD

**Issue by kflu** [TigerVNC/tigervnc#867]
**Describe the bug**
In the session window, the remote desktop only occupies the lower left corner, leaving the rest of the window "blank". This only repros using my locally built vncviewer (mac osx). If I install the official package, there's no problem. (v1.9.80)

See screenshot.

**To Reproduce**
1. locally build tigervnc (`cmake -G"Unix Makefiles"  . && make`)
2. run `vncviewer` and connect to remote desktop

**Expected behavior**
In the session window, the remote desktop only occupies the lower left corner, leaving the rest of the window "blank". See screenshot

**Screenshots**
<img width="1923" alt="vncviewer_issue_report" src="https://user-images.githubusercontent.com/1031978/64072508-6cfeef80-cc44-11e9-93a3-d934037511c0.png">

![image](https://user-images.githubusercontent.com/1031978/64072524-ec8cbe80-cc44-11e9-9029-d75290d241e4.png)

![image](https://user-images.githubusercontent.com/1031978/64072528-f44c6300-cc44-11e9-8328-fad7815bd598.png)

![image](https://user-images.githubusercontent.com/1031978/64072530-fe6e6180-cc44-11e9-9395-bc3707316266.png)

**Client (please complete the following information):**
 - OS: mac osx 10.14.6
 - VNC client: TigerVNC
 - VNC client version: 1.9.80
 - Client downloaded from: locally built

**Server (please complete the following information):**
 - OS: centos
 - VNC server: TigerVNC 
 - VNC server version: 1.9.0
 - Server downloaded from: my Linux distribution
 - Server was started using: `vncserver :1`

**Additional context**
This only repros using my locally built vncviewer (mac osx). If I install the official package, there's no problem. (v1.9.80)

I need to properly locally build and run in order to develop a pull request. So really need this to work.

**Comment by kflu** [comment]
OK, according to this (https://github.com/Homebrew/homebrew-core/issues/37872#issuecomment-479995759) comment, I was able to fix it by using an older version of fltk

**Comment by CendioOssman** [comment]
Alright, so it's an issue with FLTK then. Could you report it to @fltk so they could have a look at fixing it?
