### ISSUE TITLE
xorg extension undocumented

### ISSUE THREAD

**Issue by allefeld** [TigerVNC/tigervnc#868]
As far as I can tell, there is absolutely no documentation for the X extension module.

I installed it from the Debian package tigervnc-xorg-extension, and the package includes no documentation. I therefore looked at the tigervnc website and at the github wiki, but no success there either.

I think this module could be very useful, if one knew how to use it. ;)

**Comment by CendioOssman** [comment]
Definitely. It shares the same options as Xvnc, so that man page is mostly relevant. It needs to be specified via Xorg's config system rather than command line though, so some documentation would be nice.

**Comment by allefeld** [comment]
I tried it with a snippet of X configuration I found on some random website, which completely crashed my X. So I would like to try again, but only if there's more detailed information.

**Comment by CendioOssman** [comment]
Apparently we already had #394. Closing this issue as a duplicate.
