### ISSUE TITLE
Issues with correctly setting up a virtual multi monitor setup

### ISSUE THREAD

**Issue by naatje80** [TigerVNC/tigervnc#870]
**Describe the bug**
I'm unable to setup a working virtual multi monitor setup. We are investigating if we could switch to Tigervnc instead of a commercial VNC product we are using at the moment. We are dependent on multi monitor capabilities for our IC Designers. The commercial product (partially)  supports multi monitor setup in combination with a KDE Plasma desktop environment. But because of RHEL 8 KDE is dropped from the official repositories, we like to have the same functionality with the default GNOME Shell environment. 

With Tigervnc we also get the best results with KDE, but it is not working correctly. It could be that this is not a bug, but I could also not find any instructions how to set this up correctly.

**To Reproduce**
1. Start the VNC server with: `vncserver -screen 0 1024x768x24 -screen 1 1024x768x24 +xinerama -autokill`
2. Start the client 2 times. For the first screen: `vncviewer server:5901` and for the other display: `vncviewer server:6901`. I also tested it with the additional option:  -RemoteResize=0, but it did not solve the issue.
3. The results depends on the desktop environment setup in `$HOME/.vnc/xstartup`:
- Default xstartup (starts GNOME shell for EL 7.6 based OS). Creates first monitor correctly, second monitor only shows mouse pointer. The rest of the Windows stays black. 
- KDE environment (By putting the command: `startkde` in xstartup file): Until now this desktop environment has the best results. Shows two desktops correctly. We are able to move and open windows on both screens. But moving Windows on the second screen, almost always flips them back to the first screen. This makes this solution also unusable. Apart from the fact that it is also dropped from the official repo's. So will like to use the GNOME Shell environment instead.
- Although already not officially supported, I also tested MATE and XFCE: Results are similar compared to GNOME Shell. I also get a black screen on the second window. Only the cursor is visible. Right clicking on the desktop, results in a popup menu in the first screen.

For all Desktop Environments, I noticed that If I open the display manager it also detects one monitor.

**Expected behavior**
A working setup with multiple screens like you would expect when you physically attach two monitors to a PC.

**Client (please complete the following information):**
 - OS: Scientific Linux 7.6 (Also tested on Centos 7.6 VM) and Windows 10
 - VNC client: tigervnc on Linux and TurboVNC on Windows
 - VNC client version: 1.9.0 (both release and latest version in git)
 - Client downloaded from: Manually compiled (see version info)

**Server (please complete the following information):**
 - OS: Scientific Linux 7.6 (Also tested on Centos 7.6 VM)
 - VNC server: TigerVNC 1.9.0 (both release and latest version in git)
 - VNC server version: 1.9.0, also tested 1.8.0 default available on Centos 7.6
 - Server downloaded from: 1.9.0 Github using git clone and Centos/SL 7.6 repos (for 1.8.0)
 - Server was started using:  `vncserver -screen 0 1024x768x24 -screen 1 1024x768x24 +xinerama -autokill`

**Comment by CendioOssman** [comment]
I'm afraid we do not support the old multi screen variant of multi monitor. Instead you need to use the modern RandR variant.

Simply start the server with a single screen. Once you enter fullscreen on the client the server will be reconfigured to match the monitor setup on the client.

Right now you cannot specify the monitor setup on the server command line. Please see #328 for that feature.
