### ISSUE TITLE
Building TigerVNC to use as portable application.

### ISSUE THREAD

**Issue by AlexandreLemoine40** [TigerVNC/tigervnc#872]
I've encountered some issues trying to compile TigerVNC for Windows so I installed it with the installer available on Bintray.

The first issue is when I try to pass the "-geometry 1600x900" argument to the winvnc4 by command line, the settings are not affected and the viewers are seeing the whole screen of the computer on which the server is running on. I would know if it is normal or an issue due to a bad usage of the winvnc4 command line, or maybe a bug of the argument.

Other thing i would to know, when I connect a vncviewer to the winvnc4 server the refresh rate is 2 or 3 frame per seconds (on local network 192.168.etc so it is sensed to be fast), I looked many times at the "documentation" and nothing about Polling or refresh rate.

Finally I would appreciate a more detailed guide to build TigerVNC to be able to package a portable version into a electronjs software standalone. I don't know if a portable version is possible or if TigerVNC needs some particular installations by .exe to work correctly.

When I compile I try to build TigerVNC the following command lines.
`cd tigervnc-1.9.0`
`cmake -G "MSYS Makefiles" win`

Then the following issue come up.
 No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

I don't know if I need to really modify this file or call differently the command.

Thanks for the future help.

**Comment by CendioOssman** [comment]
> The first issue is when I try to pass the "-geometry 1600x900" argument to the winvnc4 by command line, the settings are not affected and the viewers are seeing the whole screen of the computer on which the server is running on. I would know if it is normal or an issue due to a bad usage of the winvnc4 command line, or maybe a bug of the argument.

I'm afraid WinVNC does not support showing only parts of the screen.

> Other thing i would to know, when I connect a vncviewer to the winvnc4 server the refresh rate is 2 or 3 frame per seconds (on local network 192.168.etc so it is sensed to be fast), I looked many times at the "documentation" and nothing about Polling or refresh rate.

That is a bug in our hook mechanism. Please try changing the setting to use polling instead. It should be faster.

> When I compile I try to build TigerVNC the following command lines.
> `cd tigervnc-1.9.0`
> `cmake -G "MSYS Makefiles" win`

I'm afraid that is not the correct way to call cmake. May I ask why the `win` subdirectory was given as the TigerVNC source directory? It's an issue that many keep getting confused by.

**Comment by fanfani** [comment]
hi there,

the original post is actually asking more than one question, but i am too interested in the main one (ie. the one appearing in this thread's subject):

is there a way to create a "standalone" / static executable for windows that requires no installation?

It would be even more useful to have this option ready to download from upstream, ...after all the linux binaries available from bintray are compiled just that way

thank you!

**Comment by CendioOssman** [comment]
That already exists. Please see the release page where you can download standalone .exe files that can be run from anywhere.

**Comment by fanfani** [comment]
actually, if i go to - > "Releases" - > "https://bintray.com/tigervnc/stable/tigervnc/1.10.1" - > "General" (or "Files") ...i can only download -> "tigervnc64-1.10.1.exe" , which is an installer for tigervnc server, not a standalone executable

**Comment by CendioOssman** [comment]
The same release also has "vncviewer64-1.10.1.exe" which is not an installed but rather the stand alone application.

**Comment by fanfani** [comment]
which is a client ("viewer"), not the server

**Comment by CendioOssman** [comment]
I'm afraid WinVNC requires multiple binaries and a bit of setup (like setting up services) so it wouldn't work as a standalone binary. Unfortunately you'll have to look at some other VNC server in that case that was designed from the start with that use case in mind.
