### ISSUE TITLE
Release multiple times a year

### ISSUE THREAD

**Issue by kim0** [TigerVNC/tigervnc#873]
1.9 is more than a year old release and I would really like to upgrade to a newer release since I see tons of fixes. I am not sure if the nightly builds would be stable enough. It would be great if someone can cut a release please!

It would be even better to have some cadence of release every 1 or 2 quarters to avoid people using really old versions. Thanks

cc @CendioOssman

**Comment by CendioOssman** [comment]
It would. I'm afraid it's an issue of not enough people. And we've been busy with other things here at Cendio the last year.

Unfortunately there isn't much we can do except getting more people involved. So tell your friends and get them interested in helping out with this project. :)

**Comment by kim0** [comment]
@CendioOssman .. I wouldn't mind helping a bit if you'd explain what it takes. I'm a devops guys, so CI/CD pipelines and automating things like that is what I do .. But I see you already have the automated nightly builds .. not sure what more is needed for an actual release ?

**Comment by CendioOssman** [comment]
We have the steps for the release documented on the wiki:

https://github.com/TigerVNC/tigervnc/wiki/Development:-Making-a-Release

What is needed before that though is going through the issues and pull requests and seeing if there's anything that should get fixed before a release (nothing comes to mind right now though). After that someone also needs to go through the commits since the last release and put together some release notes. Basically checking `git shortlog v1.9.0...`.

Once that is done we can look at putting out a beta. Any help you can provide along those lines would be very welcome.

**Comment by kim0** [comment]
Hi @CendioOssman .. I'm guessing collecting the release notes, is the time consuming bit, so I went ahead and did it (below). I was a little bit "generous", so you might want to delete a few more lines! Please let's try to cut a release soon, before this gets outdated. Also, let me know if there's something else, I can help with (without familiarity with the codebase).

* Use display polling by default in WinVNC
* Support extended clipboard transfers
* Use UTF-8 in clipboard API
* Always get raw keyboard layout on macOS
* Add delay on authentication failures
* Add x0vncserver option to only allow localhost connections
* Add support for VMware LED status and cursors
* Fix memory leaks
* Save a few X11 server roundtrips by ignoring empty damage regions.
* Prevent rendering uninitialized Pixmap contents on X11
* Properly terminate server on timeouts
* Handle AltGr from Windows' touch keyboard
* Adjust XDamage tracking to geometry
* Respect geometry setting in screen layout
* Fix rendering on big endian system
* Adjust some strings so they are easier to translate
* Log TLS handshake result
* Remove Java web server
* Avoid potential crash when replacing buffer in PlainPasswd
* Include unix socket in vncviewer usage
* Interpret Meta as Alt
* Replace Shift+Alt with Shift+Meta when possible
* Update NumLock comment now that we have sync
* Estimate higher bandwidth in slow start
* Allow perceptually lossless refresh
* Limit maximum lossless refresh CPU usage
* Avoid refresh of recently changed areas
* Link zlib statically on all platforms
* Fix bad color of cursor with x0vncserver
* Stop tracking changes for each glyph
* Use system certificate trust store
* Reduce size of context menu hint
* Compile fixes for Xserver 1.9
* viewer: reset ctrl / alt to menu state on focus

**Comment by CendioOssman** [comment]
Awesome. I'll try to have a look soon and get this rolling then.

If you want you can browse through the issues and pull requests see if there is anything that looks like we really must take care of before a release.

**Comment by kim0** [comment]
@CendioOssman .. Most of the more serious ones, are already labeled "bug" .. The one that seemed most serious was https://github.com/TigerVNC/tigervnc/issues/864 .. Although, that's only serious if it affected all Windows machines. This is probably not the case, bec OP mentioned it worked fine on another machine. 

Apart from that, I can't see issues that would be too serious and need immediate attention.

**Comment by CendioOssman** [comment]
I agree. So let's get a beta out then. Thanks for your assistance. :)
