### ISSUE TITLE
Full screen mode hangs viewer with external displays and lid closed (Mac OS; repeatable)

### ISSUE THREAD

**Issue by rsiverd** [TigerVNC/tigervnc#874]
**Describe the bug**
I am attempting connect to a running VNC session on a Linux machine using TigerVNC viewer on a Mac OS client. The client system is a MacBook Pro (MBP) with two external monitors connected via dock. The client system usually runs in "clamshell mode" with the laptop lid closed (uses external monitors, mouse, and keyboard). With this hardware setup, I find that full-screen mode hangs the TigerVNC viewer (spinning pinwheel, force quit required) when I either (a) connect with full-screen requested or (b) select full-screen mode after connecting in windowed mode.

This behavior is *exclusive* to the clamshell situation (laptop lid closed). When the laptop lid is open and its internal display is active, full-screen works as expected. Specifically,
these work:
 - laptop open + 1 external monitor (3840x1200 client resolution)
 - laptop open + 2 external monitors (5760x1200 client resolution)

But this hangs:
 - laptop closed + 2 external monitors (3840x1200 client resolution, desired use case)

**To Reproduce**
1. Connect external displays to MacBook Pro
2. Close lid on laptop ("clamshell mode")
3. Attempt to enter full-screen mode while or after connecting
4. Program hangs and requires force quit

**Expected behavior**
I expect the viewer to function in full-screen mode regardless of which displays are active.

**Client (please complete the following information):**
 - OS: Mac OS Mojave 10.14.6 with latest updates
 - VNC client: TigerVNC Viewer 32-bit v1.9.0
 - Client downloaded from: link provided on GitHub release page
 - Dell Docking Station D6000, connected via USB-C
 - 2x Dell U2410 displays, attached to D6000 dock

**Server (please complete the following information):**
 - OS: CentOS 6 (centos-release-6-10.el6.centos.12.3.x86_64)
 - VNC server: tigervnc-server-1.1.0-24.el6.x86_64
 - Server downloaded from: Linux distribution
 - Server was started using: `vncserver :91 -geometry 3840x1200 -autokill -localhost`

**Comment by CendioOssman** [comment]
Unfortunately this is not an issue we've heard of before. But no one else might have tried your exact scenario.

I'm afraid I don't have a macOS laptop here, so I'm not in a good position to debug this. Could you try the nightly build though? If we're lucky it has been fixed along the way.

**Comment by rsiverd** [comment]
After further investigation, I am no longer confident this is a bug in tigervnc. Instead, I think this behavior is more likely due to a bug (or bugs) in the Mac OS DisplayLink driver that the dock uses.

In short, I am not able to reproduce the program hang when using a different USB-C hub or hubs.  I have tested various combinations of either/both of the two monitors noted before via two different USB-C hub types and direct DisplayPort-to-USB-C cables. Everything works as expected in all cases (clamshell or not). Freezing only occurs when one or both monitors are run through the D6000 dock (running power, keyboard, mouse, audio, and Ethernet through the dock seems to work fine). Other video-related behaviors (that were not obviously bugs at first glance) have also changed since bypassing the dock.

I don't believe the dock hardware is faulty as it seems to work ~perfectly under Windows 10.  All told, it appears that the Mac OS dock driver is most or all of the problem. I have no explanation for why tigervnc was uniquely capable of triggering this odd behavior among the various programs installed with similar full-screen capability but am not sure that warrants investigation. Feel free to let me know if further information would be useful but otherwise I think this can be closed. Hopefully this post proves useful if someone else encounters the same issues.
