### ISSUE TITLE
TigerVNC 1.9 is not supported for the new Mac OS update (macOS Catalina 10.15)

### ISSUE THREAD

**Issue by freddehus** [TigerVNC/tigervnc#875]
Hi,

It seems that TigerVNC is not compatible with the new Mac OS update. Are you aware of this problem and does a workaround exist?

Regards,
Fredrik

**Comment by ChrisGeorgakidis** [comment]
Does it still work though?

**Comment by freddehus** [comment]
No, it does not.

**Comment by Contrapuntal** [comment]
The nightly build [http://tigervnc.bphinz.com/nightly/](http://tigervnc.bphinz.com/nightly/) seems to work fine on macOS Catalina for me.

**Comment by RobyB** [comment]
version 1.9.80, coming from the nightly builds, being 64-bit solves the issue.
Might be worth building a stable 64-bit version for OsX.

**Comment by CendioOssman** [comment]
If possible, I don't remember if we had to modify anything after 1.9.0 to get it to work. @bphinz, do you think it is possible to add a 64-bit 1.9.0 build?

Otherwise we're looking at doing a 1.10.0 at the end of the year, which will have a 64-bit build.

**Comment by freddehus** [comment]
1.9.80 worked perfectly! Thanks for all the help

**Comment by bphinz** [comment]
> @bphinz <https://github.com/bphinz>, do you think it is possible to add a
64-bit 1.9.0 build?

Yes, I'll put one up by tomorrow

**Comment by imehr4** [comment]
I still get
“TigerVNC Viewer 1.9.80” can’t be opened because Apple cannot check it for malicious software.

**Comment by v-iashin** [comment]
Managed to solve it on MPB 2018 Catalina 10.15 (and verified on another MPB 2019 Catalina 10.15):
1. Download `1.9.80` from http://tigervnc.bphinz.com/nightly/
2. Click on `.dmg` in the opened app folder there are 3 files: readme, license, and app;
3. Put the app in your `Applications` folder;
4. Double click shows you "Apple cannot check it for malicious software" as @imehr4 (@Quan96) described;
5. I went to `System Preferences` > `Security & Privacy` > `General` (Tab) > clicked on `Open Anyway` nearby `TigerVPN` app;
6. In the prompted dialogue click on the button with a question mark. It will show you the help on how to open it. You can find out that you need to `Control-click` on the app and select `Open` from the drop-menu
7. The prompt where you found the question button is still open just click `Open` in it -> nothing happens;
8. Go to your `Applications` folder and control-click on the `TigerVNC`. It should open the app. 

Next time you are going to try to open the app from applications, you will be able to do it just with a double click as any other app.

**Comment by ppwaskie** [comment]
It seems like the 1.9.80 build for Mac OS fails to open with "no mountable volumes found" when I try to attach the dmg.

**Comment by CendioOssman** [comment]
This issue was about 32-bit support, which has been resolved. Please see #881 for the signing issue.
