### ISSUE TITLE
TigerVNC 1.9.80 failing to start on MAC OS Catalina (10.15)

### ISSUE THREAD

**Issue by gsmurray** [TigerVNC/tigervnc#881]
TigerVNC 1.9.80 does not open on MAC OS Catalina. (10.15)

**To Reproduce**
1. Download .dmg from Source Location
2. Extract .app from .dmg
3. Double-click to open (or Right-Click->Open)
4. See error:

![Screen Shot 2019-10-17 at 1 26 44 PM](https://user-images.githubusercontent.com/42212433/67033135-085bff00-f0e3-11e9-845a-cacecbd4f2bc.png)

**Expected behavior**
The Application should open without Errors or Message Dialogs

**Screenshots**
Attached 

**Client (please complete the following information):**
 - OS: MAC OS Catalina (10.15)
 - VNC client: TigerVNC 
 - VNC client version: V1.9.80
 - Client downloaded from: http://tigervnc.bphinz.com/nightly/osx/TigerVNC-1.9.80.dmg

**Server (please complete the following information):**
Could not open the Client Application, therefore, Server Information is irrelevant 

**Additional context**
Previous Enhancement Requested for x64 Version for MAC OS Mojave:
**Enhancement: TigerVNC x64 Bit #695**

After multiple Attempts to Start (3-4) the Application did open and subsequent Application Starts were successful. Similar behaviour reported in Enhancement #695

**Comment by gsmurray** [comment]
Further Testing Reveals that the following Method will allow the Application to open:

1. Download 1.9.80 from http://tigervnc.bphinz.com/nightly/
2. Click on .dmg ->copy the app in your Applications folder;
3. Double click shows you "Apple cannot check it for malicious software"
4. Go to System Preferences > Security & Privacy > General (Tab) > clicked on Open Anyway nearby TigerVPN app;
5. This will Show the shows you "Apple cannot check it for malicious software" dialog again->Select OK
6. Attempt to open the Application again by DoubleClicking

Next time you are going to try to open the app from applications, you will be able to do it just with a double click as any other app.

A workaround for the issue, but not quite a resolution.

This will raise a lot of Tickets in a corporate Environment such as ours

**Comment by bphinz** [comment]
I don't believe that this has anything to do with the app itself or the way that it's built.  Apple wants everything to go through the App Store (unless it's open source software, and then they won't allow it on the app store...).  See the link below

[Safely open apps on your Mac](https://support.apple.com/en-us/HT202491)

I will look into using their notarization service, which might resolve this issue, but it requires some changes that will probably break support for running on macOS < 10.9.

**Comment by gsmurray** [comment]
Thanks Brian,

I kind of jumped the gun a little opening this bug as I later discovered that this is somewhat expected behaviour

On Previous MAS OS’s the Right-click->Open method would allow Apps from an unidentified Publisher to open.
Seem this extra step is now required.

Unrelated to the x32/x64 Architecture.

I suppose our users will just need to get used to it and I will provide the initial open instructions in my deployment.


George Scott Murray
O | 6136705388
M | 6137935792

**Comment by v-iashin** [comment]
@gsmurray hi, Siraj Raval. Can you please re-login?

https://github.com/TigerVNC/tigervnc/issues/875#issuecomment-541403316

**Comment by ppwaskie** [comment]
I don't even get that far on Catalina.  Here's what I'm getting when I try to open the .dmg:

<img width="374" alt="Screen Shot 2019-10-18 at 9 06 21 AM" src="https://user-images.githubusercontent.com/5249102/67110049-b4a2f180-f186-11e9-9517-4d13ad14da3e.png">

**Comment by bphinz** [comment]
@gsmurray - I just pushed a nightly build with a dmg that is notarized.  Can you please test it, I don't have access to a machine with Catalina at the moment.  I'm not sure whether or not it will work since the build still targets the 10.7 SDK and Apple's Gatekeeper docs state that the 10.9 SDK is a prerequisite (it opens fine on my High Sierra machine).  Thanks

**Comment by gsmurray** [comment]
Thanks Brian,

I tried the Nightly Build,

Receive the following Dialog when either double-clicking to open or Right-Click->open:

[cid:image001.png@01D585C4.3AAB3280]

Selecting Open does not result in the App opening, but just closed the dialog.
However, Double-Click or Right-Click-> does open the App every time after this procedure.

Similar to the previous behaviour for Gatekeeper set to “App Store and Identified Developers.”

George Scott Murray
O | 6136705388
M | 6137935792

**Comment by tarun-dholariya** [comment]
I have catalina installed on my mac, I downloaded TigerVNC-1.10.80.dmg from http://tigervnc.bphinz.com/nightly/ , and it worked fine.
Thanks for the fix.

**Comment by bphinz** [comment]
@gsmurray, Can you try the attached .dmg?  I had to zip it in order to attach it to the issue.  This one is built targeting the 10.9 SDK, which the Gatekeeper docs say is the minimum supported SDK version.  Thanks

[TigerVNC-1.10.80.dmg.zip](https://github.com/TigerVNC/tigervnc/files/3753522/TigerVNC-1.10.80.dmg.zip)

**Comment by tarun-dholariya** [comment]
It works, thanks.

**Comment by gsmurray** [comment]
Thanks Brian,

This version does not present any dialogs on Startup; initial or subsequent.

Not sure if I mentioned, our Gatekeeper setting are only App Store or Identified Publishers

Thanks again for this

George Scott Murray
O | 6136705388
M | 6137935792

**Comment by bphinz** [comment]
OK, the build recipe has been altered to target the 10.9 SDK and incorporate Apple's notarization service for the dmg so I'm going to go ahead and close this issue.

**Comment by radonish** [comment]
@tarun-dholariya, could I bother you to add some details about your configuration to #915 please? I saw you mention above that you had success with 1.10.80 on macOS Catalina above.

Thank you
