### ISSUE TITLE
Conflict between vncserver and x11vnc

### ISSUE THREAD

**Issue by jejo86** [TigerVNC/tigervnc#884]
# Error Description
On my system:
* Linux Mint 19.2 XFCE
* LightDM
* x11vnc
  * x11vnc/bionic,now 0.9.13-3 amd64  [installiert]
  * x11vnc-data/bionic,bionic,now 0.9.13-3 all  [Installiert,automatisch]
* tigervnc
  * ubuntu package
    * tigervnc-common/bionic,now 1.7.0+dfsg-8ubuntu2 amd64  [installiert]
    * tigervnc-standalone-server/bionic,now 1.7.0+dfsg-8ubuntu2 amd64  [installiert]
    * tigervnc-xorg-extension/bionic,now 1.7.0+dfsg-8ubuntu2 amd64  [installiert]
  * [latest binaries](https://bintray.com/tigervnc/stable/tigervnc/1.9.0) (1.9.0)
* Client is irrelevant (Several clients on Windows 7)
  * tightvnc 2.8.11
  * tigervnc 1.90
  * remote desktop with xrdp running

I cannot run **both** x11vnc **and** vncserver **at the same time**. The following errors occur:

1. vncserver does not start correctly (XIO:  fatal IO error 11)
2. Black screen when connecting to the secondly started vncserver (first started does work)
3. LightDM gets messed up, always returning to login screen when trying to log in (x11vnc).

# Tests
The following tests describe how to reproduce the errors.

## x11vnc first, vncserver 1.70 second (1)
First starting x11vnc:
```
sudo x11vnc -display :0 -nomodtweak -auth guess -forever -noxdamage -repeat -rfbauth /home/USERNAME/.vnc/passwd -rfbport 5900 -shared
```
Now connecting from Windows with one of the VNC clients. Logging in -> no problem, desktop is shown.

Then starting vncserver
```
<USERNAME>@laptop-linux:~$ vncserver -localhost no

New 'laptop-linux:1 (<USERNAME>)' desktop at :1 on machine laptop-linux

Starting applications specified in /etc/X11/Xvnc-session
Log file is /home/<USERNAME>/.vnc/laptop-linux:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/<USERNAME>/.vnc/passwd laptop-linux:1 to connect to the VNC server.


vncserver: Failed command '/etc/X11/Xvnc-session': 256!

=================== tail -15 /home/<USERNAME>/.vnc/laptop-linux:1.log ===================
syswrite() on closed filehandle WH at /usr/bin/tigervncserver line 888.

Xvnc TigerVNC 1.7.0 - built Dec  5 2017 09:25:01
Copyright (C) 1999-2016 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11905000, The X.Org Foundation


Sun Oct 20 17:32:48 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 175 requests (175 known processed) with 0 events remaining.
Killing Xtigervnc process ID 3850... which seems to be deadlocked. Using SIGKILL!

====================================================================================

Starting applications specified in /etc/X11/Xvnc-session has failed.
Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
```
-> Does not work.
(Why `created VNC server for screen 0`?? I would have expected `created VNC server for screen 1`!)

Kill x11vnc (`x11vnc -R stop`)
Try again to start `vncserver -localhost no' -> Same error -> Reboot system.

## x11vnc first, vncserver 1.70 second (2)
Same steps as in _x11vnc first (1)_, except the reboot at the end.

Try to start as root [This messes up LightDM!!]:
```
<USERNAME>@laptop-linux:~$ sudo vncserver -localhost no

New 'laptop-linux:1 (root)' desktop at :1 on machine laptop-linux

Starting applications specified in /etc/X11/Xvnc-session
Log file is /home/<USERNAME>/.vnc/laptop-linux:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/<USERNAME>/.vnc/passwd laptop-linux:1 to connect to the VNC server.
```
-> Seems to work -> Connecting with VNC client -> Asking for password -> Works, but obviously logged in as root.

Kill vncserver (`sudo vncserver -kill :*`)
Start x11vnc again. -> Cannot log in. Login screen is in a loop.
Fix messed up login:
```
rm .Xauthority* .ICEauthority*
touch .Xauthority
```
Start x11vnc again. -> Works, including the login.
Stop x11vnc, start vncserver -> Does not work, same error as above.

## vncserver 1.70 first, x11vnc second (1)
Start vncserver:
```
<USERNAME>@laptop-linux:~$ vncserver -localhost no

New 'laptop-linux:1 (<USERNAME>)' desktop at :1 on machine laptop-linux

Starting applications specified in /etc/X11/Xvnc-session
Log file is /home/<USERNAME>/.vnc/laptop-linux:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/<USERNAME>/.vnc/passwd laptop-linux:1 to connect to the VNC server.
```
Connect via VNC viewer -> No problem.

Start x11vnc -> Connect via VNC Viewer -> Trying to log in -> Error, LightDM login loop
Kill vncserver -> Start x11vnc (Did not delete .Xauthority .ICEauthority files) -> Connect -> no problem -> Seeing same desktop as previously with vncserver !!

## vncserver 1.70 first, x11vnc second (2)

This time I explicitly specified to start a display :1 `vncserver :1 -localhost no` -> No difference.

## x11vnc first, vncserver 1.90 second (1)

Same steps as in **x11vnc first, vncserver 1.70 second (1)**, just with the latest binaries. 

With this version the vncserver at least starts after x11vnc is already running and a user is logged in. Tthe log file shows the following:
```
Xvnc TigerVNC 1.9.0 - built Jul 16 2018 14:18:04
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 11400000, The X.Org Foundation

Initializing built-in extension VNC-EXTENSION
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension GLX

Sun Oct 20 18:34:12 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0

Sun Oct 20 18:34:33 2019
 Connections: accepted: 192.168.77.22::59703
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Sun Oct 20 18:34:37 2019
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
```
Logging in using a VNC client works, but a black screen is shown!

Stopping vncserver and x11vnc. Starting vncserver again, loging in -> Still only a black screen. -> Reboot

## vncserver 1.90 first, x11vnc second (1)

Start vncserver -> Connect -> no problem
Start x11vnc -> Connect -> Error: LightDM login loop
Stop vncserver -> Start x11vnc -> Connect -> no problem

**Comment by CendioOssman** [comment]
I'm afraid most desktop environments do not support multiple logins as the same user. It doesn't look like anything goes wrong with TigerVNC, but rather that the desktop environment fails to start.

So I'm afraid there isn't much we can do about this from our end. :/

What is it you're trying to achieve? Running just one for x11vnc or TigerVNC should be enough.

**Comment by jejo86** [comment]
Ahh, I see. I guess it is a limitation of XFCE then. I am using the same setup with Ubuntu Mate 16.04 and CentOS 7.5, so GNOME version 2 and 3 do not seem to have a problem with multiple logins of the same user.

The setup would be needed for the way I like to work. I want to work locally on my laptop (where I am setting this up) but if I want to change position using my desktop PC, i.e. sitting on my sofa and using the TV as a screen, or sitting at my desk using an LCD monitor, I want to continue working with all the previously opened applications by connecting via RDP / VNC. That is why I have xrdp and x11vnc installed.
Sometimes I also want to connect to a virtual X11 so that I can change the resolution, which for my laptop is limited to 1280x800. Using a virtual X11 session I can scale the laptop's desktop to full screen on my desktop PC, i.e. the TV's (1920x1080) or the LCD monitor's (1280x1024) resolution. That is why I wanted to use any other VNC solution, like TigerVNC.

Making sure I am always logged in only once is not a good solution for me. My plan is to create a new user _<USERNAME>_virtual_, probably symlinking the `/home/<USERNAME>_virtual` folder to my main user's home directory `/home/<USERNAME>`, so that I have exactly the same settings for both users. This will obviously not work, but maybe step by step I can find out which files need to be individual for each user for a second login to work (probably at least the `.Xauthority` and `.ICEauthority` files?!). I'll have to find out whether that is a good approach...

Thanks for the comment!

**Comment by dwmadden** [comment]
For what it's worth, I have this setup working mostly stable (copy/paste does not work from remote<->host for tigervncserver sessions). I'm on MacOS 10.14.6 using VNCViewer (https://www.realvnc.com/en/connect/download/viewer/) to connect to both my x11vnc and tigervncserver sessions running on my linux box (Debian)

The trick for me was updating my xstartup file, here's mine:
`#!/bin/sh
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
unset XDG_RUNTIME_DIR
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
xfce4-session &`

My invocation of x11vnc:
`x11vnc -display :0 -forever -bg -rfbauth /home/<YOUR_USERNAME>/.vnc/passwd`

And tigervncserver:
`tigervncserver :3 -verbose -geometry 2880x1800 -localhost no`

As I said, copy/paste between mac and tigervnc does't work but it does work on my x11vnc sessions (still trying to debug that). But otherwise its very useful to have this setup working. Good luck!
