### ISSUE TITLE
Clipboard not working for Russian

### ISSUE THREAD

**Issue by Pascal666** [TigerVNC/tigervnc#885]
I am running vncviewer64-1.9.0.exe on Microsoft Windows Version 10.0.18362.418 and tigervnc-server-1.9.0-1.el7.x86_64 and Google Chrome Version 77.0.3865.120 (Official Build) (64-bit) on CentOS Linux release 7.7.1908 (Core).  At https://play.google.com/store/apps/details?id=com.cleaner.storage.ram.booster.cachecleaner&showAllReviews=true there is a review left by Anna Krivenkova on August 24, 2019 in Russian.  When I copy this into my clipboard it pastes fine into other windows on Linux but when I try to paste to any apps on Windows I get:
 ÐÑÐµÐ½Ñ ÑÐ¾ÑÐ¾ÑÐµÐµ Ð¿ÑÐ¸Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ! ÐÐµÐ¹ÑÑÐ²Ð¸ÑÐµÐ»ÑÐ½Ð¾ ÑÐ¸ÑÑÐ¸Ñ ÐºÑÑ Ð¸ Ð²ÑÐ¿Ð¾Ð»Ð½ÑÐµÑ ÑÐ²Ð¾Ð¸ Ð¾Ð±ÑÐ·Ð°Ð½Ð½Ð¾ÑÑÐ¸ - Ð²ÑÐµÐ¼ ÑÐµÐºÐ¾Ð¼Ð¼ÐµÐ½Ð´ÑÑ. ÐÐµÑ Ð½Ð¸ÐºÐ°ÐºÐ¾Ð¹ Ð¿Ð¾Ð³Ð°Ð½Ð¾Ð¹ ÑÐµÐºÐ»Ð°Ð¼Ñ, ÐºÐ¾ÑÐ¾ÑÐ°Ñ Ð¿ÑÐµÐ²ÑÐ°ÑÐ°ÐµÑ Ð¸ÑÐ¿Ð¾Ð»ÑÐ·Ð¾Ð²Ð°Ð½Ð¸Ðµ Ð² ÐºÐ°ÐºÐ¾Ðµ ÑÐ¾ Ð¿Ð¼ÑÐ½Ð¾Ðµ Ð½Ð°ÐºÐ°Ð·Ð°Ð½Ð¸Ðµ. Ð¯ Ð¾ÑÐµÐ½Ñ Ð²ÑÐµÐ¼ ÑÐµÐºÐ¾Ð¼Ð¼ÐµÐ½Ð´ÑÑ! =)

**Comment by CendioOssman** [comment]
I'm afraid 1.9.0 does not support Cyrillic characters in the clipboard. Please try the nightly build instead. It should handle it better.

Note that both the server and client need to be upgraded for things to work.

**Comment by Pascal666** [comment]
Confirmed working when installed from http://tigervnc.bphinz.com/nightly/

Thank you.
