### ISSUE TITLE
Back key stuck on centos 8

### ISSUE THREAD

**Issue by imtrobin** [TigerVNC/tigervnc#888]
Hi, I've installed tigervnc on centos 8. I can connect through vnc fine, display shows but the "back" key seems to be pressed always (I have checked, it's not the keyboard). On the centos login menu, I can't enter the password to login because whatever I entered, it gets erased ('back key is pressed')

1. Connect to VNC server. I tried 3 different VNC clients.
2. Display shows fine. Click on password on centos login
3. Type password, and it keeps getting erased.

Client: Windows 10, tried tightvnc, vncviewr, tiger viewer.

Server 
- Centos8, TigerVNC 1.9.0
Installed using these instructions
https://www.linuxtechi.com/install-configure-vnc-server-centos8-rhel8/

**Comment by navysurfer** [comment]
Can you post the output of `systemctl status vncserver@:1.service` and `cat /home/$USER/$HOST:1.log` where $USER is your username and $HOST is the hostname of your server.  Selinux and pam dont play nicely with running vncserver as a system service with the currently available rpm on the centos 8 repo.

**Comment by imtrobin** [comment]
[root@localhost ~]# systemctl status vncserver@:1.service
● vncserver@:1.service - Remote Desktop VNC Service
   Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-10-23 08:43:13 +08; 9h ago
  Process: 1500 ExecStart=/usr/bin/vncserver -autokill :1 (code=exited, status=0/SUCCESS)
  Process: 1442 ExecStartPre=/bin/sh -c /usr/bin/vncserver -kill :1 > /dev/null 2>&1 || : (code=exited, sta>
    Tasks: 295 (limit: 26213)
   Memory: 645.3M
   CGroup: /system.slice/system-vncserver.slice/vncserver@:1.service
           ├─1527 /usr/bin/Xvnc :1 -auth /home/robin/.Xauthority -desktop localhost.localdomain:1 (robin) ->
           ├─2796 sh -c (/home/robin/.vnc/xstartup; /usr/bin/vncserver -kill :1) >> '/home/robin/.vnc/local>
           ├─2797 /bin/sh /home/robin/.vnc/xstartup
           ├─2798 /usr/libexec/gnome-session-binary
           ├─2807 dbus-launch --sh-syntax --exit-with-session
           ├─2808 /usr/bin/dbus-daemon --syslog --fork --print-pid 6 --print-address 8 --session
           ├─2817 /usr/bin/ssh-agent /etc/X11/xinit/Xclients
           ├─2848 /usr/libexec/at-spi-bus-launcher
           ├─2853 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofor>
           ├─2856 /usr/libexec/at-spi2-registryd --use-gnome-session
           ├─2861 /usr/libexec/gvfsd
           ├─2868 /usr/libexec/gvfsd-fuse /home/robin/.gvfs -f -o big_writes
           ├─2906 /usr/bin/gnome-keyring-daemon --start --components=pkcs11
           ├─2925 /usr/bin/gnome-shell
           ├─3033 ibus-daemon --xim --panel disable
           ├─3037 /usr/libexec/ibus-dconf
           ├─3038 /usr/libexec/ibus-extension-gtk3
           ├─3040 /usr/libexec/ibus-x11 --kill-daemon
           ├─3043 /usr/libexec/ibus-portal
           ├─3051 /usr/libexec/xdg-permission-store
           ├─3062 /usr/libexec/gnome-shell-calendar-server
           ├─3067 /usr/libexec/evolution-source-registry
           ├─3074 /usr/libexec/goa-daemon
...skipping...
   Loaded: loaded (/etc/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-10-23 08:43:13 +08; 9h ago
  Process: 1500 ExecStart=/usr/bin/vncserver -autokill :1 (code=exited, status=0/SUCCESS)
  Process: 1442 ExecStartPre=/bin/sh -c /usr/bin/vncserver -kill :1 > /dev/null 2>&1 || : (code=exited, sta>
    Tasks: 295 (limit: 26213)
   Memory: 645.3M
   CGroup: /system.slice/system-vncserver.slice/vncserver@:1.service
           ├─1527 /usr/bin/Xvnc :1 -auth /home/robin/.Xauthority -desktop localhost.localdomain:1 (robin) ->
           ├─2796 sh -c (/home/robin/.vnc/xstartup; /usr/bin/vncserver -kill :1) >> '/home/robin/.vnc/local>
           ├─2797 /bin/sh /home/robin/.vnc/xstartup
           ├─2798 /usr/libexec/gnome-session-binary
           ├─2807 dbus-launch --sh-syntax --exit-with-session
           ├─2808 /usr/bin/dbus-daemon --syslog --fork --print-pid 6 --print-address 8 --session
           ├─2817 /usr/bin/ssh-agent /etc/X11/xinit/Xclients
           ├─2848 /usr/libexec/at-spi-bus-launcher
           ├─2853 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofor>
           ├─2856 /usr/libexec/at-spi2-registryd --use-gnome-session
           ├─2861 /usr/libexec/gvfsd
           ├─2868 /usr/libexec/gvfsd-fuse /home/robin/.gvfs -f -o big_writes
           ├─2906 /usr/bin/gnome-keyring-daemon --start --components=pkcs11
           ├─2925 /usr/bin/gnome-shell
           ├─3033 ibus-daemon --xim --panel disable
           ├─3037 /usr/libexec/ibus-dconf
           ├─3038 /usr/libexec/ibus-extension-gtk3
           ├─3040 /usr/libexec/ibus-x11 --kill-daemon
           ├─3043 /usr/libexec/ibus-portal
           ├─3051 /usr/libexec/xdg-permission-store
           ├─3062 /usr/libexec/gnome-shell-calendar-server
           ├─3067 /usr/libexec/evolution-source-registry
           ├─3074 /usr/libexec/goa-daemon
           ├─3092 /usr/libexec/gvfs-udisks2-volume-monitor
           ├─3105 /usr/libexec/gvfs-mtp-volume-monitor
           ├─3115 /usr/libexec/goa-identity-service
           ├─3120 /usr/libexec/gvfs-gphoto2-volume-monitor
           ├─3129 /usr/libexec/gvfs-afc-volume-monitor
           ├─3135 /usr/libexec/gvfs-goa-volume-monitor
           ├─3163 /usr/libexec/gsd-power
           ├─3164 /usr/libexec/gsd-print-notifications
           ├─3166 /usr/libexec/gsd-rfkill
           ├─3167 /usr/libexec/gsd-screensaver-proxy
           ├─3168 /usr/libexec/gsd-sharing
           ├─3170 /usr/libexec/gsd-smartcard
           ├─3174 /usr/libexec/gsd-sound
           ├─3176 /usr/libexec/gsd-xsettings
           ├─3179 /usr/libexec/gsd-wacom
           ├─3193 /usr/libexec/gsd-clipboard
           ├─3197 /usr/libexec/gsd-a11y-settings
           ├─3199 /usr/libexec/gsd-datetime
           ├─3200 /usr/libexec/gsd-housekeeping
           ├─3202 /usr/libexec/gsd-color
           ├─3205 /usr/libexec/gsd-media-keys
           ├─3208 /usr/libexec/gsd-mouse
           ├─3212 /usr/libexec/gsd-keyboard
           ├─3231 /usr/bin/pulseaudio --start
           ├─3270 /usr/libexec/evolution-calendar-factory
           ├─3290 /usr/libexec/evolution-calendar-factory-subprocess --factory all --bus-name org.gnome.evo>
           ├─3307 /usr/libexec/dconf-service
           ├─3311 /usr/libexec/evolution-addressbook-factory
           ├─3335 /usr/libexec/evolution-addressbook-factory-subprocess --factory all --bus-name org.gnome.>
           ├─3352 /usr/libexec/ibus-engine-simple
           ├─3362 /usr/libexec/gsd-printer
           ├─3428 /usr/libexec/tracker-miner-apps
           ├─3431 /usr/libexec/tracker-miner-fs
           ├─3433 /usr/bin/gnome-software --gapplication-service
           ├─3437 /usr/libexec/gsd-disk-utility-notify
           └─3442 /usr/libexec/tracker-store

Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: Object St.BoxLayout (0x559afc9ef450), has been alr>
Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: clutter_actor_hide: assertion 'CLUTTER_IS_ACTOR (s>
Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: Object St.BoxLayout (0x559afc9ef450), has been alr>
Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: Object St.Entry (0x559afb34c320), has been already>
Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: Object St.Button (0x559afa6f9600), has been alread>
Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: Object St.Button (0x559afa6f9600), has been alread>
Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: Object St.Entry (0x559afb34c320), has been already>
Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: Object St.Entry (0x559afb34c320), has been already>
Oct 23 14:45:00 localhost.localdomain gnome-shell[2925]: JS ERROR: Exception in callback for signal: verifi>
                                                         updateSensitivity@resource:///org/gnome/shell/gdm/>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _onVerificationFailed@resource:///org/gnome/shell/>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _emit@resource:///org/gnome/gjs/modules/signals.js>
                                                         _verificationFailed@resource:///org/gnome/shell/gd>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _reportInitError@resource:///org/gnome/shell/gdm/u>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _reauthenticationChannelOpened@resource:///org/gno>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
Oct 23 14:45:01 localhost.localdomain gnome-shell[2925]: JS ERROR: Exception in callback for signal: no-mor>
                                                         _updateDefaultService@resource:///org/gnome/shell/>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _onReset@resource:///org/gnome/shell/gdm/util.js:5>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _cancelAndReset@resource:///org/gnome/shell/gdm/ut>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _verificationFailed/signalId<@resource:///org/gnom>
                                                         _emit@resource:///org/gnome/gjs/modules/signals.js>
                                                         finishMessageQueue@resource:///org/gnome/shell/gdm>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _queueMessageTimeout@resource:///org/gnome/shell/g>
                                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.>
                                                         _queueMessageTimeout/this._messageQueueTimeoutId<@

**Comment by imtrobin** [comment]
I can't find the vnc logs, but these are the logs from cockpit, nothing about vnc

 13:58 Failed to initialize daemon. pulseaudio
 13:58 Module load failed. pulseaudio
 13:58 Failed to load module "module-esound-protocol-unix" (argument: ""): initialization failed. pulseaudio
 13:58 bind(): Address already in use pulseaudio
 13:58 SELinux is preventing /usr/libexec/geoclue from search access on the directory 2925. For complete SELinux messages run: sealert -l 9795dd6f-d001-4df6-9dad-738036b1d8f0 setroubleshoot
 13:58 Cannot access vdagent virtio channel /dev/virtio-ports/com.redhat.spice.0 spice-vdagent
 13:58 Failed to start Sound Service. systemd 6 
 09:51 SELinux is preventing logrotate from write access on the directory netdata. For complete SELinux messages run: sealert -l 249188a9-74c3-4351-b941-18861c6349b0 setroubleshoot
 09:51 Plugin Exception catchall_labels setroubleshoot
 09:51 Can't find sendmail at /usr/sbin/sendmail, not mailing output anacron
 08:43 SELinux is preventing /usr/libexec/geoclue from search access on the directory 2925. For complete SELinux messages run: sealert -l 9795dd6f-d001-4df6-9dad-738036b1d8f0 setroubleshoot
 08:43 SELinux is preventing /usr/libexec/geoclue from search access on the directory 3202. For complete SELinux messages run: sealert -l 9795dd6f-d001-4df6-9dad-738036b1d8f0 setroubleshoot
 08:43 GetManagedObjects() failed: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.352" (uid=1000 pid=3231 comm="/usr/bin/pulseaudio --start " label="system_u:system_r:unconfined_service_t:s0") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.bluez" (bus) pulseaudio
 08:43 Cannot access vdagent virtio channel /dev/virtio-ports/com.redhat.spice.0 spice-vdagent 2 
 08:43 EDAC skx: ECC is disabled on imc 0 kernel
 08:43 nouveau 0000:68:00.0: bus: MMIO read of 00000000 FAULT at 10ac08 [ IBUS ] kernel
 08:43 nouveau 0000:68:00.0: bus: MMIO read of 00000000 FAULT at 3e6684 [ IBUS ] kernel

**Comment by navysurfer** [comment]
I had the log location wrong.   Itll be in the .vnc folder in your user directory.  First, try stopping the service.  `systemctl stop vncserver@:1.service` as root.
Next, make sure you're logged in as the user you'd like vnc to display. Just run `vncserver :1` from the command line.
Try connecting and let me know if it works.

**Comment by imtrobin** [comment]
ok, the manual starting method works fine. I can VNC in and keyboard is normal.

**Comment by navysurfer** [comment]
Good to hear.  First thing kill your running service: `vncserver -kill :1`
Then disable the system service as root: `systemctl disable vncserver@:1.service`
Now as root run:`loginctl enable-linger $USER`
Then as your user you'd like to connect to `systemctl --user enable vncserver@:1.service`
Again as user `systemctl --user start vncserver@:1.service`

Try connecting again.  If it works try rebooting your server and connecting again to make sure it's starting correctly on boot.

**Comment by imtrobin** [comment]
This setup auto logins me in as root? It disconnects VNC when I logout.

**Comment by navysurfer** [comment]
It shouldn't.  When you run `systemctl --user enable vncserver@:1.service` make sure you run it as the user you want to use for vnc and do not use sudo.   When you enable-linger, it prevents the service from being killed on logout.  It'll also start the service automatically on boot.

**Comment by navysurfer** [comment]
Also, if systemctl --user doesn't find the service, it may not be in your home directory.  If it's not there run `cp /usr/lib/systemd/user/vncserver@.service ~/.config/systemd/user/` Make sure not to use sudo.  Then run `systemctl --user daemon-reload`.  After that the commands above should work.

**Comment by imtrobin** [comment]
Ok, I used sudo, It works now.

But the original keyboard problem is, can't be fixed?

**Comment by navysurfer** [comment]
You said it's on the login screen?   Are you getting a login screen when you connect with vnc viewer?  Which login screen are you referring to?

**Comment by imtrobin** [comment]
Ok, I thought I did something wrong.

**Comment by navysurfer** [comment]
I had a very similar problem last week with it.  Once I ran it as a user script,  it fixed the issue.  The dev's are working on an updated version that works better with Cent8.  It may be awhile though.

**Comment by imtrobin** [comment]
Hmm, I'm not sure if its solved. I left my machine running overnight, and when I try to login in the morning, the login screen pops up and the "Back" key problem is back again.

**Comment by navysurfer** [comment]
Sorry to hear.  Hopefully someone with more experience then me can help you out.  It might help to post your logs again for them.  Outputs of systemctl --user status vncserver@:1.service, and your log at ~/.vnc/host:1.log.  It's running differently now than the last time you posted them, so hopefully it'll shed some more light on it.

**Comment by imtrobin** [comment]
systemctl --user status vncserver@:1.service
● vncserver@:1.service - Remote desktop service (VNC)
   Loaded: loaded (/usr/lib/systemd/user/vncserver@.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-10-26 12:08:58 +08; 1 day 23h ago
  Process: 1548 ExecStart=/usr/bin/vncserver :1 (code=exited, status=0/SUCCESS)
  Process: 1527 ExecStartPre=/bin/sh -c /usr/bin/vncserver -kill :1 > /dev/null 2>&1 || : (code=exited, sta>
    Tasks: 292 (limit: 26213)
   Memory: 714.3M
   CGroup: /user.slice/user-0.slice/user@0.service/vncserver.slice/vncserver@:1.service
           ├─ 1567 /usr/bin/Xvnc :1 -auth /root/.Xauthority -desktop localhost.localdomain:1 (root) -fp cat>
           ├─ 2872 /bin/sh /root/.vnc/xstartup
           ├─ 2873 /usr/libexec/gnome-session-binary
           ├─ 2882 dbus-launch --sh-syntax --exit-with-session
           ├─ 2883 /usr/bin/dbus-daemon --syslog --fork --print-pid 7 --print-address 9 --session
           ├─ 2891 /usr/bin/ssh-agent /etc/X11/xinit/Xclients
           ├─ 2920 /usr/libexec/at-spi-bus-launcher
           ├─ 2925 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofo>
           ├─ 2928 /usr/libexec/at-spi2-registryd --use-gnome-session
           ├─ 2932 /usr/libexec/gvfsd
           ├─ 2939 /usr/libexec/gvfsd-fuse /run/user/0/gvfs -f -o big_writes
           ├─ 2971 /usr/bin/gnome-keyring-daemon --start --components=pkcs11
           ├─ 3056 ibus-daemon --xim --panel disable
           ├─ 3060 /usr/libexec/ibus-dconf
           ├─ 3061 /usr/libexec/ibus-extension-gtk3
           ├─ 3063 /usr/libexec/ibus-x11 --kill-daemon
           ├─ 3066 /usr/libexec/ibus-portal
           ├─ 3074 /usr/libexec/xdg-permission-store
           ├─ 3094 /usr/libexec/gnome-shell-calendar-server
           ├─ 3113 /usr/libexec/evolution-source-registry
           ├─ 3118 /usr/libexec/gvfs-udisks2-volume-monitor
           ├─ 3126 /usr/libexec/gvfs-mtp-volume-monitor
           ├─ 3129 /usr/libexec/goa-daemon
           ├─ 3134 /usr/libexec/gvfs-gphoto2-volume-monitor
           ├─ 3139 /usr/libexec/gvfs-afc-volume-monitor
           ├─ 3147 /usr/libexec/gvfs-goa-volume-monitor
           ├─ 3156 /usr/libexec/goa-identity-service
           ├─ 3162 /usr/libexec/gsd-power
           ├─ 3163 /usr/libexec/gsd-print-notifications
           ├─ 3165 /usr/libexec/gsd-rfkill
           ├─ 3166 /usr/libexec/gsd-screensaver-proxy
           ├─ 3167 /usr/libexec/gsd-sharing
           ├─ 3168 /usr/libexec/gsd-smartcard
           ├─ 3172 /usr/libexec/gsd-sound
           ├─ 3175 /usr/libexec/gsd-xsettings
           ├─ 3177 /usr/libexec/gsd-wacom
           ├─ 3199 /usr/libexec/gsd-clipboard
           ├─ 3200 /usr/libexec/gsd-a11y-settings
           ├─ 3201 /usr/libexec/gsd-datetime
           ├─ 3202 /usr/libexec/gsd-housekeeping
           ├─ 3204 /usr/libexec/gsd-color
           ├─ 3206 /usr/libexec/gsd-media-keys
           ├─ 3209 /usr/libexec/gsd-mouse
           ├─ 3211 /usr/libexec/gsd-keyboard
           ├─ 3255 /usr/libexec/tracker-miner-apps
           ├─ 3259 /usr/libexec/tracker-miner-fs
           ├─ 3262 /usr/bin/gnome-software --gapplication-service
           ├─ 3264 /usr/libexec/evolution-calendar-factory
           ├─ 3267 /usr/libexec/tracker-store
           ├─ 3276 /usr/libexec/gsd-disk-utility-notify
           ├─ 3312 /usr/libexec/evolution-calendar-factory-subprocess --factory all --bus-name org.gnome.evolution.dataserver.Subprocess.Backend.Calendarx3264x2 --own-path /org/gnome/evolution/dataserver/Su>
           ├─ 3326 /usr/libexec/dconf-service
           ├─ 3328 /usr/libexec/evolution-addressbook-factory
           ├─ 3339 /usr/libexec/ibus-engine-simple
           ├─ 3348 /usr/libexec/gsd-printer
           ├─ 3359 /usr/libexec/evolution-addressbook-factory-subprocess --factory all --bus-name org.gnome.evolution.dataserver.Subprocess.Backend.AddressBookx3328x2 --own-path /org/gnome/evolution/dataser>
           └─13904 /usr/bin/gnome-shell

Oct 28 11:29:33 localhost.localdomain gsd-media-keys[3206]: g_variant_unref: assertion 'value != NULL' failed
Oct 28 11:29:33 localhost.localdomain gnome-shell[13904]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session.
Oct 28 11:29:33 localhost.localdomain org.gnome.Shell.desktop[13904]: current session already has an ibus-daemon.
Oct 28 11:29:33 localhost.localdomain gnome-shell[13904]: Failed to register AuthenticationAgent
Oct 28 11:29:33 localhost.localdomain gnome-shell[13904]: Telepathy is not available, chat integration will be disabled.
Oct 28 11:29:33 localhost.localdomain gsd-color[3204]: could not find device: property match 'XRANDR_name'='VNC-0' does not exist
Oct 28 11:29:33 localhost.localdomain gnome-shell[13904]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Oct 28 11:29:34 localhost.localdomain gnome-shell[13904]: GNOME Shell started at Mon Oct 28 2019 11:29:33 GMT+0800
Oct 28 11:29:34 localhost.localdomain gnome-session[2873]: gnome-session-binary[2873]: WARNING: Could not get session path for session. Check that logind is properly installed and pam_systemd is getting use>
Oct 28 11:29:34 localhost.localdomain gnome-session-binary[2873]: WARNING: Could not get session path for session. Check that logind is properly installed and pam_systemd is getting used at login.

**Comment by imtrobin** [comment]
less ~/.vnc/localhost.localdomain\:1.log

Xvnc TigerVNC 1.9.0 - built May 14 2019 23:36:08
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12003000, The X.Org Foundation


Sat Oct 26 12:08:55 2019
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5901
 vncext:      created VNC server for screen 0

Sat Oct 26 12:08:58 2019
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:-nan ratio)

Mon Oct 28 11:29:23 2019
 Connections: accepted: 192.168.1.99::52144
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)

Mon Oct 28 11:29:24 2019
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888

Mon Oct 28 11:29:35 2019
 Connections: closed: 192.168.1.99::52144 (Clean disconnection)
 EncodeManager: Framebuffer updates: 509
 EncodeManager:   Tight:
 EncodeManager:     Solid: 40 rects, 919.413 kpixels
 EncodeManager:            640 B (1:5747.08 ratio)
 EncodeManager:     Bitmap RLE: 11 rects, 5.543 kpixels
 EncodeManager:                 353 B (1:63.1841 ratio)
 EncodeManager:     Indexed RLE: 518 rects, 3.23368 Mpixels
 EncodeManager:                  778.166 KiB (1:16.2403 ratio)
 EncodeManager:     Full Colour: 79 rects, 147.718 kpixels
 EncodeManager:                  84.9775 KiB (1:6.8012 ratio)
 EncodeManager:   Tight (JPEG):
 EncodeManager:     Full Colour: 64 rects, 1.92337 Mpixels
 EncodeManager:                  204.251 KiB (1:36.7876 ratio)
 EncodeManager:   Total: 712 rects, 6.22972 Mpixels
 EncodeManager:          1.04332 MiB (1:22.7855 ratio)
 ComparingUpdateTracker: 12.1475 Mpixels in / 3.53002 Mpixels out
 ComparingUpdateTracker: (1:3.4412 ratio)

**Comment by navysurfer** [comment]
It looks like it's still trying to load for root.  Do you have another user account other than root on the system?

**Comment by CendioOssman** [comment]
I wonder if this is simply the GNOME lock screen misbehaving. It has been known to do that before. Have you seen the issue in the session before the lock screen activates?

**Comment by imtrobin** [comment]
Yes, I have. The previous instructions, was working fine for my user. But it reverts back to root if idle after a while?

@CendioOssman , I tried logging in manually first, then vnc iin, no problem. So it only happens on lock screen

**Comment by navysurfer** [comment]
`├─ 1567 /usr/bin/Xvnc :1 -auth /root/.Xauthority -desktop localhost.localdomain:1 (root) -fp cat>
├─ 2872 /bin/sh /root/.vnc/xstartup`
This is the part of the log that's sticking out at me.  It's taking the xstartup script from the root folder and using root's Xauthority.  The systemd script is being called from the /usr/lib/systemd folder instead of the /home/$USER/.config/... folder.

When you enabled the systemd script, could you have accidently been su'd into the root account?  That could lead to this showing up in the logs.

When you get a chance, try this(unless @CendioOssman corrects me, :)):
su into root account:
    `su -`
As root: 
    `systemctl --user stop vncserver@:1.service`
    `systemctl --user disable vncserver@:1.service`
Leave root account:
    `exit`
As $USER (without using sudo)
    `systemctl --user enable vncserver@:1.service`
    `systemctl --user start vncserver@:1.service`

**Comment by imtrobin** [comment]
[root@localhost ~]# su -
[root@localhost ~]# systemctl --user stop vncserver@:1.service
Failed to connect to bus: No such file or directory
[root@localhost ~]# systemctl --user disable vncserver@:1.service
Failed to connect to bus: No such file or directory


[robin@localhost ~]$ systemctl --user enable vncserver@:1.service
[robin@localhost ~]$ systemctl --user start vncserver@:1.service

**Comment by navysurfer** [comment]
I spent a few hours tonight to try to replicate your problem, and couldn't.  I tried starting the user service as root(got the same bus error).  But clearly the service is being started as root somehow by looking at your logs.  Did you modify the service file in anyway?  It shouldn't need it.
As a last ditch effort, maybe try completely reinstalling everything.  After removing, delete your .vnc directories then install again.
After its installed, you shouldn't need to run sudo at all(you should still have enable-linger enabled) for any of the commands.  Just read the instructions located in the service file at /usr/lib/systemd/user/vncserver@.service and it'll tell you what you need to do.  
I know it works on Cent8, I have the cent 8 version of tigervnc installed on two VMs.  We just have to be missing something in your case.

**Comment by imtrobin** [comment]
@navysurfer Thanks Evan, I delete and reinstalled again, from user instead of root. Everything seems fine now. Though I would prefer to separate the centos login from the vnc, for now this will do.

**Comment by navysurfer** [comment]
I'm glad you finally got it working.  Hopefully you dont have any more problems.  Yeah, right now it's hard to separate logins like that with how security has changed in linux recently.  VNC isn't the only program to have issues like that.  Best of luck.

**Comment by CendioOssman** [comment]
Glad you got it working. :) Closing this issue.
