### ISSUE TITLE
How to disable auto display port selection

### ISSUE THREAD

**Issue by samgoud** [TigerVNC/tigervnc#892]
Hi,

I am using 1.8.0 version of tigervnc. When I run vncserver with display port 69 specified, I see

bash-4.2$ vncserver :69
A VNC server is already running as :69

New 'xxx.com:5 (user)' desktop is xxx.com:5

Starting applications specified in HOME/.vnc/xstartup
Log file is HOME/.vnc/xxx.com:5.log 

I see the vncserver picked display 5 as 69 was already in use. I want to disable this feature and want vncserver to stop if the requested display port was not available (this behavior was default in tigervnc 1.7 and seems to have changed in 1.8)

How do I disable it?

**Comment by CendioOssman** [comment]
I'm afraid that is not our `vncserver` as ours aborts when the port is already used. Please file a bug with the source of your TigerVNC package. Most likely your Linux distribution.
