### ISSUE TITLE
How to set up on windows?

### ISSUE THREAD

**Issue by yc200** [TigerVNC/tigervnc#893]
Hello, pardon my obvious ignorance, but I simply don't understand how to install the software. I can't find any help guide, can't see in the latest zip file anything remotely familiar to an installer the website mentioned, nothing about the TLS extension, and I simply.... just... don't... understand. Any help appreciated. I am clearly missing something or there is some secret prerequisite magical knowledge you all have which I don't.

**Comment by yc200** [comment]
Ok, I found the EXE's in the binary link and installed the server, but I still don't understand how to set up the software. No guide that I can see.

**Comment by CendioOssman** [comment]
The Windows server unfortunately lacks a maintainer, so it doesn't really get that much polish.

It should have set up a service and started it for you though. Do you have a TigerVNC icon in your systray now?

**Comment by yc200** [comment]
Hi Pierre,
Thanks for the message. Yes, I installed the software successfully, but
have no idea how to proceed. Probably a combination of my noobness and lack
of instructions. I am using anydesk for now, but really want to support
open-source projects like this one...

**Comment by CendioOssman** [comment]
Do you see a TigerVNC icon in your systray? Could you share a screenshot of the systray?

**Comment by CendioOssman** [comment]
No response. Closing.

**Comment by dbolton** [comment]
I'm also interested in some guidance on setting up TigerVNC on Windows. I am successfully using the viewer (on Windows) to access Ubuntu's built in VNC sharing, but would like to access the Windows computer remotely. 

I installed the server version. (First tried the stable 1.10.1 release. Currently on the prerelease "tigervnc64-1.10.80.exe" after reading suggestions on other issues in this tracker). After restarting, I have the TigerVNC icon in my system tray on Windows 10. I set a password. Then tried connecting from a different computer (on my home network) using the IP address of the Windows computer and the password. Are there additional steps I need to take? 

I'm happy to write up some documentation once I get it working for me.

**Comment by CendioOssman** [comment]
That sounds like the proper way to do things. Might also need to open up port 5900 in the Windows firewall as well.

Any documentation you can provide would be much appreciated.

**Comment by dbolton** [comment]
Okay I got it working and wrote up some basic instructions. My next step would be to figure out the best way to secure the connection. Any recommendations? 

## Private network
Check you are on a private network at home (not a public network). Then check that your computer knows that you are on a private network (steps below). 
 1. In the task bar (bottom right), right click on the Network icon and choose **Open Network & Internet settings**
 2. If it says "Private network" under your connection, skip to "Install and setup TigerVNC server." If it says "Public Network" continue.
 3. Choose **Change connection properties**
 4. Choose **Private**
 5. Close settings. 

## Install and setup TigerVNC server
 1. Download and install TigerVNC server using the default settings.
 2. Restart your computer.
 3. In the task bar (bottom right), choose the up arrow to show more task icons, then right click on the TigerVNC icon and choose **Options**
 4. Under Authentication choose **Configure** and type your 

## Firewall setup
The following instructions are for Windows built-in firewall. Adapt if you are using a 3rd-party firewall.
 1. From the **Start menu** type and choose **Firewall and network protection**
 2. Choose **Allow an app through firewall**
 3. Choose **Change settings**
 4. Choose **Add an app**
 5. Choose **Browse...**
 6. Browse to C:\Program Files\TigerVNC\winvnc4.exe
 7. Choose **Add**
 8. Chooseo **OK**
 
## Connecting
 1. Open the TigerVNC viewer on another computer (we'll call this the "remote computer")
 2. Type in the name or IP address of the computer you want to connect to, then choose **Connect**
 3. Type in the password you setup for the server. Then choose **OK**

## Troubleshooting
If you get a "Can't establish connection" error. Here are a few steps to try to locate the problem. 

 1. Open TigerVNC's viewer on the same computer and connect to "localhost". This checks the VNC server is working on your computer. If you get the same error, review the "Install and setup TigerVNC server" section above. 
 2. Open TigerVNC's viewer on the same computer and connect to your IP address on the network. This checks the firewall on the server computer is not an issue. If you get the same error on this step review the "Firewall setup" section above. 
 4. On the remote computer enter the IP address/computer name. Using TigerVNC's viewer on the remote computer is recommended. If you use another viewer, here's some setting to check:
   * Protocol: **VNC** (Virtual Network Computing)
   * Server: (name/IP address of computer on your local network)
   * Username: (leave blank)
   * Password: (password you set up on the server, or leave blank if you want it to ask you every time).

## Making the connection secure
[TO DO]

**Comment by CendioOssman** [comment]
To properly secure connection then X509 needs to be configured with proper certificates and all that.

A guide for doing that would also be helpful. It would be more generic though as it isn't specific for Windows .

Perhaps you can add what you have so far as a wiki page?

**Comment by dbolton** [comment]
I wrote up draft instructions (below), however haven't quite figured it all out. I'm getting "Authentication failure: authentication failure: Error loading X509 certificate or key". Any tips? 

I'll post these instructions on the wiki once I get a secure connection working. 
## Making the connection secure
### What is a X.509 certificate?
Certificates allow three important security functions.
 * Certificates prove your identy.
 * Certificates prove the identy of the remote computer.
 * Certificates keep private the contents of the communication between you and the remote computer. 

"X.509" is a standard type of certificate commonly used for websites. However, they are also useful for securing TigerVNC.

### Create a certificate
Follow the steps for your operating system.

#### Windows
Unfortunately TigerVNC doesn't understand [Windows-style certificates](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps) saved in the Windows certificate store or that end with the file extension `.pfx`. However, you can download a tool to do the job. 

On the computer with the TigerVNC server:
 1. Download **puttygen.exe** from https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
 2. Open **puttygen.exe**
 3. Choose **Generate**
 4. Follow the instructions onscreen (like moving your mouse randomly)
 5. Choose **Save public key** and use a file name like "vnc-server.crt"
 6. Choose **Save private key** and use a file name like "vnc-server-private.key".
 7. In Windows File Explorer go to the location you saved both files. By default puttygen adds `.ppk` to the end of the file. Delete `.ppk` (so that TigerVNC can open it). 

The private key should remain private to your computer. If you have syncing services (such as OneDrive, Dropbox, etc.), consider saving to a location that isn't synced or backed up. If you ever loose the private key, just create a new certificate and private key. 

#### Linux
[TO DO]

#### Mac OS
[TO DO]

### Use the certificate with TigerVNC
On the computer with TigerVNC server:
 1. Right click the TigerVNC icon in the system tray (bottom right). 
 2. Choose **Options**
 3. Under "Session encryption" choose **TLS with X.509 certificates**
 4. Choose **Load X.509 Certificate**. Browse to the public key file you saved above.
 5. Choose **Load X.509 Certificate key**. Browse to the private key file you saved above. 
 6. Choose **Apply**
 7. Copy the public key file ("vnc-server.crt") to your remote computer. 
 
On the remote (client) computer: 
 1. Open the TigerVNC viewer
 2. Type in the anme or IP address of the computer you want to connect to.
 3. Choose **Options...**
 4. Choose the **Security** tab
 5. Under **Path to X509 CA certificate** type the path to the public key file you just copied.
 6. Choose **OK**
 7. Choose **Connect**
 
### Why not use an external Certificate Authority (like Let's Encrypt)?
External Certificate Authorities issue certificates for public domain names but not local network IP addresses.

**Comment by CendioOssman** [comment]
That is unfortunately not the right approach. Putty generates SSH keys, not certificates. So I'm afraid another tool is needed.

The required format is PEM. Perhaps Windows' certificate tools can convert to that?

**Comment by dbolton** [comment]
I couldn't generate or convert to PEM format using Window's certificate tools, so I updated the draft instructions to use OpenSSL (see below). Unfortunately I'm still not able to connect. From the client computer I get the error: "Authentication failure: load of CA cert failed".

On the computer with the TigerVNC server:
 1. Find out the local IP address of the computer running the TigerVNC server. See [LifeHacker's instructions](https://lifehacker.com/how-to-find-your-local-and-external-ip-address-5833108) or depending on your browser [this webpage may be able to tell you](https://www.whatismybrowser.com/detect/what-is-my-local-ip-address).
 2. Visit https://bintray.com/vszakats/generic/openssl (Of the binaries [suggested by OpenSSL](https://wiki.openssl.org/index.php/Binaries), this is the simplest to run.)
 3. Choose the latest .zip download that matches your computer system (probably the one ending "win64-mingw.zip") 
 4. Uncompress the zip file.
 5. Go to the uncompress folder and double click **openssl.exe**.
 6. If you have Windows Defender SmartScreen, you may have to choose **More info** > **Run anyway**.
 7. Type the following (replace "192.168.1.5" with the local IP address you found in step 1 above)
    `req -x509 -newkey rsa -days 3650 -nodes -config openssl.cnf -keyout vnc-server-private.pem -out vnc-server.pem -subj '/CN=192.168.1.5'`

### Use the certificate with TigerVNC
On the computer with TigerVNC server:
 1. Right click the TigerVNC icon in the system tray (bottom right). 
 2. Choose **Options**
 3. Under "Session encryption" choose **TLS with X.509 certificates**
 4. Choose **Load X.509 Certificate**. Browse to the public key file you saved above ("vnc-server.pem").
 5. Choose **Load X.509 Certificate key**. Browse to the private key file you saved above ("vnc-server-private.pem"). 
 6. Choose **Apply**
 7. Copy the public key file ("vnc-server.pem") to your remote computer. 
 
On the remote (client) computer: 
 1. Open the TigerVNC viewer
 2. Type in the name or IP address of the computer you want to connect to.
 3. Choose **Options...**
 4. Choose the **Security** tab
 5. Under **Path to X509 CA certificate** type the path to the public key file you just copied.
 6. Choose **OK**
 7. Choose **Connect**

**Comment by dbolton** [comment]
I just noticed today, if I leave the **Path to X509 CA certificate** in the viewer options blank, it shows a different set of messages. The first two are expected.

1. "Hostname (192.168.1.5) does not match any certificate, do you want to continue?"
2. "The certificate has been signed by an unknown authority..."
3. "Authentication failure: Out of memory"

Is the last message a bug?

**Comment by dbolton** [comment]
I did it! https://github.com/TigerVNC/tigervnc/wiki/Windows:-Setup-TigerVNC-server

It turns out the viewer doesn't understand Windows-style path names. The viewer also doesn't understand Linux-style path names if there are any spaces. You can use paths with spaces from the command line, but not from the Viewer > Options.

**Comment by dbolton** [comment]
Is it possible to avoid the "hostname mismatch" warning? "Hostname (192.168.1.5) does not match any certificate, do you want to continue?"

**Comment by bigtfromaz** [comment]
Ok.  So what do you do when no icon shows up in the system tray?  The config app starts in user mode but doen;t seem to have an effect.  The windows service appears to be running and recycles without showing any errors.  And, yes, the machine has been rebooted.

**Comment by yc200** [comment]
Hi, please take me off this thread. Perhaps I'll try TigerVNC again in the
future.
Yam

**Comment by dbolton** [comment]
@yc200 Click the unsubscribe button at the bottom of the email to get removed. I don't know if there is a way for others to do that on your behalf. 

@bigtfromaz To help troubleshoot why it didn't appear in your system tray, can you share some details about your computer? Are you on Windows 10? Did you download the 64-bit version?

As a workaround you can open the config app directly. Go to the **Start menu** > **TigerVNC 64-bit** > **Configure VNC Service**. (Make sure you choose "Service" not "Server").

**Comment by CendioOssman** [comment]
Instructions look nice. Thanks. :)

Some things that might be worth noting though:

 * Self-signed certificates aren't particularly secure, which should probably be mentioned before leading people down this path. In particular they tend to fail at verifying the server.

 * Similarly, perhaps a section that the ideal situation is configuring "real" certificates, just like for your web server.

 * Hostnames are common even for internal networks, so perhaps details on how to generate a certificate for that?

**Comment by dbolton** [comment]
@CendioOssman Thank you for the feedback!

- Self-signed certificates should offer the same level of security (i.e. verifying the server) if the client/viewer checks against their copy of the public certificate. The instructions do this. At least on Windows, it doesn't even let you accept the certificate blindly (it gives a cryptic out-of-memory error if you try). Am I missing anything?
- I see how you can issue a "real" certificate: https://security.stackexchange.com/questions/103524/lets-encrypt-for-intranet-websites#121187 (basically you have to own a domain name (example.com), and then rename your local network to a subdomain of that (local.example.com), and then reference your computers as sub-subdomains (mylaptop.local.example.com). It looks like there is away to to that without needed a publicly-accessible server on your local network (using the http-01 challenge). The only potential disadvantage is your computer names become a matter of public record (so name them accordingly). Is that right?

**Comment by CendioOssman** [comment]
> * Self-signed certificates should offer the same level of security (i.e. verifying the server) if the client/viewer checks against their copy of the public certificate. The instructions do this. At least on Windows, TigerVNC doesn't even let you accept the certificate blindly (it gives a cryptic out-of-memory error if you try). Am I missing anything?
> 

You're right. I missed that. It might be prudent to emphasise that this step is necessary for security. The "out of memory" thing is a bug that will be fixed.

> * I see how you can issue a "real" certificate: https://security.stackexchange.com/questions/103524/lets-encrypt-for-intranet-websites#121187 (basically you have to own a domain name (example.com), and then rename your local network to a subdomain of that (local.example.com), and then reference your computers as sub-subdomains (mylaptop.local.example.com). It looks like there is away to to that without needed a publicly-accessible server on your local network (using the http-01 challenge). The only potential disadvantage is your computer names become a matter of public record (so name them accordingly). Is that right?

There are many ways of getting a "real" certificate and not all requires the server to be publically accessible. It is also common to have your own internal company CA infrastructure. We don't need to document any of the details of that as we can assume those people know how to deal with it.

What I think we should document is that if you can then you should get your certificate for TigerVNC the same way you would for any other TLS server (with the assumption they know how to do that). If you don't have that option then they can proceed to the self signed instructions that you've put together.

**Comment by bira19** [comment]
I was able to use TigerVNC 1.10.0 successfully on Windows 10. And, have tested on Windows 7 by connecting through LOCALHOST on the same machine. 
Does anyone know if this version works on Windows 7 Embedded? I have been trying using the same steps as Windows 10, but observed some strange issues. Like, when tried connecting using 'None' encryption method, it gave me the error that Password was not found. I checked the Registry but it looked like it was not getting updated.

If it supports Windows 7 embedded, is there any older version that I could use?

**Comment by CendioOssman** [comment]
The wiki pages are now up, so closing this issue. Any more questions can be handled on the mailing list, and the wiki can be updated if someone has more improvements to add.

**Comment by dbolton** [comment]
@CendioOssman: I updated the wiki with your recommendations. Changes include:
* Added a new section [Certificate from an External Certificate Authority](https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection#certificate-from-an-external-certificate-authority)
* Added the warning, "If you skip over any error messages, you may bypass all the security guarantees of using certificates." (See [Use the certificate with TigerVNC](https://github.com/TigerVNC/tigervnc/wiki/Secure-your-connection#use-the-certificate-with-tigervnc), remote computer, step 6).

**Comment by CendioOssman** [comment]
Looks good. Thanks.

**Comment by throrro** [comment]
Do you know if there is any option to define the TLS version and ciphers like in linux with "GnuTLSPriority"?
