### ISSUE TITLE
Tiger VNC Smart Card Authentication

### ISSUE THREAD

**Issue by cogswela** [TigerVNC/tigervnc#899]
I'm currently connecting to a RHEL 7.7 box via SSH and authenticating with my smart card. The RHEL box authenticates against an IdM server to allow access. 

Does TigerVNC / will TigerVNC allow smart card pass through to a RHEL 7.7 box using tigervnc-server? Is this a feature that is in development?

I see authentication options when using TigerVNC viewer but obviously there is not a box for smart cards.

**Comment by CendioOssman** [comment]
No, I'm afraid that is not something we support or is under development.

If someone feels like taking a stab at it then feel free to discuss it on our development mailing list.
