### ISSUE TITLE
Envi crashes VNC server, Version 1.8.0-17.el7

### ISSUE THREAD

**Issue by yuriTheComrade** [TigerVNC/tigervnc#900]
Hello there. 

Whenever we run envi on tigervnc-server 1.8.0-17.el7 right after it starts it crashes the VNC server. It's a strange bug that only occurs on this version, not on the prior ones. 

We have confirmed that on version 1.8.0-5 it works completely fine. We are using CentOS 7.

How to reproduce:
1. Run TigerVNC server.
2. Connect to it.
3. Run envi.
4. See it crash.

**Expected behavior**
It crashes. Pretty much.

**Screenshots**

Version that is not working
tigervnc-server.x86_64                 1.8.0-17.el7                    @base

#log
Tue Nov 12 13:25:45 2019
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888
xterm: cannot load font '-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1'
Failed to read: session.screen0.titlebar.left
Setting default value
Failed to read: session.screen0.titlebar.right
Setting default value
#envi launched
(EE)
(EE) Backtrace:
(EE) 0: /bin/Xvnc (xorg_backtrace+0x55) [0x5c31d5]
(EE) 1: /bin/Xvnc (0x400000+0x1c6b39) [0x5c6b39]
(EE) 2: /usr/lib64/libpthread.so.0 (0x7f9a86fdb000+0xf5f0) [0x7f9a86fea5f0]
(EE) 3: /bin/Xvnc (DamageUnregister+0x10) [0x4d8350]
(EE) 4: /bin/Xvnc (compSetParentPixmap+0x37) [0x51f787]
(EE) 5: /bin/Xvnc (compFreeClientWindow+0x231) [0x51fa21]
(EE) 6: /bin/Xvnc (0x400000+0x11a4b9) [0x51a4b9]
(EE) 7: /bin/Xvnc (0x400000+0x197952) [0x597952]
(EE) 8: /bin/Xvnc (FreeResource+0xde) [0x59852e]
(EE) 9: /bin/Xvnc (compUnredirectWindow+0xb1) [0x51ee21]
(EE) 10: /bin/Xvnc (0x400000+0x11b743) [0x51b743]
(EE) 11: /bin/Xvnc (compDestroyWindow+0x179) [0x51d219]
(EE) 12: /bin/Xvnc (0x400000+0xd85de) [0x4d85de]
(EE) 13: /bin/Xvnc (0x400000+0x89710) [0x489710]
(EE) 14: /bin/Xvnc (0x400000+0xd22be) [0x4d22be]
(EE) 15: /bin/Xvnc (0x400000+0x19c504) [0x59c504]
(EE) 16: /bin/Xvnc (DeleteWindow+0x76) [0x59f116]
(EE) 17: /bin/Xvnc (0x400000+0x197952) [0x597952]
(EE) 18: /bin/Xvnc (FreeResource+0xde) [0x59852e]
(EE) 19: /bin/Xvnc (ProcDestroyWindow+0x8f) [0x56dbef]
(EE) 20: /bin/Xvnc (Dispatch+0x31d) [0x573abd]
(EE) 21: /bin/Xvnc (dix_main+0x39a) [0x5779ba]
(EE) 22: /usr/lib64/libc.so.6 (__libc_start_main+0xf5) [0x7f9a84b18505]
(EE) 23: /bin/Xvnc (0x400000+0x5632e) [0x45632e]
(EE)
(EE) Segmentation fault at address 0x38
(EE)
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE)
Fluxbox: XIOError: lost connection to display.
xterm: fatal IO error 11 (Resource temporarily unavailable) or KillClient on X server ":1.0"
/home/vrana.p/.Xclients: line 1:  1677 Aborted                 /bin/fluxbox
Killing Xvnc process ID 1662
Xvnc process ID 1662 already killed

**Client (please complete the following information):**
 - OS: [Win 10]
 - VNC client: [TigerVNC]
 - VNC client version: [1.9.0]

**Server (please complete the following information):**
 - OS: [CentOS]
 - VNC server: [TigerVNC]
 - VNC server version: [1.8.0-17.el7]
 - Server downloaded from: [CentOS]
 - Server was started using: [vncserver]

**Additional context**
Tested on multiple devices with multiple computers, client doesn't matter as it seems to be the xserv that is crashing. 

Thank you for any answer in beforehand.

**Comment by CendioOssman** [comment]
I'm afraid this is a bug in Xorg, not in TigerVNC. Please see #897.

Please contact Red Hat so they can update their package, or try to do a custom build with the fix referenced in the other issue.
