### ISSUE TITLE
dwm[vnc[dwm]] Mod1 button

### ISSUE THREAD

**Issue by ichensky** [TigerVNC/tigervnc#901]
**Describe the bug**
It is not possible to use Mod1 button inside of VNC session.

**To Reproduce**
1. Start vncserver inside of DWM https://dwm.suckless.org/
```
$ vncserver
```
2. Connect to it: 
```
xtigervncviewer -SecutiryTypes VncAuth -passwd /home/john/.vnc/passwd :1
```
![dwm_vnc_dwm](https://user-images.githubusercontent.com/1774641/68748363-fc415f80-0604-11ea-865e-b4818018f36a.png)
3. Inside of VNC windows try to switch between DWM windows with Mod1+1..Mod+5...Mod+9 keys. 

4. Instead of switching to another window inside VNC[dwm] , windows would be switched at the host DWM. 

**Client **
 - OS: debian buster
 - VNC client: TigerVNC
 - VNC client version: 1.9.0
 - Client downloaded from: my Linux distribution

**Server **
 - OS: debian buster
 - VNC server: TigerVNC
 - VNC server version: 1.9.0
 - Server downloaded from: my Linux distribution
 - Server was started using:  `vncserver`

**Comment by CendioOssman** [comment]
Ehm... what is a Mod1 button? Or are you referring to the modifier list? Which button are you pressing?

Your description sounds like your local window manager is grabbing this key. You need to be in fullscreen with the system keys setting enable for TigerVNC to intercept things the local window manager normally uses. Have you tried that?

**Comment by ichensky** [comment]
`Mod1` it is `Alt` button. Tried to start xtigervncviewer with `-FullScreen`, it works, thank you. 
Is it possible to configure `xtigervncviewer`, started in normal mode, that it works like in the fullscreen?

**Comment by ichensky** [comment]
Found answer in the https://github.com/TigerVNC/tigervnc/issues/2 . Patch from that issue works perfect.
