### ISSUE TITLE
vncserver man page is missing options

### ISSUE THREAD

**Issue by durack1** [TigerVNC/tigervnc#902]
**Describe the bug**
vncserver man page is missing options

**To Reproduce**
look at the [vncserver](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver.man) man page and search for the options `-p`, `-s` and `AcceptSetDesktopSize` and these are not listed

**Expected behavior**
options `-p`, `-s` and `AcceptSetDesktopSize` are listed

**Screenshots**
Not applicable

**Client (please complete the following information):**
 - OS: MacOS 10.14.6
 - VNC client: RealVNC viewer
 - VNC client version:  6.19.923 (r41938) x64
 - Client downloaded from: RealVNC.com

**Server (please complete the following information):**
 - OS: RHEL7 (v7.7)
 - VNC server: Xvnc TigerVNC 1.8.0 - built Feb 28 2019 22:03:37
 - VNC server version: Xvnc TigerVNC 1.8.0 - built Feb 28 2019 22:03:37
 - Server downloaded from: RHEL7 built
 - Server was started using: `vncserver -name gat3 -geometry 3264x1836 -depth 24 :3 -p 20 -s 5 -AcceptSetDesktopSize=0`

**Additional context**
Above should cover it

**Comment by CendioOssman** [comment]
Hmm... I cannot find `-p` or `-s` in our code. What is it these flags do?

`-AcceptSetDesktopSize` is properly documented on the `Xvnc` page. We don't duplicate the documentation as `vncserver` is documented as accepting `Xvnc` flags as well.

**Comment by durack1** [comment]
@CendioOssman apologies, I am really not sure where I collected these flags from, I have just checked the RealVNC docs at [Xvnc](https://archive.realvnc.com/products/vnc/documentation/4.6/unix/man/Xvnc.html) and [vncserver](https://archive.realvnc.com/products/vnc/documentation/4.6/unix/man/vncserver.html) and these also don't appear, so not sure how I spuriously collected them.

Where is the TigerVNC Xvnc man page? I couldn't find this at https://github.com/TigerVNC/tigervnc/blob/master/unix/xvnc.man alongside the vncserver.man

**Comment by CendioOssman** [comment]
It's in the same directory as Xvnc itself:

https://github.com/TigerVNC/tigervnc/blob/master/unix/xserver/hw/vnc/Xvnc.man

The man pages are also available in HTML form on our home page. Generally easier to read than the raw troff code. :)
