### ISSUE TITLE
[Q] Resize image on server without desktop resolution change

### ISSUE THREAD

**Issue by Benik3** [TigerVNC/tigervnc#904]
Hello.

Simple question - is there any way how to resize the image on the server side, but without changing actual resolution of grabbed desktop?
Something like you can do on client side with java client.
The reason is that I need to show application for 1920x1080 resolution on smaller display, but the app is not responsive. And I'm not able to manipulate with the VNC client.
I tried something with xrandr, but it's lake changing the monitor resolution (so it brake the app).

Thank you!

**Comment by CendioOssman** [comment]
No, that is not something we have any plans for. Any such scaling should be a client feature IMO.

You could try playing around with the HiDPI settings of your desktop, but support for that on Linux is a bit spotty.
