### ISSUE TITLE
Cannot establish any listening sockets

### ISSUE THREAD

**Issue by lesar** [TigerVNC/tigervnc#905]
I'm new on vnc.  
I installed on Ubuntu 19.10  

```bash
$ sudo apt install ubuntu-gnome-desktop
$ sudo apt install tigervnc-standalone-server tigervnc-common tigervnc-xorg-extension tigervnc-viewer
```  

but if I try to start:  
`$ vncserver :1`  
I get:  
> vncserver: /usr/bin/Xtigervnc did not start up, please look into '/home/leonardo/.vnc/leon.uffalg.net:1.log' to determine the reason! -2

and  
`$ cat /home/leonardo/.vnc/leon.uffalg.net:1.log`

give me:  

>     _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
>     _XSERVTransMakeAllCOTSServerListeners: server already running
>     (EE)
>     Fatal server error:
>     (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)

 
I am on a terminal on ubuntu desktop and I like to install a vncserver and see if it is working so I have think to install, start vncserver and then try a vncviewer
`$ vim ./.vnc/xstartup`

```bash
    #!/bin/sh
    [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
    [ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
    vncconfig -iconic &
    dbus-launch --exit-with-session gnome-session &
```  
 
`$ chmod 700 xstartup`

where I'm doing a mistake?  
best regards,  
Leonardo

### Update  
I have do some check:  
I have an **/etc/vnc.conf**  
`$ grep -v '^#' /etc/vnc.conf`

> $fontPath = undef;
> $vncStartup = "/etc/X11/Xvnc-session";
> $geometry = "1900x1200";

The file **/etc/vnc/xstartup** is missing and all **/etc/vnc/** is missing  
**~/.Xresources** is missing too  
`$ grep -v '^#' /etc/tigervnc/ssleay.cnf`
```ini
RANDFILE                = /dev/urandom
[ req ]
default_bits            = 4096
default_keyfile         = privkey.pem
distinguished_name      = req_distinguished_name
prompt                  = no
policy			= policy_anything
req_extensions          = v3_req
x509_extensions         = v3_req
default_md = sha256
string_mask = utf8only
[ req_distinguished_name ]
commonName     = @HostName@
[ v3_req ]
basicConstraints=CA:FALSE
nsCertType = server
keyUsage = digitalSignature, keyEncipherment
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer
subjectAltName = @alt_names
[alt_names]
DNS.1          = @HostName@
DNS.2          = localhost
```
`$ sudo ls /etc/tigervnc/`

> ecparams.pem  
> ssleay.cnf

**Comment by CendioOssman** [comment]
The problem is that something is already using display `:1`. Please try a different display, e.g. `:5` and it should hopefully work better. :)

(you should also not have a `&` after `gnome-session` as that can mess up the `vncserver` behaviour)
