### ISSUE TITLE
New vulnerabilities in various VNC software

### ISSUE THREAD

**Issue by a1346054** [TigerVNC/tigervnc#907]
Kaspersky recently released a report showing many vulnerabilities in VNC software.

https://ics-cert.kaspersky.com/reports/2019/11/22/vnc-vulnerability-research/

The codebase for most of those software is shared, some of it even with TigerVNC. Is TigerVNC affected?

**Comment by samhed** [comment]
TigerVNC uses a different code base than the one that the report concerns. So we're not directly affected.

However, we have been made aware by Kaspersky about other vulnerabilities that DO affect TigerVNC. These vulnerabilities are not public yet, and fixes for these are in the works. Stay tuned.

**Comment by samhed** [comment]
Fixed in [TigerVNC 1.10.1](https://github.com/TigerVNC/tigervnc/releases/tag/v1.10.1).
