### ISSUE TITLE
copyrect encodings are no longer generated, severely impacting performance

### ISSUE THREAD

**Issue by jamespaley** [TigerVNC/tigervnc#908]
I never see copyrect encodings generated by the VNC server, despite requesting from multiple vnc client vendors. Is anyone else seeing this issue, or is this a bug? This has a significant impact on performance, particularly when using raw encoding (which I am forced to use for a specific application).

Example Session Metrics Logs showing no copyrect metrics:
 EncodeManager: Framebuffer updates: 38
 EncodeManager:   Tight:
 EncodeManager:     Solid: 295 rects, 3.15223 Mpixels
 EncodeManager:            4.60938 KiB (1:2672.13 ratio)
 EncodeManager:   ZRLE:
 EncodeManager:     Bitmap RLE: 72 rects, 49.314 kpixels
 EncodeManager:                 2.00781 KiB (1:96.3619 ratio)
 EncodeManager:     Indexed RLE: 151 rects, 330.939 kpixels
 EncodeManager:                  28.6738 KiB (1:45.1457 ratio)
 EncodeManager:     Full Colour: 93 rects, 503.516 kpixels
 EncodeManager:                  160.822 KiB (1:12.2368 ratio)
 EncodeManager:   Total: 611 rects, 4.036 Mpixels
 EncodeManager:          196.113 KiB (1:80.4269 ratio)
 ComparingUpdateTracker: 423.338 Mpixels in / 21.0852 Mpixels out
 ComparingUpdateTracker: (1:20.0775 ratio)

and for raw,copyrect and cursor requested encodings:
 EncodeManager: Framebuffer updates: 31
 EncodeManager:   Raw:
 EncodeManager:     Solid: 8 rects, 304.897 kpixels
 EncodeManager:            1.16318 MiB (1:1 ratio)
 EncodeManager:     Bitmap RLE: 2 rects, 86.016 kpixels
 EncodeManager:                 336.023 KiB (1:1 ratio)
 EncodeManager:     Indexed RLE: 70 rects, 2.7723 Mpixels
 EncodeManager:                  10.5763 MiB (1:1 ratio)
 EncodeManager:     Full Colour: 50 rects, 2.94185 Mpixels
 EncodeManager:                  11.2228 MiB (1:1 ratio)
 EncodeManager:   Total: 130 rects, 6.10506 Mpixels
 EncodeManager:          23.2904 MiB (1:1 ratio)

Tested with Windows tight vnc client and linux/Centos 7 tiger vnc client. I have also monitored the network traffic and copyrect encoding (1) is being requested, but never seen in the rectangles.

Server:
 - OS: Linux Centos 7
 - VNC server: Tiger VNC
 - VNC server version: tigervnc-server-1.8.0-17.el7.x86_64
 - Server downloaded from: Centos7
 - Server was started using: vncserver -SecurityTypes=None -depth 24  -geometry 1880x1000 -pixelformat RGB888
- Using standard gnome desktop

**Comment by samhed** [comment]
Which desktop environment are you using? I'm guessing the problem lies with the DE, that it isn't copying anything but redrawing everything constantly, GNOME for example does this.

I would recommend using Mate or XFCE with disabled compositing.

**Comment by jamespaley** [comment]
Disabling compositing did the trick - thanks.
