### ISSUE TITLE
full screen over multiple, but not all monitors

### ISSUE THREAD

**Issue by ercanal** [TigerVNC/tigervnc#91]
It will be great which monitors  can be used by vncviewer. 
Ex:
2 Monitors -> Vnc Viewer Full Screen
1 Monitor -> Other programs
##

**Comment by jrwagz** [comment]
I too would like to be able to do this.  I tried the following to see if it would work, and had no luck :(

- enable full screen over all monitors in TigerVNC client
- while in full screen over all monitors, go to the GNOME display settings, and disable one of the monitors

While this does affect the overall display, it doesn't do what you would expect, or anything useful.  I have 4 monitors arranged horizontally, and when I disabled one of them I ended up getting 3 "monitors" centered across the 4 monitors, with empty black space on the far left and right, and the monitor transitions occurred in the middle of the actual monitors.

**Comment by dezza** [comment]
How do you go fullscreen over a single monitor?

When I try "vncviewer host:displaynum" I think it interprets it as a port.

**Comment by CendioOssman** [comment]
> How do you go fullscreen over a single monitor?

It's in the viewer options dialog. It will go fullscreen over the same monitor the window is currently in.

> When I try "vncviewer host:displaynum" I think it interprets it as a port. It won't work.

`displaynum` here means display in the X11 sense of the word. It does not have anything to do with monitors.

**Comment by luisgutz** [comment]
Would be great to do this.
I have the same configuration as ercanal: 3 monitors, and I would like to use 1 for windows/email.

**Comment by fbordeu** [comment]
Same case for me, I have 3 screens (I'm in windows connectig to a remot linux). I will line 1 monitor for windows and 2 monitors for tigervnc in fuul screen mode.

**Comment by wickedviking** [comment]
I can tell you that the first VNC client to support this feature will become the go to VNC client for windows users. I"ve been wanting this for years. I don't want to mess with ugly geometry hacks because I have different resolutions in the office than I do at home. I just want to open my VNC client, tell it which monitors to use, and connect to the remote system...

3 monitors in both home and office, home is 4k, office is 1080p. This all or one thing is for the birds...

**Comment by microwaveguy** [comment]
I've been following this issue for a while. Until a recent search and found the following link:
https://superuser.com/questions/827969/how-to-configure-realvnc-viewer-to-display-on-only-specific-monitors-instead-of
I've tested today, it worked pretty well with my 3-monitor setting. Still in 30-day free trial mode, not sure what will happen in free mode, though. But could worth a purchase.

**Comment by xMAC94x** [comment]
I am also interested in using TigerVNC with 2 of 3 monitors.
So i don't need to minimize the VNC session when checking mails or similar on the windows pc.

**Comment by ercanal** [comment]
There is a solution for this  and there is a pull request #427. It works good for me but for weird monitor geometries may create problems.

**Comment by dsbecker** [comment]
+1

**Comment by grantlittle** [comment]
+1

**Comment by szycha76** [comment]
As 3+ displays systems become more and more common, this is becoming more need that fancy demand.  Please re-think implementing.

**Comment by fneddy** [comment]
+1

**Comment by sydneyjd** [comment]
+1

**Comment by ybitso** [comment]
+1

**Comment by CodyBriscoe** [comment]
+1

**Comment by Akito13** [comment]
Come on, it's been 5 years.

**Comment by joris13** [comment]
+1

**Comment by Akito13** [comment]
Shouldn't this issue be a first-class citizen by now? Like come on, this is on fire and it's like nobody cares.. 
If this would be written in a modern language I would also be contributing. C-based languages below Java are a no-go for me, though.

**Comment by benrichards86** [comment]
I'm looking for the same feature. I have the same configuration as the others earlier in this thread.

I see the pull request is still open.

**Comment by samhed** [comment]
> I see the pull request is still open.

What pull request?

Code contributions are welcome.

**Comment by a1exh** [comment]
I too have this problem, 3 screens and I only want to use 2 for full screen VNC. It is a great shame that pull request #427 was never considered for merging (and is now closed due to inactivity) in as it appears to solve this problem.

**Comment by littleBanshee** [comment]
kali wsl2 with kex(tigervnc),same issue

**Comment by rayxu123** [comment]
+1

I, too, am a 3-screener but would like to use only two out of the three for VNC.  I've been wanting this for the past few years but I want it sooo badly now (work-from-home) that I am willing to post bounty on this.

**Comment by a1exh** [comment]
It depends how much the master branch has moved on since pull request #427 In theory it should be possible to take that branch merge up, fix conflicts, build, test and perform a new pull request.

**Comment by microwaveguy** [comment]
I've found the solution couple years ago and posted here. This is not an Ad to sell a product though.
I found this software: Display Fusion Pro, which is able to create shortcut to do the following actions:
1. full-screen across all monitors --> move your App's top left corner to wherever you want.

I'm currently using a laptop with resolution: 1920x1080 and two monitors with 1920x1200 resolution. With Display Fusion Pro, I was able to use VNC only across the two monitors (with full-screen, rather than maximize), and use my laptop screen for other windows stuff (email, web-browsing).

**Comment by a1exh** [comment]
DisplayFusion Pro works for me here too.  But you need to pay the license fee for the feature to run VNC full screen over two monitors. It is not part of the free version.

[https://superuser.com/questions/827969/how-to-configure-realvnc-viewer-to-display-on-only-specific-monitors-instead-of](url)

**Comment by le-petit-prince** [comment]
> DisplayFusion Pro works for me here too. But you need to pay the license fee for the feature to run VNC full screen over two monitors. It is not part of the free version.
> 
> [https://superuser.com/questions/827969/how-to-configure-realvnc-viewer-to-display-on-only-specific-monitors-instead-of](url)

an open-source command-line tool called [cmdow](https://ritchielawrence.github.io/cmdow/) can play the same role as DisplayFusion Pro here.

**Comment by a1exh** [comment]
> I found an open-source command-line tool called cmdow that can play the same role as DisplayFusion Pro

Cool. It's just such a shame that the code to fix this in TigerVNC is sitting in pull request #427 for years and isn't being considered to be merged back to master.

**Comment by benrichards86** [comment]
Agrees. This is the most frustrating thing about it.

Ben

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by theAkito** [comment]
This is exactly why we are forced to use proprietary software.

**Comment by microwaveguy** [comment]
I think the solution in #427 is for TigerVNC only. But the solution DisplayFusion provided can be used on any windos/application.
It's the best $20 I spent on software, used it for years now, never had a problem on any of my work laptop + docking + multi-monitor settings.
One thing is that if you use DisplayFusion to "full-screen" over two monitors, the VNCviewer (what I use for work) is recognizing it as one window, so when you want to maximize a window in Linux session, simply "maximize" it won't work, will need to set up some bindkeys in Linux to move and size windows.

**Comment by hugolundin** [comment]
Hi everyone! I have been working on this feature for a couple of weeks and am currently finishing up the implementation. You are welcome to try it out ([hugolundin/tigervnc/selected_monitors](https://github.com/hugolundin/tigervnc/tree/selected_monitors)). If you find any bugs, please report them in the pull request (#1282). Have a nice day! :)

**Comment by CendioOssman** [comment]
#1282 has now been merged so this feature is finally available on `master`.
