### ISSUE TITLE
Not secure message is displayed when VNC client connects to local port

### ISSUE THREAD

**Issue by Brett-Diamond** [TigerVNC/tigervnc#913]
When the vncviewer connects to a local port, the message "This connection is not secure".  Either the vncserver is on the same machine, or the connection is tunneled through ssh; in both cases, the connection is secure.

I suggest moving the warning message to the vncserver, displaying the message when there is no encryption and the server is not set to localhost only.

All client platforms, all server platforms.

**Comment by CendioOssman** [comment]
I'm afraid we've chosen to err on the side of caution. If we cannot verify the other end (using certificates), then we consider it insecure. This is similar to how browsers behave, which do not consider localhost or proxied connections automatically secure.

**Comment by gitcnd** [comment]
"Not secure" needs to explain WHY it is not secure.  Otherwise, the "err on the side of caution" is not accurate - you are forcing users to become accustomed to ignoring warning messages and not giving them any information to determine when a real attack is taking place.

**Comment by georgehank** [comment]
So, just to check that I got this right, the viewer says "not secure" when it actually is secure, it's just not "secure enough"?   Yes, what gitcnd says, error messages need to give enough info to know *what* is wrong and not just "something broke".
