### ISSUE TITLE
question: how to enable touch events with TigerVNC?

### ISSUE THREAD

**Issue by monperrus** [TigerVNC/tigervnc#916]
My application only supports X touch events.

How to configure the server and the client such that mouse events on the client are translated to touch events on the server?

Thanks!

**Comment by samhed** [comment]
You can't send touch events over VNC, it's not even in the protocol yet. You'd need some sort of emulation on the server. I did some looking around on google, but I couldn't find anything.

This use case is probably not that common compared to the opposite (touch screen but app only works with mouse). What kind of application is it?

**Comment by monperrus** [comment]
Thanks for your answer.

> What kind of application is it?

It's an Android app running in [anbox](https://anbox.io)

Do you know other remote protocols that would support touch events?

**Comment by CendioOssman** [comment]
If it's an Android emulator then I'd say it's really up to it to emulate the touch events. Most machines will not have a touch screen, so it isn't really a VNC specific issue.

I'm afraid I don't know which protocols support touch events. Much less if they support translating mouse events to touch.

I would suggest filing and issue with anbox requesting support for this directly in the application.

**Comment by monperrus** [comment]
ok thanks.
