### ISSUE TITLE
Please create tutorial how to set up TigerVNC on Centos 7

### ISSUE THREAD

**Issue by MariuszKolo** [TigerVNC/tigervnc#917]
I can find any step by step  documentation how to :
tutorial how to set up TigerVNC on Centos 7
I am new to linux and centos and I don't know how to do it .
There some youtube tutorials but some of theme are old or hard to fallow.
I will be very grateful for help.
Cheers
Mariusz

**Comment by CendioOssman** [comment]
CentOS 7 ships with TigerVNC. Have you checked their documentation, or Red Hat's?

**Comment by CendioOssman** [comment]
No response. Closing.
