### ISSUE TITLE
mouse pointer in multiscreen config

### ISSUE THREAD

**Issue by voipscout** [TigerVNC/tigervnc#92]
With a command line like this:
Xvnc :20 -ac -br +bs +iglx +render -screen 0 1920x1080x24 -screen 1 1920x1080x24 -screen 2 800x600x24 -SecurityTypes=None -query localhost

after connecting to any one of the screens with vncviewer, it's impossible to move the pointer between those.

any workaround / help with this is greatly appreciated!

**Comment by CendioOssman** [comment]
No feedback so closing this issue.

**Comment by juaningan** [comment]
Hi, I'm running TigerVNC (both stable and beta version) with:
/usr/bin/Xvnc :0 -screen 0 1280x1024x24 -screen 1 1024x768x24 -screen 2 1024x768x24 

And I'm having this problem also. Mouse trapped in first screen.
My use case is a legacy multi monitor application that is hardcoded to :0.0, :0.1 and :0.2.

Running Xorg with dummy driver and x11vnc over it is working correctly.

Thanks in advance.
