### ISSUE TITLE
Linux binaries (1.10.0, etc)?

### ISSUE THREAD

**Issue by imperative** [TigerVNC/tigervnc#920]
The official webpage says that the latest binaries should be downloaded from Bintray, the link is "https://bintray.com/tigervnc/stable/tigervnc/1.10.0", but it does not list any Linux binaries, only the java ones, a .dmg file assuming for MacOS and .exe files. Where are the linux ones?

**Comment by samhed** [comment]
The files ending with ".tar.gz" are for Linux.

**Comment by imperative** [comment]
We all know that, but there were no .tar.gz files on that link. Now they are added, thank you for uploading them!

**Comment by CendioOssman** [comment]
For future reference, the files were available under the "Files" tab. The first page shows the files that been manually selected as "important", and the tar.gz packages had not been marked as such.
