### ISSUE TITLE
Xvnc build error - Xserver header file not found

### ISSUE THREAD

**Issue by MaxLeiter** [TigerVNC/tigervnc#924]
I'm on a weird OS so this could very well be my fault.
Occurs on tigervnc-1.7.1.

`make` ran in the unix/server folder fine. However, make in `hw/vnc` fails for some reason. Any help appreciated. 
```
tigervnc-1.7.1/unix/xserver/hw/vnc root# make
  CC       Xvnc-xvnc.o
xvnc.c:53:10: fatal error: 'mibstore.h' file not found
#include "mibstore.h"
         ^~~~~~~~~~~~
```

**Comment by CendioOssman** [comment]
I'm afraid building in a subdirectory is not something that is generally expected to work. Please run `make` in the `xserver` directory and nowhere else.
