### ISSUE TITLE
Version of release 10.0.1 reported as 10.0.0 (Ubuntu based Docker image)

### ISSUE THREAD

**Issue by accetto** [TigerVNC/tigervnc#925]
**Description**

I maintain a set of Docker images based on Ubuntu 18.04 LTS that use TigerVNC (e.g. [accetto/xubuntu-vnc](https://hub.docker.com/r/accetto/xubuntu-vnc)).

The [Dockerfile](https://hub.docker.com/r/accetto/xubuntu-vnc/dockerfile) installs a specific TigerVNC version, e.g:

`RUN wget -qO- https://dl.bintray.com/tigervnc/stable/tigervnc-1.10.1.x86_64.tar.gz | tar xz --strip 1 -C /`

However, after rebuilding the image including the TigerVNC version **1.10.1** (see the line above), the reported version is still **1.10.0**.

I check the TigerVNC version using the following command:

`vncserver -version`

What could be wrong? The reported version matched the installed version till now.

**To Reproduce**

1. Build a Docker image using the [Dockerfile](https://hub.docker.com/r/accetto/xubuntu-vnc/dockerfile)

2. Create a container from the image, e.g.

`docker run -it -p 25901:5901 --rm accetto/xubuntu-vnc`

3. Connect to the container using a VNC viewer (e.g. TigerVNV Viewer), e.g.

`localhost:25901`

4. In the container, open a terminal and type the following command:

`vncserver -version`

5. The reported **incorrect** version will be **1.10.0**:

```
Could not start Xvnc.

Xvnc TigerVNC 1.10.0 - built Dec 20 2019 07:12:07
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12001000, The X.Org Foundation
```

*Remark*: Notice that the built date seems to be the date of the version **1.10.1**.

**Expected behavior**

The correct version reported should be **1.10.1**.

**Screenshots**

None.

**Client (please complete the following information):**

 Not applicable (any).

**Server (please complete the following information):**

 - OS: Docker Container based on the current `latest` [Ubuntu](https://hub.docker.com/_/ubuntu) image 
 - VNC server: TigerVNC
 - VNC server version: 1.10.1
 - Server downloaded from: [TigerVNC distribution](https://dl.bintray.com/tigervnc/stable/tigervnc-1.10.1.x86_64.tar.gz)
 - Server was started using: `vncserver`

**Additional context**

The reported version has been correct till the version **1.10.0**.

**Comment by CendioOssman** [comment]
Ooops. Sorry about that. It seems I missed Xvnc when changing the version numbers.

Unfortunately not much to do know as the release is already tagged and out. If there is a 1.10.2 we'll sort it out then. Until then you can manually patch `xvnc.c` if you need the correct version number in the binaries.

**Comment by accetto** [comment]
No big deal, thank you for the answer. I'll mention it in the changelog and we'll wait for the next release.
