### ISSUE TITLE
x0vncserver and server side cursor

### ISSUE THREAD

**Issue by shelldevi** [TigerVNC/tigervnc#932]
Hello. I can not find any docs or help about my problem and will try to describe my problem here.
I want to use x0vncserver from tigervnc package, all work just fine, but I need to see a remote cursor moving, I have a locally connected to server keyboard with touchpad which I want to use for inputs in "main" X session. Device works fine, but with x0vncserver I can not see a remote cursor position at all. It works with x11vnc, but it really buggy and sloow.

Can anyone told me is possible to see remote cursor in VNC session?

**Comment by CendioOssman** [comment]
Yes, this has been supported since TigerVNC 1.9.0, so I assume you are running something older (please try to use the issue form in the future). Please upgrade and it should work for you.
