### ISSUE TITLE
lets bring XKB extension support to this VNC server

### ISSUE THREAD

**Issue by JanuszChmiel** [TigerVNC/tigervnc#934]
Dear specialists,
I have asked this question to many developers, but nobody have answered on it.
Do you think, that it would be possible to add XKB support to yours VNC server, so client app, which will support hardware keyboard would be even used by vvisually impaired user who uses hardware keyboard?
My goal is to use GTk apps on Android by using Proot and Debian. Because Debian have been made so DBUs work perfectly even in so complex situation like when Orca screen reader is being used with various GTk apps.
If XKB extension is not available, how complex would be to incorporate it?
If is it not possible to implement it, would you tell Me why?

I hope, that there are experts hare who will tell Me this secret. Thank you very very much for yours answer on my question.
With warmest regards.
Janusz Chmiel

**Comment by CendioOssman** [comment]
TigerVNC has had XKB support for many years. But you mention screen readers, so it sounds like you are asking for something else.

Please describe what you are trying to do in more detail.

**Comment by JanuszChmiel** [comment]
Ok.
My goal is to have accessible Android VNC client, which will allow Me to use
keyboard. Fortunately, I have found one. MochaVNC. Finding Android VNC
wiever, which will allow user with no sight at all to have full keyboard
access is not verz easy. But I must solve more complex task.
Start tigervnc with special command line options or configuration, so Marco
window manager will be able to detect its XKB support. Really, when I run
tigervnc, app run correctly, but all window managers, including openbox and
Marco display, XKB extension not available.

x11vnc run partially, but XKB extension is correctly detected.

Do I have to use some special configuration changes so window manager will
detect XKB extension support of Tiger vnc?
What I have allready done?
I have been able to run many GTK apps including mate-control center, caja,
pluma, gedit, synaptic package manager and others. But I have been forced to
use Xserver XSDL.
The problem is that this app uses routine, which currently do not support
all keys on hardware keyboard while using Huavei 10 mate lite. Newest
version have totally lost its accessible GUI, so I can not remap keys to
solve this. And using old release from 2016 is not good idea.
So i would like to try VNC instead.
I Am very sorry, that I AM intruding you with so strange idea like running
Linux apps on Android. But thanks to Termux and Proot module, it is really
possible. And because some kind C and C++ programmers have even allow users
to run without using shmemget kernel sys call, it is technically possible.
Sure. LXDE desktop will never detect hod keys, Mate-session will crash
because of some memory allocation issues and thanks to gnome-keyring-daemon,
which requires insufficient process capabilities, insecure memory maid be
used.
So for now, it is possible to run even whole LXDE, but only by sighted
users. Mate can not be run, even some professionals around Manjaro community
declares, that it is possible, but I do not know how. Perhaps it is possible
to run Mate desktop even on non rooted Android devices. 

For now, I will be satisfied enough if I will be able to run Orca with some
GTK apps.
I must always firstly run window manager for example
marco &
orca &
followed by some GTK app. It is even possible to run multiple apps multiple
windows. But I would like to achievee it with tigervnc and its XKB
extension.

**Comment by CendioOssman** [comment]
XKB is always active so there isn't anything special you need to do.

I'm afraid I still don't understand quite what you are doing. Could you describe in detail how to set things up so we can test here?

Please describe what you are seeing vs what you'd like to see.

**Comment by JanuszChmiel** [comment]
You can close this issue. I have allready found functioning solution which
consists of two apps.
X11vnc and xvfb. I can use Orca screen reader with many various VNC client
apps for Android. Because x11vnc package also support XKB extension.
