### ISSUE TITLE
Conncting to VNC server shows "Access is denied" in log

### ISSUE THREAD

**Issue by klui2k1** [TigerVNC/tigervnc#935]
**Describe the bug**
Winvnc4 1.10.1 x64 is running as a service but when I try to connect using 1.10.1 x64 client, no window is shown. Telneting to the port works.

If I use the 1.9.0 server running as a service (client still 1.10.1 x64) it works. But if I use launch Winvnc4 1.9.0 server 1.9.0 as Administrator with "-Log *:file:100" I can't connect either and the logs show basically the same error.

My Windows firewall is on. I only use the loopback interface and rely on an SSH tunnel.

**To Reproduce**
Install 1.10.1 x64, register service enable service
ssh into Windows server with port forwarding
open VNCviewer 1.10.1 x64 and connect to forwarded port
(When I tried it with 1.9.0 x64, I just reinstalled over 1.10.1 x64)

**Expected behavior**
Console windows should be displayed

**Screenshots**
none.

**Client (please complete the following information):**
 - OS: Windows 10 1909 x64
 - VNC client: TigerVNC
 - VNC client version: 1.10.1
 - Client downloaded from: TigerVNC Github

**Server (please complete the following information):**
 - OS: Windows 10 1909 x64
 - VNC server: TigerVNC
 - VNC server version: 1.10.1 (1.9.0 works running as a service, but not running as Admin w/ -Log switch)
 - Server downloaded from: TigerVNC Github
 - Server was started using: system service, and running from cmd prompt

**Additional context**
Log files here. I attempted to change the service to produce the log file by filling in the parameters text box but no log was created in c:\temp, so manually running winvnc4.exe created the log files.

[TigerVNC 1.10.1 error.txt](https://github.com/TigerVNC/tigervnc/files/4021174/TigerVNC.1.10.1.error.txt)
[TigerVNC 1.9.0 error.txt](https://github.com/TigerVNC/tigervnc/files/4021176/TigerVNC.1.9.0.error.txt)

**Comment by JeffReeves** [comment]
I'm also experiencing the same issue as described with version 1.10.1 x64 on two different machines using Windows 10 Pro 1909 x64.

**Comment by CendioOssman** [comment]
@klui2k1, does 1.10.0 also work fine for you?

Could you guys also test the current nightly build? You'll find it on our homepage.

**Comment by klui2k1** [comment]
Just wanted to state that 1.10.0 also works for me. I'll try the nightly.

**Comment by antenore** [comment]
The same issue using another client based on libvnc (remmina), connecting to 1.10.0 works.

Reported by one of our users through IRC, so I'm not sure if I'll get other feedback from him/her.

**Comment by CendioOssman** [comment]
Thanks for testing. It does suggest there is something with the security fixes that is causing this.

If some developer has time to debug this then that would be helpful.

**Comment by bphinz** [comment]
Can you please try the nightly build published this morning?  I fixed a build issue that was causing the 1.10.1 windows server to crash.  Those logs look different than what I've seen however.

**Comment by klui2k1** [comment]
Thanks @bphinz. For my use case 1.10.80 built on 2020-01-14 **works**!
I just want to reiterate that I don't have any encryption enabled as I rely on an SSH tunnel using a loopback connection.

I strongly encourage @JeffReeves and @antenore try the latest.

**Comment by CendioOssman** [comment]
It's very odd you got an access denied because of the build issue, but as long as it works. :)
