### ISSUE TITLE
VNC Server connection fail 10054 (vnc server crashes in user-mode, not service mode)

### ISSUE THREAD

**Issue by mrbbs** [TigerVNC/tigervnc#936]
I just downloaded the latest nightly Windows build from 6/1/2020 after also having reported bug: https://github.com/TigerVNC/tigervnc/commit/73014910f56278a91e796ad8eed620196e289f47

Client and server version: 

tigervnc-1.10.80.exe | 11832872 | 2020-01-06 22:46:38 | 134226bf551ee2ce256d806138796ae7
tigervnc64-1.10.80.exe | 12859192 | 2020-01-06 22:55:24 | 702617ab17f2fef4a98657d01dc7e1d0

This is a clean install on a new system. I've set "no enryption" used and a fixed vnc password.
I've configured the same configuration on both user-mode and service mode.

The PC is running Windows 10 v1909 fully patched without firewall. The PC has a manual entered fixed IP address. (as found on the FAQ)

When I connect from another client when the VNC server is running in user-mode, the VNC server crashes and I'm getting error 10054.
When I connect from another client when the VNC server is running as a service, the VNC server keeps running however I'm getting error 10054 as well.
The same behaviour is also true when trying to connect via VNCViewer to the local VNC Server.

Please advise.

Kind regards,
Kevin

**Expected behavior**
Having a working connection with the vnc server

**Comment by mrbbs** [comment]
I have the same issue with the build from 10 January:

tigervnc64-1.10.80.exe | 12856800 | 2020-01-10 03:49:12 | 57bfff521900ebbd200397722de8ea29
-- | -- | -- | --

Message connected refused 10054 on the viewer for both standalone/service connections.
Running VNC server standalone crashes. If you run VNC Server as a service it keeps running.

Any suggestions?

Best regards,
Kevin

**Comment by bphinz** [comment]
It appears to be a build/linker issue.  Working on a fix now

**Comment by mrbbs** [comment]
Thank you!

**Comment by bphinz** [comment]
I just published a new nightly build, can you please try that and see if it fixes the issue?

**Comment by mrbbs** [comment]
Hi bphinz,

I just downloaded the nightly software and it works now!

Thank you so much.
Kevin
