### ISSUE TITLE
SMsgWriter::writeFramebufferUpdateEnd: nRects out of sync

### ISSUE THREAD

**Issue by smekkley** [TigerVNC/tigervnc#937]
When libvnc.so is used with Xorg to expose a physical display directly, and use MacOSX native screen sharing program to do VNC, I randomly get the following error which resemble https://github.com/TigerVNC/tigervnc/issues/914  with the latest tigervnc (1.10.1).

I especially get this error, when I maximize and move windows. Xorg server version is 1.20.6.
Also IBUS input is very slow. Normal alphabet typing is fast, but as soon as I use any input method like ibus-anthy, ibus-mozc, keyboard input gets also dropped.

```
/usr/lib/gdm-x-session[563]: Wed Jan  8 23:19:09 2020
/usr/lib/gdm-x-session[563]:  VNCSConnST:  closing 192.168.122.210::56881:
/usr/lib/gdm-x-session[563]:               SMsgWriter::writeFramebufferUpdateEnd: nRects out of sync
/usr/lib/gdm-x-session[563]:  EncodeManager: Framebuffer updates: 13
/usr/lib/gdm-x-session[563]:  EncodeManager:   ZRLE:
/usr/lib/gdm-x-session[563]:  EncodeManager:     Solid: 2 rects, 10.542 kpixels
/usr/lib/gdm-x-session[563]:  EncodeManager:            50 B (1:843.84 ratio)
/usr/lib/gdm-x-session[563]:  EncodeManager:     Bitmap RLE: 1 rects, 65.536 kpixels
/usr/lib/gdm-x-session[563]:  EncodeManager:                 104 B (1:2520.73 ratio)
/usr/lib/gdm-x-session[563]:  EncodeManager:     Indexed RLE: 47 rects, 2.34061 Mpixels
/usr/lib/gdm-x-session[563]:  EncodeManager:                  26.5312 KiB (1:344.634 ratio)
/usr/lib/gdm-x-session[563]:  EncodeManager:     Full Colour: 81 rects, 4.48083 Mpixels
/usr/lib/gdm-x-session[563]:  EncodeManager:                  1.40911 MiB (1:12.131 ratio)
/usr/lib/gdm-x-session[563]:  EncodeManager:   Total: 131 rects, 6.89752 Mpixels
/usr/lib/gdm-x-session[563]:  EncodeManager:          1.43517 MiB (1:18.3347 ratio)
/usr/lib/gdm-x-session[563]:  TcpSocket:   unable to get peer name for socket
/usr/lib/gdm-x-session[563]:  Connections: closed: ::0
/usr/lib/gdm-x-session[563]:  ComparingUpdateTracker: 0 pixels in / 0 pixels out
/usr/lib/gdm-x-session[563]:  ComparingUpdateTracker: (1:-nan ratio)
/usr/lib/gdm-x-session[563]:  Connections: accepted: 192.168.122.210::56885
/usr/lib/gdm-x-session[563]:  SConnection: Client needs protocol version 3.3
/usr/lib/gdm-x-session[563]:  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
/usr/lib/gdm-x-session[563]:  VNCSConnST:  Client pixel format depth 32 (32bpp) little-endian rgb max
/usr/lib/gdm-x-session[563]:               255,255,255 shift 16,8,0
```

10-libvnc.conf
```
Section "Module"
Load "vnc"
EndSection

Section "Screen"
Identifier "Screen0"
Option "UserPasswdVerifier" "VncAuth"
Option "PasswordFile" "/home/user1/.vnc/passwd"
EndSection

```

**Comment by smekkley** [comment]
Supressing exception in `void SMsgWriter::writeFramebufferUpdateEnd()` in `common/rfb/SMsgWriter.cxx` solves the issue. But I'm not familiar with VNC, so I have no idea what the effect is. But at least in my case, it's a definitely better solution because it won't force close the session and keeps working no matter what. Even if something really bad happens, it's up to me to disconnect and connect again.

**Comment by smekkley** [comment]
I'm still digging into it. But it'd be great if somebody gives me a hint. It also solved the problem the issue with ibus(input method for foreign language).

**Comment by CendioOssman** [comment]
Try using `gdb` to get a backtrace when that exception is thrown. It should give us some clue as to what is causing this.

**Comment by samhed** [comment]
No response.

**Comment by Phyyl** [comment]
Any news on that? On my part, connecting with UltraVNC client, the issue doesn't happen, but with a FreeVNC, resizing a window (maximize) forces the server to close the connection with "nRects out of sync" error.

**Comment by smekkley** [comment]
I moved to Nomachine, which works fine without internet.  
I need to set up a VM for this, I'll update here when I run it under gdb.
