### ISSUE TITLE
image library mismatch when connecting to xorg over freebsd

### ISSUE THREAD

**Issue by puddingepoch** [TigerVNC/tigervnc#939]
when using tigervnc viewer 1.10.80 on windows,  i can connect to x11vnc on my freebsd machine fine UNTIL i start using a window manager and such

for example, flux-box and xfe, when i add those, i suddenly cannot connect via VNC, citing a image library mismatch

seriously this vnc has so many problems...

**Comment by samhed** [comment]
What does the viewer log file say? https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs#client-1

Have you tested a different VNC viewer?

**Comment by bphinz** [comment]
I found a similar problem in the Windows server and traced it to a build error.  The linker was linking against libjpeg while using the headers from libjpeg-turbo.  Can you please try the viewer from the latest nightly build?

**Comment by samhed** [comment]
No response.
