### ISSUE TITLE
TigerVNC disconnects with message "End of stream"

### ISSUE THREAD

**Issue by jyhpsycho** [TigerVNC/tigervnc#946]
**Describe the bug**
TigerVNC Server disconnects the connection with message: "CConn:       End of stream".

**To Reproduce**
1. Install TigerVNC 1.10.1 on Windows Server.
2. Do basic settings using "Configure VNC Service" (I changed just "Session encryption" to "Anonymous TLS" only, and "Authentication" to "Standard VNC" on Security Tab).
3. Run "Start VNC Service".
4. Run vncviewer from linux client console.
5. Set connect address to Windows Server.
6. Click connect button, type the password and see the error.

**Expected behavior**
VNC Client should work as expected(showing desktop, keyboard and mouse input, etc.)

**Screenshots**
![스크린샷_2020-01-23_02-52-31](https://user-images.githubusercontent.com/4373184/72919824-7cb1d880-3d8b-11ea-888a-a81a70ec81fe.png)

**Client (please complete the following information):**
 - OS: openSUSE 15.1
 - VNC client: TigerVNC Viewer
 - VNC client version: 1.9.0
 - Client downloaded from: on Distribution package

**Server (please complete the following information):**
 - OS: Windows Server 2019
 - VNC server: TigerVNC Service mode
 - VNC server version: 1.10.1
 - Server downloaded from: official binary distribution site(bintray)
 - Server was started using: Service start

**Additional context**
 - I just try to downgrade the VNC Server to 1.9.0, and it works as expected. I think that it's 1.10+ regression.
 - The server and client version mismatches, but it should not affect to this bug because these are using same protocol version(3.8).

**Comment by bphinz** [comment]
This is a known issue, please try the latest nightly build (can be found
from the link off our homepage).

**Comment by jyhpsycho** [comment]
> This is a known issue, please try the latest nightly build (can be found from the link off our homepage).

You means the prebuilt packages at [here](http://tigervnc.bphinz.com/nightly/)? I'll try this as soon as possible.

**Comment by bphinz** [comment]
Yes

**Comment by jyhpsycho** [comment]
Good, It seems to work. Thanks for suggestion, as I don't find out the [issue](https://github.com/TigerVNC/tigervnc/issues/930) is already reported.
