### ISSUE TITLE
tigervncserver: LibGL segfaults on Ubuntu 14.04 (dri driver issue)

### ISSUE THREAD

**Issue by favila** [TigerVNC/tigervnc#95]
From within an xvnc server, anything that depends on opengl will fail with a segfault on ubuntu 14.04.

Example output:
```
$ LIBGL_DEBUG=verbose glxinfo
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
libGL: driver does not expose __driDriverGetExtensions_swrast(): /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: undefined symbol: __driDriverGetExtensions_swrast
libGL: Can't open configuration file /home/favila/.drirc: No such file or directory.
libGL: Can't open configuration file /home/favila/.drirc: No such file or directory.
libGL error: failed to load driver: swrast
Segmentation fault (core dumped)
```

This occurs with the following prebuilt binaries:

* http://tigervnc.sourceforge.net/tiger.nightly/ubuntu-14.04LTS/amd64/tigervncserver_1.4.80+20141210git74cff2e4-3ubuntu1_amd64.deb
* https://bintray.com/artifact/download/tigervnc/stable/ubuntu-14.04LTS/amd64/tigervncserver_1.4.1-3ubuntu1_amd64.deb

**Comment by CendioOssman** [comment]
I don't see how this is a problem we've caused in any way. We're just an X server. glxinfo should be using libGL and DRI drivers from the system. So it looks like your swrast driver is broken in some way.
