### ISSUE TITLE
[ TigerVNC Server ] Turn off shared clipboard

### ISSUE THREAD

**Issue by abdennour** [TigerVNC/tigervnc#950]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I cannot control copying/paste from the remote machine (which is running TigerVNC server) to the local machine.

**Describe the solution you'd like**
I would like to give an option that turns off the shared clipboard between the remote machine and the local machine.

**Additional context**
TigerVNC is integrated with Guacamole as HTML frontend.

**Comment by CendioOssman** [comment]
This is controlled by the `-AcceptCutText` and `-SendCutText` settings. Please see the [Xvnc man page](https://tigervnc.org/doc/Xvnc.html) for details.

**Comment by abdullahyildiz** [comment]
I use CentOS Linux (release 7.7.1908 (Core)) and installed Xvnc TigerVNC 1.8.0. I need to disable clipboard functionality for every client, so I added `-noclipboard` option to each vncserver startup file (e.g., /etc/systemd/system/vncserver@:13.service) of each user:

```
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
ExecStart=/usr/sbin/runuser -l ekarabulut -c "/usr/bin/vncserver %i -geometry 1920x1200 -noclipboard"
PIDFile=/home/ekarabulut/.vnc/%H%i.pid
ExecStop=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
```

However, I can still copy and paste between host and the remote machine. How can I fix this?

**Comment by abdullahyildiz** [comment]
Sorry, I noticed that I misunderstood the purpose of `-noclipboard` option.

I also need to set `-AcceptCutText` and `-SendCutText` parameters:

```
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
ExecStart=/usr/sbin/runuser -l USER -c "/usr/bin/vncserver %i -geometry 1920x1200 -noclipboard -AcceptCutText=0 -SendCutText=0"
PIDFile=/home/USER/.vnc/%H%i.pid
ExecStop=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
```
