### ISSUE TITLE
vncserver not reading config

### ISSUE THREAD

**Issue by Ult1Gamer** [TigerVNC/tigervnc#952]
I am trying to control a stock Ubuntu 19.10 computer, but the config file seems to not be read. Client is Windows 10 1909 with TigerVNC 1.10.1 viewer. Server is described below
## Here is how I installed tigervnc:
sudo apt install tigervnc-standalone-server -y
vncserver [enter prompts]
sudo ufw allow from 192.168.1.0/24 to any port 5901
vncserver -list
vncserver -kill :*
nano ~/.vnc/xstartup

#!/bin/sh 
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -iconic &
dbus-launch --exit-with-session gnome-session &

chmod u+x ~/.vnc/xstartup
vncserver -localhost no -geometry 800x600 -depth 24

<b>This allows me to connect from a windows machine</b> :thumbsup:

## Issue
Up to this point everything works, and removing "-geometry 800x600 -depth 24" such the command is only "vncserver -localhost no" also works. Removing "-localhost no" results in: <b>"unable connect to socket: Connection refused (10061)"</b> , which makes sense, because only localhost connections are allowed by default?

If I create a config file: <b> nano ~/.vnc/config</b> and place "localhost=no" in the first line, and then saving it, and then only running "vncserver" on the command line, I get the same error.

What is the correct way to create a config file?

**Comment by CendioOssman** [comment]
I'm afraid Debian and Ubuntu have their own `vncserver` script and do not use ours. As such we aren't familiar with the details of how it works so unfortunately we cannot really help you with it.

Please file an issue with Ubuntu. Hopefully they can help you out.
