### ISSUE TITLE
Alt-tab doesn't work  - viewer on Mac, server on Linux

### ISSUE THREAD

**Issue by Jendker** [TigerVNC/tigervnc#953]
**Describe the bug**
Alt-tab (produced by pressing left cmd+tab locally) opens the mac program selection, not on remote.

**Expected behavior**
To find a way to use alt-tab on remote computer.

**Client (please complete the following information):**
 - OS: MacOS 10.15.2
 - VNC client: TigerVNC
 - VNC client version: 1.10.1
 - Client downloaded from: GitHub releases

**Server (please complete the following information):**
 - OS: Ubuntu 18.04.3
 - VNC server: TigerVNC
 - VNC server version: 1.7.0 (provided by apt package)
 - Server downloaded from: my Linux distribution
 - Server was started using: `vncserver :1`

**Additional context**
Relates to https://github.com/TigerVNC/tigervnc/issues/721 but the proposed solution (left cmd + tab) does not work. Using the fullscreen option solves the issue, but it is not convenient if one needs to work on remote and local in parallel.

**Comment by samhed** [comment]
It sounds you're after something along the lines of what's discussed in #2
