### ISSUE TITLE
username/password for Plain SecurityTypes in command-line

### ISSUE THREAD

**Issue by sequencer** [TigerVNC/tigervnc#957]
**Is your feature request related to a problem? Please describe.**
I'm using vncviewer with `vncviewer -SecurityTypes=Plain $host:$port`, server will send me a complex password each time before connection. I need copy/paste it every time. 

**Describe the solution you'd like**
I wanna use a username/password file which is stored in plaintext or directly pass it in command-line.

**Additional context**
I'm using 
```
TigerVNC Viewer 64-bit v1.10.1
Built on: 2019-12-27 09:17
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
```
in Arch Linux

**Comment by CendioOssman** [comment]
Huh? Which server are you using? We don't have any system where new passwords are generated on each connection.

**Comment by sequencer** [comment]
That's a close source remote desktop software.
I reverse that damn Java program and re-implement its client protocol.
I just found the `UserPasswdGetter` is only implemented in `UserDialog`, maybe it can read from environment?

**Comment by bphinz** [comment]
Can you please clearly describe the issue?  You say that the server sends a complex password - how, via email?  It sounds as though your server is configured to use some sort of one time password via PAM, which is not something that the Plain auth handler was designed to accommodate.  Also, which software are you referring to as being closed source?

**Comment by bphinz** [comment]
> which is not something that the Plain auth handler was designed to accommodate

To be clear, I mean that if there is a dialog between the client & server other than just a username & password

**Comment by sequencer** [comment]
I post my credentials to server, server will reply a json embedded with my username and password.
And call invoke realvnc to execute vnc session.
I reimplement that protocol by reverse that Java program, and can get my username and password currently, but when passing it to `vncviewer`, since it only takes vnc password from `passwordFileStr` or start a dialog to ask username and password from user input.

**Comment by sequencer** [comment]
I'm trying to PR a username&password get from env function implemented in 
```
void UserDialog::getUserPasswd(bool secure, char** user, char** password)
```
Is that a good idea?

**Comment by sequencer** [comment]
> You say that the server sends a complex password - how, via email? 

via http post.

> It sounds as though your server is configured to use some sort of one time password via PAM, which is not something that the Plain auth handler was designed to accommodate. 

yes, it function as one time password, but didn't implement in PAM.

> Also, which software are you referring to as being closed source?

A small company's software I have no idea what the name of it, it only contains a jar. Sorry, becasue of the decompile issue, I cannot provide more information about this software.
