### ISSUE TITLE
Resize remote session to the local window doesn't work

### ISSUE THREAD

**Issue by mrbbs** [TigerVNC/tigervnc#960]
I've been installing TigerVNC instead of UltraVNC viewer because of security issues with UltraVNC.
We have installed it already on 3 clients however we fail to have the remote session resized to the local window. Also changing resolution doesn't seem to work. Or the remote window doesn't fit the screen, or the remote window has scroll bars.
We would like a resized remote screen window where we can see the full remote screen.

We are using verison vncviewer64-1.10.80 on Windows 10 Pro v1909

I found several other threads but I'm not sure if this has been fixed already?

https://github.com/TigerVNC/tigervnc/issues/274

Thanks,
Kevin

**Comment by CendioOssman** [comment]
I'm afraid our Windows server currently doesn't support resizing sessions, and as you've found we still haven't implemented any client side scaling. So please keep an eye on #274 for improvements in this area.
