### ISSUE TITLE
Issue with keyboard layouts and conflicting sessions

### ISSUE THREAD

**Issue by danielleontiev** [TigerVNC/tigervnc#962]
My current set up is Ubuntu 16.04 in virtualbox with latest TigerVNC but I also tried Ubuntu 18.04 and Manjaro with Xfce. I use TigerVNC viewer, Remmina viewer and RealVNC viewer on my host machine. My goal is to connect to the system in virtualbox from host machine. Some information:

1) The way I've installed TigerVNC: I've downloaded TigerVNC 1.10.1.x86_64 from the site and moved all the content to `/` with the command `sudo rsync -av tigervnc-1.10.1.x86_64/ /`

2) I've set up systemd unit for VNC server:
```
### /etc/systemd/system/vncserver@.service
[Unit]
Description=Start TigerVNC server at startup
After=syslog.target network.target

[Service]
Type=forking
User=vbox
PAMName=login
PIDFile=/home/vbox/.vnc/%H:%i.pid
ExecStartPre=-/usr/bin/vncserver -kill :%i > /dev/null 2>&1
ExecStart=/usr/bin/vncserver :%i
ExecStop=/usr/bin/vncserver -kill :%i

[Install]
WantedBy=multi-user.target

### sudo systemctl enable vncserver1.service
```

3) I've added some configuration for Xvnc:
```
### /home/vbox/.vnc/config
desktop=myvnc
geometry=1920x1080
alwaysshared
depth=24
dpi=96
```

3) Startup file:
```
### /home/vbox/.vnc/xstartup
#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

xsetroot -solid grey
vncconfig -nowin &
gnome-session &
/usr/lib/x86_64-linux-gnu/unity/unity-panel-service &
unity-settings-daemon &
unity &
```

After reboot I am able to connect to VNC and use computer. But there are some problems:

1) I have two keyboard layouts in my system, us and ru. I am not able to switch them. In fact I can press language switcher in the top panel but it does not do anything. When I start typing it always types English letters. I googled a lot and saw a lot of workarounds like `setxkbmap`, `setxkbmap ru`, `setxkbmap us`, `setxkbmap -model pc105 -layout ru` and so on but it does nothing for me. Letters are English anyway. I've tried for unity on ubuntu 16.04, for gnome in ubuntu 18.04 and for xfce in manjaro. I've also tried different viewers.

2) Scenario:

- Log in as vbox user from virtualbox window
- Launch firefox
- Connect to VNC from host computer
- Trying to launch firefox results in error pop-up from firefox saying that firefox is already started. If I do `killall firefox` and try again it works. But it's strange.

Another similar problem:

- Log in as vbox user from virtualbox window
- Connect to VNC
- Go to settings and do something that triggers appearing of window for entering root password, f.e. change driver settings or add/remove ppa. Sometimes you do that results in nothing but if you return to virtualbox you see that confirmation window appeared there! I think creation special user for vnc could resolve that problem but I do not like this optioin because it creates mess in file privileges I work with.

**Comment by CendioOssman** [comment]
> 1. I have two keyboard layouts in my system, us and ru. I am not able to switch them. In fact I can press language switcher in the top panel but it does not do anything. When I start typing it always types English letters. I googled a lot and saw a lot of workarounds like `setxkbmap`, `setxkbmap ru`, `setxkbmap us`, `setxkbmap -model pc105 -layout ru` and so on but it does nothing for me. Letters are English anyway. I've tried for unity on ubuntu 16.04, for gnome in ubuntu 18.04 and for xfce in manjaro. I've also tried different viewers.

VNC uses a symbols based system rather than a key based one. Practically that means the server layout doesn't matter, only the client layout. So that's why you're not seeing any effect. Switching on the client should work better (note #93 though).

Fortunately there is also an extension that allows switching to a key based system. You can enable it by setting `-RawKeyboard=1` on the server. It requires support in the client though.

> * Trying to launch firefox results in error pop-up from firefox saying that firefox is already started. If I do `killall firefox` and try again it works. But it's strange.

Modern desktops and applications do not support multiple sessions. I'm afraid this is not a bug or limitation in TigerVNC, but in those other systems. You could try filing bugs with them, but I'm afraid they'll likely continue considering multiple sessions unsupported.

**Comment by danielleontiev** [comment]
I've tried `-rawkeyboard` option and it works like a charm.
The second is a bit tricky, maybe I'll return with using another user for VNC or just reboot computer on first VNC connection.

Thank you a lot for given information. It helped me significantly
