### ISSUE TITLE
tigervnc-1.10.1 : Assertion `false' failed for encperf

### ISSUE THREAD

**Issue by fffto** [TigerVNC/tigervnc#967]
Good afternoon.
I use tigervnc-1.10.1 and rfb files from: http://www.turbovnc.org/rfbsessions.tar.bz2
```
# cat /etc/debian_version 
9.9
# uname -m -v
#1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64

```
I run:
```encperf -format = bgr888 -count = 1 -height = 1024 -width = 1280 ./ugnx-01-24.rfb```
And see error:
```
encperf: /fs/root/build/e8c/tigervnc-1.9.80/common/rfb/CConnection.cxx:552:
void rfb::CConnection::resizeFramebuffer(): Assertion `false' failed.
Aborted

```
in version 1.5.0 this error did not occur

**Comment by CendioOssman** [comment]
Thanks. Should be fixed on `master` now.
