### ISSUE TITLE
Inflate in ZlibInStream::decompress() fails if it returns other than Z_OK

### ISSUE THREAD

**Issue by CendioNiko** [TigerVNC/tigervnc#969]
The inflate in ZlibInStream::decompress() can return other values than Z_OK when successfully inflating clipboard messages. The check after inflate() only checks if return value differs from Z_OK and throws exception if it does. THe inflate() can return other (positive) flags that indicate a success, as the errors returned from inflate is negative values this is what should be checked instead. 

1. On client side use the Z_FINISH argument when deflating data to send.
2. Send clipboard message
3. Notice that the server closes connection with the error "ZlibInStream: inflate failed".

**Comment by CendioOssman** [comment]
Fixed in 1688e8cd57606f7aaeb0abddc8e9ce3827d253cc.
