### ISSUE TITLE
1.4.1 vncviewer socket exception

### ISSUE THREAD

**Issue by ha5di** [TigerVNC/tigervnc#97]
vncviewer 1.4.1 gives error message below when connecting:

terminate called after throwing an exception 'network::SocketException'

**Comment by ha5di** [comment]
Same with 1.1.0 and 1.3.1

**Comment by bphinz** [comment]
Hi,

Can you please provide some details (e.g.: what platform are you running
on, did you compile from source or are using the the official release
binaries, specific options in use, etc.)?  I am not able to replicate this
problem generically.

Thanks,
-brian

**Comment by ha5di** [comment]
Hi Brian,

it is compiled from source (1.1.0, 1.3.1 and 1.4.1 with same exception) on Raspberry Pi.

System: piCore 6.0rc1 - http://forum.tinycorelinux.net/index.php/board,57.0.html
glibc 2.20
gcc 4.9.2, binutils 2.25

tigervnc 1.1.0 was OK on piCore 5.x back but doesn't work in current environment which is used to build hundred of apps and the system itself with no errors. 1.1.0 built to disclose issues with Fltk.

AT the moment I'm lost :(

regards... Béla

**Comment by bphinz** [comment]
On Sun, Jan 4, 2015 at 10:16 AM, ha5di <notifications@github.com> wrote:

> Hi Brian,
>
> it is compiled from source (1.1.0, 1.3.1 and 1.4.1 with same exception) on
> Raspberry Pi.
>
> System: piCore 6.0rc1 -
> http://forum.tinycorelinux.net/index.php/board,57.0.html
> glibc 2.20
> gcc 4.9.2, binutils 2.25
>
> tigervnc 1.1.0 was OK on piCore 5.x back but doesn't work in current
> environment which is used to build hundred of apps and the system itself
> with no errors. 1.1.0 built to disclose issues with Fltk.
>
> AT the moment I'm lost :(
>
Can you attach the output from cmake and the file
CMakeFiles/CMakeError.log?  Also, the version of cmake that you are using,
as well as the options that you are providing to cmake would be helpful.

Thanks,
-brian

**Comment by ha5di** [comment]
Brian,

I can provide. However 1.1.0 has the same issue and it is using the GNU tools. Maybe easier to work with.

**Comment by bphinz** [comment]
On Sun, Jan 4, 2015 at 10:45 AM, ha5di <notifications@github.com> wrote:

> Brian,
>
> I can provide. However 1.1.0 has the same issue and it is using the GNU
> tools. Maybe easier to work with.
>
Perhaps, but if 1.1.0 worked on piCore 5.x but not on piCore 6.x then it
suggests to me that something in the piCore environment has changed and the
cmake output will hopefully point that out a little more clearly than the
autotools.

**Comment by ha5di** [comment]
Forgot to mention, cmake is 3.1.0

**Comment by ha5di** [comment]
See cmake output:

http://www.xham.org/cmake_tiger_logs.zip

**Comment by CendioOssman** [comment]
Could you run vncviewer with `-Log *:stderr:100` and attach the log output here?

**Comment by ha5di** [comment]
Built 1.4.2 which works as expected. Issue solved.
