### ISSUE TITLE
Display does not fit with vncviewer window

### ISSUE THREAD

**Issue by ShijiaYan** [TigerVNC/tigervnc#970]
Hi there,

I am using tigervnc with vncviewer command on Mac OS 10.15.2. The display area in my vncviewer window does not quite fit with its actual size (see the screenshot). By actual size I also mean that I need to click into the black area to reach some of the contents on top such as the menu bar. Does anyone know how to solve this? Much appreciated.

![image](https://user-images.githubusercontent.com/45582332/75104276-38596880-55d5-11ea-8b55-b8684fdff88f.png)

**Comment by CendioOssman** [comment]
This doesn't look like a correctly created app bundle. Did you build this yourself or was it downloaded? Do you know how it was built?

(this is also discussed on #959)

**Comment by samhed** [comment]
No response.

**Comment by matlupi** [comment]
Same issue observed on:
- MacOs Catalina 10.15.4
- TigerVNC Viewer 64-bit v1.10.1, Built on: 2019-12-27 18:29 (installed via brew)

**Comment by CendioOssman** [comment]
Since this is a build issue I suggest you report this to the packager of that homebrew package.
