### ISSUE TITLE
Implement TcpListener::TcpListener(int sock)

### ISSUE THREAD

**Issue by LLyronx** [TigerVNC/tigervnc#971]
**Describe the bug**
You just declared `TcpListener::TcpListener(int sock)` in `common/network/tcpsocket.h`, but you didn't implement it, did you?

**Expected behavior**

I hope you could implement it, although you may not use this function. We were confused when there's an empty function without any implementations.

**Comment by CendioOssman** [comment]
That seems to be implemented as far as I can tell. What issue are you seeing?

**Comment by LLyronx** [comment]
I do not think it has been implemented because when I use the function to create an object of TcpListener, it will throw an exception when I use its `accept()` function. On windows, the exception means `10038: An operation was attempted on something that is not a socket`. As far as I am concerned, I see nothing in the implementation of `TcpListener::TcpListener(int sock)` in `common/network/tcpsocket.cxx`

**Comment by bphinz** [comment]
He's right.  I don't think SocketListener has a constructor that takes a
socket as it's input.  Something like this should work though:

TcpListener::TcpListener(int sock) : SocketListener(sock.getFd())
{
}

**Comment by CendioOssman** [comment]
Sure it does. It's here:

https://github.com/TigerVNC/tigervnc/blob/bc1fc22df184dec0ee51df051e8c5d271174b9cd/common/network/Socket.cxx#L128-L132

And `sock` is just an `int`, so you cannot call `getFd()` on it.

The relevant constructor is even in use here:

https://github.com/TigerVNC/tigervnc/blob/bc1fc22df184dec0ee51df051e8c5d271174b9cd/unix/xserver/hw/vnc/vncExtInit.cc#L179

@LLyronx , what does the rest of your code look like? It doesn't sound like you are feeding it a proper file descriptor.

**Comment by LLyronx** [comment]
> Sure it does. It's here:
> 
> https://github.com/TigerVNC/tigervnc/blob/bc1fc22df184dec0ee51df051e8c5d271174b9cd/common/network/Socket.cxx#L128-L132
> 
> And `sock` is just an `int`, so you cannot call `getFd()` on it.
> 
> The relevant constructor is even in use here:
> 
> https://github.com/TigerVNC/tigervnc/blob/bc1fc22df184dec0ee51df051e8c5d271174b9cd/unix/xserver/hw/vnc/vncExtInit.cc#L179
> 
> @LLyronx , what does the rest of your code look like? It doesn't sound like you are feeding it a proper file descriptor.

Yeah, you are right. I thought the parameter is the Socket port so it doesn't work. Now I have changed it to the static function `void createTcpListeners(std::list<SocketListener*> *listeners,
const char *addr, int port);`. Thank you for your suggestions.
