### ISSUE TITLE
x0vncserver manual says it supports `-localhost`

### ISSUE THREAD

**Issue by ScumCoder** [TigerVNC/tigervnc#972]
**Describe the bug**
[Official manual page](https://tigervnc.org/doc/x0vncserver.html) on x0vncserver mentions `-localhost` option.
Trying to supply this option to x0vncserver prevents it from starting, and a boilerplate `Usage:` text is dumped to stderr.

**Expected behavior**
The web page corresponds to the actual list of program's parameters.

**Server (please complete the following information):**
 - OS: openSuSE 15.0
 - VNC server: TigerVNC
 - VNC server version: 1.8.0
 - Server downloaded from: openSUSE repo
 - Server was started using: /usr/bin/x0vncserver -localhost -PasswordFile ~/.vnc/passwd -display :0

**Comment by CendioOssman** [comment]
The documentation on our home page is always for the latest version of TigerVNC, and you are running a very old one. Please upgrade and you'll find that the new flags work correctly.
