### ISSUE TITLE
Installation of the latest version in CENTOS 7

### ISSUE THREAD

**Issue by nweipad** [TigerVNC/tigervnc#975]
CENTOS base repository contains the outdated version 1.8.0 of the program. 
====
repoquery -i tigervnc-server

Name        : tigervnc-server
Version     : 1.8.0
Release     : 17.el7
Architecture: x86_64
Size        : 521156
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Group       : User Interface/X
URL         : http://www.tigervnc.com
Repository  : base
Summary     : A TigerVNC server
Source      : tigervnc-1.8.0-17.el7.src.rpm

====
1) One should inform CENTOS on the availability of a newer version. Or how is it done?
2) How to install the latest version of the server at CENTOS 7? Only by compiling from source code or there are some repositories which already have it?

**Comment by CendioOssman** [comment]
> * One should inform CENTOS on the availability of a newer version. Or how is it done?
> 

Add a bug to Red Hat's bugzilla requesting an upgrade.

> * How to install the latest version of the server at CENTOS 7? Only by compiling from source code or there are some repositories which already have it?

We actually do builds as well for RHEL/CentOS 7. Please check our release page. If you click through to bintray and check the files there you'll find an "el7" folder that contains newer RPMs.
