### ISSUE TITLE
Resize remote session to the local window (enabled by default)

### ISSUE THREAD

**Issue by nathanshearer** [TigerVNC/tigervnc#976]
**Describe the bug**
I have my systems setup with tigervnc to access the xorg screen:
```
Section "Module"
        Load "vnc"
EndSection

Section "Screen"
        Identifier "Default Screen"
        Option "PasswordFile" "/etc/X11/vncpasswd"
EndSection
```
When I access these systems, the default option in VNC Viewer is to resize the remote session to the local window. This ends up cropping the remote session and making it totally unusable until it can be either killed or restarted. There is no mechanism to restore the original resolution or set an explicit resolution in VNC Viewer.

**To Reproduce**
1. connect to a remote vnc server with a smaller screen
2. let VNC resize the remote session
3. You are now unable to access your window controls or the desktop menu.
4. physically go to the remote server and restore the resolution or kill your session and any unsaved worked.

**Expected behavior**
Do not resize the remote session to a smaller resolution by default. Or provide a mechanism to specify the resolution that should be used to recover from this situation.

**Client (please complete the following information):**
 - OS: Gentoo Linux (fully updated with stable packages)
 - VNC client: TigerVNC 1.9.0

**Server (please complete the following information):**
 - OS: Gentoo Linux (fully updated with stable packages)
 - VNC server: TigerVNC Server 1.9.0 xorg module

**Comment by CendioOssman** [comment]
I'm not quite sure what you mean here. Could you give us a screenshot of the problem?

**Comment by samhed** [comment]
No response.
