### ISSUE TITLE
mac tigerVNC viewer cann't connect: "read:com.tigervnc.rdr.Exception"

### ISSUE THREAD

**Issue by lbsfei** [TigerVNC/tigervnc#977]
I used the package VncViewer-1.10.80.jar to connect Windows 10 ,but have an error: as below jpg

more info:
server: tigervnc64-1.10.80.exe
client: VncViewer-1.10.80.jar
![截屏2020-03-12下午6 53 34](https://user-images.githubusercontent.com/12455682/76515585-c7e78e00-6494-11ea-90fe-ca6d44d57903.png)

thanks!

**Comment by CendioOssman** [comment]
That's odd that we're not getting a more specific error message. @bphinz ?

@lbsfei , could you test the native macOS viewer as well and see what it says?

**Comment by lbsfei** [comment]
@CendioOssman 
Just now, i test the native macOS viewer, more info you can see:
![截屏2020-03-13上午9 21 37](https://user-images.githubusercontent.com/12455682/76580908-84c90180-650c-11ea-85d9-723565c302e3.png)

**Comment by CendioOssman** [comment]
Thanks. That looks like the server is closing down the connection for some reason and not a client issue right now.

Do you think you could get some logs from the server? Instructions here:

https://github.com/TigerVNC/tigervnc/wiki/Debug-Logs
