### ISSUE TITLE
"Please install the tigenvnc-common package"

### ISSUE THREAD

**Issue by tom-doerr** [TigerVNC/tigervnc#978]
**Describe the bug**
When I tried to start the tigervnc server I got the following error message:
```
vncserver: Couldn't find "tigervncpasswd" on your PATH.
	Please install the tigenvnc-common package, i.e., sudo apt-get install tigenvnc-common.
```
I solved it by installing `tigervnc-common` instead of `tigenvnc-common`, as suggested.
I suspect `tigenvnc-common` is a typo. 

**To Reproduce**
```
sudo apt install tigervnc-standalone-server tigervnc-viewer 
vncserver
```

**Expected behavior**
I expect to see a message prompting me to install `tigervnc-common` instead of `tigenvnc-common`.

**Server**
 - OS: Linux Mint
 - VNC client: TigerVNC
 - VNC client version: 1.7
 - Client downloaded from: Ubuntu universe/x11

**Comment by samhed** [comment]
That text isn't from us as far as I know. I guess it is apt has its own list?

**Comment by tom-doerr** [comment]
Apparently the bug is already fixed: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881276
