### ISSUE TITLE
Unrecognized option: -pam_service

### ISSUE THREAD

**Issue by mikedep333** [TigerVNC/tigervnc#98]
System: RHEL 7.0 (64-bit)

I launch TigerVNC server via this 1-line script:
`vncserver -autokill -SecurityTypes=VeNCrypt,TLSPlain -PlainUsers=$USER -pam_service login -desktop $HOSTNAME +extension GLX`

With the TigerVNC 1.4.0 x86_64 generic build, that script successfully launches TigerVNC server.

With the TigerVNC 1.4.1 x86_64 generic build, I get this error:
> Unrecognized option: -pam_service

I tried other forms of that argument such as `pam_service=login`.

**Comment by bphinz** [comment]
In my haste to address the Xorg CVEs, I failed to notice some build issues
that resulted from all of the changes I made in updating to Xorg 1.12.
Poor QA on my part...  I've already pushed a patch to my github fork that
addresses all of these issues.  I'm just waiting for Pierre to return to
see how he wants to handle this.

-brian

**Comment by mikedep333** [comment]
Great :+1:

**Comment by CendioOssman** [comment]
Fix now I suppose?

**Comment by mikedep333** [comment]
Yes, it is fixed :+1:
