### ISSUE TITLE
Support VncViewer passing Xauthority cookie to vnc server

### ISSUE THREAD

**Issue by bob333** [TigerVNC/tigervnc#980]
**Is your feature request related to a problem? Please describe.**
In corporate environment the vncsever is setup to use the Xauthority cookie( "-auth /home/user/.Xauthority " )

**Describe the solution you'd like**
Similar to PasswordFile supporting vnc password, required a parameter "XauthorityCookie"

**Comment by CendioOssman** [comment]
Could you describe your use case a bit more? In what way is the current behaviour insufficient?

**Comment by samhed** [comment]
No response.
