### ISSUE TITLE
Video and events recording 

### ISSUE THREAD

**Issue by MarkLTZ** [TigerVNC/tigervnc#982]
Hello,

I think it could be very nice to have a built-in video recorder for sessions and events recording (such as keyboard and mouse events).

These features should be separated:
1. session screen recording on MP4 or similar formats
2. keyboard and mouse event tracers on a structured text files (or binary one with a tool to extract these events in text format)

My opinion is that these  features are really useful for smart-working solutions. In this way, IT admins are able to provide a tool to employees or consultants for accessing to internal servers by VPN and at the same time record everything they do for security reasons. This is a MUST for forensic analysis

Regards,
Mark

**Comment by CendioOssman** [comment]
I'm afraid this is out of scope of this project unless someone is ready to step up and implement this. I'm sure there are several screen recorders out there that will work fine in a TigerVNC session.
