### ISSUE TITLE
Parameter PasswordFile not recognized in default.tigervnc

### ISSUE THREAD

**Issue by conqp** [TigerVNC/tigervnc#983]
**Describe the bug**
Upon connection I get the error:

```
Parameters:  Unknown parameter PasswordFile on line 27 in file
              /home/rne/.vnc/default.tigervnc
```
**To Reproduce**
1. Add a line `PasswordFile=~/.vnc/passwd` to `~/.vnc/default.tigervnc`
2. Connect to a VNC server using vncviewer
3. Get the above error message
4. You have to enter the password manually

**Expected behavior**
1. No error message.
2. The password provided by the configured password file is used.

**Screenshots**
N/A

**Client:**
 - OS: Arch Linux
 - VNC client: TigerVNC (vncviewer)
 - VNC client version: 1.10.1-1
 - Client downloaded from: Official Arch Linux repos

**Server:**
 - OS: Arch Linux
 - VNC server: TigerVNC (x0vncserver)
 - VNC server version: 1.10.1-1
 - Server downloaded from: Official Arch Linux repos
 - Server was started using: systemd (`/usr/bin/x0vncserver -display :0 -passwordfile /var/lib/digsig/vncpasswd`)

**Additional context**
The manual under https://tigervnc.org/doc/vncviewer.html clearly states:

> −passwd, −PasswordFile password-file
> 
> If you are on a filesystem which gives you access to the password file used by the server, you can specify it here to avoid typing it in. It will usually be "~/.vnc/passwd".

as well as

> $HOME/.vnc/default.tigervnc
> 
> Default configuration options. This file must have a "magic" first line of "TigerVNC Configuration file Version 1.0" (without quotes), followed by simple <setting>=<value> pairs of your choosing. The available settings are those shown in this man page.

My configuration file is

```
$ cat ~/.vnc/default.tigervnc 
TigerVNC Configuration file Version 1.0

ServerName=REDACTED
X509CA=
X509CRL=
SecurityTypes=X509Plain,TLSPlain,X509Vnc,TLSVnc,X509None,TLSNone,VncAuth,None
DotWhenNoCursor=1
AutoSelect=1
FullColor=1
LowColorLevel=2
PreferredEncoding=Tight
CustomCompressLevel=0
CompressLevel=2
NoJPEG=0
QualityLevel=8
FullScreen=1
FullScreenAllMonitors=1
DesktopSize=
RemoteResize=1
ViewOnly=0
Shared=0
AcceptClipboard=1
SendClipboard=1
SendPrimary=1
MenuKey=F8
FullscreenSystemKeys=1
PasswordFile=~/.vnc/passwd
```

The actual output is:

```
TigerVNC Viewer 64-bit v1.10.1
Built on: 2019-12-27 09:17
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.

Tue Mar 24 10:21:56 2020
 Parameters:  Unknown parameter PasswordFile on line 27 in file
              /home/rne/.vnc/default.tigervnc
 DecodeManager: Detected 8 CPU core(s)
 DecodeManager: Creating 4 decoder thread(s)
 CConn:       Connected to host 1017.terminals.homeinfo.intra port 5900
 CConnection: Server supports RFB protocol version 3.3
 CConnection: Using RFB protocol version 3.3
 CConn:       Connection failed: Too many security failures
```
I'd then manually have to enter the password.
Beware that the _Connection failed: Too many security failures_ is due to too many aborted connection attempts and is not the issue here.

I was also able to dertermine, that the configuration parameter `PasswordFile` is not listed in `parameterArray` here: https://github.com/TigerVNC/tigervnc/blob/master/vncviewer/parameters.cxx#L159

**Comment by CendioOssman** [comment]
Oops. I wasn't aware we had documented that way. The intention of the code was only to store those things that you can modify in the GUI, to avoid surprises.

I guess we'll have to have another look at this.

**Comment by CendioOssman** [comment]
I see we already had #398 for this. Closing this one as a duplicate.

**Comment by Ville1ero** [comment]
Hi @CendioOssman, it seems that with the #398 "Increase default pointer event interval" was fixed, but the "Parameter PasswordFile not recognized" still missing.

Thanks for your help.

**Comment by Neustradamus** [comment]
@CendioOssman: Any news?

**Comment by cschanzlenist** [comment]
+1 for convenience to have PasswordFile supported in the config file.
