### ISSUE TITLE
Can not copy data from CENTOS-gnome tigervnc-served to tigervnc-client on Win10

### ISSUE THREAD

**Issue by nweipad** [TigerVNC/tigervnc#984]
**Describe the bug**
Direct copy to clipboard from tigervnc on centos7 in ANSYS does not work. I have to copy the data from Ansys (table of numbers) to Knotes in the remote session and then it's working.

**To Reproduce**
Generate any result in ANSYS which gives a column of data. Copy the row of numbers to clipboard. Pasting in Win10 tigervnc client  does  not work, unless I paste these numbers in KNotes and copy it there. Then pasting in Win10 works well.

**Expected behavior**
Copying from ANSYS to shared clipboard should work via Tigervnc.

**Client (please complete the following information):**
 - OS: Win10
 - VNC client: TigerVNC
 - VNC client version: 1.10.1
 - Client downloaded from: official website of Tigervnc

**Server (please complete the following information):**
 - OS: Centos 7 + standard Gnome
 - VNC server: TigerVNC
 - VNC server version: 1.10.1
 - Server downloaded from: official website of Tigervnc
 - Server was started using: vncserver

**Additional context**
Ansys is started via the shortcut on the desktop with a line: "Exec=/ansys_inc/ANSYS_main_launcher.sh" .  This script contains the lines: "export VGL_SPOILLAST=0" and "vglrun ./home/ansys/v201/Framework/bin/Linux64/runwb2"

**Similar to last message here: https://github.com/TigerVNC/tigervnc/issues/520**

**Comment by CendioOssman** [comment]
Have you checked the logs on the client and server for any errors?

You can turn up the logging on the server by adding `-Log Selection:stderr:100` to Xvnc's command line.

**Comment by samhed** [comment]
Did you get a chance to look at the logs @nweipad?

**Comment by nweipad** [comment]
Thank for you a reminder. The log is attached below.

`Sat Apr  4 22:00:11 2020   - @@ Copying with Ctrl-C a row in a table in ANSYS 2020 R1 (server). In client Win10 - pasting - nothing is out. No success
 VNCSConnST:  Key pressed: 0x76 / 0x2f
 Input:       keycode 55 down
 Selection:   Selection owner change for CLIPBOARD
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection notification for CLIPBOARD (target TARGETS, property
              TARGETS, type TARGETS)
 VNCSConnST:  Key released: 0x76 / 0x2f
 Input:       keycode 55 up
 VNCSConnST:  Key released: 0xffe3 / 0x1d
 Input:       keycode 37 up

Sat Apr  4 22:00:14 2020 @@ On server pushing Ctrl-V in KNotes (like notepad in Windows). Select in Knotes and Ctrl-C again and paste in Win10. Success.
 Selection:   Selection owner change for PRIMARY
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for PRIMARY selection
 Selection:   Selection notification for PRIMARY (target TARGETS, property
              TARGETS, type ATOM)
 Selection:   Compatible format found, notifying clients
 Selection:   Got request for local clipboard, re-probing formats
 Selection:   Requesting TARGETS for PRIMARY selection
 Selection:   Selection notification for PRIMARY (target TARGETS, property
              TARGETS, type ATOM)
 Selection:   Requesting UTF8_STRING for PRIMARY selection
 Selection:   Selection notification for PRIMARY (target UTF8_STRING, property
              UTF8_STRING, type UTF8_STRING)
 Selection:   Sending clipboard to clients (15 bytes)
 VNCSConnST:  Key pressed: 0xffe3 / 0x1d
 Input:       keycode 37 down

Sat Apr  4 22:00:15 2020
 VNCSConnST:  Key pressed: 0x63 / 0x2e
 Input:       keycode 54 down
 Selection:   Selection owner change for CLIPBOARD
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection notification for CLIPBOARD (target TARGETS, property
              TARGETS, type ATOM)
 Selection:   Compatible format found, notifying clients
 Selection:   Got request for local clipboard, re-probing formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection notification for CLIPBOARD (target TARGETS, property
              TARGETS, type ATOM)
 Selection:   Requesting UTF8_STRING for CLIPBOARD selection
 Selection:   Selection notification for CLIPBOARD (target UTF8_STRING,
              property UTF8_STRING, type UTF8_STRING)
 Selection:   Sending clipboard to clients (15 bytes)
 VNCSConnST:  Key released: 0x63 / 0x2e
 Input:       keycode 54 up
 VNCSConnST:  Key released: 0xffe3 / 0x1d
 Input:       keycode 37 up

Sat Apr  4 22:02:21 2020 @@ Trying again to copy a table in ANSYS 2020 R1 (on server) and pasting in Win10 (client). No success.
 VNCSConnST:  Key pressed: 0xffe3 / 0x1d
 Input:       keycode 37 down
 VNCSConnST:  Key pressed: 0x63 / 0x2e
 Input:       keycode 54 down
 Selection:   Local clipboard lost, notifying clients
 Selection:   Selection owner change for CLIPBOARD
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection owner change for CLIPBOARD
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection owner change for CLIPBOARD
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection owner change for CLIPBOARD
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection owner change for CLIPBOARD
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection owner change for CLIPBOARD
 Selection:   Got clipboard notification, probing for formats
 Selection:   Requesting TARGETS for CLIPBOARD selection
 Selection:   Selection notification for CLIPBOARD (target TARGETS, property
              TARGETS, type TARGETS)
 Selection:   Selection notification for CLIPBOARD (target TARGETS, property
              TARGETS, type TARGETS)
 Selection:   Selection notification for CLIPBOARD (target TARGETS, property
              TARGETS, type TARGETS)
 Selection:   Selection notification for CLIPBOARD (target TARGETS, property
              TARGETS, type TARGETS)
 Selection:   Selection notification for CLIPBOARD (target TARGETS, property
              TARGETS, type TARGETS)

Sat Apr  4 22:02:22 2020
 VNCSConnST:  Key released: 0x63 / 0x2e
 Input:       keycode 54 up
 VNCSConnST:  Key released: 0xffe3 / 0x1d
 Input:       keycode 37 up

`

**Comment by samhed** [comment]
Okay, nothing noteworthy there, perhaps the issue is on the Windows client side. What does the viewer logs say?

**Comment by nweipad** [comment]
```
Mon Apr 06 11:30:59 2020   # copy paste from server-CENTOS-ANSYS 2020 R1 to client Win10. Fail.
 Viewport:    Key pressed: 0x001d => 0xffe3

Mon Apr 06 11:31:00 2020
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x002e => 0x0063
 Viewport:    Key released: 0x002e => 0x0063
 Viewport:    Key released: 0x001d => 0xffe3

Mon Apr 06 11:31:46 2020   # on server-CENTOS copy from ANSYS 2020 R1 and paste to KNotes, then copy to clipboard and on client Win10 paste. Success.
 Viewport:    Key pressed: 0x001d => 0xffe3
 Viewport:    Key pressed: 0x002f => 0x0076
 Viewport:    Key released: 0x002f => 0x0076

Mon Apr 06 11:31:47 2020
 Viewport:    Key pressed: 0x001e => 0x0061
 Viewport:    Key released: 0x001e => 0x0061

Mon Apr 06 11:31:48 2020
 Viewport:    Key pressed: 0x002e => 0x0063
 Viewport:    Got notification of new clipboard on server
 Viewport:    Key released: 0x002e => 0x0063
 Viewport:    Key released: 0x001d => 0xffe3
 Viewport:    Got clipboard data (15 bytes)
```

**Comment by CendioOssman** [comment]
The bug is actually here:

>  Selection:   Selection notification for CLIPBOARD (target TARGETS, property
>               TARGETS, type TARGETS)

Ansys is setting an invalid type here. Compare with KNotes:

>  Selection:   Selection notification for CLIPBOARD (target TARGETS, property
>               TARGETS, type ATOM)

This is in violation of the clipboard specification.

Can you do your own builds? Please test what happens if you comment out these two lines:

https://github.com/TigerVNC/tigervnc/blob/9a330f9865787d5f7957ada92fda4375c43f114a/unix/xserver/hw/vnc/vncSelection.c#L508-L509

**Comment by CendioOssman** [comment]
No response. Closing.
