### ISSUE TITLE
“TigerVNC Viewer 1.4.3.app” needs to be updated.

### ISSUE THREAD

**Issue by mlee03** [TigerVNC/tigervnc#985]
I have downloaded TigerVNC-1.4.3.dmg on macOS Catalina Version 10.15.4 and I get the following popup message:

"“TigerVNC Viewer 1.4.3.app” needs to be updated.
The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information."

Is there anything I can do get TigerVNC running?  

Thank you! 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC client: [e.g. TigerVNC, or UltraVNC]
 - VNC client version: [e.g. 1.8.0]
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC server: [e.g. TigerVNC, or UltraVNC]
 - VNC server version: [e.g. 1.8.0]
 - Server downloaded from: [e.g. my Linux distribution]
 - Server was started using: [e.g. `vncserver`]

**Additional context**

**Comment by LicoMonch** [comment]
your version is from ancient times, long before the year 0 BC (read: "Before Corona" 👍 :-D)

you can get the latest release here: 

- https://bintray.com/tigervnc/stable/tigervnc/1.10.1

direct link for your OS:

- https://bintray.com/tigervnc/stable/download_file?file_path=TigerVNC-1.10.1.dmg

**Comment by mlee03** [comment]
Awesome, works perfectly now, thank you!
Stay safe!
