### ISSUE TITLE
Authentication failure: Out of memory

### ISSUE THREAD

**Issue by burkett123** [TigerVNC/tigervnc#988]
Fedora 31, 
dnf list tiger*
Last metadata expiration check: 2:01:07 ago on Wed 01 Apr 2020 07:57:44 AM CDT.
Installed Packages
tigervnc.x86_64                             1.10.1-2.fc31               @updates
tigervnc-icons.noarch                       1.10.1-2.fc31               @updates
tigervnc-license.noarch                     1.10.1-2.fc31               @updates
tigervnc-server-minimal.x86_64              1.10.1-2.fc31               @updates

I see that there's a patch applied for this, dbad687, Dec 30, 2019.  As I understand this is after the 1.10.1 release.  
Is it time for a 1.10.2 release? 
Thanks.

**Comment by CendioOssman** [comment]
We're aiming for a 1.11.0 soonish. We have some development projects we want to wrap up first.

Since this is a Fedora package you can always request that they add this fix until a new release is out.
