### ISSUE TITLE
Password length not validated correctly

### ISSUE THREAD

**Issue by bryonbaker** [TigerVNC/tigervnc#989]
**Describe the bug**
It is possible to log into VNC Server with an incorrect password. The password is only being matched so if you type the correct password plus any random characters you can still log on.

**To Reproduce**
1. Configure a user password with vncpassword. Use password "password"
2. Log on with any VNCviewer and enter "password12345"
3. You are able to establish a session.

**Expected behavior**
Invalid password should be displayed.

**Screenshots**
N/A

**Client (please complete the following information):**
 - OS: Fedora 31
 - VNC client: TigerVNC on Fedora, or VNC Viewer on macOS
 - VNC client version: 
 - Client downloaded from: [e.g. my Linux distribution]

**Server (please complete the following information):**
 - OS: [e.g. Windows 8.1]
 - VNC server: [e.g. TigerVNC, or UltraVNC]
 - VNC server version: 1.10.1
 - Server downloaded from: Fedora rpm
 - Server was started using: vncserver`

**Additional context**

**Comment by samhed** [comment]
That's a known flaw/limitation of using VNC password authentication. Our documentation says:

> only the first eight characters are significant

It's found here: https://tigervnc.org/doc/vncpasswd.html

**Comment by CendioOssman** [comment]
We could warn the user though, see #370.
