### ISSUE TITLE
Work around for conflicting proptietary X drivers

### ISSUE THREAD

**Issue by rolffokkens** [TigerVNC/tigervnc#99]
This might be related to: https://github.com/TigerVNC/tigervnc/issues/95
This is about a solution/workaround though.

The issue is the fact that (on Fedora anyway) the nvidia closed source driver as installed from rpmfusion 'activates' the nvidia driver module (.so) on the search path by configuring ld.so. This works fine for local hardware displays, but not for Xvnc servers.

More details: https://bugzilla.redhat.com/show_bug.cgi?id=1178566

Not being an expert on either, but still looking forward to a solution, I'd like to share some thoughts:

I guess that the best solution would be to specify a specific LD_LIBRARY_PATH per display prior to starting the X server in which case the nvidia driver could be 'activated' by specifying the right LD_LIBRARY_PATH.

An alternative would be to put an LD_LIBRARY_PATH setting in the vncserver perl script specificall specifying /usr/lib so the standard libGL.so would be linked. This would be a workaround (not a true solution) but it would be an easy fix.

**Comment by CendioOssman** [comment]
No, providing LD_LIBRARY_PATH overrides the system ld.so conf and might have all kinds of unintended effects. I'm afraid this is an incompatibility between Nvidia and Xorg/Mesa and not something TigerVNC specific. So I'm going to have to direct you to file a bug with either of them for this issue.
