### ISSUE TITLE
Cannot send the insert key from macOS viewer

### ISSUE THREAD

**Issue by vleonbonnet** [TigerVNC/tigervnc#990]
**Describe the bug**

The macOS viewer sends the Help key instead of the insert key.

See https://github.com/TigerVNC/tigervnc/blob/master/vncviewer/cocoa.mm#L325

**To Reproduce**
1. Open macOS viewer
2. Connect to linux server
3. open `xev` on remote endpoint
4. Press insert key on local macOS
5. observe wrong key press: `keysym 0xff6a, Help`

**Expected behavior**

The Insert key should be sent over VNC.

**Client:**
 - OS: macOS 10.15.3
 - VNC client: TigerVNC
 - VNC client version: 1.10.80

**Server:**
 - OS: slackware 14.2
 - VNC server: TigerVNC
 - VNC server version: 1.9.0
 - Server downloaded from: my Linux distribution]
 - Server was started using: `vncserver`

**Comment by CendioOssman** [comment]
I'm afraid this isn't as simple as saying that this is the wrong key. In macOS that key isn't the Insert key, so sending it is also wrong and I really don't want to open the whole discussion of sending what's printed on the key or not.

Have you tried enabling `RawKeyboard` on the server? That ignores all keyboard layout stuff and just sends the physical key presses straight through to the server.

**Comment by vleonbonnet** [comment]
Yes, I tried running the server with `RawKeyboard` but that did not seem to change the key detected by the server (which is now running version 1.10.0).

For now I am usring a workaround with `xmodmap -e "keycode 146 = Insert"`, which remaps the Help key to Insert on the server side.

With regard to the macOS client, I am not actually pressing a key that says "Insert" but instead am generating the keypress with Karabiner-Elements (which is able to distinguish between Insert vs Help). So, I think ideally TigerVNC should simply send the key it received (Help or Insert) and no try to map one to the other.

**Comment by CendioOssman** [comment]
Ah. The physical key map we have also maps that key to the Help key rather than the Insert key, so that's why you're getting keycode 146. It would seem the [keycodemapdb](https://gitlab.com/keycodemap/keycodemapdb) project has made the same choice we have. The fact that `xmodmap` works indicates that `RawKeyboard` is active though as any such changes are otherwise ignored.

As far as we know macOS doesn't have any codes for Insert. Karbiner-Elements might just consider Insert to be an alias for Help? I'll try to install it here and see what I can find out.

**Comment by CendioOssman** [comment]
I got Karbiner-Elements installed here, but unfortunately I could not configure it to generate Insert. In the gui I added an entry with "help" in the "from" field and "insert" in the "to" field. I then tried using "vi" locally and pressing the Help key did nothing.

Could you share how you have configured things and tested them?

**Comment by vleonbonnet** [comment]
This is my `Karabiner-Elements` configuration (`~/.config/karabiner/karabiner.json`):

```
"rules": [
    {
        "description": "Change fn + i to insert",
        "manipulators": [
            {
                "from": {
                    "key_code": "i",
                    "modifiers": {
                        "mandatory": [
                            "fn"
                        ],
                        "optional": [
                            "any"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "insert"
                    }
                ],
                "type": "basic"
            }
        ]
    },
    {
        "description": "Change fn + h to help",
        "manipulators": [
            {
                "from": {
                    "key_code": "h",
                    "modifiers": {
                        "mandatory": [
                            "fn"
                        ],
                        "optional": [
                            "any"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "help"
                    }
                ],
                "type": "basic"
            }
        ]
    }
]
```

Launching the `EventViewer` from Karabiner-Elements shows that the two events are different:

```
type:key_down        code:65538      name:fn              misc:flags: fn 
type:key_up          code:65538      name:fn              misc:
type:key_down        code:73         name:insert          misc:
type:key_up          code:73         name:insert          misc:
type:key_down        code:65538      name:fn              misc:flags: fn 
type:key_up          code:65538      name:fn              misc:
type:key_down        code:117        name:help            misc:
type:key_up          code:117        name:help            misc:
```

Running `xev` on the server shows that it is receiving the same keycodes:

```
KeyPress event, serial 36, synthetic NO, window 0x1600001,
    root 0x268, subw 0x0, time 2659668449, (625,462), root:(626,463),
    state 0x0, keycode 146 (keysym 0xff63, Insert), same_screen YES,
    XKeysymToKeycode returns keycode: 118
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x1600001,
    root 0x268, subw 0x0, time 2659668486, (625,462), root:(626,463),
    state 0x0, keycode 146 (keysym 0xff63, Insert), same_screen YES,
    XKeysymToKeycode returns keycode: 118
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 36, synthetic NO, window 0x1600001,
    root 0x268, subw 0x0, time 2659669097, (625,462), root:(626,463),
    state 0x0, keycode 146 (keysym 0xff63, Insert), same_screen YES,
    XKeysymToKeycode returns keycode: 118
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False
              
KeyRelease event, serial 36, synthetic NO, window 0x1600001,
    root 0x268, subw 0x0, time 2659669139, (625,462), root:(626,463),
    state 0x0, keycode 146 (keysym 0xff63, Insert), same_screen YES,
    XKeysymToKeycode returns keycode: 118
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by CendioOssman** [comment]
Thank you, I can see how Karbiner is supposed to work now.

Unfortunately it doesn't really change much. Karbiner is using PC terminology, so what it labels "Insert" is what macOS considers "Help", so that's why you're still getting a "Help" event. The button labeled "Help" in Karbiner is an entirely different key which hasn't appeared on any macOS keyboards to my knowledge. macOS still seems to support it though as it is still reported to the applications. Unfortunately it uses the exact same code as the other key.

Karbiner's event viewer is reporting on low level kernel events and not on what applications receive, so that's why it is able to differentiate between the keys.

So for now we'll keep the existing behaviour as AFAICT Insert still isn't really supported by macOS.

**Comment by vleonbonnet** [comment]
Thanks for digging into this. Very appreciated.
