### ISSUE TITLE
How to stop the server in Ubuntu 18?

### ISSUE THREAD

**Issue by jlsam** [TigerVNC/tigervnc#994]
I installed the nightly build recommended in the Issue https://github.com/TigerVNC/tigervnc/issues/668 in Xubuntu 18.04 and I managed to successfully start the server with a systemd service file created using the template and instructions at /lib/systemd/system/vncserver@.service.

However I'm not sure what would be the best way to stop the server... the template is missing an ExecStop setting and the classic `vncserver -kill :1` is not available:

> $ vncserver -kill :1
> Command 'vncserver' not found, did you mean:
>  command 'vnc4server' from deb vnc4server
> Try: sudo apt install <deb name>

Also, the binary called to start the server, vncsession-start. doesn't seem to be able to stop the server (would be odd with this name), and I also couldn't find a flag to stop the server with the other binaries packaged in the .deb.

Can you provide a suitable example for systemd, for both stopping and reloading? Thanks.

**Comment by CendioOssman** [comment]
Simply use the standard service commands. E.g. `systemctl stop vncserver@:1`.

**Comment by jlsam** [comment]
Yes, but the template at `/lib/systemd/system/vncserver@.service`

```
[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
ExecStart=/usr/lib/x86_64-linux-gnu/vncsession-start %i
PIDFile=/var/run/vncsession-%i.pid
SELinuxContext=system_u:system_r:vnc_session_t:s0

[Install]
WantedBy=multi-user.target
```
does not include an `ExecStop=` instruction. 

https://www.freedesktop.org/software/systemd/man/systemd.service.html indicates that 

> Use of this setting is optional. [...] If this option is not specified, the process is terminated by sending the signal specified in KillSignal= or RestartKillSignal= when service stop is requested.

Should the service file include a `KillSignal=` or `RestartKillSignal=` instruction, then?

**Comment by CendioOssman** [comment]
No, that is not needed:

> KillSignal=
>
>    Specifies which signal to use when stopping a service. This controls the signal that is sent as first step of shutting down a unit (see above), and is usually followed by SIGKILL (see above and below). For a list of valid signals, see signal(7). Defaults to SIGTERM.
